### PR TITLE
Chore/refactor smart swap modal

### PR DESCRIPTION
**Pull request by infiniteflower**
## Explanation

This PR resolves [MMS-520](https://consensyssoftware.atlassian.net/browse/MMS-520):

1. Updates the Smart Transaction popover to use the new components from the Component Library and values from the Design System. 
2. The component was converted to TS for better typing. 
3. A Storybook story was added for ease of testing and development.

### Before

image-20230727-124737

### After

Screenshot 2023-07-27 at 4 10 47 PM

## Manual Testing Steps

1. Wipe your MM data by reinstalling the extension
4. Navigate to the Swaps screen
5. Observe modal popping up
6. Accept or reject the Smart Tx 
7. Click the Settings in Swaps
8. Observe that your Accept/Reject was properly set for Smart Tx

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [x] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Comment by infiniteflower** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by brad-decker — DISMISSED** [review]
😍

**Review by darkwing — DISMISSED** [review]
Thank you for removing the downward animation as well!

**Review by brad-decker — APPROVED** [review]

**Review by dan437 — APPROVED** [review]
Looks good!

**Pull request merged**
