### PR TITLE
tx utils - detect estimateGas err and set simulationFailed

### LINKED ISSUE #1812: eth_estimateGas throws "Transaction execution error."
This looks similar to #1628 although it's happening when I try to call a function of my contract.

Browser: Chome 59.0.3071.115 running on GNU/Lunix Ubuntu 17.04
Metamask: 3.9.0 
Solidity contract source: https://etherscan.io/address/0x1aFdbFde88Bd0189cb0479d309b3794e99E3d53F#code

### Expected Behaviour

When I'm calling my contract's `closeLong()` function using web3, I would expect the MataMask dialog  to show where I can choose my gas and approve the transaction.

You can try here https://www.ethhodler.org/bancor/ and click "Sell BNT" to see what happens.

### Actual Behaviour:

Metamask does not pop up. After a second, the console for the extension shows the following error:

```
InternalError {message: "Transaction execution error.", code: -32603}
code
:
-32603
message
:
"Transaction execution error."

```

Further more, it seems that the background Metamask process goes into a loop and starts hitting the `https://mainnet.infura.io/metamask` servers hard over and over again (~240 requests per minute). This continues until I close the page.

I've checked to make sure the ABI is correct.

I've isolated the problem to just one line on the contract. It happens on line 175 on here https://etherscan.io/address/0x1aFdbFde88Bd0189cb0479d309b3794e99E3d53F#code (as you can see all other lines are commented out. What's funny is that the `long()` function calls the same code with different args, but it works OK)

Again, testing page is here https://www.ethhodler.org/bancor/ - the "Sell BNT" button is causing the problem.

Would be happy to put a 1 ETH bounty on this bug if it can be fixed, or someone knows the solution/workaround. Thanks.

### PR DESCRIPTION
**Pull request by kumavis**
Fixes #1812

### CODE REVIEW

**Comment by frankiebee** [comment]
I would not consider this a full fix for that issue with out a little more explanation as to how it fixes it. 
- Consider some form of display to the user that simulationFailed 
and 
>  Same behavior where it starts hitting the RPC provider on loop
from that issue ^
was this reproducible?  if so how does this fix that?

>Metamask does not pop up. After a second, the console for the extension shows the following error: ...
does the popup now open even if it's a failed simulation or is it still a "silent" fail?

**Comment by kumavis** [comment]
> Consider some form of display to the user that simulationFailed

we actually already have that! but we stopped setting the `simulationFailed` flag

**Comment by kumavis** [comment]
> Metamask does not pop up. After a second, the console for the extension shows the following error: 

yeah just confirmed it does now

tthe ui shows "Transaction Error. Exception thrown in contract code."

**Review by tmashuang — APPROVED** [review]
Approved verbally 👍

**Pull request merged**
