### PR TITLE
17873 ledger instruction banner

### LINKED ISSUE #17873: Update LedgerInstructionField to use BannerAlert
### Description
Currently the `LedgerInstructionField` is using the old banner style. Seeing it next to the new `BannerAlert` creates inconsistencies. It would be great to update it to use `BannerAlert` 

### Before
Screenshot 2023-02-22 at 5 10 33 PM

### After

Screenshot 2023-02-22 at 5 44 59 PM

### Technical Details
- Update `LedgerInstructionField` to use the [BannerAlert](https://metamask.github.io/metamask-storybook/?path=/docs/components-componentlibrary-banneralert--default-story#banneralert) component 
- Create a story in storybook using the below code

```
import React from 'react';
import LedgerInstructionField from '.';

export default {
  title: 'Components/App/LedgerInstructionField',
  argTypes: {
    showDataInstruction: {
      control: {
        type: 'boolean',
      },
    },
  },
};

export const DefaultStory = (args) => <LedgerInstructionField {...args} />;

DefaultStory.storyName = 'Default';
```

Rough JSX markup without local functions or conditionals, if you have a design contact I would suggest checking with them 🙇 

```
<Box display={DISPLAY.FLEX} flexDirection={FLEX_DIRECTION.COLUMN} gap={3}>
      <BannerAlert severity={SEVERITIES.DANGER}>
        Cannot connect to Ledger device. Please make sure your device is
        unlocked and Ethereum app is opened.
      </BannerAlert>
      <BannerAlert
        {...args}
        severity={SEVERITIES.INFO}
        actionButtonLabel="Close any other software connected to your device and then click here to refresh."
      >
        <Text>Prior to clicking confirm:</Text>
        <ul>
          <Text variant={TextVariant.bodySm} as="li">
            - Enable Use Ledger Live under Settings > Advanced
          </Text>
          <Text variant={TextVariant.bodySm} as="li">
            - Open and unlock Ledger Live App
          </Text>
          <Text variant={TextVariant.bodySm} as="li">
            - Plug in your Ledger device and select the Ethereum app
          </Text>
          <Text variant={TextVariant.bodySm} as="li">
            - Enable "smart contract data" or "blind signing" on your Ledger
            device
          </Text>
        </ul>
      </BannerAlert>
    </Box>
```

### Acceptance Criteria
- `LedgerInstructionField` looks similar to other notificaitons

### PR DESCRIPTION
**Pull request by flexa-rob**
## Explanation

Currently the LedgerInstructionField is using the old banner style. Seeing it next to the new BannerAlert creates inconsistencies. It would be great to update it to use BannerAlert

### Before

image

### After

image

image

## Manual Testing Steps

Sign data using the E2E Test Dapp:

1. Open the E2E Test Dapp (https://metamask.github.io/test-dapp/) using a Ledger account
2. Click the "Personal Sign" option
3. The Ledger Instructions Field component should appear above the action buttons

Styling can also be viewed via the storybook using the new Components / App / LedgerInstructionField component.

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Review by georgewrmarshall — CHANGES_REQUESTED** [review]
Nice work! We can take this a little further and replace 
```
import Typography from '../../ui/typography/typography';
import Button from '../../ui/button';
```
With
```
import { BannerAlert, Text, ButtonLink } from '../../component-library';
```

Then this piece can be update to
```
const renderInstructionStep = (
  text,
  show = true,
  color = TextColor.textDefault,
) => {
  return (
    show && (
      <Text color={color} as="h6">
        {text}
      </Text>
    )
  );
};
```

and update all
```
 <Button type="link"
```
with
```
<ButtonLink
```

Screenshot of git diff 

Screenshot 2023-03-02 at 4 51 08 PM
Screenshot 2023-03-02 at 4 51 17 PM

**Comment by georgewrmarshall** [comment]
Screenshot 2023-03-02 at 4 52 24 PM

**Comment by flexa-rob** [comment]
> Screenshot 2023-03-02 at 4 52 24 PM

No problem @georgewrmarshall  - done

**Review by georgewrmarshall — DISMISSED** [review]
LGTM! 🚀 Nice work!

**Review by georgewrmarshall — DISMISSED** [review]

**Comment by SaraCheikh** [comment]
hello @flexa-rob, this looks good! some small details:
-We can left align the action to be consistent with the alignment in the component
-Some small copy suggestions based on @coreyjanssen feedback on [this file](https://www.figma.com/file/C9K6IjSkZTZLdMSREV38NS/Bug-17630-silent-ledger-failures?node-id=1%3A2356&t=0YVJSqGv4U9GvW8J-1). @coreyjanssen I reduced the amount of works we use in the action, feel free to suggest changes. 

Screenshot 2023-03-09 at 11 38 36

**Comment by flexa-rob** [comment]
> hello @flexa-rob, this looks good! some small details: -We can left align the action to be consistent with the alignment in the component -Some small copy suggestions based on @coreyjanssen feedback on [this file](https://www.figma.com/file/C9K6IjSkZTZLdMSREV38NS/Bug-17630-silent-ledger-failures?node-id=1%3A2356&t=0YVJSqGv4U9GvW8J-1). @coreyjanssen I reduced the amount of works we use in the action, feel free to suggest changes.
> 
> Screenshot 2023-03-09 at 11 38 36

Thanks @SaraCheikh - I've updated the alignment and copy. Screenshots in the description above have been updated to reflect these changes.

**Review by georgewrmarshall — APPROVED** [review]

**Review by georgewrmarshall — DISMISSED** [review]
UI approved

**Review by georgewrmarshall — DISMISSED** [review]

**Review by georgewrmarshall — DISMISSED** [review]

**Review by georgewrmarshall — APPROVED** [review]

**Comment by flexa-rob** [comment]
> Nice update!

Thanks @bschorchit :smiley: 

Is there any chance I can get a 2nd approval for this one, so it can be merged?

**Review by digiwand — APPROVED** [review]

**Pull request merged**
