### PR TITLE
feat(MMPD-554): Automatically switch to account initiating a transactions when a user is on a different account

### PR DESCRIPTION
**Pull request by GuiBibeau**
## Explanation

Currently, if a dapp is connected to a different account than the one a user has selected, sending transactions provides a minimal amount of information. Only a single warning is shown. This is inconvenient for users since going back to the extension to check on the transaction, leaves it nowhere to be seen unless they switch to the account manually.

This now makes it so that the extension will automatically switch to the proper account, allowing users a faster flow and easier integration with dapps.

Link to Portfolio ticket (internal MM) https://consensyssoftware.atlassian.net/browse/MMPD-554

## Screenshots/Screencaps

mmpd-554

## Manual Testing Steps

1. Connect account 1 to a dapp
1. switch to a different account in extension (ex: Account 2
1.start from the dapp any transaction such as transfer, spending approval or contract interaction
1. Approve transaction 
1. open extension, expect to see the different account now selected

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [x] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Comment by GuiBibeau** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by brad-decker** [comment]
Hmm... @jpuri @mcmire (sorry not sure who else to tag here) does this have any implications on multi-network efforts. I know this is account based, not network based, but wouldn't there be a possibility for some accounts to exist only on certain networks? Just making sure this behavior would not result in any negative effects downstream or be a jarring experience (not that the current one is good, just want to source opinions and make sure there is buy-in before I put a seal of approval on it)

**Review by danjm — CHANGES_REQUESTED** [review]
I'm not sure what the impact of this is. Needs some amount of careful consideration. Should dapps just be able to switch users accounts by proposing a transaction?

Putting requests changes and a do not merge label until we can think this through

**Comment by bschorchit** [comment]
> Should dapps just be able to switch users accounts by proposing a transaction?
Definitely not by proposing. If the user approves the transaction (which seems like the flow in the giphy/video), it can be considered. But I agree it needs more careful consideration.

**Comment by bschorchit** [comment]
@GuiBibeau is this an issue users were facing in portfolio? Do you have more details on it? I don't have access to the Jira link, but will try to get access.

@cryptotavares maybe result pages could be an alternative solution here?

**Comment by GuiBibeau** [comment]
@bschorchit, we're presently grappling with an issue where dApps have the capability to initiate transactions from accounts that aren't actively selected by users. This can create confusion, as users might be left wondering about the whereabouts of their transaction worth $1000, for instance. Let's consider the following frequently occurring use case scenario:

1. The user links account A with the dApp.
2. Without connecting account B, the user switches over to it within the dApp.
3. The user then initiates a transaction on the dApp.
4. Although the user approves the transaction for account A in the dApp, they are redirected to account B post-approval, hence missing sight of their transaction.

From a dApp's perspective, this is particularly inconvenient for several reasons:

-It is impossible for a dApp to reflect the current state of the extension, primarily because there is no message emitted from the provider signaling, "User connected to a non-authorized account."
-To eliminate the above confusion, we would have to disable our transaction buttons and request the user to switch their wallet. However, we cannot initiate this action programmatically on the dApp side.


I will be happy to implement a final solution we can agree upon. Our current solution, while not perfect, does offer the advantage of being low impact and easily reversible. This flexibility allows us to address this longstanding UX issue promptly rather than allowing it to persist.

**Pull request closed without merging**
