### PR TITLE
E2e beta tests upgrade

### PR DESCRIPTION
**Pull request by danjm**
Same as https://github.com/MetaMask/metamask-extension/pull/4546, but with a cleaner commit history

### CODE REVIEW

**Review by whymarrh — COMMENTED** [review]
I'm might be missing it, where are we using `http://localhost:8080` in the tests?

(Also, small thing, would it be possible to use an http package that isn't v0, e.g. [superstatic](https://npmjs.org/package/superstatic) or similar?)

**Comment by danjm** [comment]
>I'm might be missing it, where are we using http://localhost:8080 in the tests?

https://github.com/MetaMask/metamask-extension/pull/4678/files#diff-b00929238ad0453812af55a40336e889R449

**Comment by danjm** [comment]
> (Also, small thing, would it be possible to use an http package that isn't v0, e.g. superstatic or similar?)

Switched to superstatic in f824a298

**Review by whymarrh — APPROVED** [review]
LGTM, I'm happy to see more (stable) tests 👍

**Pull request merged**
