### PR TITLE
A Tale Of Sourcemaps and Sentries

### LINKED ISSUE #3701: Sentry - Make source maps work
see if we can get sentry to load source maps from a different/remote source

### LINKED ISSUE #3702: Build - Generate source maps for prod, but don't include in release
This is useful for uploading to Sentry

### PR DESCRIPTION
**Pull request by kumavis**
Make Sentry setup better:
- de-vendorize sentry reporter `raven-js`
- always generate sourcemaps, including prod (not included in build .zip)
- when reporting to sentry, rewrite urls for a cross-platform consistency
- introduce npm scripts for uploading source maps to sentry

Includes https://github.com/MetaMask/metamask-extension/pull/3707
Fixes #3702
Fixes #3701

### CODE REVIEW

**Comment by kumavis** [comment]
fixed

**Comment by kumavis** [comment]
after building prod to publishing, you can run `npm run sentry` and it will upload the sourcemaps
will need to first run `npx sentry-cli login` and `brew install jq`

**Comment by lazaridiscom** [comment]
@kumavis , I saw "A Tale" and ran to read...

 I've not yet understood the overall test-system. Possibly you can add a README to the test-folder, and add the new info to it as a start.

**Review by danjm — APPROVED** [review]

**Review by danfinlay — APPROVED** [review]
Seems fine, will QA before next release.

**Pull request merged**
