### PR TITLE
fix: use transactionMeta for TransactionController events

### PR DESCRIPTION
**Pull request by ccharly**
## **Description**

Use of a wrong field name which ends up as an error once published.

ses-user-ops

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/24003?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/accounts-planning/issues/359

## **Manual testing steps**

1. Create a 4337 account using: https://metamask.github.io/snap-account-abstraction-keyring/latest/
  - You might need to change the `EIP_4337_ENTRYPOINT` in your `.metamaskrc` or `builds.yml` (or he might already be up-to-date)
2. Send some ETH to your newly created account
3. Try to send back some ETH to any account
  - The transaction should now succeed (it was failing before this fix)

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by mikesposito — COMMENTED** [review]
Is there a way to test that the `_onUserOperationTransactionUpdated` function does what it is expected to do? 

The `_` suggests that it's intended as _private_ function and we don't usually add tests for private functions directly, but perhaps we could test that the `transaction-updated` event is handled properly?

**Comment by ccharly** [comment]
I must say that I don't really know 😅

We did a small investigation with @montelaidev and we found out what was this error. We were doing manual tests though...

I don't know if the e2e tests should cover this one (implicitly)... Any thought regarding the best approach to test this @matthewwalsh0?

**Review by mcmire — COMMENTED** [review]
Good catch. I must have missed this in the TransactionController upgrade in #23252.

**Review by montelaidev — APPROVED** [review]
Tested with @ccharly

**Review by matthewwalsh0 — APPROVED** [review]

**Comment by k-g-j** [comment]
Testing on Chrome Version 125.0.6422.61 with the Flask build linked [here](https://github.com/MetaMask/metamask-extension/pull/24347#issuecomment-2122529592)❌ 

The extension shows a forever loading screen when I go to try and send funds from my 4337 Account back to my main EOA account.

https://github.com/MetaMask/metamask-extension/assets/91970214/27514bb9-6874-4cf5-8595-b3236357c90e

**Comment by k-g-j** [comment]
Using Flask build 12.0.0 [046766c1](https://github.com/MetaMask/metamask-extension/pull/25098#issuecomment-2154502562)

Testing on Chrome Version 126.0.6478.57 ✅ 

https://github.com/MetaMask/metamask-extension/assets/91970214/6bba7111-9e72-4df0-ad3f-f03d07214056

**Pull request merged**
