### PR TITLE
Increment tx ids to avoid collisions

### LINKED ISSUE #791: Metamask losing connection
This occurs randomly but seems to be occurring after calling a contract´s function.
The Extension contains no information about the issue but the console contains:
```
inpage-provider.js:14 
MetamaskInpageProvider - lost connection to MetaMask
(anonymous function) @ inpage-provider.js:14
(anonymous function) @ index.js:72f @ once.js:25
(anonymous function) @ index.js:44call @ index.js:49
(anonymous function) @ index.js:69f @ once.js:25
(anonymous function) @ index.js:28f @ once.js:17EventEmitter.emit @ events.js:96PostMessageStream._onMessage @ index.js:34

index.js:54 Uncaught Error: StreamProvider - Unknown response id(…)
StreamProvider._onResponse	@	index.js:54
StreamProvider._write	@	index.js:77
doWrite	@	_stream_writable.js:319
writeOrBuffer	@	_stream_writable.js:308
Writable.write	@	_stream_writable.js:246
ondata	@	_stream_readable.js:531
EventEmitter.emit	@	events.js:81
readableAddChunk	@	_stream_readable.js:198
Readable.push	@	_stream_readable.js:157
Transform.push	@	_stream_transform.js:123
(anonymous function)	@	obj-multiplex.js:15
Transform._read	@	_stream_transform.js:159
Transform._write	@	_stream_transform.js:147
doWrite	@	_stream_writable.js:313
writeOrBuffer	@	_stream_writable.js:302
Writable.write	@	_stream_writable.js:241
ondata	@	_stream_readable.js:542
EventEmitter.emit	@	events.js:81
readableAddChunk	@	_stream_readable.js:213
Readable.push	@	_stream_readable.js:172
PostMessageStream._onMessage	@	index.js:32
```

This is critical for a DAPP because there is no feedback to the DAPP and the function will never be called.

Piece of code I use:
```
   ...
   return contract.myFunction(param1, param2, ..., {from: account, value: price})
      .then(_tx => {
          // NEVER GET THERE
       })
      .catch(e => {
          // NEVER GET THERE
      })
... game over!
```

### PR DESCRIPTION
**Pull request by danfinlay**
It was possible for two requests to have the same ID, causing a crash and loss of StreamProvider connection.

This new id generation strategy creates a random ID, and increments it for each request.

In case the id generator is included from two different processes, I'm initializing the counter at a random number, and rolling it over a large number when it gets too big.

Fixes #791

### CODE REVIEW

**Comment by flyswatter** [comment]
I've already included an equivalent fix on the MultiVault branch pending merge.

**Comment by chevdor** [comment]
Thank you guys!

**Comment by flyswatter** [comment]
Thank YOU for pushing this forward!  People have reported this for a while, but never with reproduction steps, so that really put this over the top.

**Comment by chevdor** [comment]
Much appreciated, I hope I can help even more with a few PRs.
I will keep the test site up until I get this fix in the next version and can check it out. After that, I will wipe the site unless you need it.

**Pull request merged**
