### PR TITLE
fix (cherry-pick for v12.0.0): notification slowness and crashes

### PR DESCRIPTION
**Pull request by Prithpal-Sooriya**
## **Description**

This is a cherry pick for https://github.com/MetaMask/metamask-extension/pull/25946 (https://github.com/MetaMask/metamask-extension/commit/003ee98e7b3ed3ed9e3ff54093f4a5f807ea27fb)

------

This is a series of fixes added to core libraries. Adding to extension, and soon we will migrate extension to use shared libraries.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/25946?quickstart=1)

## **Related issues**

https://github.com/MetaMask/core/pull/4530
https://github.com/MetaMask/core/pull/4531
https://github.com/MetaMask/core/pull/4532
https://github.com/MetaMask/core/pull/4533
https://github.com/MetaMask/core/pull/4536

https://github.com/MetaMask/metamask-extension/issues/25749

## **Manual testing steps**

1. Create multiple accounts
2. Go to notification settings page
3. Wait for settings to load, and try toggling notifications

Before: some settings would error or not load
After: you should be able to toggle accounts and not see errors.

### **Before**

[](https://github.com/MetaMask/metamask-extension/issues/25749)

### **After**

https://www.loom.com/share/49b582e8c33b4199bdafc994a3f6087f?sid=9f94a885-351b-4fee-84d8-f72c97506e7d

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by mathieuartu — APPROVED** [review]
🫡

**Comment by Prithpal-Sooriya** [comment]
Fixes: https://github.com/MetaMask/metamask-extension/issues/25748

**Comment by Prithpal-Sooriya** [comment]
Fixes: https://github.com/MetaMask/metamask-extension/pull/25979

**Comment by Prithpal-Sooriya** [comment]
Fixes: https://github.com/MetaMask/metamask-extension/issues/25750

**Pull request merged**
