### PR TITLE
fix: Confirm Redesign styles: padding, box-shadow, and scroll; ScrollToBottom logic

### LINKED ISSUE #23662: [Bug]: Fix Confirm Design Page styles
### Describe the bug

ScrollToBottom PR introduced a style bug which caused an issue with the background colors and padding

There are a few other discrepancies found: 
- other padding issues
- scroll should scroll entire content including title
- box-shadow is not visible
- add box-shadow to footer
- add padding top to loadingindicator

### Expected behavior

Figma: https://www.figma.com/file/uACzbBjwU2tV30UuewYiTx/Confirmation-redesign-V2?type=design&node-id=775-28145&mode=design&t=Tpxj24iutpvomAFY-0
Figma Prototype: https://www.figma.com/proto/uACzbBjwU2tV30UuewYiTx/Confirmation-redesign-V2?page-id=461%3A8573&type=design&node-id=461-8632&viewport=352%2C310%2C0.1&t=Yak84g5KVUSjwbdf-1&scaling=min-zoom&starting-point-node-id=461%3A8632&show-proto-sidebar=1&mode=design

### Screenshots/Recordings

https://consensys.slack.com/files/U02DJ4GUD0V/F06QVHRUKGB/screenshot_2024-03-22_at_5.30.00___pm.png?origin_team=T02P98BKE&origin_channel=D057RSM4V9T

### Steps to reproduce

1. enable conf-redesign feature in build.yml
2. test signatures in test-dapp

### Error messages or log output

_No response_

### Version

11.12.3

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by digiwand**
## **Description**

Fixes confirmation refactor styles:
- fixes padding 
- header box-shadow is not visible
- adds box-shadow to footer

Fixes scroll to bottom issues:
- scroll now scrolls entire content including title
- scroll to bottom button should show on component mount
- scroll to bottom button should update when changing current confirmation / navigating through transactions

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/23661?quickstart=1)

Note: the loading spinner we are using is absolute positioned and has top: -5 for some reason. If we want to update this, this is out of scope 
Screenshot 2024-03-26 at 7 43 21 AM

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/23662

## **Manual testing steps**

enable conf-redesign feature in build.yml
test signatures in test-dapp

### **Before**

Screenshot 2024-03-22 at 5 30 00 PM (2)
Screenshot 2024-03-12 at 11 17 04 PM

### **After**

Screenshot 2024-03-22 at 3 39 14 PM
Screenshot 2024-03-22 at 4 29 26 PM

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by segun — DISMISSED** [review]

**Comment by jpuri** [comment]
@digiwand : changes look perfect, I have a doubt I think scrollbar should not be visible on the page. May be we confirm designs with @SayaGT

**Comment by digiwand** [comment]
Thanks @jpuri! I'm curious about what exact doubt you have about this

**Comment by digiwand** [comment]
thanks @jpuri! Fixed https://github.com/MetaMask/metamask-extension/pull/23661/commits/918c2c9addeb24389bc4f09d75ce5750469cabec
cc: @SayaGT

**Review by jpuri — DISMISSED** [review]

**Review by segun — DISMISSED** [review]

**Comment by digiwand** [comment]
thanks for the reviews! no changes were added since the approval. needed to resolve a merge conflict. may I get reapprovals on this please? @jpuri @segun

**Review by jpuri — APPROVED** [review]

**Review by pedronfigueiredo — APPROVED** [review]
LGTM!

**Pull request merged**
