### PR TITLE
enable privacy mode for first time users

### PR DESCRIPTION
**Pull request by tmashuang**
Enable privacy mode for first time users

### CODE REVIEW

**Review by danjm — DISMISSED** [review]
fast turnaround! :raised_hands:

**Review by whymarrh — DISMISSED** [review]
LGTM

**Review by whymarrh — DISMISSED** [review]
LGTM (electric boogaloo)

**Review by danjm — APPROVED** [review]

**Review by whymarrh — APPROVED** [review]
LGTM (🎬 3)

**Pull request merged**
