### PR TITLE
Dark Mode UI

### PR DESCRIPTION
**Pull request by ChrisCates**
This is still in progress.
But, just wanted to keep you guys updated on what I've done so far.

**Here are some screenshots:**

screen shot 2018-11-20 at 9 28 26 pm

screen shot 2018-11-20 at 9 29 38 pm

*Feel free to help out if you want to.*

If you have feedback @cjeria, let me know.

### CODE REVIEW

**Comment by bdresser** [comment]
fixes https://github.com/MetaMask/metamask-extension/issues/577

here's a color palette from @cjeria's brand guide if helpful! 

screen shot 2018-11-21 at 2 53 16 pm

**Comment by ChrisCates** [comment]
Perfect, I'll make sure to update that.
I will either finish it this weekend, or, have a PR ready for review by this weekend.

Chat soon @bdresser!

**Comment by ChrisCates** [comment]
@cjeria, no worries. I'll probably submit a new commit Saturday or Sunday anyway.

**Comment by cjeria** [comment]
@ChrisCates Here's a color palette to get you started. I've based these off of some research I did on dark UIs. These also tested pretty well with accessibility (using screen tool called Sim Daltonism to test). There are a lot of other colors that aren't spec'd here (like hover states, fonts and one-offs colors), but at least we have a good starting point. Please let me know if you have any questions!

**Color Palette**
dark mode - color palette

**Main UI Color Spec**
dark mode - color spec

**UI with Dark Mode Colors** 
Sorry for using an older UI for this!
dark mode

**Comment by ChrisCates** [comment]
Ahhh, this is great. Ill send an update Saturday since thats when Ill
startup again!~

**Comment by danjm** [comment]
I wonder if we can make this more flexible, make it easy to add other themes in the future should we so choose, and greatly reduce the amount of css you have to write by using css variables for dynamic css updating. An example is described here: https://itnext.io/css-variables-dynamic-app-themes-86c0db61cbbb

What do you think @ChrisCates?

**Comment by ChrisCates** [comment]
@danjm, sounds like a great idea.
I could maybe have a textbox in settings to edit it.

Sorry, just been busy with a bunch of stuff. I'm going to set out a few hours tomorrow to push a commit!~

**Comment by ChrisCates** [comment]
screen shot 2018-12-03 at 9 03 54 pm
screen shot 2018-12-03 at 9 03 59 pm
screen shot 2018-12-03 at 9 04 21 pm
screen shot 2018-12-03 at 9 04 26 pm
screen shot 2018-12-03 at 9 04 31 pm
screen shot 2018-12-03 at 9 04 38 pm
screen shot 2018-12-03 at 9 04 43 pm
screen shot 2018-12-03 at 9 04 48 pm
screen shot 2018-12-03 at 9 04 54 pm
screen shot 2018-12-03 at 9 05 00 pm

**Comment by ChrisCates** [comment]
@bdresser, @danjm, @cjeria.

Majority of the work is done now. Do I need to update the SVG for Metamask logo in top? Perhaps that SVG should have a custom text color?

Everything uses css variables now. So they are easily overrideable via a text input. Maybe a third tab could exist that is called "Theme". And you can change each hex value.

Anyway, review and let me know if there are any issues.

**Comment by ChrisCates** [comment]
Closing due to inactivity, I'll keep the code laying around if you still want to use it.

**Comment by bdresser** [comment]
sorry for the slow reply @ChrisCates. We're spread pretty thin on the design side, but we'll have someone take a closer look at this in the next couple weeks! Thanks for the contribution, this is a fun one.

**Comment by ChrisCates** [comment]
@bdresser, just ping me when you're good to go!~

I had my wisdom teeth pulled and had some pretty bad inflammation/headaches this week. So I've been behind on some stuff. Overall I'm feeling better.

Anyway, that'll be irrelevant next week. :)

**Comment by hrqmonteiro** [comment]
Isn't this working? Just started using MetaMask and i was looking for dark mode (and still is)

**Comment by Arnauw** [comment]
How to use this please ?

**Comment by ChrisCates** [comment]
Just want to make sure I'm not blocking anything for this project.
I believe we need to rebase the PR due to how old it is.

But would love to see it implemented.

> I have read the CLA Document and I hereby sign the CLA

**Comment by ChrisCates** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Waxxx333** [comment]
Does this still work ? 
And if so, how would I use it ? 
My config directory for Metamask doesn't show the path `ui/app/css/itcss/etc/etc`. 
Instead I just have UI files ranging from `ui-0.js` to `ui-10.js`. 
Any help would be appreciated. I don't understand why Metamask doesn't have a dark theme toggle button like everything else.

**Comment by ChrisCates** [comment]
Hey @Waxxx333, this PR is outdated. Therefore doesn't match majority of updates to the codebase.

This one is much closer to the master branch. And is actively being implemented: https://github.com/MetaMask/metamask-extension/issues/13719

Hope this helps.

**Pull request closed without merging**
