### PR TITLE
feat: add Mint Blockchain

### PR DESCRIPTION
**Pull request by zhwindy**
## **Description**

Add Mint Blockchain Mainnet network icon support.

## **Related issues**

Fixes: N/A

## **Manual testing steps**

1. Go to [Mint](https://www.mintchain.io)
2. Click the Metamask icon to add network
3. Open Metamask extension to check the network and token icons

### **Before**
image

### **After**
mint-metamask-white

mint-metamask-black

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by zhwindy** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by gambinish — CHANGES_REQUESTED** [review]
Hi @zhwindy thank you for making this PR! A couple of requests:

Could you please provide and "after" screenshot in both light and dark mode?

I suspect that you'll also want to update the `CHAIN_ID_TO_NETWORK_IMAGE_URL_MAP` mapping [here](https://github.com/MetaMask/metamask-extension/blob/5639952a1012e5da01b98cd2bb33ce7158101067/shared/constants/network.ts#L715) in order for the network icon to correctly display.

Additionally, I'm looking at your [docs](https://docs.mintchain.io/build/network), and it looks like your testnet is actually running on Sepolia? Wondering why you namespaced them to Goerli here.

**Comment by zhwindy** [comment]
> Hi @zhwindy thank you for making this PR! A couple of requests:
> 
> Could you please provide and "after" screenshot in both light and dark mode?
> 
> I suspect that you'll also want to update the `CHAIN_ID_TO_NETWORK_IMAGE_URL_MAP` mapping [here](https://github.com/MetaMask/metamask-extension/blob/5639952a1012e5da01b98cd2bb33ce7158101067/shared/constants/network.ts#L715) in order for the network icon to correctly display.
> 
> Additionally, I'm looking at your [docs](https://docs.mintchain.io/build/network), and it looks like your testnet is actually running on Sepolia? Wondering why you namespaced them to Goerli here.

ok, I will try to provide and "after" screenshot in both light and dark mode in localhost.

the Goerli added is a mistake and will remove it now, our testnet is running on Sepolia.

yep, mainnet is already update in `CHAIN_ID_TO_NETWORK_IMAGE_URL_MAP` in order for the network icon to correctly display

**Comment by zhwindy** [comment]
@gambinish hi, already fixed all, please check again.

**Pull request closed without merging**
