### PR TITLE
Updating welcome message

### PR DESCRIPTION
**Pull request by darkwing**
Updates welcome messaging for BETA, as well as reformats the current welcome message to use Typography.

BTWelcome

### CODE REVIEW

**Comment by SayaGT** [comment]
Hey @darkwing can we make "standard Terms" clickable instead of just "Terms"? Otherwise looks good to me!

**Review by SayaGT — DISMISSED** [review]
Hey @darkwing can we make "standard Terms" clickable instead of just "Terms"? Otherwise looks good to me!

**Review by Gudahtt — COMMENTED** [review]
LGTM! I can approve after the requested adjustment is made

**Comment by darkwing** [comment]
@SayaGT @Gudahtt Updated to include 'standard' as part of the link!

**Comment by darkwing** [comment]
Std

**Review by Gudahtt — APPROVED** [review]
LGTM!

**Review by brad-decker — APPROVED** [review]

**Pull request merged**
