### PR TITLE
fix: isPermitSignatureRequest logic. Do not display as Permit if spender is not present

### LINKED ISSUE #27385: [Bug]: Permit pages may render for TypedSign signatures without "Spender" field
### Describe the bug

There are various Permit specs types e.g. EIP-2612, Permit2, EIP-4494 (NFT)

What they have in common is that these all require a "spender" field

In cases where a "spender" field is missing, we should fallback to displaying a regular EIP-712 signatures.

### Expected behavior

_No response_

### Steps to reproduce

run
```
await window.ethereum.request({ "method": "eth_signTypedData_v4", "params": [
  "0xyourAddressHere", 
    {
            domain: {
              name: 'Example Domain',
              version: '1',
              chainId: 11155111,
              verifyingContract: '0xC36442b4a4522E871399CD717aBDD847Ab11FE88',
            },
                    types: {
          Person: [
            { name: "name", type: "string" },
            { name: "wallet", type: "address" },
          ],
          Permit: [
            { name: "from", type: "Person" },
            { name: "to", type: "Person" },
            { name: "contents", type: "string" },
          ],
        },
        primaryType: "Permit",
        message: {
          from: {
            name: "Cow",
            wallet: "0xCD2a3d9F938E13CD947Ec05AbC7FE734Df8DD826",
          },
          to: {
            name: "Bob",
            wallet: "0xbBbBBBBbbBBBbbbBbbBbbbbBBbBbbbbBbBbbBBbB",
          },
          contents: "Hello, Bob!",
        },
  }
], });
```

with updated chainId and param[0] address. ChainId here is currently set to Sepholia: 11155111

### Error messages or log output

_No response_

### Detection stage

During release testing

### Version

12.3.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by digiwand**
## **Description**

If primaryType either:
- Permit 
- PermitBatch
- PermitBatchTransferFrom
- PermitSingle
-  PermitTransferFrom

and it does not have a "spender" hex address, do not render the signature as a Permit. Without a spender, we will fallback to an EIP-712 signature.

Note: The check for isPermitSignatureRequest is not sophisticated. This will be revisited with the upcoming Signatures API work. 

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/27384?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/27385

## **Manual testing steps**

```
await window.ethereum.request({ "method": "eth_signTypedData_v4", "params": [
  "0xE56E7847Fd3661A9B7c86aAF1DaEa08D9DA5750e", 
    {
            domain: {
              name: 'Test Domain',
              version: '1',
              chainId: 11155111,
              verifyingContract: '0xC36442b4a4522E871399CD717aBDD847Ab11FE88',
            },
                    types: {
          Person: [
            { name: "name", type: "string" },
            { name: "wallet", type: "address" },
          ],
          Permit: [
            { name: "from", type: "Person" },
            { name: "to", type: "Person" },
            { name: "contents", type: "string" },
          ],
        },
        primaryType: "Permit",
        message: {
          from: {
            name: "Cow",
            wallet: "0xCD2a3d9F938E13CD947Ec05AbC7FE734Df8DD826",
          },
          to: {
            name: "Bob",
            wallet: "0xbBbBBBBbbBBBbbbBbbBbbbbBBbBbbbbBbBbbBBbB",
          },
          contents: "Hello, Bob!",
        },
  }
], });
```

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by jpuri** [comment]
Hey @digiwand : I think this task requires more detailed discussion as there can be many different validations for different signature. In case we are not able to validate a signature - should we reject it or display as simple typed sign or some other approach.

**Review by jpuri — CHANGES_REQUESTED** [review]
We should re-evaluate the approach and discuss this more.

**Comment by digiwand** [comment]
Hi @jpuri, I agree we should have further discussion on how to approach this. In the meantime, I think it would be a good idea to enforce Spender exists for displaying Permit since Spender is required for EIP-2612, Permit2, and EIP-4494 (NFT)

I'm creating a couple of new tickets to address the validation and display handling for permits

**Comment by digiwand** [comment]
Hi @jpuri, I agree we should discuss how to approach this further. In the meantime, I think we should still enforce the `spender` exists for displaying Permit since `spender` is required for EIP-2612, Permit2, and EIP-4494 (NFT), and without it, our UI is misleading. 

> should we reject it or display as simple typed sign or some other approach

I think we should persist the behavior of our old signatures and not reject the signatures in this case. As the signature authors design their own EIP-712 struct, any arbitrary string could be a valid `primaryType`. This should mean a message with `primaryType` === "Permit" without a `spender`, or another required Permit spec, can still be a valid EIP-712. 

We could possibly warn developers if we detect that they may be trying to create a EIP-2612 signature and the required fields are invalid or missing. 

We have explicit support for a minor subset of Permit `primaryType`s as mentioned in the description above, along with Order primaryTypes not mentioned. We will revisit support for additional types with the upcoming Signature API work

**Comment by digiwand** [comment]
per discussion to reevaulate UI/UX closing ticket

**Pull request closed without merging**
