### PR TITLE
Continue migration from mocha to jest

### PR DESCRIPTION
**Pull request by tmashuang**
Migration of mocha to jest for 

```
'app/scripts/account-import-strategies/account-import-strategies.test.js',
'app/scripts/controllers/backup.test.js',
'app/scripts/controllers/cached-balances.test.js',
'app/scripts/controllers/incoming-transactions.test.js',
```

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [x] How reviewers can test my changes
- [x] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Comment by pedronfigueiredo** [comment]
Looks good @tmashuang 🔥

**Review by pedronfigueiredo — DISMISSED** [review]

**Review by Wallyworldg02 — COMMENTED** [review]
Walter

**Review by Wallyworldg02 — APPROVED** [review]

**Review by pedronfigueiredo — DISMISSED** [review]

**Comment by tmashuang** [comment]
Part of #19355.

**Review by arti210 — APPROVED** [review]

**Review by CASABECI — COMMENTED** [review]
Ekn

**Review by MWGW — APPROVED** [review]

**Pull request closed without merging**
