### PR TITLE
Enables the "Safe Transaction From" copy for safeTransferFrom transactions

### LINKED ISSUE #14636: Sentry Error: The category prop passed to TransactionIcon is not supported._Last 30 Days: 23K
Sentry Issue: [METAMASK-J9QW](https://sentry.io/organizations/metamask/issues/2586495035/?referrer=github_integration)

```
Error: The category prop passed to TransactionIcon is not supported. The prop is: undefined
  at action (ui/store/actions.js:3109:24)
  at TransactionIcon (ui/components/app/transaction-icon/transaction-icon.js:48:5)
  at None (ui/index.js:159:3)
...
(10 additional frame(s) were not displayed)
```
Last 30 Days: 23K

### LINKED ISSUE #14729: Sentry Error: The category prop passed to TransactionIcon is not supported. The prop is: undefined_Last 30 Days: 9.7K
Sentry Issue: [METAMASK-NKV0](https://sentry.io/organizations/metamask/issues/3248244711/?referrer=github_integration)

```
Error: The category prop passed to TransactionIcon is not supported. The prop is: undefined
  at None (metamask/common-1.js:1:197151)
  at None (metamask/common-5.js:27:12294)
  at v (metamask/ui-5.js:10:223917)
  at mi (metamask/ui-0.js:1:87997)
  at Ms (metamask/ui-0.js:1:132755)
...
(10 additional frame(s) were not displayed)
```
Last 30 Days: 9.7K

### PR DESCRIPTION
**Pull request by digiwand**
## Explanation

The `safeTransferFrom` translation is currently not being used. This PR puts the `safeTransferFrom` translation to use. 

## More Information

* Further fix for https://github.com/MetaMask/metamask-extension/issues/14729  and https://github.com/MetaMask/metamask-extension/issues/14636 after  https://github.com/MetaMask/metamask-extension/pull/14678
* Related: https://github.com/MetaMask/metamask-extension/pull/13535 (original implementation of `t('safeTransferFrom')`

### Before

Screenshot 2022-05-24 at 10 35 56 AM

### After

Screenshot 2022-05-24 at 1 45 44 PM
Screenshot 2022-05-24 at 11 14 09 AM

## Manual Testing Steps

Instructions based off of: https://github.com/MetaMask/metamask-extension/issues/14729:
1. Go to [Remix](https://remix.ethereum.org/#code=Ly8gU1BEWC1MaWNlbnNlLUlkZW50aWZpZXI6IE1JVApwcmFnbWEgc29saWRpdHkgXjAuOC40OwoKaW1wb3J0ICJAb3BlbnplcHBlbGluL2NvbnRyYWN0c0A0LjYuMC90b2tlbi9FUkM3MjEvRVJDNzIxLnNvbCI7CmltcG9ydCAiQG9wZW56ZXBwZWxpbi9jb250cmFjdHNANC42LjAvYWNjZXNzL093bmFibGUuc29sIjsKCmNvbnRyYWN0IE15VG9rZW4gaXMgRVJDNzIxLCBPd25hYmxlIHsKICAgIGNvbnN0cnVjdG9yKCkgRVJDNzIxKCJNeVRva2VuIiwgIk1USyIpIHt9CgogICAgZnVuY3Rpb24gc2FmZU1pbnQoYWRkcmVzcyB0bywgdWludDI1NiB0b2tlbklkKSBwdWJsaWMgb25seU93bmVyIHsKICAgICAgICBfc2FmZU1pbnQodG8sIHRva2VuSWQpOwogICAgfQp9Cg&optimize=false&runs=200&evmVersion=null&version=soljson-v0.8.7+commit.e28d00a7.js)
2. Compile My Token contract
  a. Go to "Solidity Compiler" tab
  b. Click "Compile contract..."
3. Go to "Deploy & Run Transactions" tab
4. Connect Metamask (click on Injected Web3 Provider [under Environment])
  a. Under "Environment", select "Injected Web3"
  b. Connect account(s)
5. Deploy MyToken contract
  a. Under "Contract", select "MyToken ..."
  b. Click "Deploy" button
  c. Follow MM to "Confirm" "Contract Deployment" 
6. Once deployed, expand "MY TOKEN 0X..." contract under "Deployed Contracts"
7. "safeMint" one token with select owner address, and token id 1)
  a. input the owner address, token id  e.g. "0xabcdef, 1"
  b. click the orange "safeMint" button
  c. optionally, expand "safeMint" to enter via form fields
8. Once minted, "safeTransferFrom" the token
  a. input the owner address, target address, and the token id  e.g. "0xabcdef, 0x12345, 1"
  b. click the orange "safeTransferFrom" button
  c. optionally, expand "safeTransferFrom" to enter via form fields
9. See MM activity entries

Video or repo steps provided in https://github.com/MetaMask/metamask-extension/issues/14729

## Pre-Merge Checklist

- [x] PR template is filled out
- [x] Manual testing complete & passed
- [x] **IF** this PR fixes a bug, a test that _would have_ caught the bug has been added
- [x] PR is linked to the appropriate GitHub issue
- [x] **IF** QA attention is required, "QA Board" label has been applied
- [x] PR has been added to the appropriate release Milestone

### CODE REVIEW

**Review by darkwing — APPROVED** [review]

**Review by jpuri — APPROVED** [review]
👍

**Comment by seaona** [comment]
@digiwand looking good! I see that all the console errors have gone and `Safe Transfer From` tx type is handled properly

**Comment by brad-decker** [comment]
Can I ask how this fixes the category prop issue? In the previous iteration is appears to me that the category prop was being set properly for this type of transaction? I'm not suggesting it doesn't I just would like more context :) @digiwand

**Comment by digiwand** [comment]
Hello 👋  Great question. You're totally right which is why I described this PR as a "Further fix"
> Further fix for https://github.com/MetaMask/metamask-extension/issues/14729 and https://github.com/MetaMask/metamask-extension/issues/14636 after https://github.com/MetaMask/metamask-extension/pull/14678

To elaborate, I believe the error itself was fixed by https://github.com/MetaMask/metamask-extension/pull/14678 around 2 weeks ago. https://github.com/MetaMask/metamask-extension/pull/14678 was combatting a different issue and it, for lack of better phrases, killed two birds with one stone. 

The missing piece for https://github.com/MetaMask/metamask-extension/pull/14678 was that it now labeled this transaction type as a "Send Token" whereas the original intention was to show "Safe Transfer From" (see https://github.com/MetaMask/metamask-extension/pull/13535).

**Comment by digiwand** [comment]
@brad-decker 

Hello 👋  Great question. You're totally right which is why I described this PR as a "Further fix"
> Further fix for https://github.com/MetaMask/metamask-extension/issues/14729 and https://github.com/MetaMask/metamask-extension/issues/14636 after https://github.com/MetaMask/metamask-extension/pull/14678

To elaborate, I believe the error itself was fixed by https://github.com/MetaMask/metamask-extension/pull/14678 around 2 weeks ago. https://github.com/MetaMask/metamask-extension/pull/14678 was combatting a different issue and it, for lack of better phrases, killed two birds with one stone. 

The missing piece for https://github.com/MetaMask/metamask-extension/pull/14678 was that it now labeled this transaction type as a "Send Token" whereas the original intention was to show "Safe Transfer From" (see https://github.com/MetaMask/metamask-extension/pull/13535).

Thanks for bringing this up! I will link https://github.com/MetaMask/metamask-extension/pull/14678 and the author, @adonesky1, with the related issue tickets as well

**Comment by brad-decker** [comment]
Thanks for the elaboration! I just misunderstood what was meant by further fix for. Thanks for clearing that up

**Comment by digiwand** [comment]
👍

**Pull request merged**
