### PR TITLE
Fix token USD price calculation

### LINKED ISSUE #5960: Incorrect USD price of tokens in menu
**Describe the bug**
The USD price of tokens in Menu is incorrect. It shows huge amount of USD - around ±100x more as the real value. I'm not sure if it's only a problem of decimal point or the prices are totally wrong. It's obviously connected to where token prices are coming from.

**To Reproduce**
1. Open Metamask extension
2. Click on the hamburger menu in top left corner
3. Scroll down to tokens
4. Inspect prices

**Expected behavior**
A correct value in USD should be displayed. 

Examples of tokens with invalid USD prices: Crypto20 C20, Gnosis GNO

**Screenshots**
https://pasteboard.co/HSUIZwg.png

**Browser details (please complete the following information):**
 - OS: MacOS 10.14 Mojave
 - Browser: Brave Version 0.58.16 Chromium: 71.0.3578.98 (Official Build) (64-bit)
 - MetaMask Version 5.2.2

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by pavel-lens**
USD price calculation was wrong, see discussion #5960 

Please test the fix before merging.

Closes #5960

### CODE REVIEW

**Comment by tmashuang** [comment]
@svitekpavel Thanks for the contribution, our develop branch CI tests have been fix. Please rebase your fix branch and we'll get it merged in.

**Comment by svitekpavel** [comment]
I rebased it. Fixed lint and unit tests.

Some unit test in "Transaction Controller" are failing though.

**Review by tmashuang — DISMISSED** [review]

**Comment by danfinlay** [comment]
@svitekpavel could you pull `develop` over this branch then push to it again? Right now the PR includes a lot of unrelated history so it's hard to review.

I got the test passing too btw.

**Comment by danfinlay** [comment]
Closing in favor of #6005, which just cleans this up a bit. Thanks for the contribution!

**Pull request closed without merging**
