### PR TITLE
Handle case where gas estimate fails

### LINKED ISSUE #2898: Transaction - handle case where estimateGas fails
ended up with suggested gasLimit of 0

### PR DESCRIPTION
**Pull request by danfinlay**
If gas estimation returns an error that we don't handle, mark that transaction as failed.

Fixes #2898

### CODE REVIEW

**Review by kumavis — APPROVED** [review]
noice

**Comment by kumavis** [comment]
looks like frankie also solved this in a slightly different way, this approach hybridizes the two

**Comment by kumavis** [comment]
Test errors should be fixed by https://github.com/MetaMask/metamask-extension/pull/3029

**Comment by danfinlay** [comment]
Sounds like this is already fixed in another way.

**Pull request closed without merging**
