### PR TITLE
Add Rootstock to the popular network list

### PR DESCRIPTION
**Pull request by jonathansmirnoff**
## **Description**

Add Rootstock to the popular custom network list.

## **Manual testing steps**

1. Go to Add network
2. Go to Rootstock network and click at "add"

## **Screenshots/Recordings**

https://github.com/MetaMask/metamask-extension/assets/7558841/14102c7e-3f57-43fb-9ef5-45fbc45ae136

### CODE REVIEW

**Comment by jonathansmirnoff** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by jonathansmirnoff** [comment]
Hi @legobeat! Rootstock community has been waiting for this feature for a long time. Do you think it is possible to have it?

**Comment by jonathansmirnoff** [comment]
Hi @pedronfigueiredo! Is there any chance to review this PR? For Rootstock community is very important. Thanks in advance!

**Comment by alepc253** [comment]
There's a poll supporting this integration [here](https://community.metamask.io/t/add-rootstock-to-the-popular-network-list/27570)

**Comment by alepc253** [comment]
This PR is still waiting to be merged

**Pull request closed without merging**
