### PR TITLE
Added a much needed documentation generator.

### PR DESCRIPTION
**Pull request by restarian**
Hey guys, this project is screaming for a documentation manager. I've added [Brace Document](https://github.com/restarian/brace_document) as optional dependencies and ran it against the current documentation as it stands and it seems to output well. Please compare the changes and get back to me. Keep in mind that I only ran the command _npm run make_docs_ to get this results. I am willing to format the document pages better when this is ok'ed for merging. Note: it automatically creates a _package_information.md_ page in the specification directory. Also note: small tweeks can be made to fix the title hyphens and case issues

### CODE REVIEW

**Review by whymarrh — COMMENTED** [review]
> Hey guys, this project is screaming for a documentation manager.

Hey @restarian, thanks for proposing this. I've looked at the changes here and don't immediately see the benefit—what is the tangible improvement here? Hyperlinks?

We have a separate user-facing docs site, [MetaMask Developer Documentation](https://metamask.github.io/metamask-docs/) ([GitHub repo](https://github.com/MetaMask/metamask-docs)), that's intended for MetaMask users. Where this is all "internal" documentation and where some of these files are tiny, I might suggest that we could fold a lot of this into one file.

> Keep in mind that I only ran the command `npm run make_docs` to get this results. I am willing to format the document pages better when this is ok'ed for merging. Note: it automatically creates a `package_information.md` page in the specification directory. Also note: small tweeks can be made to fix the title hyphens and case issue

This does all seem a bit messy, to be honest. If this is the default output of the tool, will we need to tweak it manually after each run? What is the benefit does the `package_information.md` file bring? `yarn run` will list all of the available scripts, and listing the dependencies seems unnecessary (certainly at least because it's subject to change and this is now one more place we'll need to update).

**Comment by restarian** [comment]
Well, I hear ya about the package.md file, but automatic creation of document pages which include links to other dependencies is good for search-ability.  Also, it makes a project feel more comfortable to developers (like me :) when it is included int the actual repository documentations.

And no, there are zero tweeks to the documentation need to run the command. It is safe and idempotent. I simply was stating that there is some work to do which I do not want to do unless the team sees the impact that restarian will have on your project. Also, I see that two readme files are included and I believe this is because github requires them to be at the base directory level. Brace Document Link fixes this by create symlinks to the base directory so that the documents can be managed for a single location in a coherent fashion (with sub directories). 
Your project is just begging for this guys!

**Comment by restarian** [comment]
> sary (certainly at least because it's subject to change 

Oh ya, the package.md file is updated automatically. Also, the documents are generated using the current git branch as well.

**Comment by whymarrh** [comment]
Thanks again for suggesting this—ultimately most of these docs are some combination of inaccurate, stale, or unnecessary (unfortunately) and I'd sooner we delete these than try and organize them. (See also #7988, #7989, #7998, and #7999, where I've started deleting some of the most egregious ones.)

For the ones that are decent, they really should live in on our separate user-facing docs site, [MetaMask Developer Documentation](https://metamask.github.io/metamask-docs/), where we have an existing docs generator. I've opened #8000 to represent that.

**Pull request closed without merging**
