### PR TITLE
Delete unused SeedImportSubview component

### PR DESCRIPTION
**Pull request by whymarrh**
Refs #7523

This PR deletes the unused `SeedImportSubview` component.

### CODE REVIEW

**Review by Gudahtt — DISMISSED** [review]
LGTM!

**Comment by whymarrh** [comment]
Rebased and added a5a1f88 to remove two localized messages that are no longer used.

**Comment by Gudahtt** [comment]
Those messages still need to be removed from the other locales

**Comment by whymarrh** [comment]
Ah yes good point 😅

**Review by Gudahtt — APPROVED** [review]
LGTM!

**Pull request merged**
