### PR TITLE
Lionbridge

### PR DESCRIPTION
**Pull request by UFCSVCLionbridge**
I have read the CLA Document and I hereby sign the CLA

### CODE REVIEW

**Comment by darkwing** [comment]
@UFCSVCLionbridge Could you please sign the CLA?  Thank you!

**Comment by ryanml** [comment]
@UFCSVCLionbridge - would you also mind rebasing this PR to our latest version of `develop`? Thanks!

**Comment by UFCSVCLionbridge** [comment]
> @UFCSVCLionbridge - would you also mind rebasing this PR to our latest version of `develop`? Thanks!

Hi ryanml,

Sorry to bother you with this but I'm not Github expert and I'm not sure what is required of Lionbridge here, when you say rebase - do you know what commands I need to run to effect this?

Thanks,

Mark.

**Comment by ryanml** [comment]
@UFCSVCLionbridge - I'm closing this pull request in favor of: https://github.com/MetaMask/metamask-extension/pull/11292 - which contains the changes you folks have made for translations, it is just now on an origin branch which is easier to work with. Thank you!

**Pull request closed without merging**
