### PR TITLE
Add new lightweight logo

### LINKED ISSUE #624: Include new lightweight metamask logo for speed boosts
For fun, feel free to post your before/after metamask pop-up time, so we can measure the speed bump!

### PR DESCRIPTION
**Pull request by danfinlay**
- No longer need to check for webGL compliance (svg rendered!)
- logo.canvas has been replaced with logo.container, since svg doesn't render to canvas but to an element.
- Reduces logo from >600kb to 5kb!

Otherwise, worked with very little effort!!

Fixes #624

### CODE REVIEW

**Comment by flyswatter** [comment]
Gah, passes locally, this is probably another problem with our test suite running on an old container.  I think I'm going to update it now.

**Comment by flyswatter** [comment]
The new container seems to not be installing our dependencies by default, I've reached out to Circle to address it.  In the meanwhile I'm considering adding `npm i` to our `circle.yml`, although it's going to make the builds sooo slow, with no caching.

**Comment by Zanibas** [comment]
screenshot from 2016-09-08 13 23 04

**Comment by Zanibas** [comment]
This works fine, but there are some optimization issues that arise when visiting the lock screen multiple t imes without closing the popup, but that's an edge case.

**Comment by flyswatter** [comment]
What are those issues?

- Dan

**Pull request merged**
