### PR TITLE
Update Italian translation 

### PR DESCRIPTION
**Pull request by matteopey**
Hello, this is an update of the Italian translation on the latest version of messages.json.

WIP because I have yet to test the app to see if the translation makes sense, I'll do it in the weekend.

### CODE REVIEW

**Comment by daddyfatstaks** [comment]
F MatteoP!!!!!

**Comment by matteopey** [comment]
I think is ready to be merged. 
I've rebased it to latest develop. Hope I didn't make any mistake.

**Comment by whymarrh** [comment]
@matteopey would you mind rebasing this on the latest `develop` (again, sorry!)

I think the e2e failure here is real and fixed with a recent commit.

**Review by whymarrh — APPROVED** [review]
Thanks @matteopey!

**Pull request merged**
