### PR TITLE
Removing unused NETWORKS_FORM_ROUTE route

### PR DESCRIPTION
**Pull request by ryanml**
Follow up to: https://github.com/MetaMask/metamask-extension/pull/15442

### CODE REVIEW

**Review by digiwand — COMMENTED** [review]
Can we add an explanation as to why we're removing this feature entirely from the * popup *? If we go through with this, we should also remove the related styles

**Comment by adonesky1** [comment]
> Can we add an explanation as to why we're removing this feature entirely from mobile? If we go through with this, we should also remove the related styles

@digiwand not sure whether this has anything to do with mobile, but I agree PR description would help us understand how to review. Thanks in advance @ryanml!

**Review by NiranjanaBinoy — APPROVED** [review]
LGTM

**Comment by digiwand** [comment]
Sorry, that was a typo slip. I meant the popup* not mobile. @adonesky1

**Comment by brad-decker** [comment]
@ryanml could you update this PR so we can move it forward?

**Comment by brad-decker** [comment]
@ryanml i'm converting this to draft until it can be rebased. After another 30 day period i'll close the PR due to inactivity. Only doing this to keep the PR queue clear and put proper emphasis on keeping prs in a reviewable state! <3

**Pull request closed without merging**
