### PR TITLE
Adding expanse network

### PR DESCRIPTION
**Pull request by chrisfranko**

### CODE REVIEW

**Comment by Zanibas** [comment]
Thank you for being thorough with this PR in line with the procedure to add new networks. We will have to deliberate on whether or not to add it in though, as our network menu is already getting clogged as is.

**Comment by kumavis** [comment]
for relevant discussion, see https://github.com/MetaMask/metamask-plugin/pull/1476

**Comment by chrisfranko** [comment]
Thanks, the only thing i didnt notice was setting chain_id or network_id

The chain id of EXP is 2, while our network id is 1.

A suggested change to the network menu id make is... Have ETH and EXP and but have ETH be a dropdown menu that houses all the eth networks. It would tidy it up a bit and make some room. Also, as a plan B, if yall decide against integrating EXP how much of MetaMask would I be able to rebrand as say MetaMask-EXP or something entirely different.

MetaMask is really helpful for people with little experience in crypto to be able to use dapps. (I personally use it all the time for testing the dapps we are working on at expanse)

**Comment by Zanibas** [comment]
Encapsulated in #1820 until we can dedicate more time to this. Please redirect all concerns to that issue.

**Pull request closed without merging**
