### PR TITLE
Use core transaction controller

### PR DESCRIPTION
**Pull request by matthewwalsh0**
## **Description**

Replace the extension `TransactionController` with the core `TransactionController` to utilise the same transaction logic in both clients.

This also includes:

- Remove all duplicate extension types such as `TransactionMeta` and `TransactionStatus`.
- Create a migration to convert the persisted transactions to an array rather than an object.

## **Manual testing steps**

Full and in-depth regression of all functionality related to transactions.

### **After**

[Pending]

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained:
  - [x] What problem this PR is solving.
  - [x] How this problem was solved.
  - [x] How reviewers can test my changes.
- [x] I’ve indicated what issue this PR is linked to: Fixes #???
- [x] I’ve included tests if applicable.
- [x] I’ve documented any added code.
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)).
- [x] I’ve properly set the pull request status:
  - [x] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by sleepytanya** [comment]
Incoming transactions are not detected in the transactions history:

https://github.com/MetaMask/metamask-extension/assets/104780023/14115eff-4bba-4a0c-809e-8195e2ba9737

**Comment by sleepytanya** [comment]
Unable to `cancel` or `speed up` tx with low gas fee.
Steps to reproduce:
1. Create tx with very low gas fee using `advanced gas settings`
2. Try to `cancel` or `speed up` the tx

https://github.com/MetaMask/metamask-extension/assets/104780023/77924993-cbbd-459c-92be-ae86f98002a0

**Comment by sleepytanya** [comment]
Unable to use custom nonce:

https://github.com/MetaMask/metamask-extension/assets/104780023/d79cc998-d14f-4c74-a67d-7d1fb4b890cf

Steps:
1. Regular Send transaction
2. Input custom nonce (630 in my case)
3. See subsequent nonce # (628) on transactions history.

**Comment by sleepytanya** [comment]
Test DAPP `Watch NFT` and NFT `Approve` do not work (`Watch all NFTs` and `Set approval for all` work as expected).

**Comment by sleepytanya** [comment]
Non-native token swap showing this error:
Screenshot 2023-11-20 at 11 49 10 AM
Screenshot 2023-11-20 at 11 49 39 AM

`Eth` swaps work as expected.

**Comment by sleepytanya** [comment]
Using `Gas fee options` won't cancel the transaction unless you use `Advanced options`:

https://github.com/MetaMask/metamask-extension/assets/104780023/50133d67-2f6b-431a-89b1-efb6c327e49c

**Comment by matthewwalsh0** [comment]
@SocketSecurity ignore @metamask/transaction-controller@18.1.0

**Review by vinistevam — APPROVED** [review]
This is remarkable @matthewwalsh0 ! :1st_place_medal:

**Review by OGPoyraz — APPROVED** [review]

**Pull request merged**
