### PR TITLE
xDai chain support by default

### PR DESCRIPTION
**Pull request by vbaranov**
Inspired by https://twitter.com/rstormsf/status/1192275093054881792?s=19

xDai chain resources: https://www.xdaichain.com/
xDai explorer: https://blockscout.com/poa/xdai/
xDai bridge: https://dai-bridge.poa.network

Screenshot 2019-11-22 at 16 34 33
Screenshot 2019-11-22 at 16 35 31
Screenshot 2019-11-22 at 16 34 10
Screenshot 2019-11-22 at 16 35 04

### CODE REVIEW

**Comment by rstormsf** [comment]
@whymarrh any feedback on this?

**Comment by whymarrh** [comment]
Hey, @vbaranov, thanks for putting this together. (@rstormsf thanks for the ping.) As I commented over on the Pocket Network PR, the network list can't be extended to include everyone's networks and we don't have a way of honestly choosing among all the possible networks. As noted in the Twitter thread linked in the OP, our forthcoming plugin system may very well be a way to introduce some extensibility to MetaMask's understanding of networks.

I'm closing this for now, but #3604 and #5101 are relevant here, as ideally we should have a way to allow sites (or plugins) to add new networks and we welcome new ideas on this front.

**Comment by anxolin** [comment]
When will we see this PR in a release?

**Comment by anxolin** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request closed without merging**
