### PR TITLE
Remove unused RPC handler hook

### PR DESCRIPTION
**Pull request by rekmarks**
## Explanation

Removes an unused RPC handler hook that became unused in #20376. Also adds a check to fail immediately at runtime if extraneous hooks are provided, to prevent this from happening again.

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Review by legobeat — APPROVED** [review]
LGTM!

**Review by legobeat — CHANGES_REQUESTED** [review]
[Failing unit tests](https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/54824/workflows/0c8124fe-3287-4c3f-ba77-0294eb2eea21/jobs/1629608)

```

  403 passing (5s)
  3 failing

  1) MetaMaskController
       MetaMaskController Behaviour
         #setupUntrustedCommunication
           adds a tabId and origin to requests:
     Error: Received unexpected hooks:

setApprovalFlowLoadingText
showApprovalSuccess
showApprovalError
getNetworkConfigurations

      at createMethodMiddleware (app/scripts/lib/rpc-method-middleware/createMethodMiddleware.js:10:1)
      at MetamaskController.currUseCurrencyRateCheck [as setupProviderEngine] (app/scripts/metamask-controller.js:747:60)
      at MetamaskController.setupProviderConnection (app/scripts/metamask-controller.js:713:39)
      at MetamaskController.setupUntrustedCommunication (app/scripts/metamask-controller.js:655:21)
      at Context.<anonymous> (app/scripts/metamask-controller.test.js:1067:11)
      at processImmediate (node:internal/timers:476:21)

  2) MetaMaskController
       MetaMaskController Behaviour
         #setupUntrustedCommunication
           should add only origin to request if tabId not provided:
     Error: Received unexpected hooks:

setApprovalFlowLoadingText
showApprovalSuccess
showApprovalError
getNetworkConfigurations

      at createMethodMiddleware (app/scripts/lib/rpc-method-middleware/createMethodMiddleware.js:10:1)
      at MetamaskController.currUseCurrencyRateCheck [as setupProviderEngine] (app/scripts/metamask-controller.js:747:60)
      at MetamaskController.setupProviderConnection (app/scripts/metamask-controller.js:713:39)
      at MetamaskController.setupUntrustedCommunication (app/scripts/metamask-controller.js:655:21)
      at Context.<anonymous> (app/scripts/metamask-controller.test.js:1109:11)
      at processImmediate (node:internal/timers:476:21)

  3) MetaMaskController
       MetaMaskController Behaviour
         #setupTrustedCommunication
           sets up controller JSON-RPC api for trusted communication:
     Error: Received unexpected hooks:

setApprovalFlowLoadingText
showApprovalSuccess
showApprovalError
getNetworkConfigurations

      at createMethodMiddleware (app/scripts/lib/rpc-method-middleware/createMethodMiddleware.js:10:1)
      at MetamaskController.currUseCurrencyRateCheck [as setupProviderEngine] (app/scripts/metamask-controller.js:747:60)
      at MetamaskController.setupProviderConnection (app/scripts/metamask-controller.js:713:39)
      at MetamaskController.chunk [as setupTrustedCommunication] (app/scripts/metamask-controller.js:670:5)
      at Context.<anonymous> (app/scripts/metamask-controller.test.js:1149:24)
      at processImmediate (node:internal/timers:476:21)



Error: Exited with code '1'
    at runInShell (/home/circleci/project/development/lib/run-command.js:134:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runMocha (/home/circleci/project/test/run-unit-tests.js:81:3)
    at async start (/home/circleci/project/test/run-unit-tests.js:183:7)

Exited with code exit status 1

```

**Comment by gauthierpetetin** [comment]
Hi @rekmarks , is this ticket ready for review?

**Comment by rekmarks** [comment]
Superseded by #24357

**Pull request closed without merging**
