### PR TITLE
Refactor checking if address is contract into a new module.

### LINKED ISSUE #12350: Create helper method for determining whether an address is a contract
We currently have two locations where we check whether a given address is a contract:

https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/controllers/transactions/index.js#L1238-L1250

https://github.com/MetaMask/metamask-extension/blob/develop/ui/ducks/send/send.js#L229-L241

We should abstract the common logic into a helper method. This will then be reusable in other locations in the future.

The helper method should probably go somewhere in the `shared/` directory

Let's add appropriate unit tests too.

### PR DESCRIPTION
**Pull request by segun**
Fixes: #12350

Explanation:  

We currently have two locations where we check whether a given address is a contract:
We should abstract the common logic into a helper method. This will then be reusable in other locations in the future.

  - 
  - 
  -

### CODE REVIEW

**Comment by segun** [comment]
> @segun Was looking through some stuff and it looks like we already have this function:
> 
> https://github.com/MetaMask/metamask-extension/blob/864800b035d722db97641c01cff9b46a3c260ccf/ui/helpers/utils/transactions.util.js#L146-L151
> 
> Is it possible to reuse this somehow? Or, maybe that function should be changed to use your function?

Yeah, I think the idea is this was done is a few places and we should make sure it's only being done in a single place. I somehow missed this one. I will update to use the new code.

**Review by mcmire — DISMISSED** [review]
Looks good!

**Review by jpuri — DISMISSED** [review]
Looks good, I added small feedback.

**Review by danjm — APPROVED** [review]
LGTM!

**Review by mcmire — APPROVED** [review]

**Review by darkwing — APPROVED** [review]

**Pull request merged**
