### PR TITLE
add fsevents policies to policy overrides to avoid policy generation diffs across different operating systems

### PR DESCRIPTION
**Pull request by adonesky1**
@kumavis ✌️

### CODE REVIEW

**Comment by kumavis** [comment]
this is my suggested approach to deal with the platform-specific dep subgraph. downside: its a ton of stuff to add to the override so i kinda hate it. but it does accomplish having the policy being stable across platform differences

**Comment by kumavis** [comment]
commit the matching changes in the `build-system/policy.json` (you'll need to have generated the policy again)

**Review by kumavis — CHANGES_REQUESTED** [review]
commit the matching changes in the `build-system/policy.json` (you'll need to have generated the policy again)

**Comment by adonesky1** [comment]
@kumavis done here https://github.com/MetaMask/metamask-extension/pull/14902/commits/05c7e3b7e90bb6aab8ef882dcebfddabe910ea66

**Comment by brad-decker** [comment]
running this fresh produced a single line diff for me: 

image

**Comment by adonesky1** [comment]
@brad-decker could you push that diff?

**Comment by brad-decker** [comment]
@adonesky1 yup just did

**Review by brad-decker — DISMISSED** [review]

**Comment by adonesky1** [comment]
@brad-decker & @darkwing what OS are you each using?

**Comment by brad-decker** [comment]
I'm using ubuntu 22 on a system76 machine.

**Comment by adonesky1** [comment]
🤷‍♂️

**Comment by kumavis** [comment]
woof, what a diff

**Comment by kumavis** [comment]
@darkwing what system are you on

**Comment by kumavis** [comment]
lets get this updated and merged so we have a smaller policy diff

**Review by brad-decker — APPROVED** [review]

**Comment by darkwing** [comment]
I got this diff on Mac OS https://gist.github.com/darkwing/dab2c1cc1e444d8ead7581ec0b9e9603

**Comment by brad-decker** [comment]
@adonesky1 i'm going to close this in favor of doing cross OS testing after the yarn3 branch merges.

**Pull request closed without merging**
