### PR TITLE
Fix GetEncryptionKey TypeError Cannot destructure property 'msgParams' of 'txData'

### LINKED ISSUE #17747: [Bug]: `TypError: Cannot destructure property 'msgParams' of 'txData' as it is undefined.` when calling GetEncryptionKey
### Describe the bug

**Problem**: when I call the Get Encryption Key function I land on the MetaMask Error page and see the error `Cannot destructure property 'msgParams' of 'txData' as it is undefined.`

https://user-images.githubusercontent.com/54408225/218747227-35aa3eee-7af6-4183-996c-299c8f838406.mp4

### Steps to reproduce

1. Open MM full view
2. On a new browser tab, go to Test Dapp
3. Connect to Test Dapp
4. Click Get Encryption Keys
5. Open MM full view
6. Accept -- land on Error page

### Error messages or log output

_No response_

### Version

10.26.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by digiwand**
## Explanation

Fixes https://github.com/MetaMask/metamask-extension/issues/17747 (v10.26.0 bug)
"TypeError: Cannot destructure property 'msgParams' of 'txData' as it is undefined when calling GetEncryptionKey"

The bug appears to be caused by an underlying issue that surfaced after this commit  https://github.com/MetaMask/metamask-extension/commit/20800444dd38416d8ddd0324bd9d73f0be1b070e (PR https://github.com/MetaMask/metamask-extension/pull/17473)

### Description of bug and fix

During the transition back to the activity page, the component is still mounted while the transaction no longer exists in the unconfirmedTransactions list as it changes its status from `unconfirmed`. This causes the. bug.

This PR uses the confirmTransaction in state as it should represent the real-time, active transaction regardless of transaction status. 

### Testing

We have a related e2e test here: `test/e2e/tests/encrypt-decrypt.spec.js`, however, this didn't catch the bug because it only tests the notification. When the bug occurs, the transaction is still completed. From the notification, it will briefly show the error and then close. Then the dapp continues to work as expected. From home.html, the bug show the error and stopped the app.

Since we plan to deprecate these encrypt and decrypt components, I think it's okay to skip writing additional tests for this.

## Manual Testing Steps

copied from Issue ticket:

- Open MM full view
- On a new browser tab, go to Test Dapp
- Connect to Test Dapp
- Click Get Encryption Keys
- Open MM full view
- Accept -- land on Error page

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [x] How reviewers can test my changes
- [x] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [x] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Review by blackdevelopa — DISMISSED** [review]
Oh nice.

**Comment by PeterYinusa** [comment]
@digiwand I'm still able to reproduce the error on this branch

**Comment by jpuri** [comment]
@digiwand: I am hoping to eventually be able to get rid of `confirmTransaction` we should not depend on it. We should rather fix this component to not throw error if transaction is not defined.

**Review by pedronfigueiredo — DISMISSED** [review]

**Review by jpuri — DISMISSED** [review]
Seems to work well 👍

**Comment by Sylvia24** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Review by jpuri — APPROVED** [review]

**Review by PeterYinusa — APPROVED** [review]
LGTM

**Pull request merged**
