### PR TITLE
Update sinon and proxyquire

### LINKED ISSUE #8024: Update Sinon version
The version of sinon we're using is 3 major versions behind. Let's fix that.

```bash
$ yarn add --dev sinon
$ yarn test:unit
[...]
7 failing
```

### PR DESCRIPTION
**Pull request by whymarrh**
Closes #8024

This PR updates our `sinon` and `proxyquire` versions. We had a few too many calls to `sinon.restore` that were breaking tests/making test order-dependent... so I've remove all of them.

### CODE REVIEW

**Comment by whymarrh** [comment]
Debugging the inconsistent test results due to our `sinon.restore` calls was _quite_ fun. 😑

**Comment by Gudahtt** [comment]
Wait, how was `sinon.restore()` resulting in inconsistent test results?

To quote their [general setup guide](https://sinonjs.org/releases/v8.1.1/general-setup/):
>By default these are created in the _default sandbox_. Be sure to `restore` this sandbox after each test. ... Forgetting to restore your sandbox results in a memory leak.

If anything we should be using `sinon.restore` _more often_, or in a global `afterEach` hook.

**Comment by whymarrh** [comment]
> Wait, how was `sinon.restore()` resulting in inconsistent test results?

That's good question, especially in the context of that quote from the docs. Here's what I was looking at:

1. Checking out 0ea516d results in 7 failing tests
2. [A good few rounds of trying to figure out why these were failing]
3. The realization that:
    - Running the failing tests in isolation works
        - e.g. `yarn mocha --inspect --exit --require test/env.js --require test/setup.js ui/app/pages/send/tests/send-component.test.js`
    - Running this fails: `yarn mocha --inspect --exit --require test/env.js --require test/setup.js ui/app/pages/first-time-flow/welcome/tests/welcome.test.js ui/app/pages/send/tests/send-component.test.js`

For some reason, the `sinon.restore` calls seemed to make sense to me to remove, So I removed them. I now realized that doesn't make any sense, as you've pointed out. We had global state in the tests that was the root issue.

> [...] we should be using `sinon.restore` _more often_ [...]

Yes, now instead of b3e312f I've introduced 1ab0e97.

**Review by Gudahtt — APPROVED** [review]
Thanks! This seems reasonable.

I've been meaning to update `sinon` for a while now - I can't recall what stopped me 🤔 . I probably ran into these failures and gave up.

**Pull request merged**
