### PR TITLE
Use Webpack 5 for Storybook

### PR DESCRIPTION
**Pull request by Mrtenz**
Storybook uses Webpack 4 by default. In order to support some Snaps packages, we need Webpack 5.

### CODE REVIEW

**Review by georgewrmarshall — COMMENTED** [review]
Oh nice 👍 Thank you for making this update! I'm wondering if we could also update all the related storybook packages to `^6.5.13` using:

```
npx storybook@latest upgrade
```

Also seems to break a few stories but not certain as to why?

## Before

[Storybook on Github pages](https://metamask.github.io/metamask-storybook/?path=/story/ui-components-app-transaction-list-item-transaction-list-item-stories-js--contract-interaction) 

https://user-images.githubusercontent.com/8112138/203844023-f9f3a810-e503-45c2-9dfe-72f97f94f88d.mov

## After
Storybook on local

https://user-images.githubusercontent.com/8112138/203844125-5cabc306-1c6d-41b2-a7e2-a07fafebe305.mov

**Comment by Mrtenz** [comment]
> I'm wondering if we could also update all the related storybook packages to `^6.5.13`

Done!

> Also seems to break a few stories but not certain as to why?

Strange. It was working on my end, but I will try again.

**Comment by Mrtenz** [comment]
image

@georgewrmarshall It's working here. Maybe try `rm -rf node_modules && yarn storybook`?

**Comment by georgewrmarshall** [comment]
@Mrtenz nuked `node_modules` and still getting errors. Is your console reasonably clean in developer tools? The story that is broken for me is `TransactionListItem`

**Comment by FrederikBolding** [comment]
@georgewrmarshall After my changes today this seems to run without issues in the console for me. Can you verify so we can get this reviewed and merged?

**Review by georgewrmarshall — APPROVED** [review]
Excellent! Thanks so much @Mrtenz and @FrederikBolding! You even fixed the SectionShape issue and made the MetaMask template renderer - render. That story has been broken for a while. 💯 🙏 🙇

**Review by GuillaumeRx — APPROVED** [review]

**Comment by kumavis** [comment]
policy changes look good

**Pull request merged**
