### PR TITLE
info.js Remove width element to fix email layout

### PR DESCRIPTION
**Pull request by abitrolly**
Fix for #2855 which is gone from master for some reason

### CODE REVIEW

**Comment by whymarrh** [comment]
Hey @abitrolly, this is indeed in the codebase as of 4.8.0:

https://github.com/MetaMask/metamask-extension/blob/d910c35e90d0d725e86b7743538b6c6c429f26f0/old-ui/app/info.js#L138-L144

I think we can close this PR. Thanks!

**Comment by abitrolly** [comment]
@whymarrh you mean merge? Because the fix is not in 4.8.0

image

**Comment by whymarrh** [comment]
> you mean merge?

I didn't mean merge, no, but I was incorrect about the direction of the change.

> Because the fix is not in 4.8.0

This PR _removes_ the line so it is indeed valid. I misread the diff.

Would you mind rebasing this on the latest `develop` so we can merge this?

**Comment by abitrolly** [comment]
@whymarrh rebased. But take a notice that if this commit got reverted, then all other fixes in the same timespan got reverted too.

**Review by whymarrh — APPROVED** [review]

**Pull request merged**
