### PR TITLE
Allow Dapps to Specify Nonce

### PR DESCRIPTION
**Pull request by danfinlay**
Integrates work by @vicnaum from #2679, and adds a constraint that disallows nonces that are larger than the next valid nonce, to avoid potentially confusing situations.

Bumps changelog and version for a quick release to alleviate CryptoKitty load.

We discussed also adding a validation that allowed no nonce lower than the earliest pending tx, but since the network will already enforce this, keeping it smaller for simplicity for now.

### CODE REVIEW

**Review by kumavis — APPROVED** [review]
nice and clean

**Comment by kumavis** [comment]
QAing now

**Comment by kumavis** [comment]
non-blocking problem:
- [ ] this nonce validation does not happen when the dapp submits the tx, only after user approval

problems:
- [ ] error does not get back to dapp in callback

**Comment by kumavis** [comment]
fix incomming

**Comment by eloudsa** [comment]
Did you tried this fix with a in-memory Ethereum node like Truffle Develop, testrpc or Ganache?

If I import an account from Ganache and I send transactions from it, I have issues when I restart Ganache because Metamask refuses to send transactions due to nonce problems.

**Comment by danfinlay** [comment]
You're waiting for this fix: https://github.com/MetaMask/metamask-extension/pull/2623

**Pull request merged**
