### PR TITLE
feat: Add support for mode network

### PR DESCRIPTION
**Pull request by agileurbanite**
## **Description**

Add support for https://mode.network a new L2 as part of the OP Superchain.

## **Related issues**

N/A

## **Manual testing steps**

N/A

## **Screenshots/Recordings**

N/A

### **Before**

N/A

### **After**

N/A

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by agileurbanite** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by okalenyk** [comment]
+1

**Comment by fede2442** [comment]
+1

**Comment by HermesGoodgod** [comment]
+1

**Comment by wolfcito** [comment]
+1

**Comment by joshuanwankwo** [comment]
+1

**Comment by Gordiancyber** [comment]
+1

**Comment by therevealer** [comment]
+1

**Comment by kohasummons** [comment]
+1

**Comment by salimtb** [comment]
hey @agileurbanite ,
thanks for your contribution.
it seems that it's not possible to go to the edit network page once the network has been added (watch the video below).

https://github.com/MetaMask/metamask-extension/assets/26223211/5426740b-363b-48dd-83fb-809f0396a41c

**Comment by emilianobonassi** [comment]
for context, this PR is for adding support to show L1 fees for ancient8 network based on OP Stack deployed with Conduit

similar stuff asked for Zora

https://github.com/MetaMask/metamask-extension/pull/20501

**Comment by agileurbanite** [comment]
@salimtb hope the comment by @emilianobonassi provides clarity

**Comment by agileurbanite** [comment]
@bschorchit can we get visibility on this PR as well?

**Comment by agileurbanite** [comment]
bump @salimtb @bschorchit 
leia-youre-my-only-hope

**Comment by agileurbanite** [comment]
bump @danjm

**Comment by agileurbanite** [comment]
Bump @danfinlay

**Pull request closed without merging**
