### PR TITLE
Version v11.15.0

### PR DESCRIPTION
**Pull request by benjisclowder**
RC v11.15.0

### CODE REVIEW

**Comment by benjisclowder** [comment]
[Manual test scenarios:](https://github.com/MetaMask/metamask-extension/tree/develop/test/scenarios)

**Chrome**

- [ ]  Onboarding - create a wallet
- [ ]  Onboarding - import a wallet
- [ ]  Keyring - connect hardware wallet
- [ ]  Keyring - reset a wallet
- [ ]  Transactions - send native token origin MM
- [ ]  Transactions - send native token origin dapp
- [ ]  Transactions - send ERC20 token origin MM
- [ ]  Transactions - send ERC20 token origin dapp
- [ ]  Transactions - send ERC721 token origin MM
- [ ]  Transactions - send ERC721 token origin dapp
- [ ]  Transactions - speed up transaction
- [ ]  Transactions - cancel transaction
- [ ]  Transactions - deploy failing transaction
- [ ]  Transactions - deposit and withdraw
- [ ]  Transactions - navigate multiple transactions
- [ ]  Tokens - import ERC20 token origin MM
- [ ]  Tokens - import ERC20 token origin dapp
- [ ]  Tokens - import ERC721 token origin MM
- [ ]  Tokens - import ERC721 token origin dapp
- [ ]  Tokens - import ERC1155 token origin MM
- [ ]  Tokens - import ERC1155 token origin dapp
- [ ]  Tokens - approve ERC1155 token
- [ ]  Tokens - approve ERC20 token
- [ ]  Tokens - approve ERC721 token
- [ ]  Tokens - autodetect tokens
- [ ]  Tokens - autodetect NFTs
- [ ]  Tokens - approve erc20 custom amount
- [ ]  ENS - name resolution
- [ ]  Phishing - warning page
- [ ]  Network - add custom network manually
- [ ]  Network - add custom network from the list of popular networks
- [ ]  Network - add custom network from dApp
- [ ]  Network - update networks
- [ ]  Network - switching networks
- [ ]  Network - delete networks from the dropdown list
- [ ]  Network - delete networks in Settings
- [ ]  Backup - backup user data
- [ ]  Backup - restore user data
- [ ]  Metrics - send event metrics
- [ ]  Address-book - add a contact to the address book
- [ ]  Address-book - remove a contact from the address book
- [ ]  Address-book - update a contact in the address book
- [ ]  Gas fee - EIP-1559 gas
- [ ]  Gas fee - legacy gas
- [ ]  Sign - eth sign
- [ ]  Sign - personal sign
- [ ]  Sign - sign in with ethereum
- [ ]  Sign - sign typed with data
- [ ]  Sign - sign typed data v3 with hardware wallet
- [ ]  Sign - sign typed data v4 with hardware wallet
- [ ]  Sign - personal sign with hardware wallet
- [ ]  Sign - eth sign with hardware wallet
- [ ]  Permissions - connecting and disconnecting from a dapp
- [ ]  Swap - smart swap
- [ ]  Swap - swap eth
- [ ]  Incoming transactions - receive native token
- [ ]  Settings - about MetaMask
- [ ]  Settings - general - change language
- [ ]  Settings - advanced - check custom nonce toggle
- [ ]  Settings - advanced - show hex data
- [ ]  Contract - deploy contract, mint and import NFT with hardware wallet
- [ ]  Contract - hardware wallet qr based connect
- [ ]  Contract - send token with hardware wallet

 
**Firefox**

 

- [ ] Onboarding - create a wallet
- [ ]  Onboarding - import a wallet
- [ ]  Keyring - connect hardware wallet
- [ ]  Keyring - reset a wallet
- [ ]  Transactions - send native token origin MM
- [ ]  Transactions - send native token origin dapp
- [ ]  Transactions - send ERC20 token origin MM
- [ ]  Transactions - send ERC20 token origin dapp
- [ ]  Transactions - send ERC721 token origin MM
- [ ]  Transactions - send ERC721 token origin dapp
- [ ]  Transactions - speed up transaction
- [ ]  Transactions - cancel transaction
- [ ]  Transactions - deploy failing transaction
- [ ]  Transactions - deposit and withdraw
- [ ]  Transactions - navigate multiple transactions
- [ ]  Tokens - import ERC20 token origin MM
- [ ]  Tokens - import ERC20 token origin dapp
- [ ]  Tokens - import ERC721 token origin MM
- [ ]  Tokens - import ERC721 token origin dapp
- [ ]  Tokens - import ERC1155 token origin MM
- [ ]  Tokens - import ERC1155 token origin dapp
- [ ]  Tokens - approve ERC1155 token
- [ ]  Tokens - approve ERC20 token
- [ ]  Tokens - approve ERC721 token
- [ ]  Tokens - autodetect tokens
- [ ]  Tokens - autodetect NFTs
- [ ]  Tokens - approve erc20 custom amount
- [ ]  ENS - name resolution
- [ ]  Phishing - warning page
- [ ]  Network - add custom network manually
- [ ]  Network - add custom network from the list of popular networks
- [ ]  Network - add custom network from dApp
- [ ]  Network - update networks
- [ ]  Network - switching networks
- [ ]  Network - delete networks from the dropdown list
- [ ]  Network - delete networks in Settings
- [ ]  Backup - backup user data
- [ ]  Backup - restore user data
- [ ]  Metrics - send event metrics
- [ ]  Address-book - add a contact to the address book
- [ ]  Address-book - remove a contact from the address book
- [ ]  Address-book - update a contact in the address book
- [ ]  Gas fee - EIP-1559 gas
- [ ]  Gas fee - legacy gas
- [ ]  Sign - eth sign
- [ ]  Sign - personal sign
- [ ]  Sign - sign in with ethereum
- [ ]  Sign - sign typed with data
- [ ]  Sign - sign typed data v3 with hardware wallet
- [ ]  Sign - sign typed data v4 with hardware wallet
- [ ]  Sign - personal sign with hardware wallet
- [ ]  Sign - eth sign with hardware wallet
- [ ]  Permissions - connecting and disconnecting from a dapp
- [ ]  Swap - smart swap
- [ ]  Swap - swap eth
- [ ]  Incoming transactions - receive native token
- [ ]  Settings - about MetaMask
- [ ]  Settings - general - change language
- [ ]  Settings - advanced - check custom nonce toggle
- [ ]  Settings - advanced - show hex data
- [ ]  Contract - deploy contract, mint and import NFT with hardware wallet
- [ ]  Contract - hardware wallet qr based connect
- [ ]  Contract - send token with hardware wallet

**Comment by benjisclowder** [comment]
We need teams' approval on April 22 at the latest to stick to our 7-day release cut-submission trial plan for the following 4 RC's.

Instructions for Team Review
1. Review Changes: Refer to the [Release Tracker for v11.15.0](https://docs.google.com/spreadsheets/d/1tsoodlAlyvEUpkkcNcbZ4PM9HuC9cEM80RZeoVv5OCQ/edit#gid=2144825527) to see all changes relevant to your team.
2. Log Bugs: If you find any issues, log them in the release tracker and attach them to [MetaMask/MetaMask-planning#2364](https://github.com/MetaMask/MetaMask-planning/issues/2364).
3. Approval: After reviewing, indicate your team's approval by:
Marking the checkbox next to your team's name in [this comment]().
Optionally, leave a comment for additional information.

Your thorough review ensures a smooth and successful release. If you have any questions please reach out to extension platform team or in the [#metamask-qa](https://consensys.slack.com/archives/C01U65ZUS2E) slack channel. Thank you for your collaboration!

- [ ] Assets: [@sahar.fehri](https://github.com/sahar-fehri) / [@albert.feng](https://github.com/alfeng6) - There are 11 Assets changes in v11.15.0
- [ ] Confirmation Systems: [@tatiana.bobritsky](https://github.com/sleepytanya) - There are 10 Confirmation Systems changes in v11.15.0.
- [ ] Confirmation UX: [@mariona.farell](https://consensys.slack.com/team/U032XS4NP9U) - There are 21 Confirmations UX changes in v11.15.0
- [ ] DappAPI: [@jiexi.luan](https://github.com/jiexi) - There are 2 DappAPI changes in v11.15.0.
- [ ] Design/Systems: @georgewrmarshall - There are 2 Design/Systems changes in v11.15.0.
- [ ] MMI: [@antonio.regadas](https://github.com/zone-live) / [@Shane T](https://github.com/shane-t) - There are 12 MMI changes in v11.15.0.
- [ ] Snaps: [@bowen.sanders](https://consensys.slack.com/team/U030WPBCEUW) / [@frederik.bolding](https://github.com/FrederikBolding) / [@christian.montoya](https://github.com/Montoya) - There are 7 Snaps changes in v11.15.0.
- [ ] Swaps: [@davibroc](https://github.com/davibroc) / [@dan437](https://github.com/dan437) - There are 2 Swaps change in v11.15.0.
- [ ] Wallet UX: [@david.walsh](https://consensys.slack.com/team/U01B02GRABF) / [@nidhi.kumari ](https://github.com/NidhiKJha)- There are 10 Wallet UX changes in v11.15.0 (8 non-main).

**Comment by sleepytanya** [comment]
🟢  Approval from Confirmation Systems team.

**Comment by seaona** [comment]
:green_circle:  QA Sign Off from Confirmations UX team.
Notes:
- there is a [minor issue](https://github.com/MetaMask/metamask-extension/issues/24157) related to ppom+metrics, but since it's already in prod, we can fix it in a subsequent release.
- I've opened a couple of Smart Transaction bugs, but since it's not from our team, I defer to the corresponding team to decide if they want to fix those or not, since I'm lacking the context.

**Comment by georgewrmarshall** [comment]
🟢 Approval from @MetaMask/design-system team

**Comment by davibroc** [comment]
🟢 QA Sign Off from Swap team

**Comment by jiexi** [comment]
🟢 DappAPI sign off. Apologies for the delay

**Comment by Gudahtt** [comment]
🟢 QA Sign Off from me on #24106
(I repeated the manual testing steps, and it worked without a hitch)

**Review by danjm — APPROVED** [review]

**Pull request merged**
