### PR TITLE
move search icon || update imports || add to story

### LINKED ISSUE #13563: Move SearchIcon to icon folder and create story
**Description**
Move `SearchIcon` component file from `ui/components/ui/search-icon/search-icon.component.js` to `ui/components/ui/icon/search-icon.component.js`

Add to icon stories `ui/components/ui/icon/icon.stories.js` under "Other Icons"

Screen Shot 2022-02-09 at 10 37 15 AM

### PR DESCRIPTION
**Pull request by daniiba**
## Explanation

Currently, 
SearchIcon is stored in ui/components/ui/search-icon/search-icon.component.js  

Should be stored in ui/components/ui/icon/search-icon.component.js and added to  icon stories 

## More Information
* Fixes #13563

### Before

image

### After

image

## Manual Testing Steps

<!--
How should reviewers and QA manually test your changes? For instance:

- Start storybook
- Go to /story/ui-components-ui-icon-icon-stories-js--default-story

## Pre-Merge Checklist

- [ ] PR template is filled out
- [ ] **IF** this PR fixes a bug, a test that _would have_ caught the bug has been added
- [ ] PR is linked to the appropriate GitHub issue
- [ ] PR has been added to the appropriate release Milestone

### + If there are functional changes:

- [ ] Manual testing complete & passed
- [ ] "Extension QA Board" label has been applied

### CODE REVIEW

**Comment by daniiba** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by georgewrmarshall — DISMISSED** [review]
Hey @daniiba! Thanks so much for picking this up it's looking really good! I made a few small adjustments as I had them in my local already.

- Updated icon component api to be more consistent with other icons and removed onclick as it was not used in any of the SearcIcon instances

Screen Shot 2022-06-15 at 11 35 19 AM

- Updated the color of the icon to match other search icons

Screen Shot 2022-06-15 at 11 39 33 AMScreen Shot 2022-06-15 at 11 40 20 AMScreen Shot 2022-06-15 at 11 40 44 AM

Verified in storybook! You may have to pull and rebase from develop if e2e tests are failing. I think there may have been a recent update.

**Comment by daniiba** [comment]
Thank you for the feedback! 
I also saw that there is a different search Icon being used in the ImportToken page:
https://github.com/MetaMask/metamask-extension/blob/ebf967562bf87d316b531d9a5367a72d0e97736f/ui/pages/import-token/import-token.component.js#L604

and in the TokenListPlaceholder Component:
https://github.com/MetaMask/metamask-extension/blob/ebf967562bf87d316b531d9a5367a72d0e97736f/ui/pages/import-token/token-list/token-list-placeholder/token-list-placeholder.component.js#L14

Do we want to switch  them out for the SearchIcon aswell?

**Comment by georgewrmarshall** [comment]
@daniiba that's a great idea! 💯  found a couple more instances that could be switched out too. We are in the process of updating our icon library so hopefully we should have more consistent looking icons in the near future 😅 

Screen Shot 2022-06-15 at 12 59 47 PM

**Review by georgewrmarshall — APPROVED** [review]
LGTM! 💯 Thanks for your contribution 🙏

**Review by darkwing — APPROVED** [review]
Thank you @daniiba !

**Pull request merged**
