### PR TITLE
Enable Lavamoat for Home screen

### PR DESCRIPTION
**Pull request by kumavis**
part of incremental introduction of lavamoat

Adds lavamoat protections to the home screen (does not include popup)

### CODE REVIEW

**Review by darkwing — APPROVED** [review]
Home screen working for me!

**Comment by mcmire** [comment]
@kumavis Just to clarify, to test this, pulling up the extension in full screen view after entering a password (or going back to the main screen if you're already authenticated) should work?

**Comment by mcmire** [comment]
@kumavis We still want to do this?

**Comment by kumavis** [comment]
@mcmire correct, this only affects the full screen. pr needs to merge with main and have `yarn lavamoat:auto` run to be updated

**Comment by kumavis** [comment]
the next step is #12939 which can be separate or combined

**Pull request closed without merging**
