### PR TITLE
Fix approve all warning modal

### LINKED ISSUE #18583: [Bug]: Error: Insufficient number of substitutions for key "nftWarningContentBold" with locale "en"
### Describe the bug

https://user-images.githubusercontent.com/53189696/231854309-fe464878-e729-4bb9-9174-673c880f3750.mov

### Steps to reproduce

1. log in to the extension
2. navigate to test dapp
3. deploy an erc1155
4. mint some erc1155
5. click set approval for all, ignore the popup 
6. switch to the extension
7. open the unapproved transaction fro the activity list
8. click confirm

### Error messages or log output

```shell
i18n-helper.tsx:117 Error: Insufficient number of substitutions for key "nftWarningContentBold" with locale "en"
  at i18n-helper.tsx:114:23
  at Array.map (<anonymous>)
  at a.getMessage (i18n-helper.tsx:99:36)
  at i18n.js:20:7
  at h (set-approval-for-all-warning.js:108:14)
  at ha (react-dom.production.min.js:154:1)
  at Cu (react-dom.production.min.js:259:1)
  at Tl (react-dom.production.min.js:230:1)
  at gl (react-dom.production.min.js:229:1)
  at fl (react-dom.production.min.js:223:1)
  at react-dom.production.min.js:121:1
  at n.unstable_runWithPriority (scheduler.production.min.js:18:1)
  at $o (react-dom.production.min.js:120:1)
  at Zo (react-dom.production.min.js:121:1)
  at Jo (react-dom.production.min.js:120:1)
  at ue (react-dom.production.min.js:285:1)
  at Pn (react-dom.production.min.js:82:1)
(
```

### Version

10.29

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jpuri**
Fixes: #18583

Regression error in approve all warning modal.

### CODE REVIEW

**Comment by seaona** [comment]
@jpuri from QA looks good! I see the issue fixed for all signature types
- eth_sign
- personal_sign
- sign_typeddata
- sign_typeddata_v3
- sign_typeddata_v4

[Screencast from 17-04-23 11:26:46.webm](https://user-images.githubusercontent.com/54408225/232443616-f9429050-a25b-4ad5-9e14-e1b2513376c0.webm)

**Comment by NiranjanaBinoy** [comment]
@jpuri I am still getting the error in the console while testing the PR

**Comment by jpuri** [comment]
@NiranjanaBinoy : thanks for bringing this up, I fixed this can you plz re-review.

**Review by danjm — APPROVED** [review]
LGTM

**Review by NiranjanaBinoy — APPROVED** [review]
LGTM

**Review by digiwand — APPROVED** [review]

**Pull request merged**
