### PR TITLE
chore: bump `@metamask/eth-snap-keyring` to version 4.4.0

### PR DESCRIPTION
**Pull request by ccharly**
## **Description**

Bumping the Snap bridge. This new version will now sanitize the redirect URL passed by a Snap.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/27864?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/accounts-planning/issues/585

## **Manual testing steps**

1. `yarn start:flask`
2. Use the SSK Snap with the following branch: `test/keyring-snap-bridge-70`
3. Run the SSK dapp + Snap using `yarn start`, go to http://localhost:8000/
4. Install the Snap
5. Make sure that "Use Synchronous Approval" on the SSK dapp is **disabled**
6. Create an SSK account
7. Go to https://metamask.github.io/test-dapp/
8. Connect your SSK account
9. Use the personal sign test
10. You should see a sanitized URL `https://ioi.com?fake=1` on the Snap dialog

### **Before**

Screenshot 2024-10-11 at 11 19 52

### **After**

Screenshot 2024-10-11 at 12 22 59

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by k-g-j — DISMISSED** [review]
LGTM in code and manual testing!

Screenshot 2024-10-16 at 11 30 28 AM

**Comment by k-g-j** [comment]
The URL displayed in the UI is correct: https://ioi.com/?fake=1

Screenshot 2024-10-16 at 1 17 55 PM

**Review by dabossdana — APPROVED** [review]
Remove from sharing

**Comment by legobeat** [comment]
@metamaskbot update-policies

**Review by legobeat — APPROVED** [review]
Supply-chain wise LGTM but have not performed any testing

**Review by danroc — APPROVED** [review]

**Pull request merged**
