### PR TITLE
Refactor confirm page container component from class to functional co…

### LINKED ISSUE #16824: Refactor componentDidMount using the hook API useEffect
## Background
https://github.com/MetaMask/metamask-extension/pull/16195#discussion_r1040995609

### PR DESCRIPTION
**Pull request by amerkadicE**
## Explanation

Just a code refactor for Confirm page container component from class to functional component

Fixes #16824 

## Manual Testing Steps

Check if Confirm page works as before.
For example, Set Approval for all screens.

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [x] How reviewers can test my changes
- [x] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Comment by fejzic** [comment]
Verified by QA

**Comment by jpuri** [comment]
Changes look good, but they are touching very important component, I would suggest QA of the PR.

**Review by jpuri — DISMISSED** [review]
LGTM

**Review by jpuri — DISMISSED** [review]

**Comment by bschorchit** [comment]
@pedronfigueiredo could you give this PR a review once you have a chance? Asking due to context [here](https://github.com/MetaMask/metamask-extension/pull/16195#discussion_r1040995609)

**Review by jpuri — APPROVED** [review]

**Review by darkwing — APPROVED** [review]

**Pull request merged**
