### PR TITLE
fix: display link to privacy-policy explanation in onboarding flow

### PR DESCRIPTION
**Pull request by matteoscurati**
## **Description**

This PR adds a link to the Metametrics page during the onboarding process to explain to the user how their data will be managed using the new profile syncing feature.

The user is redirected to this link: https://support.metamask.io/privacy-and-security/profile-privacy#how-is-the-profile-created

This is the Figma with the requested modification: https://www.figma.com/design/1otUTgYHYD7A77pgP7wT2v/MetaMetrics-update?node-id=3-275&t=bw8aqpz5nBQ6rTVV-0

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/26038?quickstart=1)

## **Related issues**

Fixes:

## **Manual testing steps**

1. During the onboarding process
2. On the Metametrics page
3. Verify the presence of the text and the link

### **Before**

Screenshot 2024-07-23 at 08 26 12

### **After**

Screenshot 2024-07-23 at 16 39 37

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by Prithpal-Sooriya — DISMISSED** [review]

**Comment by Avazbek84** [comment]
Asss

**Review by Avazbek84 — APPROVED** [review]

**Review by Prithpal-Sooriya — DISMISSED** [review]

**Comment by jonybur** [comment]
The figma file shows the placement of the buttons as vertical instead of horizontal.

Also the link redirects to https://support.metamask.io/privacy-and-security/profile-privacy#how-is-the-profile-created, is this correct?

Screenshot 2024-07-23 at 18 18 32

**Review by jonybur — CHANGES_REQUESTED** [review]
~The figma file shows the placement of the buttons as vertical instead of horizontal.~

~Also the link redirects to https://support.metamask.io/privacy-and-security/profile-privacy#how-is-the-profile-created, is this correct?~

Both questions resolved by @hesterbruikman

**Review by jonybur — DISMISSED** [review]
All good

**Review by Prithpal-Sooriya — APPROVED** [review]

**Review by mathieuartu — APPROVED** [review]
🛹

**Comment by georgewrmarshall** [comment]
Hey @matteoscurati, It looks like there was a chance to remove some deprecated code by updating the `Box` import statement to the TypeScript version from the component library, as well as replacing the `Button` component. When you hover over the strikethrough code, it provides specific instructions and a link to the issue for removal. Do you think there’s any way we could make these updates more noticeable in the future?
Screenshot 2024-07-26 at 2 32 40 PM
Screenshot 2024-07-26 at 2 33 46 PM

**Comment by georgewrmarshall** [comment]
Created a fix here https://github.com/MetaMask/metamask-extension/pull/26207

**Pull request merged**
