### PR TITLE
Update messages.json

### PR DESCRIPTION
**Pull request by ystartgo**
add more translations
I have read the CLA Document and I hereby sign the CLA

### CODE REVIEW

**Comment by ystartgo** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ystartgo** [comment]
> **CLA Signature Action:** All authors have signed the CLA. You may need to manually re-run the blocking PR check if it doesn't pass in a few minutes.

I have read the CLA Document and I hereby sign the CLA

**Review by darkwing — CHANGES_REQUESTED** [review]
Thank you for the contribution @ystartgo !   `yarn:lint fix` will fix the lint problem!

**Comment by brad-decker** [comment]
Thank you for your contribution @ystartgo -- if you'd like to rebase this and then apply @darkwing 's suggestion you may re-open this for consideration!

**Pull request closed without merging**
