### PR TITLE
fix: upgrade transaction-controller to 32.0.0 to fix mmi

### PR DESCRIPTION
**Pull request by dbrans**
> [!NOTE]
> This PR is intended to be cherry-picked into RC 11.17.0 after being merged into develop

## **Description**
Upgrade transaction-controller to get this fix: https://github.com/MetaMask/core/pull/4343

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/24947?quickstart=1)

## **Related issues**

Fixes:
A recent update to the transaction-controller has made the TransactionMeta object passed to the afterSign hook frozen. This change prevents adding new properties, leading to the error: “Cannot add property custodyId, object is not extensible.” This bug is breaking all transactions for MMI as the original txMeta cannot store required properties like custodyId.

Blocked by https://github.com/MetaMask/metamask-extension/pull/24861 
Blocked by https://github.com/MetaMask/metamask-extension/pull/24913

## **Manual testing steps**
I followed these steps to test the fix:
1. yarn && yarn start:mmi
2. create a new wallet
3. visit https://saturn-custody-ui.dev.metamask-institutional.io/ and add two custodial addresses
4. send 0ETH from one custodial address to the other

You should see a popup with an Approve button. Before this fix, the transaction would appear in the activity tab with an error.

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by dbrans** [comment]
@metamaskbot update-policies

**Comment by dbrans** [comment]
@metamaskbot update-policies

**Comment by legobeat** [comment]
@dbrans Can we get this on top of #24861 so we can update it 29 -> 30 -> 32? :)

**Review by zone-live — DISMISSED** [review]
LGTM!

**Comment by legobeat** [comment]
@zone-live #24861

**Comment by zone-live** [comment]
@metamaskbot update-policies

**Comment by zone-live** [comment]
Hi @dbrans, I noticed it had some conflicts with develop, so I went ahead and fixed them, think it looks good 👍🏼

**Review by zone-live — APPROVED** [review]

**Review by albertolive — APPROVED** [review]

**Review by DDDDDanica — APPROVED** [review]

**Pull request merged**
