### PR TITLE
Update SmartTransactionsController to v3

### LINKED ISSUE #16479: [Bug]: Cannot perform a Send on Sepolia network. MM stays loading indefinitely
### Describe the bug

**Problem**: I cannot perform a Send on Sepolia network. MM stays loading. If I refresh the browser, I see that tx stays stuck on a  Pending state.

https://user-images.githubusercontent.com/54408225/201647673-fe2ae450-b191-4f70-ada0-2966c4e63023.mp4

### Steps to reproduce

1. Unlock MM
2. Change to Sepolia network
3. Click Send
4. Add recipient and input amounts
5. Confirm tx -- see MM stays loading indefinitely
6. Refresh the browser -- see tx stays Pending

### Error messages or log output

_No response_

### Version

10.23.0

### Build type

_No response_

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Gudahtt**
This update drops support for Node.js v12, and it includes a bug fix for a deadlock encountered when using swaps on unsupported testnets.

Fixes #16479

## Manual Testing Steps

(derived from the steps listed in #16479)

- Unlock MM
- Change to Goerli
- Click Swap
- Enable Smart Transactions
- Add amount and token
- Click Review Swap
- Click Swap
- The swap should fail rather than loading indefinitely.

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [x] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [x] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Review by brad-decker — APPROVED** [review]

**Comment by brad-decker** [comment]
Tested and looks good to me

**Review by danjm — APPROVED** [review]

**Comment by Gudahtt** [comment]
Thanks @seaona !

I am not sure what those errors are. Maybe they would be fixed by #16500? If not, that's concerning.

**Comment by danjm** [comment]
yes, I believe they are fixed by #16500

**Comment by seaona** [comment]
@Gudahtt @danjm I confirm these errors are not present on the RC branch, which includes both PRs

**Pull request merged**
