### PR TITLE
Use jest to run ui/**/*.test.js

### PR DESCRIPTION
**Pull request by tmashuang**
Large PR to change the ui/'s tests runner to jest.

### CODE REVIEW

**Comment by brad-decker** [comment]
🚀 🎸 🤘🏻

**Review by brad-decker — COMMENTED** [review]
I'm going to do a more thorough review soon, but wanted to say that from a surface level this looks great. Number of tests match up good so I don't think we're missing anything. long live the reign of jest.

**Comment by tmashuang** [comment]
There are still some inconsistencies such as, we are still using enzyme as out component wrappers and sinon for some stubbing. Here I used `jest.fn()` over sinon in some places that it seemed appropriate and replaced `proxyquire` with `jest.mock`. As I didn't want to complicate the PR too too much with the nuanced differences between `jest.fn()` and `sinon` that I can be migrated in a different PR along with the migration from `Enzyme` to `testing-library/react`.

**Review by brad-decker — APPROVED** [review]
LGTM, excited to get coverage minimums and path for ward for UI test coverage

**Pull request merged**
