### PR TITLE
Fix hard code account menu and settings page buttons style 

### PR DESCRIPTION
**Pull request by egorlem**
Explanation:  Buttons did't adapt to text size in different languages. This PR fixes the styles of it 

**Production**

Снимок экрана 2022-02-17 в 17 04 22

**Fix**

Снимок экрана 2022-02-17 в 17 02 23

### CODE REVIEW

**Comment by guesswhozzz** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by brad-decker — CHANGES_REQUESTED** [review]

**Review by darkwing — APPROVED** [review]
Thank you for the contribution, @guesswhozzz !  I was testing this wife a few changes:

https://gist.github.com/darkwing/236cc6765a5c0b6417b2dabb45ea64f0

I don't think the `<div>` with `width: auto` is necessary .

**Review by darkwing — CHANGES_REQUESTED** [review]
Thank you for the contribution, @guesswhozzz !  I was testing this wife a few changes:

https://gist.github.com/darkwing/236cc6765a5c0b6417b2dabb45ea64f0

I don't think the `<div>` with `width: auto` is necessary .

**Comment by guesswhozzz** [comment]
> Thank you for the contribution, @guesswhozzz ! I was testing this wife a few changes:
> 
> https://gist.github.com/darkwing/236cc6765a5c0b6417b2dabb45ea64f0
> 
> I don't think the `<div>` with `width: auto` is necessary . 

Oh, I agree the `with: auto` property on a bare div element is weird. I removed it. I also removed wrapping the title in a <div>. I noticed a BEM notation in your layout and I still think even if the element does not have styles, it still needs to be wrapped in a tag so as't to violate BEM.  

Thank you for your response

**Pull request closed without merging**
