### PR TITLE
Fix concat-stream resolution

### PR DESCRIPTION
**Pull request by Gudahtt**
## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Comment by Gudahtt** [comment]
@metamaskbot update-policies

**Comment by Gudahtt** [comment]
@metamaskbot update-policies

**Comment by Gudahtt** [comment]
@metamaskbot update-policies

**Comment by brad-decker** [comment]
@metamaskbot update-policies

**Comment by brad-decker** [comment]
I actually pushed that third concat-stream thing up without realizing what you were doing to validate the two concat-streams. I see two entries in the policy.json for concat-streams in the node_modules structure: lavamoat-browserify>node_modules>concat-stream exists, but browserify>node_modules>concat-stream does not exist.
`@metamask/snaps-controllers>node_modules>concat-stream` does exist though

**Comment by brad-decker** [comment]
@metamaskbot update-policies

**Comment by brad-decker** [comment]
and maybe the way node_modules is structured is just a red herring because it exists in other spaces too:

eth-snap-keyring also has it in its node_modules.

**Comment by brad-decker** [comment]
@metamaskbot update-policies

**Comment by brad-decker** [comment]
@metamaskbot update-policies

**Comment by brad-decker** [comment]
well the changelog for browserify only mentioned updating browser-resolve, but also module-deps updated: https://github.com/browserify/browserify/pull/1973/files

**Comment by brad-decker** [comment]
module-deps changelog is here https://github.com/browserify/module-deps/blob/master/CHANGELOG.md#623---2020-08-03

**Pull request closed without merging**
