### PR TITLE
test:  Fix flaky test: "Custom network customNetwork should add mainnet network"

### LINKED ISSUE #24634: Flaky test: "Custom network customNetwork should add mainnet network"
### What is this about?

Failure:
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/81018/workflows/092574cf-d4e8-4fbd-a5ae-b185ee6b9737/jobs/2868183/tests

Error message

Screenshot 2024-05-20 at 16 28 34

Screenshot
Screenshot 2024-05-20 at 16 28 10

### Scenario

_No response_

### Design

_No response_

### Technical Details

_No response_

### Threat Modeling Framework

_No response_

### Acceptance Criteria

_No response_

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

### References

_No response_

### PR DESCRIPTION
**Pull request by chloeYue**
## **Description**

This PR addresses the flakiness in e2e test "Custom network customNetwork should add mainnet network."

Root Cause: The flakiness happens due to occasionally hitting the API rate limit while fetching the token symbol, resulting in the warning message `"Ticker symbol verification data is currently unavailable..."`, as indicated by the failure screenshots in the CI job. However, the test is intended to verify the presence of a different warning: `"The token symbol doesn't match the network or chainID..."`. Both warnings share the same data-testid but differ in text. Consequently, when the first warning appears, the test mistakenly identifies it as the second warning, leading to test failure.

Fix Implemented: The solution for this test is to refine the selector for the specific warning message we aim to verify. By making the selector more precise, we ensure that the test accurately checks for the intended warning, thereby eliminating the flakiness caused by the confusion between the two warnings.

Screenshot 2024-05-30 at 13 55 57

Screenshot 2024-05-30 at 11 57 16

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/24895?quickstart=1)

## **Related issues**

Fixes: #24634 

## **Manual testing steps**

1. Run the test several times yarn test:e2e:single  test/e2e/tests/network/add-custom-network.spec.js  --browser=firefox --leave-running --retryUntilFailure --retries=10
2. Check ci jobs

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by seaona — COMMENTED** [review]
> The flakiness happens due to occasionally hitting the API rate limit while fetching the token symbol

I think we could also solve the root cause of the problem, by adding a mock, that returns the json list of symbols. Something like:
1. We add a json file with the contents of this, which is the list of chain ids and symbols https://chainid.network/chains.json
2. In the `mock-e2e.js` file,  we add a mock where any request to this endpoint, return the json file in the response result.

What do you think?

**Comment by chloeYue** [comment]
> > The flakiness happens due to occasionally hitting the API rate limit while fetching the token symbol
> 
> I think we could also solve the root cause of the problem, by adding a mock, that returns the json list of symbols. Something like:
> 
> 1. We add a json file with the contents of this, which is the list of chain ids and symbols https://chainid.network/chains.json
> 2. In the `mock-e2e.js` file,  we add a mock where any request to this endpoint, return the json file in the response result.
> 
> What do you think?

Thanks for the suggestion, will try to implement !

**Review by seaona — APPROVED** [review]
hey @chloeYue , since this test is failing a lot, I think it's good if we merge this so we fix it, and we can add the mock in a separate PR. What do you think?

**Comment by chloeYue** [comment]
> hey @chloeYue , since this test is failing a lot, I think it's good if we merge this so we fix it, and we can add the mock in a separate PR. What do you think?

Yes agree, let's merge this to fix the test and mock in another PR.

**Comment by hjetpoluru** [comment]
@chloeYue , I dont see the message coming as per the screenshot attached when running it locally. Also we dont need those validation and may be remove as this test is related to adding a Network. 
 `driver.clickElement(selectors.tickerButton);`
Screenshot 2024-06-27 at 1 29 55 PM

**Comment by chloeYue** [comment]
> @chloeYue , I dont see the message coming as per the screenshot attached when running it locally. Also we dont need those validation and may be remove as this test is related to adding a Network. `driver.clickElement(selectors.tickerButton);` Screenshot 2024-06-27 at 1 29 55 PM

Hi @hjetpoluru ,thanks for checking! Indeed, hitting the API rate limit is very difficult to reproduce locally, that's why you don't see it locally.  And it's expected that the error message don't display. That's why we assert in the test body that the warning is not displayed. I believe it's sensible to verify that no error message is shown when a user attempts to add a network correctly, to prevent any odd displays.

**Review by DDDDDanica — APPROVED** [review]

**Pull request merged**
