### PR TITLE
4byte fallback

### PR DESCRIPTION
**Pull request by whymarrh**
This PR re-introduces the 4byte fallback for `getMethodData`, originally introduced in #6435.

We'll want to improve how this behaves before landing it on `develop` again, namely:

- [x] Fix use of `knownMethodData`, eliminate network requests for already known data (#6530)
- [x] Add front end network request caching (#6531)
- [x] Add timeout to fetch requests for tx method data (#6535)

~**Note:** this feature branch will see the above changes made before it is marked as ready for review.~

This PR is ready for review.

### CODE REVIEW

**Comment by danjm** [comment]
Just rebased onto latest develop

**Comment by bdresser** [comment]
Even with caching, this will send a lot of traffic to 4byte - @danfinlay can you check with the maintainer? 

Chatted with Infura and they are not keen to host a version of the API simply for bandwidth reasons

**Comment by danjm** [comment]
Rebased onto developer

**Comment by danjm** [comment]
- [ ] confirm that number of requests to 4byte will now be equal to the sum of each users total unique contract method confirmations (i.e. much less than the total number of transactions a day)

**Comment by danjm** [comment]
Rebased onto develop

**Comment by whymarrh** [comment]
From @danjm above, emphasis mine:<sup>[\[1\]][1]</sup>

> Confirm that number of requests to 4byte will now be equal to the sum of each users total unique contract method *confirmations* (i.e. much less than the total number of transactions a day)

### Version 6.4.0

6.4.0 was the first version we shipped the 4byte fallback in. It made two lookup requests for each transaction in the transaction list and two lookup requests on the confirm screen. A network waterfall for 4 txs in the list:



You can notice that the two requests are dispatched at the same time (i.e., they're not staggered).

It's also worth re-affirming that the old implementation handled failures for both requests—both requests failing individually and requests failing together:





### With this PR

This PR adjusts how we dispatch the requests to reduce the requests made to 4byte. We now no longer make two requests per tx in the tx list. In fact, we now need no requests to render the tx list and make only two requests for each tx confirmation.

  [1]:https://github.com/MetaMask/metamask-extension/pull/6551#issuecomment-496570484

**Review by whymarrh — COMMENTED** [review]
I feel confident that this makes significantly fewer requests than the previous implementation

@chikeichan @danjm can one of y'all give this a ✅

**Review by danjm — APPROVED** [review]

**Pull request merged**
