### PR TITLE
Update 'react-devtools' to ^4.8.0

### PR DESCRIPTION
**Pull request by tmashuang**
One noticeable fix is the ability to resize the standalone app.

### CODE REVIEW

**Review by whymarrh — DISMISSED** [review]
LGTM but I think there might be some uncommitted lockfile changes here.

Would you mind running `yarn` and seeing if there are any extra changes?

**Comment by tmashuang** [comment]
There were, just didn't know if they were relevant or not, so I redacted them. Will provide them.

**Comment by whymarrh** [comment]
I'm not sure why the build is failing from a quick look, want to try rebasing this on the latest `develop`?

**Comment by tmashuang** [comment]
Pretty sure it was me pushing the branch to this repo then deleting. I'll resolve.

**Review by whymarrh — APPROVED** [review]
LGTM!

**Pull request merged**
