### PR TITLE
Update Button prop name type to variant

### PR DESCRIPTION
**Pull request by hakeemullahjan**
## Explanation
In this PR, I worked on issue #18693, I had to replace the prop value from `type` to `variant` to make it more consistent with other components `ui/components/component-library` and luckily this issue was assigned to me.
All files under this directory `ui/components/component-library/..` have been changed. Following changes are: 

- `type` to `variant`
- `BUTTON_TYPES` to `BUTTON_VARIANTS`
- Comments
- Imports & Exports
- Test Cases
- Storybook components and its documentations
- README.mdx

`ui/components/component-library/button/button.constants.js`
`ui/components/component-library/button/button.js`
`ui/components/component-library/button/button.stories.js`
`ui/components/component-library/button/button.test.js`
`ui/components/component-library/button/index.js`
`ui/components/component-library/button/README.mdx`
`ui/components/component-library/index.js`

`ui/components/app/modals/hold-to-reveal-modal/hold-to-reveal-modal.js`
`ui/components/app/terms-of-use-popup/terms-of-use-popup.js`
`ui/components/institutional/compliance-settings/compliance-settings.js`
`ui/components/multichain/network-list-menu/network-list-menu.js`
`ui/pages/create-account/connect-hardware/index.js`
`ui/pages/institutional/confirm-add-custodian-token/confirm-add-custodian-token.js`
`ui/pages/institutional/confirm-add-institutional-feature/confirm-add-institutional-feature.js`
`ui/pages/keychains/reveal-seed.js`
`ui/components/app/snaps/snap-version/snap-version.js`
`ui/components/institutional/custody-confirm-link-modal/custody-confirm-link-modal.js`
`ui/pages/settings/snaps/view-snap/view-snap.js`

## Screenshots/Screencaps

[README] Button
### Before

button-readme-before

### After

button-readme-after

[Storybook] Components / ComponentsLibray / Button - Default

### Before
button-default-before

### After
button-default-after

[Storybook] Components / ComponentsLibray / Button - Type to Variant

### Before
button-type-before

### After
button-variant-after

[Storybook] ui/components/app/terms-of-use-popup/terms-of-use-popup.js
### Before
terms-of-use-popup js1

### After

terms-of-use-popup js2

[Storybook] ui/components/institutional/compliance-settings/compliance-settings.js
### Before
compliance-settings js1

### After

compliance-settings js2

[Storybook] ui/components/multichain/network-list-menu/network-list-menu.js
### Before
network-list-menu js1

### After

network-list-menu js2

[Storybook] ui/pages/create-account/connect-hardware/index.js
### Before
connect-hardware1

### After

connect-hardware2

[Storybook] ui/pages/institutional/confirm-add-custodian-token/confirm-add-custodian-token.js
### Before
confirm-add-custodian-token js1

### After

confirm-add-custodian-token js2

[Storybook] ui/pages/institutional/confirm-add-institutional-feature/confirm-add-institutional-feature.js
### Before
confirm-add-institutional-feature js1
### After
confirm-add-institutional-feature js2

[Storybook] ui/pages/keychains/reveal-seed.js
### Before
reveal-seed js1

### After

reveal-seed js2

## Manual Testing Steps
`yarn storybook` then open [http://localhost:6006/](URL) and start comparing above changed components with [https://metamask.github.io/metamask-storybook/?path=/story/components-componentlibrary-button--default-story](url)

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Comment by hakeemullahjan** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by hakeemullahjan** [comment]
@georgewrmarshall I am done with all requested changes, please can you or someone else review this PR?

**Review by garrettbear — DISMISSED** [review]
LGTM 🚀

**Review by georgewrmarshall — COMMENTED** [review]
Hey @hakeemullahjan, these changes look great! One small detail is that the `BUTTON_VARIANT` should be singular without the `S`? Could you please update accordingly?

**Comment by hakeemullahjan** [comment]
> Hey @hakeemullahjan, these changes look great! One small detail is that the `BUTTON_VARIANT` should be singular without the `S`? Could you please update accordingly?

Yeah sure, No problem.

**Comment by hakeemullahjan** [comment]
@georgewrmarshall @garrettbear done.

**Review by DDDDDanica — DISMISSED** [review]

**Review by DDDDDanica — APPROVED** [review]

**Review by georgewrmarshall — COMMENTED** [review]
LGTM! Thanks for your contribution 🙏

**Review by georgewrmarshall — APPROVED** [review]

**Pull request merged**
