### PR TITLE
Decrypt

### PR DESCRIPTION
**Pull request by xmaysonnave**
Fixes:

This PR adresses three issues while decrypting :
https://github.com/MetaMask/metamask-extension/issues/8152
https://github.com/MetaMask/metamask-extension/issues/9042

Explanation:  

1 - The first addressed issue is an improvement as described in https://github.com/MetaMask/metamask-extension/issues/8152. 
It removes an unnecessary conversion. 
With the previous implementation a 3MB message was converted in a 6.5MB array and converted again to its initial 3MB message when sent to eth-sig-util. 
This PR let the message pass through Metamask and let eth-sig-util handle it.

2 - The second addressed issue is a blocking behavior in the Chrome family, this behavior does not occur with Firefox though.

The confirm-decrypt-message dialog box was able to display in its text field the whole content of an encrypted message or the whole content of the decrypted message.

However it appears that Chrome do not like big message ( > 3MB, maybe less, 3MB is my sample. With this sample Chrome hangs all the time and never displays the confirm-decryt-message dialog box). 

This PR fixes this issue. 

The UI displays a limited amount of the encrypted/decrypted message (default to 512 chars). 

To avoid any partial cut and past when the message is decrypted the UI text is non selectable through its css.  

Only the command copy the decrypted text is able to copy the whole decrypted message,

3 – The last issue is the message displayed with the command copy when the message has been decrypted. 

Currently the displayed message is ‘Copy encrypted message’ however the displayed text is the decrypted form of the message and the copy command copy the decrypted message. 

This PR updates the message with ‘Copy decrypted message’ instead.

4 - This PR lies in its own branch on my forked repo 'decrypt'. The branch decrypt come from the latest Metamask-extension upstream repo. yarn test as been performed.

5 - I can provide encrypted content samples over IPFS if you provide public encryption keys.

Thanks

### CODE REVIEW

**Comment by xmaysonnave** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by DONALDSULLENDER — APPROVED** [review]

**Comment by xmaysonnave** [comment]
Any time frame to be merged ? Thanks

**Comment by ronanyeah** [comment]
I would also like to see this merged!

**Comment by brad-decker** [comment]
@xmaysonnave thank you for your contribution, it seems that one of the issues you are attempting to resolve was closed recently due to not being reproducible. If you would like to have this PR considered for merging could you do the following for me:

1. Add reproduction steps to the Issue linked that is already closed. 
2. Rebase this PR.
3. Tag me, i'll assign myself and see that your PR gets attention from reviewers. 

Thank you.

**Comment by brad-decker** [comment]
Hey there @xmaysonnave I am closing this PR due to it becoming stale. This doesn't mean we do not want this contribution, only that we are trying to clean our PR queue to keep our reviewers focused on the most up to date and mergeable prs. If you make the requested changes and rebase the PR you can reopen it for review. Thank you!

**Pull request closed without merging**
