### PR TITLE
i18n - load locales manually

### PR DESCRIPTION
**Pull request by kumavis**
this allows users to override their default language

status: wip

### CODE REVIEW

**Comment by kumavis** [comment]
a missing locale is explosive atm

**Comment by kumavis** [comment]
this currently does not persist the currentLocale configuration option, and always sets the locale to japanese at ui start

**Comment by kumavis** [comment]
Alternative solution: Put locale into redux state

heres the TODOs for that approach from @danjm 

We will need to
- add a locale reducer to `ui/app/reducers.js`
- initialize the locale state in the `configureStore` call in `ui/index.js` with the messages object passed from `popup.js`
- add a reducer file in `ui/app/reducers/` with a default state. At bare minimum this part of state will need a `'currentLanguage'` property and a `'messages'` property
- the reducer might only need to handle one action: `'SET_LANGUAGE'`. This just updates `'currentLanguage'` and `'messages'` according to passed parameters
- add a `setLanuage` method to `ui/app/actions.js` that dispatches the `'SET_LANGUAGE'` action
- add an action for fetching the new language, once the language is fetched it will dispatch a `'SET_LANGUAGE'` action. It can also contain logic for hiding and showing a loading indicator
- each component that renders text will need the `locale` state mapped to its props. We might have to add this one by one, or if we are lucky there might be a way to configure react-redux's `connect` method to add it to everything (I'm investigating this, but have not found anything yet)
- replace the current `_t` method with the new one
- a ui for setting the language, which can just be a simple dropdown on the settings page (just like the currency selection dropdown).

**Comment by danjm** [comment]
To add to the outline on implementing this with redux, here is a solution for mapping the `locale` state to each component's props without having to update each one by one (or remember to add it each time you create a new component)-

- replace react-redux `connect()` with a higher order function (e.g. `metamaskConnect()`)that also takes `mapStateToProps()` and `mapDispatchToProps()` as params, and imports `connect()`
- `metamaskConnect()` would pass the result of passing `mapStateToProps()` to a new function `higherOrderMapStateToProps()`, and `mapDispatchToProps()`, to `connect()`
- `higherOrderMapStateToProps(mapStateToProps)` would return a function that accepts the same params as `mapStateToProps`, it would call mapStateToProps with those params, add `locale` to the result of that call and return this props object

The main drawback of this approach is that the addition of locale to props in this way will look like magic to anyone new to the codebase.

**Comment by danjm** [comment]
a working version of the above redux plan: https://github.com/MetaMask/metamask-extension/tree/i18n-translator-redux

There is one way we can improve on this: replace all `t(` (getMessage) calls with a connected component. That way we don't need to wrap the `connect` method, which could be a confusing addition to the codebase as it is not a widely used technique. This also eliminates the need to pass the `localeMessages` part of state to each translation, keeping our code cleaner and more concise.

**Comment by kumavis** [comment]
some related work from @danjm  https://github.com/MetaMask/metamask-extension/tree/i18n-translator-redux

**Comment by kumavis** [comment]
replaced by https://github.com/MetaMask/metamask-extension/pull/3609

**Pull request closed without merging**
