### PR TITLE
test: Adding e2e for SIWE and re-enabling redesign for SIWE

### LINKED ISSUE #24679: [e2e] Signature redesign - create Permit and SIWE Signature tests
Extend existing Signature Redesign tests to test new SIWE and Permit pages

### PR DESCRIPTION
**Pull request by pnarayanaswamy**
## **Description**

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/25831?quickstart=1)

## **Related issues**

Fixes: [#24679](https://github.com/MetaMask/metamask-extension/issues/24679)

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by pedronfigueiredo — DISMISSED** [review]
LGTM

**Review by digiwand — COMMENTED** [review]
Looking good! One thing is that I'm not sure if this checks that it presents a Sign-in With Ethereum UI rather than a personal sign UI. To do this we could check the "Signing in with" row exists 

another thing that might be good to check here is that domain binding (Domain alert) displays. We should be able to trigger this clicking on the "Bad Account" button. This is unique to SIWE and does not exist for personal sign

**Review by jpuri — DISMISSED** [review]

**Comment by digiwand** [comment]
p.s. adding more tests for SIWE could be done in a future PR and does not block this PR

there are also lint errors here. This oftentimes can be fixed using 'yarn lint:fix'
CleanShot 2024-07-15 at 18 54 10@2x

**Comment by pnarayanaswamy** [comment]
> Looking good! One thing is that I'm not sure if this checks that it presents a Sign-in With Ethereum UI rather than a personal sign UI. To do this we could check the "Signing in with" row exists
> 
> another thing that might be good to check here is that domain binding (Domain alert) displays. We should be able to trigger this clicking on the "Bad Account" button. This is unique to SIWE and does not exist for personal sign

Added a test for bad domain.

**Review by pedronfigueiredo — DISMISSED** [review]

**Review by pedronfigueiredo — APPROVED** [review]

**Review by digiwand — APPROVED** [review]
Nice! 

side note: aside from verifying the domain binding which is unique to SIWE and not personal-sign, we check the "Signing in with" row is displayed in the unit test
`ui/pages/confirmations/components/confirm/info/personal-sign/personal-sign.test.tsx`

**Pull request merged**
