### PR TITLE
Update assets controllers to version 22 - OpenSea V2

### PR DESCRIPTION
**Pull request by bergeron**
## **Description**

Updates the assets controllers package to version 22.0.0.  This brings in [PR 3654](https://github.com/MetaMask/core/pull/3654) to migrate from OpenSea V1 to V2 API.

## **Related issues**

Fixes: https://github.com/MetaMask/MetaMask-planning/issues/1841

## **Manual testing steps**

1. Import a wallet containing NFTs on mainnet
2. Manually import an NFT owner by the wallet, verify it appears
3. Enable NFT autodetection in settings, verify the rest of the NFTs appear
4. Verify descriptions, collection/token images are correct
5. Send an NFT, verify it works

## **Screenshots/Recordings**

No visible differences

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by bergeron** [comment]
Not sure why socket.dev hasn't seen the new version, it's on NPM:
https://www.npmjs.com/package/@metamask/assets-controllers/v/22.0.0

**Comment by bergeron** [comment]
Looking at 2e2 test failure

**Comment by DDDDDanica** [comment]
Hey @bergeron i want to ask if you will update the usage of v1 api in MM repo as well? 
https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/lib/security-provider-helpers.ts#L81

**Review by sahar-fehri — APPROVED** [review]

**Comment by bergeron** [comment]
> Hey @bergeron i want to ask if you will update the usage of v1 api in MM repo as well? https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/lib/security-provider-helpers.ts#L81

Good flag.  Looking into this endpoint, but I suspect this V1 might be an internal versioning scheme and not OpenSea's V1.

**Review by DDDDDanica — APPROVED** [review]

**Pull request merged**
