### PR TITLE
RecentBlockController - query gas price on demand

### PR DESCRIPTION
**Pull request by kumavis**
this removes the blockTracker subscription, removing the last barrier to silent-on-idle

### CODE REVIEW

**Comment by kumavis** [comment]
test failure seems consistent but not immediately clear why

**Comment by kumavis** [comment]
maybe no blocks -> no gasPrice result?

**Comment by kumavis** [comment]
This is failing tests because the transaction `origin` data is missing - not sure why

**Comment by frankiebee** [comment]
out of date

**Pull request closed without merging**
