### PR TITLE
chore: Enable `@typescript-eslint/no-explicit-any` as an error rule

### LINKED ISSUE #23530: style: Enable `@typescript-eslint/no-explicit-any` as an error rule
### What is this about?

The ongoing TypeScript conversion effort will be most effective if `any` usage can be minimized in incoming code. 

While `@typescript-eslint/no-explicit-any` is disabled in `@metamask/eslint-config-typescript`, we may want to enable it for this repo at this time. 

To minimize disruption to existing code, we could add a `eslint-disable-next-line` directive accompanied by a TODO comment to each current violation. This will enable us to separate the tasks of fixing existing violations and preventing new instances of `any` usage. 

This approach has previously been successfully applied to the core monorepo.

### Scenario

_No response_

### Design

_No response_

### Technical Details

_No response_

### Threat Modeling Framework

_No response_

### Acceptance Criteria

_No response_

### Stakeholder review needed before the work gets merged

- [X] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

### References

_No response_

### PR DESCRIPTION
**Pull request by MajorLift**
## **Description**

The ongoing TypeScript conversion effort will be most effective if `any` usage can be minimized in incoming code. A helpful step in achieving this is to enable `@typescript-eslint/no-explicit-any` as an error rule.

To minimize disruption to existing code, all 385 existing violations have been annotated with an `eslint-disable-next-line` directive and TODO comment. Errors for this rule will only be triggered by new instances of `any`.

This approach has previously been successfully applied to the core monorepo.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/23531?quickstart=1)

## Disclaimer

This is a major change, so please feel free to voice any concerns. Code review and updates to [documentation](https://github.com/MetaMask/contributor-docs/blob/240206-typescript-guidelines-any-as/docs/typescript.md#avoid-any) may be sufficient to encourage best practices for the time being. 

That said, if minimizing `any` usage through these other means sounds like a good idea, that might be a strong sign that enabling this linter rule aligns with the coding standards that we already have in place.

## **Related issues**

- Closes https://github.com/MetaMask/metamask-extension/issues/23530

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [x] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by brad-decker** [comment]
@Gudahtt / @mcmire / @davidmurdoch  is this how you would suggest handling enabling this rule to prevent future breaks? My concern is the TODO's will get lost. Though the only alternative I know is to ignore rules by file.

**Comment by mcmire** [comment]
@brad-decker Sure, good question.

The motivation for enabling this rule is to prevent further uses of `any`, which (despite the name) completely disables typechecking for the variable in question. We noticed that we had a lot of instances of `any` on `core`, and the approach we took to solve it was to add `eslint-disable` lines. Then, we did a search to count the number of instances of the ``TODO: Replace `any` with type`` comment that we had and grouped them together by area. Then we created a ticket on our Zenhub board per area, and we've been slowly working through those tickets to replace `any` with a better type and remove the `eslint-disable` comments.

This has worked for us, but if there is another approach that you think would work for you, we can certainly follow it.

**Review by DDDDDanica — DISMISSED** [review]

**Review by mikesposito — DISMISSED** [review]

**Comment by MajorLift** [comment]
@brad-decker As long as this eslint rule is in place, there should be no way to remove the `// eslint-disable-next-line @typescript-eslint/no-explicit-any` annotations other than to actually fix the `any` usage. So even if some of the TODO comments get lost, we should be able to track all `any` usage by searching for the `eslint-disable` directive.

**Review by brad-decker — DISMISSED** [review]

**Comment by brad-decker** [comment]
@mcmire nah i didn't have an alternative in mind, just making sure I understood and that we were doing things appropriately :)

**Review by mcmire — DISMISSED** [review]
Looks good!

**Review by dbrans — DISMISSED** [review]

**Review by mcmire — DISMISSED** [review]

**Review by brad-decker — DISMISSED** [review]

**Review by Mrtenz — DISMISSED** [review]

**Review by mikesposito — APPROVED** [review]

**Review by Mrtenz — APPROVED** [review]

**Review by dbrans — APPROVED** [review]

**Review by dbrans — APPROVED** [review]

**Pull request merged**
