### PR TITLE
chore: Version v12.9.0

### PR DESCRIPTION
**Pull request by chloeYue**
## **Description**

Version v12.9.0

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/28805?quickstart=1)

### CODE REVIEW

**Comment by benjisclowder** [comment]
**Version 12.8.0 Release Validation**

_Release Cut_: November 29
**Target Date for Release Sign-Off**: December 5

Hi Teams! We can start testing and validating **v12.9.0**([builds](https://github.com/MetaMask/metamask-extension/pull/28805#issuecomment-2507633940)). Let's do this!

**Instructions for Teams**

1. **Review Changes**: Refer to the [Release Tracker for v12.9.0](https://docs.google.com/spreadsheets/d/1tsoodlAlyvEUpkkcNcbZ4PM9HuC9cEM80RZeoVv5OCQ/edit?pli=1&gid=1268161483#gid=1268161483) to see all changes relevant to your team.
- Testing status to update the PR testing status: In Progress, Passed, Failed (with comments), Blocked, or Skipped (for documentation or testing improvements).
- Changelog status aids documentation. Select: Changed, Fixed, Added, or N/A if not required.
- Type of Change helps determine the impact. It is broadly categorized as Functional(User facing or non), Non-Functional(regression or not), Non main change.
2. **Log Bugs**: If you find any issues, log them in the release tracker, and make sure you add the right labels on it: type-bug , regression-RC-x.y.z , (and release-blocker when needed).
3. **Approval**: After testing is completed, and the team is happy with their RC features/changes and there are no more issues to address, indicate your team's approval by marking the checkbox next to your team's name in comment. 

Optionally, leave a comment for additional information.
Your thorough review ensures a smooth and successful release. If you have any questions please reach out to extension platform team or in the [#metamask-qa](https://consensys.slack.com/archives/C01U65ZUS2E) slack channel. Thank you for your collaboration!

**Teams to Sign Off 12.9.0 Release**:

- [ ] Accounts: @gantunesr - There are 4 Accounts changes
- [ ] Assets: @sahar-fehri / @alfeng6 - There are 26 Assets changes
- [ ]  Bridge: @jclancy93 - There are 3 Bridge changes
- [ ]  Confirmations: @sleepytanya / @cryptotavares - There are 24 Confirmations changes
- [ ]  Contributor Experience/Tiger Team: @HowardBraham / @gauthierpetetin - There are 2 Contributor Experience changes
- [ ]  Design System: @georgewrmarshall - There is 1 Design System change
- [ ]  Extension Platform: @danjm / @hjetpoluru - There are 22 Extension Platform changes
- [ ]  Identity: @dylanbutler1 - There are 5 Identity changes
- [ ]  Portfolio: @jclancy93 - There is 1 Portfolio change
- [ ]  Product safety: @cryptotavares - There is 1 Product safety change
- [ ]  Snaps: @ajeetd  - There are 3 Snaps Platform changes
- [ ]  Solana: @zone-live - There are 2 Solana changes
- [ ]  Swaps: @davibroc - There are 2 Swaps changes
- [ ]  Transactions: @klejeune - There is 2 Transactions changes
- [ ]  Wallet API: @adonesky1 - There are 3 Wallet API Platform changes
- [ ]  Wallet Framework: @mikesposito / @desi - There are 19 Wallet Framework changes
- [ ]  Wallet UX: @darkwing / @NidhiKJha - There are 10 Wallet UX changes

cc @jvbriones

_Important Reminder:
Please be aware of the importance of starting your testing immediately to ensure there is sufficient time to address any unexpected defects. This proactive approach will help prevent release delays and minimize impacts on other teams' deliveries._

**Comment by macellan401** [comment]
2 Ara 2024 Pzt 17:58 tarihinde MetaMask Bot ***@***.***> şunu
yazdı:

**Review by georgewrmarshall — DISMISSED** [review]
🟢 Approved on behalf of @MetaMask/design-system 
Checked the following PRs:
- https://github.com/MetaMask/metamask-extension/pull/28547 ✅

**Comment by hjetpoluru** [comment]
Testing has been completed for the @MetaMask/extension-platform changes and this is sign off message.

**Comment by danjm** [comment]
@SocketSecurity ignore-all

**Comment by danjm** [comment]
@metamaskbot update-attributions

**Review by danjm — APPROVED** [review]

**Pull request merged**
