### PR TITLE
Spawn yarn processes in a cmd subshell on Windows

### PR DESCRIPTION
**Pull request by ethernet8023**
In Windows, the "command" passed to spawn must be
The exact filename of an executable.
e.g. .\yarn.cmd can't be spawned by `spawn("yarn")`.
Instead, we launch cmd and use a subshell.

This allows `yarn start` to succeed on Windows.
This fixes the previously closed unresolved issue https://github.com/MetaMask/metamask-extension/issues/9127 on my machine on Windows 10.

This issue was first reported in 2011: https://github.com/nodejs/node-v0.x-archive/issues/2318
There's precedent (100+ references in the above issue) in the nodejs ecosystem to work around this issue by either spawning a cmd subshell on Windows, or using [`cross-spawn`](https://github.com/fusionjs/fusion-scaffolder/blob/master/index.js#L116) (which does the same thing).

### CODE REVIEW

**Comment by arilotter** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by Gudahtt — CHANGES_REQUESTED** [review]
Thanks @arilotter !

Could you replace with with `cross-spawn` instead, and add it as a `devDependency`? As you suggested in the description, this would do the same thing. I believe it would be easier to maintain as well, as I don't entirely follow what is going on here on the `isWindows` branches.

We already have `cross-spawn` as a transitive dependency of a number of our other `devDependencies`, so adding it would not increase the size of our dependencies.

**Comment by arilotter** [comment]
@Gudahtt I've updated my branch to use cross-spawn.

**Comment by Gudahtt** [comment]
Thanks @arilotter ! I've pushed one small change to deduplicate the `cross-spawn` version used by updating a transitive dependency.

**Review by Gudahtt — APPROVED** [review]
LGTM! Everything seems to work as-expected when running this on Linux.

I'll ping a few other team members to test this on other platforms.

**Comment by tmashuang** [comment]
LGTM, working on `cmd` and `git-bash` win10.

**Review by tmashuang — APPROVED** [review]

**Pull request merged**
