### PR TITLE
Version v11.4.0

### PR DESCRIPTION
**Pull request by danjm**
## **Description**
_Write a short description of the changes included in this pull request, also include relevant motivation and context. Have in mind the following questions:_
_1. What is the reason for the change?_
_2. What is the improvement/solution?_

## **Manual testing steps**

_1. Step1:_
_2. Step2:_
_3. ..._

## **Screenshots/Recordings**

_If applicable, add screenshots and/or recordings to visualize the before and after of your change._

### **Before**

_[screenshot]_

### **After**

_[screenshot]_

## **Related issues**

_Fixes #???_

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained:
  - [ ] What problem this PR is solving.
  - [ ] How this problem was solved.
  - [ ] How reviewers can test my changes.
- [ ] I’ve indicated what issue this PR is linked to: Fixes #???
- [ ] I’ve included tests if applicable.
- [ ] I’ve documented any added code.
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)).
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by benjisclowder** [comment]
Testing scenario task list:

- [ ]  onboarding - create a wallet
- [ ]  onboarding - import a wallet
- [ ]  keyring - reset a wallet
- [ ]  transactions - cancel transaction
- [ ]  transactions - send erc20 token origin MM
- [ ]  transactions - send erc721 token origin MM
- [ ]  transactions - send native token origin MM
- [ ]  transactions - speed up transaction
- [ ]  tokens - import erc1155 token origin MM
- [ ]  tokens - import erc20 token origin MM
- [ ]  tokens - import erc721 token origin MM
- [ ]  ens - name resolution
- [ ]  phishing - warning page
- [ ]  network - add custom network from dApp
- [ ]  network - add custom network manually
- [ ]  network - add network from the list of popular networks
- [ ]  network - switching networks
- [ ]  network - update networks
- [ ]  network - delete networks from the dropdown list
- [ ]  network - delete networks in Settings
- [ ]  backup - backup user data
- [ ]  backup - restore user data
- [ ]  metrics - send event metrics
- [ ]  address book - add a contact to the address book
- [ ]  address book - remove a contact from the address book
- [ ]  address book - update a contact in the address book

**Review by bowensanders — DISMISSED** [review]
team-snaps signs in approval for:

- Update transaction insights dropdown (#21231)
- Remove snap errors from home component (#21298)
- Bump `metamask/slip44` (#21294)
- Bump snaps packages (#21255)
- Remove usage of `subject-metadata-controller` package (#21254)
- Improve snap export metrics throttling (#21230)
- [FLASK] Create E2E for revoking snap permission (#21199)
- Add Snap website field to Snap settings page and make UI changes (#21095)
- Add Snaps directory link to the banner when at least one Snap is installed (#21167)
- Bump snaps packages (#21165)

**Review by tmashuang — DISMISSED** [review]

**Comment by vandan** [comment]
@jiexi and @tmashuang tested and have greenlit EIP-6963 support that's in the v11.4.0 RC.
This is the `team-devex` sign off

**Comment by sleepytanya** [comment]
`Confirmations system team` sign off:
I tested 'Synchronise address book and name controller (#21084)' and 'Add privacy setting to disable external name sources (#21045)' PRs that are included in this RC. PR 'Add logs on new extension version updates and put them in state logs (#21077)' cannot be tested (no functional changes).

**Comment by plasmacorral** [comment]
Accounts team approval for Snap Account API changes: Please consider this comment our sign off on the accounts team PRs cited [here](https://docs.google.com/spreadsheets/d/1tsoodlAlyvEUpkkcNcbZ4PM9HuC9cEM80RZeoVv5OCQ/edit#gid=1006642236) 

Most manual tests were conducted with Chrome 117 on Mac sonoma 14, with some tests in Firefox 118. For more detail on what all was tested see [here](https://docs.google.com/spreadsheets/d/1ivudVG_FTgZ_FpddEEoW85qw-OKIMkjtbfOlquFELXs/edit#gid=1892493458).

**Comment by seaona** [comment]
Confirmations UX QA Sign Off after [this PR](https://github.com/MetaMask/metamask-extension/pull/21565) is merged into the release branch (cherry-pick Security Provider Terms of Use)

**Pull request merged**
