### PR TITLE
Set the BSC_CONTRACT_ADDRESS to lowercase

### PR DESCRIPTION
**Pull request by danjm**
Set the BSC_CONTRACT_ADDRESS to lowercase. This makes it consistent with other address constants and the way all addresses are handled in our front-end. This fixes a bug found while I was QAing where swaps transactions don't appear in token specific views while on binance.

### CODE REVIEW

**Comment by Gudahtt** [comment]
>swaps transactions don't appear in token specific views while on binance.

How did the case of the address cause this to happen? :thinking:

**Comment by tmashuang** [comment]
Is this the case where `txParams.to` is not checksummed?

**Comment by danjm** [comment]
> How did the case of the address cause this to happen? thinking
@Gudahtt See Thomas' comment above

**Comment by danjm** [comment]
But maybe then there is a question of why the `to` params are not checksummed... perhaps because we get it from the api?

**Comment by danjm** [comment]
oh, we normalize it to lowercase in `addUnapprovedTransaction`

**Review by tmashuang — APPROVED** [review]
LGTM

**Pull request merged**
