### PR TITLE
chore: Update ppom package

### LINKED ISSUE #24170: Update PPOM package to 1.4.6 on extension

### PR DESCRIPTION
**Pull request by pedronfigueiredo**
## **Description**

Update @blockaid/ppom_release package to 1.4.6

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/24171?quickstart=1)

## **Related issues**

Fixes: #24170

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by jpuri — DISMISSED** [review]

**Comment by pedronfigueiredo** [comment]
> hi there 👋 do we need to add the opBNB support [here](https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/lib/ppom/ppom-middleware.ts#L31) or this will be done in a separate PR?
Hi @seaona thanks for the reminder, as discussed with Barbara, this will be tackled separately on these tickets:
https://github.com/MetaMask/MetaMask-planning/issues/2392
https://github.com/MetaMask/MetaMask-planning/issues/2393

**Review by DDDDDanica — DISMISSED** [review]

**Review by jpuri — DISMISSED** [review]

**Review by DDDDDanica — APPROVED** [review]

**Review by jpuri — APPROVED** [review]

**Review by FrederikBolding — APPROVED** [review]

**Comment by digiwand** [comment]
hi @pedronfigueiredo, could we update the description from 
> Update @blockaid/ppom_release package to 1.4.5

to

> Update @blockaid/ppom_release package to 1.4.6

**Comment by pedronfigueiredo** [comment]
@digiwand great catch! Changed. Thank you

**Comment by digiwand** [comment]
ty! @pedronfigueiredo

**Pull request merged**
