### PR TITLE
NFTs: Hide  detail when no thumbnail available

### PR DESCRIPTION
**Pull request by darkwing**
## Explanation

When importing an NFT on Polygon, the detail screen is missing the `link` information because it's not provided by the API.  If no separate thumbnail link is available, we should hide that row in the NFT detail.

## Screenshots/Screencaps

NoLink

## Manual Testing Steps

1.  Add Polygon network to the wallet
2. Import this NFT: https://polygonscan.com/tx/0x02bb91ad32785551c9be1182173fc2df692d1f77062a92bdee060e3bbda3d979
3. Before this PR, a "Link" column would display without required information
4. After this PR, that "Link" column is hidden

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Comment by adonesky1** [comment]
@darkwing are you referring to the `source` field? Or something else? There's a `link` field? Also will others be able to import this NFT? or is this on a shared account?

**Review by NidhiKJha — DISMISSED** [review]

**Comment by darkwing** [comment]
@adonesky1 Seeing this at the moment:

### Mainnet
MainnetNFT

### Polygon
PolygonNFT

The link is based off of `imageThumbnail` which isn't there on polygon.

**Comment by adonesky1** [comment]
Ok hmmm I don't remember it. Sounds good though.

**Review by georgewrmarshall — APPROVED** [review]
LGTM

**Review by NidhiKJha — APPROVED** [review]

**Pull request merged**
