### PR TITLE
fix: flaky test `Add account should not affect public address when using secret recovery phrase to recover account with non-zero balance @no-mmi`aded

### PR DESCRIPTION
**Pull request by seaona**
## **Description**
In the process for creating a new account, we get to see this error:

```
TimeoutError: Waiting for element to be located By(css selector, [data-testid="account-list-menu-details"])
Wait timed out after 10023ms
  (Ran on CircleCI Node 17 of 20, Job test-e2e-chrome)
    at /home/circleci/project/node_modules/selenium-webdriver/lib/webdriver.js:929:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
This happens after clicking the account menu, and after clicking the Add account. It seems that the click doesn't hit exactly the button due to the account list loading, making the button move. When the account list is loaded, the click is performed outside the button boundary, and this makes the popup close and you cannot find the next element: "account-list-menu-details" element.

I haven't been able to reproduce this but I've seen this behaviour in the manual process

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/27420?quickstart=1)

## **Related issues**

Fixes: those 3 are fixed in this PR, as they were caused by the same issue

- https://github.com/MetaMask/metamask-extension/issues/27419
- https://github.com/MetaMask/metamask-extension/issues/27337
- https://github.com/MetaMask/metamask-extension/issues/27336

## **Manual testing steps**

1. Check ci
2. Run tests locally

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by chloeYue — DISMISSED** [review]
LGTM ! I have already migrated account list in page object model, i will try to convert this test to use that in separate PR

**Review by hjetpoluru — DISMISSED** [review]
LGTM

**Comment by hjetpoluru** [comment]
@seaona - I notice [this failure ](https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/102417/workflows/07b5889a-29c5-4076-813a-93310612f01c/jobs/3816438/tests) and we could implement the similar here too or is it different issue.

**Review by HowardBraham — DISMISSED** [review]

**Comment by seaona** [comment]
> @seaona - I notice [this failure ](https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/102417/workflows/07b5889a-29c5-4076-813a-93310612f01c/jobs/3816438/tests)and we could implement the similar here too or is it different issue. I am thinking you're still working on this flaky test and hence I reverted my approval.

hey @hjetpoluru nice catch! I've added the fix to a couple of more testcases!
And thank you @chloeYue !
When we implement page objects for this, we could add this condition into the page object itself, so any test utilizing the page object will already mitigate the flakiness, and it won't happen again :+1:

**Review by HowardBraham — DISMISSED** [review]

**Comment by davidmurdoch** [comment]
A super nit here, please ignore if you want.

Should this use `driver.waitForSelector` instead of `driver.findElement`? The end result is the same, but I think the use case here is perfect for `driver.waitForSelector` (the two function do literally the exact the same thing under the hood, so it really doesn't matter.)

**Comment by seaona** [comment]
> A super nit here, please ignore if you want.
Should this use driver.waitForSelector instead of driver.findElement? The end result is the same, but I think the use case here is perfect for driver.waitForSelector (the two function do literally the exact the same thing under the hood, so it really doesn't matter.)

yeah, that's a good point @davidmurdoch :heart_eyes: I've updated it, thank you :pray:

**Review by DDDDDanica — APPROVED** [review]

**Review by davidmurdoch — APPROVED** [review]

**Comment by hjetpoluru** [comment]
@seaona, looks the test [failing ](https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/102509/workflows/89102810-b662-4425-8148-542453153514/jobs/3819761)in CI and something strange from the logs 
Screenshot 2024-09-26 at 4 52 23 PM
I will rerun the test again to see if it occurs.

**Pull request merged**
