### PR TITLE
ci - improve lavamoat validation debug info

### PR DESCRIPTION
**Pull request by kumavis**

### CODE REVIEW

**Review by darkwing — DISMISSED** [review]

**Review by rekmarks — COMMENTED** [review]
Is there any particular reason to narrow the `git diff` invocations to just `package.json` and `lavamoat/`? It seems more future proof to not specify a file or path, at no cost to readability.

**Comment by kumavis** [comment]
the validations deal with specifically those targets, we could add a more generic check i suppose

**Comment by kumavis** [comment]
i also limited the diff to ensure the validation debug output was relevant

**Review by Gudahtt — DISMISSED** [review]
LGTM!

**Review by brad-decker — DISMISSED** [review]

**Review by rekmarks — APPROVED** [review]
LGTM!

**Review by Gudahtt — APPROVED** [review]

**Pull request merged**
