### PR TITLE
@metamask/providers@9.0.0

### PR DESCRIPTION
**Pull request by rekmarks**
Bump `@metamask/providers` to `9.0.0`. Should be completely non-breaking for our purposes.

### CODE REVIEW

**Comment by joani24** [comment]
> Bata `@metamask/providers`para `9.0.0`. Deve ser completamente inquebrável para nossos propósitos.

**Review by FrederikBolding — APPROVED** [review]

**Comment by darkwing** [comment]
Looking at the changelog (https://github.com/MetaMask/providers/commit/a6e3b8a50d3e33d2147deeee85366f2c2fe3eac2), I'm seeing lots of breaking changes.  Anything specific we should be manually testing for?

**Comment by FrederikBolding** [comment]
@darkwing The only breaking change in `9.0.0` is moving some logic from `BaseProvider` to a new class. But `BaseProvider` isn't used directly anywhere I could find.

**Comment by rekmarks** [comment]
@darkwing all of the breaking changes should be in the `BaseProvider` / `StreamProvider`, there should be no breaking changes whatsoever in the `MetaMaskInpageProvider`, which is what we inject via our content script. It is not impossible that we missed something during review so I think we'll have to rely on careful QA of the provider behavior on the test dapp while doing lots of network switches and account switches etc. to see how it does.

cc: @PeterYinusa @tmashuang

**Review by darkwing — APPROVED** [review]

**Pull request merged**
