### PR TITLE
Hide zero balance tokens with preference

### LINKED ISSUE #10165: Hide tokens with 0 balance
As someone who sold all of a token, I'd like my tokens with 0 balances to be auto-hidden, so that they don't clutter my view.

**description**

after a token's entire balance is emptied, that token has a 0 balance but is still being shown in the user's wallet by default. Instead, the tokens with 0 balances should be removed from the list until they have a balance again.

### PR DESCRIPTION
**Pull request by darkwing**
Fixes: https://github.com/MetaMask/metamask-extension/issues/10165

I've been seeing a lot of requests for this, and I myself would love it, so I threw this together.  I'm not sure if we had previous design for this so apologies if we did.

### CODE REVIEW

**Review by Gudahtt — COMMENTED** [review]
So the request here is to automatically hide tokens with zero balance?

Note that we already allow the hiding of any token manually, and we don't automatically add tokens unless we detect that a token on our list has a non-zero balance. So it seems like this would be a convenience of marginal benefit, unless I'm missing something?

**Comment by darkwing** [comment]
Reasons I would want to be able to toggle this:

1.  From an investor perspective, I think it's nice to be able to show and hide tokens I have owned in the past, regardless of *current* balance.
2. From an investor perspective, I would still like to see individual transaction data, regardless of if I have any balance *now*
3. Automatically hiding tokens may be a bit jarring to existing users, so having this as an option would prevent UX shock.  If it really does come down to users wanting that, we can simply default this to `true`

**Comment by Gudahtt** [comment]
I see, so the main advantage for you over manually hiding tokens would be that this is _temporarily_ , and allows you to untoggle this to see your old transaction history if you want to. Does that sound about right?

**Comment by darkwing** [comment]
Bingo. Since we don't have a "transactions" view, thus no way to see transactions for a given token (other than telling users to go check out Etherscan) if we auto-hide zero balances, we should probably give this as an option to the user.  I'm happy to hear what the rest of the team thinks though.

**Comment by jacobcantele** [comment]
I think the UX that @darkwing is proposing here is superior to other proposals we've seen that all create problems where the user can't find those tokens once they have balance in the future. @rachelcope could you take a look when you have a sec?

**Comment by darkwing** [comment]
https://user-images.githubusercontent.com/46655/109065521-54448e00-76b1-11eb-8c6b-1ac691ea6973.mp4

**Comment by darkwing** [comment]
Ledger does this via a setting as well:

unnamed

**Review by Gudahtt — APPROVED** [review]
LGTM!

**Review by rachelcope — APPROVED** [review]
Looks good to me!

**Pull request merged**
