### PR TITLE
deps - remove "remotedev-server"

### PR DESCRIPTION
**Pull request by kumavis**
removes `remotedev-server` as dep

if you use it as part of your workflow, please add it globally `yarn global add remotedev-server`

### CODE REVIEW

**Review by Gudahtt — CHANGES_REQUESTED** [review]
These three packages are no longer used, and should be removed from the `allow-scripts` config:
* `sqlite3`
* `ejs`
* `sc-uws`

**Review by Gudahtt — APPROVED** [review]
I removed the three extraneous entries myself, since I already had it checked out locally to test this out.

LGTM!

**Comment by Gudahtt** [comment]
Correction: `ejs` _is_ still present in the dependency tree, but only `ejs@3`, which doesn't have any install scripts. `ejs@2` does have install scripts, and it has been removed in this PR.

**Review by rekmarks — APPROVED** [review]
LGTM!

**Comment by kumavis** [comment]
❤️ ❤️ ❤️

**Pull request merged**
