### PR TITLE
Update account options menu design

### PR DESCRIPTION
**Pull request by Gudahtt**
The `AccountDetailsDropdown` component has been rewritten to use the new `Menu` component, and to follow the latest designs.

This should be functionally equivalent. A couple of the icons have changed, but that's about it.

Support for a subtitle was added to `MenuItem` to support the `origin` subtitle used for the explorer link for custom RPC endpoints.

A few adjustments were required to `test/helper.js` to accommodate the use of `Menu` from a JSDOM context (this is the first time it's been used in a unit test). A `popover-content` element was added to the fake DOM, and another global was added that `react-popper` used internally.

An additional driver method (`clickPoint`) was added to the e2e driver to allow clicking the background behind the menu to dismiss it. This wasn't possible using the `clickElement` method, because that method would refuse to click an obscured element. The only non-obscured
element to click was the menu backdrop, and that didn't work either because the center was obscured by the menu (Selenium clicks the center of whichever element is targeted).

### CODE REVIEW

**Comment by Gudahtt** [comment]
This was done now because a separate change I was working on locally relating to the asset page resulted in the position of the account options menu being totally broken. Instead of fixing that issue, I figured we'd might as well replace the whole thing.

**Comment by Gudahtt** [comment]
Here are the new designs I was following: https://www.figma.com/file/b8U583mpXW1FsPWfGFNT8C/Wallet-home-(popup-%2B-fullscreen)?node-id=217%3A104

<details>
<summary>Here are screenshots of the new account options menu:</summary>

Typical case:

new-options

With a custom RPC endpoint and while an imported account is selected:

new-options-custom-rpc

</details>

**Review by brad-decker — APPROVED** [review]
image
:shipit:

**Review by whymarrh — APPROVED** [review]
LGTM!

**Pull request merged**
