### PR TITLE
Persian translation

### PR DESCRIPTION
**Pull request by EhsanMamakani**
I've added the Persian translation.

### CODE REVIEW

**Comment by whymarrh** [comment]
Hey @ehsan01, thanks for this! Unfortunately our right-to-left is... er, pending (#6822) and we'll want to land that first to make this the best possible experience.

**Comment by whymarrh** [comment]
(In the meantime, if you did want to rebase this on the latest `develop` that'd fix up the `test-deps` failure. Not required though. 😅)

**Review by Gudahtt — CHANGES_REQUESTED** [review]
Thanks, this is fantastic!

Could you add this to the locale index in `app/_locales/index.json` as well? Otherwise it's impossible for the user to select this locale.

**Comment by mapmeld** [comment]
Hi @ehsan01 !  RTL support is now merged in 
If you add "fa":  "فارسی" to the languages JSON file, then it can get merged.
There are a few UI changes to translate, but I can send them to you and a friend in Herat to add later

**Review by Gudahtt — APPROVED** [review]
I've just went ahead and made that minor change myself, as I'm eager to get at least one RTL locale merged to demonstrate the RTL support. I've also deleted a few messages that were recently removed.

Thanks for the contribution @ehsan01 ! Any further additions to the locale would be greatly appreciated :pray:

**Pull request merged**
