### PR TITLE
deps: Update @metamask/post-message-stream and dependents

### LINKED ISSUE #21653: Upgrade @metamask/post-message-stream to latest
### What is this about?
The offscreen document will utilize post-message-stream for communication to create namespaced communication pathways. This will also be used by Snaps, and the snaps Offscreen Executor uses Post message stream version 7.0.0. We should be in alignment on dependency versions.

### Scenario

_No response_

### Design

_No response_

### Technical Details

_No response_

### Threat Modeling Framework

_No response_

### Acceptance Criteria

- [ ] Upgrade done with no breaking tests

### References

_No response_

### PR DESCRIPTION
**Pull request by brad-decker**
## **Description**
1. Updates `@metamask/post-message-stream` to 7.0.0
2. Updates `@metamask/phishin-warning` to 3.0.0 (which eliminates dependencies on post-message-stream 6.2.0)

## **Related issues**

Fixes: #21653 

## **Manual testing steps**

1. No functional changes expected. Verify tests pass.

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by brad-decker** [comment]
@metamaskbot update-policies

**Review by HowardBraham — DISMISSED** [review]

**Comment by brad-decker** [comment]
@legobeat should that block this?

**Comment by brad-decker** [comment]
I am fairly confident that the two places we directly import this dependency in the extension are not affected by the breaking changes, the main one that I think could affect it is the upgrade of readable-stream. However, The phishing page is under E2E test so I feel confident that this isn't breaking due to a mismatch here. I do think we should prioritize the upgrade of the phishing-controller dependency. Ill wait for others to chime in on this and add the do-not-merge flag until a decision is reached.

**Review by Mrtenz — DISMISSED** [review]
Looks good to me, but I don't know if this would affect `@metamask/phishing-warning` in some way.

**Comment by brad-decker** [comment]
@metamaskbot update-policies

**Comment by brad-decker** [comment]
@metamaskbot update-policies

**Comment by brad-decker** [comment]
@SocketSecurity ignore @metamask/phishing-warning@3.0.0

**Review by DDDDDanica — APPROVED** [review]

**Review by darkwing — APPROVED** [review]

**Pull request merged**
