### PR TITLE
fix: fix e2e for Migrate Opensea to Blockaid Banner @no-mmi Shows up on Token Approval transaction confirmations

### PR DESCRIPTION
**Pull request by DDDDDanica**
## **Description**
Could be caused by 2 PRs merging race issue while one was introducing a migration state

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/24327?quickstart=1)

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by HowardBraham — APPROVED** [review]

**Review by pedronfigueiredo — APPROVED** [review]

**Review by legobeat — APPROVED** [review]

**Comment by legobeat** [comment]
Curiously, lavamoat runtime errors in chrome e2e tests: https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/78551/workflows/2d949ec1-4481-476c-8498-54ea44fd5977/jobs/2739483

```
error caught in retry(): JavascriptError: javascript error: LavaMoat - property "name" of globalThis is inaccessible under scuttling mode. To learn more visit https://github.com/LavaMoat/LavaMoat/pull/360.
```

Not present on `develop`: https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/78551/workflows/2d949ec1-4481-476c-8498-54ea44fd5977/jobs/2739483

That it happens during retry is an indication that it could be unrelated to this PR and the issue it addresses.

**Comment by danjm** [comment]
@legobeat I can't see the lavamoat errors you mention. Did you share the right link?

**Comment by legobeat** [comment]
> @legobeat I can't see the lavamoat errors you mention. Did you share the right link?

Apparently not!

**Review by vthomas13 — APPROVED** [review]

**Comment by DDDDDanica** [comment]
Closed as it is not the right fix

**Pull request closed without merging**
