### PR TITLE
Removing TOKEN_DETECTION_V2 feature flag

### LINKED ISSUE #14297: Clean up after TOKEN_DETECTION_V2 flag removal
Remove the TOKEN_DETECTION_V2 flag and clean up related changes

### PR DESCRIPTION
**Pull request by NiranjanaBinoy**
Removing TOKEN_DETECTION_V2 feature flag.

### CODE REVIEW

**Comment by darkwing** [comment]
Wow, congrats on getting this to the end of the road @NiranjanaBinoy !

**Comment by danjm** [comment]
When we bump the controllers PR, we also need to make the following change:

Screenshot from 2022-05-26 21-13-45

**Comment by danjm** [comment]
Blocking this on updating the controller version:

- [ ] Update the controller version

**Comment by danjm** [comment]
Based on convo with @Cal-L: we may want to call `detectNewTokens` on a network switch

**Pull request closed without merging**
