### PR TITLE
Fix for missing git commit-based dependency issue

### PR DESCRIPTION
**Pull request by kumavis**
> Could not install from "node_modules/eth-tx-summary/node_modules/eth-block-tracker/async-eventemitter@github:ahultgren/async-eventemitter#fa06e39e56786ba541c180061dbf2c0a5bbf951c" as it does not contain a package.json file.

### CODE REVIEW

**Comment by kumavis** [comment]
the original error can lead to this next error
```
npm ERR! path /home/circleci/project/node_modules/ganache-core/node_modules/web3-providers-ws/node_modules/websocket
npm ERR! code EISGIT
npm ERR! git /home/circleci/project/node_modules/ganache-core/node_modules/web3-providers-ws/node_modules/websocket: Appears to be a git repo or submodule.
npm ERR! git     /home/circleci/project/node_modules/ganache-core/node_modules/web3-providers-ws/node_modules/websocket
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.
```

**Comment by kumavis** [comment]
cache was bad so i added an environment var to CircleCI so we can manually change that to reset the cache without pushing commits

seems like a hack but its the official reccomendation https://support.circleci.com/hc/en-us/articles/115015426888-Clear-project-cache

**Comment by kumavis** [comment]
woof this spiraled out of control a bit

**Comment by Azier777** [comment]
Oo OK sry I'm still trying to get the hang of this

**Comment by kumavis** [comment]
closing in favor of https://github.com/MetaMask/metamask-extension/pull/6286

**Comment by rushairer** [comment]
git clone https://github.com/MetaMask/metamask-extension.git -b develop

npm i

also has this problem

```
metamask-extension git:(develop) npm i
npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules/eth-tx-summary/node_modules/eth-block-tracker/async-eventemitter@github:ahultgren/async-eventemitter#fa06e39e56786ba541c180061dbf2c0a5bbf951c" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/abenx/.npm/_logs/2019-05-10T04_05_57_685Z-debug.log

```

**Pull request closed without merging**
