### PR TITLE
chore(ts): Use FirstTimeFlowType enum

### PR DESCRIPTION
**Pull request by brad-decker**
## **Description**
As part of #23056 we discovered that it will be necessary to introduce a new "type" of firstTimeFlow which is 'restore'. In order to reason about those changes I wanted to shift to using an enum for FirstTimeFlowType which can actually be null, 'import' or 'create' at present. @NiranjanaBinoy converted the onboarding controller to typescript and introduced the enum in https://github.com/MetaMask/metamask-extension/pull/23461 and this PR propogates its usages. 

## **Manual testing steps**
1. There should be no testing required as this is not a functional change. However, validating that onboarding still works as intended is viable, and hopefully any bugs will be severe enough to be caught In CI.

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by MajorLift** [comment]
Looks like this is a duplicate of https://github.com/MetaMask/metamask-extension/pull/23461?

This comment seems relevant here as well: https://github.com/MetaMask/metamask-extension/pull/23461#discussion_r1525656532

**Comment by brad-decker** [comment]
@MajorLift thanks for pointing that out! I talked to @NiranjanaBinoy and we're going to get her version merged then I'll rebase mine to only be relevant to using the new enum type for FirstTimeFlowType.

**Comment by MajorLift** [comment]
Do these belong in this PR as well?

```diff
diff --git a/test/e2e/fixture-builder.js b/test/e2e/fixture-builder.js
index 5ac235d94a..31d0efc02d 100644
--- a/test/e2e/fixture-builder.js
+++ b/test/e2e/fixture-builder.js
@@ -5,6 +5,7 @@ const {
 const { merge } = require('lodash');
 const { toHex } = require('@metamask/controller-utils');
 const { NetworkStatus } = require('@metamask/network-controller');
+const { FirstTimeFlowType } = require('../../shared/constants/onboarding');
 const { CHAIN_IDS, NETWORK_TYPES } = require('../../shared/constants/network');
 const { SMART_CONTRACTS } = require('./seeder/smart-contracts');
 const { DAPP_URL, DAPP_ONE_URL } = require('./helpers');
@@ -145,7 +146,7 @@ function defaultFixture(inputChainId = CHAIN_IDS.LOCALHOST) {
       },
       OnboardingController: {
         completedOnboarding: true,
-        firstTimeFlowType: 'import',
+        firstTimeFlowType: FirstTimeFlowType.import,
         onboardingTabs: {},
         seedPhraseBackedUp: true,
       },
diff --git a/ui/pages/onboarding-flow/create-password/create-password.test.js b/ui/pages/onboarding-flow/create-password/create-password.test.js
index c70fdb2fef..d08d448e9a 100644
--- a/ui/pages/onboarding-flow/create-password/create-password.test.js
+++ b/ui/pages/onboarding-flow/create-password/create-password.test.js
@@ -55,7 +55,7 @@ describe('Onboarding Create Password', () => {
         ...initializedMockState,
         metamask: {
           ...initializedMockState.metamask,
-          firstTimeFlowType: 'import',
+          firstTimeFlowType: FirstTimeFlowType.import,
         },
       };
       const mockStore = configureMockStore()(importFirstTimeFlowState);

```

**Review by MajorLift — APPROVED** [review]
LGTM!

**Review by NiranjanaBinoy — APPROVED** [review]
LGTM

**Pull request merged**
