### PR TITLE
React Devtools functionality

### PR DESCRIPTION
**Pull request by EtDu**
These proposed changes include an option for developers to enable the React Dev Tools for debugging the UI, as the in-browser option does not work with extensions.

### CODE REVIEW

**Review by MarkOSullivan94 — APPROVED** [review]
Tested out the changes and all is working on my end! Great job 👍

**Comment by whymarrh** [comment]
@ContemporaryAnarchy thanks for working on this. Unfortunately this suffers from the same problem [my original branch and changes](https://github.com/MetaMask/metamask-extension/compare/6ccc34cb52d52c449e3233aaf2a85be70c4f58da...whymarrh:devtools) suffered from: the bundle includes this package and we don't yet have a _clean_ way of excluding packages from the bundle. I'm closing this for now, but being able to uses these devtools is something we want to land in MetaMask in the near future.

**Comment by MarkOSullivan94** [comment]
@whymarrh where could I follow updates for devtools integration into MetaMask?

**Comment by whymarrh** [comment]
@MarkOSullivan94 #6793 supersedes this PR (and #5620) and we're actively working on removing it from the bundle. We're hoping to land this soon.

**Pull request closed without merging**
