### PR TITLE
Fix form prefilling in Swaps on the Build Quote page

### PR DESCRIPTION
**Pull request by dan437**
## Explanation
This PR fixes an issue where a user saw prefilled values on the Build Quote page after they left Swaps and entered it again when certain conditions were met. Now every time a user leaves and enters Swaps, they will start from a clean slate and only the "Swap from" field will be preselected.

## Manual testing steps
- Go to Swaps
- Select swap from, amount and swap to. Once you select all of them, wait for about 2 seconds and click on the Fox head / Cancel link to exit Swaps
- Enter Swaps again
- Only the "Swap from" field will be prefilled

### CODE REVIEW

**Review by danjm — DISMISSED** [review]
LGTM

**Review by adonesky1 — DISMISSED** [review]
LGTM! Thanks for this fix!

**Comment by PeterYinusa** [comment]
LGTM

**Review by PeterYinusa — APPROVED** [review]

**Review by adonesky1 — APPROVED** [review]
LGTM

**Review by danjm — APPROVED** [review]

**Pull request merged**
