### PR TITLE
fix: updated toasts component and copy

### PR DESCRIPTION
**Pull request by NidhiKJha**
This PR is to update the toast component and update the copy changes for the toast

## **Related issues**

Fixes: [https://github.com/MetaMask/MetaMask-planning/issues/3389](https://github.com/MetaMask/MetaMask-planning/issues/3389
)
## **Manual testing steps**

1. Run extension with CHAIN_PERMISSIONS=1 yarn start
2. Check the toast component, it has border radius, box shadow and other fixes as described in ticket

### **Before**
Screenshot 2024-10-07 at 12 33 08 PM

### **After**
Screenshot 2024-10-07 at 12 33 52 PM

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by darkwing** [comment]
We need to use a new localization key so that other messages get re-translated.

**Review by darkwing — CHANGES_REQUESTED** [review]
We need to use a new localization key so that other messages get re-translated.

**Comment by NidhiKJha** [comment]
> We need to use a new localization key so that other messages get re-translated.

@darkwing This localization key is not translated yet. It only exists in `en` file. So, I think we can use it. Right?

**Review by andreahaku — APPROVED** [review]
LGTM

**Review by darkwing — APPROVED** [review]

**Pull request merged**
