### PR TITLE
Update network controller to use updated eth-json-rpc-middleware

### PR DESCRIPTION
**Pull request by jpuri**
## **Description**
Update network controller to use new version of `eth-json-rpc-middleware`. Old version of `eth-json-rpc-middleware` had a bug which was failing Blockaid validations.

## **Related issues**

Fixes: MetaMask/MetaMask-planning#1461

## **Manual testing steps**
NA

## **Screenshots/Recordings**
NA

## **Pre-merge author checklist**

- [X] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've clearly explained what problem this PR is solving and how it is solved.
- [X] I've linked related issues
- [] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [X] I’ve properly set the pull request status:
  - [X] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by jpuri** [comment]
@metamaskbot update-policies

**Comment by jpuri** [comment]
@metamaskbot update-policies

**Comment by jpuri** [comment]
@metamaskbot update-policies

**Comment by jpuri** [comment]
@metamaskbot update-policies

**Comment by jpuri** [comment]
@metamaskbot update-policies

**Comment by jpuri** [comment]
@metamaskbot update-policies

**Review by blackdevelopa — APPROVED** [review]
Looks good to me. PS: I don't know so much about the policy diff

**Review by FrederikBolding — APPROVED** [review]

**Review by zone-live — APPROVED** [review]

**Pull request merged**
