### PR TITLE
chore(deps): Bump name-controller to ^6.0.1

### PR DESCRIPTION
**Pull request by mcmire**
## **Description**

There are a few notable changes between 4.2.0 and 6.0.1:

- Support for fetching proposed nicknames via Etherscan on Optimism Goerli has been removed in favor of Optimism Sepolia
- Support for fetching proposed nicknames via Etherscan on Linea Sepolia has been added
- Proposed nicknames now get automatically removed from state after 24 hours

See the changelog for more:

<https://github.com/MetaMask/core/blob/%40metamask/name-controller%406.0.1/packages/name-controller/CHANGELOG.md>

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/24229?quickstart=1)

## **Related issues**

Progresses #24140.

## **Manual testing steps**

This PR should not introduce any functional changes; the petnames feature should continue to work as designed.

## **Screenshots/Recordings**

(None)

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by mikesposito** [comment]
@metamaskbot update-policies

**Review by mikesposito — APPROVED** [review]

**Review by cryptodev-2s — APPROVED** [review]
LGTM!

**Comment by Gudahtt** [comment]
There is one breaking change in this range that doesn't seem to require any changes to the extension, but I wasn't sure:

>- **BREAKING:** Add expire limit for proposed names ([#3748](https://github.com/MetaMask/core/pull/3748))
  - Expired names now get removed on every call to `updateProposedNames`
  
cc @cryptotavares @OGPoyraz @vinistevam could you confirm that this change is safe to bring in?

**Review by Gudahtt — APPROVED** [review]
LGTM!

**Comment by OGPoyraz** [comment]
Thanks for the ping @Gudahtt, as you said it's totally safe to merge it in.

**Review by OGPoyraz — APPROVED** [review]

**Review by vinistevam — APPROVED** [review]

**Pull request merged**
