### PR TITLE
Added the ability to navigate multiple SIWE notifications

### LINKED ISSUE #17807: [Enhancement] Add the ability to navigate multiple SIWE notifications
It would be good if the user could navigate between multiple Sign In With Ethereum requests similar to the other signature requests

https://user-images.githubusercontent.com/53189696/219660983-3480fbfa-e119-47ee-a46c-f7a8bb181c28.mov

### PR DESCRIPTION
**Pull request by aleksandar-mihajlovic**
## Explanation

Added the ability to navigate multiple SIWE notifications, now when user sign's multiple SIWE, the navigation header is shown so that he can go through multiple SIWE and also user has option to RejectAll.
* Fixes #17807

### Before

multipleSIWENotificationBefore

### After

multipleSIWENotificationAfter

### Before

Screenshot 2023-03-10 at 15 35 01

### After

Screenshot 2023-03-10 at 16 17 55

## Lint

Screenshot 2023-03-10 at 16 26 14

## Manual Testing Steps

1. Go to Test Dapp https://metamask.github.io/test-dapp/
2. Connect MetaMask
3. Click to Sign In With Ethereum multiple times
4. In MetaMask extension navigation header is shown and can go through multiple notifications
5. At the bottom of extension Reject requests button is shown
6. When clicked there is pop up modal to Reject
7. After reject extension is closed and there are no requests

### CODE REVIEW

**Comment by dzfjz** [comment]
Verified by QA

**Comment by bschorchit** [comment]
Does this need changes so it passes codecov check?

**Comment by aleksandar-mihajlovic** [comment]
> Does this need changes so it passes codecov check?

I am not sure what should i do here, since this component doesnt have unit test file

**Review by digiwand — COMMENTED** [review]
re: @legobeat's comment. I agree that adding a test when `messagesCount < 1` would be a good addition

edit: 
 
Thanks @aleksandar-mihajlovic for creating this PR and adding the feature support! As discussed with the team, I can get this PR merged. Feel free to reach out to me for anything regarding the PR

**Review by segun — APPROVED** [review]

**Review by NiranjanaBinoy — APPROVED** [review]
LGTM

**Comment by seaona** [comment]
hi @aleksandar-mihajlovic @digiwand PR looks good from QA side. Great job :fire:

**Pull request merged**
