### PR TITLE
Utilize the full size of icon space

### PR DESCRIPTION
**Pull request by sergejmueller**
Increase the MetaMask icon size to the available browser action bar size. The "bigger" icon appears sharper and clearer.

**Initial icon size**
chrome-actionbar-metamask-before

**Modified icon size**
chrome-actionbar-metamask-after

### CODE REVIEW

**Comment by cjeria** [comment]
Hey @sergejmueller thanks for suggesting this update! We'd be more than happy to update this icon. 

We'd like to use our official front-facing logo as the icon. See example/
image

I've included all 3 version per chrome's spec https://developer.chrome.com/apps/manifest/icons

This zip should have all 3 image sizes. 
[extension_icon.zip](https://github.com/MetaMask/metamask-extension/files/3844756/extension_icon.zip)

**Comment by sergejmueller** [comment]
All icons are replaced by the front-facing logo. There are seven different sizes, they are all used in any extension files.

**Review by Gudahtt — APPROVED** [review]
Thanks, looks great!

@cjeria the notification badge colour apparently needs to be changed at runtime - I'll submit a separate PR for that.

**Comment by cjeria** [comment]
Here's the 512px sized icon for good measure.
icon512

**Pull request merged**
