### PR TITLE
Fixes #4250

### LINKED ISSUE #4250: select local language should be translated
choose  language code setting from the file as following:
metamask-extension/app/_locales/index.json(the file location)
content:
[
  { "code": "cs", "name": "Czech" },
  { "code": "de", "name": "German" },
  { "code": "en", "name": "English" },
  { "code": "es", "name": "Spanish" },
  { "code": "fr", "name": "French" },
  { "code": "hn", "name": "Hindi" },
  { "code": "it", "name": "Italian" },
  { "code": "ja", "name": "Japanese" },
  { "code": "ko", "name": "Korean" },
  { "code": "nl", "name": "Dutch" },
  { "code": "ph", "name": "Tagalog" },
  { "code": "pt", "name": "Portuguese" },
  { "code": "ru", "name": "Russian" },
  { "code": "sl", "name": "Slovenian" },
  { "code": "th", "name": "Thai" },
  { "code": "tml", "name": "Tamil" },
  { "code": "tr", "name": "Turkish" },  
  { "code": "vi", "name": "Vietnamese" },
  { "code": "zh_CN", "name": "Mandarin" },
  { "code": "zh_TW", "name": "Taiwanese" }
]

much better as following:
[
  { "code": "zh_CN", "name": "中文简体" }
]

### PR DESCRIPTION
**Pull request by trowacat**
Localized language names as suggested in #4250.

### CODE REVIEW

**Review by kumavis — APPROVED** [review]

**Review by kumavis — CHANGES_REQUESTED** [review]
I actually can see that Japanese is incorrect - which makes me suspect others may be as well

**Review by kumavis — DISMISSED** [review]

**Comment by kumavis** [comment]
Cool, made some fixes and some changes that are hopefully improvements. Primarily used a wikipedia article's alternate languages list.

**Comment by kumavis** [comment]
hmm build system is broken, fix is here https://github.com/MetaMask/metamask-extension/pull/5561

**Comment by trowacat** [comment]
@kumavis Thank you! I will make the addition of the fix you referenced later today.

**Review by kumavis — APPROVED** [review]

**Pull request merged**
