### PR TITLE
Add lockfile-lint to CI

### LINKED ISSUE #7646: lockfile-lint integration useful?
### What problem are you trying to solve?
A neat idea to increase lockfile security by using [lockfile-lint](https://github.com/lirantal/lockfile-lint/tree/master/packages/lockfile-lint), see an article on snyk.io
https://snyk.io/blog/why-npm-lockfiles-can-be-a-security-blindspot-for-injecting-malicious-modules/

### Describe the solution you'd like
**1.** The command `npx lockfile-lint --path yarn.lock --type yarn --validate-https --allowed-hosts registry.yarnpkg.com` returns a lot of warnings:

```
detected invalid protocol for package: bignumber.js@git+https://github.com/debris/bignumber.js.git#94d7146671b9719e00a09c29b01a691bc85048c2
    expected: https:
    actual: git+https:

detected invalid protocol for package: bignumber.js@git+https://github.com/frozeman/bignumber.js-nolookahead.git
    expected: https:
    actual: git+https:

detected invalid protocol for package: ethereumjs-abi@0.6.7
    expected: https:
    actual: git+https:

detected invalid protocol for package: ethereumjs-abi@git+https://github.com/ethereumjs/ethereumjs-abi.git
    expected: https:
    actual: git+https:

detected invalid protocol for package: module-name-from-path@git+https://git@github.com/kumavis/module-name-from-path.git
    expected: https:
    actual: git+https:

detected invalid host(s) for package: assemblyscript@github:assemblyscript/assemblyscript#v0.6
    expected: registry.yarnpkg.com
    actual: codeload.github.com

detected invalid host(s) for package: bignumber.js@git+https://github.com/debris/bignumber.js.git#94d7146671b9719e00a09c29b01a691bc85048c2
    expected: registry.yarnpkg.com
    actual: github.com

detected invalid host(s) for package: bignumber.js@git+https://github.com/frozeman/bignumber.js-nolookahead.git
    expected: registry.yarnpkg.com
    actual: github.com

detected invalid host(s) for package: concat-stream@github:hugomrdias/concat-stream#feat/smaller
    expected: registry.yarnpkg.com
    actual: codeload.github.com

detected invalid host(s) for package: ethereumjs-abi@0.6.7
    expected: registry.yarnpkg.com
    actual: github.com

detected invalid host(s) for package: ethereumjs-abi@git+https://github.com/ethereumjs/ethereumjs-abi.git
    expected: registry.yarnpkg.com
    actual: github.com

detected invalid host(s) for package: level-js@github:timkuijsten/level.js#idbunwrapper
    expected: registry.yarnpkg.com
    actual: codeload.github.com

detected invalid host(s) for package: module-name-from-path@git+https://git@github.com/kumavis/module-name-from-path.git
    expected: registry.yarnpkg.com
    actual: github.com

detected invalid host(s) for package: ndjson@github:hugomrdias/ndjson#feat/readable-stream3
    expected: registry.yarnpkg.com
    actual: codeload.github.com

detected invalid host(s) for package: pull-ws@hugomrdias/pull-ws#fix/bundle-size
    expected: registry.yarnpkg.com
    actual: codeload.github.com

detected invalid host(s) for package: webcrypto-shim@github:dignifiedquire/webcrypto-shim#master
    expected: registry.yarnpkg.com
    actual: codeload.github.com

detected invalid host(s) for package: webrtcsupport@github:ipfs/webrtcsupport
    expected: registry.yarnpkg.com
    actual: codeload.github.com

detected invalid host(s) for package: websocket@github:web3-js/WebSocket-Node#polyfill/globalThis
    expected: registry.yarnpkg.com
    actual: codeload.github.com
```

**2.** The command `npx lockfile-lint --path yarn.lock --type yarn --allowed-hosts registry.yarnpkg.com --allowed-schemes "https:" "git+https:"` returns a little less items:

```
detected invalid host(s) for package: assemblyscript@github:assemblyscript/assemblyscript#v0.6
    expected: registry.yarnpkg.com
    actual: codeload.github.com

detected invalid host(s) for package: bignumber.js@git+https://github.com/debris/bignumber.js.git#94d7146671b9719e00a09c29b01a691bc85048c2
    expected: registry.yarnpkg.com
    actual: github.com

detected invalid host(s) for package: bignumber.js@git+https://github.com/frozeman/bignumber.js-nolookahead.git
    expected: registry.yarnpkg.com
    actual: github.com

detected invalid host(s) for package: concat-stream@github:hugomrdias/concat-stream#feat/smaller
    expected: registry.yarnpkg.com
    actual: codeload.github.com

detected invalid host(s) for package: ethereumjs-abi@0.6.7
    expected: registry.yarnpkg.com
    actual: github.com

detected invalid host(s) for package: ethereumjs-abi@git+https://github.com/ethereumjs/ethereumjs-abi.git
    expected: registry.yarnpkg.com
    actual: github.com

detected invalid host(s) for package: level-js@github:timkuijsten/level.js#idbunwrapper
    expected: registry.yarnpkg.com
    actual: codeload.github.com

detected invalid host(s) for package: module-name-from-path@git+https://git@github.com/kumavis/module-name-from-path.git
    expected: registry.yarnpkg.com
    actual: github.com

detected invalid host(s) for package: ndjson@github:hugomrdias/ndjson#feat/readable-stream3
    expected: registry.yarnpkg.com
    actual: codeload.github.com

detected invalid host(s) for package: pull-ws@hugomrdias/pull-ws#fix/bundle-size
    expected: registry.yarnpkg.com
    actual: codeload.github.com

detected invalid host(s) for package: webcrypto-shim@github:dignifiedquire/webcrypto-shim#master
    expected: registry.yarnpkg.com
    actual: codeload.github.com

detected invalid host(s) for package: webrtcsupport@github:ipfs/webrtcsupport
    expected: registry.yarnpkg.com
    actual: codeload.github.com

detected invalid host(s) for package: websocket@github:web3-js/WebSocket-Node#polyfill/globalThis
    expected: registry.yarnpkg.com
    actual: codeload.github.com
```

**3.** The extended command `npx lockfile-lint --path yarn.lock --type yarn --allowed-hosts registry.yarnpkg.com github.com codeload.github.com --allowed-schemes "https:" "git+https:"` returns no warnings.

### Question
Make a lockfile lint sense? I mean, malicious packages can also be placed on trusted hosts like GitHub and npm/yarnpkg.

### PR DESCRIPTION
**Pull request by whymarrh**
Closes #7646

This PR adds a [lockfile-lint](https://github.com/lirantal/lockfile-lint) CI job. This allows us at least make sure that we don't accidentally add any deps from new hosts.

### CODE REVIEW

**Comment by whymarrh** [comment]
It would be nice to migrate everything to just HTTPS but this is good for now.

**Comment by Gudahtt** [comment]
>It would be nice to migrate everything to just HTTPS but this is good for now.

Not sure what you're referring to here; are we using HTTP somewhere?

**Comment by whymarrh** [comment]
> Not sure what you're referring to here; are we using HTTP somewhere?

We have some Git URLs that I'd love to remove

**Comment by whymarrh** [comment]
That is,

```diff
- --allowed-schemes \"https:\" \"git+https:\"
+ --allowed-schemes \"https:\"
```

**Review by Gudahtt — APPROVED** [review]
Thanks, this looks useful!

**Pull request merged**
