### PR TITLE
fix: misleading gas fee label in UI

### PR DESCRIPTION
**Pull request by maczniak**
## **Description**

The UI label for max ~~base~~ fee per gas is "Max base fee" (key `maxBaseFee`). I correct this label to "Max fee" (key `maxFee`). Thank Hee Jung Sonny Son for reporting!

### **Before**

screenshot in English https://gist.github.com/assets/3060954/a1850425-f25a-46a3-960c-5ab36c390632
screenshot in Korean https://gist.github.com/assets/3060954/6737b0c5-778b-43d4-bd0c-393e4b664aad

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by maczniak** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by HowardBraham** [comment]
I'm confused about why this PR fails the step `prep-deps`, but also, I think the screen is correct as-is.  It's the maximum of how much you will pay for the "base fee."

**Comment by maczniak** [comment]
In the first screenshot,
* Max fee 0.00026301 ETH
* Max base fee 12.5244
* Priority Fee 0.0565
* Gas limit 21000

I did simple math.
fee = (base fee + priority fee) * gas amount
0.00026301 * 10^18 = (12.5244) * 10^9 * 21000 =/= (12.5244 + 0.0565) * 10^9 * 21000

Wait... Yes, technically, max base fee (per gas) is the same as max fee (per gas) because it is a upper limit. If it is intended, please ignore this pull request.

**Comment by segun** [comment]
Follow up on slack discussion around this issue [https://consensys.slack.com/archives/C4V2HTG0Y/p1708710402351709](https://consensys.slack.com/archives/C4V2HTG0Y/p1708710402351709)

**Review by brad-decker — APPROVED** [review]

**Review by brad-decker — CHANGES_REQUESTED** [review]
Erroneously approved. waiting for resolution of conversation internally.

**Review by matthewwalsh0 — APPROVED** [review]

**Review by digiwand — APPROVED** [review]
The update looks good to me. Base fee ≠ MaxFeePerGas and Max Fee Per Gas may be shortened to Max Fee. 

If we wanted to also display the base fee, we could add this in a follow-up PR.

**Review by HowardBraham — APPROVED** [review]

**Pull request merged**
