### PR TITLE
Support for ENS wildcard and offchain resolution

### PR DESCRIPTION
**Pull request by makoto**
## Explanation

This PR addresses https://github.com/MetaMask/specifications/issues/9

NOTE: Support for contenthash will be separate PR.

## More information

Please read https://medium.com/the-ethereum-name-service/upgrade-ethers-js-to-5-6-1-to-activate-ens-l2-offchain-integration-40ee1a0fdf2a for more deail.

### Display forward lookup

Screenshot 2022-04-25 at 16 36 05

### Display reverse record (aka primary name)

Screenshot 2022-04-25 at 16 35 48

## Manual testing steps

- 1. Select testnet (Ropsten/Rinkeby/Goerli network)
- 2. Lookup 1.offchainexample.eth to lookup ENS name
- 3. Send ETH to 1.offchainexample.eth and check it shows in the transaction log

### CODE REVIEW

**Comment by jacobc-eth** [comment]
Hey Makoto, we're discussing this on our side! In the meantime, would you consider submitting a similar PR for MetaMask Mobile? We try to avoid situations where features are only available on one client to the extent possible.

**Comment by makoto** [comment]
> would you consider submitting a similar PR for MetaMask Mobile?

I can give it a try but do your mobile apps also use js so that I can just upgrade ethers.js that does the majority of the support work?

**Comment by jacobc-eth** [comment]
@makoto yep, our mobile app is React Native.

**Comment by brad-decker** [comment]
Closing in favor of #14675

**Pull request closed without merging**
