### PR TITLE
Validate empty key

### PR DESCRIPTION
**Pull request by danfinlay**
Previously importing an empty string would result in a new empty Keyring
object to be constructed, with no notification to the user.

Now we render a clear error explaining the mistake.

This would not result in any bad accounts, just a memory leak.

### CODE REVIEW

**Comment by kumavis** [comment]
I think we need strong validation, like making sure the private key is actually valid
I think a privateKey `'banana'` would still generate an empty keyring

**Comment by danfinlay** [comment]
Added a commit that includes much more strong private key importing validations, but for some reason they fail. Will have to revisit at some point. Should be easy for someone else to pick up, if they wanted to finish this out.

**Comment by kumavis** [comment]
1) `assert.throws` only works for synchronous methods. `assert.rejects` is added is node v10 for awaiting promises
2) in async functions, you need to await the method to catch the error in a try-catch
3) ethereumjs-util takes non-hex-prefixed strings and buffer encodes them as utf8 (!)

**Comment by danfinlay** [comment]
I would approve this, but I can't b/c I opened the PR. Thanks for clarifying the assert.fails/async issue.

**Review by kumavis — APPROVED** [review]

**Comment by kumavis** [comment]
BY THE POWER VESTED IN ME, I DECLARE YOU APPROVED. YOU MAY NOW MERGE WITH THE BASE.

**Pull request merged**
