### PR TITLE
Add Kovan explorer

### PR DESCRIPTION
**Pull request by ivigamberdiev**
Fix Kovan Etherscan link in network constants.

### CODE REVIEW

**Comment by rekmarks** [comment]
Thank you for opening this PR, @ivigamberdiev. If you sign the CLA, I'll go ahead and merge immediately!

**Comment by Ariful369** [comment]
ivigamberdiev:patch-2

**Comment by ivigamberdiev** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by rekmarks — APPROVED** [review]
Thanks again!

**Pull request merged**
