### PR TITLE
New slide up modal added

### LINKED ISSUE #15855: Create new modal component
## Resources
[Figma Design file](https://www.figma.com/file/n0xMnZqQz4w9Sfa3ZdhWUi/Consentful-experience-for-token-allowances?node-id=2007%3A14708)
[Figma prototype with animation](https://www.figma.com/proto/n0xMnZqQz4w9Sfa3ZdhWUi/Consentful-experience-for-token-allowances?page-id=3781%3A26973&node-id=3781%3A26974&viewport=138%2C336%2C0.63&scaling=min-zoom&starting-point-node-id=3781%3A26974)

## Acceptance Criteria
1. New modal component is created following the design;
2. Modal slides up when opened and slides out (down) when dismissed (see Figma prototype with animation above);
3. This modal can be used in different parts of the product to display different content as exemplified in the screenshot below.
Screen Shot 2022-09-20 at 17 19 21

### PR DESCRIPTION
**Pull request by amerkadicE**
## Explanation

New slide up modal in the storybook so we can reuse it on multiple screens. 

Fixes #15855 

### After

image

## Manual Testing Steps

Go to StoryBook
Find SlideUp component
Check animation

## Pre-Merge Checklist

- [x] PR template is filled out
- [x] **IF** this PR fixes a bug, a test that _would have_ caught the bug has been added
- [x] PR is linked to the appropriate GitHub issue
- [ ] PR has been added to the appropriate release Milestone

### + If there are functional changes:

- [ ] Manual testing complete & passed
- [ ] "Extension QA Board" label has been applied

### CODE REVIEW

**Comment by mirjanaKukic** [comment]
Verified by QA

**Review by georgewrmarshall — COMMENTED** [review]
Oh interesting. I wasn't aware that we were using these slide up modals in the extension. Is there any reason to not use a normal modal for the application in the design? And what would constitute using one over the other? cc @SayaGT @bschorchit @Akatori-Design

If we are including this component in the extension I'm interested to know what it should look like in expanded view? Should it look like more of a conventional modal that is positioned in the centre of the screen?

I think it can be slightly refined so the scroll bar isn't visible when it animates in and I believe the overlay should fade in instead of appear.


https://user-images.githubusercontent.com/8112138/195211939-d03da319-28aa-453e-b095-08f497e97b57.mov

**Comment by Akatori-Design** [comment]
+1 for @georgewrmarshall that we should use a center-justified `modal` instead. This might be a design that was created when `sheet` type view was being explored in Extension iterations. In the new extension designs, `modal` is used for all modality views, and `sheet` is being reserved for mobile only. 
cc: @SayaGT  @bschorchit

**Comment by bschorchit** [comment]
As decided in [this slack thread](https://consensys.slack.com/archives/G4V2HTG0Y/p1665591084399769?thread_ts=1665590966.455449&channel=G4V2HTG0Y&message_ts=1665591084.399769) we should use the center justified modal instead of this new modal.

**Pull request closed without merging**
