### PR TITLE
test - unit - fail if tests contain a .only call

### PR DESCRIPTION
**Pull request by kumavis**
`.only` was accidently committed a couple times, this will catch it in the test suite

### CODE REVIEW

**Comment by whymarrh** [comment]
Instead of introducing a separate tool for this, it might be worth using [`eslint-plugin-mocha`](https://github.com/lo1tuma/eslint-plugin-mocha)'s [`no-exclusive-tests`](https://github.com/lo1tuma/eslint-plugin-mocha/blob/master/docs/rules/no-exclusive-tests.md) rule since ESLint is already part of the project.

**Comment by kumavis** [comment]
we dont currently lint our tests
```
[11:16:09] ESLintError in plugin 'gulp-eslint'
Message:
    Failed with 303 errors
Details:
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false
```

adding those will require some fixes

**Comment by kumavis** [comment]
started a lint rework but it got out of hand https://github.com/MetaMask/metamask-extension/pull/4395

**Comment by kumavis** [comment]
@whymarrh lets merge this and then remove it in #4395 whenever that lands

**Review by whymarrh — APPROVED** [review]

**Pull request merged**
