### PR TITLE
fix: update sepolia nickname on signature request

### PR DESCRIPTION
**Pull request by sahar-fehri**
## **Description**

Updates the nickname displayed for Sepolia network when the signature request is triggered

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/24692?quickstart=1)

## **Related issues**

Fixes:
Relates to: https://github.com/MetaMask/metamask-extension/issues/24043

## **Manual testing steps**

1. Switch to Sepolia
2. Go to test dapp and trigger a signature request (exp: click on deploy token)
3. You should see Sepolia displayed

### **Before**

https://github.com/MetaMask/metamask-extension/assets/10994169/d0403f93-cd72-445a-8e86-36807461a6d7

### **After**

https://github.com/MetaMask/metamask-extension/assets/10994169/8dceceaa-e5d4-4f4f-b58f-bb75dbda436e

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by darkwing — APPROVED** [review]

**Comment by bergeron** [comment]
My interpretation of bug https://github.com/MetaMask/metamask-extension/issues/24043 is that it wants to display "Sepolia test network" instead of "Sepolia" i.e. the other way around from this PR.

This PR's video recording does `create token` on the test dapp, which does not reproduce the bug for me.  I think you have to do a signature rather than a transaction.  For example`sign typed data`, which does:

Screenshot 2024-06-10 at 12 31 17 PM

**Review by bergeron — CHANGES_REQUESTED** [review]
My interpretation of bug https://github.com/MetaMask/metamask-extension/issues/24043 is that it wants to display "Sepolia test network" instead of "Sepolia" i.e. the other way around from this PR.

This PR's video recording does `create token` on the test dapp, which does not reproduce the bug for me.  I think you have to do a signature rather than a transaction.  For example`sign typed data`, which does:

Screenshot 2024-06-10 at 12 31 17 PM

maybe @seaona can advise

**Comment by bschorchit** [comment]
We use different names for Sepolia across the wallet. The issue might be likely where we're pulling these names from rather than specifically to confirmations?

Screenshot 2024-04-16 at 11 44 45
Screenshot 2024-04-16 at 11 42 14
Screenshot 2024-04-16 at 11 43 50
Screenshot 2024-04-16 at 11 43 43

**Comment by sahar-fehri** [comment]
Closing this after this comment https://github.com/MetaMask/metamask-extension/issues/24043#issuecomment-2189684993

**Pull request closed without merging**
