### PR TITLE
Fix: typos

### PR DESCRIPTION
**Pull request by omahs**
Fix: typos

### CODE REVIEW

**Review by brad-decker — DISMISSED** [review]
Man you took the 'the' right out of my mouth. Thanks!

**Review by mcmire — DISMISSED** [review]
Nice! Thanks for the PR @omahs.

**Comment by omahs** [comment]
Is the PR missing a label? @mcmire

**Comment by omahs** [comment]
should we merge? @mcmire

**Review by HowardBraham — APPROVED** [review]

**Review by DDDDDanica — APPROVED** [review]

**Pull request merged**
