### PR TITLE
[i18n:gu] Update `gu` localized messages

### PR DESCRIPTION
**Pull request by MonarthS**

### CODE REVIEW

**Comment by MonarthS** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by MonarthS** [comment]
@Gudahtt can we add this?

**Comment by mcmire** [comment]
Hi @MonarthS, I'm sorry it's taken us so long to get back to you on this. Would you mind rebasing your changes? You may have to do another passthrough given the number of changes that have taken place since your last commit. Sorry :(

**Comment by brad-decker** [comment]
@MonarthS thanks for being patient with us, and apologies for the delay in response. Our translation system is now active but we still welcome community corrections. If you'd like to see this merged please rebase and fix any conflicts, then tag me for review. Thanks for your submission!

**Pull request closed without merging**
