### PR TITLE
Change Ci Badge url for readme

### PR DESCRIPTION
**Pull request by tmashuang**
Update url from plugin to extension for ci badge.

### CODE REVIEW

**Comment by tmashuang** [comment]
SVG or Shield?

**Comment by kumavis** [comment]
svg: [svg](https://circleci.com/gh/MetaMask/metamask-extension)

shield: [shield](https://circleci.com/gh/MetaMask/metamask-extension)

**Comment by tmashuang** [comment]
which looks better?

**Comment by kumavis** [comment]
I guess i like shield better - has a label explaining what is passing

**Review by kumavis — APPROVED** [review]

**Pull request merged**
