### PR TITLE
Checking for sufficient balance in tx confirmation screen

### LINKED ISSUE #3471: Check for sufficient balance on new-ui confirm screen
We currently check whether balance is sufficient on the send screen, but not the confirm screen. We need to check on confirm as well to handled transactions coming from dApps.

### PR DESCRIPTION
**Pull request by danjm**
Fixes #3471 

mar-27-2018 23-21-59

### CODE REVIEW

**Comment by kumavis** [comment]
@danjm merge conflicts and lint errors

**Review by kumavis — CHANGES_REQUESTED** [review]
Code looks good but i realize feature parity is still behind old-ui:
- does not auto update when changing the params

**Comment by kumavis** [comment]
> does not auto update when changing the params
as in changing gasPrice does not trigger an update to the warning

**Comment by danjm** [comment]
> does not auto update when changing the params

@kumavis fixed with d6ebf5d9

clearinsufficienterror

**Review by alextsg — APPROVED** [review]

**Comment by kumavis** [comment]
Please also check for sufficient balance on first render

**Comment by kumavis** [comment]
waiting to merge https://github.com/MetaMask/metamask-extension/pull/3788 first

**Review by kumavis — APPROVED** [review]

**Pull request merged**
