### PR TITLE
18566 firefox ledger u2f message

### LINKED ISSUE #18566: [Bug]: Ledger is no longer working on Firefox
### Describe the bug

The Ledger integration on Firefox is no longer working due to the latest version of Firefox dropping support for U2F. 

Internal Slack conversation: https://consensys.slack.com/archives/GTQAGKY5V/p1679484733528029 

### Steps to reproduce

Try and connect a Ledger to Firefox 112 and you'll see this error:
image

### Error messages or log output

_No response_

### Version

Firefox 112

### Build type

None

### Browser

Firefox

### Operating system

MacOS

### Hardware wallet

Ledger

### Additional context

We don't know a long term fix right now, so I'm proposing a super small copy change to the existing error message to direct users to a Ledger article describing a workaround. 

We should change the existing Firefox warning text from:
> We had trouble connecting to your ledger, try reviewing our hardware wallet connection guide 

To:
> We had trouble connecting to your Ledger, try reviewing our [hardware wallet connection guides](https://support.metamask.io/hc/en-us/articles/4408552261275-Hardware-Wallet-Hub#:~:text=MetaMask%20currently%20supports%20five%20lines,to%20Mobile%20in%20future%20updates.).  If you're using the latest version of Firefox you might be experiencing a specific issue related Firefox dropping U2F support, for instructions on how to fix this issue go [here](https://support.ledger.com/hc/en-us/articles/10371387758493-MetaMask-Firefox-Ledger-Integration-Issue?support=true). 

We should also add an on click metrics event to this support article. Something like `Ledger-firefox-support-article-clicked`

### PR DESCRIPTION
**Pull request by montelaidev**
## Explanation

Changes the error description for the U2F connection with Ledger using firefox.

Fixes #18566

### Before
Screenshot 2023-04-13 at 7 47 18 PM

### After
Screenshot 2023-04-13 at 11 38 46 PM

Screenshot 2023-04-14 at 10 06 28 AM

## Manual Testing Steps
On Firefox
1. Click on connect hardware wallet.
2. Select Ledger.
3. Click on continue with your ledger still locked.

On Chrome
1. Click on settings.
2. Click on Advanced
3. Select U2F in the dropdown of Preferred Ledger connection type.
4. Go back to home
5. Click on connect hardware wallet.
6. Select Ledger.
7. Click on continue with your ledger still locked.

## Pre-merge author checklist

- [ x I've clearly explained:
  - [ x] What problem this PR is solving
  - [ x] How this problem was solved
  - [ x] How reviewers can test my changes
- [ x] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

### CODE REVIEW

**Comment by coreyjanssen** [comment]
Made a few copy improvements to your proposed changes. Hopefully it isn't too late to implement these. 

```
We're having trouble connecting your Ledger. Review our hardware wallet connection guide and try again. 
If you're on the latest version of Firefox, you might be experiencing an issue related to Firefox dropping U2F support. Learn how to fix this issue here.
```

**Comment by danjm** [comment]
@montelaidev @AlexJupiter  we might need to also consider the case of a user who has already connected their wallet, and then their firefox updates. We'll want to show them a warning somewhere.

Something we could do is add a "What's new" message, and only display it to ledger users on firefox. This way, all ledger users currently connected will see a message when the version updates

**Comment by montelaidev** [comment]
> @montelaidev @AlexJupiter we might need to also consider the case of a user who has already connected their wallet, and then their firefox updates. We'll want to show them a warning somewhere.
> 
> Something we could do is add a "What's new" message, and only display it to ledger users on firefox. This way, all ledger users currently connected will see a message when the version updates

Sure, i've added a new Whats New message for firefox and ledger users.

**Review by danjm — APPROVED** [review]
Looks good. Nice work!

**Review by brad-decker — APPROVED** [review]

**Pull request merged**
