### PR TITLE
update text component color to use box color

### LINKED ISSUE #18209: Refactor Text component to use Box color prop
### Description
Currently the `Text` component is using it's own logic and classNames to decide on the css `color`. This is creating extra classNames and CSS that isn't necessary as well as complicates tests when change the root component from `Box` to `Text`.

The `Text` component should be refactored to just utilize the `Box` color prop instead of creating it's own version

### Technical Details
- Remove the `color` prop logic and css from the Text component
- Update Tests 

### Acceptance Criteria 
- `Text` component uses the `Box` component `color` prop
- Checking for a color class on the `Text` component should just check for the `box--color-[color]`

### PR DESCRIPTION
**Pull request by garrettbear**
## Explanation

Update `Text` component to utilize the `Box` component class and remove the need for excess classnames. 

* Fixes #18209 

## Screenshots/Screencaps
No visual change

### Before
Screenshot 2023-03-20 at 3 05 02 PM

### After
Screenshot 2023-03-20 at 3 01 36 PM

## Manual Testing Steps
`yarn jest ui/components/component-library`

## Pre-merge author checklist

- [X] I've clearly explained:
  - [X] What problem this PR is solving
  - [X] How this problem was solved
  - [X] How reviewers can test my changes
- [X] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [X] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [X] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Review by georgewrmarshall — COMMENTED** [review]
Code LGTM! Just need a build to check storybook

**Review by brad-decker — DISMISSED** [review]

**Review by darkwing — DISMISSED** [review]

**Review by NidhiKJha — COMMENTED** [review]
Code looks good to me but need to check the colors here. I am not sure if this is correct for `goerli inverse` and `sepolia inverse`


https://user-images.githubusercontent.com/39872794/226990427-30eaa7ed-0af3-436f-b269-949acbdf00f8.mov

**Review by georgewrmarshall — COMMENTED** [review]
Code looks good! Just need to fix the issue @NidhiKJha outlined

**Review by NidhiKJha — DISMISSED** [review]

**Review by NidhiKJha — APPROVED** [review]

**Review by georgewrmarshall — APPROVED** [review]
Really nice work 🎸

**Pull request merged**
