### PR TITLE
advanced settings: add test faucet

### PR DESCRIPTION
**Pull request by jennypollack**

### CODE REVIEW

**Comment by danjm** [comment]
The code looks good @jennypollack!

Can you add an explanation of the reason for this change to the description?

Also, I notice that the "Test Faucet" button on the settings page will open the deposit modal. Any reason we do that instead of taking the user to the faucet directly?

And I wonder if we should just show this button on networks for which we have explicit faucet links? I think that's just Ropsten and Rinkeby. One way it could work is that the button on settings page would only be shown if either of those networks is selected, and clicking the button would open a tab with the respective faucet url.

**Review by kumavis — DISMISSED** [review]

**Comment by kumavis** [comment]
this will have conflict with https://github.com/MetaMask/metamask-extension/pull/5575

**Comment by bdresser** [comment]
@danjm @jennypollack we good to merge this?

**Comment by whymarrh** [comment]
This has a few conflicts so I'm going to close this for now. We can reopen it when we update it.

**Pull request closed without merging**
