### PR TITLE
Adopt new version of `@metamask/signature-controller` to add signature operation logs

### PR DESCRIPTION
**Pull request by OGPoyraz**
## **Description**

This PR aims to update `@metamask/signature-controller@^6.1.2` in order to adopt add logs on signature operations.

## **Manual testing steps**

There is no functional change in signatures. But if you get signature request, sign or rejects, that should end up in `MetaMask State Logs.json` which could be downloaded under `Settings>Download State Logs`

## **Screenshots/Recordings**

I am adding an example of state logs as a proof. (Please note that I've removed locale messages to make file a bit smaller)
[MetaMask state logs.txt](https://github.com/MetaMask/metamask-extension/files/12816449/MetaMask.state.logs.txt)

## **Related issues**

_Fixes https://github.com/MetaMask/MetaMask-planning/issues/1321

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained:
  - [x] What problem this PR is solving.
  - [x] How this problem was solved.
  - [x] How reviewers can test my changes.
- [x] I’ve indicated what issue this PR is linked to: Fixes #???
- [x] I’ve included tests if applicable.
- [x] I’ve documented any added code.
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)).
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by OGPoyraz** [comment]
@metamaskbot update-policies

**Review by brad-decker — DISMISSED** [review]

**Comment by sleepytanya** [comment]
Signature requests are logged in `MetaMask State Logs.json`

**Review by matthewwalsh0 — DISMISSED** [review]

**Review by vinistevam — DISMISSED** [review]

**Comment by OGPoyraz** [comment]
@metamaskbot update-policies

**Review by matthewwalsh0 — DISMISSED** [review]

**Review by vinistevam — DISMISSED** [review]

**Comment by OGPoyraz** [comment]
@metamaskbot update-policies

**Review by matthewwalsh0 — APPROVED** [review]

**Review by vinistevam — APPROVED** [review]

**Pull request merged**
