### PR TITLE
Fix incorrectly showing checksums on non-ETH blockchains

### PR DESCRIPTION
**Pull request by jonathansmirnoff**
This PR fix the issue: https://github.com/MetaMask/metamask-extension/issues/5838

### CODE REVIEW

**Comment by jonathansmirnoff** [comment]
@whymarrh did you have the chance to review this PR?

**Comment by whymarrh** [comment]
Hey @jonathansmirnoff, thanks for this PR! Firstly, can we rebase this on the latest `develop` to try for a green build. Also, I'm not sure that adding custom RSK-specific logic is a good solution here... maybe there's a way to do this without being specific?

**Comment by jonathansmirnoff** [comment]
@whymarrh thanks for your review. I will do the rebase.
Also I will try to some changes in the logic to check the network to avoid RSK specific logic.

**Comment by jonathansmirnoff** [comment]
@whymarrh is it possible that **ci/circleci: test-e2e-beta-drizzle** test is not working?

**Comment by jonathansmirnoff** [comment]
@whymarrh I implemented a few changes, I think that now it is more clear the code. I put the logic of the network check in the function `checksumAddress`:

```
function checksumAddress (address, network) {
  const checksummed = address ? ethUtil.toChecksumAddress(address) : ''
  return checksummed && network && !isEthNetwork(network) ? checksummed.toLowerCase() : checksummed
}
```
So now I pass the networkid to the checksumAddress function. For example:
`const checksummedAddress = checksumAddress(selectedAddress, network) `

Let me know what do you think about this. 
Also yesterday I fixed the issue with the test. But now I get the last of develop and I have a few test that aren't passing. Do you know if there any with them?

Thanks!

**Comment by jonathansmirnoff** [comment]
I will do another PR to be more clear with the history.

**Pull request closed without merging**
