### PR TITLE
Implemented Keevo hardware wallet support

### PR DESCRIPTION
**Pull request by AlexanderPodlesniyQs**
### Description

Implemented support of [Keevo hardware wallet](https://www.keevowallet.com).

### Changes

Added [@keevo/keevo-metamask-keyring](https://github.com/keevowallet/keevo-metamask-keyring) dependency.
Added Keevo keyring type.
Added Keevo device.
Added Keevo connect URL.
Added Keevo button.
Updated Lavamoat policies.

### CODE REVIEW

**Comment by AlexanderPodlesniyQs** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by porqz** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by porqz** [comment]
Hey, @kumavis, @darkwing! We have fixed all the issues with tests and now the PR is ready to be reviewed. Please take a look. Thank you!

**Comment by Gudahtt** [comment]
Thanks for the contribution! Unfortunately we're not accepting any more hardware wallet integrations at this time. QA and maintenance of hardware wallet integrations has been a huge burden for our team in the past, and we're focusing now on making our existing integrations more robust and maintainable before considering new ones. We're also working on adding support for hardware wallets to our new snaps API so that new hardware wallets can be more easily integrated in the future.

For now I'd suggest creating a topic for this in [the "Feature Request" category of our Community forum](https://community.metamask.io/c/feature-requests-ideas/13) to help us keep track of this request, and we'll get back to you as soon as we can about any updates.

**Pull request closed without merging**
