### PR TITLE
chore: Create a story for TokenCurrencyDisplay component

### PR DESCRIPTION
**Pull request by Devin-Apps**
## **Description**

This PR introduces a Storybook story for the TokenCurrencyDisplay component to facilitate isolated UI testing and development.

## **Related issues**
N/A

## **Manual testing steps**

1. Go to the latest build of storybook in this PR
2. Navigate to the TokenCurrencyDisplay component in the Components/UI folder.

## **Screenshots/Recordings**

Screenshot 2024-06-12 at 2 22 56 AM

## **Pre-merge author checklist**

- [X] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

[Devin Run](https://preview.devin.ai/devin/2160d3493b21468dbb83691ab5fefe84)

### CODE REVIEW

**Review by georgewrmarshall — APPROVED** [review]
LGTM!

**Review by garrettbear — APPROVED** [review]

**Comment by garrettbear** [comment]
Try rebasing to see if it resolves the failing tests. The failures are not caused by this PR.

**Review by georgewrmarshall — COMMENTED** [review]
Merging with `develop` branch should resolve this issue

**Comment by georgewrmarshall** [comment]
Closing in favor of https://github.com/MetaMask/metamask-extension/pull/26172 can't get Devin to reset soft and hard push to fix these tests

Screenshot 2024-07-26 at 3 05 58 PM

**Pull request closed without merging**
