### PR TITLE
add rinkeby network

### PR DESCRIPTION
**Pull request by nnn-gif**
#1327 
TBD
1) Network icon 
2) Redirect to  Rinkeby GitHub Authenticated Faucet
3) RPC url for rinkeby  for now it is https://rinkeby.infura.io

### CODE REVIEW

**Comment by flyswatter** [comment]
Oh nice, @zanibas look he beat you to it!

**Comment by flyswatter** [comment]
@vladtod any thoughts on additional test net icons? Maybe stick with the hollow diamond but in different colors?

**Review by 2-am-zzz — APPROVED** [review]
Thank you for this submission! Just added a few missing files as well as an addendum to our README for future contributions! ^_^

**Review by danfinlay — APPROVED** [review]

**Comment by flyswatter** [comment]
Since we don't run tests from external contributors, I've pulled & reopened this PR as #1352, will merge there after tests pass.  Thanks @niktrix and congrats on your first contribution!

**Pull request merged**
