### PR TITLE
Add benchmark to CI

### LINKED ISSUE #6881: Measure changes in performance
It would be helpful to track performance changes over time, and on pull requests. We've profiled the performance of the various interfaces manually, but this profiling is not done very often. Having this information collected automatically would help us make better informed decisions.

There are few different metrics we could focus on, but it might be best to focus on user-centric metrics (as described in [this article](https://developers.google.com/web/fundamentals/performance/user-centric-performance-metrics)).

The three user interfaces we could profile are `home.html`, `popup.html`, and `notification.html`. Additionally, we could use something like [exthouse](https://github.com/treosh/exthouse) to track the performance impact our extension has upon other pages.

### PR DESCRIPTION
**Pull request by Gudahtt**
The page load benchmark for Chrome is now run during CI, and the results are collected and summarized in the `metamaskbot` comment.

Closes  #6881

### CODE REVIEW

**Comment by Gudahtt** [comment]
This depends upon #7869 and #7870 , so the commits from each of those PRs have been cherry-picked into this branch. To review this in the meantime, you can look at this commit: https://github.com/MetaMask/metamask-extension/pull/7871/commits/dd6326f208c9c7d127c3ee79772c00e3fef84a96

**Comment by Gudahtt** [comment]
^ Hey, it works finally!

I messed up the formatting of that message a good few times, but it should be good now.

**Comment by Gudahtt** [comment]
Huh, well the variation between those two page load times isn't encouraging :thinking: 
I'll try a few more runs.

**Comment by Gudahtt** [comment]
I was getting _dramatically_ different results locally today (~3 times larger for each metric), and it turns out it was because I used the dev build! Apparently it's _a lot_ slower. I know that shouldn't be surprising but I didn't expect the difference to be so large.

**Comment by Gudahtt** [comment]
Now that it's taking 20 samples rather than 10, these results are looking a lot more consistent! Not bad.

It still only takes 2 minutes to collect all 20 samples, so I think this is a good number to stay with for now.

**Review by whymarrh — APPROVED** [review]
LGTM

**Pull request merged**
