### PR TITLE
trim unused account-list-item code and co-locate styles

### PR DESCRIPTION
**Pull request by brad-decker**
1. account-dropdown in `itcss/components` had a mixture of used and unused styles, the `account-dropdown related styles were unused` but the `account-list-item` styles are active.
2. `account-list-item.container` was no longer used and all imports of `account-list-item` manually targeted `account-list-item.component`
3. `account-list-item` had props related to showing of balances, but this component is only used now in three places: The headers of the encryption key, decrypt, and sign data popups.
4. Each of the above places was passing in 'showBalance={false}` and importing only the component, not the requisite container.
5. Deleted all the code and styles related to balances
6. Moved account list item from the `pages/send` folder to `components/app/` folder

All of this results in no user-facing changes

### CODE REVIEW

**Review by Gudahtt — DISMISSED** [review]
LGTM!

I did find a couple of lingering references to some now-deleted classes (`.account-list-item__account-primary-balance` and `.account-list-item__input`, in `ui/app/css/base-styles.scss`). It'd be nice to remove those at some point too.

**Comment by brad-decker** [comment]
@Gudahtt gonna look into that req as part of this PR but gonna wait until #9074 merges to avoid the inevitable rebase issues.

**Comment by brad-decker** [comment]
@Gudahtt removed those two references from base-styles.

**Review by Gudahtt — APPROVED** [review]
LGTM!

**Pull request merged**
