### PR TITLE
Fix token balance precision on confirm token approval page from soon-to-be-deprecated token allowance flow 

### LINKED ISSUE #16686: [Bug]: Approve Tokens legacy screen displays wrong decimal numbers for Token
### Describe the bug

**Problem**: the legacy screen for Approve Tokens, displays the wrong decimal numbers on the token balance when the user clicks on Edit permissions.

approve-tokens-legacy

### Steps to reproduce

1. Go to the test dapp https://metamask.github.io/test-dapp/
2. Connect MM
3. Click Create Token
4. Accept tx on MM
5. Click Approve Tokens
6. Click Edit permissions on MM popup - check top balance is displaying the wrong decimal numbers / compare to the value below the screen

### Error messages or log output

_No response_

### Version

10.23.0

### Build type

_No response_

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by digiwand**
## Explanation

Fixes #16686

As mentioned in the comments in the related issue ticket, this is a fix for UI/UX that will be deprecated in #16740 which is planned for v10.25

Since the UI/UX will be deprecated soon, I decided not to add tests for this. 

### Before

Screen Shot 2022-12-13 at 20 02 59

### After

Screen Shot 2022-12-13 at 20 05 39

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [x] How reviewers can test my changes
- [x] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [x] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [x] PR is linked to the appropriate GitHub issue
- [x] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Review by darkwing — DISMISSED** [review]

**Review by jpuri — DISMISSED** [review]

**Comment by jpuri** [comment]
This [PR](https://github.com/MetaMask/metamask-extension/pull/16676) it seems is doing opposite change.

**Comment by digiwand** [comment]
Thanks for the reference @jpuri. hmm.. the referenced PR addresses another value on a different element. The logic to shorten lengthy values is handy.

@darkwing @jpuri

Earlier, I took the first solution from a similar component, `metamask-extension/ui/pages/token-allowance/token-allowance.js`. Since we should handle N length, I re-added precision logic. Please re-review 🙏 

Separate from this PR, I think we should double-check that lengthy values from `metamask-extension/ui/pages/token-allowance/token-allowance.js` are being handled properly

**Review by jpuri — DISMISSED** [review]
👍 I am wondering do we have a utility method to do this, if not will be n ice to add one. Not necessarily in this PR.

**Comment by jpuri** [comment]
Very big values may appear as
```
parseFloat(10000000000000000000).toPrecision(9)
'1.00000000e+19'
```
Not sure if this is ok.

**Comment by digiwand** [comment]
@jpuri I think it is as this is what the previous logic which compute

**Review by jpuri — DISMISSED** [review]

**Comment by jpuri** [comment]
In that case I think its ok to merge this PR for 10.24.0 and this issue should take care to fix [all](https://github.com/MetaMask/metamask-extension/issues/16427) occurances of scientific notation.

**Comment by digiwand** [comment]
@jpuri 

Great suggestion mentioned here https://github.com/MetaMask/metamask-extension/pull/16934#issuecomment-1351897608. I was about to add one and then found out that one already exist for this 😄 updated the PR once more

**Review by darkwing — APPROVED** [review]

**Review by danjm — APPROVED** [review]

**Pull request merged**
