### PR TITLE
Address Add Token design feedback

### LINKED ISSUE #3734: Add token Design feedback
This is feedback per this PR https://github.com/MetaMask/metamask-extension/pull/3710#issuecomment-376327122

@tmashuang here's the feedback I intended to include in the previous PR.

• Remove tab button hover and click state animation/transitions, having transitions on tabs are superfluous. 
• Update fonts per #3457
• Update button styles per #3457 (maybe updated already?)
• The cancel and the arrow "<" are not vertically aligned in the screenshot attached.
image

Here's the design for reference. Let's also make sure the font sizes consistent.
image

• This label is oddly positioned.
image

Please reference this design for the add token confirm screen:
image

### PR DESCRIPTION
**Pull request by yookd**
Fixes #3734 

- Removing unnecessary animation when hovering on tabs
- Adding subtitle text (`Would you like to add these tokens?`)
- Updating text to `Token balance(s)`

**Screenshots:**
Hover state on tabs:
screen shot 2018-04-02 at 5 10 40 pm

Confirmation modal: 
screen shot 2018-04-02 at 5 10 30 pm

Selected tokens with active state borders:
screen shot 2018-04-02 at 5 12 43 pm

### CODE REVIEW

**Comment by cjeria** [comment]
Will provide feedback here shortly

**Comment by cjeria** [comment]
This is close. Please see feedback.

- Update fonts to regular font weight (400) per https://github.com/MetaMask/metamask-extension/issues/3457
- Add drop shadow (see the send transaction screen)
- Make sure that the cancel button and other clickable text buttons have cursor pointer applied to them.

More feedback/specs in this screenshot
screen shot 2018-04-02 at 5 52 40 pm

**Comment by yookd** [comment]
Screenshots:

screen shot 2018-04-03 at 9 38 11 am
screen shot 2018-04-03 at 9 38 07 am
screen shot 2018-04-03 at 9 37 59 am
screen shot 2018-04-03 at 9 35 53 am
screen shot 2018-04-03 at 9 35 49 am

**Review by cjeria — COMMENTED** [review]
Looks great!

**Review by danjm — APPROVED** [review]

**Review by kumavis — APPROVED** [review]

**Pull request merged**
