### PR TITLE
Fix for #4639: display values of EIP712 typed boolean fields in the signing prompt

### PR DESCRIPTION
**Pull request by weijiekoh**
This PR fixes issue #4639.

### CODE REVIEW

**Comment by danjm** [comment]
@weijiekoh PR looks good. There is a lint error. Can you run `npm run lint` and fix the error? (You'll see a bunch of lint warnings, but we are only concerned about the error. I think you just need to use single quotes instead of double quotes.

**Comment by weijiekoh** [comment]
Thanks. Fixed that lint error with commit `f17d99f`.

**Review by danjm — APPROVED** [review]

**Comment by om26er** [comment]
Curious if this regressed in latest versions again ? The 'consent' field is supposed to be a boolean, however the dialog doesn't really show that.
metamask-regression

**Comment by Gudahtt** [comment]
Thanks for the report @om26er ! I've re-opened the original issue.

**Pull request merged**
