### PR TITLE
ignore method's 4byte to text_signature if there is none

### LINKED ISSUE #16949: [Bug]: TypeError: Cannot read properties of undefined (reading 'text_signature')
### Describe the bug

**Problem**: with a verified Contract, when I try to call one of its functions, I get the UI console error `TypeError: Cannot read properties of undefined (reading 'text_signature')`.

https://user-images.githubusercontent.com/54408225/207579605-bed243c6-e964-447a-a361-118e3e5d17a9.mp4

### Steps to reproduce

1. Set Goerli network
2. Go to the contract https://goerli.etherscan.io/address/0x0E58766584C320B41CD1dCF9364acc612E1999F7#writeContract
3. Click on Write Contract
4. Click Connect for connecting MM
5. Click `lotsOfParams`function
6. Fill the values
7. Click Write
8. Right click MM popup to inspect the console -- see error

### Error messages or log output

_No response_

### Version

10.24.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by EresDev**
Fixes #16949
## Explanation
Metamask fetches contract's method `text_signature` from https://www.4byte.directory/ by sending it `hex_signature` of the method.

For example, a request to https://www.4byte.directory/api/v1/signatures/?hex_signature=0x9aa643fd returns the following:

```
{
    "count": 1,
    "next": null,
    "previous": null,
    "results": [
        {
            "id": 848123,
            "created_at": "2022-12-17T19:27:40.645120Z",
            "text_signature": "current_timestamp()",
            "hex_signature": "0x9aa643fd",
            "bytes_signature": "¦Cý"
        }
    ]
}
```

When 4byte.directory does not have mapping from method's hex to text, it sends back an empty results response, which creates the error in console `TypeError: Cannot read properties of undefined (reading 'text_signature').` 

For example, a request to https://www.4byte.directory/api/v1/signatures/?hex_signature=0x9aa643fd returns the following:

```
{
    "count": 0,
    "next": null,
    "previous": null,
    "results": []
}
```

Metamask is always trying to read the `text_signature` even when there is none.  https://github.com/MetaMask/metamask-extension/blob/204f39ef12822f1163c34d47226e9236e723c633/ui/helpers/utils/transactions.util.js#L43

The fix returns the result based on `count` in the response from 4byte. 

## Manual Testing Steps

Manual testing has been performed by using the lotsOfParams method of https://goerli.etherscan.io/address/0x0ef46122991b9c36f53ad08c162d1cbb9240dbfb#writeContract

Screenshot_20221219_004117

It returns the target console error without the fix. After the fix, the error is no more. 

For testing multiple times, please clear keyvaluepairs each time. Because if hex to text value is present in storage, it is not fetched from 4byte. Keyvaluepairs can be cleared in chrome's dev console of metamask in 
Application > Storage > IndexedDB > keyvaluepairs

### CODE REVIEW

**Review by FrederikBolding — APPROVED** [review]

**Comment by FrederikBolding** [comment]
For some reason this is not running CI 🤔

**Comment by EresDev** [comment]
> For some reason this is not running CI thinking

are you referring to `ci/circleci: all-tests-pass `?
maybe because it already passed in my branch https://github.com/EresDev/metamask-extension/tree/method-txt-sig and the CI config are the same. I am not sure though.

**Comment by seaona** [comment]
Thank you for your contribution @EresDev. The fix is working fine on my end. Trying to figure out what's happening with circle ci jobs.

**Comment by jpuri** [comment]
Hey @EresDev : there is weird issue with build. Can you plz try to create a PR for a different branch ?

**Comment by EresDev** [comment]
> Hey @EresDev : there is weird issue with build. Can you plz try to create a PR for a different branch ?

Ok, I will do this today.

**Pull request closed without merging**
