### PR TITLE
Version v11.13.0

### PR DESCRIPTION
**Pull request by benjisclowder**
RC v11.13.0

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by benjisclowder** [comment]
V11.13.0 Bug Report: https://github.com/MetaMask/MetaMask-planning/issues/2199

**Comment by benjisclowder** [comment]
[Manual test scenarios:](https://github.com/MetaMask/metamask-extension/tree/develop/test/scenarios)

Chrome

- [ ]  Onboarding - create a wallet
- [ ]  Onboarding - import a wallet
- [ ]  Keyring - connect hardware wallet
- [ ]  Keyring - reset a wallet
- [ ]  Transactions - send native token origin MM
- [ ]  Transactions - send native token origin dapp
- [ ]  Transactions - send ERC20 token origin MM
- [ ]  Transactions - send ERC20 token origin dapp
- [ ]  Transactions - send ERC721 token origin MM
- [ ]  Transactions - send ERC721 token origin dapp
- [ ]  Transactions - speed up transaction
- [ ]  Transactions - cancel transaction
- [ ]  Tokens - import ERC20 token origin MM
- [ ]  Tokens - import ERC20 token origin dapp
- [ ]  Tokens - import ERC721 token origin MM
- [ ]  Tokens - import ERC721 token origin dapp
- [ ]  Tokens - import ERC1155 token origin MM
- [ ]  Tokens - import ERC1155 token origin dapp
- [ ]  Tokens - approve ERC1155 token
- [ ]  Tokens - approve ERC20 token
- [ ]  Tokens - approve ERC721 token
- [ ]  Tokens - autodetect tokens
- [ ]  Tokens - autodetect NFTs
- [ ]  ENS - name resolution
- [ ]  Phishing - warning page
- [ ]  Network - add custom network manually
- [ ]  Network - add custom network from the list of popular networks
- [ ]  Network - add custom network from dApp
- [ ]  Network - update networks
- [ ]  Network - switching networks
- [ ]  Network - delete networks from the dropdown list
- [ ]  Network - delete networks in Settings
- [ ]  Backup - backup user data
- [ ]  Backup - restore user data
- [ ]  Metrics - send event metrics
- [ ]  Address-book - add a contact to the address book
- [ ]  Address-book - remove a contact from the address book
- [ ]  Address-book - update a contact in the address book
- [ ]  Gas fee - EIP-1559 gas
- [ ]  Gas fee - legacy gas
- [ ]  Sign - eth sign
- [ ]  Sign - personal sign
- [ ]  Sign - sign in with ethereum
- [ ]  Sign - sign typed with data
- [ ]  Sign - sign typed data v3 with hardware wallet
- [ ]  Sign - sign typed data v4 with hardware wallet
- [ ]  Permissions - connecting and disconnecting from a dapp
- [ ]  Swap - smart swap
- [ ]  Swap - swap eth
- [ ]  Incoming transactions - receive native token
- [ ]  Settings - about MetaMask
- [ ]  Settings - general
- [ ]  Settings - advanced

Firefox

- [ ] Onboarding - create a wallet
- [ ]  Onboarding - import a wallet
- [ ]  Keyring - connect hardware wallet
- [ ]  Keyring - reset a wallet
- [ ]  Transactions - send native token origin MM
- [ ]  Transactions - send native token origin dapp
- [ ]  Transactions - send ERC20 token origin MM
- [ ]  Transactions - send ERC20 token origin dapp
- [ ]  Transactions - send ERC721 token origin MM
- [ ]  Transactions - send ERC721 token origin dapp
- [ ]  Transactions - speed up transaction
- [ ]  Transactions - cancel transaction
- [ ]  Tokens - import ERC20 token origin MM
- [ ]  Tokens - import ERC20 token origin dapp
- [ ]  Tokens - import ERC721 token origin MM
- [ ]  Tokens - import ERC721 token origin dapp
- [ ]  Tokens - import ERC1155 token origin MM
- [ ]  Tokens - import ERC1155 token origin dapp
- [ ]  Tokens - approve ERC1155 token
- [ ]  Tokens - approve ERC20 token
- [ ]  Tokens - approve ERC721 token
- [ ]  Tokens - autodetect tokens
- [ ]  Tokens - autodetect NFTs
- [ ]  ENS - name resolution
- [ ]  Phishing - warning page
- [ ]  Network - add custom network manually
- [ ]  Network - add custom network from the list of popular networks
- [ ]  Network - add custom network from dApp
- [ ]  Network - update networks
- [ ]  Network - switching networks
- [ ]  Network - delete networks from the dropdown list
- [ ]  Network - delete networks in Settings
- [ ]  Backup - backup user data
- [ ]  Backup - restore user data
- [ ]  Metrics - send event metrics
- [ ]  Address-book - add a contact to the address book
- [ ]  Address-book - remove a contact from the address book
- [ ]  Address-book - update a contact in the address book
- [ ]  Gas fee - EIP-1559 gas
- [ ]  Gas fee - legacy gas
- [ ]  Sign - eth sign
- [ ]  Sign - personal sign
- [ ]  Sign - sign in with ethereum
- [ ]  Sign - sign typed with data
- [ ]  Sign - sign typed data v3 with hardware wallet
- [ ]  Sign - sign typed data v4 with hardware wallet
- [ ]  Permissions - connecting and disconnecting from a dapp
- [ ]  Swap - smart swap
- [ ]  Swap - swap eth
- [ ]  Incoming transactions - receive native token
- [ ]  Settings - about MetaMask
- [ ]  Settings - general
- [ ]  Settings - advanced

**Comment by chloeYue** [comment]
We need teams' approval on the 20th of March at the latest.

## Instructions for Team Review

1. **Review Changes**: Refer to the [Release Tracker for v11.13.0](https://docs.google.com/spreadsheets/d/1tsoodlAlyvEUpkkcNcbZ4PM9HuC9cEM80RZeoVv5OCQ/edit#gid=1048579647) to see all changes relevant to your team.
2. **Log Bugs**: If you find any issues, log them in the release tracker and attach them to [this bug report epic](https://github.com/MetaMask/MetaMask-planning/issues/2199).
3. **Approval**: After reviewing, indicate your team's approval by:
   - Marking the checkbox next to your team's name in this comment.
   - Optionally, leave a comment for additional confirmation.

Your thorough review ensures a smooth and successful release. If you have any questions please reach out to extension platform team or in the [#metamask-qa](https://consensys.slack.com/archives/C01U65ZUS2E) slack channel. Thank you for your collaboration!

 
- [ ] Snaps: @bowensanders / @FrederikBolding / @Montoya - There are 12 functional Snaps changes in v11.13.0. 
- [ ]  Confirmation UX: @seaona - There are 9 functional Confirmations UX changes in v11.13.0
- [ ]  Confirmation Systems: @sleepytanya - There are 10 Confirmation Systems changes in v11.13.0.
- [ ]  Accounts: @plasmacorral - There are 10 Accounts changes in v11.13.0.
- [ ]  Wallet UX: @darkwing / @NidhiKJha - There are 16 Wallet UX changes in v11.13.0.
- [ ]  Design/Systems: @georgewrmarshall - There are 2 Design/Systems changes in v11.13.0. 
- [ ]  Devex: @tmashuang / @vandan - There are 7 Devex change in v11.13.0.
- [ ]  Assets: @sahar-fehri / @alfeng6 - There are 10 Assets changes in v11.13.0
- [ ]  MMI: @zone-live / @shane-t - There are 5 MMI changes in v11.13.0.

**Comment by Bullcoiner** [comment]
Firefox v11.13.0 QA Testing

- [x] Onboarding - create a wallet
- [x]  Onboarding - import a wallet
- [x]  Keyring - connect hardware wallet
- [x]  Keyring - reset a wallet
- [x]  Transactions - send native token origin MM
- [x]  Transactions - send native token origin dapp
- [x]  Transactions - send ERC20 token origin MM
- [x]  Transactions - send ERC20 token origin dapp
- [x]  Transactions - send ERC721 token origin MM
- [x]  Transactions - send ERC721 token origin dapp
- [x]  Transactions - speed up transaction
- [x]  Transactions - cancel transaction
- [x]  Tokens - import ERC20 token origin MM
- [x]  Tokens - import ERC20 token origin dapp
- [x]  Tokens - import ERC721 token origin MM
- [x]  Tokens - import ERC721 token origin dapp
- [x]  Tokens - import ERC1155 token origin MM
- [x]  Tokens - import ERC1155 token origin dapp
- [x]  Tokens - approve ERC1155 token
- [x]  Tokens - approve ERC20 token
- [x]  Tokens - approve ERC721 token
- [x]  Tokens - autodetect tokens
- [x]  Tokens - autodetect NFTs
- [x]  ENS - name resolution
- [x]  Phishing - warning page
- [x]  Network - add custom network manually
- [x]  Network - add custom network from the list of popular networks
- [x]  Network - add custom network from dApp
- [x]  Network - update networks
- [x]  Network - switching networks
- [x]  Network - delete networks from the dropdown list
- [x]  Network - delete networks in Settings
- [x]  Backup - backup user data
- [x]  Backup - restore user data
- [x]  Metrics - send event metrics
- [x]  Address-book - add a contact to the address book
- [x]  Address-book - remove a contact from the address book
- [x]  Address-book - update a contact in the address book
- [x]  Gas fee - EIP-1559 gas
- [x]  Gas fee - legacy gas
- [x]  Sign - eth sign
- [x]  Sign - personal sign
- [x]  Sign - sign in with ethereum
- [x]  Sign - sign typed with data
- [x]  Sign - sign typed data v3 with hardware wallet
- [x]  Sign - sign typed data v4 with hardware wallet
- [x]  Permissions - connecting and disconnecting from a dapp
- [x]  Swap - smart swap
- [x]  Swap - swap eth
- [x]  Incoming transactions - receive native token
- [x]  Settings - about MetaMask
- [x]  Settings - general
- [x]  Settings - advanced

**Comment by plasmacorral** [comment]
🟢 Approval from Accounts team

**Comment by sleepytanya** [comment]
🟢 Approval from the Confirmations System team.

**Comment by seaona** [comment]
:green_circle:  QA Sign Off from Confirmations UX team.

Note: there are 2 issues related to ppom which are currently under investigation. We do not consider them blockers and they are already in prod, but they are top priority, since they leave the ppom validation forever loading without a recovery path.

- https://github.com/MetaMask/metamask-extension/issues/23174
- https://github.com/MetaMask/metamask-extension/issues/23295

**Comment by danjm** [comment]
@socket-security ignore-all

The author mentioned is a long time contributor to eslint projects, and the shell access mentioned is needed for a dev dependency

**Comment by danjm** [comment]
@SocketSecurity ignore-all

**Review by danjm — APPROVED** [review]

**Pull request merged**
