### PR TITLE
adds READMEs to folders, re #3427

### PR DESCRIPTION
**Pull request by ghost**
### Scenario

A developer (me in this case) tries to get a source-code overview right from within the source code.

The READMEs should provide basic general info. Can be viewed nicely during code-browsing from github ui or IDE.

(note that I have most possibly misunderstood something)

### CODE REVIEW

**Comment by kumavis** [comment]
I generally like this, but I don't want to push the "other documents" off of the primary readme. If there's too much there, lets move other content off and keep this as an index.

**Comment by lazaridiscom** [comment]
(@kumavis , I revert the ./README change, although its a quite important one. But will come back to this to a later point. Note: me messing up the "squash" as usual, so you'll have possibly some noise. If it gets to much, just close this PR and I'll open a new one)

**Comment by lazaridiscom** [comment]
@danfinlay

**Comment by lazaridiscom** [comment]
@kumavis , can we get this in? (having multiple branches makes me always nervous...)

**Review by danfinlay — APPROVED** [review]
This looks good, addressed concerns about the main README.

**Review by kumavis — APPROVED** [review]

**Pull request merged**
