### PR TITLE
Version v11.5.0

### PR DESCRIPTION
**Pull request by danjm**

### CODE REVIEW

**Comment by pedronfigueiredo** [comment]
@SocketSecurity ignore-all

The "New Author" issues are related to packages controlled by us and to author changes to bots controlled by us.

Storybook is a dev dependency that is not executed in production, so network access isn't a concern.

**Comment by benjisclowder** [comment]
Release tracker for change validation on 11.5.0:
https://docs.google.com/spreadsheets/d/1tsoodlAlyvEUpkkcNcbZ4PM9HuC9cEM80RZeoVv5OCQ/edit#gid=815647856

- [ ] MMI: @zone-live / @shane-t - Two MMI changes in v11.5.0. 
- [ ] Snaps: @bowensanders / @FrederikBolding / @Montoya - We would like to get your approval on the v11.5.0 release by this Thursday for Snaps changes (6).
- [ ] Design/Systems: @georgewrmarshall - Three changes in v.11.5.0.
- [ ] Confirmation UX: @seaona - We would like to get your approval on the v11.5.0 release by this Thursday for Confirmations UX changes (7).
- [ ] Confirmation Systems: @sleepytanya - We would like to get your approval on the v11.5.0 release by this Thursday for Confirmation Systems changes (2).

**Comment by sleepytanya** [comment]
Two PRs from Confirmations System:
1. [Decouple MetaMetricsController from TxController #21330](https://github.com/MetaMask/metamask-extension/pull/21330)  - no functional changes.
2. [Adopt new version of `@metamask/signature-controller` to add signature operation logs (#21207)](https://github.com/MetaMask/metamask-extension/pull/21207) - no functional change in signatures. All signature requests (approved and rejected) logged in `MetaMask State Logs.json`.
State log file:
[sign.json](https://github.com/MetaMask/metamask-extension/files/13300286/sign.json)
[State log explorer is here](https://metamask.github.io/state-log-explorer/)
Screenshot:
Screenshot 2023-11-08 at 1 51 48 PM

**Comment by seaona** [comment]
:green_circle:  **Confirmations UX**: QA Sign Off

**Pull request merged**
