### PR TITLE
fix: handle trailing slashes in block explorer URLs

### PR DESCRIPTION
**Pull request by bguiz**
## What

- modify `ui/app/helpers/utils/transactions.util.js` and
  `ui/lib/account-link.js` to strip trailing slashes
  if they are present.
- added relevant tests not just for the new scenario,
  but also the general scenarios for these functions,
  as there previously was no test coverage for these
  two functions.

## Why

- Current behaviour, when user enters a block explorer URL
  when configuring a custom RPC, and that block explorer URL
  contains a trailing `/`.
  - e.g. `https://block.explorer/`
  - this results in a double-slash (`//`) in the transaction
    and account URLs generated by MetaMask.
  - e.g. `https://block.explorer/tx/0xabcd...`,
    `https://block.explorer/account/0xabcd...`
  - This needs to be handled using a router redirect
    on the server of the block explorer,
    and this changes would avoid that requirement.

### CODE REVIEW

**Review by rekmarks — CHANGES_REQUESTED** [review]
Neat work, thanks!

Please resolve the lint failures and push again. `yarn lint:fix` or `yarn lint:changed:fix` (quicker, if you do a soft reset), should do the trick.

**Comment by bguiz** [comment]
> Neat work, thanks!
> 
> Please resolve the lint failures and push again. `yarn lint:fix` or `yarn lint:changed:fix` (quicker, if you do a soft reset), should do the trick.

@rekmarks done, looks like the various CI lint tasks have all passed now. Earlier on `ci/circleci: test-e2e-firefox` appears to have failed as well, but a forced-push without any changes appears to have resolved it, so perhaps that test is fragile/ non-deterministic.

https://circleci.com/gh/MetaMask/metamask-extension/164993

```
[2020-05-14 02:31:56.620][e2e]   1) MetaMask
[2020-05-14 02:31:56.620][e2e]        Going through the first time flow
[2020-05-14 02:31:56.620][e2e]          clicks the continue button on the welcome screen:
[2020-05-14 02:31:56.620][e2e]      ElementClickInterceptedError: Element <button class="button btn-primary first-time-flow__button"> is not clickable at point (154,509) because another element <div class="loading-overlay"> obscures it
```

**Comment by whymarrh** [comment]
Yeah, our e2e tests aren’t especially reliable, currently 🙃

**Comment by bguiz** [comment]
> Yeah, our e2e tests aren’t especially reliable, currently

@whymarrh yeah, well one more failed test-e2e-Firefox, same error, but I manually triggered the build by doing another forced push. All checks are passing now!

**Review by rekmarks — APPROVED** [review]
LGTM!

@bguiz, this is a lovely example of an external PR. I really appreciate the care you put into it.

**Comment by bguiz** [comment]
> LGTM!
> 
> @bguiz, this is a lovely example of an external PR. I really appreciate the care you put into it.

You're welcome @rekmarks - and thanks for the comment!

**Pull request merged**
