### PR TITLE
Specify that Ancient8 is a multilayer network

### PR DESCRIPTION
**Pull request by 0xtrou**
## **Description**

Ancient8 is also based on the OP stack, so follows the same gas rules as Optimism and Base.
This closely follows the form of https://github.com/MetaMask/metamask-extension/pull/20097.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/pull/20097

## **Manual testing steps**

1. Open the extension

2. Add the Ancient8 network using the following information

Chain name: Ancient8
Chain Id: 888888888
Chain RPC: https://rpc.ancient8.gg

3. Send some transactions

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [x] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by emilianobonassi** [comment]
for context, this PR is for adding support to show L1 fees for ancient8 network based on OP Stack deployed with Conduit

similar stuff asked for Zora

https://github.com/MetaMask/metamask-extension/pull/20501

is this the correct process to support a multilayer network on Metamask? @brad-decker 

thanks!

**Comment by bschorchit** [comment]
Hi @0xtrou, thank you for your PR! The team will work through it soon (expect ~2 weeks).

**Comment by 0xtrou** [comment]
Thank you @bschorchit

**Comment by cjtoolseram** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by 0xtrou** [comment]
hey how is thing going @bschorchit ser

**Comment by bschorchit** [comment]
Hey, the team will be wrapping up a work this week that is currently blocking moving on to this. Sorry for the delay, but we're planning to get to this soon.

**Comment by 0xtrou** [comment]
Hi pals, I know you guys are super busy, but any chances I can know if there were any ETA for this issue?

Thanks very mucu @bschorchit

**Comment by emilianobonassi** [comment]
any update on this @bschorchit ?

**Pull request closed without merging**
