### PR TITLE
Use getUILanguage over getAcceptLanguages

### LINKED ISSUE #7972: Extension incorrectly detects locale? (French instead of English)
**Describe the bug**

After installing the Chrome extension, the extension is in French by default without any way to change the language. As far as I know, my computer and browser languages are both English and I'm not currently located in a French speaking country. Why does it chose to use the French translation?

**To Reproduce (REQUIRED)**

Install extension on Chrome.

**Expected behavior**

Extension should be in English.

**Screenshots**

Screen Shot 2020-02-02 at 8 48 15 AM

### PR DESCRIPTION
**Pull request by tmashuang**
Fixes https://github.com/MetaMask/metamask-extension/issues/7972

Docs
https://developer.chrome.com/extensions/i18n#method-getUILanguage
https://developer.chrome.com/extensions/i18n#method-getAcceptLanguages

Currently we use the first index of `getAcceptLanguages()` result that users can set in the browser's langugage setting. Users who have multiple lanugages set for translation purposes might not have the default at the top of their preferences.

Reproduction steps:
- Add Spanish and French to list of browser langugages (or something similiar)
- Set one of to above langs to default and move to bottom, set other to top of preference language list
- Add extension/addon to list, should open with welcome screen in the default lang.

### CODE REVIEW

**Comment by Gudahtt** [comment]
I considered doing this before, as this would probably be what users want most of the time. However I think the way it's currently implemented is more correct.

The ` accept-languages` configured in the browser should reflect the user's preferences. The same setting is sent to all websites the user visits (via the [`Accept-Language` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language)), so any user that is surprised by our default locale would get the same surprising result on any other website that correctly respects that header and supports the locale. For example, in #7972, if the user does have French set first in the list of preferences, then the rest of the internet should also be in French (e.g. `wikipedia.org`).

I'm not sure what we should choose - respect the user's preferences, or ignore them because of how often we see them misconfigured 🤔

**Comment by tmashuang** [comment]
I agree with the current implementation as well. This really only effects users that have manually moved the default language away from the top. Changing the default displayed language gets it moved to the top of the list after browser relaunch. So I am happy to close this and the issue along with it.

**Comment by Gudahtt** [comment]
Maybe the reason this happens and seems to surprise users is that their first choice is skipped, because we don't have the locale. The same might be true of the UI locale as well.

For example, lots of people might have their browser set to an English locale other than `en-US` (e.g. mine is set to `en-CA`). It's recommended that the "generic" language be specified in addition to any variant, but I'm not sure that browsers enforce that. Some web servers will implicitly add these generic language options if they're missing, but usually they'll be added to the _end_ of the list, meaning they might not help in this case.

**Comment by gzigg** [comment]
OMG first time user and the language is not MY language, and no option to change it on startup screens.  RIGHT OFF THE GATE ZERO CONFIDENCE - and the fact this issue has been around since at least 2018 and developers STILL DONT FIX IT IS UNREAL.   Moving to another wallet/exchange, thanks for trying.

**Pull request closed without merging**
