### PR TITLE
Sign typed data

### PR DESCRIPTION
**Pull request by danfinlay**
Builds on #2223 but adds some fixes/improvements that I wanted:
- Better input validations
- Fixed dependency versions
- Bumps changelog

Added an easy way to confirm this works on my [signature examples](https://danfinlay.github.io/js-eth-personal-sign-examples/) page (click "sign typed data").

### CODE REVIEW

**Comment by ukstv** [comment]
@danfinlay Hold on, please, I add validation based on eth-sig-util.

**Comment by danfinlay** [comment]
Ok. If you want, you can just push that update onto your own PR (#223), and we can treat it as the master one.

**Comment by ukstv** [comment]
Ok.

**Comment by danfinlay** [comment]
Closing in favor of #2223

**Pull request closed without merging**
