### PR TITLE
I#5956 fix2 dont overwrite existing rpc settings

### LINKED ISSUE #5956: Custom RPC incorrectly inserts chainId(4-rinkeby) eth_signTypedData_v3, signing tx affected.
**Describe the bug**

**To Reproduce**
1. Set Custom RPC URL to `https://api.myetherwallet.com/eth `
2. Add some extra custom RPC such as `https://api.myetherwallet.com/rop`
3. Go to https://rstormsf.github.io/js-eth-personal-sign-examples/
4. Click Connect
5. Click sign typed data v3
6. See error
```
AssertionError: Provided chainId (1) must match the active chainId (4)
```

**Expected behavior**
Custom RPC must not use hardcoded values

**Browser details (please complete the following information):**
 - OS: [OSX]
 - Browser [chrome]
 - MetaMask Version [5.2.2]

**Additional context**

I have created PR to remove hardcoded chainId
https://github.com/danfinlay/js-eth-personal-sign-examples/pull/7

image

I also wasn't able to send any transactions from custom RPC URLs, and when I click on Tx Hash, it redirects me to rinkeby.etherscan.io 
I believe it's ignoring custom rpcs and reading from last network id from dropdown which is rinkeby

### PR DESCRIPTION
**Pull request by frankiebee**
fixes #5956

### CODE REVIEW

**Comment by bdresser** [comment]
@frankiebee does this also fix https://github.com/MetaMask/metamask-extension/issues/5934

**Comment by danfinlay** [comment]
I don't think that _has_ to block this, considering this fixes a pretty big issue, but I agree, it would be better if we never broke any behavior in the first place, and don't mind waiting an extra day or two for that. What do you think, @frankiebee?

**Comment by frankiebee** [comment]
yeah i can get that in

**Comment by rstormsf** [comment]
Thanks everyone who is working on it. I highly appreciate it.

**Review by danjm — APPROVED** [review]
Reviewed code and QA'd. Looks good. Approved.

**Pull request merged**
