### PR TITLE
Add support for fiat on-ramp via Transfi

### PR DESCRIPTION
**Pull request by Jithendra-transfi**
## Explanation
We are adding a new fiat on-ramp option via TransFi. TransFi offers easy crypto on-ramps supported in 140+ countries with Credit, Debit card, Bank transfer and local payment methods.

New feature added is supported in asian countries like Singapore, Thailand etc and mobile wallet payment methods like FPX, VietQR, GrabPay, DuitNow etc...,

## Feature request and PR from MetaMask community:
https://community.metamask.io/t/other-options-for-on-ramp-solution/20086/18

## Screenshots/Screencaps

Screenshot 2022-12-26 at 4 04 30 PM

## Manual Testing Steps

- Open the MetaMask extension
- Click on Buy on the main page
- Click on Continue to TransFi
- Click on Buy Now on the TransFi Checkout page
- SignIn using email account
- ETH wallet address is pre-populated
- Select the payment method
- Complete the transaction 

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [x] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Comment by Jithendra-transfi** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Jithendra-transfi** [comment]
@kumavis @hmalik88 can you please review

**Comment by srameshr** [comment]
@brad-decker Could you please take a look at this?

**Comment by Jithendra-transfi** [comment]
@kumavis @hmalik88 @brad-decker could you please look at this!!!!!

**Comment by Jithendra-transfi** [comment]
@kumavis can you please review this

**Comment by Jithendra-transfi** [comment]
@kumavis @hmalik88 @brad-decker please review this

**Comment by pedronfigueiredo** [comment]
Hi @srameshr @Jithendra-transfi, thanks for your contribution.

Unfortunately, we cannot approve it at this stage and will close the pull request. For more information, please get in touch with our fiat on-ramp team through our contact form: https://consensys.net/contact/

**Pull request closed without merging**
