### PR TITLE
Vulnerabilities down from 19 to 7

### PR DESCRIPTION
**Pull request by brunobar79**
Ran `npm audit fix` and `npm audit fix --force`

### CODE REVIEW

**Review by whymarrh — DISMISSED** [review]
> Ran `npm audit fix` and `npm audit fix --force`

It looks like we're unboxing truffle here, is that intentional?

**Comment by brunobar79** [comment]
Drizzle tests are failing because of this issue: https://github.com/truffle-box/drizzle-box/issues/59

**Comment by whymarrh** [comment]
@brunobar79 the Drizzle job is passing on develop if you want to try rebasing this PR

**Comment by brunobar79** [comment]
@whymarrh  Test are finally passing  🎉

**Review by whymarrh — APPROVED** [review]

**Pull request merged**
