### PR TITLE
Link to ESDB in local phishing.html

### PR DESCRIPTION
**Pull request by blurpesec**
Adds Etherscamdb link for detected domains.

Fixes: #4774 
Prepares for:
-  [MetaMask/eth-phishing-detect#2063](https://github.com/MetaMask/eth-phishing-detect/issues/2063)
- #4151 

new phishing page

### CODE REVIEW

**Comment by whymarrh** [comment]
@hahnmichaelf thanks! (Also, don't mind the test-e2e-beta-firefox failure, we're working to make that less flaky.)

**Review by whymarrh — COMMENTED** [review]
This looks good to me if @tmashuang wants to give it a quick QA pass

**Review by tmashuang — APPROVED** [review]

**Comment by tmashuang** [comment]
Waiting to merge after new provider is fleshed out in develop.

**Review by whymarrh — APPROVED** [review]

**Comment by whymarrh** [comment]
@tmashuang think we could merge this into develop now?

**Pull request merged**
