### PR TITLE
feat: brand evo design system

### LINKED ISSUE #655: [EXT] Test Design Token Updates in Pre-Release Branch for Extension
### Description
The purpose of this ticket is to ensure that the recent updates to the design tokens, as part of our brand evolution, are correctly implemented and functioning as expected in the portfolio's pre-release branch. This involves a comprehensive testing phase to identify any discrepancies, visual or functional, that may arise from the new design token updates.

### Technical Details
- The updates are located in the `feature/brand-evolution-design-tokens` branch.
- Testing should cover all major components affected by design tokens, including typography, color schemes, button styles, and layout spacings.
- Use both automated and manual testing strategies to cover a wide range of scenarios.
- Ensure compatibility across all supported browsers and devices.
- Any found issues should be documented with screenshots and detailed descriptions.

### Acceptance Criteria
1. All major components (e.g., headers, footers, buttons, input fields) reflect the updated design tokens correctly.
2. The application maintains its responsiveness and functionality across different screen sizes and devices.
3. No visual regressions are introduced by the design token updates.
4. The application is tested across all supported browsers (Chrome, Firefox, Safari, Edge) with no compatibility issues.
5. All discovered issues are documented and reported in the GitHub repository with appropriate labels.
6. Pair with Hiro to walk through designs together to determine acceptance from design

### PR DESCRIPTION
**Pull request by garrettbear**
## **Description**

The purpose of this ticket is to ensure that the recent updates to the design tokens, as part of our brand evolution, are correctly implemented and functioning as expected in the portfolio's pre-release branch. This involves a comprehensive testing phase to identify any discrepancies, visual or functional, that may arise from the new design token updates.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/25268?quickstart=1)

## **Related issues**

Fixes: [#655](https://github.com/MetaMask/design-tokens/issues/655)

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by georgewrmarshall** [comment]
There are a couple instances that use the JS tokens, so they haven't been updated in this branch
Screenshot 2024-06-13 at 3 06 30 PM

https://github.com/MetaMask/metamask-extension/blob/0c02dd51b767ffc1a745d962fdf7ee6f204d8330/ui/components/ui/toggle-button/toggle-button.component.js#L42-L43

**Review by georgewrmarshall — COMMENTED** [review]
Were you able to get the CSS-in-JS tokens for the toggle button working?

https://github.com/MetaMask/metamask-extension/blob/3706d3cc6037050d85e2a7099030d34df8c0634e/ui/components/ui/toggle-button/toggle-button.component.js#L5

Screenshot 2024-07-17 at 2 20 31 PM

**Comment by garrettbear** [comment]
> Were you able to get the CSS-in-JS tokens for the toggle button working?
> 
> https://github.com/MetaMask/metamask-extension/blob/3706d3cc6037050d85e2a7099030d34df8c0634e/ui/components/ui/toggle-button/toggle-button.component.js#L5
> 
> Screenshot 2024-07-17 at 2 20 31 PM

yes 
Screenshot 2024-06-13 at 4 15 53 PM

**Comment by garrettbear** [comment]
Created a [dummy package](https://www.npmjs.com/package/design-tokens-clone) to test

image

**Pull request closed without merging**
