### PR TITLE
Remove my wallet account 10342

### LINKED ISSUE #10342: Remove "My Wallet Account" section in Settings > Contacts
**Description**
Remove "My Wallet Account" section in Settings > Contacts

As a user, I don't want to see a list of my accounts under my Contact settings. I believe this is a result of the Settings > [Contact page designs](https://github.com/MetaMask/metamask-extension/issues/7069) not being fully implemented.

For now that section should be removed. 

**Steps to replicate**
1. Go to 'Settings'
2. Click on 'Contact'

### PR DESCRIPTION
**Pull request by rgordon95**
Fixes: #10342 

Explanation:  Removed the code in accordance with the instructions in the ticket

Manual testing steps:  
  - Go to 'Settings'
  -  Click on 'Contact'
  - See the section is removed from the ui 
  - see the locales and related display function are also removed

### CODE REVIEW

**Comment by rgordon95** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by Gudahtt — CHANGES_REQUESTED** [review]
Thanks for the contribution! This is a good start, but there is more dead code here to delete.

Now that you've deleted the `history.push(CONTACT_MY_ACCOUNTS_ROUTE)` line, that route is now unreachable. The same goes for `CONTACT_MY_ACCOUNTS_EDIT_ROUTE` and `CONTACT_MY_ACCOUNTS_VIEW_ROUTE`, which are only accessible from that page. The `my-accounts` component directory can be deleted entirely. The logic in `edit-contact` and `add-contact` can be simplified to no longer account for whether you're on the `MyAccounts` page.

**Comment by rgordon95** [comment]
Will ping you when I'm finished with the changes and conflicts, should be this weekend.

**Comment by Gudahtt** [comment]
Sure, no rush! Please take whatever time you need, and feel free to ask for one of us to take this over if you'd like to stop working on it, or if you'd like any help from us.

Lots of conflicts but they're probably all due to us updating our eslint rules to turn semicolons on (sorry about that :sweat_smile: ).

I'm going to put this back into draft for now until you've updated it. Feel free to move it back out of draft when it's ready again.

**Comment by BboyAkers** [comment]
Is this still in the works? 😃

**Pull request closed without merging**
