### PR TITLE
Updating deprecated Etherscam link 

### PR DESCRIPTION
**Pull request by hensha256**
## Description

When visiting a potential phishing scam, Metamask gives a warning page to users. This warning page includes a link to `https://etherscamdb.info/domain/${suspect.hostname}`.

However when you visit this site, e.g. https://etherscamdb.info/domain/sai2dai.com, the site states that it is deprecated, and that you should instead visit https://cryptoscamdb.org/.

Screenshot 2019-11-18 at 3 40 47 PM

This PR updates the URL to be the new site.

### CODE REVIEW

**Comment by whymarrh** [comment]
Does this link to the specific entry? I think we'll need to use the API to be able to link users directly to the entry they're looking for, else this isn't quite a 1:1 link swap.

**Comment by alicevhenshaw** [comment]
So the difference with the new site is that it seemingly doesn't have pages for domains that haven't yet been listed. So with etherscam, when you hit sai2dai.com and it doesnt have an entry for it, it still renders a page to say that it hasn't yet been classified:
https://etherscamdb.info/domain/sai2dai.com

However with cryptoscamdb, if the site hasnt yet been classified then it just doesn't exist on the site. That was the reason I just inserted a link to the search box.

**Comment by whymarrh** [comment]
@alicevhenshaw apologies for the slow response. I agree that we need to move to this service, I think it's worth exploring getting their site to support some sort of linking, similar to how the old site worked.

**Comment by whymarrh** [comment]
Or, maybe instead, if we can, using the API to link directly to the entry when it exists.

**Review by whymarrh — APPROVED** [review]
@alicevhenshaw I've updated the working a touch (f1c1bbf) to make it clear that the user will need to search when on the site. Thanks again for bringing this up.

**Pull request merged**
