### PR TITLE
Fixed firefox Snaps + add initial end-to-end tests

### PR DESCRIPTION
**Pull request by shanejonas**
This fixes snaps in firefox. Also adds e2e tests to test against https://github.com/MetaMask/test-snaps/

### CODE REVIEW

**Review by darkwing — DISMISSED** [review]

**Review by rekmarks — APPROVED** [review]
This is a great start to our Flask tests. We may want to consider running more regular tests, but we can deal with that later.

LGTM!

**Review by rekmarks — CHANGES_REQUESTED** [review]
I have to retract my prior approval because the snaps e2e tests are too flaky on Chrome. We can't add tests that need to be consistently re-run.

Once the snap tests pass consistently on Chrome, this PR can be merged.

On a related note, I noticed that the failed test doesn't appear to produce any artifacts. We should ensure that artifact generation works for the snaps tests as well, although that can be done in a follow-up if need be.

**Comment by danjm** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by danjm — APPROVED** [review]

**Review by rekmarks — APPROVED** [review]
LGTM!

**Comment by Gudahtt** [comment]
This branch conflicted with #13895 so now this new e2e test is broken on develop. Working on a fix.

**Pull request merged**
