### PR TITLE
Add Kovan Test Net

### PR DESCRIPTION
**Pull request by 2-am-zzz**
Ain't they a good-looking one. Adds Kovan support. Adds Kovan etherscan links. Adds a beautiful hollow diamond.

screenshot from 2017-03-22 16-05-39

### CODE REVIEW

**Comment by Zanibas** [comment]
Fixes #1243

**Comment by flyswatter** [comment]
Does this fix #1238?

**Comment by Zanibas** [comment]
@flyswatter I assume so, Aaron said txs were working:
```
kovan seems to be working fine for me on the published version (basic txs + data txs)
https://github.com/MetaMask/metamask-plugin/issues/1238#issuecomment-288504200
```

**Review by danfinlay — APPROVED** [review]
Well alright then!

**Comment by flyswatter** [comment]
loool 4th merge master merge on this PR.

**Pull request merged**
