### PR TITLE
lavamoat - @lavamoat/allow-scripts v2

### PR DESCRIPTION
**Pull request by kumavis**
Updates `@lavamoat/allow-scripts` to use the new secure `'a'a` package naming convention

The `'a'a` package naming convention uses the "shortest logical dependency path" (`a>b>c`) to name a package, instead of using the package's filesystem location based name (`c`). Using standard node resolution logic helps avoid bugs associated with edgecase package locations and security issues arising from flattened package path based names.

### CODE REVIEW

**Review by brad-decker — APPROVED** [review]
very nice

**Comment by mcmire** [comment]
@kumavis For the uninformed, what is the significance of the changes to `allow-scripts` here? I see that it solves some problems mentioned in Slack — what are those problems and how do they solve them?

**Review by rekmarks — APPROVED** [review]
LGTM, but we should answer @mcmire's question in the PR description.

**Comment by kumavis** [comment]
@mcmire added description. ping me with more questions

**Pull request merged**
