### PR TITLE
Changing cancel button labels in send screen when in editing stage

### LINKED ISSUE #11929: Duplicate "Cancel" buttons in Metamask Extension Edit Screen Bring you Forward to Confirm Screen
**Describe the bug**
The two "cancel" buttons on Metamask extension "edit" screen do not cancel the transaction, they return you to the confirmation screen

**Steps to reproduce**

1. Go to Extension and enter a destination address and amount of funds to send
2. Click "next"
3. Click "edit"
4. Metamask returns to confirmation screen when clicking either "cancel" button

**Expected behavior**

Expect either "cancel" button to return you to Metamask home.  Recommend renaming one to "cancel edit" that is on the top right, and renaming bottom left button to "reject" to align it with the confirmation screen.

**Browser details (please complete the following information):**

 - OS: OS Big Sur 11.2.3
 - Browser: Chrome Version 92.0.4515.159 (Official Build) (arm64)
 - MetaMask Version: 10.0.2

### PR DESCRIPTION
**Pull request by jpuri**
Fixes: #11929

Explanation:  White sending in metamask when editing transaction cancel buttons take user back to confirmation screen and not metamask home. This is confusing for users. As recommended in reported issue the PR change the label of edit screen when in edit stage. And Reject button at bottom ot edit send screen should take user to home page.

Manual testing steps:  
- go to send and enter a destination address - label on top right should be "Cancel" and bottom-left should also be "Cancel"
- click next
- click edit - label on top right should be "Cancel Edit" and bottom-left should be "Reject"
- Clicking top right "Cancel Edit" will take user back on previous send screen
- Clicking on bottom left "Reject" will take user back to home page

Thus you can see that label in Draft stage are still "Cancel" but they are updated in editing stage.

Send screen when drafting transaction:
Screenshot 2021-09-10 at 10 45 07 AM

Send screen when editing transaction:
Screenshot 2021-09-10 at 10 43 58 AM

### CODE REVIEW

**Review by danjm — CHANGES_REQUESTED** [review]
The code changes here look good, but I realized that another specification should have been provided in the github ticket.

For the button in `send-footer.component.js`, the `onCancel` method should be modified so that, when in the edit stage, it cancels the transaction and takes the user to the home screen.

To do this, a `cancelTx` action will have to be dispatched (you can see this defined in actions.js) and `history.push` should just be to the `DEFAULT_ROUTE` that can be imported from `ui/helpers/constants/routes.js`

So then, when editing a transaction, if the user clicks the button in the top right, they go back to the confirm screen, and if they click the bottom in the bottom left (in the footer), the transaction is cancelled and they go to the home screen

**Comment by brad-decker** [comment]
Sorry I reviewed this yesterday and came to the same conclusion that @danjm posted above, but then forgot to submit my feedback.

**Review by darkwing — APPROVED** [review]
Wow, this is great @jpuri !

**Review by danjm — APPROVED** [review]
Nice work!

**Pull request merged**
