### PR TITLE
Deps - Npm6 fresh package-lock

### PR DESCRIPTION
**Pull request by kumavis**
checking to see what happens when we mass-modify our package with the new `npm@6`'s `npm audit fix` tool

### CODE REVIEW

**Comment by kumavis** [comment]
Hey look at that - all tests passing
theres some aggressive and unmonitored changes in here and so we should sit and have a think about this

**Comment by kumavis** [comment]
would also mean all devs should move to `npm@6` i think

**Comment by whymarrh** [comment]
Thanks for this. I agree that where this may update packages that have been pinned/locked for a while we'll need to double-check that in-range versions are safe.

> would also mean all devs should move to npm@6 i think

I think devs should still be able to use a late `@5` version since a lot of the `package-lock.json` churn may have just been old npm versions incorrectly switching between sha1 and sha512 and reordering the entries.

**Comment by kumavis** [comment]
This was merged here #4675

**Pull request closed without merging**
