### PR TITLE
Update font family globally

### PR DESCRIPTION
**Pull request by brad-decker**
1. Adds a * { } style in base-styles to set the font-family globally.
2. Couldn't figure out why the reset.scss was taking precedence over the above (probable: specificity of the * selector), so I replaced `font: inherit` with the individual properties except for `font-family` in reset.scss
3. removed all `font-family:` styles set elsewhere.

Depends on:
1. ~#9018~ 
2. ~#9071~ 
3. ~#9072~ 

### Screenshot Samples

This doesn't represent all of the changes, given the wide target for this PR, but it should give an idea of the scope and quality of the changes. If you'd like to do a full audit, see the latest comment from @metamaskbot to get the build and install it locally. Or checkout this branch and build for dev mode. 

#### Lock screen
<details>
<summary>Before</summary>

</details>

<details>
<summary>After</summary>

</details>

#### Home

<details>
<summary>Before</summary>

</details>

<details>
<summary>After</summary>

</details>

#### Activity List

<details>
<summary>Before</summary>

</details>

<details>
<summary>After</summary>

</details>

#### Asset list

<details>
<summary>Before</summary>

</details>

<details>
<summary>After</summary>

</details>

#### Main Menu
<details>
<summary>Before</summary>

</details>

<details>
<summary>After</summary>

</details>

#### Create Account
<details>
<summary>Before</summary>

</details>

<details>
<summary>After</summary>

</details>

#### Settings Page
<details>
<summary>Before</summary>

</details>

<details>
<summary>After</summary>

</details>

#### Connected Sites modal
<details>
<summary>Before</summary>

</details>

<details>
<summary>After</summary>

</details>

### CODE REVIEW

**Comment by brad-decker** [comment]
[Update fonts](https://trello.com/c/giqTMDWN/59-update-fonts)

**Comment by rachelcope** [comment]
This looks fantastic, yay! The only one that does not look updated to me is the Create account (after), but it is likely just a wrong screenshot? Very excited about this update 🚀

**Review by rachelcope — APPROVED** [review]

**Review by danjm — APPROVED** [review]
Review code and tested in browser. LGTM

**Review by rekmarks — APPROVED** [review]
@danjm approval-by-proxy.

**Pull request merged**
