### PR TITLE
Version v11.10.0 

### PR DESCRIPTION
**Pull request by chloeYue**
## **Description**

RC v11.10.0

### CODE REVIEW

**Comment by chloeYue** [comment]
v11.10.0 bug report: https://github.com/MetaMask/MetaMask-planning/issues/1970

**Comment by benjisclowder** [comment]
Manual test scenarios:

Chrome

- [ ] Onboarding - create a wallet
- [ ]  Onboarding - import a wallet
- [ ]  Keyring - connect hardware wallet
- [ ]  Keyring - reset a wallet
- [ ]  Transactions - send native token origin MM
- [ ]  Transactions - send native token origin dapp
- [ ]  Transactions - send ERC20 token origin MM
- [ ]  Transactions - send ERC20 token origin dapp
- [ ]  Transactions - send ERC721 token origin MM
- [ ]  Transactions - send ERC721 token origin dapp
- [ ]  Transactions - speed up transaction
- [ ]  Transactions - cancel transaction
- [ ]  Tokens - import ERC20 token origin MM
- [ ]  Tokens - import ERC20 token origin dapp
- [ ]  Tokens - import ERC721 token origin MM
- [ ]  Tokens - import ERC721 token origin dapp
- [ ]  Tokens - import ERC1155 token origin MM
- [ ]  Tokens - import ERC1155 token origin dapp
- [ ]  Tokens - approve ERC1155 token
- [ ]  Tokens - approve ERC20 token
- [ ]  Tokens - approve ERC721 token
- [ ]  Tokens - autodetect tokens
- [ ]  Tokens - autodetect NFTs
- [ ]  ENS - name resolution
- [ ]  Phishing - warning page
- [ ]  Network - add custom network manually
- [ ]  Network - add custom network from the list of popular networks
- [ ]  Network - add custom network from dApp
- [ ]  Network - update networks
- [ ]  Network - switching networks
- [ ]  Network - delete networks from the dropdown list
- [ ]  Network - delete networks in Settings
- [ ]  Backup - backup user data
- [ ]  Backup - restore user data
- [ ]  Metrics - send event metrics
- [ ]  Address-book - add a contact to the address book
- [ ]  Address-book - remove a contact from the address book
- [ ]  Address-book - update a contact in the address book
- [ ]  Gas fee - EIP-1559 gas
- [ ]  Gas fee - legacy gas
- [ ]  Sign - eth sign
- [ ]  Sign - personal sign
- [ ]  Sign - sign in with ethereum
- [ ]  Sign - sign typed with data
- [ ]  Permissions - connecting and disconnecting from a dapp
- [ ]  Swap - smart swap
- [ ]  Swap - swap eth
- [ ]  Incoming transactions - receive native token

Firefox

- [ ] Onboarding - create a wallet
- [ ]  Onboarding - import a wallet
- [ ]  Keyring - connect hardware wallet
- [ ]  Keyring - reset a wallet
- [ ]  Transactions - send native token origin MM
- [ ]  Transactions - send native token origin dapp
- [ ]  Transactions - send ERC20 token origin MM
- [ ]  Transactions - send ERC20 token origin dapp
- [ ]  Transactions - send ERC721 token origin MM
- [ ]  Transactions - send ERC721 token origin dapp
- [ ]  Transactions - speed up transaction
- [ ]  Transactions - cancel transaction
- [ ]  Tokens - import ERC20 token origin MM
- [ ]  Tokens - import ERC20 token origin dapp
- [ ]  Tokens - import ERC721 token origin MM
- [ ]  Tokens - import ERC721 token origin dapp
- [ ]  Tokens - import ERC1155 token origin MM
- [ ]  Tokens - approve ERC1155 token
- [ ]  Tokens - approve ERC20 token
- [ ]  Tokens - approve ERC721 token
- [ ]  Tokens - autodetect tokens
- [ ]  Tokens - autodetect NFTs
- [ ]  ENS - name resolution
- [ ]  Phishing - warning page
- [ ]  Network - add custom network manually
- [ ]  Network - add custom network from the list of popular networks
- [ ]  Network - add custom network from dApp
- [ ]  Network - update networks
- [ ]  Network - switching networks
- [ ]  Network - delete networks from the dropdown list
- [ ]  Network - delete networks in Settings
- [ ]  Backup - backup user data
- [ ]  Backup - restore user data
- [ ]  Metrics - send event metrics
- [ ]  Address-book - add a contact to the address book
- [ ]  Address-book - remove a contact from the address book
- [ ]  Address-book - update a contact in the address book
- [ ]  Gas fee - EIP-1559 gas
- [ ]  Gas fee - legacy gas
- [ ]  Sign - eth sign
- [ ]  Sign - personal sign
- [ ]  Sign - sign in with ethereum
- [ ]  Sign - sign typed with data
- [ ]  Permissions - connecting and disconnecting from a dapp
- [ ]  Swap - smart swap
- [ ]  Swap - swap eth
- [ ]  Incoming transactions - receive native token

**Comment by AlexHerman1** [comment]
the cancel txn functionality worked but not sure if its intended to show a "receive" for the cancel txn? Probably could handle this better but not sure

Screenshot 2024-01-31 at 3 58 01 PM

**Comment by AlexHerman1** [comment]
when testing the "send erc721 origin MM" scenario, it passed just fine, but i sent it to another account in this MM instance and the receiving account erroneously refers to the NFT as "Previously Owned" And does not allow you to send it, even after lock and unlock.

Screenshot 2024-01-31 at 4 31 58 PM
Screenshot 2024-01-31 at 4 32 06 PM

**Comment by AlexHerman1** [comment]
chrome failed: **Tokens - import ERC721 token origin MM**

When entering the token contract and symbol, the "import" button would not "un-grey" itself and function

**Comment by AlexHerman1** [comment]
autodetect NFT on mainnet not working with this asset:

https://etherscan.io/token/0xeda7b44eda773c69aeff616767d3b2e439cdb2fc?a=0xC8bc4288c81f18Cdbb1af2bA90863f4e8fe41Ea0

Also wont let me manually import

Screenshot 2024-01-31 at 6 42 06 PM

**Comment by chloeYue** [comment]
Release tracker for change validation on v11.10.0:
https://docs.google.com/spreadsheets/d/1tsoodlAlyvEUpkkcNcbZ4PM9HuC9cEM80RZeoVv5OCQ/edit#gid=854571266

We need teams' approval on 7 Feb at the latest.

 Snaps: @bowensanders / @FrederikBolding / @Montoya - There are 3 Snaps changes in v11.10.0.
 Confirmation UX: @seaona - There are 9 Confirmations UX changes in v11.10.0.
 Confirmation Systems: @sleepytanya - There are 2 Confirmation Systems changes in v11.10.0.
 Accounts: @plasmacorral - There are 5 Accounts changes in v11.10.0.
 Assets: @sahar-fehri / @alfeng6 - There is 1 Assets changes in v11.10.0.
 Swaps: @davibroc / @dan437 - There is 1 Swaps change in v11.10.0.
 Extension UX: @darkwing / @NidhiKJha - There are 6 Extension UX changes in v11.10.0.
 MMI: @zone-live / @shane-t - There is 1 MMI changes in v11.10.0. 

Note: please attach all the release bugs to this bug report epic here: https://github.com/MetaMask/MetaMask-planning/issues/1970

Thank you so much!

**Comment by anaamolnar** [comment]
Sign - eth sign
 Sign - personal sign
 Sign - sign in with ethereum
 Sign - sign typed with data
 
When signing the above type transactions, these error pop up after the pop-up closes.
image

**Comment by anaamolnar** [comment]
ENS - not supported on Sepolia, works fine on Mainnet, Goerli

**Comment by benjisclowder** [comment]
> the cancel txn functionality worked but not sure if its intended to show a "receive" for the cancel txn? Probably could handle this better but not sure (chrome) Screenshot 2024-01-31 at 3 58 01 PM

The "receive" post canceled transaction is expected as per the documentation of the test scenario.

**Comment by benjisclowder** [comment]
> when testing the "send erc721 origin MM" scenario, it passed just fine, but i sent it to another account in this MM instance and the receiving account erroneously refers to the NFT as "Previously Owned" And does not allow you to send it, even after lock and unlock.
> 
> (chrome)
> 
> Screenshot 2024-01-31 at 4 31 58 PM Screenshot 2024-01-31 at 4 32 06 PM

Thanks @AlexHerman1, that's a good catch, I have checked and it was not happening in a previous version so it must have been introduced in this RC. I have logged it here: https://github.com/MetaMask/metamask-extension/issues/22794. What I noticed is that the NFT will appear on all accounts (even 4) that are added in the wallet, even before proceeding to send the asset. After sending it, the same mention is displayed on all accounts of "previously owned". As you said, lock/unlock does not do the trick, but Adding a new account does make it go away.

**Comment by benjisclowder** [comment]
> chrome failed: **Tokens - import ERC721 token origin MM**
> 
> chrome failed: **Tokens - import ERC1155 token origin MM**
> 
> both show the same failure
> 
> Screenshot 2024-02-01 at 11 12 24 AM
> 
> Screenshot 2024-02-01 at 11 11 41 AM

That's valid, issue logged here: https://github.com/MetaMask/metamask-extension/issues/22796

**Comment by sleepytanya** [comment]
ENS on mainnet - initially works then 'ens lookup failed' message pops up.
Chrome:

https://github.com/MetaMask/metamask-extension/assets/104780023/c4730a6d-d135-41f0-9112-34bd9687b9eb

Firefox:

https://github.com/MetaMask/metamask-extension/assets/104780023/222d988a-5fca-4ba7-8c47-c6169a1e19dc

**Comment by plasmacorral** [comment]
🟢 QA Sign Off from Accounts team
Several observations added to the bug report, but none are launch blocking.

**Comment by sleepytanya** [comment]
🟢 QA Sign Off from Confirmations System team

**Review by brad-decker — DISMISSED** [review]

**Review by danjm — APPROVED** [review]

**Pull request merged**
