### PR TITLE
chore: update Trezor Connect to v9.4.0, remove workarounds

### PR DESCRIPTION
**Pull request by vthomas13**
This PR includes changes from PR #26749 by @martykan.

## **Description**

> With MV3, MetaMask started to use Trezor Connect inside an offscreen environment, in a way that was previously unsupported and required a workaround by patching the Trezor Connect library.
> 
> In recent versions of Trezor Connect, the library can handle working in an offscreen environment correctly, without the need for the workaround, which could cause issues with compatibility.
> 
> This PR removes the patch and updates the Trezor Connect library to the latest version (v9.4.0).
> The change in manifest.json is due to new URL parameters, Firefox needs the asterisk at the end to match the URL with them.
> I haven't removed the WebUSB device request which was added on MetaMask's side in relation to the workaround, since it can improve UX of the pairing process, but it could be removed if desired.
> 
> The dependency update affects Lavamoat, I am including the policy changes in my commit, however let me know if you would like me to remove them and handle them using your own process.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/27112?quickstart=1)

## **Related issues**

Fixes:

## **Manual testing steps**

> 1. Open accounts dropdown, "Add hardware wallet"
> 2. Select Trezor
> 3. Follow prompts to connect the device
> 4. See a list of accounts from the Trezor

## **Pre-merge author checklist**

- [x ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by danjm** [comment]
@metamaskbot update-policies

**Comment by vthomas13** [comment]
@metamaskbot update-policies

**Comment by danjm** [comment]
@metamaskbot update-policies

**Comment by vthomas13** [comment]
@metamaskbot  update-policies

**Comment by vthomas13** [comment]
@metamaskbot update-policies

**Comment by danjm** [comment]
@SocketSecurity ignore npm/tiny-secp256k1@1.1.6

**Comment by vthomas13** [comment]
@SocketSecurity ignore npm/varuint-bitcoin@1.1.2 npm/@solana/buffer-layout@4.0.1
Verified these authors as members of other open source projects

**Comment by vthomas13** [comment]
@SocketSecurity ignore npm/agentkeepalive@4.5.0 npm/bigint-buffer@1.1.5 npm/ripple-lib@1.10.1 npm/blake-hash@2.0.0

[npm/agentkeepalive@4.5.0](https://socket.dev/npm/package/agentkeepalive/overview/4.5.0): it's a widely used library to improve HTTP/HTTPS performance by maintaining persistent connections.
[npm/bigint-buffer@1.1.5](https://socket.dev/npm/package/bigint-buffer/overview/1.1.5): the fallback mechanism ensures the non-native version can still be used in case of an issue with the native code
[npm/ripple-lib@1.10.1](https://socket.dev/npm/package/ripple-lib/overview/1.10.1): it's a stable release, but the library is deprecated, so it's good to migrate to xrpl.js as Socket suggests.
[npm/blake-hash@2.0.0](https://socket.dev/npm/package/blake-hash/overview/2.0.0): It's a cryptographic library, and they usually use native code for performance reasons. However native-code can lead to platform-specific vulnerabilities. It's used in trezor's utxo-lib package

**Comment by vthomas13** [comment]
@SocketSecurity ignore npm/wif@4.0.0 npm/usb@2.12.0 npm/jayson@4.1.1 npm/@solana/web3.js@1.95.3 npm/@trezor/transport@1.3.0

[npm/wif@4.0.0](https://socket.dev/npm/package/wif/overview/4.0.0):  Verified the new author as a member of other open source projects
[npm/usb@2.12.0](https://socket.dev/npm/package/usb/overview/2.12.0), [npm/jayson@4.1.1](https://socket.dev/npm/package/jayson/overview/4.1.1),  [npm/@solana/web3.js@1.95.3](https://socket.dev/npm/package/@solana/web3.js/overview/1.95.3), [npm/@trezor/transport@1.3.0](https://socket.dev/npm/package/@trezor/transport/overview/1.3.0): These are not used in trezor/connect-web, which is what we import.

**Comment by vthomas13** [comment]
@SocketSecurity ignore npm/@trezor/blockchain-link-utils@1.2.0 npm/@trezor/analytics@1.2.0
[npm/@trezor/blockchain-link-utils@1.2.0](https://socket.dev/npm/package/@trezor/blockchain-link-utils/overview/1.2.0), [npm/@trezor/analytics@1.2.0](https://socket.dev/npm/package/@trezor/analytics/overview/1.2.0): These are not used in trezor/connect-web, which is what we import.

**Review by danjm — APPROVED** [review]

**Review by mikesposito — APPROVED** [review]

**Comment by vthomas13** [comment]
@SocketSecurity ignore npm/bs58@5.0.0 npm/bs58check@3.0.1 npm/node-addon-api@7.1.0
The new authors are members of other related open source projects

**Pull request merged**
