### PR TITLE
Version v11.16.8

### PR DESCRIPTION
**Pull request by zone-live**
See changelog for details

### CODE REVIEW

**Comment by zone-live** [comment]
@metamaskbot update-policies

**Comment by zone-live** [comment]
@metamaskbot update-policies

**Comment by zone-live** [comment]
@metamaskbot update-policies

**Comment by zone-live** [comment]
@metamaskbot update-policies

**Comment by Gudahtt** [comment]
@metamaskbot update-policies

**Comment by Gudahtt** [comment]
@SocketSecurity ignore npm/utf-8-validate@5.0.10
@SocketSecurity ignore npm/bufferutil@4.0.8
@SocketSecurity ignore npm/rpc-websockets@7.11.1

These are all false positives, none of these are added here. The last one is actually being replaced. I'm not sure what's causing this.

**Comment by danjm** [comment]
@albertolive Tested the mmi custodial account transaction flow
@adonesky1 Tested the hardware switching bug

I tested:
- installing on chromium v108, seeing the warning
- installing on v126, not seeing the warning
- ledger transactions, signatures
- sending a transaction on an L2 with trezor, swap on an L2 with trezor
- Snaps and PPOM
- the auto lock timer bug, both the auto lock working when set to 1 minute, and no error happening when set to empty string
- being on v11.16.7, hitting the auto lock timer bug, refreshing metamask and then being stuck on the loading screen, updating to v11.16.8 and now being able to log in successfully

**Review by danjm — APPROVED** [review]

**Pull request merged**
