### PR TITLE
Master sync

### PR DESCRIPTION
**Pull request by danfinlay**

### CODE REVIEW

**Comment by Gudahtt** [comment]
We will need to update this to remove the `revert` for now. The plan is to revert that revert commit on `master` prior to the next feature release.

**Comment by danfinlay** [comment]
> We will need to update this to remove the revert for now. The plan is to revert that revert commit on master prior to the next feature release.

Ok, then closing this for now.

**Comment by Gudahtt** [comment]
I'll prepare a separate branch to sync the non-revert changes

**Comment by Gudahtt** [comment]
Actually we don't need a master sync - all of these commits were cherry-picked from develop. We'll save the sync until after the feature releaase.

**Pull request closed without merging**
