### PR TITLE
resolve onion address

### PR DESCRIPTION
**Pull request by ricott1**
We extended the Ipfs name resolution to include the possibility to resolve an onion address.

This pull works in tandem with the [ens-app](https://github.com/ensdomains/ui/pull/13) pull.

### CODE REVIEW

**Comment by whymarrh** [comment]
> This pull works in tandem with the ens-app pull.

Does that PR need to be merged in first? How are the different PRs coordinated here? The code changes here look good, I want to make sure I understand the context for all the different things that are working together to make this functionality useful to users.

**Comment by ricott1** [comment]
> Does that PR need to be merged in first? 
Yes, I think that is a better idea. 

There is also the question of whether or not use a gateway to the tor network, or just resolve the onion address, in which case the address would be reachable only if using the tor browser.

**Comment by ricott1** [comment]
The ens-app pull has been merged. I updated the onion address resolution, but I'm still resolving the address directly, without any gateway.

**Comment by whymarrh** [comment]
@ricott1 I rebased this PR on our latest `develop` branch and updated content-hash to the latest version. I'm good with these changes if you are.

**Review by whymarrh — APPROVED** [review]
1ca21fd LGTM

**Comment by ricott1** [comment]
It's good for me, thanks

**Pull request merged**
