### PR TITLE
i18n-helper - abort on i18n failure

### LINKED ISSUE #4079: TypeError: Cannot read property 'message' of undefined
https://sentry.io/metamask/metamask/issues/512877842/

```
TypeError: Cannot read property 'message' of undefined
  at getMessage (ui/i18n-helper.js:17:22)
  at r.value (ui/app/components/network-display.js:33:39)
  at None (node_modules/react-dom/lib/ReactCompositeComponent.js:1:1)
  at measureLifeCyclePerf (node_modules/react-dom/lib/ReactCompositeComponent.js:1:1)
  at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (node_modules/react-dom/lib/ReactCompositeComponent.js:1:1)
...
(45 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by kumavis**
Fixes #4079

### CODE REVIEW

**Review by danjm — DISMISSED** [review]

**Comment by kumavis** [comment]
guess we could also return something like `[${key}]` instead of an empty string

**Comment by danfinlay** [comment]
Yeah, that sounds better, I'd hate for a user to see nothing and just be confused.

**Comment by danfinlay** [comment]
Does this fix a particular reported issue?

**Comment by danfinlay** [comment]
Looks like this fixes #4079.

**Comment by kumavis** [comment]
@danjm review and merge at your convenience

**Review by danfinlay — APPROVED** [review]

**Pull request merged**
