### PR TITLE
Handle incoming tx fetch errors

### PR DESCRIPTION
**Pull request by danjm**
This PR updates the incoming tx controller so that fetch errors are handled without being thrown to sentry

### CODE REVIEW

**Comment by Gudahtt** [comment]
It looks like these are already being caught on line 178. I'm not sure whether this changes anything ultimately.

**Comment by whymarrh** [comment]
I agree with @Gudahtt's comment above, these errors should already be caught & logged

**Comment by whymarrh** [comment]
I think the defaults change though could be useful, if even just as documentation, I'd approve those changes in their own PR.

**Comment by Gudahtt** [comment]
Hey @danjm I'm going to close this for now - feel free to re-open if you think we still need it.

**Review by Gudahtt — APPROVED** [review]
Thanks! Seems reasonable.

**Pull request merged**
