### PR TITLE
New notification fixes

### PR DESCRIPTION
**Pull request by danjm**
This PR improves our new notifications in the following ways:
- positions the notifications to the bottom of the window, and not the bottom of the tx list
- removes `isRequired` proptypes conditions that could cause errors
- adds UX for multiple notifications
- allows user to dismiss connect notifications
- and, along the way, some refactoring was done to remove the backup-notification component in favour of the home-notification component

Screen captures

Multiple notifications: https://streamable.com/g6icb
Dismiss connect notification: https://streamable.com/agory

### CODE REVIEW

**Comment by Gudahtt** [comment]
I noticed that if you hover over the tooltip, then click `Dismiss` while the tooltip is still showing, the popup gets a scrollbar, leaving a bunch of empty space in the footer.

**Comment by Gudahtt** [comment]
I was concerned that dismissing the connect notification would leave a user unable to ever connect to that site. That's not the case though luckily - the ProviderApproval controller state isn't persisted, so the notice shows up again after restarting the browser.

**Comment by bdresser** [comment]
Restarting the browser? Is it possible to have the notification re-appear on page refresh?

**Comment by danjm** [comment]
> Restarting the browser? Is it possible to have the notification re-appear on page refresh?
Not easily, at least that we know of at this moment

**Review by Gudahtt — APPROVED** [review]
Looks good to me! I'll submit the scrollbar issue as a separate issue.

Edit: Scrollbar issue: #6971

**Pull request merged**
