### PR TITLE
Add time and origin to confirm page

### LINKED ISSUE #6071: Signature request screen must show requesting domain
Currently our signature challenge screen as presented by 3Box does not show the requesting domain, so if I'm looking at another domain while the challenge pops up, I might think it's coming from them, which could be used to mitm the 3box secret material.

### PR DESCRIPTION
**Pull request by PatrykLucka**
This PR adds information about **time of transaction initiation**, **origin** and **favicon** to

- transaction confirmation screen
Screenshot 2020-09-09 at 13 20 22

- signing screen
Screenshot 2020-09-09 at 13 22 00

I'm not sure about the design - although in my opinion at least signing screen looks pretty nice : )
Also let me know if I missed any other screens!

Fixes #6071
Related to #5611 #6433

### CODE REVIEW

**Comment by darkwing** [comment]
@rachelcope @jacobcantele Is this a feature we want?  Any design feedback?

**Comment by danfinlay** [comment]
We are currently weighing the security benefits of this change vs the design impact. We aren't aware of any current dangers or phishing schemes that are related to deceiving users what domain a proposal is coming from, but I'd be happy to hear extra context about what motivated this PR.

**Comment by danfinlay** [comment]
Ok we're going to make some design proposal improvements, keeping this open for Rachel to add those designs.

**Comment by rachelcope** [comment]
I've updated the designs to more closely align with our other confirmations and design system.

image
image

Figma file:
 https://www.figma.com/file/UZG4xSubSqvDc1KC7RhKCj/9377-Confirm-Transaction?node-id=0%3A1

**Review by Gudahtt — CHANGES_REQUESTED** [review]
The new designs posted in @rachelcope 's last comment are ready to implement now. The changes to the confirmation page are to remove the timestamp and left-align the origin. The signature request has a few more substantial changes, making it look a bit more like the connect confirmation.

Let us know if you have any questions! Or if you need to hand this off.

**Comment by danfinlay** [comment]
Fixes #6071

**Comment by danjm** [comment]
Let's just add the origin for now.

**Comment by Gudahtt** [comment]
This has been superseded by #10300 and #10296, which add the origin to the signature request confirmation page and transaction confirmation page respectively.

The time will added in a future redesign.

Thanks again @PatrykLucka for your work on this!

**Pull request closed without merging**
