### PR TITLE
fix: issue where per dapp selected network proxies are not synced correct across preference toggle

### PR DESCRIPTION
**Pull request by adonesky1**
## **Description**

[The changes integrated here](https://github.com/MetaMask/core/commit/15518442513fbeaade83e4993851acdc1f038e4a#diff-f17918dbe6fc43037bfaa47fa6869da4c3b244154ef7a9eacbcd3a0a373351efR10) from `@metamask/selected-network-controller` v12 keep the per domain proxies (stored in domainProxyMap) pointing to the correct network client instance when the "Select networks for each site" toggle is turned on and off.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/24093?quickstart=1)

## **Manual testing steps**

1. Open the wallet in fullscreen
2. Switch network to Ethereum Mainnet
3. Open the experimental settings page
4. Turn off 'Select networks for each site' if was on previously (otherwise leave it off)
5. Open a dapp (or any webpage will work) in another window or tab
6. Connect to the dapp
7. Open the console and execute:
```
await window.ethereum.request({
  "method": "eth_chainId",
  "params": []
});
```
8. You should get '0x1'
9. Switch the network in the wallet to Sepolia
10. Go back to the dapp console and execute the same request -> You should get '0xaa36a7'
11. Turn on the 'Select networks for each site' setting
12. Switch the network back to Ethereum Mainnet
13. Go back to the dapp console and execute the same request -> You should still get '0xaa36a7'
14. Turn off the 'Select networks for each site' setting
15. Go back to the dapp console and execute the same request -> You should get '0x1' again

### **Before**

https://github.com/MetaMask/metamask-extension/assets/34557516/e39ce796-6e39-41d3-80b2-f582b66fa965

### **After**

https://github.com/MetaMask/metamask-extension/assets/34557516/de8701d7-b342-4b56-ab87-1a73842c0706

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by adonesky1** [comment]
I think I may need to go back and apply this change to SelectedNetworkController 😮‍💨 :

```
diff --git a/packages/selected-network-controller/src/SelectedNetworkController.ts b/packages/selected-network-controller/src/SelectedNetworkController.ts
index 8f84c332..ea67aaab 100644
--- a/packages/selected-network-controller/src/SelectedNetworkController.ts
+++ b/packages/selected-network-controller/src/SelectedNetworkController.ts
@@ -332,11 +332,13 @@ export class SelectedNetworkController extends BaseController<
    * @returns The proxy and block tracker proxies.
    */
   getProviderAndBlockTracker(domain: Domain): NetworkProxy {
-    const networkClientId = this.getNetworkClientIdForDomain(domain);
     let networkProxy = this.#domainProxyMap.get(domain);
     if (networkProxy === undefined) {
       let networkClient;
-      if (networkClientId === undefined || !this.#useRequestQueuePreference) {
+      if (
+        !this.#useRequestQueuePreference ||
+        !this.#domainHasPermissions(domain)
+      ) {
         networkClient = this.messagingSystem.call(
           'NetworkController:getSelectedNetworkClient',
         );
@@ -344,6 +346,7 @@ export class SelectedNetworkController extends BaseController<
           throw new Error('Selected network not initialized');
         }
       } else {
+        const networkClientId = this.getNetworkClientIdForDomain(domain);
         networkClient = this.messagingSystem.call(
           'NetworkController:getNetworkClientById',
           networkClientId,
```

**Comment by adonesky1** [comment]
I can add an E2E test for this however we will be removing this toggle soon so I'm not sure how valuable. Let me know if you think its worth it!

**Comment by jiexi** [comment]
Note that your Manual testing steps do not specify that the dapp should have accounts connected when i think it should. When following the steps without connecting the webpage, step 12 gave me the chainId for mainnet, not sepolia

**Review by jiexi — APPROVED** [review]
confirmed that the dapp must have connected accounts for the steps above. approving

**Review by mcmire — APPROVED** [review]
Followed the testing steps with `test-dapp` and can confirm that this works.

**Pull request merged**
