### PR TITLE
Enforce transaction log limit

### LINKED ISSUE #390: Persist transaction history outside config-manager
Right now all our persistence is in the same config file, which is eventually going to grow too big to keep in a single `localStorage` key.

Most of our config grows at a modest rate, the one thing that is proportional to usage is the transaction log.

If we could just start storing transactions in leveldb, we could access them and filter them on retrieval, without muddying up the rest of our persistence.

### PR DESCRIPTION
**Pull request by danfinlay**
Fixes #390 

Adds a limit to our persisted transaction list, to avoid overloading our localStorage (eventually we'll move to something that can handle a large list, but for now our list is hardly comprehensive, so a limit doesn't seem that bad).

Also added a `View more` button to the transaction history, which looks like so (depending on whether there are txs or not):

screen shot 2016-08-18 at 4 22 14 pm
screen shot 2016-08-18 at 4 22 24 pm

### CODE REVIEW

**Comment by kumavis** [comment]
Shouldnt ever say "No Transaction History" and "show more", right?

**Comment by flyswatter** [comment]
We don't know. *We* don't know of any history, but we can *show more* about their account, for example, incoming txs, or txs before this vault was created.

Maybe the wording can be improved.

**Comment by flyswatter** [comment]
At the very least we both casually switched to `Show More`, which sounds more casual than `View More`.

**Comment by kumavis** [comment]
This feels a little weird -- guess we just need to replace it later with a fancy optimized lazy-loading scroll view

**Comment by flyswatter** [comment]
I agree, it's not ideal, but it prevents *unknown repercussions* with little enough effort that we can pursue our main goals before that layer of optimization.

- Dan

**Comment by flyswatter** [comment]
I don't get what conflicts this branch has. I think Github is freaking out.

**Comment by frankiebee** [comment]
Maybe a little info symbol would be nice with the tooltip. when you hover over it it tells you that it directs you to a site to see if you have any other transactions not recorded in history. I agree with Aaron that it looks weird that we say no history and then show more

**Comment by flyswatter** [comment]
- [ ] Change "transactions" list header to "history"
- [ ] Move the "view more" button into a little "info" icon next to the `copy` button.

**Comment by flyswatter** [comment]
screen shot 2016-08-22 at 2 37 58 pm
screen shot 2016-08-22 at 2 37 51 pm

Updated, probably ready for a merge!

**Pull request merged**
