### PR TITLE
Integration test suite improvements

### PR DESCRIPTION
**Pull request by kumavis**
- [x] refactor and rename npm scripts (could affect your muscle memory)
- [x] migrate mascara tests to karma
- [x] mascara tests - move temp build files into dist/mascara
- [ ] mascara tests - get em passing (sw race condition) @frankiebee 
- [ ] include mascara integration tests in normal CI run
- [ ] maybe get UI dev helper working again, may have broken it
- [x] check in with kyokan on these changes @chikeichan @sdtsui et al

### CODE REVIEW

**Comment by kumavis** [comment]
```
Chrome 61.0.3163 (Linux 0.0.0) ERROR
  Some of your tests did a full page reload!
```
my guess is its the proxy.js
```
background.on('updatefound', () => window.location.reload())
```

**Comment by kumavis** [comment]
@frankiebee any ideas? i dont get this issue locally

**Comment by frankiebee** [comment]
why would it come from proxy? thats weird its shouldnt reload at all due too `METAMASK_SKIP_RELOAD`

**Review by frankiebee — APPROVED** [review]
LGTM

**Pull request merged**
