### PR TITLE
Fix Buffer warnings during build

### PR DESCRIPTION
**Pull request by Gudahtt**
The production build shows many deprecation warnings about the `Buffer` constructor. They look like this:
```
(node:2133709) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

The warnings about use of the unsafe Buffer constructor have been addressed by package updates and patches.

The updates were:
 * `gulp-sourcemaps` was updated from v2 to v3, and was patched to replace remaining uses of the `Buffer` constructor
   * Upstream PR: gulp-sourcemaps/gulp-sourcemaps#388
 * The transitive dependency `yazl` was updated from v2.4.3 to v2.5.1 in the lockfile.
 * The abandoned packages `combine-source-map` and `inline-source-map` were patched.

### CODE REVIEW

**Comment by Gudahtt** [comment]
This depends upon #10493. Also I want to get upstream patches up before merging this if possible, so we're on track for removing these patches.

**Comment by darkwing** [comment]
@Gudahtt Do you know if this is still relevant?  I don't know what the buffer issue is...

**Comment by Gudahtt** [comment]
This was to address verbose console warnings during the build. I think it's still relevant but I can double check. Sorry about the lack of detail! I had expected to have this ready when the new build system was still new, and it the new warnings were more obvious.

I'll update this tomorrow.

**Comment by Gudahtt** [comment]
@darkwing This is now ready for review! I've updated the PR description, and added an example of the warning this gets rid of. Run `yarn build prod` to test it.

**Review by darkwing — APPROVED** [review]

**Comment by mcmire** [comment]
@Gudahtt We still want to wait until https://github.com/gulp-sourcemaps/gulp-sourcemaps/pull/388 is merged or do you now want to get this in sooner rather than later?

**Comment by Gudahtt** [comment]
I'm not especially hopeful about that being merged anytime soon. I mentioned that because an aspirational goal for patches was to use them as a last resort, and to try to land them upstream if at all possible so we don't have to maintain them.

The highest cost of patches is in keeping them up-to-date when the package being patched gets updated. So hopefully if a patch has an upstream PR, that PR will get accepted before the next package release, and we can then delete the patch when we update the package.

I didn't bother with the two updated packages because they were so clearly abandoned, so it seemed unlikely they'd ever be updated again.

**Review by mcmire — APPROVED** [review]
Sounds good. Looks good to me.

**Pull request merged**
