### PR TITLE
Fix 2094 related issues

### PR DESCRIPTION
**Pull request by danfinlay**
This has some fixes, but there are more to go:

- [x] @kgserrano cant import account (can't reproduce)
- [x] @frankiep cant edit gasLimit
- [x] Balance not updating (`BalanceController` not getting update triggered from `AccountTracker`)

### CODE REVIEW

**Comment by tmashuang** [comment]
Issue with send screen when changing network. Reproduction: initialize a transaction, before clicking Submit change network, and infinite loading spinner.

**Comment by danfinlay** [comment]
Does this PR introduce that bug? Was it even the last PR? Are we sure when that behavior began?

I think that's an edge case we should account for, but not block this over.

**Comment by Zanibas** [comment]
@tmashuang that's an issue we've had for awhile, non-blocking

**Comment by tmashuang** [comment]
My mistake, thought we always have listened on network changes on the send tx screen. The issues seemed to have been resolved.

**Review by 2-am-zzz — APPROVED** [review]
nothing major breaking, other errors may have been there already. We can progress from here.

**Pull request merged**
