### PR TITLE
use latest signTypedData version from eth-sig-util

### LINKED ISSUE #6106: Array support in encodeData for EIP712 signature.
I have been working with metamask support of EIP712 signatures for a long time, but when I recently tryied signing an array of structs I got an error:

```RPC Error: Error: MetaMask Message Signature: Error: Arrays currently unimplemented in encodeData`` `

To reproduce the error, just run the following code:

```
TYPES =
{
	EIP712Domain: [
		{ name: "name",              type: "string"  },
		{ name: "version",           type: "string"  },
		{ name: "chainId",           type: "uint256" },
		{ name: "verifyingContract", type: "address" },
	],
	Entry: [
		{ name: "id",                 type: "address" },
		{ name: "value",              type: "uint256" },
	],
	Entries: [
		{ name: "content",            type: "Entry[]" },
	],
};
DOMAIN =
{
	name:              "test-domain",
	version:           "0.0.1",
	chainId:           await web3.eth.net.getId(),
	verifyingContract: 0,
};
wallet = "0x......."; // Your wallet address here
message = { content: [{ id: 0, value: 0 }] };
await web3.currentProvider.sendAsync({
	method: "eth_signTypedData_v3",
	params: [ wallet, JSON.stringify({ types: TYPES, domain: DOMAIN, primaryType: "Entries", message: message }) ],
	from: wallet,
});
```

### LINKED ISSUE #6868: Add support for signTypedData_v4
UI should be identical to `_v3`, making implementation simple. The difference is it should use the [newly merged `v4` method in `eth-sig-util@2.3.0`](https://github.com/MetaMask/eth-sig-util/pull/54), which supports arrays and recursive structs.

Created by our friends at Infura to support a new type of state channel they've designed!

Completing this issue also requires updating [our docs site](https://metamask.github.io/metamask-docs/).

### PR DESCRIPTION
**Pull request by BrendanChou**
This supports arrays in signing of typed data

fixes #6868 
fixes #6106

### CODE REVIEW

**Review by danfinlay — CHANGES_REQUESTED** [review]
The purpose of the `v3` suffix is to avoid breaking changes. Rather than changing the behavior of this method, we should add a `case 'V4'` which will use the new method.

**Comment by BrendanChou** [comment]
Ready for another look

**Review by danfinlay — COMMENTED** [review]
This looks good! Thank you so much for contributing this, we weren't able to fit it into this sprint. Could I get a UI team member, maybe @Gudahtt to do an additional sanity check/approval?

**Review by danfinlay — APPROVED** [review]

**Review by bitpshr — APPROVED** [review]

**Review by whymarrh — APPROVED** [review]
LGTM

**Pull request merged**
