### PR TITLE
Reorganize selectors directory

### PR DESCRIPTION
**Pull request by rekmarks**
This PR, while quite large, includes _no functional changes_. It is merely an attempt to rationalize the organization of the `ui/app/selectors` directory. Feedback appreciated! Changes in detail:

- All selectors in directory declared in named files
  - `selectors/selectors.js` remains as a catch-all
  - Permissions-related selectors in `selectors.js` moved to `permissions.js`
- Create `selectors/index.js`, which re-exports all selectors
  - This has the added benefit of catching duplicate exports on linting, of which there were 2
  - Decided against just renaming `selectors.js` to `index.js`, because mixing the re-exports with selector implementations seemed, weird
- Every file importing selectors from the directory now specifies the path as `.../selectors`, without knowledge of the file structure in that directory
  - Exception: tests inside `selectors/tests` import directly from named selector files

### CODE REVIEW

**Comment by whymarrh** [comment]
What's the rationale behind introducing a `tests/` directory? We've pretty consistently kept test files alongside their subjects for most recent code.

**Comment by rekmarks** [comment]
@whymarrh the `tests/` directory was already there, I just moved the `custom-gas` tests into it (they were in the root). I also find the hierarchy more readable with the tests in their own folder.

**Comment by whymarrh** [comment]
Gotcha, I missed that the directory was already there just looking at the diff 😅

**Review by whymarrh — APPROVED** [review]
Seems legit

**Pull request merged**
