### PR TITLE
adding Filecoin logo for the MetaMask UI

### PR DESCRIPTION
**Pull request by longfeiWan9**
## Explanation
Filecoin virtual Machain is EVM-compatible and there are a lot of devs and users who used MetaMask for FIL token transfer or smart contract interaction on Filecoin network.
Users are able to add the Filecoin network to MetaMask and use all the features. But the Filecoin logo is not showing up anywhere in the UI. So we would love to add the Filecoin logo to the proper place on MetaMask UI.

## Screenshots/Screencaps

This PR is mainly the UI work, adding Filecoin logo to proper place.

### Before

image

image

### After

image

image

## Manual Testing Steps

- add Filecoin to the Network on MetaMask
- switch to Filecoin network
- check if the logo shows up on network display as well as token display
- try to transfer FIL token and verify if Filecoin logo is displayed.

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [x] How reviewers can test my changes
- [x] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Comment by longfeiWan9** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by legobeat — COMMENTED** [review]
Thank you for your contribution! I wonder if there is an appropriate svg that could be used instead of the png?

**Comment by longfeiWan9** [comment]
@legobeat I tried svg file, but the logo looks very small on MetaMask UI. The png logo works better.

**Comment by longfeiWan9** [comment]
@kevinghim any updates on this one? Do we have a roughly estimate when this will be reviewed , or released ?

**Review by kevinghim — DISMISSED** [review]

**Comment by honghaoq** [comment]
@kevinghim is this PR ready to merge? anything else needed from Filecoin side?

**Review by Ameralameri — APPROVED** [review]
Approved

**Comment by honghaoq** [comment]
thanks! when can we expect to see the change reflected in metamask UI?

**Comment by longfeiWan9** [comment]
@Ameralameri thank you for approving this PR. When can we expect it to be merged and released?

**Comment by honghaoq** [comment]
@kevinghim @Ameralameri @legobeat Hi checking in here, can we merge the fix please? thanks

**Comment by honghaoq** [comment]
@Ameralameri can you help us merge this change? thanks

**Pull request closed without merging**
