### PR TITLE
fix vanishing list on firefox

### PR DESCRIPTION
**Pull request by brad-decker**
So, this resolves the issue of disappearing components on firefox when scrolling. but I dislike removing this functionality for chrome that doesn't have a problem with it. How difficult would it be to add the browser we are building for as a classname to the HTML element during the build step? We could then enable or disable rules based on browser

Additional details:
There is interplay between position: sticky and z-index. If I change z-index to 0 less of the components disappear when scrolling, if I change it to -1 everything is great but the tabs are gone so :P

### CODE REVIEW

**Comment by Gudahtt** [comment]
Any idea what the underlying cause is here? e.g. maybe a Firefox bug?

**Comment by brad-decker** [comment]
I don't even know, it doesn't have issues when in full screen, either... 🤕 

Pretty sure there's a better solution -- at least I hope there is. I'll keep digging.

**Comment by brad-decker** [comment]
@Gudahtt and @whymarrh this PR now adds static asset replacement feature to the build process, wherein each .HTML file has a `class="browser-classname"` added to the HTML element. Then, during static asset copying...instead of just copying them over we read the file, replace that `browser-classname` with `chrome-browser` or `firefox-browser` or whatever.. now we have the ability to override styling based on browser with no (little) runtime cost

**Comment by whymarrh** [comment]
Well this escalated quickly.

**Comment by brad-decker** [comment]
It really got out of hand fast.

**Comment by brad-decker** [comment]
@whymarrh very interesting. that does fix the problem! Way better fix. Do you want to do the honors or should I close this and submit a new pr with that one liner?

**Comment by whymarrh** [comment]
I can open one up, sure.

**Pull request closed without merging**
