### PR TITLE
bump allow scripts

### PR DESCRIPTION
**Pull request by EtDu**
- Fixes https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/9600/workflows/0dbdedd0-7bb8-45fa-9a29-7357d5fd8907/jobs/280180

### CODE REVIEW

**Comment by Gudahtt** [comment]
So the only change is that there is now a trailing newline - is that correct?

**Review by kumavis — APPROVED** [review]

**Comment by kumavis** [comment]
@Gudahtt  correct - it now appends a newline when generating the policy https://npmfs.com/compare/@lavamoat/allow-scripts/1.0.5/1.0.6/

**Comment by EtDu** [comment]
For the sake of our linter. Maybe we broke someone else's... 🤷

**Comment by Gudahtt** [comment]
Doubtful. It's a requirement of the POSIX standard, for one thing. The npm CLI will always include a trailing newline in newly generated `package.json` files as well, and they typically dictate the format used by any tooling.

Though this might still be broken on Windows, for any projects that are setup to use `\r\n`. Ideally `allow-scripts` would preserve the pre-existing formatting.

**Review by Gudahtt — APPROVED** [review]

**Pull request merged**
