### PR TITLE
Add simple send e2e test

### LINKED ISSUE #6548: Write e2e test for a simple send in new e2e setup

### PR DESCRIPTION
**Pull request by whymarrh**
Closes #6548

This PR adds a e2e test using fixture data that exercises the send flow, sending 1 ETH from one account to another on a local test chain.

### CODE REVIEW

**Comment by whymarrh** [comment]
@danjm this is ready for review—I've added it to CI but I'm still debugging it. It does pass locally so maybe we can leave out the CI job for now?

**Comment by danjm** [comment]
@whymarrh I agree we can leave out the CI for now.

**Comment by danjm** [comment]
Can you add some basic documentation for running these tests locally?

**Comment by danjm** [comment]
Do we need to commit all of these fixture files/

**Review by danjm — CHANGES_REQUESTED** [review]
Code looks fine. Suggested addition of documentation and questioned the committing of all the fixture files.

**Comment by whymarrh** [comment]
> Do we need to commit all of these fixture files

Whatever is needed for a test to run should be committed to the repo, yes. It's the best solution _I_ can come up with, but I'm open to alternatives.

> Can you add some basic documentation for running these tests locally?

I've added brief info for running the tests locally and for generating the fixture files.

**Review by danjm — APPROVED** [review]
LGTM

**Pull request merged**
