### PR TITLE
✔️ Issue #5742 update ens resolver to eip 1577

### PR DESCRIPTION
**Pull request by pldespaigne**
For solving this issue I have used a small lib called `content-hash`. I have developped this lib to implement the content-hash encoding specified by the [EIP1577](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1577.md). The code of the lib can be found [here](https://github.com/pldespaigne/content-hash). This lib is trusted by the ENS team and it is currently used in the official ENS manager web app ([discussion here](https://github.com/ensdomains/ens-contenthash/issues/1), [commit here](https://github.com/ensdomains/ens-app/pull/78/commits/17ca55bd67d6563c131ee3e94dccf991b574e9a8)).
Because the purpose of the `content-hash` lib is to solve this exact issue, I have included it in the `package.json` file.

Detailed realisations :
- [x] resolve eip1577 compliant swarm content-hash to the swarm gateway
- [x] resolve eip1577 compliant ipfs content-hash to the ipfs gateway
- [x] resolve legacy swarm content to the swarm gateway
- [x] redirect to the [ENS manager](https://manager.ens.domains) on error
- [x] use ENS logo on the loading page

You can test on ropsten with those link
[errordomain.eth](https://errordomain.eth) -> error : redirect to the ENS manager
[dappsnation.eth](https://dappsnation.eth) -> legacy swarm content
[ipfs.dappsnation.eth](https://ipfs.dappsnation.eth) ->ipfs content-hash
[swarm.dappsnation.eth](https://swarm.dappsnation.eth) ->ipfs content-hash

### CODE REVIEW

**Comment by pldespaigne** [comment]
see issue #5742

**Comment by pldespaigne** [comment]
@danfinlay @kumavis this is ready for review 😁

**Review by Arachnid — DISMISSED** [review]

**Comment by pldespaigne** [comment]
Guys ? Is there anybody to review my PR ?
@danfinlay  @kumavis @bdresser

**Comment by tmashuang** [comment]
Will need to fix `package-lock` conflicts, since it's been updated after this PR. Regression, so we aren't allowing access to legacy domains like http://portalnetwork.eth?

**Comment by pldespaigne** [comment]
- This PR supports legacy resolver with `content` field as defined by [the old ens docs](https://ens.readthedocs.io/en/latest/implementers.html?highlight=content#writing-a-resolver)
- It support the new `contenthash` field as defined by the [EIP1577](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1577.md)
- It does NOT supports `multihash` field as proposed by [EIP1062](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1062.md)
- It does NOT supports ipfs content resolution via `text['dnslink']` ala Dappnode

`multihash` is not widely used and kinda deprecated by `contenthash` and resolution via the `text` field is not standard at all and used solely by Dappnode. Moreover it is really hard to find doc about both, that's why I haven't implemented them into this PR. I could do it if needed but I'm not sure it is a good idea, @Arachnid what are your thought about that ?

PS: Here you can read discussion about the [EIP1062, dappnode](https://ethereum-magicians.org/t/eip-1062-formalize-ipfs-hash-into-ens-ethereum-name-service-resolver/281) and the [EIP1577](https://ethereum-magicians.org/t/eip-1577-multiaddr-support-for-ens/1969).

**Comment by Arachnid** [comment]
@pldespaigne I think supporting only `content` (as legacy) and `contenthash` is the best way to go.

**Comment by tmashuang** [comment]
Looks good to me then, just need to resolve the `package-lock.json`. A quick solution would be to rebase with develop, remove the package-lock.json, `npm i`, and commit the new package-lock.json.

**Comment by pldespaigne** [comment]
@danfinlay @bdresser @kumavis @whymarrh The conflict is solved, I just need a review now :)

**Review by tmashuang — APPROVED** [review]

**Pull request merged**
