### PR TITLE
Version v11.9.0

### PR DESCRIPTION
**Pull request by chloeYue**
## **Description**

RC v11.9.0

### CODE REVIEW

**Comment by benjisclowder** [comment]
Manual test scenarios:

Chrome

- [ ] Onboarding - create a wallet
- [ ] Onboarding - import a wallet
- [ ] Keyring - connect hardware wallet
- [ ] Keyring - reset a wallet
- [ ] Transactions - send native token origin MM
- [ ] Transactions - send native token origin dapp
- [ ] Transactions - send ERC20 token origin MM
- [ ] Transactions - send ERC20 token origin dapp
- [ ] Transactions - send ERC721 token origin MM
- [ ] Transactions - send ERC721 token origin dapp
- [ ] Transactions - speed up transaction
- [ ] Transactions - cancel transaction
- [ ] Tokens - import ERC20 token origin MM
- [ ] Tokens - import ERC20 token origin dapp
- [ ] Tokens - import ERC721 token origin MM
- [ ] Tokens - import ERC721 token origin dapp
- [ ] Tokens - import ERC1155 token origin MM
- [ ] Tokens - import ERC1155 token origin dapp
- [ ] Tokens - approve ERC1155 token
- [ ] Tokens - approve ERC20 token
- [ ] Tokens - approve ERC721 token
- [ ] Tokens - autodetect tokens
- [ ] Tokens - autodetect NFTs
- [ ] ENS - name resolution
- [ ] Phishing - warning page
- [ ] Network - add custom network manually
- [ ] Network - add custom network from the list of popular networks
- [ ] Network - add custom network from dApp
- [ ] Network - update networks
- [ ] Network - switching networks
- [ ] Network - delete networks from the dropdown list
- [ ] Network - delete networks in Settings
- [ ] Backup - backup user data
- [ ] Backup - restore user data
- [ ] Metrics - send event metrics
- [ ] Address-book - add a contact to the address book
- [ ] Address-book - remove a contact from the address book
- [ ] Address-book - update a contact in the address book
- [ ] Gas fee - EIP-1559 gas
- [ ] Gas fee - legacy gas
- [ ] Sign - eth sign
- [ ] Sign - personal sign
- [ ] Sign - sign in with ethereum
- [ ] Sign - sign typed with data
- [ ] Permissions - connecting and disconnecting from a dapp
- [ ] Swap - smart swap
- [ ] Swap - swap eth
- [ ] Incoming transactions - receive native token

Firefox

- [ ] Onboarding - create a wallet
- [ ] Onboarding - import a wallet
- [ ] Keyring - connect hardware wallet
- [ ] Keyring - reset a wallet
- [ ] Transactions - send native token origin MM
- [ ] Transactions - send native token origin dapp
- [ ] Transactions - send ERC20 token origin MM
- [ ] Transactions - send ERC20 token origin dapp
- [ ] Transactions - send ERC721 token origin MM
- [ ] Transactions - send ERC721 token origin dapp
- [ ] Transactions - speed up transaction
- [ ] Transactions - cancel transaction
- [ ] Tokens - import ERC20 token origin MM
- [ ] Tokens - import ERC20 token origin dapp
- [ ] Tokens - import ERC721 token origin MM
- [ ] Tokens - import ERC721 token origin dapp
- [ ] Tokens - import ERC1155 token origin MM
- [ ] Tokens - approve ERC1155 token
- [ ] Tokens - approve ERC20 token 
- [ ] Tokens - approve ERC721 token
- [ ] Tokens - autodetect tokens
- [ ] Tokens - autodetect NFTs
- [ ] ENS - name resolution
- [ ] Phishing - warning page
- [ ] Network - add custom network manually
- [ ] Network - add custom network from the list of popular networks
- [ ] Network - add custom network from dApp
- [ ] Network - update networks
- [ ] Network - switching networks
- [ ] Network - delete networks from the dropdown list
- [ ] Network - delete networks in Settings
- [ ] Backup - backup user data
- [ ] Backup - restore user data
- [ ] Metrics - send event metrics
- [ ] Address-book - add a contact to the address book
- [ ] Address-book - remove a contact from the address book
- [ ] Address-book - update a contact in the address book
- [ ] Gas fee - EIP-1559 gas
- [ ] Gas fee - legacy gas
- [ ] Sign - eth sign
- [ ] Sign - personal sign
- [ ] Sign - sign in with ethereum
- [ ] Sign - sign typed with data
- [ ] Permissions - connecting and disconnecting from a dapp
- [ ] Swap - smart swap
- [ ] Swap - swap eth
- [ ] Incoming transactions - receive native token

**Comment by chloeYue** [comment]
Bug report for v11.9.0: https://github.com/MetaMask/MetaMask-planning/issues/1923

**Comment by benjisclowder** [comment]
Release tracker for change validation on v11.9.0:
https://docs.google.com/spreadsheets/d/1tsoodlAlyvEUpkkcNcbZ4PM9HuC9cEM80RZeoVv5OCQ/edit#gid=1626398579

- [ ] MMI: @zone-live / @shane-t - There are 3 MMI changes in v11.9.0. We would like to get your team's approval on this release by next Tuesday.
- [ ]  Snaps: @bowensanders / @FrederikBolding / @Montoya - There are 14 Snaps changes in v11.9.0. We would like to get your team's approval on this release by next Tuesday.
- [ ]  Confirmation UX: @seaona - There are 15 Confirmations UX changes in v11.9.0. We would like to get your team's approval on this release by next Tuesday.
- [ ]  Confirmation Systems: @sleepytanya - There are 6 Confirmation Systems changes in v11.9.0. We would like to get your team's approval on this release by next Tuesday.
- [ ]  Accounts: @plasmacorral - There are 11 Accounts changes in v11.9.0. We would like to get your team's approval on this release by next Tuesday.
- [ ]  Assets: @sahar-fehri / @alfeng6 - There are 2 Assets changes in v11.9.0. We would like to get your team's approval on this release by next Tuesday.
- [ ]  Design/Systems: @georgewrmarshall - There are 11 Design/Systems changes in v11.9.0. We would like to get your team's approval on this release by next Tuesday. These do not affect user facing code, so don't require QA
- [ ]  Dapp API: @tmashuang - There are 3 Dapp API changes in v11.9.0. We would like to get your team's approval on this release by next Tuesday.
- [ ]  Devex: @tmashuang / @vandan - There are 5 Devex changes in v11.9.0. We would like to get your team's approval on this release by next Tuesday.
- [ ]  Swaps: @davibroc / @dan437 - There is 1 Swaps change in v11.9.0. We would like to get your team's approval on this release by next Tuesday.
- [ ] Extension UX: @darkwing / @NidhiKJha  - There are 20 Extension UX changes in v11.9.0. We would like to get your team's approval on this release by next Tuesday.

Note: please attach all the release bugs to this bug report epic here: https://github.com/MetaMask/MetaMask-planning/issues/1923

Thank you so much!

**Comment by Bullcoiner** [comment]
Manual test scenarios:

Chrome

- [x] Onboarding - create a wallet
- [x]  Onboarding - import a wallet
- [ ]  Keyring - connect hardware wallet `(unable to complete, do not have a hardware wallet to test with)`
- [x]  Keyring - reset a wallet 
- [x]  Transactions - send native token origin MM
- [x]  Transactions - send native token origin dapp
- [x]  Transactions - send ERC20 token origin MM
- [x]  Transactions - send ERC20 token origin dapp
- [x]  Transactions - send ERC721 token origin MM
- [x]  Transactions - send ERC721 token origin dapp
- [x]  Transactions - speed up transaction
- [x]  Transactions - cancel transaction
- [x]  Tokens - import ERC20 token origin MM
- [x]  Tokens - import ERC20 token origin dapp
- [x]  Tokens - import ERC721 token origin MM
- [x]  Tokens - import ERC721 token origin dapp
- [x]  Tokens - import ERC1155 token origin MM
- [x]  Tokens - import ERC1155 token origin dapp
- [x]  Tokens - approve ERC1155 token
- [x]  Tokens - approve ERC20 token
- [x]  Tokens - approve ERC721 token
- [x]  Tokens - autodetect tokens
- [x]  Tokens - autodetect NFTs
- [x]  ENS - name resolution `(ENS name does not resolve on Goerli or Sepolina, but does on Mainnet. Error "No address has been set for this name")`
- [x]  Phishing - warning page
- [x]  Network - add custom network manually
- [x]  Network - add custom network from the list of popular networks
- [x]  Network - add custom network from dApp
- [x]  Network - update networks
- [x]  Network - switching networks
- [x]  Network - delete networks from the dropdown list
- [x]  Network - delete networks in Settings
- [x]  Backup - backup user data
- [x]  Backup - restore user data
- [x]  Metrics - send event metrics
- [x]  Address-book - add a contact to the address book
- [x]  Address-book - remove a contact from the address book
- [x]  Address-book - update a contact in the address book
- [x]  Gas fee - EIP-1559 gas
- [x]  Gas fee - legacy gas
- [x]  Sign - eth sign
- [x]  Sign - personal sign
- [x]  Sign - sign in with ethereum
- [x]  Sign - sign typed with data
- [x]  Permissions - connecting and disconnecting from a dapp
- [ ]  Swap - smart swap `(unable to complete, need main net funds to test with)`
- [ ]  Swap - swap eth
- [x]  Incoming transactions - receive native token

**Comment by seaona** [comment]
:green_circle:  QA Sign Off from Confirmations UX team

**Comment by plasmacorral** [comment]
🟢 QA Sign Off from Accounts team
 Observations [1974](https://app.zenhub.com/workspaces/extension-release-regression-6478c62d937eaa15e95c33c5/issues/gh/metamask/metamask-planning/1974), [1975](https://app.zenhub.com/workspaces/extension-release-regression-6478c62d937eaa15e95c33c5/issues/gh/metamask/metamask-planning/1975) and [1976](https://app.zenhub.com/workspaces/extension-release-regression-6478c62d937eaa15e95c33c5/issues/gh/metamask/metamask-planning/1976) are not launch blocking for this release

**Comment by sleepytanya** [comment]
🟢 QA sign-off from Confirmations System team.

**Comment by bowensanders** [comment]
🟢 QA Signoff from Snaps team.

**Review by davibroc — COMMENTED** [review]
🟢 QA Signoff from Swap team.

**Comment by danjm** [comment]
@SocketSecurity ignore-all

The warnings are either about new authors in packages we control, or there is one about network access in the trezor/connect library. For the former, we know all the new authors. For the latter issue, Socket Security warns about network access in v1.1.12 of the @trezor/transport library https://socket.dev/npm/package/@trezor/transport/overview/1.1.12. It is saying that fetch is called within lib/bridge/http.js and lib/bridge/v2.js. Looking those files, is points to the fetch function called within `setFetch`. However, these fetch calls have been there for a long time, at least as far back as 1.0.0 of the trezor transport package, which was release in 2021.

**Comment by tmashuang** [comment]
🟢 QA Signoff from DevEx team.

**Comment by seaona** [comment]
:green_circle:  New QA Sign Off from Confirmations UX Team.
**Note**: we've identified some minor issues but they are non-blockers and we agreed that they will be fixed in a subsequent release

cc @bschorchit @danjm

**Review by danjm — APPROVED** [review]

**Pull request merged**
