### PR TITLE
Bundler Refactor

### PR DESCRIPTION
**Pull request by kumavis**
**status: ready for additional feedback or merge** :guitar:  

refactor of the bundler using lavamoat-friendly bundle factoring. this **does not** add lavamoat to the bundles.

### changes to bundle result

- the `ui-libs` and `bg-libs` have been replaced by the `common` bundle. `common` contains all packages that are used by both the `background` and the `ui`. the "factoring" into the `common` bundle is automatic and does not need any adjustment as modules are added/removed.

here is a breakdown of the resultant bundle sizes under different minification strategies. the current configuration is the strategy all the way to the right. compare the size of bg/ui/common.
image

### changes to bundling process

I tried to refactor the bundler so that it was easier to follow without having too much repeated code, but im not sure that I succeeded. part of what complicates this is that certain things (e.g. sourcemaps) need to configure both:
1) initial bundle options (enable browserify debug option) and
2) post-bundle build pipeline (load + write sourcemaps)

its additionally complicated because a watchify re-build involves creating a new build pipeline. my proposed solution is as follows

a basic bundle+build config obj
```js
{ bundlerOpts: {}, events: new EventEmitter() }
```

`events` will fire a `'pipeline'` event when the build pipeline is ready to be augmented. The pipeline is based on browserify's own internal pipeline, a [`labeled-stream-splicer`](https://github.com/browserify/labeled-stream-splicer). It is essentially a nested array of streams that you can pop into position, and it handles all the plumbing for you. it may be slightly over-engineered, but it allows our very different build configurations (inpage+contentscript standalone, ui+background factor) share the same interface, and makes applying some feature (e.g. sourcemaps) able to happen in one place

### etc

moved the lavamoat dashboard (sesify-viz) to a separate process that runs parallel with the other builds, should speed up CI ~3min

### CODE REVIEW

**Comment by kumavis** [comment]
remove https://github.com/MetaMask/metamask-extension/blob/f8b01071ee829dd05f6b1eb5726d8d3bc653ffd1/development/build/scripts.js#L275

**Comment by kumavis** [comment]
move loose things to top of defaults (before sourcemaps/watchify)
https://github.com/MetaMask/metamask-extension/blob/f8b01071ee829dd05f6b1eb5726d8d3bc653ffd1/development/build/scripts.js#L250-L262

**Comment by kumavis** [comment]
moved the lavamoat dashboard (sesify-viz) to a separate process that runs parallel with the other builds, should speed up CI ~3min

**Comment by kumavis** [comment]
Ok I'm happy with this : )

seems like there is [a fair amount of noise in total CI run time](https://app.circleci.com/pipelines/github/MetaMask/metamask-extension?branch=build-sys-2) to see a marked improvement

**Comment by kumavis** [comment]
this isnt handling phishing-detect correctly

**Comment by kumavis** [comment]
ok this should correctly handle `phishing-detect`, it was aggressive of me to change it before understanding how it was wired up. in retrospect i had a nagging suspicion but didnt follow it and hey, tests passed! :roll_eyes:

**Comment by kumavis** [comment]
@Gudahtt ready for another review

**Comment by kumavis** [comment]
@danjm @Gudahtt @whymarrh please review or just trust me and merge : )

**Review by whymarrh — DISMISSED** [review]
@kumavis please don't merge this in just yet. We're trying to keep changes on `develop` to a minimum as we try and get LPS out the door. If you need to base LavaMoat work off this branch, you should be able to do so without merging.

**Comment by kumavis** [comment]
lavamoat work is not blocked by this

**Comment by kumavis** [comment]
QA against https://github.com/MetaMask/metamask-extension/issues/8167

**Comment by Gudahtt** [comment]
The bundles produced by this branch look good, but the sourcemaps for `common.js` are totally wrong 🤔

I'll try and reduce the size of this PR first by getting a few of these changes merged separately, then I'll investigate that problem.

**Comment by Gudahtt** [comment]
It looks like the source maps for _all_ of the bundles are messed up. The `sources` entry in `ui.js.map` lists a bunch of background modules, for example.

**Comment by Gudahtt** [comment]
I tried looking at the direct output of `bify-package-factor` to check the inline source maps, and they seem correct 🤔 Or at least they weren't as obviously incorrect as the final output. So maybe the problem here is with something we're doing _after_ `bify-package-factor`.

**Comment by Gudahtt** [comment]
I've just merged `develop` into this again to bring in the source map validator script changes (and I updated it to check the `common.js` bundle), so CI should now fail until the source maps are fixed.

**Comment by kumavis** [comment]
this PR is super stale now, but has some potentially useful stuff

**Comment by kumavis** [comment]
i want to revert this to a draft pr but i dont see an option for that?

**Comment by brad-decker** [comment]
Screen Shot 2021-01-18 at 9 53 50 AM

I didn't know this existed until Whymarrh pointed it out to me. Paying it forward, also marking this as draft.

**Comment by kumavis** [comment]
rip

**Pull request closed without merging**
