### PR TITLE
chore: Upgrade @metamask/transaction-controller to v21.0.1

### PR DESCRIPTION
**Pull request by vinistevam**
## **Description**
The package `@metamask/transaction-controller` has been upgraded to `v21.0.1`.

This version has the following fixes:
- Resolves transaction custodian promise when setting transaction status to submitted or failed ([#3845](https://github.com/MetaMask/core/pull/3845))
- Fix normalizer ensuring property type is always present in TransactionParams ([#3817](https://github.com/MetaMask/core/pull/3817))

See here for the changelog: https://github.com/MetaMask/core/blob/main/packages/transaction-controller/CHANGELOG.md#2101

## **Related issues**

Fixes: 

## **Manual testing steps**

1. Transaction regression

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [x] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by vinistevam** [comment]
@metamaskbot update-policies

**Comment by vinistevam** [comment]
@metamaskbot update-policies

**Comment by vinistevam** [comment]
@metamaskbot update-policies

**Review by DDDDDanica — APPROVED** [review]

**Review by OGPoyraz — APPROVED** [review]

**Comment by bergarces** [comment]
Tested the issue with the custodian transaction using this branch. It works as expected now.

**Review by bergarces — APPROVED** [review]

**Pull request merged**
