### PR TITLE
Add standard hd path for Ledger

### PR DESCRIPTION
**Pull request by danfinlay**

### CODE REVIEW

**Comment by rekmarks** [comment]
If we do this, are we going to end up with a bunch of users defaulting to the new default and freaking out because all of their accounts are in fact on Ledger Live?

If we think that's a possibility, we should consider an alert overlay like we did for the v8 launch.

**Comment by Gudahtt** [comment]
Is there any compelling reason to change the default at all? Just adding this as an option in the dropdown would be sufficient, and would avoid any change in behavior that might surprise users.

**Comment by rekmarks** [comment]
Isn't this superseded by #9367?

**Comment by danfinlay** [comment]
While I think this could be done in combination with #9367, I agree with the concerns that this could cause alarmed Ledger users, and Ledger users who want to use a more conventional path could use the custom path input from #9367 instead of this one, so I'm going to close this for now.

**Pull request closed without merging**
