### PR TITLE
Bump eth-sig-util to 2.3.0

### PR DESCRIPTION
**Pull request by whymarrh**
Closes #6661, refs https://github.com/MetaMask/eth-sig-util/pull/51

### CODE REVIEW

**Review by Gudahtt — DISMISSED** [review]
On #6661, @danfinlay mentioned having to update the keyrings to use the new version of `eth-sig-util` as well. That hasn't been done yet - they're still on 1.x.

This change seems fine either way - we were already using 2.x. I'm wondering what the consequences of our dependencies using the older `eth-sig-util` might be though - whether any expectations about these signatures bleed across package boundaries. 🤔

**Review by bitpshr — DISMISSED** [review]

**Comment by danfinlay** [comment]
The reason this was listed as a breaking semver change (`eth-sig-util@>=2.x.x` is because the signTypedData method was assigned a new name. We should make sure we are pointing to the correct method in this PR:
https://github.com/MetaMask/eth-sig-util/pull/20/files

**Review by danfinlay — CHANGES_REQUESTED** [review]
The reason this was listed as a breaking semver change (`eth-sig-util@>=2.x.x` is because the signTypedData method was assigned a new name. We should make sure we are pointing to the correct method in this PR:
https://github.com/MetaMask/eth-sig-util/pull/20/files

**Comment by danfinlay** [comment]
Looks like Mark already raised my concern, feel free to dismiss my review, I just mean that we should make sure it still works the same, like on the signature test site: 
https://danfinlay.github.io/js-eth-personal-sign-examples/

**Comment by whymarrh** [comment]
> On #6661, @danfinlay mentioned having to update the keyrings to use the new version of` eth-sig-util` as well. That hasn't been done yet - they're still on 1.x.

Updated to bump `eth-keyring-controller` as well. It is a major version bump but looking at the commits it's all dependency version bumps.<sup>[\[1\]][1]</sup>

I believe this change now accomplishes what we need—I don't think the other instances of the module are important in this context. `npm ls --production eth-sig-util`:

```
├─┬ eth-json-rpc-filters@3.0.4
│ └─┬ eth-json-rpc-middleware@2.6.1
│   └── eth-sig-util@1.4.2 
├─┬ eth-keyring-controller@4.0.1
│ ├─┬ eth-hd-keyring@2.0.0
│ │ └── eth-sig-util@2.3.0  deduped
│ ├── eth-sig-util@1.4.2 
│ └─┬ eth-simple-keyring@2.0.0
│   └── eth-sig-util@2.3.0  deduped
├─┬ eth-ledger-bridge-keyring@0.2.0
│ └── eth-sig-util@1.4.2 
├── eth-sig-util@2.3.0 
├─┬ eth-trezor-keyring@0.4.0
│ └── eth-sig-util@1.4.2 
└─┬ gaba@1.4.1
  ├─┬ eth-keyring-controller@4.0.1
  │ ├─┬ eth-hd-keyring@2.0.0
  │ │ └── eth-sig-util@2.2.0  deduped
  │ ├── eth-sig-util@1.4.2 
  │ └─┬ eth-simple-keyring@2.0.0
  │   └── eth-sig-util@2.2.0  deduped
  ├── eth-sig-util@2.2.0 
  └─┬ UNMET DEPENDENCY web3-provider-engine@github:metamask/provider-engine#e91367bc2c2535fbf7add06244d9d4ec98620042
    └── UNMET DEPENDENCY eth-sig-util@1.4.2 

```

By module:

- **`eth-json-rpc-middleware@2.6.1` using `eth-sig-util@1.4.2`** only uses `#recoverPersonalSign`<sup>[\[2\]][2]</sup>
- **`eth-keyring-controller@4.0.1` using `eth-sig-util@1.4.2`** directly only uses `#normalize`<sup>[\[3\]][3]</sup>
- **`eth-ledger-bridge-keyring@0.2.0` using `eth-sig-util@1.4.2`** does not support `signTypedData`<sup>[\[4\]][4]</sup>
- **`eth-trezor-keyring@0.4.0` using `eth-sig-util@1.4.2`** does not support `signTypedData`<sup>[\[5\]][5]</sup>
- **`gaba@1.4.1`** we are using only select controllers from, none of which deal with signing

> I'm wondering what the consequences of our dependencies using the older eth-sig-util might be though - whether any expectations about these signatures bleed across package boundaries. — @Gudahtt 

That's a valid concern and something we should audit. I imagine we can/will run into issues with the version mix we have (e.g. if `normalize` were to behave differently across versions or something like that). A separate concern though, I believe.

> The reason this was listed as a breaking semver change (`eth-sig-util@>=2.x.x` is because the signTypedData method was assigned a new name. We should make sure we are pointing to the correct method [...] — @danfinlay

The extension was already on 2.x so it shouldn't need undergo any changes for us to bump the direct dependency. Looking at the API for the `KeyringController`, bumping that as well shouldn't require extension changes.

That said, I did test this with the signature site and it looks good to me. Maybe @tmashuang can also give it his seal of approval? I've add @brunobar79 to the reviewers here as well for good measure.

  [1]:https://github.com/MetaMask/KeyringController/compare/v3.3.1...5d4fefac5eed8e33aa3e93faef5e4ddc18e781e4
  [2]:https://github.com/MetaMask/eth-json-rpc-middleware/blob/6be3862c1dde4f781c1cb4cbd4e09ab7017e10a3/wallet.js#L137
  [3]:https://github.com/MetaMask/KeyringController/blob/663427f10ca4e2c393c15828d6a86a71afb628c3/index.js#L9-L10
  [4]:https://github.com/MetaMask/eth-ledger-bridge-keyring/tree/v0.2.0#eth-ledger-bridge-keyring-
  [5]:https://github.com/MetaMask/eth-trezor-keyring/tree/v0.4.0#eth-trezor-keyring-

**Review by Gudahtt — APPROVED** [review]
Sounds reasonable to me 👍

**Review by danfinlay — APPROVED** [review]
Looks like @whymarrh did the due diligence, thanks!

**Pull request merged**
