### PR TITLE
refactor: remove desktop support

### LINKED ISSUE #25165: Remove desktop code from extension
Remove all desktop code and related CI jobs, in order to simplify codebase and marginally reduce pipeline cost.

### PR DESCRIPTION
**Pull request by matthewwalsh0**
## **Description**

Remove all code and configuration supporting the unreleased desktop functionality.

This can be extracted from the commit history if needed in future.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/25147?quickstart=1)

## **Related issues**

Fixes: #25165

## **Manual testing steps**

No functional changes to main build, E2E tests should validate existing flows.

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by matthewwalsh0** [comment]
@metamaskbot update-policies

**Comment by matthewwalsh0** [comment]
@SocketSecurity ignore-all

**Review by legobeat — APPROVED** [review]

**Review by jpuri — APPROVED** [review]
LGTM

**Review by mcmire — APPROVED** [review]

**Pull request merged**
