### PR TITLE
Add subheader to all settings subviews

### PR DESCRIPTION
**Pull request by chikeichan**
subheader

### CODE REVIEW

**Comment by danjm** [comment]
Code looks good. Overlaps with changes here: https://github.com/MetaMask/metamask-extension/pull/6483/files

**Review by danjm — DISMISSED** [review]

**Comment by cjeria** [comment]
@chikeichan Only one thing I'm seeing: the bottom border applied to the subheader is running all the way to the right edge of the white page container. I'd give it a margin-right:24px (or something equivalent) to the `settings-page__subheader` container so that it doesn't touch the far right edge of the white container. Other than that, it's looking good!

image

**Comment by chikeichan** [comment]
Screen Shot 2019-04-26 at 4 52 16 PM

Updated!

**Review by cjeria — COMMENTED** [review]
Looks good!

**Review by danjm — APPROVED** [review]

**Pull request merged**
