### PR TITLE
Migrate components to TS: AvatarAccount

### LINKED ISSUE #18882: Migrate components to TS: AvatarAccount
### Description
Migrate `AvatarAccount` component to TypeScript

### Technical Details
- Convert Objects in `SNAKE_CASE` to enums in `PascalCase` follow [TS conventions](https://www.notion.so/Use-TypeScript-9ec7bd8fc8cf4d82b81cd8943c4707cd?pvs=4#7e6410b21100455a9a08442108f19d78)
- Update file name from `component-name.contants.js` to `component-name.types.ts` and add types
- Update file name from `component-name.js` to `component-name.tsx` and add types
- Update file name from `component-name.test.js` to `component-name.test.tsx`
- Update file name from `component-name.stories.js` to `component-name.stories.tsx`
- Update all instances of component objects to enums
- Update all documentation 

### Acceptance Criteria
- Component has been converted to TypeScript

### PR DESCRIPTION
**Pull request by sumitshinde-84**
-->Fixes #18882

### CODE REVIEW

**Comment by sumitshinde-84** [comment]
hii @georgewrmarshall  please review this pull request .

**Review by georgewrmarshall — CHANGES_REQUESTED** [review]
Hey @sumitshinde-84, thanks for your contribution. Would you be able to check your PR against a recent PR that migrates avatar base. It seems you are missing some storybook types along with some other things https://github.com/MetaMask/metamask-extension/pull/18494. Also lint tests are failing

**Comment by georgewrmarshall** [comment]
Hey @sumitshinde-84, just wanted to check in. It looks like this PR is almost there. Did you still want to work on it? If so, that's great! Let us know if you need any assistance or if there are any blockers. If you're unable to continue working on it or haven't had a chance to address it, no worries! I can take it from here and carry it forward. Cheers!

**Comment by sumitshinde-84** [comment]
Apologies, @georgewrmarshall. I was preoccupied with my job search, but now I am fully committed to tackling it head-on. I'm determined to find a solution. Thank you for your understanding

**Comment by georgewrmarshall** [comment]
Hey @sumitshinde-84, Thanks for your time and effort in creating this pull request. We have identified an issue related to the typing of the `Box` component, specifically with the polymorphic `as` prop. To address this issue, we have an open ticket at https://github.com/MetaMask/metamask-extension/issues/19239 and a draft pull request at https://github.com/MetaMask/metamask-extension/pull/19363 that needs to be merged before we can proceed with your PR. Because this PR is 2 weeks old I am going to close it. Feel free to create another PR once the dependency issue has been resolved.

**Pull request closed without merging**
