### PR TITLE
Make `eth_accounts` return all permitted accounts

### LINKED ISSUE #18515: eth_accounts should return all permitted accounts
When we first shipped the permission system (i.e. `rpc-cap`, today known as the `PermissionController`), we made the conservative decision to make `eth_accounts` continue only returning the user's most recently selected permitted address.<sup>[1](#myfootnote1)</sup> It has always been possible for a dapp to see all of its permitted accounts by inspecting the return value of `wallet_getPermissions`, but many users have requested this behavior for `eth_accounts` over the years. We should evaluate whether this change will break any existing dapps and try to ship it.

**<a name="myfootnote1">1</a>:** Prior to the permission system, all addresses were implicitly permitted, and we always returned whichever one was selected in the UI.

**Acceptance Criteria**
Given: A dapp requests access a wallet user's accounts (by directly or indirectly calling eth_accounts)
When: The user permits the dapp to access more than one account AND the currently selected account is "A"
Then: The resulting array includes all permitted accounts with "A" as the first account in the array

**Non-functional Requirements:**
- [x] Consistent behavior of eth_accounts across Extension & Mobile
- [x] E2E Test Dapp should be updated to allow for multiple accounts in the result
- [x] Test against the top 10 Dapps
- [ ] We should coordinate developer communications around this change
- [ ] Release updated technical documentation once the change is released

NOTE: This change does not require a MIP because it fixes the existing spec

### PR DESCRIPTION
**Pull request by rekmarks**
## Explanation

It's high time we make `eth_accounts` return all permitted accounts instead of only the most recently selected one, just like the inventors of arrays intended. There are no associated UI changes. See #18515 for details.

Fixes #18515

## Manual Testing Steps

This change should not affect any functionality within the extension, but may cause unexpected breakages in dapps. We should conduct basic compatibility testing with our own e2e test dapp and the top X currently used dapps in MetaMask. We should consider shipping this change to Mobile at the same time.

## Pre-merge reviewer checklist

- [x] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [x] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Comment by vandan** [comment]
@vandan to add a developer comms plan for this update.

**Comment by vandan** [comment]
Needs corresponding Mobile PR.

**Comment by jiexi** [comment]
Accidentally deleted branch

**Comment by jiexi** [comment]
> Needs corresponding Mobile PR.

[Mobile PR here](https://github.com/MetaMask/metamask-mobile/pull/6499)

**Review by BelfordZ — APPROVED** [review]

**Review by shanejonas — APPROVED** [review]

**Pull request merged**
