### PR TITLE
Added account options on home screen

### PR DESCRIPTION
**Pull request by santteegt**
This PR covers issue #3461 requirements and includes changes that updates the home screen by adding a new drop down menu with options for account navigation. It also adds a new e2e test case to cover the UI changes.

### CODE REVIEW

**Review by whymarrh — DISMISSED** [review]
Hey @santteegt, thanks for this! Would you mind running the linter locally and fixing up the errors? (I see that `test-lint` is currently failing.)

**Comment by santteegt** [comment]
@whymarrh sorry I missed that!. Changes have been pushed. However, I'm getting unrelated errors when running the test:mascara. Is that OK?

**Review by whymarrh — APPROVED** [review]
LGTM

**Comment by whymarrh** [comment]
Thanks @santteegt!

**Pull request merged**
