### PR TITLE
remove the ui/app and ui/lib folders

### PR DESCRIPTION
**Pull request by brad-decker**
### Problem statement
Giving instructions to new engineers (or even those who have been around the block) to go to the `ui/app/components/app` folder is somewhat confusing. This would be fine to just overcome, but it also provides no real value. In fact it disjoints the file structure by implying significance of `ui/libs` over things like `ui/app/helpers` and to further complicate the matter the `ui/libs` folder had test helpers in it (some were unused) 

### Solution
Relocate all files in `ui/lib` to the most sensible destination, for most this was `ui/app/helpers/utils`. Once done, flatten the contents of `ui/app` into `ui/` making `ui/` the top level folder of the entire frontend portion of the extension.

Also, 1316 files later, I'm sorry.

### CODE REVIEW

**Comment by darkwing** [comment]
Is there a way we can do this without losing all history 😬😬😬 ?  Also, it might be good to separate the actual file moves into one commit and the config changes in another, so that rebases etc. aren't a horrible experience.

**Comment by brad-decker** [comment]
@darkwing I don't believe preserving history at the file level to be possible in all cases, but we will have the ability to see the file changes and connect the history manually. As an example the first entry for any "new" file in this PR will be the commit in this PR, which if clicked will inform the viewer of the old location. Browsing the repo at that point in history will give the rich file history while it was located in the previous place. 

Not ideal, but unfortunately obscuring file history in this way isn't avoidable in many cases. 

I did split out the configuration changes into a separate commit

**Review by darkwing — DISMISSED** [review]

**Comment by brad-decker** [comment]
Waiting for the [What's new feature](https://github.com/MetaMask/metamask-extension/pull/10583) to land before merging

**Comment by kumavis** [comment]
@brad-decker why do you think these are not being recognized as file renames?

**Comment by kumavis** [comment]
reading suggestions to prefer `git mv` when possible

**Comment by kumavis** [comment]
ohhh

> git commit never detects renames. It just writes content to the repository. Renames (and copies as well) are only detected after the fact, i.e. when running git diff, git merge and friends. That's because git does not store any rename/copy information.

https://stackoverflow.com/questions/14832963/how-can-i-control-the-rename-threshold-when-committing-files-under-git

**Comment by brad-decker** [comment]
@kumavis Thanks for the lesson! I didn't know the entire interface is just being deciphered! I won't complain about github loading slowly on my huge PRs anymore lol.

**Review by ryanml — APPROVED** [review]
great work!

**Pull request merged**
