### PR TITLE
CI - create archive of dependency sources

### PR DESCRIPTION
**Pull request by kumavis**
status: experiment

the intention of this is to create an uncorruptible record of the dependencies used to create the build

### CODE REVIEW

**Comment by kumavis** [comment]
I've created a monster

**Comment by Gudahtt** [comment]
I see what you mean about the CircleCI conditional steps being not fun. It looks like they can't take environment variables at all, so it might not be possible to use them for this kinda thing.

Maybe something like this would work instead: https://github.com/Gudahtt/metamask-extension/commit/269b6c02f242687ef78b72f93effc00f93953417
It's not pretty, but it works (I think).
I was tempted to add a `prep-deps` job that included both to avoid having to list both as requirements, but adding another stage (even a "dummy" stage with just an 'echo' like `all-tests-pass`) has a substantial performance impact.

**Comment by kumavis** [comment]
wow, uploading artifacts as tar.gz vs as files is a crazy difference
tar.gz took 2s, individual files has been running for 1+hr :astonished:

**Comment by kumavis** [comment]
@Gudahtt i think its probly best to do the conditions in shell scripts and not put too much into the circle config. one thing to note tho is that the `store_artifacts` must be in the config

**Comment by Gudahtt** [comment]
Yeah, that would probably be best. We can just store an empty `deps-archive` in the default case.

**Comment by kumavis** [comment]
need to verify if artifacts can be tampered with, not sure how they would be tho if it needs to be in the circleci config

**Comment by kumavis** [comment]
fyi archive size: yarn-cache.tar.gz (288 MB)

**Comment by kumavis** [comment]
https://github.com/MetaMask/metamask-extension/releases/edit/untagged-ce3c6d0e5aed93d4644c

you seem to be able to slap a whole 300mb into the releases page

image

**Comment by Gudahtt** [comment]
The [only limit I could](https://help.github.com/en/articles/about-releases#limitations-on-binary-files) find was 2 GB _per file_, which we're well within.

**Comment by kumavis** [comment]
lets get https://github.com/MetaMask/metamask-extension/pull/7208 merged first, then I'll update this

**Comment by whymarrh** [comment]
@kumavis did you still want to merge this?

**Comment by whymarrh** [comment]
> status: experiment

I'm closing this for now, we can re-open it when we update it

**Pull request closed without merging**
