### PR TITLE
Provider - Use Infura rest api for infura networks

### PR DESCRIPTION
**Pull request by kumavis**
Needs QA and approval of go-live before partial rollout.
I used it and it seems to work great. Quite speedy responses on `eth_call`.

Infura may make a breaking change on their end.

### CODE REVIEW

**Comment by kumavis** [comment]
relevant module bump diffs
https://github.com/MetaMask/provider-engine/commit/84ef0d4f99f162535dabcb407c3b1af722925744
https://github.com/kumavis/eth-json-rpc-infura/commit/a23532487e73657a2ca16a1a06f6553948d1035a

**Comment by kumavis** [comment]
ok to merge : )
deploy when infura is ready

**Comment by danfinlay** [comment]
In case we have other hot-fixes, I think we should not merge until we are want to deploy, at which point one last QA run should be run after the merge.

**Review by danfinlay — APPROVED** [review]
I've pulled this down, it seems to work fine!

**Comment by kumavis** [comment]
approved to slow rollout from infura

**Pull request merged**
