### PR TITLE
External accounts implemented for issue #5640

### PR DESCRIPTION
**Pull request by r001**
External acccounts allow Metamask to track account whose private keys are stored on a safe device, and tx data and signatures are exchanged by using QR codes. This allows very safe account password storage. 

This pull request enables users to create so called external accounts. This means that after applying this pull request in the "import account" menu there will be an "external" tab that enables importing an ethereum address. There is no local private key stored, but upon confirming a transaction a QR code is presented and the transaction can be signed by an external signer. And the signature can be provided in the signature input field. By providing the signature, the transaction will be signed, and published. 

The way it works is the following:
1. User creates transaction (or msg signing) and Confirms it.
2. Request goes to the background, and since the from-accunt belongs to eth-external-account-keyring, the keyrings `signTransaction()` function is called.
3. Sign transaction adds an object to eth-keyring-controller's `extToSign` array, which is monitored by the UI modal.js base component.
4. Since there is a new `extToSign` entry `ui/app/components/modals/modal.js` starts the external-sign-modal.js window, and displays QR code, and requests signature. 
5. Once signature received from user, the tx is segned normall, and handled in a standard way by Metamask.

To allow for external signatures, **eth-keyring-controller** package had to be updated, and **eth-external-account-keyring** package was created. So in the package.json my updated ones are the sources.
Eth-external-account-keyring is available at:
https://github.com/r001/eth-external-account-keyring

Install instructions for reference implementation of encoding/decoding QR code can be found at 
https://github.com/r001/qr-encoding/blob/master/INSTALL.md

Modified signer that can create appropriate signature can be found at :
https://github.com/r001/dapptools/tree/ethsign-signature
To create signature use `ethsign tx --signature-only <tx options>...`

### CODE REVIEW

**Comment by r001** [comment]
I have created pr for eth-keyring-controller to enable external signing: https://github.com/MetaMask/KeyringController/pull/29

**Comment by danfinlay** [comment]
This is a very exciting contribution, I'm looking forward to looking at it in detail soon!

**Comment by r001** [comment]
Had to rebase last changes I made, that is why I had to force push, and also tried to delete and push again.

**Comment by caffeinum** [comment]
Linking my comments to the protocol here: https://github.com/r001/qr-encoding/issues/1

The main idea: I think it could be wise to use human-readable parameters for an encoded link instead of raw bytes.

**Comment by augustoteixeira** [comment]
Sorry for the ignorance, but what is the current situation of this PR? Its status sais `closed`, does it mean it was rejected and the feature will not be included anytime soon?

**Comment by r001** [comment]
> Sorry for the ignorance, but what is the current situation of this PR? Its status sais `closed`, does it mean it was rejected and the feature will not be included anytime soon?

Hi Augusto,
This pr has been moved to:
https://github.com/MetaMask/metamask-extension/pull/6267
And it is open, and I'm working on it, and finally have an idea how to implement it in a nice way.

**Comment by augustoteixeira** [comment]
Great news!

This change will greatly improve the security of our setup here. And I am sure this will also be the case for several other teams.

**Pull request closed without merging**
