### PR TITLE
Remove usages of useMetricEvent hook

### LINKED ISSUE #13769: Remove usages of useMetricEvent hook
The useMetricEvent hook used to do more, back when the segment implementation was primarily frontend and not controller based. Now it only acts as a memoization channel and it doesn't really help engineers. In fact in many cases it is unusable as events must be fired in loop from an array of items dynamically. 

## Requirements
* In the file list section below, convert usages of the useMetricEvent hook to use the new MetaMetrics context directly from `metametrics.new.js`
* Using the below guide, translate the payloads of these methods to use the new payload parameters
* Delete the useMetricEvent hook

## Transformation guide
Matomo event structure has two positional parameters. The first is called config and is an object. The second parameter is called overrides and is an object as well. The new context for segment is a function that takes two parameters, the first is payload and the second are options.

**The following transformations apply to the payload object, or first parameter to the method**
1. `config.eventOpts.name` -> `event`
2. `config.eventOpts.category` -> `category`
3. `config.eventOpts.action` -> `properties.action`
4. `config.customVariables` -> `properties`

**These transformations apply to the options object, or second parameter. If none of the keys exist then omit the options object**
1. `config.isOptIn` -> `isOptIn`
2. `config.eventOpts.excludeMetaMetricsId` -> `excludeMetaMetricsId`
3. `overrides.excludeMetaMetricsId` -> `excludeMetaMetricsId`
4. `config.metaMetricsId` -> `metaMetricsId`
5. `config.flushImmediately` -> `flushImmediately`

**Add the following property to the properties object for events converted**
`legacy_event: true`

### Example Conversion
```js
  const selectTokenEvent = useMetricEvent({
    eventOpts: {
      category: 'Navigation',
      action: 'Token Menu',
      name: 'Clicked Token',
    },
  });

 //....

      <TokenList
        onTokenClick={(tokenAddress) => {
          onClickAsset(tokenAddress);
          selectTokenEvent();
        }}
      />
```

```js
 const trackEvent = useContext(MetaMetricsContext);

      <TokenList
        onTokenClick={(tokenAddress) => {
          onClickAsset(tokenAddress);
          trackEvent({
            event: 'Clicked Token',
            category: 'Navigation',
            properties: {
              action: 'Token Menu',
              legacy_event: true,
            }
         })
        }}
      />
```

## File List
- [ ] ui/components/app/asset-list/asset-list.js
- [ ] ui/components/app/asset-list-item/asset-list-item.js
- [ ] ui/components/app/edit-gas-display/edit-gas-display.component.js
- [ ] ui/components/app/import-token-link/import-token-link.component.js
- [ ] ui/components/app/menu-bar/account-options-menu.js
- [ ] ui/components/app/menu-bar/menu-bar.js
- [ ] ui/components/app/transaction-list-item/transaction-list-item.component.js
- [ ] ui/components/app/wallet-overview/eth-overview.js
- [ ] ui/components/app/wallet-overview/token-overview.js
- [ ] ui/pages/onboarding-flow/creation-successful/creation-successful.js
- [ ] ui/pages/send/send.js
- [ ] ui/pages/send/send-content/send-amount-row/amount-max-button/amount-max-button.js

### PR DESCRIPTION
**Pull request by VSaric**
fixes: #13769

**Explanation:**  Remove usages of `useMetricEvent` hook and convert usages to use the new MetaMetrics context directly from `metametrics.new.js`.

### CODE REVIEW

**Review by brad-decker — CHANGES_REQUESTED** [review]
These changes look good but to fully finish out this task we need to delete the useMetricEvent function from the useMetricEvent.js file

**Comment by VSaric** [comment]
> These changes look good but to fully finish out this task we need to delete the useMetricEvent function from the useMetricEvent.js file

@brad-decker Done [here](https://github.com/MetaMask/metamask-extension/pull/13930/commits/77edade14764cc895ef1233e52446c38d198aed9)

**Review by brad-decker — APPROVED** [review]
LGTM

**Review by darkwing — APPROVED** [review]

**Review by digiwand — APPROVED** [review]
🙌

**Pull request merged**
