### PR TITLE
return early from metaRPCHandler if stream has ended

### PR DESCRIPTION
**Pull request by shanejonas**
still cant reproduce locally. but i believe this could solve `write after end`.

### CODE REVIEW

**Review by Gudahtt — DISMISSED** [review]
LGTM! I suspect that this will address https://sentry.io/organizations/metamask/issues/2394407935/.

It would be great to have this covered by a unit test too.

**Comment by Gudahtt** [comment]
I think there is still one outstanding `write after error` case that will require a similar change to be made in `metamask-controller`: https://sentry.io/organizations/metamask/issues/2394666692/

**Review by rekmarks — COMMENTED** [review]
Nice!!

**Review by rekmarks — APPROVED** [review]
LGTM!

I'd recommend that we use [`duplex.writableEnded`](https://nodejs.org/api/stream.html#stream_writable_writableended), but the stream implementation we use emulates a Node version well before that property was introduced. (Specifically, our version of `readable-stream` emulates Node 8, while the `writableEnded` property was introduced in Node 12.)

**Review by rekmarks — CHANGES_REQUESTED** [review]
Although, per @Gudahtt's suggestion, should we just include an early return here as well? https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/metamask-controller.js/#L2049-L2057

**Review by rekmarks — APPROVED** [review]
LGTM!

**Pull request merged**
