### PR TITLE
Shortcut to open MetaMask

### PR DESCRIPTION
**Pull request by 2-am-zzz**
It's `Ctrl + M` for most people, or `Command + M` for the Mac folk!

### CODE REVIEW

**Comment by flyswatter** [comment]
On a mac, `command-M` usually minimizes a window, so this would be overriding an OS-level behavior, which I'm not really huge on.. If we're going to add a shortcut to the browser, I'd like us to have a reasoned justification for the key we choose.

One way to get a little more safely off the heavily tread path is to add additional modifier keys, like command-option-M/command-alt-M. On a mac, that seems to also only minimize a single window, so it would be no extra loss.

**Comment by Zanibas** [comment]
What about `Alt + M`?

**Comment by flyswatter** [comment]
Usually the option key on mac just modifies a typed key when used by itself, for special characters.

For example, `opt-M` on a mac creates the µ (micro) symbol. To fit into the mac paradigm it should have at least one ctrl or command key, plus either alt or shift, or just pick a combination that really isn't popular (I'm not sure the best way to start that research).

**Comment by Zanibas** [comment]
Shortcuts are hard man. Hmmm, then let's settle on this:
`Win: Ctrl+Alt+M`
`Mac: Command+Opt+M`
etc etc.

**Comment by flyswatter** [comment]
Yeah I'm ok with that
# FOR NOW!!!

**Pull request merged**
