### PR TITLE
Implement Mascara First Time Flow

### PR DESCRIPTION
**Pull request by chikeichan**
[Last Updated: September 27, 2017]

Progress:
- [x] Create Password Screen- UI
- [x] Create Password Screen- Integration
- [x] Import Account Screen- UI
- [x] Import Account Screen- Integration
- [x] Secure Image Screen
- [x] Terms and Condition Screen
- [x] Terms and Condition -- disable CTA until scrolled to bottom
- [x] Backup Phrase Screen - UI
- [x] Backup Phrase Screen - Integration
- [x] Backup Phrase Screen -- randomize token
- [x] Buy Ether Screen Screen - UI
- [x] Buy Ether Screen Screen - Coinbase Integration
- [x] Buy Ether Screen Screen - Shapeshift Integration (pending design)
- [x] Move "Skip This Step" in Buy Ether screen to side panel

### CODE REVIEW

**Comment by chikeichan** [comment]
*Core FTUE Flow*
ftue

*Buy Ether*
import

*Import Account*
buyether

**Comment by Zanibas** [comment]
This will fail our CI tests no matter what--should we use this as a good time to write our first integration test?

**Comment by Zanibas** [comment]
Wait, it's passing?

**Comment by chikeichan** [comment]
@Zanibas Yep i added new integration tests for new first time flow. It was breaking due to another issue on master.

**Comment by frankiebee** [comment]
@chikeichan This all looks supper great!!

**Comment by frankiebee** [comment]
Can I get another pair of eyes on this though as far as review maybe @Zanibas

**Review by frankiebee — APPROVED** [review]

**Comment by frankiebee** [comment]
@tmashuang can I get qa on this?

**Comment by tmashuang** [comment]
When importing an incorrect seed phrase there is no error in the UI, just in the console.

**Review by tmashuang — APPROVED** [review]
Added error handling messages for seed phrase and password validation on click. Disabling the button when there is an issue leaves the user worried and no clear indication of where the issue originated. Error handling does need design for the future, but for now this should help. I was thinking of adding it to the backup seed phrase screen, but there really is only one error that users can come across on the screen. Will be nice to see how users response to the button disabling on initial release as well.

**Pull request merged**
