### PR TITLE
Update token cell to show inline stale balance warning

### PR DESCRIPTION
**Pull request by Gudahtt**
The token cell how shows a warning inline for the case where the token balance failed to update. It displays a warning icon next to the balance, with a tooltip that contains the same contents as was shown on the token list previously.

This was roughly modelled after the ["Wallet home (full-screen)" Figma design](https://www.figma.com/file/b8U583mpXW1FsPWfGFNT8C/Wallet-home-(full-screen)?node-id=0%3A1). It doesn't match exactly yet though of course, as that design includes moving the token list into a tab. The rest of the design will come in follow-up PRs.

### CODE REVIEW

**Comment by Gudahtt** [comment]
<details>
<summary>Screenshots:</summary>

Old design:
old-stale-balances

New design:
new_stale

New design with tooltip:
stale_with_tooltip

</details>

**Comment by whymarrh** [comment]
> The token cell how shows a warning inline for the case where the token balance failed to update.

Is this "where **any** token balance failed to update"? Is this a list-global error rendered alongside each token balance?

**Review by danjm — APPROVED** [review]
code looks good to me

**Comment by Gudahtt** [comment]
>Is this "where any token balance failed to update"? Is this a list-global error rendered alongside each token balance?

Yes, that is correct. The token tracker doesn't currently all distinguishing _which_ token failed when a failure does occur. That would be nice though. It's something we should consider in future API changes to the token tracker.

**Review by whymarrh — APPROVED** [review]
LGTM!

**Pull request merged**
