### PR TITLE
chore: update Trezor Connect to v9.4.0, remove workarounds

### PR DESCRIPTION
**Pull request by martykan**
## **Description**

With MV3, MetaMask started to use Trezor Connect inside an offscreen environment, in a way that was previously unsupported and required a workaround by patching the Trezor Connect library. 

In recent versions of Trezor Connect, the library can handle working in an offscreen environment correctly, without the need for the workaround, which could cause issues with compatibility. 

This PR removes the patch and updates the Trezor Connect library to the latest version (v9.4.0). 
The change in `manifest.json` is due to new URL parameters, Firefox needs the asterisk at the end to match the URL with them. 
I haven't removed the WebUSB device request which was added on MetaMask's side in relation to the workaround, since it can improve UX of the pairing process, but it could be removed if desired.   

The dependency update affects Lavamoat, I am including the policy changes in my commit, however let me know if you would like me to remove them and handle them using your own process. 

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/26749?quickstart=1)

## **Related issues**

NA

## **Manual testing steps**

1. Open accounts dropdown, "Add hardware wallet"
2. Select Trezor
3. Follow prompts to connect the device
4. See a list of accounts from the Trezor

## **Screenshots/Recordings**

NA

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by chloeYue** [comment]
Test OK for Trezor connection on this PR branch:

https://github.com/user-attachments/assets/712838ba-aa50-4312-a7dc-f0efda933317

**Review by vthomas13 — DISMISSED** [review]
Tested on 12.0.6. Works great! Thanks a lot @martykan

**Comment by martykan** [comment]
Ok, I've updated it. There seem to be some failing checks, I don't think I can affect those.

**Comment by vthomas13** [comment]
Hey @martykan, we are working to get this reviewed internally as a workaround to a CI step that is failing for external contributors. Really appreciate your patience on this!

**Comment by danjm** [comment]
Thanks again for the contribution! This PR was re-opened as https://github.com/MetaMask/metamask-extension/pull/27112 to workaround some issues we are currently having with CI and forks, and that PR has been closed.

**Pull request closed without merging**
