### PR TITLE
[Bug]: Balance does not update on duplicate chainId network #13690

### LINKED ISSUE #13690: [Bug]: Balance does not update on duplicate chainId network
### Describe the bug

The balance of an account won't update if the network selected has a chainId that is already present in Metamask.

### Steps to reproduce

1. run `ganache-cli --chainId 3 -d -m "worker"`
2. import private key "ce15110096297c533cccdeb27499126d9b45fbfe98e1d96178dfbe989d76810d"
3. create network in metamask: chainId 3, RPC url: http://localhost:8545
4. Balance stays 0, repeat with unused chainId -> Balance 100

### Error messages or log output

_No response_

### Version

10.9.3

### Build type

_No response_

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by dragana8**
## Explanation

Currently, the balance of an account won't update if the network selected has a chainId that is already present in Metamask. That happens because in account-tracker.js there is a check for chainId and if it belonged to known networks ( as in this case it was Ropsten network) it called the method that checked balance on Ropsten network and not localhost as it should.

In order to solve this problem, I added if statement that checks if rpcUrl is localhost and in that case the right method (updateBalance) is being called.

## More information

* Fixes #13690

### Before

Screenshot 2022-03-29 at 13 00 34

### After

Screenshot 2022-03-29 at 12 32 47

### CODE REVIEW

**Comment by mirjanaKukic** [comment]
Verified by QA

**Review by segun — DISMISSED** [review]
LGTM

**Review by brad-decker — DISMISSED** [review]

**Comment by brad-decker** [comment]
@dragana Could you rebase this please and fix conflicts? we'll get it landed after that

**Review by Ellajoke — DISMISSED** [review]

**Comment by dragana8** [comment]
@brad-decker done

**Review by brad-decker — DISMISSED** [review]

**Review by NiranjanaBinoy — DISMISSED** [review]
Changes look good to me, this PR can be merged once it is rebased.

**Review by brad-decker — APPROVED** [review]
I rebased the pr for @dragana8, please reapprove when ready!

**Review by NiranjanaBinoy — APPROVED** [review]

**Pull request merged**
