### PR TITLE
Update `@metamask/eth-ledger-bridge-keyring`

### LINKED ISSUE #21144: Update `@metamask/eth-ledger-bridge-keyring`
We should use the latest version of `@metamask/eth-ledger-bridge-keyring`, as it brings improvements needed for MV3 compatibility.

### PR DESCRIPTION
**Pull request by mikesposito**
## **Description**
This PR updates the `@metamask/eth-ledger-bridge-keyring` version to latest (`^1.0.0`).
This brings a major breaking change: the transport logic (the way Metamask connects to the device) has been split from the keyring logic (the interface supported by our KeyringController).

Due to this, `@metamask/eth-ledger-bridge-keyring` needs a transport bridge to be passed on construction and successively initialized calling `Keyring.init()`. 

As this is a new behavior compared to the usual way we build keyrings, we have to use a different keyring builder factory, specific for this kind of "bridged keyring". That is, a keyring that needs a bridge class instance as a constructor option.

The bridge initialization is, instead, done outside the keyring builder (as it is async).

**Note**
Test coverage for hardware wallets is insufficient: I did some manual smoke tests with my Ledger Nano X (account unlock, send eth transaction sign), but this likely needs additional QA

## **Related issues**

* Fixes #21144 

## **Manual testing steps**

- Connect a new Ledger hardware wallet 
- Signing transaction should work as before

### **Before**

n/a

### **After**

n/a

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained:
  - [x] What problem this PR is solving.
  - [x] How this problem was solved.
  - [x] How reviewers can test my changes.
- [x] I’ve indicated what issue this PR is linked to: Fixes #???
- [x] I’ve included tests if applicable.
- [x] I’ve documented any added code.
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)).
- [x] I’ve properly set the pull request status:
  - [x] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by mikesposito** [comment]
Waiting for #21145

**Comment by brad-decker** [comment]
@mikesposito could we update this to upgrade to 2.0.0 that was released recently?

**Comment by mikesposito** [comment]
@metamaskbot update-policies

**Review by brad-decker — DISMISSED** [review]

**Comment by Gudahtt** [comment]
Ah interesting. That's something we hadn't considered in that update command. Maybe a good idea to update it to sequence the build policy update first, before the webapp policies.

**Comment by mcmire** [comment]
@metamaskbot update-policies

**Comment by mcmire** [comment]
I've updated this branch, but it looks like we're getting an audit error now that `@metamask/snaps-ui` is deprecated. We'll have to fix that first before merging this.

**Review by mcmire — DISMISSED** [review]
Makes sense to me.

**Review by kumavis — CHANGES_REQUESTED** [review]
This will cause a known compatibility issue

issue:
https://github.com/MetaMask/eth-sig-util/issues/340
https://github.com/MetaMask/metamask-mobile/issues/7792

fix (merged, awaiting release):
https://github.com/MetaMask/eth-sig-util/pull/354

releases:
v7 https://github.com/MetaMask/eth-sig-util/pull/355
v6 https://github.com/MetaMask/eth-sig-util/pull/357

thanks to @legobeat for bringing to my attention

**Comment by mcmire** [comment]
Sounds like we need to ensure that `@metamask/eth-sig-util` is bumped to 7.0.1 in `yarn.lock`, yes?

**Comment by mikesposito** [comment]
@metamaskbot update-policies

**Review by legobeat — APPROVED** [review]

**Review by kumavis — APPROVED** [review]

**Pull request merged**
