### PR TITLE
MV3: support Service Worker restart for phishing warning pages

### LINKED ISSUE #15987: MV3: Support dapp phishing warning page
### Describe the bug

This support should piggyback off the support we have for dapp pages.

Update logic to only trigger 45 minute keep alive logic on load.

### Error messages or log output

_No response_

### Version

10.19.x

### Build type

_No response_

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### LINKED ISSUE #16448: [Bug]: [MV3] Phishing detection stops working after service worker re-start
### Describe the bug

**Problem**: if I terminate the MM service worker, and I go to a phishing page, the phishing detection stops working and I land into the malicious page, instead of on the phishing warning page.

https://user-images.githubusercontent.com/54408225/201068403-4441aeb6-47d6-4df2-9174-ff434e6cf767.mp4

See comment here:
https://github.com/MetaMask/metamask-extension/pull/16075#issuecomment-1308557521

### Steps to reproduce

1. Load MM
2. Open a malicious page: https://ethereum-mask.com/ -- see that you are redirected to MM Phishing Detection
3. Close the malicious page
4. Terminate MM service worker
5. Open a malicious page: https://ethereum-mask.com/ -- see that now you land into the malicious page

### Error messages or log output

_No response_

### Version

https://github.com/MetaMask/metamask-extension/pull/16075

### Build type

_No response_

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by digiwand**
## Explanation

- Fix bug and add support to enable service worker to reload while using phishing streams (Fixes #16448)
- Only keep service worker alive on load (Fixes #15987) 

**Note:** There is an issue with the phishing warning detection which is out of scope of this PR: https://github.com/MetaMask/metamask-extension/issues/16551

> [@seaona](https://github.com/seaona) observed refreshing the extension from chrome://extensions and then opening a URL detected as a phishing page will not show the phishing warning page.
>
> Looking into this, it appears that the blocklist may not finish loading when the user first lands on a detected phishing page.

### Before

Screen Shot 2022-11-14 at 23 46 40

### After

Screen Shot 2022-11-14 at 23 55 05

## Manual Testing Steps

Steps to reproduce
- Load MM
- Open a malicious page: https://ethereum-mask.com/ -- see that you are redirected to MM Phishing Detection
- Restart the service worker
- Click on "continuing at your own risk." to be redirected to the malicious site
- Open the malicious page: https://ethereum-mask.com/ again and notice that you will go directly to the malicious site. This means that the service restart is working because after clicking "continuing at your own risk.",  the site is saved to the allowlist/safelist of the wallet. 
- To repro, use a different wallet without the malicious page in the allowlist/safelist

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [x] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [x] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [x] PR is linked to the appropriate GitHub issue
- [x] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Comment by darkwing** [comment]
Needs rebase

**Comment by digiwand** [comment]
@darkwing thank you and done 👍

**Comment by seaona** [comment]
This PR looks good from QA @digiwand. I've checked and it fixes [this issue](https://github.com/MetaMask/metamask-extension/issues/16448). 
Small note [already discussed]: the issue above was occurring without the step of clicking `Continue at your own risk`.

**Comment by digiwand** [comment]
Thanks @seaona! I updated the description to mention this PR does fix the bug you reported as well

**Review by darkwing — APPROVED** [review]
Works as described!

**Review by brad-decker — APPROVED** [review]

**Comment by digiwand** [comment]
Thanks for the reviews! 🙏

**Pull request merged**
