### PR TITLE
refactor: Bump `@metamask/providers` to `^16.0.0`.  Remove deprecated networkId

### PR DESCRIPTION
**Pull request by jiexi**
## **Description**

This PR bumps the `@metamask/providers` version, which removes properties that are not officially documented and should not have been exposed in the first place. It also removes support for the networkChange event and offline net_version resolution which will allow us to remove the last remaining chunk of networkId usage in Extension. These have all been properly deprecated, the most recent deprecations being 180 days old now.

Removes the following:
- window.ethereum.chainId
- window.ethereum.networkVersion
- window.ethereum.selectedAddress
- networkChanged event
- offline net_version support in window.ethereum.send()
- networkId resolution inside MetaMaskController

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/23375?quickstart=1)

## **Related issues**

See: https://github.com/MetaMask/MetaMask-planning/issues/2195
See: https://github.com/MetaMask/metamask-improvement-proposals/discussions/23
See: https://github.com/MetaMask/MetaMask-planning/issues/2176
See: https://github.com/MetaMask/providers/pull/306

## **Manual testing steps**

1. Open a dapp
2. Connect to the dapp
3. In dapp web console, check the values of 
  - `window.ethereum.chainId`: should throw
  - `window.ethereum.selectedAddress`: should throw
  - `window.ethereum.networkVersion`: should be undefined
4. Open background extension network tab
  - in the dapp web console, `window.ethereum.send({method: 'net_version'}, console.log)`: should result in a network request to the rpc endpoint as this is no longer resolved locally/cached
5. In the dapp web console
  - `window.ethereum.on('networkChanged', console.log)`
  - In the wallet UI, switch networks
  - nothing should be logged

### **Before**

Screenshot 2024-03-07 at 10 16 08 AM

### **After**

Screenshot 2024-03-07 at 10 23 54 AM

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by adonesky1** [comment]
what is meant by 
> offline net_version support in window.ethereum.send()
?

**Comment by jiexi** [comment]
`ethereum.send()` previously resolved `net_version` requests without hitting the actual rpc endpoint (or even the wallet json rpc engine itself) by using a local cached value. Now it always sends a request to the wallet json rpc engine since this value is no longer persisted in the Provider instance

**Review by BelfordZ — DISMISSED** [review]

**Comment by BelfordZ** [comment]
meant to approve the other pr haha but still nice work!

**Comment by jiexi** [comment]
@metamaskbot update-policies

**Comment by jiexi** [comment]
@metamaskbot update-policies

**Comment by jiexi** [comment]
iceboxing this

**Pull request closed without merging**
