### PR TITLE
Replaced deprecated Callout component with BannerAlert from the compo…

### PR DESCRIPTION
**Pull request by subhajit20**
…nent-library

## **Description**
Replaced deprecated Callout component with BannerAlert from the component-library
Issue - #20470 

Before
Before 2023-10-10 at 7 27 08 PM

After
after 2023-10-10 at 7 23 52 PM

_Write a short description of the changes included in this pull request, also include relevant motivation and context. Have in mind the following questions:_
_1. What is the reason for the change?_
_2. What is the improvement/solution?_

## **Manual testing steps**

_1. Step1:_
_2. Step2:_
_3. ..._

## **Screenshots/Recordings**

_If applicable, add screenshots and/or recordings to visualize the before and after of your change._

### **Before**

_[screenshot]_

### **After**

_[screenshot]_

## **Related issues**

_Fixes #???_

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained:
  - [ ] What problem this PR is solving.
  - [ ] How this problem was solved.
  - [ ] How reviewers can test my changes.
- [ ] I’ve indicated what issue this PR is linked to: Fixes #???
- [ ] I’ve included tests if applicable.
- [ ] I’ve documented any added code.
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)).
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by georgewrmarshall — COMMENTED** [review]
Hey @subhajit20, could you please add the before and after screenshots and manual testing steps otherwise I'm afraid this PR will be closed

**Comment by subhajit20** [comment]
hey @georgewrmarshall  are those above screen shots relevant?

**Review by georgewrmarshall — CHANGES_REQUESTED** [review]
Hey @subhajit20, no, these screenshots are not relevant you may have to create a storybook file if you cannot replicate it. We are looking for the UI that renders these alerts so we can check for visual regression and make sure they look as intended. I traced the last updates to this PR https://github.com/MetaMask/metamask-extension/pull/10310 you could try to follow the manual testing steps here. @brad-decker do you have any suggestions on how we could render the alert UI here?

**Comment by subhajit20** [comment]
> Hey @subhajit20, no, these screenshots are not relevant you may have to create a storybook file if you cannot replicate it. We are looking for the UI that renders these alerts so we can check for visual regression and make sure they look as intended. I traced the last updates to this PR #10310 you could try to follow the manual testing steps here. @brad-decker do you have any suggestions on how we could render the alert UI here?

Okay let me check

**Pull request closed without merging**
