### PR TITLE
Feature/tx decoding

### PR DESCRIPTION
**Pull request by alaahd**
Fixes: #

Explanation:  

Manual testing steps:  
  - 
  - 
  -

### CODE REVIEW

**Comment by danjm** [comment]
leaving this as a draft for now as I still need to solve the issue with the decoder dependency

**Comment by danjm** [comment]
oh, I see that was resolved in the `decoder` repo itself

**Comment by darkwing** [comment]
Unfortunately we need a large rebase here.

**Comment by danjm** [comment]
closing in favour of https://github.com/MetaMask/metamask-extension/pull/12881

**Pull request closed without merging**
