### PR TITLE
Prevent external domains from submitting more than one perm request at once

### PR DESCRIPTION
**Pull request by rekmarks**
### Summary

- Return an error if an external domain requests permissions while they already have a pending permissions request

### Details

I haven't fully decided whether we should do this. Are there legitimate uses for multiple permission requests submitted at once?

Related: #7969 (whichever is merged last will have to be rebased and updated with new tests)

### CODE REVIEW

**Comment by Gudahtt** [comment]
>Are there legitimate uses for multiple permission requests submitted at once?

Huh, interesting point 🤔. Maybe? It's conceivable that once we start adding more permissions, a dapp might allow the user to request them one-by-one in the dapp, thus triggering separate permission requests.

**Comment by rekmarks** [comment]
> It's conceivable that once we start adding more permissions, a dapp might allow the user to request them one-by-one in the dapp, thus triggering separate permission requests.

Good point. We probably shouldn't restrict that without good reason. If we merge this, we should add an issue making sure that only e.g. duplicate `eth_requestAccounts` requests are rejected (that being the one that's probably most likely to get spammed).

**Comment by danfinlay** [comment]
I kinda like it just because it would fundamentally simplify the process of keeping the approval prompt safe. Devs will build interfaces that work well with our approval system, so we can simply avoid the scenario Mark suggested by merging this.

**Comment by rekmarks** [comment]
@danfinlay I think the case Mark described warrants an issue and further discussion (we already talked about it some), but I do agree that this should be merged for now regardless!

**Comment by Gudahtt** [comment]
I think I've come around to this idea - it would definitely be simpler. And if we impose this restriction from the start, dapps will be forced to accommodate it.

If we do allow multiple requests to be pending at once, then that raises the question of how to deal with "corrections", or requests that supersede previous ones. That would be a complex flow to handle; if we do nothing, then the user might customize permissions to their liking on the first request, then not remember what the chose the second time they're asked (i.e. we'd want to go the extra mile to show what's _changing_ in order to help the user understand what's going on). If we try to merge the requests, then we risk things updating while the user is reviewing, which is dangerous. We could issue an alert, but that would be clunky.

Far simpler to disallow it altogether.

**Review by Gudahtt — APPROVED** [review]
LGTM!

**Review by danjm — APPROVED** [review]

**Pull request merged**
