### PR TITLE
fix: Revert gridplus sdk version bumps

### PR DESCRIPTION
**Pull request by danjm**
## **Description**

This PR reverts #27973 and #28008, and then forces an secp256k1 resolution to deal with a yarn audit failure. This is necessary to fix typed message signing with the lattice gridplus hardware wallet.

All of this had been done on release branches and master in the past, when it should have been done directly on develop.

We do want to restore the #27973 and #28008 changes soon, but that requires getting to root of why those changes result in typed message signing failure with lattice griduplus

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/29125?quickstart=1)

## **Related issues**

Fixes:

## **Manual testing steps**

Test "Sign Typed Message" v4 in the test dapp with a gridplus hardware wallet. It should succeed without error

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by danjm** [comment]
@metamaskbot update-policies

**Comment by danjm** [comment]
@metamaskbot update-policies

**Comment by danjm** [comment]
@SocketSecurity ignore-all

The new author is known and cryptographic operations within the gridplus sdk are to be expected

**Comment by danjm** [comment]
@metamaskbot update-policies

**Comment by vivek-consensys** [comment]
Working as expected, tested by completing sign transactions using test-dapp. 
See recording here: 

https://github.com/user-attachments/assets/e6e2e76f-c65c-4ccb-85c9-406c673612f8

**Review by Akaryatrh — APPROVED** [review]

**Review by gantunesr — APPROVED** [review]

**Pull request merged**
