### PR TITLE
Deduplicate dependencies in lockfile

### PR DESCRIPTION
**Pull request by kumavis**
yarn does not automatically dedupe deps. this is prolly why it merges with so few conflicts.

this diff was generated with `npx yarn-deduplicate --strategy highest` 
look at that `yarn.lock` diff! `+305 −2,060`

- :lock: does not introduce new package versions
- :rocket: should improve bundle size
- :thinking: surprisingly little improvement in dep install time 
- :warning: likely will cause merge conflicts with any existing PRs
- :snail: we will need to do this every once and awhile

### CODE REVIEW

**Comment by kumavis** [comment]
should improve bundle size

**Comment by rekmarks** [comment]
Marking as `DONOTMERGE`, per @kumavis comments elsewhere.

**Comment by kumavis** [comment]
fine to merge but it will cause conflicts with existing PRs

**Comment by rekmarks** [comment]
It can be merged if we want it!

**Comment by kumavis** [comment]
@danfinlay asked me to come up with instructions for how to de-conflict yarn.lock in other PRs after this is merged
we determined that simply running the deduplicate command listed at the top comment of this PR should resolve the conflict as the result is deterministic

**Comment by danjm** [comment]
@kumavis Given the conflicts, you might want to update this PR by rerunning the command on latest develop and force pushing the results

**Comment by danjm** [comment]
The one commit in this PR was generated by:
- running `npx yarn-deduplicate --strategy highest` on latest develop
- running `yarn`

A regression test of key features (sending, swapping, adding and removing tokens, importing accounts) was successful

**Comment by danjm** [comment]
This PR has been rebased and updated

**Review by Gudahtt — APPROVED** [review]
LGTM! Diff looks to be about what I'd expect, and it seems to work locally.

**Comment by kumavis** [comment]
thanks/ @danjm  @Gudahtt

**Pull request merged**
