### PR TITLE
Version v12.3.0

### PR DESCRIPTION
**Pull request by danjm**

### CODE REVIEW

**Comment by benjisclowder** [comment]
Hi, teams! We can start testing and validating v12.3.0. Let's do this! :rocketship:

**Instructions for Team Review**

**Review Changes**: Refer to the [Release Tracker for v12.3.0](https://docs.google.com/spreadsheets/d/1tsoodlAlyvEUpkkcNcbZ4PM9HuC9cEM80RZeoVv5OCQ/edit?gid=1626676623#gid=1626676623) to see all changes relevant to your team. _Please mark your team's **Non functional/No risk** changes accordingly and **Skip** validation on these if needed._ 

**Log Bugs**: If you find any issues, log them in the release tracker and attach them to the [bug report](https://github.com/MetaMask/MetaMask-planning/issues/2893).

**Approval**: After reviewing, indicate your team's approval by:

- Marking the checkbox next to your team's name in this comment.

- Optionally, leave a comment for additional information.

Your thorough review ensures a smooth and successful release. If you have any questions please reach out to extension platform team or in the [#metamask-qa](https://consensys.slack.com/archives/C01U65ZUS2E) slack channel. Thank you for your collaboration!


 

- [ ] Accounts: @gantunesr  - There are 17 Accounts changes in v12.3.0

- [ ]  Assets: @sahar-fehri  / @alfeng6  - There are 21 Assets changes in v12.3.0

- [ ]  Bridge: @micaelae - There are 7 Bridge changes in v12.3.0

- [ ]  Confirmations: @sleepytanya / @cryptotavares - There are 30 Confirmations changes in v12.3.0.

- [ ]  Design/System: @georgewrmarshall - There are 17 Design/System change in v12.3.0.

- [ ]  Hardware Wallets: @gantunesr  - There is 1 Hardware Wallets change in v12.3.0.

- [ ]  Lavamoat: @legobeat - There are 2 Lavamoat changes in v12.3.0

- [ ]  MMI: @zone-live / @shane-t - There are 12 MMI changes in v12.3.0.

- [ ]  Notifications: @Prithpal-Sooriya / @matteoscurati - There are 10 Notifications changes in v12.3.0

- [ ]  Portfolio: @julesat22 - There is 1 Portfolio change in v12.3.0

- [ ]  Snaps: @bowensanders / @FrederikBolding / @Montoya - There are 12 Snaps changes in v12.3.0.

- [ ]  Swaps: @davibroc - There are 2 Swaps changes in v12.3.0.

- [ ]  Transactions: @dbrans - There are 4 Transactions changes in v12.3.0.

- [ ]  Wallet Framework: @Gudahtt - There are 22 Wallet Framework changes in v12.3.0.

- [ ]  Wallet UX: @darkwing / @NidhiKJha - There are 6 Wallet UX changes in v12.3.0.

- [ ]  Wallet API: @adonesky1 - There are 4 Wallet API changes in v12.3.0

**Comment by benjisclowder** [comment]
[Manual test scenarios:](https://github.com/MetaMask/metamask-extension/tree/develop/test/manual-scenarios)

**Chrome:**

- [ ] Onboarding - create a wallet
- [ ] Onboarding - import a wallet
- [ ] Keyring - connect hardware wallet
- [ ] Keyring - reset a wallet
- [ ] Keyring - Import account using private key
- [ ] Transactions - send native token origin MM
- [ ] Transactions - send native token origin dapp
- [ ] Transactions - send ERC20 token origin MM
- [ ] Transactions - send ERC20 token origin dapp
- [ ] Transactions - send ERC721 token origin MM
- [ ] Transactions - send ERC721 token origin dapp
- [ ] Transactions - speed up transaction
- [ ] Transactions - cancel transaction
- [ ] Transactions - deploy failing transaction
- [ ] Transactions - deposit and withdraw
- [ ] Transactions - navigate multiple transactions
- [ ] Transactions - send transactions with custom nonce
- [ ] Transactions - cancel transaction using same nonce
- [ ] Tokens - import ERC20 token origin MM
- [ ] Tokens - import ERC20 token origin dapp
- [ ] Tokens - import ERC721 token origin MM
- [ ] Tokens - import ERC721 token origin dapp
- [ ] Tokens - import ERC1155 token origin MM
- [ ] Tokens - import ERC1155 token origin dapp
- [ ] Tokens - approve ERC1155 token
- [ ] Tokens - approve ERC20 token
- [ ] Tokens - approve ERC721 token
- [ ] Tokens - autodetect tokens
- [ ] Tokens - autodetect NFTs
- [ ] Tokens - approve erc20 custom amount
- [ ] ENS - name resolution
- [ ] Phishing - warning page
- [ ] Network - add custom network manually
- [ ] Network - add custom network from the list of popular networks
- [ ] Network - add custom network from dApp
- [ ] Network - update networks
- [ ] Network - switching networks
- [ ] Network - delete networks from the dropdown list
- [ ] Network - delete networks in Settings
- [ ] Backup - backup user data
- [ ] Metrics - send event metrics
- [ ] Address-book - add a contact to the address book
- [ ] Address-book - remove a contact from the address book
- [ ] Address-book - update a contact in the address book
- [ ] Gas fee - EIP-1559 gas
- [ ] Gas fee - legacy gas
- [ ] Sign - personal sign
- [ ] Sign - sign in with ethereum
- [ ] Sign - sign typed with data
- [ ] Sign - sign typed data v3 with hardware wallet
- [ ] Sign - sign typed data v4 with hardware wallet
- [ ] Sign - personal sign with hardware wallet
- [ ] Permissions - connecting and disconnecting from a dapp
- [ ] Swap - smart swap
- [ ] Swap - swap eth
- [ ] Security - stop network polling
- [ ] Incoming transactions - receive native token
- [ ] Settings - about metamask - ui validation
- [ ] Settings - general - change language
- [ ] Settings - advanced - check custom nonce toggle
- [ ] Settings - advanced - show hex data
- [ ] Settings - advanced - show test networks
- [ ] Contract - deploy contract, mint and import NFT with hardware wallet
- [ ] Contract - hardware wallet qr based connect
- [ ] Contract - send token with hardware wallet
- [ ] Privacy - Check “network details check” toggle works correctly
- [ ] Privacy - Check “IPFS gateway” toggle works correctly
- [ ] Privacy - Check “Show ENS domains in address bar” toggle works correctly
- [ ] Privacy - Check “Display NFT Media” toggle works correctly

**Firefox:** 

- [ ] Onboarding - create a wallet
- [ ] Onboarding - import a wallet
- [ ] Keyring - connect hardware wallet
- [ ] Keyring - reset a wallet
- [ ] Keyring - Import account using private key
- [ ] Transactions - send native token origin MM
- [ ] Transactions - send native token origin dapp
- [ ] Transactions - send ERC20 token origin MM
- [ ] Transactions - send ERC20 token origin dapp
- [ ] Transactions - send ERC721 token origin MM
- [ ] Transactions - send ERC721 token origin dapp
- [ ] Transactions - speed up transaction
- [ ] Transactions - cancel transaction
- [ ] Transactions - deploy failing transaction
- [ ] Transactions - deposit and withdraw
- [ ] Transactions - navigate multiple transactions
- [ ] Transactions - send transactions with custom nonce
- [ ] Transactions - cancel transaction using same nonce
- [ ] Tokens - import ERC20 token origin MM
- [ ] Tokens - import ERC20 token origin dapp
- [ ] Tokens - import ERC721 token origin MM
- [ ] Tokens - import ERC721 token origin dapp
- [ ] Tokens - import ERC1155 token origin MM
- [ ] Tokens - import ERC1155 token origin dapp
- [ ] Tokens - approve ERC1155 token
- [ ] Tokens - approve ERC20 token
- [ ] Tokens - approve ERC721 token
- [ ] Tokens - autodetect tokens
- [ ] Tokens - autodetect NFTs
- [ ] Tokens - approve erc20 custom amount
- [ ] ENS - name resolution
- [ ] Phishing - warning page
- [ ] Network - add custom network manually
- [ ] Network - add custom network from the list of popular networks
- [ ] Network - add custom network from dApp
- [ ] Network - update networks
- [ ] Network - switching networks
- [ ] Network - delete networks from the dropdown list
- [ ] Network - delete networks in Settings
- [ ] Backup - backup user data
- [ ] Metrics - send event metrics
- [ ] Address-book - add a contact to the address book
- [ ] Address-book - remove a contact from the address book
- [ ] Address-book - update a contact in the address book
- [ ] Gas fee - EIP-1559 gas
- [ ] Gas fee - legacy gas
- [ ] Sign - personal sign
- [ ] Sign - sign in with ethereum
- [ ] Sign - sign typed with data
- [ ] Sign - sign typed data v3 with hardware wallet
- [ ] Sign - sign typed data v4 with hardware wallet
- [ ] Sign - personal sign with hardware wallet
- [ ] Permissions - connecting and disconnecting from a dapp
- [ ] Swap - smart swap
- [ ] Swap - swap eth
- [ ] Security - stop network polling
- [ ] Incoming transactions - receive native token
- [ ] Settings - about metamask - ui validation
- [ ] Settings - general - change language
- [ ] Settings - advanced - check custom nonce toggle
- [ ] Settings - advanced - show hex data
- [ ] Settings - advanced - show test networks
- [ ] Contract - deploy contract, mint and import NFT with hardware wallet
- [ ] Contract - hardware wallet qr based connect
- [ ] Contract - send token with hardware wallet
- [ ] Privacy - Check “network details check” toggle works correctly
- [ ] Privacy - Check “IPFS gateway” toggle works correctly
- [ ] Privacy - Check “Show ENS domains in address bar” toggle works correctly
- [ ] Privacy - Check “Display NFT Media” toggle works correctly

**Comment by garrettbear** [comment]
@MetaMask/design-system-engineers  PRs Confrmed 

- [x] https://github.com/MetaMask/metamask-extension/pull/25638
- [x] https://github.com/MetaMask/metamask-extension/pull/25553
- [x] https://github.com/MetaMask/metamask-extension/pull/25551
- [x] https://github.com/MetaMask/metamask-extension/pull/26031
- [x] https://github.com/MetaMask/metamask-extension/pull/25557
- [x] https://github.com/MetaMask/metamask-extension/pull/26069
- [x] https://github.com/MetaMask/metamask-extension/pull/25636
- [x] https://github.com/MetaMask/metamask-extension/pull/25561
- [x] https://github.com/MetaMask/metamask-extension/pull/25637
- [x] https://github.com/MetaMask/metamask-extension/pull/25515
- [x] https://github.com/MetaMask/metamask-extension/pull/25600
- [x] https://github.com/MetaMask/metamask-extension/pull/25552
- [x] https://github.com/MetaMask/metamask-extension/pull/25630
- [x] https://github.com/MetaMask/metamask-extension/pull/25265
- [x] https://github.com/MetaMask/metamask-extension/pull/25277
- [x] https://github.com/MetaMask/metamask-extension/pull/26172
- [x] https://github.com/MetaMask/metamask-extension/pull/26207

**Comment by danjm** [comment]
@SocketSecurity ignore-all

`webpack-dev-server` and `lydell/node-pty@1.0.1` are needed for a local development dependency
`launch-editor`, `multicast-dns`, `spdy`, `serve-index`, `http-proxy`, `http-proxy-middleware` and `sockjs` are a dependencies of `webpack-dev-server`

**Review by DDDDDanica — APPROVED** [review]

**Review by desi — APPROVED** [review]

**Review by sleepytanya — APPROVED** [review]

**Pull request merged**
