### PR TITLE
Sort app-components.scss

### PR DESCRIPTION
**Pull request by rekmarks**
Sort imports in `app-components.scss`.

### CODE REVIEW

**Review by ryanml — APPROVED** [review]

**Comment by mcmire** [comment]
Can we assume that each CSS file is scoped appropriately and does not depend on any other CSS file? If not we may want to double-check to make sure that this doesn't create any UI bugs.

**Comment by brad-decker** [comment]
Speaking from experience.... you'll want to double check that this doesn't cause any UI regressions.

**Comment by brad-decker** [comment]
```/** Please import your files in alphabetical order **/``` *stares in "convert code comment to lint rule"*

**Review by jpuri — APPROVED** [review]

**Review by DELJUJAZI — APPROVED** [review]

**Review by DELJUJAZI — APPROVED** [review]

**Comment by rekmarks** [comment]
> Speaking from experience.... you'll want to double check that this doesn't cause any UI regressions. 

Well, now there are conflicts, I have a bunch of failing tests, and.... I'm just not going to bother.

**Pull request closed without merging**
