### PR TITLE
Make `setProviderType` async

### PR DESCRIPTION
**Pull request by Gudahtt**
## Explanation

The network controller method `setProviderType` is now async, and the async operation `_setProviderConfig` called at the end of the method is now awaited.

Because the only async operation was the last step, this should have no impact upon the flow of execution in cases where the opertaion is not awaited.

The `switch-ethereum-chain` middleware was updated to await this operation. As a result, an error thrown while the network is switching will now be thrown in this middleware and returned to the dapp as an internal error.

The UI will also be affected, in that the background call to switch networks will not resolve until the network switch has completed. This may impact the timing of state updates slightly in cases where the network switches in the UI (e.g. when using the network switcher)

Relates to https://github.com/MetaMask/metamask-extension/issues/18587

## Manual Testing Steps

Test the `eth_switchEthereumChain` method to ensure it still work correctly. It should work the same as before, just with slight internal changes in timing.

Test any situations where the network can be switched from the UI (e.g. the network switcher, adding a network, etc.)

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [x] How reviewers can test my changes
- [x] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Comment by Gudahtt** [comment]
This depends upon #18600

**Review by mcmire — APPROVED** [review]
Looks good!

**Comment by Gudahtt** [comment]
Rebased to resolve a conflict

**Review by brad-decker — APPROVED** [review]
LGTM

**Pull request merged**
