### PR TITLE
Unit test adjustment

### PR DESCRIPTION
**Pull request by tmashuang**
For #7149

### CODE REVIEW

**Comment by kumavis** [comment]
lint failure is in an unrelated file - weird

**Review by Gudahtt — APPROVED** [review]
I'm going to approve this just so it isn't blocked waiting for a codeowner, but @frankiebee I'll leave this to you since it's against your PR.

**Comment by frankiebee** [comment]
awesome thanks for this

**Comment by frankiebee** [comment]
@kumavis this is just some help from @tmashuang for my WIP branch

**Pull request merged**
