### PR TITLE
feature(19491): fix send-eth and import NFT flaky tests

### LINKED ISSUE #19491: [Flaky e2e test]: Send eth
**Occurring in pipelines:**
`send-eth`:
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/47456/workflows/35fc96c2-5680-4128-889d-bd6e5f770774/jobs/1353477
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/48456/workflows/2efaf1f5-93a8-49af-a56d-383e50e6bee1/jobs/1386320
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/48456/workflows/2efaf1f5-93a8-49af-a56d-383e50e6bee1/jobs/1386320

**Investigation & proposed solution:**

### PR DESCRIPTION
**Pull request by DDDDDanica**
## Explanation
Fix https://github.com/MetaMask/metamask-extension/issues/19491: `Import ERC1155 NFT` is a flaky test detected by circleCI insight tool and didn't provide much error message but snapshot in artifacts. 

And a flaky test for send-eth captured in 

- https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/47456/workflows/35fc96c2-5680-4128-889d-bd6e5f770774/jobs/1353477
- https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/48456/workflows/2efaf1f5-93a8-49af-a56d-383e50e6bee1/jobs/1386320
- https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/48456/workflows/2efaf1f5-93a8-49af-a56d-383e50e6bee1/jobs/1386320

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Comment by Gudahtt** [comment]
Any idea why these additional pauses are necessary? It's hard to tell from the linked failures whether the issue was just a matter of the test running slowly, or whether there was another error.

**Comment by DDDDDanica** [comment]
Hey @Gudahtt thanks for reviewing. It is indeed super difficult to figure out what is the failure for artifacts only. At the same time i cannot reproduce it locally.

However, the flaky one in `test/e2e/nft/import-erc1155.spec.js` is occurring frequently and the only report from artifacts is available. 
Screenshot 2023-06-14 at 00 16 14

From the report of artifacts I could only have a guess that the responding time is a bit long and not enough for UI to enable correct button. Will keep monitoring this test after merging in the future and see if this is the real solution or we need to dig deeper.

Let me know your thoughts ~

**Comment by Gudahtt** [comment]
I hesitate because it seems more likely to me that something has failed by this point, or that some real network call is unmocked and is taking too long. Either way, these added pause might either not help, or they might mask the real problem.

It's too bad we can't see the background console logs. I thought we had that setup at one point. I will look into that.

**Review by brad-decker — APPROVED** [review]

**Review by brad-decker — CHANGES_REQUESTED** [review]
I seem to have hit approve on the wrong tab after changing contexts, Meant to ask about the delays as a means of fixing tests. In the past this has just changed the failure point and been brittle to future changes.

**Comment by DDDDDanica** [comment]
@brad-decker thanks for reviewing. I tend to agree the delay is not the ultimate way of fixing.
In terms of changes made in `test/e2e/tests/send-eth.spec.js`, it is aiming to remove the wrong fix before as `findClickableElement` is included in `clickElement` function. And we just need to give background a bit longer responding time for calls so now the delay is in place to achieve that.
while in `test/e2e/nft/import-erc1155.spec.js` due to luck of detailed error report and difficulty to reproduce locally. The delay was only inspired by [error screenshot](https://github.com/MetaMask/metamask-extension/issues/19491) and an experimental change to see if it could fix. If you have any suggestions would be awesome !

**Pull request closed without merging**
