### PR TITLE
Replace chrome notifications with windows.create

### LINKED ISSUE #452: Replace chrome notifications with windows.create
For chrome notifications, this works from the background console:
```
chrome.windows.create({
    url:"popup.html",
    type:"panel",
    width:360,
    height:500,
});
```

Thanks to @frankiebee for catching this.

### PR DESCRIPTION
**Pull request by danfinlay**
Fixes #452

I'm unsure which will be more performant: A notification using a trimmed down version of the UI, or using the main UI js, letting the browser cache them both.

Here I've modified the normal UI to recognize when it's a notification, and change the UX accordingly in a few ways:
- Hide the menu bar
- Hide the back button from the notifications view.
- When confirming the last tx, close the window.

unlocked-popup
locked-popup

### CODE REVIEW

**Comment by flyswatter** [comment]
Needs some serious QA before we merge.

In particular, since we're using the same general state events to render this notification popup, I suspect that if a notification is visible while the user starts interacting with the app, its state will transition around along with the main popup.

That could be alleviated either with lots of conditionals in the main UI, or by forking apart the notification UI code from the main UI code, despite them sharing many features.

**Comment by flyswatter** [comment]
I tested against those concerns, they turn out to have been baseless, and that makes sense in retrospect: Our app view transition state is not held in the background process at all, but is all just local state of the UI. This is a great benefit of having UI state stored locally, and having global vault + blockchain state held centrally. @kumavis

**Comment by flyswatter** [comment]
Testing our github slack notifications.

**Comment by flyswatter** [comment]
The popups now stay in sync with the main app, and are even dismissed by it when it closes the last tx/msg.

popup-dismiss-remote

**Comment by flyswatter** [comment]
Ok, thanks for the common sense, clicking the main popup will now dismiss the notification.

popup-dismiss-remote2

**Comment by kumavis** [comment]
PS: confirm message signature requests work

**Comment by flyswatter** [comment]
Message signature requests were fixed in another PR, now merged into this one.

**Pull request merged**
