### PR TITLE
[TS dashboard] Reorganize files slightly

### PR DESCRIPTION
**Pull request by mcmire**
## Explanation

I'm making some usability improvements to the TypeScript dashboard, and this is a prerequisite for those changes that cleans things up a bit.

* Create a better distinction between app files and non-app files by
  moving app files from `src/` to `app/`
* Split up stylesheet file
* Move the partitions file (a file generated only once in watch mode
  that is used to build the visualization on the dashboard) within the
  `build/` directory, as it's a built file
* Extract all file and directory paths to a file shared between the app
  and build scripts
  * Note that we use the data from the partitions file from within the
    app, but because neither `fs.readFile*` nor `path.resolve` works
    within a browser context, we use `brfs` to read the file at build
    time and then bake it into the compiled version of the app. However,
    `brfs` is a bit weird to work with, so we can't completely separate
    the variable that holds the path and the call to `fs.readFile` —
    we have to use them in the same place. See the comment in
    `development/ts-migration-dashboard/common/partitions-file.ts` for
    more.

## Manual Testing Steps

* Run `yarn ts-migration:dashboard:watch`, then run `open development/ts-migration-dashboard/build/final/index.html`. You should see the dashboard locally.
* Run `yarn ts-migration:enumerate`. You should see a success message. (Make sure to clear your working index as this changes a file that is kept in the repo.)

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [x] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Review by brad-decker — DISMISSED** [review]

**Review by brad-decker — DISMISSED** [review]

**Comment by mcmire** [comment]
Wish there was a way to test CircleCI without pushing again 😅

**Comment by mcmire** [comment]
Okay should be good for review again — the dashboard link in the bot message above was broken but should work now.

**Review by brad-decker — APPROVED** [review]

**Review by pedronfigueiredo — APPROVED** [review]

**Review by Gudahtt — APPROVED** [review]
The CircleCI config changes look good to me! I didn't review the rest of this closely though.

**Comment by brad-decker** [comment]
This PR contains no changes to the packages socket-dev is complaining about...

**Comment by brad-decker** [comment]
@SocketSecurity ignore jest@29.4.2 jest-cli@28.1.3

**Comment by mcmire** [comment]
@brad-decker Thanks for merging :)

**Pull request merged**
