### PR TITLE
Prevent batch request from opening multiple windows (redux)

### PR DESCRIPTION
**Pull request by kumavis**
https://github.com/MetaMask/metamask-extension/pull/3513 but with master merged for latest CI config

### CODE REVIEW

**Comment by kumavis** [comment]
@tmashuang needs QA

**Comment by kumavis** [comment]
@trigun0x2 please avoid including out-of-bound fixes (lint for unrelated files) in PRs, ty

**Comment by trigun0x2** [comment]
@kumavis I fixed it on my master. Behavior might different between new and old UI. A lot of weird things have been happening with Metamask recently, not sure if it's my changes.

**Comment by kumavis** [comment]
@trigun0x2 what sort of weird things have you been experiencing?

**Pull request closed without merging**
