### PR TITLE
feat(stx): animations and cosmetic changes to smart transaction status page 

### PR DESCRIPTION
**Pull request by dbrans**
## **Description**
Animations and cosmetic changes to smart transaction status page.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/27650?quickstart=1)

## **Related issues**

Fixes:
* https://consensyssoftware.atlassian.net/browse/TXL-366
* https://consensyssoftware.atlassian.net/browse/TXL-413
* https://consensyssoftware.atlassian.net/browse/TXL-365
* https://consensyssoftware.atlassian.net/browse/TXL-412

## **Manual testing steps**

1. Go to this page...
2.
3.

### **Before**

https://github.com/user-attachments/assets/e05e6333-9300-41ad-9c0e-f55b2f30e2a8

### After

https://github.com/user-attachments/assets/fcaa4b2e-5b49-4c8e-92a0-9721751407c5

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by dbrans** [comment]
@metamaskbot update-policies

**Review by georgewrmarshall — APPROVED** [review]
LGTM! I'm not familiar with Lottie, so I'll need to review the documentation to understand best practices and conventions, but I checked the Storybook stories 🔥 and ran some basic performance testing—no concerns! This is a great example of adding more delight to our applications 💯

**Comment by DesignFox3000** [comment]
this looks great @dbrans I only see the success transition - where can I view the failure state?

**Comment by dbrans** [comment]
@DesignFox3000 Glad you asked – it's [in the storybook](https://output.circle-artifacts.com/output/job/84a15d46-0e8a-42bd-88e8-34758465e3a8/artifacts/0/storybook/index.html?path=/story/pages-smarttransactions-smarttransactionstatuspage--failed).

**Review by sleepytanya — APPROVED** [review]

**Pull request merged**
