### PR TITLE
Feature: Subscription support

### LINKED ISSUE #5425: Transaction receipt callback is not called on Metamask 4.12
With MetaMask 4.12, the receipt is not returned in both callback and promise versions.

`contract.methods.method().send({ from: address }).then(receipt => console.log(receipt))`

`contract.methods.method().send({ from: address }).on('receipt', function(receipt) {
   console.log(receipt);
})`

Both these examples are not working in Metamask 4.12 but working fine in 4.9

### PR DESCRIPTION
**Pull request by kumavis**
This enables partial support for the experimental "web3 1.0 Ethereum JSON RPC subscriptions", covering the two most commonly used subscription types `newHeads` and `logs`.

### supported subscription types:
- [x] `newHeads` new block headers https://github.com/ethereum/go-ethereum/wiki/RPC-PUB-SUB#newheads
- [x] `logs` evm log filter results https://github.com/ethereum/go-ethereum/wiki/RPC-PUB-SUB#logs
- [ ] `newPendingTransactions` get pending txs as we hear about them (somewhat functional in provider-engine, but likely not compliant)
- [ ] `syncing` whether the client is currently syncing blocks or not (not implemented in provider-engine either)

### changes in deps 
Lionshare of the changes appears in the following deps:
- [metamask-inpage-provider@1.2.0](https://github.com/MetaMask/metamask-inpage-provider/compare/86704ef8c245227824299ec26c6715d449ac018f...master)
- [eth-json-rpc-middleware@3.0.0](https://github.com/MetaMask/eth-json-rpc-middleware/compare/cce9b33f788005a1bde59a3598d63ee778d08f22...master)
- [json-rpc-engine@3.8.0](https://github.com/MetaMask/json-rpc-engine/compare/b4473d4828e5152793d876a2e8cebb24805ef701...master)
- [json-rpc-middleware-stream@2.1.0](https://github.com/MetaMask/json-rpc-middleware-stream/compare/86cd776701bb8a41c209aad036d346ebd6dc37a8...master)
- [eth-json-rpc-filters@3.0.1](https://github.com/MetaMask/eth-json-rpc-filters/compare/dbe7b374ef5692dc81717628c8f3de6e9da8412f...master) <-- subs implementation

### testing and QA
While subscription support is tested in the `eth-json-rpc-filters` module, MetaMask is lacking dapp-level integration tests. It can be QA'd like this:

- navigate to a dapp like `metamask.io` and open the console
- log ALL subscription hits to console
```js
web3.currentProvider.on('data', console.log)
```
subscribe to `newHeads`
```js
web3.currentProvider.send({ id:1, method: 'eth_subscribe', params:['newHeads']}, console.log)
```
subscribe to a log filter (eg DAI txs) 
```js
web3.currentProvider.send({ id:1, method: 'eth_subscribe', params:['logs', { address: '0x89d24A6b4CcB1B6fAA2625fE562bDD9a23260359'}]}, console.log)
```
subscribe to all logs (fire hose warning) 
```js
web3.currentProvider.send({ id:1, method: 'eth_subscribe', params:['logs', {}]}, console.log)
```

### Relevant Issues and PRs
This PR replaces https://github.com/MetaMask/metamask-inpage-provider/pull/3
Fixes #5425
Fixes #3642

### CODE REVIEW

**Comment by kumavis** [comment]
Addressing the "missing provider" test failures...

**Comment by whymarrh** [comment]
Can we add "fixes #5425" to this PR?

**Review by tmashuang — APPROVED** [review]

**Comment by HowardBraham** [comment]
@kumavis and @danfinlay, does this change the way one has to write web3 code in a Dapp?

I am using [web3.js@v1.0.0-beta.36](https://github.com/ethereum/web3.js/releases/tag/v1.0.0-beta.36), and when I do this on Rinkeby:
`let contract = new web3.eth.Contract( ...`
`contract.methods.transfer( ...`

After this PR, the UI will show the error:
`ALERT: Transaction Error. Exception thrown in contract code.`

And deeper, the RPC error when calling `eth_estimateGas` is:
`Error: [ethjs-rpc] rpc error with payload ... TypeError: blockRef.slice is not a function`

My PR #5283 depends on this functionality, and I thought possibly it's just that the web3 syntax has changed.

**Comment by tmashuang** [comment]
@HowardBraham this has been fixed in https://github.com/MetaMask/eth-json-rpc-middleware/pull/6

**Comment by elie222** [comment]
So with this merged in, is Metamask now compatible with web3 1.0?

**Pull request merged**
