### PR TITLE
 Add `react/no-unused-prop-types` ESLint rule

### PR DESCRIPTION
**Pull request by Gudahtt**
The [`react/no-unused-prop-types` ESLint rule](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-unused-prop-types.md) has been enabled. All detected unused prop types have been removed. I have attempted to ensure these props are no longer passed in either.

There were a few prop types that were erroneously detected by `react/no-unused-prop-types` as being unused props. I had to make a few minor adjustments to prevent them from being flagged as errors (see the second commit)

### CODE REVIEW

**Review by whymarrh — DISMISSED** [review]
LGTM

**Comment by Gudahtt** [comment]
There are still a few changes i need to make to fix lint errors that were introduced since the React v16 PR - I'll add that later as a separate commit. In the meantime the rest of this could be reviewed. It couldn't hurt to review this in more detail, as some of these changes were pretty... well, non-obvious.

**Comment by Gudahtt** [comment]
The two lint failures were due to props used within `UNSAFE_componentWillReceiveProps`, which are not detected properly by this rule. Those cases have been ignored for now with `eslint-disable-line` comments until we can replace those lifecycle functions.

**Review by whymarrh — APPROVED** [review]
This is a great PR

**Pull request merged**
