### PR TITLE
Drop the buy button in if tx is more then account balance 

### LINKED ISSUE #519: Buy button on tx conf view
- Dropping the buy button in the notification. 
possibly looking into switching from notifications to pop ups.
- In a perfect world hold the tx untill their is enough eth in balance. 
- And buy amount possibly have a input
- Buy amount cant be more then 5.

### PR DESCRIPTION
**Pull request by frankiebee**
fixes #519 
screen shot 2016-09-15 at 10 28 28 am

### CODE REVIEW

**Comment by flyswatter** [comment]
I think I’d like to pair the `BUY` button with maybe a `span.warning` on the line above, that might indicate “The sending account has insufficient funds to perform the requested transaction.”

Then maybe name the button even more descriptively, `BUY ETHER`.

Open to others’ opinions, I know that’s a heavy-handed proposal, but I think we need some more clear indication why there’s no accept button.

**Comment by kumavis** [comment]
maybe arrange as [ buy ether ] [ accept (disabled) ] [ buy ether ]

**Comment by kumavis** [comment]
for this PR:
- [ ] add warning
for later:
- [ ] show disabled "accept" button

**Comment by frankiebee** [comment]
@kumavis two buy ether buttons?
or [buy ether][accept][reject]

**Comment by kumavis** [comment]
@frankiebee sorry i should have said im picking this up now

**Comment by kumavis** [comment]
image

**Comment by kumavis** [comment]
image

**Comment by flyswatter** [comment]
Bump changelog, then good to merge to me.

**Pull request merged**
