### PR TITLE
Pocket

### LINKED ISSUE #6782: Add decentralized infrastructure option for Metamask users
**What problem are you trying to solve?**
Currently Metamask supports connecting to the network via a custom RPC URL or a centralized provider. In this issue the Pocket Network team would like to propose an integration between Pocket Core MVP and Metamask, allowing users to utilize the Pocket Core MVP network of nodes (currently 6 different infrastructure providers) to connect to the blockchain using a trusted decentralized network of nodes via random access across different requests.

**Describe the solution you'd like**
Scope:

1. Update the UI RPC node selection screen to show the option to use Pocket Network.
2. Create a brand new Pocket middleware to allow RPC requests to be sent via the Pocket Network.
3. Creation of a `json-rpc-engine` middleware package to conform to the architectural standard of network providers, [currently hosted here](https://github.com/pokt-network/json-rpc-pocket).

All the before-mentioned work would be executed by the Pocket Network team according to the project's Contribution Guidelines. For more information about the Pocket Network, feel free to check the links below:

1. [Pocket Network website]( https://pokt.network )
2. [Pocket Core MVP](https://pokt.network/pocket-core-mvp)
3. [Pocket Developer Portal](https://docs.pokt.network)

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by luyzdeleon**
Decentralized Infrastructure option (Pocket Network) PR: Closes #6782 

Adds a decentralized infrastructure provider that allows users to use Pocket Network instead of
the standard centralized provider.

Changelog:
1. Updates the UI in 2 different places:

A. Adds an additional option in the Network Dropdown:
Screen Shot 2019-06-28 at 1 16 37 PM
     
B. Adds an additional option in the default Network List in the Networks tab under Settings:
Screen Shot 2019-07-01 at 7 16 50 PM

2. Added `json-rpc-pocket` dependency found here: [https://github.com/pokt-network/json-rpc-pocket](https://github.com/pokt-network/json-rpc-pocket).
3. Added file createPocketClient.js -> creates the Pocket middleware using the `json-rpc-pocket`.
4. Updated English locale files to add `pocket_` label texts where applicable.
5. Updated the Networks enums to be able to differentiate when the provider is Infura or when it is Pocket Network.
6. Updated the NetworkController to be able to detect and create a Pocket Middleware when Pocket Network is selected as the network provider.

How To Use:
1. Click the Network Dropdown and select any desired network that says `- Pocket Network`.
2. Click the Account logo, click Settings, then click Network, and then select any desired network that says `- Pocket Network`

Additionally a User tutorial guide will be posted to the Pocket Network Developer Portal found here: [Developer Portal](https://docs.pokt.network)

### CODE REVIEW

**Comment by decanus** [comment]
@luyzdeleon it might be nicer to have a UI where I can switch between node providers, rather than having every network duplicated.

**Comment by luyzdeleon** [comment]
> @luyzdeleon it might be nicer to have a UI where I can switch between node providers, rather than having every network duplicated.

Hello @decanus

**Comment by luyzdeleon** [comment]
> @luyzdeleon it might be nicer to have a UI where I can switch between node providers, rather than having every network duplicated.

Hello @decanus , thank you for your feedback. That was our original intent, however by further inspecting the code we realized that we would have to rearchitect the UI portion of the default network provider system, in order to make it a multi provider system. In that case we decided to stick to the existing architecture and go this route.

**Comment by kumavis** [comment]
@luyzdeleon nice, its critical to have more infrastructure options. Can you tell us more about the trust model for the responding nodes? Since data is not validated, its important that we can trust the data source. We have a close relationship with infura which helps in that case, but here it seems theres a few steps between us and the data provider

**Comment by luyzdeleon** [comment]
@kumavis We are currently in a closed beta where we vet each infrastructure provider before allowing them to run a Pocket Node. This is done to ensure a trusted, high quality service at this stage of the protocol's development. Pocket's current providers are (besides ourselves) Nodesmith, Quiknode, Figment Networks, Protofire and the Metacartel.

When the protocol is live there will be client-side validation and cryptoeconomic guarantees to ensure that the data being received is fair and true.

Find the links to the current providers websites below:

https://nodesmith.io/
https://quiknode.io/
https://protofire.io/
https://www.metacartel.org/
https://figment.network/

**Comment by whymarrh** [comment]
Hey, @luyzdeleon, thanks for taking the time to work on this and apologies for not responding sooner. The network list can't be extended to include everyone's networks and we don't have a way of honestly choosing among the various networks (see also xDai's #7492).

> by further inspecting the code we realized that we would have to rearchitect the UI portion of the default network provider system, in order to make it a multi provider system. In that case we decided to stick to the existing architecture and go this route.

You've noticed a shortcoming of our current architecture that we're aware of and will address.

I'm going to close this for now. I appreciate you opening #6782 before starting this work—we can continue discussions there about how we might best make these networks available to our users. #3604 and #5101 are also relevant here, as ideally we should have a way to allow sites (plugins even?) to add new networks. We welcome new ideas on these.

**Pull request closed without merging**
