### PR TITLE
Updates Add token screen to latest design.

### PR DESCRIPTION
**Pull request by danjm**
screen shot 2018-03-24 at 1 09 26 am
----
screen shot 2018-03-24 at 1 09 19 am
----
screen shot 2018-03-24 at 1 09 12 am

addtoken-newdesign

### CODE REVIEW

**Review by alextsg — APPROVED** [review]

**Comment by cjeria** [comment]
@tmashhuang I was going to review this PR today, I have some feedback.

**Comment by cjeria** [comment]
I’ll create another issue with my feedback.

**Comment by cjeria** [comment]
Created issue #3734 with design feedback for this PR.

**Comment by cjeria** [comment]
It's best to catch design feedback in the PR phase to avoid rework later down the road.

**Pull request merged**
