### PR TITLE
Version v11.17.0

### PR DESCRIPTION
**Pull request by benjisclowder**
Adding RC 11.17.0

### CODE REVIEW

**Comment by benjisclowder** [comment]
[Manual test scenarios:](https://github.com/MetaMask/metamask-extension/tree/develop/test/scenarios)

**Chrome**

- [ ] Onboarding - create a wallet
- [ ]  Onboarding - import a wallet
- [ ]  Keyring - connect hardware wallet
- [ ]  Keyring - reset a wallet
- [ ]  Transactions - send native token origin MM
- [ ]  Transactions - send native token origin dapp
- [ ]  Transactions - send ERC20 token origin MM
- [ ]  Transactions - send ERC20 token origin dapp
- [ ]  Transactions - send ERC721 token origin MM
- [ ]  Transactions - send ERC721 token origin dapp
- [ ]  Transactions - speed up transaction
- [ ]  Transactions - cancel transaction
- [ ]  Transactions - deploy failing transaction
- [ ]  Transactions - deposit and withdraw
- [ ]  Transactions - navigate multiple transactions
- [ ]  Transactions - send transactions with custom nonce
- [ ]  Transactions - cancel transaction using same nonce
- [ ]  Tokens - import ERC20 token origin MM
- [ ]  Tokens - import ERC20 token origin dapp
- [ ]  Tokens - import ERC721 token origin MM
- [ ]  Tokens - import ERC721 token origin dapp
- [ ]  Tokens - import ERC1155 token origin MM
- [ ]  Tokens - import ERC1155 token origin dapp
- [ ]  Tokens - approve ERC1155 token
- [ ]  Tokens - approve ERC20 token
- [ ]  Tokens - approve ERC721 token
- [ ]  Tokens - autodetect tokens
- [ ]  Tokens - autodetect NFTs
- [ ]  Tokens - approve erc20 custom amount
- [ ]  ENS - name resolution
- [ ]  Phishing - warning page
- [ ]  Network - add custom network manually
- [ ]  Network - add custom network from the list of popular networks
- [ ]  Network - add custom network from dApp
- [ ]  Network - update networks
- [ ]  Network - switching networks
- [ ]  Network - delete networks from the dropdown list
- [ ]  Network - delete networks in Settings
- [ ]  Backup - backup user data
- [ ]  Backup - restore user data
- [ ]  Metrics - send event metrics
- [ ]  Address-book - add a contact to the address book
- [ ]  Address-book - remove a contact from the address book
- [ ]  Address-book - update a contact in the address book
- [ ]  Gas fee - EIP-1559 gas
- [ ]  Gas fee - legacy gas
- [ ]  Sign - eth sign
- [ ]  Sign - personal sign
- [ ]  Sign - sign in with ethereum
- [ ]  Sign - sign typed with data
- [ ]  Sign - sign typed data v3 with hardware wallet
- [ ]  Sign - sign typed data v4 with hardware wallet
- [ ]  Sign - personal sign with hardware wallet
- [ ]  Sign - eth sign with hardware wallet
- [ ]  Permissions - connecting and disconnecting from a dapp
- [ ]  Swap - smart swap
- [ ]  Swap - swap eth
- [ ]  Incoming transactions - receive native token
- [ ]  Settings - about MetaMask
- [ ]  Settings - general - change language
- [ ]  Settings - advanced - check custom nonce toggle
- [ ]  Settings - advanced - show hex data
- [ ]  Contract - deploy contract, mint and import NFT with hardware wallet
- [ ]  Contract - hardware wallet qr based connect
- [ ]  Contract - send token with hardware wallet

**Firefox**

- [ ] Onboarding - create a wallet
- [ ]  Onboarding - import a wallet
- [ ]  Keyring - connect hardware wallet
- [ ]  Keyring - reset a wallet
- [ ]  Transactions - send native token origin MM
- [ ]  Transactions - send native token origin dapp
- [ ]  Transactions - send ERC20 token origin MM
- [ ]  Transactions - send ERC20 token origin dapp
- [ ]  Transactions - send ERC721 token origin MM
- [ ]  Transactions - send ERC721 token origin dapp
- [ ]  Transactions - speed up transaction
- [ ]  Transactions - cancel transaction
- [ ]  Transactions - deploy failing transaction
- [ ]  Transactions - deposit and withdraw
- [ ]  Transactions - navigate multiple transactions
- [ ]  Transactions - send transactions with custom nonce
- [ ]  Transactions - cancel transaction using same nonce
- [ ]  Tokens - import ERC20 token origin MM
- [ ]  Tokens - import ERC20 token origin dapp
- [ ]  Tokens - import ERC721 token origin MM
- [ ]  Tokens - import ERC721 token origin dapp
- [ ]  Tokens - import ERC1155 token origin MM
- [ ]  Tokens - import ERC1155 token origin dapp
- [ ]  Tokens - approve ERC1155 token
- [ ]  Tokens - approve ERC20 token
- [ ]  Tokens - approve ERC721 token
- [ ]  Tokens - autodetect tokens
- [ ]  Tokens - autodetect NFTs
- [ ]  Tokens - approve erc20 custom amount
- [ ]  ENS - name resolution
- [ ]  Phishing - warning page
- [ ]  Network - add custom network manually
- [ ]  Network - add custom network from the list of popular networks
- [ ]  Network - add custom network from dApp
- [ ]  Network - update networks
- [ ]  Network - switching networks
- [ ]  Network - delete networks from the dropdown list
- [ ]  Network - delete networks in Settings
- [ ]  Backup - backup user data
- [ ]  Backup - restore user data
- [ ]  Metrics - send event metrics
- [ ]  Address-book - add a contact to the address book
- [ ]  Address-book - remove a contact from the address book
- [ ]  Address-book - update a contact in the address book
- [ ]  Gas fee - EIP-1559 gas
- [ ]  Gas fee - legacy gas
- [ ]  Sign - eth sign
- [ ]  Sign - personal sign
- [ ]  Sign - sign in with ethereum
- [ ]  Sign - sign typed with data
- [ ]  Sign - sign typed data v3 with hardware wallet
- [ ]  Sign - sign typed data v4 with hardware wallet
- [ ]  Sign - personal sign with hardware wallet
- [ ]  Sign - eth sign with hardware wallet
- [ ]  Permissions - connecting and disconnecting from a dapp
- [ ]  Swap - smart swap
- [ ]  Swap - swap eth
- [ ]  Incoming transactions - receive native token
- [ ]  Settings - about MetaMask
- [ ]  Settings - general - change language
- [ ]  Settings - advanced - check custom nonce toggle
- [ ]  Settings - advanced - show hex data
- [ ]  Contract - deploy contract, mint and import NFT with hardware wallet
- [ ]  Contract - hardware wallet qr based connect
- [ ]  Contract - send token with hardware wallet

**Comment by benjisclowder** [comment]
We need teams' approval by May 22.

**Instructions for Team Review**

**Review Changes**: Refer to the [Release Tracker for v11.17.0](https://docs.google.com/spreadsheets/d/1tsoodlAlyvEUpkkcNcbZ4PM9HuC9cEM80RZeoVv5OCQ/edit#gid=1616117868) to see all changes relevant to your team.

**Log Bugs**: If you find any issues, log them in the release tracker and attach them to https://github.com/MetaMask/MetaMask-planning/issues/2467.

**Approval**: After reviewing, indicate your team's approval by:

- Marking the checkbox next to your team's name in this comment.
- Optionally, leave a comment for additional information.

Your thorough review ensures a smooth and successful release. If you have any questions please reach out to extension platform team or in the [#metamask-qa](https://consensys.slack.com/archives/C01U65ZUS2E) slack channel. Thank you for your collaboration!

- [ ] Accounts: @plasmacorral - There are 2 Accounts changes in v11.17.0
- [ ]  Assets: @sahar-fehri / @alfeng6 - There are 4 Assets changes in v11.17.0
- [ ]  Confirmations: @sleepytanya - There are 30 Confirmation Systems changes in v11.17.0.
- [ ]  DappAPI: @jiexi - There are 2 DappAPI changes in v11.17.0.
- [ ]  Design/Systems: @georgewrmarshall - There are 3 Design/Systems change in v11.17.0.
- [ ]  Devex: @tmashuang / @vandan - There are 3 Devex changes in v11.17.0.
- [ ]  MMI: @zone-live / @shane-t - There are 4 MMI changes in v11.17.0.
- [ ]  Shared Libraries: @Gudahtt - There are 4 Shared Libraries changes in v11.17.0.
- [ ]  Snaps: @bowensanders / @FrederikBolding / @Montoya - There are 6 Snaps changes in v11.17.0.
- [ ]  Swaps: @davibroc / @dan437 - There are 2 Swaps change in v11.17.0.
- [ ]  Wallet UX: @darkwing / @NidhiKJha - There are 12 Wallet UX changes in v11.17.0.

**Review by georgewrmarshall — COMMENTED** [review]
🟢 Approval from @MetaMask/design-system

Checked changes from the following PRs:

- https://github.com/MetaMask/metamask-extension/pull/24089
- https://github.com/MetaMask/metamask-extension/pull/24262
- https://github.com/MetaMask/metamask-extension/pull/24411

Screenshot 2024-05-15 at 11 45 07 AM

**Comment by benjisclowder** [comment]
Closing this PR as 11.17.0 was included in 12.0.0.

**Pull request closed without merging**
