### PR TITLE
feature: add goerli support

### LINKED ISSUE #6249: Add Goerli test net
Infura supports it now, we should add it. They say to add as a normal json-rpc endpoint, they’re going to deprecate the rest endpoints.

### PR DESCRIPTION
**Pull request by bitpshr**
This pull request adds [goerli](https://goerli.net/) network support.

Resolves #6249 

Screen Shot 2019-04-15 at 11 10 07 AM

Screen Shot 2019-04-15 at 11 10 11 AM

Screen Shot 2019-04-15 at 11 18 22 AM

### CODE REVIEW

**Review by whymarrh — CHANGES_REQUESTED** [review]
LGTM, one small nitpick: can we drop the changes to the `package-lock.json` file as there are no changes to the `package.json` file in this PR?

**Comment by bitpshr** [comment]
Thanks @whymarrh, good catch. Updated.

**Review by whymarrh — DISMISSED** [review]

**Comment by whymarrh** [comment]
@tmashuang would you be able to give this a QA pass as well? It seems good to me.

**Comment by tmashuang** [comment]
Will need to add the network list to the the `buyEth` deposit modal

https://github.com/MetaMask/metamask-extension/blob/ac39a9b3788372870fc668ed9395644ee20fe6bc/ui/app/components/app/modals/deposit-ether-modal.js#L136

and provide a url for the test network

https://github.com/MetaMask/metamask-extension/blob/98a2fb43fb371584d3cd6730958f0f3d17fc0d12/app/scripts/lib/buy-eth-url.js#L14

I recommend https://bridge.goerli.com/ from 
https://github.com/goerli/testnet/blob/master/README.md#meta-data-görli

**Review by tmashuang — DISMISSED** [review]
Will need to add the network list to the the `buyEth` deposit modal

https://github.com/MetaMask/metamask-extension/blob/ac39a9b3788372870fc668ed9395644ee20fe6bc/ui/app/components/app/modals/deposit-ether-modal.js#L136

and provide a url for the test network

https://github.com/MetaMask/metamask-extension/blob/98a2fb43fb371584d3cd6730958f0f3d17fc0d12/app/scripts/lib/buy-eth-url.js#L14

I recommend https://bridge.goerli.com/ from 
https://github.com/goerli/testnet/blob/master/README.md#meta-data-görli but requires eth from other test networks, could use the other ones recommended.

Edit: Couldn't get the bridge to work.
https://goerli-faucet.slock.it/ provides 0.05/tx
https://faucet.goerli.mudit.blog/ will need a social media link with an address as the message

**Comment by tmashuang** [comment]
This PR, #6444 also touched the `network-dropdown.js` will need to resolve those conflicts.

**Review by whymarrh — APPROVED** [review]
Seems legit (cc @bitpshr)

**Pull request merged**
