### PR TITLE
update scams and network security risks link

### LINKED ISSUE #12746: Update 'Learn about scams and network security risks' link
In the add network popup, the link on the "scams and network security risks" text is out of date.

The current link is https://metamask.zendesk.com/hc/en-us/articles/360056196151-Using-custom-networks-with-MetaMask

It should be updated to: https://metamask.zendesk.com/hc/en-us/articles/4404424659995

Screen_Shot_2021-11-10_at_19 00 53

### PR DESCRIPTION
**Pull request by rootial**
Fixes: #12746

Explanation:  
minor change

I have read the CLA Document and I hereby sign the CLA

### CODE REVIEW

**Comment by rootial** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by rootial** [comment]
Hi guys, i failed to rum the storybook job due to no access to the repos, can you help me enable it? thanks

@Gudahtt @danjm

**Comment by Gudahtt** [comment]
Hi @rootial, thanks for the contribution! I have approved this workflow to run, but it looks like it was cancelled and needs to be re-run by you. We don't have access to re-run because you have not allowed write access to maintainers on this PR (or at least I think that's the reason - not 100% sure).

**Comment by rootial** [comment]
@Gudahtt i have enabled write access to maintainers and i found that story deploy failed due to no access. Do you know how to address this? thanks
```
Error: Exec code(128) on executing: git push --force --quiet git@github.com:MetaMask/metamask-storybook.git master:master
ERROR: The key you are authenticating with has been marked as read only.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.


```

**Comment by Gudahtt** [comment]
Thanks @rootial ! I have rebased this branch to trigger CI to run again.

That error about the storybook deployment is not of any concern. That's only supposed to run on our `develop` branch, not on PRs. It's running only because you are also using a branch named `develop`. Usually people use different branch names for their changes. But it's no big deal, we can just ignore the error.

**Review by Gudahtt — APPROVED** [review]
LGTM!

**Comment by Gudahtt** [comment]
It looks like the CircleCI jobs aren't running because CircleCI suspended your project or account. Please contact CircleCI about that if you want to make further contributions to this project. This change is small enough that we can merge this without the CI checks though.

**Review by mcmire — APPROVED** [review]

**Pull request merged**
