### PR TITLE
Storybook - fix font paths

### PR DESCRIPTION
**Pull request by kumavis**
make font paths relative so they work in the CI artifacts build of storybook

### CODE REVIEW

**Comment by kumavis** [comment]
hmm couldnt get fontawesome to work

**Comment by kumavis** [comment]
@brad-decker im fighting the sass compiler for control over the paths . lemme know if you have some advice here

**Comment by kumavis** [comment]
these changes need to verified to make sure they dont change prod

**Comment by EtDu** [comment]
I'll keep this alive. Next steps are:
- fix for FontAwesome
- verify prod still works as intended

**Comment by danjm** [comment]
This was resolved with https://github.com/MetaMask/metamask-extension/pull/13028

**Pull request closed without merging**
