### PR TITLE
Added Haitian Creole translations

### PR DESCRIPTION
**Pull request by farahbrunache**
This closes issue https://github.com/MetaMask/metamask-extension/issues/5141.

I worked with a local to do the contextual translations. Most concepts to do not exist in the language. So there are a few intentional words left so to not lose context, for example "cryptocurrency," "seed" and "token."

### CODE REVIEW

**Comment by farahbrunache** [comment]
@QueenT03 please see the updated translations.

**Review by QueenT03 — COMMENTED** [review]
Looks good!

**Comment by farahbrunache** [comment]
@mapmeld - is everything good to go 👍 ?

**Review by mapmeld — DISMISSED** [review]
Mesi anpil for doing this! Looking forward to seeing it merged into the app.  If there are any remaining questions, I will talk to the MetaMask organizers on Slack

**Comment by farahbrunache** [comment]
@mapmeld any updates? I have users for my application, it is difficult to advocate for them to use MetaMask when it is not in Kreyòl ...

**Review by kumavis — DISMISSED** [review]

**Comment by kumavis** [comment]
Looks great, thanks for the contribution

Need to investigate the test failures. May be associated with the whitespace change in the index.json

**Comment by kumavis** [comment]
primary issue was invalid json for haitian translation:
- unescaped quotes in translation
- repeated key-value pair

**Review by kumavis — APPROVED** [review]
Formatting issues resolved

**Pull request merged**
