### PR TITLE
Part of ##18714 Replace deprecated design system typography consts with enums in: confirm-page-container.component.js

### PR DESCRIPTION
**Pull request by PrgrmrHarshShukla**
## Explanation
This PR is a part of #18714 Replace deprecated design system typography consts with enums in: 
**ui\components\app\confirm-page-container\confirm-page-container.component.js**

### Before

Screenshot (96)

### After
Screenshot (97)

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Comment by georgewrmarshall** [comment]
Hey @PrgrmrHarshShukla the label PR failure you are getting is because of the commented out issue reference in your PRs. I would suggest removing the entire commented out section for future PRs

Screenshot 2023-05-09 at 5 30 58 PM
Screenshot 2023-05-09 at 5 31 25 PM

**Review by georgewrmarshall — APPROVED** [review]
LGTM!

**Comment by brad-decker** [comment]
@PrgrmrHarshShukla I have placed a 7 day block on you on the MetaMask organization in GitHub due to repetitive attempts to engage our developers in communication channels outside of GitHub. You will be automatically unblocked after 7 days. If the behavior continues the block could become permanent. If you need to speak with someone I recommend using the tools available to the public at www.metamask.io

**Comment by georgewrmarshall** [comment]
I wasn't aware of this. @PrgrmrHarshShukla please adhere to our [contributor guidelines](https://github.com/MetaMask/.github/blob/main/CODE_OF_CONDUCT.md)

**Review by garrettbear — APPROVED** [review]

**Pull request merged**
