### PR TITLE
Block gravityforms.com from web3 injection

### LINKED ISSUE #3073: Conflict with Wordpress Gravityforms
On a site that has no web3 functionality, metamask appears to get an error when a Gravityform is submitted with confirmation mode set to 'redirect'. This prevents the page from showing the confirmation.

Currently, the page is on a development env, not public, so it is hard to give you a reproduction. If there is interest, we could put one online. In the meantime, here is the Chrome console error:

```
Uncaught ReferenceError: jQuery is not defined
    at ?frame-view=true:158
(anonymous) @ ?frame-view=true:158
VM835 inpage.js:38 Uncaught Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again.
    at Object.eval (inpage.js:38)
    at Object.1../lib/auto-reload.js (inpage.js:80)
    at s (inpage.js:1)
    at e (inpage.js:1)
    at eval (inpage.js:1)
    at eval (<anonymous>)
    at VM741 jquery.js?ver=1.12.4:2
    at Function.globalEval (VM741 jquery.js?ver=1.12.4:2)
    at Ha (VM741 jquery.js?ver=1.12.4:3)
    at a.fn.init.append (VM741 jquery.js?ver=1.12.4:3)
(anonymous) @ VM835 inpage.js:38
1../lib/auto-reload.js @ VM835 inpage.js:80
s @ VM835 inpage.js:1
e @ VM835 inpage.js:1
(anonymous) @ VM835 inpage.js:1
(anonymous) @ VM741 jquery.js?ver=1.12.4:2
globalEval @ VM741 jquery.js?ver=1.12.4:2
Ha @ VM741 jquery.js?ver=1.12.4:3
append @ VM741 jquery.js?ver=1.12.4:3
(anonymous) @ ?frame-view=true:381
dispatch @ VM741 jquery.js?ver=1.12.4:3
r.handle @ VM741 jquery.js?ver=1.12.4:3
```

  *  Expected Behavior
Metamask should have no effect on the page.

  *  Actual Behavior
Metamask error halts js execution on the page.

  *  Browser Used
Chrome

  *  Operating System Used
OSX

### PR DESCRIPTION
**Pull request by danfinlay**
Fixes #3073

### CODE REVIEW

**Review by kumavis — APPROVED** [review]

**Comment by mfx-shaun** [comment]
Is there a way to fix or workaround this issue without forcing every person that visits our site having to update metamask?

**Comment by danfinlay** [comment]
MetaMask updates automatically, no user interaction should be required.

**Comment by mfx-shaun** [comment]
last release was 8 days ago and this fix happened 7 days ago. We need to wait for the next release correct?

**Comment by danfinlay** [comment]
No, this is a living list, changes to this repo affect all metamask instances in about 10 minutes.

**Comment by danfinlay** [comment]
Oh sorry, wrong repo. Yes you're waiting for the next release. Should be tomorrow morning.

**Comment by mastef** [comment]
This doesn't really fix it, as WordPress GravityForms are installed on other domains than gravityforms.com. You could check for existence of `typeof window.gform_gravityforms != 'undefined'`

**Pull request merged**
