### PR TITLE
ci - cache deps before patch-package

### LINKED ISSUE #10734: bug: CI - prep deps - we're caching the node_modules after patch
Build - we're caching the `node_modules` after patch, then recovering them, then apply the patch again. this sometimes fails

### PR DESCRIPTION
**Pull request by kumavis**
Fixes: https://github.com/MetaMask/metamask-extension/issues/10734

we are accidentally caching the patched package and then patching them again

### CODE REVIEW

**Review by EtDu — DISMISSED** [review]
/sparkle

**Comment by kumavis** [comment]
cache is bad for branches that are sensitive to this bug

**Review by EtDu — APPROVED** [review]
new cache :)

**Review by Gudahtt — APPROVED** [review]
LGTM!

**Pull request merged**
