### PR TITLE
Prevent send to token warning

### PR DESCRIPTION
**Pull request by estebanmino**
Following https://github.com/MetaMask/metamask-extension/pull/6051
 
This PR adds this validation as a warning instead of an error. With this the user will see `Known contract address.` as an error but is still possible to send the transaction.

This PR also adds a new object to the `send` state, called `warnings`. For now rendered with the component `SendRowWarningMessage` as the errors, but the idea of this is to easily modify the way we want to show warnings to users, without blocking the transaction validation.

### CODE REVIEW

**Review by danjm — DISMISSED** [review]

**Comment by estebanmino** [comment]
Sure there is a GIF 

shpw

As you can see, sending HACK to the address HACk or any contract in contract-metadata it will show a `Known contract address.` message that is part of the `warnings` added to this PR so the user will still be able to send the token to the address. And this warning will appear only when sending tokens.

If we want to change the color or anything else in that message we just need to modify `SendRowWarningMessage` that right now is working with the same style as errors.

**Comment by danjm** [comment]
@estebanmino Yeah, let's change the color to orange, as it is just a warning. For example, see the different warning colours we have in the speed up sidebar.

speeduperrors

Otherwise this looks good to merge.

**Comment by estebanmino** [comment]
done

@danjm  changed

**Review by whymarrh — APPROVED** [review]
LGTM

**Pull request merged**
