### PR TITLE
build system task output improvement

### PR DESCRIPTION
**Pull request by kumavis**
concurrently does have a way of adding jobs after instantiation, and so we run them one by one
it really isnt providing very much here, just prefixing the output.
it also only wraps the output for tasks run in child processes.

image

### CODE REVIEW

**Comment by kumavis** [comment]
test failures bc i didnt update lavamoat policy

**Comment by brad-decker** [comment]
@kumavis should this be fixed up and made reviewable or closed?

**Comment by kumavis** [comment]
image
pretty! but stats look wrong. also the process isnt closing

**Review by brad-decker — APPROVED** [review]
Looks good to me! 💯

**Pull request closed without merging**
