### PR TITLE
Cancel error rebased

### PR DESCRIPTION
**Pull request by danjm**
Closes #6088

A re-push of https://github.com/MetaMask/metamask-extension/pull/6088 with lint errors and merge conflicts fixed

### CODE REVIEW

**Comment by tmashuang** [comment]
Hmm I could get the expected result. With a balance of 0.01, send a max tx value with for 0.009979, and tx fee was 0.000021, but the cancel button wasn't disabled for me.

**Comment by danjm** [comment]
thanks @tmashuang I'll check it out

**Comment by tmashuang** [comment]
With a little debugging, the cancelDisabled prop was true. It might on the conditional render, maybe?

**Comment by danjm** [comment]
@tmashuang oh, that's interesting... I just pushed https://github.com/MetaMask/metamask-extension/pull/6341/commits/99d641a0fe9a00c2b148bfa89e5c1a5530c7a4b6 without which I'd expect the behaviour you saw.

Is it possible that when you saw `cancelDisabled` as true your balance was less than `gasFee * 1.1`?

**Review by whymarrh — APPROVED** [review]
LGTM

**Pull request merged**
