### PR TITLE
Settings:TabBar: Fix text wrap style

### LINKED ISSUE #13856: [Bug]: Design breaks on the Settings Navbar when Internationalization
### Describe the bug

When I choose another language, I see that the design breaks on the left navbar for Advance Settings.

**Example1: Spanish**
image

**Example2: Catalan**
image

**Note**: this happens with most of the languages

### Steps to reproduce

1. Open the Expanded View
2. Go to Menu // Settings
3. Change the Language (i.e. Spanish)

### Error messages or log output

_No response_

### Version

10.10.2

### Build type

_No response_

### Browser

Firefox

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by digiwand**
## Explanation

Fixes: https://github.com/MetaMask/metamask-extension/issues/13856 and [the icon and text misalignment mentioned in the comment below.](https://github.com/MetaMask/metamask-extension/pull/14348#issuecomment-1088187635)

### Before
Screenshot 2022-04-04 at 2 08 00 PM
Screenshot 2022-04-04 at 2 08 11 PM
Screenshot 2022-04-04 at 2 08 00 PM

### After
Screenshot 2022-04-05 at 2 30 49 PM
Screenshot 2022-04-05 at 2 31 01 PM

### CODE REVIEW

**Comment by digiwand** [comment]
Note: I did consider this style update where the icon remains at the top of the row: 
Screenshot 2022-04-04 at 4 57 13 PM

Screenshot 2022-04-04 at 2 19 20 PM

Please reach out if you prefer this change over the one that has been implemented 

cc: @georgewrmarshall

**Comment by bschorchit** [comment]
Saya noticed that currently in prod the icons are not fully aligned (picture below). As I noticed you might have done a few things changes related to alignment, do you know if that is still an issue? 
No worries if it still is an issue, I'm just asking to update its status within the papercuts epic if needed. 

Screenshot 2022-03-17 at 20 04 45

**Comment by digiwand** [comment]
@bschorchit Thanks for relaying this concern from Saya! You two are right. It is slightly misaligned.

The icons are of different sizes and set to take up 18px height. With the icons left-aligned and at different widths, the text to the sides of the icons starts at different X positions. 

I fixed this misalignment by having each icon take an 18px x 18px area and centering the icons in this area.

**Review by jpuri — APPROVED** [review]

**Review by NiranjanaBinoy — APPROVED** [review]

**Review by georgewrmarshall — APPROVED** [review]
Nice work. LGTM!

**Pull request merged**
