### PR TITLE
Remove cross-env

### PR DESCRIPTION
**Pull request by whymarrh**
This PR removes `cross-env` from our scripts. We already don't use it in some scripts—we also use Bash and \*nix commands in many other scripts. Also Bash on Windows exists.

### CODE REVIEW

**Comment by whymarrh** [comment]
Welp, our shellcheck version has a false positive

**Comment by whymarrh** [comment]
I'll need to rebase this once #7951 is merged

**Comment by Gudahtt** [comment]
I would rather keep `cross-env`. Why would we want to make it more difficult for Windows developers to contribute?

I don't mind that we use linux-specific commands in our npm scripts meant for CI, but `test:unit` is pretty useful for local development.

**Comment by whymarrh** [comment]
Bash on Windows offers a way for this to work on Windows. It’s simply easier for us to have a single env (\*nix) that we support and actually ensure the dev process works on. It’s not just CI scripts but `lint:staged`, etc.

**Comment by Gudahtt** [comment]
WSL is far from ideal as a development environment; lots of people choose not to use it for good reason. It's buggy, slow, resource intensive, and can be difficult to integrate with Windows applications such as IDEs. I'd still prefer that we keep anything needed for developing working on PowerShell, especially given how easy that is for us to accomplish.

**Comment by whymarrh** [comment]
How about this: we only use cross-env to set 1 environment variable for mocha, I can move that one environment variable to a `test/env.js` that is required before each of the runs. Would that be a satisfactory replacement?

**Comment by whymarrh** [comment]
@Gudahtt updated—the current version of this PR should continue to work just as well on Windows

**Review by Gudahtt — APPROVED** [review]
LGTM!

**Pull request merged**
