### PR TITLE
Add icon to actionable message

### PR DESCRIPTION
**Pull request by darkwing**
Provides the groundwork for implementing the override block:

EditGasOverride

ActionIcon

### CODE REVIEW

**Review by danjm — DISMISSED** [review]
LGTM

**Comment by brad-decker** [comment]
Should we elevate this out of the swaps page if we intend to use it outside of swaps?

**Comment by darkwing** [comment]
Elevated out!

**Review by brad-decker — APPROVED** [review]

**Review by adonesky1 — APPROVED** [review]

**Review by Bow0628 — APPROVED** [review]

**Review by Bow0628 — APPROVED** [review]
@Bow0628 #11409 #11433 #11405 #11448 
Duplicate of #

**Pull request merged**
