### PR TITLE
Add `--leave-running` flag to E2E test script

### PR DESCRIPTION
**Pull request by Gudahtt**
The `--leave-running` flag has been added to the E2E test runner. This ensures the browser, ganache, and everything else stays running upon test failure. This is useful for local debugging, for investigating what state the extension was in when it failed.

Manual testing steps:  
  - Try running `yarn test:e2e:single --browser firefox --leave-running` to see that it works correctly for a working test (it should exit normally).
  - Try running `yarn test:e2e:single --browser firefox --leave-running` on a test that will fail (e.g. one that you introduced an error into). Everything should stay running. It should all exit cleanly after sending an interrupt (CTRL+C).

### CODE REVIEW

**Review by brad-decker — DISMISSED** [review]
I assume this is intended not to work yet with the metamask-ui file knowing that it'll eventually be replaced with using the fixtures?

**Comment by Gudahtt** [comment]
Oh! No, that was intended, I just forgot. I'll update this to do that too. That might take a while to get rid of after all.

**Comment by Gudahtt** [comment]
Ok, this should work with `metamask-ui.spec.js` now as well.

Spent some time trying to find an equivalent for `this.currentTest.state` for the `after` hook, but it doesn't appear to exist :thinking: :shrug:

**Comment by brad-decker** [comment]
that seems counterintuitive at the least. working well locally though!

**Review by brad-decker — APPROVED** [review]

**Pull request merged**
