### PR TITLE
UX MULTICHAIN: added connect account in account list menu item

### PR DESCRIPTION
**Pull request by NidhiKJha**
This PR is to add the connect account button in account list menu item

## **Related issues**

Fixes:[https://github.com/MetaMask/MetaMask-planning/issues/1967]( https://github.com/MetaMask/MetaMask-planning/issues/1967)

## **Manual testing steps**

1. Go to account list menu
2. Click on connect account, if account is not connected it should connect the account

### **Before**
Screenshot 2024-02-14 at 3 35 44 PM

### **After**
Screenshot 2024-02-14 at 8 04 17 PM

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by darkwing — CHANGES_REQUESTED** [review]
At present it looks like `connectAccount` assumes the currently selected account, so we'll need a change like this:

https://gist.github.com/darkwing/348a0a52b66eef2c301416d4d932e7b4

Still, I'm seeing this error eventually:

SCR-20240214-ktei

**Comment by darkwing** [comment]
Seeing this in `ui/pages/connected-accounts/connected-accounts.container.js`:

```
connectAccount: (address) =>
      dispatchProps.addPermittedAccount(activeTabOrigin, address),
```

I'm thinking `addPermittedAccount` could be the way to go!

**Comment by darkwing** [comment]
Also, adding a quick test in `ui/components/multichain/account-list-item-menu/account-list-item-menu.test.js` to ensure the correct action and account are used would be great!

**Comment by NidhiKJha** [comment]
> Also, adding a quick test in `ui/components/multichain/account-list-item-menu/account-list-item-menu.test.js` to ensure the correct action and account are used would be great!

@darkwing Updated the actions here, https://github.com/MetaMask/metamask-extension/pull/22941/commits/baaf4c1658954bca66379eb94bb6681f25dc2ee0

For the tests, since this component is accessible only in popup view, if I try  to add the test. It's not accessible for jest and it starts failing here  as the DOM doesn't render it in full screen view
Screenshot 2024-02-16 at 4 24 06 PM

**Comment by darkwing** [comment]
Would doing the following allow for testing?  

```
{process.env.MULTICHAIN || process.env.IN_TEST ? (
```

**Comment by NidhiKJha** [comment]
> added tests

Updated here https://github.com/MetaMask/metamask-extension/pull/22941/commits/69e1e37f9f26c5ab3aeda98cfd45d3221ab719ee

**Review by darkwing — APPROVED** [review]

**Review by vthomas13 — APPROVED** [review]

**Pull request merged**
