### PR TITLE
cherry-pick chore: revert recent gas api endpoint changes (#25230) into Version v11.16.11 

### PR DESCRIPTION
**Pull request by dbrans**
cherry-pick chore: revert recent gas api endpoint changes 04642d21f9feeccd09b16fa318c6c7876fd34ab1 (#25230) into Version v11.16.11 

Merge conflicts were resolved by comparing this PR diff with the [intended diff](https://github.com/MetaMask/metamask-extension/pull/25230/files).

```bash
CONFLICT (content): Merge conflict in app/scripts/metamask-controller.js
CONFLICT (content): Merge conflict in package.json
CONFLICT (content): Merge conflict in shared/constants/swaps.ts
CONFLICT (content): Merge conflict in shared/lib/swaps-utils.js
CONFLICT (content): Merge conflict in test/e2e/mock-e2e.js
CONFLICT (content): Merge conflict in test/jest/constants.js
CONFLICT (content): Merge conflict in yarn.lock
```

### CODE REVIEW

**Comment by dbrans** [comment]
@metamaskbot update-policies

**Comment by dbrans** [comment]
@metamaskbot update-policies

**Comment by dbrans** [comment]
@metamaskbot update-policies

**Comment by dbrans** [comment]
@metamaskbot update-policies

**Comment by danjm** [comment]
@metamaskbot update-policies

**Comment by sleepytanya** [comment]
Everything looks good. All gas settings appear to be correctly configured, with the information displayed in the user interface aligning with the data available on Etherscan.
Low gas https://etherscan.io/tx/0xa6c5b933ab216c10924b1da82344e71b08aa26c8021b59580c645e55570b8e11 



 Market gas https://etherscan.io/tx/0x8926234cb5ee52507c6a03b53f1952ced7c5a1f22863453d70b3b041fa04554a


Aggressive gas https://etherscan.io/tx/0x343017894053b0786c06ab2635af355916285393f588a93b1d2993cc7e3e5b62

**Review by sleepytanya — APPROVED** [review]

**Pull request merged**
