### PR TITLE
chore: Version v12.8.0

### PR DESCRIPTION
**Pull request by hjetpoluru**
## **Description**

Version v12.8.0

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/28503?quickstart=1)

### CODE REVIEW

**Comment by hjetpoluru** [comment]
@metamaskbot update-attributions

**Comment by hjetpoluru** [comment]
Version 12.8.0 Release Validation

Release Cut: November 15
Target Date for Release Sign-Off: November 22

Hi Teams! We can start testing and validating v12.8.0([builds](https://github.com/MetaMask/metamask-extension/pull/28503#issuecomment-2480210134)). Let's do this!

Instructions for Teams

Review Changes: Refer to the [Release Tracker for v12.8.0](https://docs.google.com/spreadsheets/d/1tsoodlAlyvEUpkkcNcbZ4PM9HuC9cEM80RZeoVv5OCQ/edit?gid=1885469311#gid=1885469311) to see all changes relevant to your team.
Testing status to update the PR testing status: In Progress, Passed, Failed (with comments), Blocked, or Skipped (for documentation or testing improvements).
Changelog status aids documentation. Select: Changed, Fixed, Added, or N/A if not required.
Type of Change helps determine the impact. It is broadly categorized as Functional(User facing or non), Non-Functional(regression or not), Non main change.
Log Bugs: If you find any issues, log them in the release tracker, and make sure you add the right labels on it: type-bug , regression-RC-x.y.z , (and release-blocker when needed).
Approval: After testing is completed, and the team is happy with their RC features/changes and there are no more issues to address, indicate your team's approval by marking the checkbox next to your team's name in comment. Optionally, leave a comment for additional information.
Your thorough review ensures a smooth and successful release. If you have any questions please reach out to extension platform team or in the [#metamask-qa](https://consensys.slack.com/archives/C01U65ZUS2E) slack channel. Thank you for your collaboration!

Teams to Sign Off 12.8.0 Release:

 Assets: @sahar-fehri / @alfeng6 - There are 12 Assets changes
 Bridge: @jclancy93 - There are 2 Bridge changes
 Confirmations: @sleepytanya / @cryptotavares - There are 27 Confirmations changes
 Contributor Experience/Tiger Team: @HowardBraham / @gauthierpetetin - There are 1 Contributor Experience changes
 Design System: @georgewrmarshall - There are 1 Design System changes
 Extension Platform: @danjm / @hjetpoluru - There are 21 Extension Platform changes
 MMI: @shane-t - There are No MMI changes
 Notifications: @Prithpal-Sooriya / @matteoscurati - There are 1 Notifications changes
 Snaps Platform: @Montoya - There are 3 Snaps Platform changes
 Swaps: @davibroc - There are 2 Swaps changes
 Transactions: @dbrans - There is 2 Transactions changes
 Wallet API: @adonesky1 - There is 1 Wallet API Platform changes
 Wallet Framework: @mikesposito - There are 8 Wallet Framework changes
 Wallet UX: @darkwing / @NidhiKJha - There are 7 Wallet UX changes

cc @jvbriones
Important Reminder:
Please be aware of the importance of starting your testing immediately to ensure there is sufficient time to address any unexpected defects. This proactive approach will help prevent release delays and minimize impacts on other teams' deliveries.

**Review by georgewrmarshall — COMMENTED** [review]
🟢 Approved on behalf of @MetaMask/design-system 
Checked the following PRs:
- https://github.com/MetaMask/metamask-extension/pull/28232 ✅

**Comment by hjetpoluru** [comment]
Testing for the @MetaMask/extension-platform changes is complete and everything works as expected.

**Comment by danjm** [comment]
@SocketSecurity ignore-all

These are snaps packages controlled by us that need that network access

**Review by danjm — APPROVED** [review]

**Pull request merged**
