### PR TITLE
Remove related UI code from the app dir

### LINKED ISSUE #15286: Remove UI related code from app directory
Dan's comment: 

https://github.com/MetaMask/metamask-extension/issues/15020#issuecomment-1180291101

"We should also make the refactors needed so that we are not importing any code from the UI into files under the app/ directory"

### PR DESCRIPTION
**Pull request by filipsekulic**
## Explanation
Removed all the ui references within the app directory. Moved those references into the app directory (app/constants/*.js and other files - see the code) so they are now being imported from that place in both the ui and app directory in order to prevent redundancy.

## More Information
Fixes: https://github.com/MetaMask/metamask-extension/issues/15286

* Relates to: #15023

### CODE REVIEW

**Comment by jpuri** [comment]
A lot of changes are lint related. I am not sure what has changed recently with lint configuration. Can you run `yarn run lint:fix` locally to fix this ?

**Comment by segun** [comment]
Work done so far.

I have removed all the UI related code in constant and moved them to shared/ folder. The rationale for this is that the code are being used by both App and UI, so should be in shared folder.

I also fixed unit tests accordingly and e2e tests as well.

To make rebase easier, I also squashed all the commits before rebasing....Although I can see the branch is out of sync again and will need another rebase. But this should be easy since the commits are squashed.

Unit tests are currently failing because of tests threshold, which basically means we need to write more tests.

**Comment by mirjanaKukic** [comment]
Verified by QA

**Comment by brad-decker** [comment]
@filipsekulic gonna need a rebase here.

**Comment by filipsekulic** [comment]
> @filipsekulic gonna need a rebase here.

Done :white_check_mark:

**Review by brad-decker — APPROVED** [review]

**Review by segun — APPROVED** [review]

**Pull request merged**
