### PR TITLE
Update buttons & colors to match design system

### PR DESCRIPTION
**Pull request by chikeichan**
btnstyle

@cjeria let's review on a call!

### CODE REVIEW

**Comment by cjeria** [comment]
@chikeichan looking good! The one state that's missing (or isn't working) is the Primary button's "active" state. I actually see the selector `:active` color:#0260A4; has been defined, but unfortunately it's not working in storybook?

Also the `font-family` is set to `system-ui` (in storybook at least), it should display Roboto. Is there some kind of inconsistency between storybook and the app?

**Comment by cjeria** [comment]
We should also aim to add the remaining buttons to storybook and align on how a consistent naming convention.

image

**Comment by chikeichan** [comment]
> @chikeichan looking good! The one state that's missing (or isn't working) is the Primary button's "active" state. I actually see the selector `:active` color:#0260A4; has been defined, but unfortunately it's not working in storybook?
> 
> Also the `font-family` is set to `system-ui` (in storybook at least), it should display Roboto. Is there some kind of inconsistency between storybook and the app?

Nice catch! It was an issue only in storybook as the extension uses a global style to change `font-family`. I have fixed it now.

**Comment by chikeichan** [comment]
> We should also aim to add the remaining buttons to storybook and align on a consistent naming convention.
> 

Fixed the active state, and updated storybook with all the button types!

**Comment by chikeichan** [comment]
@cjeria two questions:
- I notice that in your design sync today, all button text still retains ALL CAPS. In this PR, I have adjusted all button text to small caps based on figma -> let me know if that was intentional.
- some hover state uses color that is not on the palette. I have created one-off values that them - let me know if that was intentional as well.

Thanks!

**Review by danjm — DISMISSED** [review]

**Comment by cjeria** [comment]
@chikeichan Thanks!

> I notice that in your design sync today, all button text still retains ALL CAPS. In this PR, I have adjusted all button text to small caps based on figma -> let me know if that was intentional.

Caps case is correct! I changed it from UPPERCASE for the reason that uppercase is proven to be harder to read.

> some hover state uses color that is not on the palette. I have created one-off values that them - let me know if that was intentional as well.

That's intentional.

Noticed that the font weight in the design system is regular (400). I've spec'd them as bold (600), however, after experimenting with bold fonts in the inspector, I think a good in-between would be a medium weight font (500).

I also noticed button variations are now under the dropdown menu which took me a little while to find. I prefer to see them in the side nav. Is there a reason why they are behind a "type" dropdown?

**Comment by chikeichan** [comment]
> Noticed that the font weight in the design system is regular (400). I've spec'd them as bold (600), however, after experimenting with bold fonts in the inspector, I think a good in-between would be a medium weight font (500).

Cool - i will make this change

> I also noticed button variations (in storybook) are now under a dropdown menu which took me a little while to find. I prefer to see them in the side nav. Is there a reason why they are behind a "type" dropdown? It's a slight usability thing I think would make using the design system easier to navigate if component variations are listed in the side nav.

I put all variables in a `type` dropdown intentionally because I thought it was easier to navigate that way 😅 - let me change it back!

**Comment by cjeria** [comment]
Thanks @chikeichan let me know when you'd like me to review again!

**Comment by chikeichan** [comment]
Ready for review again @cjeria !

**Review by danjm — APPROVED** [review]

**Comment by cjeria** [comment]
Looks good!

**Pull request merged**
