### PR TITLE
Bump `@metamask/network-controller` to v12.2.0

### PR DESCRIPTION
**Pull request by jiexi**
## **Description**
Bumps our NetworkController version to the recent release. Needed because this change requires a minor update to spec scaffolding and is breaking other branches that includes these changes in a preview build. 

## **Manual testing steps**

None should be necessary as this shouldn't cause any noticeable changes

## **Related issues**

* See ttps://github.com/MetaMask/metamask-extension/pull/20822
* See https://github.com/MetaMask/metamask-extension/pull/20652#discussion_r1332277485

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained:
  - [x] What problem this PR is solving.
  - [x] How this problem was solved.
  - [x] How reviewers can test my changes.
- [x] I’ve indicated what issue this PR is linked to: Fixes #???
- [x] I’ve included tests if applicable.
- [x] I’ve documented any added code.
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)).
- [ ] I’ve properly set the pull request status:
  - [x] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by jiexi** [comment]
@metamaskbot update-policies

**Comment by jiexi** [comment]
@metamaskbot update-policies

**Comment by adonesky1** [comment]
Relevant Changelog entry: https://github.com/MetaMask/core/blob/main/packages/network-controller/CHANGELOG.md#added

**Review by adonesky1 — APPROVED** [review]
LGTM

**Review by brad-decker — APPROVED** [review]

**Pull request merged**
