### PR TITLE
chore: upgrade transaction controller to increase polling rate

### PR DESCRIPTION
**Pull request by matthewwalsh0**
## **Description**

Upgrade `@metamask/transaction-controller` to increase the pending transaction polling rate.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/28452?quickstart=1)

## **Related issues**

Fixes: [#3629](https://github.com/MetaMask/MetaMask-planning/issues/3629)

## **Manual testing steps**

Regression of pending transaction polling including:

- Alternate Chains
- Queued Transactions
- Sequential Transactions
- Multiple Transactions

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by sleepytanya** [comment]
@matthewwalsh0 
Blockaid message is shown for Legacy and EIP 1559 transaction:


https://github.com/user-attachments/assets/6ae52732-645b-4634-b396-4fc74f1a8100

**Comment by sleepytanya** [comment]
Sometimes STX is created with 0 gas fee, tx fails:



https://github.com/user-attachments/assets/c9c84669-3688-49e2-bfa9-5ddf0508187a


I also see console gas errors messages on Linea (can't reproduce, probably need fresh install), tx can be successfully submitted:

Screenshot 2024-11-19 at 02 52 26

Screenshot 2024-11-19 at 02 52 09

**Comment by sleepytanya** [comment]
Other functionality including queueing, nonce customization, cancel / speed up, multiple transactions on different networks function as expected.
I can't check STX + txs on other network due to the bug not related to current PR - https://github.com/MetaMask/metamask-extension/issues/28517

**Comment by sleepytanya** [comment]
Latest `develop` build

1. No Blockaid validation for Legacy and EIP 1559 transactions:



https://github.com/user-attachments/assets/e2ebecfc-d924-4bd7-9c9a-cbf3a05098a1

**Comment by sleepytanya** [comment]
Blockaid Legacy and EIP 1559 issue wasn't related to the current PR, fixed after merging the latest `develop`:


https://github.com/user-attachments/assets/e0831427-331a-4ea2-b926-0b7c1e17350d

**Review by vinistevam — APPROVED** [review]

**Review by OGPoyraz — APPROVED** [review]

**Review by digiwand — APPROVED** [review]

**Pull request merged**
