### PR TITLE
Import account disclaimer and change loose label to imported.

### PR DESCRIPTION
**Pull request by tmashuang**
- Add import account disclaimer

importaccountdisclaimer
newuiimportaccountdisclaimer

- Change Loose label to Imported

loosetoimported
newuiimportedlabel

### CODE REVIEW

**Comment by cjeria** [comment]
@tmashuang @danjm adding design feedback here for the new UI import account screen (see mockup).

import account

**Comment by cjeria** [comment]
@tmashuang I also notice that the "imported" label here is very dark, hard to read.

image

Can it be lightened to match the design (see below)
image

**Comment by lazaridiscom** [comment]
Short: "Your Seed Phrase **IS** your Account."

This tiny phrase would have had helped my back then to grasp this strange MetaMask thing sooner.

(curious: is this "would have had helped" me correct English? )

**Comment by tmashuang** [comment]
Updated Styling Imported Account Label and Import Account Disclaimer.

importedaccountslabel
importaccountdisclaimerv2

**Review by cjeria — APPROVED** [review]
Looks good @tmashuang

**Review by danjm — APPROVED** [review]
Reviewed code. Looks good.

**Pull request merged**
