### PR TITLE
Added Snaps Custom Confirmation

### LINKED ISSUE #11686: Snaps Custom Confirmation
We want to allow snaps to show custom confirmations to the user. This will allow snap devs to ask for user consent before taking certain actions, such as signing.

This custom confirmation can be very limited to start with, with just a custom title, maybe a custom subtitle, a custom text area, and "Confirm" / "Reject" buttons (or something similar). All custom text areas should be specified by the snap.

We should make it clear that the confirmation is coming from the snap, not from MetaMask. We don't know what it happens if the user confirms, whether the text is accurate, or how high or low risk the action being confirmed might be. All we know is that it's internal to the snap.

### PR DESCRIPTION
**Pull request by ritave**
fixes #11686
Screenshot 2021-12-13 at 18 19 32

### CODE REVIEW

**Comment by darkwing** [comment]
Hello @ritave !  Could we get a screenshot or video of how this will appear?

**Comment by ritave** [comment]
@darkwing I've updated the PR comment with a screenshot

**Comment by darkwing** [comment]
Code looks good but I feel like, from a design perspective, we should differentiate the basic text from the specific text like `message` and `account`, otherwise the text all just runs together.  Could we differentiate the font or use bold?

**Review by hmalik88 — COMMENTED** [review]
The screenshot doesn't seem to match the figma design, did we have something to pass in for title and subtitle?

**Comment by ritave** [comment]
@hmalik88 The header and subtitle are empty in the FilSnap example
@darkwing The text is provided by an external Snap, not Metamask, in the current release it's not planned the text to be style-able

**Review by rekmarks — CHANGES_REQUESTED** [review]
This is most of the way there, we just need to fix one thing before we merge, and make another change pending a new version of the `skunkworks` packages.

First, we are missing the disclaimer in the footer, above the buttons. The copy used for this footer we can iterate on, but we need some value there. The `add-ethereum-chain` confirmation template has a similar footer, and can be used as a reference.

<details><summary>Screenshot of designs</summary></details>

The footer is the only thing we need to fix to merge this PR. Secondly, there is the question of the parameters, specifically their names and purpose. I think the Filecoin Snap has lead us astray in terms of how we use the values we receive from `snap_confirm`, compounded by a poor review of mine of the method implementation.

At the moment, the `prompt` is used to populate the scrollable text area, while the title and subtitle components of the confirmation are unused. Instead, the `prompt` should be a short question used as the title of the confirmation, while the subtitle / description and text area contents should be optional.

I created a PR against `skunkworks` updating the method [here](https://github.com/MetaMask/snaps-skunkworks/pull/158), but fixing the footer issue is sufficient to merge this PR. We can update it per the `skunkworks` changes later.

**Comment by ritave** [comment]
Screenshot 2021-12-14 at 13 43 15
@rekmarks I've added the footer. I've rebased onto latest snaps branch and seems that origin and subjectMetadata are empty now, at least for FilSnap.

**Review by rekmarks — APPROVED** [review]
LGTM!

**Review by hmalik88 — APPROVED** [review]
LGTM.

**Pull request merged**
