### PR TITLE
Part of #17670: Replace Typography with Text component in cancel-speedup-popover.js

### PR DESCRIPTION
**Pull request by dhruvv173**
## Explanation
Partially fixes [#17670](https://github.com/MetaMask/metamask-extension/issues/17670)
Made changes by replacing the Typography component with Text component in the ```cancel-speedup-popover.js``` file
ui/components/app/cancel-speedup-popover/cancel-speedup-popover.js

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [x] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Comment by dhruvv173** [comment]
hey @NidhiKJha I created a new PR for this fix, it passes all the tests, please review this when possible.
Thanks!

**Review by NidhiKJha — APPROVED** [review]
LGTM! Thanks for your contribution

**Review by DDDDDanica — APPROVED** [review]

**Comment by DDDDDanica** [comment]
Hey @dhruvv173 thanks for contributing, it looks good !
However, can you add the before/after screenshot as comparison to make sure we didn't change the styles as required in https://github.com/MetaMask/metamask-extension/issues/17670?
> Before / After screenshots of changes in PR description or as comments near relevant code

Thank you !

**Comment by dhruvv173** [comment]
> Hey @dhruvv173 thanks for contributing, it looks good ! However, can you add the before/after screenshot as comparison to make sure we didn't change the styles as required in #17670?
> 
> > Before / After screenshots of changes in PR description or as comments near relevant code
> 
> Thank you !

hey @DDDDDanica I couldnt attach before/after screenshots as the story file does not exist on storybook

**Pull request merged**
