### PR TITLE
cherry-pick fix NFT mint simulations to v11.15.1

### PR DESCRIPTION
**Pull request by dbrans**
cherry-pick fix NFT mint simulations by updating transaction-controller (#24306) to v11.15.1

NOTE: This commit is _not_ a cherry-pick of an existing commit. To ensure peer dependencies were met, `yarn add @metamask/transaction-controller@^28.1.1` was run against v11.15.1 and the results were committed.

### CODE REVIEW

**Comment by danjm** [comment]
@metamaskbot update-policies

**Comment by dbrans** [comment]
@danjm, I'm at a loss for why the policy generation failed.

**Comment by dbrans** [comment]
@metamaskbot update-policies

**Comment by dbrans** [comment]
@metamaskbot update-policies

**Pull request closed without merging**
