### PR TITLE
Fix 12192 - Implement new metametrics onboarding screen

### LINKED ISSUE #12192: Help Us Improve View

### PR DESCRIPTION
**Pull request by darkwing**
Fixes: #12192

Supercedes https://github.com/MetaMask/metamask-extension/pull/12199/files

### CODE REVIEW

**Comment by adonesky1** [comment]
@darkwing would you mind adding the routing for this component to onboarding-flow.js?

**Comment by adonesky1** [comment]
@darkwing am I looking at the wrong mockups? https://www.figma.com/file/iCOjL3k1BkQqpYHFUVVFUZ/Extension-Onboarding?node-id=1535%3A16880

this is what I'm seeing in figma: 
Screen Shot 2021-10-14 at 1 55 59 PM

**Review by adonesky1 — DISMISSED** [review]
Looks good! There are a few css margin/width discrepancies with the designs but not going to block on those!

**Review by adonesky1 — DISMISSED** [review]

**Review by mcmire — DISMISSED** [review]
One small question, but looks good regardless.

**Review by adonesky1 — DISMISSED** [review]

**Review by adonesky1 — APPROVED** [review]

**Review by mcmire — APPROVED** [review]
Looks good!

**Pull request merged**
