### PR TITLE
Update Chinese translations.

### PR DESCRIPTION
**Pull request by shichangzhi**
Explanation:  Correct the translation of wrong words and sentences.

### CODE REVIEW

**Comment by wxy** [comment]
Don't tinker with this translation anymore, I did a full update (PR #12694) , to keep up with the latest English I18N.

**Comment by shichangzhi** [comment]
> Don't tinker with this translation anymore, I did a full update (PR #12694) , to keep up with the latest English I18N.

I looked through your PR ( #12694 ) and it seems that your work may be causing some errors. Maybe it's better to take things one step at a time. 
But your idea is very good. You can continue to perfect your translation, or I will try to retranslate the whole document when I'm done with what I'm doing.

**Comment by mcmire** [comment]
Hey, sorry it's taken us a while to get back to you. We have a lot of new translations coming in via #13206, so I'll wait until that's merged first.

**Comment by wxy** [comment]
> @shichangzhi the new translation system has had a few iterations merged now, would you mind rebasing and checking your translations against the new ones to see if the changes are still applicable/necessary?

The new translation system? Where is it? I would like to take over the translation of Chinese.

**Comment by brad-decker** [comment]
You may continue to make suggestions via pr, but its called crowdin and you can see the prs they open, its automated.

**Comment by brad-decker** [comment]
@wxy bump. Did you want to see this landed? If not please close the PR. If you do want to see this land please do a rebase for me :)

**Comment by wxy** [comment]
> @wxy bump. Did you want to see this landed? If not please close the PR. If you do want to see this land please do a rebase for me :)
I would be more than happy to pick it back up and provide a complete and timely translation if my PR could be reviewed and merged in a timely manner. As with this PR and my previous PR submission (#12694), no one has reviewed and merged it, or it has taken a long time, which is very discouraging.

**Comment by brad-decker** [comment]
@wxy I know it can be frustrating, and my sincere apologies. I just got back from vacation and will commit to reviewing this PR if the changes are made. I'm going to assign myself to this PR as well and we can work together on getting it landed.

**Comment by brad-decker** [comment]
@wxy when you are ready to rebase and get this ready for review, please re-open and I will take a look as swiftly as possible. Thanks for your contribution

**Pull request closed without merging**
