### PR TITLE
Adds MetaMask specific in-page ethereum provider.

### PR DESCRIPTION
**Pull request by JeffreyDoyle**
## 👋 Overview & Background

An issue with current ethereum wallet extensions is an unfortunate race condition each wallet faces in setting their provider to the `window.ethereum` variable. This inhibits an applications ability to support multiple ethereum wallets, since only one wallet can have their provider set to that variable at a time.

While efforts exist to [standardize ethereum provider implementations](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1193.md) (EIP 1193), their efforts aren't (and shouldn't be) directed towards standardizing the injection of providers into the `window` variable.

Powerful distributed applications desire an ability to allow users to specify which wallet provider they wish to use with their application. However, many ethereum wallet extensions exist, presenting users who enjoy having multiple wallets enabled in their browser the problem of having the enable and disable their wallets depending on which one they wish to use. This is a negative and annoying user experience for informed power users, and a source of confusion for people new to ethereum and distributed applications.

While wallets compliant with EIP 1102 [must support injecting their providers on `window.ethereum`](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1102.md) , there exists the possibility to increase usability of wallets and the dapp ecosystem as a whole if ethereum wallets _additionally_ inject their providers to unique window variables.

## 💡Proposed Changes

The PR injects a new in-page variable,

`window.MetaMaskEthereum` 

which will exist alongside `window.ethereum`. With this change, dapps can choose to support MetaMask specifically by creating their `Web3` instances using the `window.MetaMaskEthereum` provider. However, they do not necessarily need to as `window.ethereum` will exist as it does currently.

This small change allows for massive new possibilities for dapps. Developers can now enjoy allowing users to toggle between ethereum wallets by creating `Web3` instances dependant on which provider is available. Should a developer choose to prioritize MetaMask over other ethereum wallet extensions, they can check to see if `window.MetaMaskEthereum` is available to create their `Web3` instance before checking `window.ethereum` as per the standard.

## 👨‍💻 👩‍💻 Considerations

- This PR passes all tests.
- This PR has been tested against a wildly popular ethereum based distributed application, and works perfectly.

I would appreciate a developer with experience on this project to carefully review these non-breaking additions to verify they're acceptable.

Thank you for your time.

### CODE REVIEW

**Comment by danfinlay** [comment]
It's great that you've provided a solution to this problem.

In general, we'd like to minimize the amount that we pollute the global namespace.

It was recently suggested that we could instead reply to a MetaMask-specific `postMessage` and return a provider object, and that could be a way to avoid additional global namespace pollution, while also solving the same problem.

@MichahZoltu has been a big proponent of this alternative approach, I'd like us to consider it before merging.

**Comment by MicahZoltu** [comment]
@JeffreyDoyle I don't think having a MetaMask specific anything is the right solution here.  That just ends up with dapp developers needing to look for dozens or hundreds of different potential Ethereum providers and what is worse, a dapp written at time `t` will not be able to work with a provider developed at time `>t`.

On top of that, there are several problems with injecting stuff into `window` directly.  For starters, plugins have to [hack around](https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/contentscript.js#L33-L44) the fact that the browser-plugin security model doesn't allow them to inject into the page's JS environment.  Second, it is not possible (from what I can find) to create a page wrapper page that allows you to inject into the sub-page's window.  This means you cannot create a wallet (hosted locally or on IPFS or something) that looks like this:
```html
<body>
    <iframe src.bind='queryStringParam1'/>
    <script>
        document.querySelector('body iframe').contentWindow.ethereum = ...
    </script>
</body>
```

The recommendation from browser authors is to use events to communicate between parent/child pages and page/extensions.  By design, you can send/receive events between an iframe parent and child and between a plugin and page.

The nice thing about using events is that we can easily do one-to-many so a user may have multiple connected providers that can advertise themselves to the dapp.  For example, if someone loads a page in an iframe provider host while also using MetaMask extension, the dapp would receive an advertisement (via events) from both MetaMask and the iframe host which it can then present to the user using information provided in the advertisements.

The way I envision the workflow going is by starting with the advertisement, which is _requested_ by the dapp.  Such a protocol may look something like this:
```typescript
export interface BaseRequest<T> { ... } // boilerplate for requests
export interface BaseResponse<T> { ... } // boilerplate for responses
export interface BaseSuccessResponse<T> extends BaseResponse<T> { ... } // boilerplate for successes
export interface BaseFailureResponse<T> extends BaseResponse<T> { ... } // boilerplate for failures

export namespace Hello {
	export type Type = 'hello'
	export interface Protocol {
		name: string
		version: string
	}
	export interface Request extends BaseRequest<Type> { }
	export interface SuccessResponse extends BaseSuccessResponse<Type> {
		/** used to allow the application to communicate with a specific provider in the case when there are many available providers */
		provider_id: string
		/** the client must communicate with this provider using one of the protocols listed here */
		supported_protocols: Array<Protocol>
		/** the friendly name of this provider to present to the user */
		friendly_name: string
	}
	export interface FailureResponse extends BaseFailureResponse<Type> { }
	export type Response = SuccessResponse | FailureResponse
}
```

The dapp would fire a `Hello.Request` event over a well known channel (e.g., 'EthereumHandshake-client' named event on window).  Any providers that were listening at the time that event was fired would then respond to the request over a well known channel (e.g., 'EthereumHandshake-provider' named event on window) with information like the user-friendly name of the provider so the dapp can present a list of providers for the user to choose from.  The provider would also express what protocol it speaks for further communication.  The protocol allows us to iterate on protocols over time and support graceful degradation when either the provider or the dapp doesn't support some newer protocol.

Once the dapp receives the provider's response, it can then start communicating with the provider.  One thing it may do as a first step is ask the provider what capabilities it has before proceeding.  For example, a particular provider may not provide signing capabilities which could impact whether (or how) the dapp uses that provider.

All communication between the provider and the dapp would be done via events.  Each provider would have its own event channel (e.g., events on window named `MyProtocol-client-<provider_id>` and `MyProtocol-provider-<provider_id>`).  Note that in these examples we have separate channels for client->provider communication and provider->client communication to simplify implementation, as you don't have to ignore your own outgoing messages on the channel.

----

This system is a notable departure from the current system, but I think it solves several problems at once.  Not only does it follow the paradigm that browser specification authors are trying to push towards (use events for extra-page communication), but it also addresses the one (dapp) to many (providers) issue as well.  On top of that, it provides an avenue for providers to enhance user privacy by simply _not_ responding to the handshake event if the user has not enabled the provider for that particular application.

----

I have a spike on this that can be found at https://github.com/Zoltu/recoverable-wallet/blob/08aa879bf2bdcbe376f1f2c2a72eebd34b6bfba1/browser-extension/source/shared.ts#L48, though it is under active development embedded in another project so don't rely on that link to survive indefinitely.

**Comment by danfinlay** [comment]
I agree with most of what Micah says above. One small point of divergence:

> it provides an avenue for providers to enhance user privacy by simply not responding to the handshake event if the user has not enabled the provider for that particular application.

We briefly tried this out in the past, and it made for  impossible Dapp UX, where a dapp wouldn't know whether the user didn't have a web3 browser or if they weren't signing in, so they didn't know what to suggest to help sign in.

I'd also like to just point out that events are also pretty flawed. For example, they have their own global namespace, and so Micah is still suggesting creating client-specific message channels, and it's already a degree of authority leakage that extensions can listen to each others' communication, but that's what we have to work with.

That said, the call-response `EthereumHandshake-client` and `EthereumHandshake-provider` pattern seems like a good compromise. Clients could decide for themselves whether to reply if not signed in but installed, and the only shared namespace is the protocol itself.

We just have to hope no websites rely on events by those names ;)

**Comment by MicahZoltu** [comment]
I actually am not a big advocate of the privacy thing I mentioned, I just have heard many people advocate it in the past and wanted to show that events make such a thing _possible_ (even if I don't think it is desirable, it potentially allows someone to build a privacy-focused extension).

We could have the handshake do some kind of encryption, where the dapp exposes a transient public key in the Hello.Request and then each signer would respond with a transient public key encrypted in the Hello.Response (so only the client can read it).  Other providers then wouldn't be able to read the communication between the client and other providers.  We could further make it so the provider ID is also encrypted and randomly selected ([1,2^256] or something).  If there are many providers that are all communicating, this would further prevent other providers from listening in.

Note: all of the above is a possible solution, though I am not convinced there is a problem here worth solving.  I would be curious to hear about scenarios where the user is using providers/plugins/page hosts that they don't trust.  Already, anything that can listen in on events for the page is in a pretty elevated position, anything we do to try to protect the user further seems "meh" at best.

**Comment by danfinlay** [comment]
> We could have the handshake do some kind of encryption, where the dapp exposes a transient public key in the Hello.Request and then each signer would respond with a transient public key encrypted in the Hello.Response (so only the client can read it).

I don't want to go down this rabbit hole, I've been here before, but briefly: There's no way to verify that this initial key is from the dapp and not from one of the other installed extensions.

But I do get your point, it makes some new things possible, and is more versatile, agreed.

**Comment by whymarrh** [comment]
Hey @JeffreyDoyle, thanks for this PR. Ultimately this isn't something we're going to merge as it further pollutes the global namespace and further fragments the way dapps look for wallets. Both yourself and @MicahZoltu have spent a lot of time thinking about this, as have we, so I don't mean to shut down the conversation (feel free to continue here!) but the code changes suggested aren't quite something we'll merge.

**Pull request closed without merging**
