### PR TITLE
New UI

### PR DESCRIPTION
**Pull request by sdtsui**
*Sept 27th*
 - Add validation to Send Token/Ether
 - Various Styling fixes
 - Restore notification functionality
 - Add Export private key flow
 - Use Gas Estimator to estimate gas
 - New ShapeShift UI is implemented in mascara first time flow PR

*Sept 20th*
 - Add Token Done
 - Restoring old pop-up functionality

*Sept 12th*
- Send Token Integration done
- Add actions to pull in exchange rate for tokens
sendtoken

*Sept 5th*
- Send Transaction UI + Integration
- Send Transaction confirmation
- Styling updates to be nearly pixel-perfect to Inivision
- Send Token UI work start (20%)

*Aug 20th:*
- Component refactor + State Management for all NewUI Modals

*Aug14th:*
- Dropdowns extracted so its easier to hook up new functionality
- Modals extracted to support the 3+ different modal types recently added to prototype
- Added Stylelint, stylefmt, and high-level CSS cleanup

*Aug 10/11th Updates:*
- Added new selectors for improved state management
- Organized CSS
- Worked on responsive UI for :
---- Transactions List
-------- Implement infinite scrolls (no lazy loading) for wallet view
---- Balance Display Components

---

*Aug 9th Updates:*
- Modal centering tweaks, adjust text sizes for modals on multiple viewports.
- Note to self: will need to refactor modals + to support new designs (many different modals are needed now, to access all functionality).
- Note to self: will need to refactor dropdowns to support different viewports...probably use styles instead of inline  #css.
- Paying down some tech debt, did planning on new selector logic, making grabbing of addresses easier.

---

*Aug 8th Updates:*
- Branch is named `NewUI-flat`, to differentiate from `NewUI`.
- Also introducing [@lhr0909](http://cdn.rawgit.com/lhr0909/SimonsResume/master/simon-liang-resume.pdf) who is helping out a little with state management/testing while I crank out the UI.
- Responsive Modal layout is done. Still some minor tweaks/stuff to hook up, but it's ready to be looked at. Feedback welcome. 
modal-demo

---

Work ongoing on [sdtsui](https://github.com/sdtsui/metamask-extension).

### CODE REVIEW

**Comment by kumavis** [comment]
Hi @lhr0909 how was your time at Hooli? `Lead Developer, Hooli XYZ` :laughing:

**Comment by kumavis** [comment]
Ah, i see its real - how funny http://www.hoolix.com/

**Comment by lhr0909** [comment]
@kumavis There we go! We liked the show so much and we named our company Hooli. Piped Piper just doesn't rhyme as well in Chinese ;)

**Comment by sdtsui** [comment]
Leaving a note for Jazzicon above /\
Weird behavior. Fixed now. See [3](https://github.com/flyswatter/jazzicon/issues/3) for more info.

**Comment by frankiebee** [comment]
@kumavis deployed this to mascara to take a look at it. Some things i found:

- the back button dosent work on the qr screen and is a funny size.
- when screen is smaller side menu does not collapse when you click something
- send button goes no where (i'm assuming it's because you havent gotten to it yet)

**Comment by frankiebee** [comment]
Looks good so far though 😊

**Comment by kumavis** [comment]
fyi we made some changes on how tests are started on master

**Comment by kumavis** [comment]
should we be resolving merge conflicts? sounds like it could add up to a painful process if we dont take care of it now and then

**Comment by lrgeoemtry** [comment]
## Request

Is there a repo to identify scaling solutions for Metamask moving forward? 

Wanting to scale our project in conjunction with this new trajectory. 

[GitHub followers](https://github.com/HERCone)

**Comment by lrgeoemtry** [comment]
Perhaps a new Export Format so the custom names of the accounts are...accounted for during the import format UI.

**Pull request closed without merging**
