### PR TITLE
[WIP] document/rearrange metamask-controller.js, re #3568

### PR DESCRIPTION
**Pull request by ghost**
commit 904f00e rearranges method positions in the file, and thus its difficult to review.

d8f5150 is easier to follow.

### CODE REVIEW

**Comment by lazaridiscom** [comment]
@danfinlay , is this the test-system or my changes? (changes _should_ be neutral...)

**Comment by danfinlay** [comment]
Not sure, the mascara tests failed to find a `button` element. Re-running just in case it's a bad test. It may be related to the translation features we've been merging into `master`. Will review in more detail soon, this looks very good, thank you!

**Comment by kumavis** [comment]
Nice - would be cool to start generating some doc pages with jsdoc

**Review by kumavis — APPROVED** [review]

**Review by kumavis — APPROVED** [review]

**Comment by lazaridiscom** [comment]
@kumavis , thanks!

> Nice - would be cool to start generating some doc pages with jsdoc

I assume you have to include a step into the build-system, right?

As for "branch can be safely deleted. ", I can trust gh here?

**Pull request merged**
