### PR TITLE
fix: unit flaky test `AddContact component › should disable submit button when input is not a valid address`

### LINKED ISSUE #27624: Flaky unit test "AddContact component › should disable submit button when input is not a valid address"
### Describe the bug

The unit test "AddContact component › should disable submit button when input is not a valid address" appears to be flaky.

### Expected behavior

_No response_

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/actions/runs/11178468044/job/31076102462

### Steps to reproduce

`yarn jest ./ui/pages/settings/contact-list-tab/edit-contact/edit-contact.test.js`

### Error messages or log output

_No response_

### Detection stage

On the development branch

### Version

develop

### Build type

None

### Browser

Other (please elaborate in the "Additional Context" section)

### Operating system

Other (please elaborate in the "Additional Context" section)

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by seaona**
## **Description**

The unit test for Add Account is flaky as sometimes the state[name].stage var is undefined so it breaks at this point:

Screenshot from 2024-10-18 09-22-26

Update: [as Mark pointed out](https://github.com/MetaMask/metamask-extension/pull/27941#issuecomment-2452364332), another flakiness point appeared after the first one was fixed, also due to missing some state mocks.

The fix is to add the missing mocks in the test setup, so they always defined.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/27941?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/27624

## **Manual testing steps**

1. Check runs. After the 2 fixes, I've re-run the unit tests in github x3 times and they all passed

Screenshot from 2024-11-05 10-57-30

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by Gudahtt — DISMISSED** [review]
LGTM!

**Review by pedronfigueiredo — DISMISSED** [review]

**Comment by Gudahtt** [comment]
Just hit a new error for this test on this branch: https://github.com/MetaMask/metamask-extension/actions/runs/11626222545/job/32377483362?pr=27941

```
FAIL ui/pages/settings/contact-list-tab/add-contact/add-contact.test.js (8.068 s)
  ● AddContact component › should disable submit button when input is not a valid address

    TypeError: Cannot convert undefined or null to object
        at Function.values (<anonymous>)

      1608 |
      1609 | export const getEnabledSnaps = createDeepEqualSelector(getSnaps, (snaps) => {
    > 1610 |   return Object.values(snaps).reduce((acc, cur) => {
           |                 ^
      1611 |     if (cur.enabled) {
      1612 |       acc[cur.id] = cur;
      1613 |     }

      at values (ui/selectors/selectors.js:1610:17)
      at node_modules/reselect/lib/index.js:76:25
      at node_modules/reselect/lib/index.js:36:25
      at node_modules/reselect/lib/index.js:90:33
      at node_modules/reselect/lib/index.js:36:25
      at node_modules/reselect/lib/index.js:86:37
      at node_modules/reselect/lib/index.js:36:25
      at fetchResolutions (ui/ducks/domains.js:104:48)
      at fetchResolutions (ui/ducks/domains.js:192:31)
```

**Comment by Gudahtt** [comment]
It looks like there is more missing from the state mock. Maybe we should make a helper function to return a "blank" global state that includes everything 🤔

**Comment by seaona** [comment]
> It looks like there is more missing from the state mock. Maybe we should make a helper function to return a complete initial global state 🤔

oh thank you for catching this, Mark! I'll review what else is missing and add it in this PR using you recommendation :pray:

**Comment by seaona** [comment]
:information_source:  After the last changes, I've re-run the unit tests x3 times and they passed consistently

**Review by Gudahtt — APPROVED** [review]
LGTM!

**Review by pedronfigueiredo — APPROVED** [review]

**Pull request merged**
