### PR TITLE
Issue 3505 | Transpile to ES5

### LINKED ISSUE #3505: Version 4.x no longer compiling to es5
Expected behaviour: not a blank window. I don't know what it should look like, never used it before.
Actual behaviour: blank window.

metamask_01a

Metamask version: 4.2.0
Browser: Chrome Version 46.0.2490.71  (yes, very old, but it's the latest version I can run on this particular machine).
OS: Linux SolydK 201412 (bastardised Debian Wheezy/Jessie hybrid)

Popup log says:

metamask_01b

And background log says:

metamask_02a

These logs don't match any of the other "blank window" reports.

### PR DESCRIPTION
**Pull request by liberty-rowland**
Fixes #3505 

Babel step responsible for transpiling to ES5 was removed here: https://github.com/MetaMask/metamask-extension/pull/2975/files#diff-b9e12334e9eafd8341a6107dd98510c9L381

This PR re-adds this step, after `uglify-es`. No memory leaks (reason for change above) were observed locally with this modification.

In order to prevent this regression in the future, I also added a test that automatically checks `dist` after the `npm run dist` script to ensure it's valid `es5` after a build.

EDIT: Would be nice to add this check to the circleCI. I'm not sure exactly which test suites are run there. Do these CI scripts call `npm run dist`? If not, which script would I want to add this to?

### CODE REVIEW

**Review by danfinlay — APPROVED** [review]
Looks good, thank you!

**Comment by kumavis** [comment]
@ryan-rowland your PR caused the builds to no longer be browserified somehow, and was reverted.

we can revisit this again

**Comment by ryan-rowland** [comment]
Uh oh, that doesn't sound good. I'll review.

**Comment by kumavis** [comment]
@ryan-rowland repro: 
- npm install
- npm run dist
- drop dist/chrome into chrome extensions tab
- see that ui does not boot, open console for error message "require is undefined"

**Pull request merged**
