### PR TITLE
Web3 1.0 "subscription" support

### PR DESCRIPTION
**Pull request by matthewlilley**

### CODE REVIEW

**Comment by kumavis** [comment]
Thanks for the contribution, please try to avoid out-of-bound changes

**Comment by lazaridiscom** [comment]
[pj.code.guide]

@matthewlilley , just a general remark: your "general cleanup"  (e.g. imports, whitespace, coding-style) should affect only(!) your new/own code, in order to avoid to create to much distracting "noise" in your PR. So, even if those changes are 100% correct or even mandatory, you do not make them in one pass with the new functionality (your task was anyway not a "code cleanup").

Some of your changes affect "coding-style" (preferences), and there you should simply adapt the existent style of the module-owner.

**Comment by matthewlilley** [comment]
Opps, this is what happens when you're running on no sleep. For the sake of clarity I'll close this and create a fresh one. I was supposed to add those changes to a local branch.

**Comment by matthewlilley** [comment]
@ryan-rowland #1 Absolutely, less lines is always good with me. #2 Agree on this as well.

**Comment by lazaridiscom** [comment]
[pj.code.guide] - Keep return statements in their own line

use:

```js
function clearSubscriptions() {
  if (!inpageProvider.subscriptions) {
    return
  }

  inpageProvider.sendAsync(...)
}
```
avoid:

```js
function clearSubscriptions() {
  if (!inpageProvider.subscriptions) { return }

  inpageProvider.sendAsync(...)
}
```

**Comment by lazaridiscom** [comment]
[pj.code.review] - Within a code-review, focus to verify code functionality first (e.g.: is the new feature provided stable, is the bug fixed). Only **after** this is confirmed, a detail-level can start. Avoid in any case to point out issues which are anyway processed by automatisms (e.g. "lint").

**Comment by lazaridiscom** [comment]
> Functionality looked good

Nice to know.

Can you possibly explain me why the web3 library is still not changed to version 1.0? (see my quetion here: https://github.com/MetaMask/metamask-extension/pull/4047#pullrequestreview-114177970)

**Pull request closed without merging**
