### PR TITLE
Update messages.json

### PR DESCRIPTION
**Pull request by MATsxm**
Few fr updates... 😉

## Explanation

EASY FIX - just FR t9n are missing and some messages need to be added.
Improvement, no real issues

I have read the CLA Document and I hereby sign the CLA

### CODE REVIEW

**Comment by MATsxm** [comment]
> **CLA Signature Action:**
> 
> Thank you for your submission, we really appreciate it. We ask that you read and sign our [Contributor License Agreement](https://metamask.io/cla.html) before we can accept your contribution. You can sign the CLA by just by adding a comment to this pull request with this exact sentence:
> 
> > _**I have read the CLA Document and I hereby sign the CLA**_
> 
> By commenting with the above message you are agreeing to the terms of the CLA. Your account will be recorded as agreeing to our CLA so you don't need to sign it again for future contributions to this repository.
> 
> **0** out of **1** committers have signed the CLA. ❌ @MATsxm

I have read the CLA Document and I hereby sign the CLA

**Comment by MATsxm** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by CryptoGodfatherVA4 — APPROVED** [review]

**Comment by MATsxm** [comment]
Don't know what to do at this point 🤔

**Comment by digiwand** [comment]
Hi @MATsxm, first and foremost, thank you for finding and proposing these FR translations! 

not sure what is going on with the CLA signature. Let's try again? Your signature looks right to me.

There are two things I'd like to mention in regards to the code: 
1. We have a process to add i18n translations after adding English translation messages. We coincidentally have a call with our translation vendor tomorrow. We should be able to provide you with another update soon. 
2. `test-lint` is failing because it looks for a direct 1:1 mapping of the description from `app/_locales/en/messages.json`. The description describes the message or placeholder(s), and it is not shown in the UI.
```
**fr**: 4 missing descriptions
Messages with missing descriptions:
  - [ ] acceptTermsOfUse
  - [ ] accessAndSpendNotice
  - [ ] accessAndSpendNoticeNFT
  - [ ] accountNameDuplicate
```

**Comment by MATsxm** [comment]
Thanks,
Just let me know if I can help as it seems few strings are missing in the fr-FR version 😉

**Comment by adonesky1** [comment]
@GuillaumeRx would you mind reviewing these translations?

**Comment by digiwand** [comment]
@MATsxm can we update the descriptions to match the `en/messages.json` file descriptions? I can also update these as well

**Comment by MATsxm** [comment]
Ok then...
There's a lot to do in fact: description + some strings are also missing regarding the 'en' version.
I pushed this one to check that you would merge or at least work on it and then.... not waisting my time :wink: (believe me it happens often :rofl: ) . 
Now that I know it's not :grin: , I'm going to work on it this week-end and come up with a brand new PR.

**Comment by MATsxm** [comment]
New PR for :fr: t9n to come...

**Pull request closed without merging**
