### PR TITLE
fix: lock and unlock events

### PR DESCRIPTION
**Pull request by rynst**
[Investigating Issue #10368](https://github.com/MetaMask/metamask-extension/issues/10368)

### CODE REVIEW

**Comment by rsteubs** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by niconiahi** [comment]
what's the status on this? would be neat to have it already

**Comment by rsteubs** [comment]
Still working on it @niconiahi

**Comment by rsteubs** [comment]
After digging into this, it looks like lock events just aren't added:
On `line 321` of https://github.com/MetaMask/providers/blob/main/src/BaseProvider.ts, `There are no lock/unlock events.`

I have a commit for this, though there might be other issues to getting it working.  Closing since this is a feature, rather than a bug.
https://github.com/rsteubs/providers/commit/0951d26fefc06bd646df4decf9cbb132fd027918

**Pull request closed without merging**
