### PR TITLE
Fix edit-gas-display render Storybook

### LINKED ISSUE #12926: Fix EditGasDisplay in storybook
**Describe the bug**
EditGasDisplay storybook is broken and needs to be fixed. Originally in this PR #12388

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Go to [EditGasDisplay on storybook](https://metamask.github.io/metamask-storybook/index.html?path=/story/ui-components-app-edit-gas-display-edit-gas-display-stories-js--basic)
2. See error

**Expected behavior**
It should display the EditGasDisplay ui

**Screenshots**
Screen Shot 2021-12-01 at 9 19 50 AM

### PR DESCRIPTION
**Pull request by bestony**
## Explanation

fix #12926  by add Optional chaining

## More information

* Fixes: #12926 

## Screenshots/Screencaps

image

### Before

image

### After

image

### CODE REVIEW

**Comment by bestony** [comment]
cc @georgewrmarshall

**Review by georgewrmarshall — APPROVED** [review]
lgtm!

**Review by darkwing — CHANGES_REQUESTED** [review]
Looking at `isLegacyTransaction(transaction) {` in shared/modules/transaction.utils.js, this should still bomb because:

```
export function isLegacyTransaction(transaction) {
  return (
    typeof transaction.txParams.maxFeePerGas === 'undefined' &&
    typeof transaction.txParams.maxPriorityFeePerGas === 'undefined' &&
    (typeof transaction.txParams.gasPrice === 'undefined' ||
      isHexString(transaction.txParams.gasPrice))
  );
}
```

We'll need a transaction for this to work properly.

**Comment by georgewrmarshall** [comment]
@darkwing it seems to work? I've verified it works in storybook and it looks like this optional object operator is a common pattern used with:

```
useSelector(checkNetworkAndAccountSupports1559) &&
    !isLegacyTransaction(transaction?.txParams)
```

Screen Shot 2022-06-15 at 1 12 03 PM

Screen Shot 2022-06-15 at 12 53 36 PM

**Comment by georgewrmarshall** [comment]
We also have 2 `isLegacyTransactions` and the one being used here is:

```
export function isLegacyTransaction(txParams) {
  return txParams?.type === TRANSACTION_ENVELOPE_TYPES.LEGACY;
}
```

Screen Shot 2022-06-15 at 1 14 38 PM

**Review by darkwing — APPROVED** [review]

**Pull request merged**
