### PR TITLE
Improving identicon settings accessibility

### LINKED ISSUE #13753: Make Identicon Settings More Accessible
### Describe the bug

I noticed that the identicon settings makes you specifically click the circular image but you can't also click the text, which is what you'd expect as form `label`.

### Steps to reproduce

1. Go to Settings > General
2. Click the verbiage next to either circular image
3. The preference doesn't change

### Error messages or log output

_No response_

### Version

10.10.0

### Build type

_No response_

### Browser

Firefox

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ryanml**
Fixes: https://github.com/MetaMask/metamask-extension/issues/13753

https://user-images.githubusercontent.com/8732757/155673998-7170a82b-0dc6-4a4e-bab9-acfb138f9310.mov

### CODE REVIEW

**Review by NiranjanaBinoy — DISMISSED** [review]

**Review by darkwing — CHANGES_REQUESTED** [review]
This is a slight improvement but I think we need to make the element a `<button>` instead of a `div` so that it's keyboard accessible.

**Comment by ryanml** [comment]
@darkwing - I've made the change for keyboard accessibility:
https://user-images.githubusercontent.com/8732757/155790514-56443f0c-0366-4a4d-b08c-f92069826628.mov

**Review by darkwing — DISMISSED** [review]
Nice improvement!  I think we can improve this in 2 ways:

1.  `background: unset` will get rid of the gray background
2.   We should add a transparent border around the unselected item so that there's no height jump

**Review by ryanml — COMMENTED** [review]
Thanks @darkwing - updated

**Review by brad-decker — APPROVED** [review]

**Review by jpuri — APPROVED** [review]

**Pull request merged**
