### PR TITLE
Remove Unused CSS: ConnectedStatusIndicator #19587

### LINKED ISSUE #19587: Remove unused CSS: ConnectedStatusIndicator
### Description
It seems that the styles for the `ConnectedStatusIndicator` component in `ui/components/app/connected-status-indicator/index.scss` is not being used and can be removed.

Screenshot 2023-06-13 at 9 52 50 AM

### Technical Details
- Check that the className `connected-status-indicator` is not being used 
- Remove style sheet and all references from code base

### Acceptance Criteria
- Good explanation for checking if styles are being used in PR description
- Stylesheet and references to `ui/components/app/connected-status-indicator/index.scss` have been removed

### Difficulty: beginner
Good first issue for contributors that have experience with searching a codebase, sass and writing good PR descriptions

### PR DESCRIPTION
**Pull request by Jainex17**
## Explanation

* Fixes #19587 

This pull request aims to fix issue #19587 by removing the unused CSS related to the ConnectedStatusIndicator component. The connected-status-indicator/index.scss file and its associated import statement have been deleted, as they are no longer being used in the codebase.

## Changes Made

1. Deleted the connected-status-indicator/index.scss file.
2. Removed the @import 'connected-status-indicator/index'; line from app-components.scss.

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [x] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

Please review the changes and merge this pull request if everything looks satisfactory.

Thank you!

### CODE REVIEW

**Review by brad-decker — APPROVED** [review]

**Review by NidhiKJha — APPROVED** [review]
LGTM! Thanks for your contribution. Need to wait for the build to pass and we can merge this PR :)

**Comment by Jainex17** [comment]
> **CLA Signature Action:**
> 
> Thank you for your submission, we really appreciate it. We ask that you read and sign our [Contributor License Agreement](https://metamask.io/cla.html) before we can accept your contribution. You can sign the CLA by just by adding a comment to this pull request with this exact sentence:
> 
> > _**I have read the CLA Document and I hereby sign the CLA**_
> 
> By commenting with the above message you are agreeing to the terms of the CLA. Your account will be recorded as agreeing to our CLA so you don't need to sign it again for future contributions to this repository.
> 
> **0** out of **1** committers have signed the CLA. ❌ @Jainex17

I have read the CLA Document and I hereby sign the CLA

**Comment by Jainex17** [comment]
Thank you for reviewing my contribution! I appreciate your feedback and guidance throughout the process. I'm glad I had the opportunity to contribute to this project. Let me know if there are any further steps or actions required from my end.✨

**Comment by darkwing** [comment]
@Jainex17 Thank you!  I think your comment must just be `I have read the CLA Document and I hereby sign the CLA`, without the quoted stuff.  Thank you!

**Comment by Jainex17** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Jainex17** [comment]
@NidhiKJha Thank you for guiding me. I see that two tests have failed on CircleCI. I appreciate your help so far. Is there anything specific I can do to assist in resolving this issue? Your guidance is greatly appreciated.

**Pull request merged**
