### PR TITLE
UX Multichain: Updated app header account picker and address button

### PR DESCRIPTION
**Pull request by NidhiKJha**
This PR is to update the following changes in App-Header:
1. In the Account Picker,
- Updated the AvatarSize
- Removed address since address now has a copy button
2. Updated Adress text and copy button
3. I have also removed the copy button which was earlier introduced to remove connections icon for Multichain.

## **Related issues**

Fixes: [1816](https://github.com/MetaMask/MetaMask-planning/issues/1816)

## **Manual testing steps**

1. Run extension with `MULTICHAIN=1 yarn start`
2. Check for copy button under the account picker

### **Before**
Screenshot 2024-01-23 at 4 36 18 PM

#### Full Screen
Screenshot 2024-01-23 at 4 35 14 PM

#### Extension View
Screenshot 2024-01-23 at 4 35 29 PM

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [x] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by darkwing — CHANGES_REQUESTED** [review]
A few requests/suggestions:

1.  Can we make the entire address a `button` so that I can click the shorten address and get the copy functionality as well?
2.  I think I added a `showAddress` prop to the `AccountPicker`; is that still needed with these changes?  (I guess maybe send flow?)
3.  Is there a way we can better center the address?  The `0x` pops out on the left, but the buttons line up on the right.  Just a thought.

SCR-20240123-iqoe

**Comment by NidhiKJha** [comment]
> 1. Can we make the entire address a `button` so that I can click the shorten address and get the copy functionality as well?

Updated here https://github.com/MetaMask/metamask-extension/pull/22637/commits/cbaef93c121041dbbb3e57ba133a265c85034977

**Review by vthomas13 — DISMISSED** [review]

**Review by darkwing — CHANGES_REQUESTED** [review]
As part of these changes, we need to remove the blue address button:

SCR-20240131-jkdp

Also, should we add a hover background to the address that looks like the Account Picker's?

**Comment by NidhiKJha** [comment]
> As part of these changes, we need to remove the blue address button:
Updated here https://github.com/MetaMask/metamask-extension/pull/22637/commits/a7497f83766670e5d597bbce3534ec1e7b787b06

> Also, should we add a hover background to the address that looks like the Account Picker's?
Updated here https://github.com/MetaMask/metamask-extension/pull/22637/commits/a8a53b1976ebd0aaa607380ab10673f7f513c039

**Review by darkwing — DISMISSED** [review]

**Review by darkwing — APPROVED** [review]

**Review by vthomas13 — APPROVED** [review]

**Pull request merged**
