### PR TITLE
fix(action): add a workaround for known bots

### LINKED ISSUE #27037: [Bug]: Check Template and Add Labels Test Fails When Devin AI Creates a PR
### Describe the bug

The "Check template and add labels" GitHub Action fails when a PR is created by the Devin AI bot. The error message suggests that GitHub is unable to resolve the user `devin-ai-integration`. This results in the failure of the workflow, preventing it from completing successfully.

### **What Happened?**

When the Devin AI bot creates a pull request, the "Check template and add labels" job fails with the following error:

```
message: "Could not resolve to a User with the login of 'devin-ai-integration'."
```

Additionally, the "Get team label" step fails with the following error:

```
Error: Team label not found for author: devin-ai-integration[bot]. Please open a pull request with your GitHub handle and team label to update teams.json
```

### Expected behavior

The test should correctly identify the user `devin-ai-integration` or gracefully handle cases where the bot cannot be resolved, allowing the workflow to proceed.

### Screenshots/Recordings

Screenshot 2024-09-09 at 2 48 06 PM
Screenshot 2024-09-09 at 3 01 49 PM

### Steps to reproduce

1. Trigger a PR creation by `devin-ai-integration` bot.
2. Observe the failure in the GitHub Action under the "Check template and add labels" job.

### Error messages or log output

```shell
- `Could not resolve to a User with the login of 'devin-ai-integration'.`
- `Team label not found for author: devin-ai-integration[bot].`
```

### Detection stage

On the development branch

### Version

12.1.2

### Build type

None

### Browser

Brave

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

- Only effects Devin PRs in development not critical

### PR DESCRIPTION
**Pull request by gauthierpetetin**
## **Description**

Bots like "[devin-ai-integration](https://github.com/apps/devin-ai-integration)" are not Github users, which leads to the following [error](https://github.com/MetaMask/metamask-extension/actions/runs/10781784044/job/29900441899?pr=26997) when the Github action is executed on PRs created by bots.

[Same PR for Mobile repo](https://github.com/MetaMask/metamask-mobile/pull/11130).

This PR adds a workaround for known bots.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/27019?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/27037

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by georgewrmarshall — APPROVED** [review]
LGTM! Thanks for the quick fix @gauthierpetetin 🙏 🔥

**Review by georgewrmarshall — COMMENTED** [review]
Hmm looks like it's still failing. I got Devin AI to duplicate the updates here and create a new PR so I can use that to test https://github.com/MetaMask/metamask-extension/pull/27040

**Comment by gauthierpetetin** [comment]
The [error message](https://github.com/MetaMask/metamask-extension/actions/runs/10796409140/job/29945339149?pr=27040) in this [PR](https://github.com/MetaMask/metamask-extension/pull/27040) shows `userBelongsToMetaMaskOrg` is being called.
I don't understand how this can happen, given that `labelable?.author` equals "devin-ai-integration".

**Comment by gauthierpetetin** [comment]
Hi @georgewrmarshall , I just tried it out on a test repo:
- Here's an [issue](https://github.com/gauthierpetetin-test/repo_test/issues/199) I created before adding myself (@gauthierpetetin ) to the list of known bots => The Github action ran successfully and `external-contributor` label was added, which indicates `userBelongsToMetaMaskOrg` function was executed and returned `false`
- Here's another [issue](https://github.com/gauthierpetetin-test/repo_test/issues/200) I created after adding myself (@gauthierpetetin ) to the list of known bots (see PR) => The Github action ran successfully and `external-contributor` label was not added, which indicates `userBelongsToMetaMaskOrg` function hasn't been executed (which is expected behaviour for knownBots)

**Review by hjetpoluru — APPROVED** [review]
LGTM

**Review by georgewrmarshall — APPROVED** [review]
I was under the impression the actions were run from the PR and not from `develop`, which is why I expected the tests to pass in this [duplicate PR](https://github.com/MetaMask/metamask-extension/pull/27182) that I had Devin create. Let's merge and test!

Screenshot 2024-09-16 at 3 56 20 PM

**Pull request merged**
