### PR TITLE
chore: update Keystone and NGRAVE dependencies

### PR DESCRIPTION
**Pull request by zhaono1**
## **Description**

This PR updates the dependencies for QR-based hardware wallets.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/PR?quickstart=1)

## **Related issues**

Progresses: https://github.com/MetaMask/MetaMask-planning/issues/2043

## **Manual testing steps**

1. Connect a QR-based hardware wallet (AirGap, Keystone, NGRAVE, etc)
2. Import 2 or more accounts
3. Send a transaction in a test network with the QR wallet account
4. Use [MM E2E test Dapp](https://metamask.github.io/test-dapp/) to sign different messages with a QR wallet account
    - Eth Sign
    - Personal Sign
    - Sign Typed Data
    - Sign Typed Data V3
    - Sign Typed Data V4
    - Sign Permit 
    - Sign In With Ethereum

## **Screenshots/Recordings**

Not applicable

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by Charon-Fan** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Charon-Fan** [comment]
And I need help with updating the LavaMoat policy files.👆

**Comment by Gudahtt** [comment]
Thanks for the contribution! I have resolved conflicts and updated the LavaMoat policies.

There is a bug in our CI setup that is preventing the PR status checks from running, but we hope to have that resolved soon, after which we'll re-run the checks here.

**Review by Gudahtt — DISMISSED** [review]
LGTM! I needed to push one more commit to dedupe the dependencies, but now this looks good. The CI issue I mentioned earlier was resolved as well, so the checks are working fine.

**Comment by Charon-Fan** [comment]
Hello @Gudahtt , is there anything else I need to do before the PR is merged?

**Comment by Gudahtt** [comment]
@Charon-Fan Nope! Just awaiting a second review.

**Comment by Gudahtt** [comment]
I have pushed another update to resolve policy conflicts and re-generate the policies

**Review by Gudahtt — APPROVED** [review]

**Review by pedronfigueiredo — APPROVED** [review]

**Pull request merged**
