### PR TITLE
Fix custom nonce support + incoming transaction display

### LINKED ISSUE #22043: [Bug]: Custom nonces values ignored
### Describe the bug

When custom nonces are enabled, the transaction submits without error however the original calculated nonce is used rather than the custom value.

### Expected behavior

The custom nonce value would be used in the submitted transaction.

### Screenshots/Recordings

_No response_

### Steps to reproduce

1. Enable custom nonces.
2. Specify a low custom nonce.
3. Expect an error, but instead see a successful transaction with the next valid nonce.

### Error messages or log output

_No response_

### Version

develop

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by matthewwalsh0**
### Nonce support

Fix the custom nonce support after migrating to the core `TransactionController`.

This was caused due to the extension using an additional metadata property `customNonceValue` that wasn't supported in the core controller which expected custom nonces to be set in the `txParams.nonce` property.

### Incoming transactions

Fix the display of incoming transactions in the activity list.

This was caused due to the missing `type` property on incoming transaction entries in the state.

### Notes

This is solely a dependency update with no code changes.

See [here](https://github.com/MetaMask/core/pull/3579) for relevant updates in the `@metamask/transaction-controller` package.

## **Related issues**

Fixes: #22043 #22045 

## **Manual testing steps**

1. Enable custom nonces in settings.
2. Verify error with low custom nonce.
3. Verify queued transaction with high custom nonce.
4. Verify transactions with custom nonces disabled.
5. Verify all nonce related functionality such as speed up and cancel.

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [x] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by OGPoyraz — DISMISSED** [review]

**Comment by sleepytanya** [comment]
Incoming transactions correctly shown on the Activity list:

https://github.com/MetaMask/metamask-extension/assets/104780023/35fe7142-a841-46bf-abf9-606a14e48d16

**Comment by sleepytanya** [comment]
Transaction with higher nonce is successfully queued:

https://github.com/MetaMask/metamask-extension/assets/104780023/c40fd192-8a89-416a-8d22-09405083ecdb

**Comment by sleepytanya** [comment]
Speed up/Cancel work as expected:

https://github.com/MetaMask/metamask-extension/assets/104780023/bf687319-8a23-45df-a7ed-883b10eb38c6

**Comment by sleepytanya** [comment]
Transaction can be successfully cancelled by sending low nonce transaction:

https://github.com/MetaMask/metamask-extension/assets/104780023/18260776-1efd-4b71-b150-48a9292c8071

**Review by vinistevam — DISMISSED** [review]

**Review by vinistevam — APPROVED** [review]

**Review by OGPoyraz — APPROVED** [review]

**Comment by sleepytanya** [comment]
Tested:
- incoming transactions are3 visible in the Activity list
- low nonce transaction fails with correct error message
- high nonce transaction submits
- transaction can be queued
- queued transactions can be cancelled
- Speed Up / Cancel works as expected

**Pull request merged**
