### PR TITLE
Version v12.6.0

### PR DESCRIPTION
**Pull request by hjetpoluru**
## **Description**

Version v12.6.0

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/27996?quickstart=1)

### CODE REVIEW

**Comment by danjm** [comment]
<details><summary>Builds ready [30d7f1c]</summary><ul><li>builds: <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/builds/metamask-chrome-12.6.0.zip">chrome</a>, <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/builds-mv2/metamask-firefox-12.6.0.zip">firefox</a></li>
<li>builds (beta): <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/builds-beta/metamask-beta-chrome-12.6.0.zip">chrome</a></li>
<li>builds (flask): <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/builds-flask/metamask-flask-chrome-12.6.0-flask.0.zip">chrome</a>, <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/builds-flask-mv2/metamask-flask-firefox-12.6.0-flask.0.zip">firefox</a></li>
<li>builds (MMI): <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/builds-mmi/metamask-mmi-chrome-12.6.0-mmi.0.zip">chrome</a>, <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/builds-mmi/metamask-mmi-firefox-12.6.0-mmi.0.zip">firefox</a></li>
<li>builds (test): <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/builds-test/metamask-chrome-12.6.0.zip">chrome</a>, <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/builds-test-mv2/metamask-firefox-12.6.0.zip">firefox</a></li>
<li>builds (test-flask): <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/builds-test-flask/metamask-flask-chrome-12.6.0-flask.0.zip">chrome</a>, <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/builds-test-flask-mv2/metamask-flask-firefox-12.6.0-flask.0.zip">firefox</a></li>
<li>build viz: <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/build-artifacts/build-viz/index.html">Build System</a></li>
<li>mv3: <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/test-artifacts/chrome/initialisation/background/index.html">Background Module Init Stats</a></li>
<li>mv3: <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/test-artifacts/chrome/initialisation/ui/index.html">UI Init Stats</a></li>
<li>mv3: <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/test-artifacts/chrome/load_time/index.html">Module Load Stats</a></li>
<li>mv3: <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/test-artifacts/chrome/bundle_size.json">Bundle Size Stats</a></li>
<li>mv2: <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/test-artifacts/chrome/benchmark/user_actions.json">E2e Actions Stats</a></li>
<li>code coverage: <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/coverage/index.html">Report</a></li>
<li>storybook: <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/storybook/index.html">Storybook</a></li>
<li>typescript migration: <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/ts-migration-dashboard/index.html">Dashboard</a></li>
<li><a href="https://circleci.com/gh/MetaMask/metamask-extension/3995831#artifacts/containers/0">all artifacts</a></li>
<li><details>
       <summary>bundle viz:</summary>
       <ul><li>background: <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/build-artifacts/source-map-explorer/background-0.html">0</a>, <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/build-artifacts/source-map-explorer/background-1.html">1</a>, <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/build-artifacts/source-map-explorer/background-2.html">2</a>, <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/build-artifacts/source-map-explorer/background-3.html">3</a>, <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/build-artifacts/source-map-explorer/background-4.html">4</a>, <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/build-artifacts/source-map-explorer/background-5.html">5</a>, <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/build-artifacts/source-map-explorer/background-6.html">6</a></li><li>common: <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/build-artifacts/source-map-explorer/common-0.html">0</a>, <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/build-artifacts/source-map-explorer/common-1.html">1</a>, <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/build-artifacts/source-map-explorer/common-10.html">10</a>, <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/build-artifacts/source-map-explorer/common-11.html">11</a>, <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/build-artifacts/source-map-explorer/common-2.html">2</a>, <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/build-artifacts/source-map-explorer/common-3.html">3</a>, <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/build-artifacts/source-map-explorer/common-4.html">4</a>, <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/build-artifacts/source-map-explorer/common-5.html">5</a>, <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/build-artifacts/source-map-explorer/common-6.html">6</a>, <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/build-artifacts/source-map-explorer/common-7.html">7</a>, <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/build-artifacts/source-map-explorer/common-8.html">8</a>, <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/build-artifacts/source-map-explorer/common-9.html">9</a></li><li>content-script: <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/build-artifacts/source-map-explorer/content-script-0.html">0</a></li><li>offscreen: <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/build-artifacts/source-map-explorer/offscreen-0.html">0</a></li><li>ui: <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/build-artifacts/source-map-explorer/ui-0.html">0</a>, <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/build-artifacts/source-map-explorer/ui-1.html">1</a>, <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/build-artifacts/source-map-explorer/ui-10.html">10</a>, <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/build-artifacts/source-map-explorer/ui-11.html">11</a>, <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/build-artifacts/source-map-explorer/ui-12.html">12</a>, <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/build-artifacts/source-map-explorer/ui-2.html">2</a>, <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/build-artifacts/source-map-explorer/ui-3.html">3</a>, <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/build-artifacts/source-map-explorer/ui-4.html">4</a>, <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/build-artifacts/source-map-explorer/ui-5.html">5</a>, <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/build-artifacts/source-map-explorer/ui-6.html">6</a>, <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/build-artifacts/source-map-explorer/ui-7.html">7</a>, <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/build-artifacts/source-map-explorer/ui-8.html">8</a>, <a href="https://output.circle-artifacts.com/output/job/b635c456-fdff-4b11-a50a-245e1f95a03e/artifacts/0/build-artifacts/source-map-explorer/ui-9.html">9</a></li></ul>
     </details></li></ul></details>

<details><summary>Page Load Metrics (2005 ± 87 ms)</summary><table><thead><tr><th>Platform</th><th>Page</th><th>Metric</th><th>Min (ms)</th><th>Max (ms)</th><th>Average (ms)</th><th>StandardDeviation (ms)</th><th>MarginOfError (ms)</th></tr></thead><tbody><tr><td rowspan="11">Chrome</td><td rowspan="11">Home</td><td>firstPaint</td><td align="right">1692</td><td align="right">2531</td><td align="right">2002</td><td align="right">184</td><td align="right">88</td></tr><tr><td>domContentLoaded</td><td align="right">1669</td><td align="right">2523</td><td align="right">1978</td><td align="right">190</td><td align="right">91</td></tr><tr><td>load</td><td align="right">1684</td><td align="right">2529</td><td align="right">2005</td><td align="right">182</td><td align="right">87</td></tr><tr><td>domInteractive</td><td align="right">20</td><td align="right">179</td><td align="right">52</td><td align="right">32</td><td align="right">15</td></tr><tr><td>backgroundConnect</td><td align="right">10</td><td align="right">88</td><td align="right">30</td><td align="right">22</td><td align="right">10</td></tr><tr><td>firstReactRender</td><td align="right">51</td><td align="right">294</td><td align="right">105</td><td align="right">48</td><td align="right">23</td></tr><tr><td>getState</td><td align="right">6</td><td align="right">64</td><td align="right">19</td><td align="right">20</td><td align="right">10</td></tr><tr><td>initialActions</td><td align="right">0</td><td align="right">0</td><td align="right">0</td><td align="right">0</td><td align="right">0</td></tr><tr><td>loadScripts</td><td align="right">1159</td><td align="right">1985</td><td align="right">1475</td><td align="right">178</td><td align="right">85</td></tr><tr><td>setupStore</td><td align="right">13</td><td align="right">65</td><td align="right">32</td><td align="right">21</td><td align="right">10</td></tr><tr><td>uiStartup</td><td align="right">1894</td><td align="right">2802</td><td align="right">2240</td><td align="right">202</td><td align="right">97</td></tr></tbody></table></details>

<details><summary>Bundle size diffs</summary><ul><li>background: 0 Bytes (0.00%)</li>
<li>ui: 0 Bytes (0.00%)</li>
<li>common: 0 Bytes (0.00%)</li></ul></details>

**Comment by benjisclowder** [comment]
**Version 12.6.0 Release Validation**. NEW SCOPE!

_Release scope has been after merging 12.6.0 and 12.7.0.
Release Cut: October 21
Release Tracker Available: October 22
Target Date for Release Sign-Off: October 29_

Hi Teams! We can start testing and validating v12.6.0 new release scope. Let's do this!

**Instructions for Teams**

1. **Review Changes**: Refer to the [Release Tracker for v12.6.0](https://docs.google.com/spreadsheets/d/1tsoodlAlyvEUpkkcNcbZ4PM9HuC9cEM80RZeoVv5OCQ/edit?gid=2038724435#gid=2038724435) to see all changes relevant to your team.
- Testing status to update the PR testing status: In Progress, Passed, Failed (with comments), Blocked, or Skipped (for documentation or testing improvements).
- Changelog status aids documentation. Select: Changed, Fixed, Added, or N/A if not required.
- Type of Change helps determine the impact. It is broadly categorized as Functional(User facing or non), Non-Functional(regression or not), Non main change.

2. **Log Bugs**: If you find any issues, log them in the release tracker, and make sure you add the right labels on it: type-bug , regression-RC-x.y.z , (and release-blocker when needed).

3. **Approval**: After testing is completed, indicate your team's approval by marking the checkbox next to your team's name in comment. Optionally, leave a comment for additional information.

Your thorough review ensures a smooth and successful release. If you have any questions please reach out to extension platform team or in the [#metamask-qa](https://consensys.slack.com/archives/C01U65ZUS2E) slack channel. Thank you for your collaboration!

Teams to Sign Off 12.6.0 Release on [GH](https://github.com/MetaMask/metamask-extension/pull/27996#issuecomment-2427962132):

- [ ] Accounts: @gantunesr - There are 14 Accounts changes
- [ ] Assets: @sahar-fehri / @alfeng6 - There are 13 Assets changes
- [ ] Bridge: @jclancy93 - There are 6 Bridge changes
- [ ] Confirmations: @sleepytanya / @cryptotavares - There are 40 Confirmations changes
- [ ] Contributor Experience/Tiger Team: @HowardBraham / @gauthierpetetin -  There are 7 Contributor Experience changes
- [ ] Extension Platform: @danjm / @hjetpoluru - There are 46 Extension Platform changes
- [ ] Lavamoat: @legobeat - There are 5 Lavamoat changes
- [ ] MMI: @shane-t - There are 2 MMI changes
- [ ] Notifications: @Prithpal-Sooriya / @matteoscurati - There are 6 Notifications changes
- [ ] Product Safety: @cryptotavares - There are 2 Product Safety changes
- [ ] Snaps Platform: @bowensanders / @Montoya - There are 18 Snaps Platform changes
- [ ] Swaps: @davibroc - There are 4 Swaps changes
- [ ] Transactions: @dbrans - There are 6 Transactions changes
- [ ] Wallet API: @adonesky1 - There are 3 Wallet API Platform changes
- [ ] Wallet Framework: @mikesposito - There are 10 Wallet Framework changes
- [ ] Wallet UX: @darkwing / @NidhiKJha - There are 17 Wallet UX changes

**Important Reminder**:
Please be aware of the importance of starting your testing immediately to ensure there is sufficient time to address any unexpected defects. This proactive approach will help prevent release delays and minimize impacts on other teams' deliveries.

**Comment by plasmacorral** [comment]
Approval from Accounts/Hardware on the 14 changes cited above, with the inclusion of cherry pick https://github.com/MetaMask/metamask-extension/pull/28140.

**Review by naugtur — DISMISSED** [review]
Signoff from LavaMoat team on related items

**Comment by danjm** [comment]
@SocketSecurity ignore-all

I believe all are either maintained by Metamask, expected and necessary network access, or in the dependency tree because of `@solana/web3.js` which is a dependency of trezor libraries, but our use of trezor libraries does not depend on the solana library

**Review by danjm — APPROVED** [review]

**Pull request merged**
