### PR TITLE
Custom tokens must have between 0 and 12 characters

### LINKED ISSUE #7668: Metamask says it only allows tokens with symbol between 0 and 12 chars, but doesn't allow 12 chars
**Describe the bug**
It is as the bug title says

**To Reproduce**
1. Add a custom token on Metamask
2. Paste 0x66117f59814DC7f2AaA7A2f90F6ef16F7e2b363D as the token contract address (mainnet)
3. This token symbol has exactly 12 characters
4. The extension complains saying it should be between 0 and 12 characters.
5. If you edit the name and remove 1 character (so it has 11), it accepts the symbol.

**Expected behavior**
The extension should support 12 characters in the symbol as the error message says.

**Screenshots**
image

**Browser details (please complete the following information):**
 - OS: macos Catalina
 - Browser: Chrome
 - MetaMask Version: 7.7.0.1

### PR DESCRIPTION
**Pull request by ggviana**
Custom token ui shouldn't show error when the a token symbol has exactly 12 characters

Fixes #7668

### CODE REVIEW

**Comment by Gudahtt** [comment]
The intention _was_ to limit token symbols to a maximum of 11 characters; the error message was just worded poorly.

While we could certainly consider increasing that limit, this doesn't fix the linked issue. If anything this makes the error message more misleading, as now the range given ("between 0 and 12") is exclusive on one end and inclusive on the other.

**Comment by whymarrh** [comment]
To follow-up to @Gudahtt's comment, we could maybe adjust the message to add a qualifier like so:

> Symbol must be between 0 and 12 characters, inclusively.

Or even:

> Symbol must be 11 characters or fewer.

**Comment by whymarrh** [comment]
@ggviana do you want to try updating this PR? Let me know if I can help out.

**Comment by ggviana** [comment]
@whymarrh I updated the error messages and provided the translations.
Please let me know if there's anything else I can do to fix this issue.

**Review by whymarrh — APPROVED** [review]
Thanks, @ggviana! This looks good to me!

**Pull request merged**
