### PR TITLE
Update Wyre purchase URL

### PR DESCRIPTION
**Pull request by wachunei**

### CODE REVIEW

**Comment by wachunei** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by wachunei** [comment]
Wyre has updated their UI and this change will keep the fields population working. It is a small change so I think Chrome/Firefox stores would auto approve a new version release 👀.

**Review by whymarrh — APPROVED** [review]
Thanks!

**Comment by whymarrh** [comment]
This will go out in our next release, which should be later this week!

**Pull request merged**
