### PR TITLE
security - lockdown node_modules as read-only during build process

### PR DESCRIPTION
**Pull request by kumavis**
ACL rules here https://github.com/MetaMask/metamask-extension/pull/7210/files#diff-1e8f93b839517952c584b03b44fc3832

### CODE REVIEW

**Comment by kumavis** [comment]
Hmm so I can create a new user and run yarn as that user, but I lose all write perms and get `Operation not supported` when I try to use `setfacl` to add those perms to the necessary places.

There might be a way to fix this but my linux sysadmin skills are low

**Comment by kumavis** [comment]
played around on ssh a bit, got stuck on some other errors i havent been able to reproduce on CI

**Comment by kumavis** [comment]
Now you can see the error I was encountering:
```
+ setfacl -R -m u:buildtask:rw ui/app/css/output
setfacl: ui/app/css/output: Operation not supported
```
unclear why its not supported

**Comment by whymarrh** [comment]
I'll close this for now, we can re-open it when we update it

**Pull request closed without merging**
