### PR TITLE
Ignore this - Get gas price experiment

### PR DESCRIPTION
**Pull request by kumavis**

### CODE REVIEW

**Comment by kumavis** [comment]
`test-e2e-beta-chrome` is passing here

**Comment by kumavis** [comment]
`test-e2e-beta-chrome` is failing here

**Comment by kumavis** [comment]
adding delay breaks a lot of e2e tests

**Comment by kumavis** [comment]
my best guess for the original chrome failure is some super sensitive timing issue, tho doesnt really make sense to me

**Comment by frankiebee** [comment]
closing because of inactivity and `ignore this` feel free to reopen if relevant

**Pull request closed without merging**
