### PR TITLE
Fix BigNumber exception in confirm-send-ether

### LINKED ISSUE #3913: Conversion util: new BigNumber() not a base 16 number: undefined
https://sentry.io/metamask/metamask/issues/512798488/

```
BigNumber Error: new BigNumber() not a base 16 number: undefined
  at W (node_modules/bignumber.js/bignumber.js:1:1)
  at None (node_modules/bignumber.js/bignumber.js:1:1)
  at new $ (node_modules/bignumber.js/bignumber.js:1:1)
  at multiplyCurrencies (ui/app/conversion-util.js:169:22)
  at getGasTotal (ui/app/components/send/send-utils.js:67:10)
...
(45 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by alextsg**
Fixes #3913 

@cjeria Is the loading screen here ok for the UX?

confirm-send-ether

### CODE REVIEW

**Comment by cjeria** [comment]
@alextsg move the spinner and the text up the screen see mock with specs.

loading indicator

**Comment by danjm** [comment]
This looks good to me @alextsg . One thing is unclear: if `isFetching` is not set to false on the initial call of `componentWillMount`, then when is it set to false? Does returning a `<noscript>` unmount the component?

**Comment by alextsg** [comment]
@danjm The `isFetching` flag is set in `setTokenData` and gets called in `componentWillMount` along with `componentDidUpdate`. If it wasn't set to `false` in `componentWillMount` then it should get set to `false` in subsequent `componentDidUpdate` calls. I don't think the `<noscript>` does anything here but I could be wrong.

**Review by danjm — DISMISSED** [review]

**Comment by alextsg** [comment]
@cjeria The spinner we're using is different and larger than the one in the mock so the margins/padding will be a bit different. We can change the spinner but that should probably be done in a separate pull request. Also, the spinner+message was previously centered in the screen, but it looks like you'd like them moved up in the popup view. How should it look in fullscreen mode?

**Comment by alextsg** [comment]
Fix spinner overlay to overlay over the entire screen including the top bar. It might be better to create another issue to address the spinner specifications in order to not block this bug fix.

image

@danjm Can you please review this again? Thanks.

**Comment by cjeria** [comment]
@alextsg yes, let's move the spinner and text up a bit, it's a visual balance thing. I follow the golden ratio rule of thirds whenever possible (see screenshot).

I used a spinner i had off hand for the mockup, no need to change it, but let's scale it down to 56px (to follow the 8px grid rule).

image

**Review by danjm — APPROVED** [review]

**Pull request merged**
