### PR TITLE
Part of #17670 and #18714 for file detected-token-aggregators.js

### PR DESCRIPTION
**Pull request by PrgrmrHarshShukla**
## Explanation
In this PR I have replaced Typography with Text component AND replaced design system typography consts with enums in the file:
**- ui\components\app\detected-token\detected-token-aggregators\detected-token-aggregators.js**

### Before
Screenshot (74)

### After

Screenshot (75)

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Review by pedronfigueiredo — DISMISSED** [review]

**Comment by PrgrmrHarshShukla** [comment]
@georgewrmarshall , @brad-decker , 
Please look into this PR.

Regards

**Review by georgewrmarshall — COMMENTED** [review]
I'm seeing 0 files changes did you forget to push something?

Screenshot 2023-05-03 at 1 14 50 PM

**Comment by PrgrmrHarshShukla** [comment]
Hey @georgewrmarshall ,
This is quite confusing.
But, no worries.

This file has already been fixed for #17670  Replace Typography with Text component &
 #18714 Replace deprecated design system typography consts with enums.
 in the PR #18789.

The PR #18789 has already been merged.

**Comment by georgewrmarshall** [comment]
Hey @PrgrmrHarshShukla, no worries. Going to close. Thanks!

**Pull request closed without merging**
