### PR TITLE
continue button changed to agree

### PR DESCRIPTION
**Pull request by nihar97**
Changed the terms and condition button to say agree instead of continue as with issue https://github.com/MetaMask/metamask-plugin/issues/1384

### CODE REVIEW

**Review by 2-am-zzz — APPROVED** [review]
LGTM!

**Comment by kumavis** [comment]
@Zanibas is this for every notice of just tos?

**Comment by Zanibas** [comment]
This is for every notice: notice.js applies to every single one.

**Comment by Zanibas** [comment]
You may need to force-merge this one due to the CI

**Review by danfinlay — APPROVED** [review]

**Comment by kumavis** [comment]
@Zanibas whats wrong wit the CI ?

**Comment by Zanibas** [comment]
Same problem we have whenever outside contributors submit a PR--the CI doesn't run for them (by design), but GitHub still blocks us on it.

**Comment by kumavis** [comment]
does this make sense to use generally?

"we moved the default to rinkeby"
// Agree

I wonder if "accept" is a more general and yet still positive

**Comment by flyswatter** [comment]
I like "Accept", I accept that it's a more versatile word. Whoever pulls this in to merge it can also change the word, or Nihar could if he'd like.

**Pull request closed without merging**
