### PR TITLE
Fix provider crashes

### LINKED ISSUE #5588: Couldn't decode _____ from ABI: 0x
**Describe the bug**

We at [Origin](https://github.com/OriginProtocol) are experiencing intermittent bad responses from Web3 reads. The issue seems to be related to passing a specific block number in `web3.eth.call` rather than `'latest'`. It happens intermittently to some users, but it seems to be certainly reproducible on MetaMask 4.16. The bad response is either `Couldn't decode address from ABI: 0x` or `Couldn't decode uint256 from ABI: 0x`.

**To Reproduce**

Request Payload
```
{id: 2726296308, jsonrpc: "2.0", method: "eth_call",…}
id: 2726296308
jsonrpc: "2.0"
method: "eth_call"
params: [{from: "0xbd6c9914a5853437363d379f4bc01f4c8a06172c",…}, "0x642bbc"]
```
Response
```
{"jsonrpc":"2.0","id":2726296308,"result":"0x"}
```

**Expected behavior**
```
curl 'https://api.infura.io/v1/jsonrpc/mainnet' -H 'origin: chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn' -H 'accept-encoding: gzip, deflate, br' -H 'accept-language: en-US,en;q=0.9' -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3588.0 Safari/537.36' -H 'content-type: application/json' -H 'accept: application/json' -H 'authority: api.infura.io' --data-binary '{"id":2726296308,"jsonrpc":"2.0","method":"eth_call","params":[{"from":"0xbd6c9914a5853437363d379f4bc01f4c8a06172c","data":"0xde74e57b0000000000000000000000000000000000000000000000000000000000000013","to":"0x819bb9964b6ebf52361f1ae42cf4831b921510f9"},"0x642bbc"]}' --compressed
```
```
{"jsonrpc":"2.0","id":2726296308,"result":"0x000000000000000000000000adc10da9039cbbded8d90cf72626fa9f1a07a5930000000000000000000000000000000000000000000000000000000000000000000000000000000000000000adc10da9039cbbded8d90cf72626fa9f1a07a593"}
```

**Browser details (please complete the following information):**
 - OS X
 - Chrome
 - MetaMask Version 4.16

### LINKED ISSUE #5846: Occasional hanging calls to `getBalance`
**Describe the bug**
Inconsistently, the calls to web3 `getBalance` do not resolve. This is different from issue  #5842 

**To Reproduce**
Unfortunately we do not have good steps to reproduce, although this starts to happen after keeping the browser open for a while.

**Expected behavior**
Calls to web3 `getBalance` should always either resolve with the account balance or reject

**More details**
In our app, we make 3 back to back to back calls:

`getAccounts()`
`getNetwork()`
`getBalance(address)`

The first two calls go through fine, almost immediately.

The third getBalance call hangs, and even after waiting several minutes does not resolve.

Something interesting to note is that in MetaMask’s network tab - we’re not seeing any of the JSONRPC calls made to accounts, network, or balance. All we’re seeing is:

https://api.infura.io/v1/jsonrpc/rinkeby/eth_blockNumber?params=%5B%5D

https://api.infura.io/v1/jsonrpc/rinkeby/eth_getBlockByNumber?params=%5B%220x342c2e%22%2Ctrue%5D

Both of these requests come back with valid responses.

Especially important is that we don’t see any calls to eth_getBalance, however, when the balance _does_ successfully get fetched in our app, we do see those calls being made in the metamask network tab.

It's hard to reproduce this issue because it inconsistently starts happening. Enabling / disabling the metamask extension in chrome OR switching accounts to a different account will resolve the issue (but switching back to the original account experiencing the issue still causes the call to hang).

It might be helpful to note that enabling / disabling the extension then reinvokes the process of calling `window.ethereum.enable` for handling metamask's privacy update.

**Browser details (please complete the following information):**
 - OS: macOS High Sierra Version 10.13.3
 - Browser: Brave & Chrome
 - MetaMask Version: 5.0.3

### PR DESCRIPTION
**Pull request by danfinlay**
- Bump json-rpc-engine to v4.0.0
- Bump package-lock, mostly https links.

As reproduced & identified in danfinlay/ujo-bug-repro#1
As [fixed](https://github.com/MetaMask/json-rpc-engine/commit/6de511afbd03ccef4550ea43ff4010b7d7a84039) in `json-rpc-engine@4.0.0`.

Fixes #5846 

Probably many other situations where a request failed and then crashed the entire provider.

### CODE REVIEW

**Comment by whymarrh** [comment]
Are there breaking changes in this release that we need to update our usages to handle?

**Comment by tmashuang** [comment]
This doesn't really fix the issue's repro steps with https://github.com/MetaMask/metamask-extension/issues/5588#issuecomment-432474862. Seems that some valid responses are returning with `0x`.

**Comment by danjm** [comment]
@danfinlay  Shouldn't #5588 only be resolved once the underlying issue with geth is resolved?

Doesn't this only fix #5846 ?

**Comment by danfinlay** [comment]
Oh my mistake, I mixed in the geth issue here. Removed that fixes line.

According to Aaron, version `4.0.0` actually doesn't break how we use the json-rpc-engine, but it's a good point he major-versioned it, so it seems to imply something is breaking. Will get his verification here for hopefully a new version early tomorrow?

**Comment by danjm** [comment]
@tmashuang were you able to QA that this fixes #5846? (not sure how easy that is to QA)

**Review by tmashuang — APPROVED** [review]

**Pull request merged**
