### PR TITLE
Version v11.1.0 RC 

### PR DESCRIPTION
**Pull request by danjm**

### CODE REVIEW

**Comment by danjm** [comment]
Testing scenario task list:

- [ ] onboarding - create a wallet
- [ ] onboarding

**Comment by benjisclowder** [comment]
Testing scenario task list:

- [ ] onboarding - create a wallet 
- [ ] onboarding - import a wallet
- [ ] keyring - reset a wallet
- [ ] transactions - cancel transaction
- [ ] transactions - send erc20 token origin MM
- [ ]  transactions - send erc721 token origin MM
- [ ] transactions - send native token origin MM
- [ ] transactions - speed up transaction
- [ ] tokens - import erc1155 token origin MM
- [ ] tokens - import erc20 token origin MM
- [ ] tokens - import erc721 token origin MM
- [ ] ens - name resolution
- [ ] phishing - warning page

**Comment by plasmacorral** [comment]
Conducted hardware testing against commit f134493285a23b04332f2bad135acce109770b1b running Mac Ventura 13.5.2.  Majority of testing was with Chrome 117.0.5938.88 (Official Build), unless noted Firefox and in that case was 117.0.1 (64 bit).

Observations in 11.1 RC were all able to be reproduced in v11.0 and v10.35.1, and will be reported outside of the RC.
HardwareResults

**Review by albertolive — APPROVED** [review]

**Comment by danjm** [comment]
@SocketSecurity ignore-all

**Review by chloeYue — APPROVED** [review]

**Review by brad-decker — APPROVED** [review]

**Pull request merged**
