### PR TITLE
Fix #17385 - Provide autohide callback for ActionMessage

### LINKED ISSUE #17385: NFTs: The disappearing toast reappears when you navigate away and then back
### Describe the bug

The logic I used to auto-hide the toast doesn't permanently autohide it.  That's a problem.

### Steps to reproduce

1.  Add an NFT
2. See the "Added successfully" toast
3. Wait 5 seconds
4. Click into the NFT and then back
5. See the "Added successfully" toast again

### Error messages or log output

_No response_

### Version

10.23

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by darkwing**
## Explanation

* Fixes #17385

When the autohide timer goes off, we should record the event so state updates and the ActionableMessage doesn't display again.

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Review by vthomas13 — DISMISSED** [review]
nice

**Review by brad-decker — DISMISSED** [review]

**Comment by NidhiKJha** [comment]
@darkwing should we add autoHide for `removeCollectibleMessage` as well?

**Comment by darkwing** [comment]
Good shout @NidhiKJha !  Updated!

**Review by chloeYue — APPROVED** [review]
QA test OK, LGTM

**Review by NidhiKJha — APPROVED** [review]
LGTM 🚀

**Pull request merged**
