### PR TITLE
Account for 0x/empty string recipient

### LINKED ISSUE #2621: Deploy contract (with MEW) causes "Recipient address is invalid."
Trying to deploy a contract with myetherwallet/metamask combo on rinkeby

MEW prepares data but in MM, error message is seen

image

Note : Data is BIG (300K+)

### PR DESCRIPTION
**Pull request by tmashuang**
Remove recipient field if application initializes a tx with an empty string, or 0x, and tx data. Throw an error with the same condition, but without tx data. Primarily for deploying contracts from MEW.
Added in `tx-gas-utils` but could have added to `app/scripts/lib/util`.
 Fixes #2621.

### CODE REVIEW

**Review by kumavis — APPROVED** [review]
Looks good!

**Comment by kumavis** [comment]
I don't think this solves the MEW bug, as they were sending us the empty string `""` and not `"0x"`

**Review by kumavis — CHANGES_REQUESTED** [review]
Please also handle the `""` case

**Comment by tmashuang** [comment]
The premise with accounting just a '0x' address comes when MetaMask adds the `unApprovedTransaction`  . This is what MetaMask logs
`MetaMaskController newUnapprovedTransaction {"from":"0x3b222de3aaba8ec9771ca9e9af5d8ed757fb7f62","to":"0x","value":"0x0","data":"0x606060405234...`
I assumed Web3 and EthQuery converts the empty string to `0x`, unless we do it.

**Comment by kumavis** [comment]
Were you testing with MEW? I saw it was sending us `""` but wasn't looking at the `addUnapprovedTransaction`

**Review by kumavis — APPROVED** [review]

**Pull request merged**
