### PR TITLE
Add signature prefix to eth_sign method

### LINKED ISSUE #2215: Replace eth_sign behavior with eth_personalSign behavior
We are actually doing `eth_sign` and `eth_personalSign` both wrong.

`personal_*` methods are meant to take a password, and never be exposed to Dapps.

`eth_sign` is still doing the deprecated signing method, and is basically only supported because EtherDelta still uses it.

Eventually we should make our `eth_sign` method do what our `personal_sign` method currently does, which is what Geth and Parity both do anyways.

### PR DESCRIPTION
**Pull request by danfinlay**
The eth_sign method has been considered insecure for a long time,
because it allows signing arbitrary data blobs, which can leak personal
information, and be used to sign transactions without the usual approval
process.

We have long implemented the preferred alternative as personal_sign,
which is actually not the same as any other client.

For both security and cross-client compatibility, this change brings
eth_sign up to the same behavior as personal_sign, without deprecating
that method, again for retroactive compatibility.

Fixes #2215

### CODE REVIEW

**Comment by bwheeler96** [comment]
Once caveat, this now displays data passed in to `eth_sign` with UTF-8 encoding. Many people using `eth_sign` are going to prefer the data displayed as hex (i.e. IDEX, ForkDelta, me).

Maybe we could merge #4039 in with this as well?

screen shot 2018-04-28 at 6 46 54 am

**Comment by danfinlay** [comment]
Forcing a user to see hex seems like a good way for an attacker to obscure a challenge provided by another site, so I'm not sure this should be rolled together with #4039.

**Comment by bwheeler96** [comment]
@danfinlay good point.

Maybe we can make hex display optional if and only if the data being signed is a valid 32 byte hex string. This greatly reduces the attack surface for obfuscating challenges.

Personally I think the ultimate solution is for the client application to send a list of items and their ABI encoding to MM `Array<Item<String,enum{uint,string,etc...}>>` and have metamask show that data to the user. Then the user can sign the more-readable data, and MM can hash the data using the `soliditySha3` function, then MM will produce a signature for `prefix + soliditySha3(data)`.

I know this has been hashed out every which way, but this proposal is backwards-compatible for almost all contracts, much nicer for users, and has a significantly reduced attack surface.

**Comment by christianlundkvist** [comment]
Hey @FlySwatter as we discussed earlier I would prefer if this is not merged in until [EIP712](https://github.com/ethereum/EIPs/pull/712) is finalized. Right now the signed messages conforming to EIP191 (for instance in [simple-multisig](https://github.com/christianlundkvist/simple-multisig/blob/master/contracts/SimpleMultiSig.sol#L29)) cannot be signed using Metamask if Metamask forces the prefix. Ideally these kinds of offline signed messages should be using EIP712 but since that has not been finalized we're in a bit of a limbo. EIP712 does look like it's in pretty good shape though so hopefully will be finalized soon.

**Comment by danfinlay** [comment]
Marking DONOTMERGE until we finalize EIP712 for those reasons.

**Comment by dekz** [comment]
@danfinlay How are we looking for this to be merged now that EIP712 has been merged?
Its still a bit confusing with multiple signers behaving in non spec compliant ways (w.r.t the prefix being added inside the signer). Our code either must attempt to discover MM is implementing `eth_sign` or request the user to specify (so we add the prefix before calling `eth_sign` which is not to spec).

One thing I have noticed is the inconsistencies with `eth_sign` `personal_sign` and the encoding of the message to be signed. We recently worked with Trezor to support signing hex messages (with prefix added on the device, so you can't be tricked into signing a transaction). This was broken since it used utf8 as an encoding which means you can't sign a keccak256 message (pretty common scenario). Trezor has added support for this. I am concerned this PR might result in the same issues?

It also appears that the MM Trezor integration only supports `personal_sign` and not `eth_sign` https://github.com/MetaMask/metamask-extension/issues/5218. 

It would be a happy day when we can truly be agnostic to the underlying `eth_sign` provider!

**Comment by kumavis** [comment]
I would also suggest just dropping eth_sign support since it has had such a shaky history of changing specs and incompatible implementations

**Comment by dekz** [comment]
@kumavis that would make Metamask inconsistent with every other provider. Perhaps its worth just discussing all the things that are a problem with `eth_sign` and how it relates to Metamask.

I would suggest modifying the `eth_sign` behaviour in Metamask to be consistent with the [JSON RPC](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_sign) definition of `eth_sign`. It seems to be equivalent to what you call `personal_sign` (which most providers don't define and has no spec).

Other tools and libraries are having to write work arounds for your code since it is different from other providers. E.g [Ethers.js](https://github.com/ethers-io/ethers.js/blob/master/src.ts/providers/web3-provider.ts#L61), [0x.js](https://github.com/0xProject/0x-monorepo/blob/development/packages/subproviders/src/subproviders/metamask_subprovider.ts#L68).

For reference in this discussion, here is what is defined in the JSON RPC interface for `eth_sign`.

```
The sign method calculates an Ethereum specific signature with: sign(keccak256("\x19Ethereum Signed Message:\n" + len(message) + message))).

By adding a prefix to the message makes the calculated signature recognisable as an Ethereum specific signature. This prevents misuse where a malicious DApp can sign arbitrary data (e.g. transaction) and use the signature to impersonate the victim.

Parameters
account, message

DATA, 20 Bytes - address.
DATA, N Bytes - message to sign.
Returns
DATA: Signature
```

So it takes in `message` and returns `sign(keccak256("\x19Ethereum Signed Message:\n" + len(message) + message)))`. That is it prefixes internally on the signer before signing and the message is sent over the wire without the prefix.

This is how Trezor and Ledger both operate, where they prefix on the device itself. 

If your concern is breaking dApps that are requiring signed hashes without a prefix then perhaps you can migrate them to `eth_sign_v1`. I completely understand that `eth_sign` and the prefix changed from the time MM was started, and dApps were created which used this original signing implementation. But continuing to support this old insecure behaviour comes at a cost of work arounds in other tools and confusion for developers.

I'll be at devcon and @ricmoo and @fabioberger and I plan on setting aside some time to discuss Providers in general and a compliance test suite. We'd love for you to attend as well.

**Comment by danfinlay** [comment]
For now, this implementation of `eth_sign` has become a foundation for a considerable amount of the ecosystem, and the error message we added to it has seemed to adequately mitigate the security concerns.

For those reasons of non-breaking and reduced security concerns, we are closing for now. Petitions to change this behavior should be discussed in #2215.

**Comment by Azier777** [comment]
This is so fascinating and i wish someone could break it down to help me understand so i can finally do this myself...

**Pull request closed without merging**
