### PR TITLE
Prevent Polling while MetaMask user is logged out

### PR DESCRIPTION
**Pull request by captDaylight**
Over at Infura we're looking for ways to relieve some load off our servers. I found that eth-block-tracker was polling for both logged in and logged out users. Instead, with this PR we're hoping to only initiate the polling only once the user is logged in and then terminate again once they're logged out. I've been running this version locally without any problems. 

In `metamask-controller.js` on line 286 I'm checking for auth & polling status, If there's a better place to drop this lmk. We could also remove the check for polling on line 106 if we can remove the line that kickstarts polling in [provider-engine](https://github.com/MetaMask/provider-engine/blob/006a94d4ad5c2a8a147d2a440495d0c3defab498/zero.js#L93).

### CODE REVIEW

**Comment by danfinlay** [comment]
I like this idea, I think it's reasonable to not block track when not logged in, the same way in #714 we will make logging in an explicit act, and so we could just always have block tracking off if no provider was requested.

My only concerns are related to existing Dapp experience (this could be alleviated by strong communication, and preparation of our support staff, but I would like us to think through any UX hiccups so we can prepare):

- When a user visits a site, and it detects MetaMask and web3, it normally might start loading blockchain data immediately to load their UI, even when the user isn't logged in. When a site requests `latest` block with the user not logged in, if block tracking is off, will we return our latest cached block, or will we correctly defer to Infura?

Are there other cases we should consider?

**Comment by captDaylight** [comment]
@danfinlay I think it would be good to keep the cache empty when not logged in, then it's a simple check on metamask's end whether to defer to infura or its cache. From the dapp's perspective they wouldn't need to modify their code, the data's still coming back async (if I'm not mistaken). 

Are there other parts of the codebase that rely on the recent-block cache to be up to date?

**Comment by captDaylight** [comment]
@danfinlay the latest block is returning successfully each time I run `web3.eth.getBlock('latest', (e, block) => { ... })` with the block tracker turned off. I actually can't find an instance where fetching the latest block defers to the cache rather than fetching from Infura.

**Comment by danfinlay** [comment]
> the latest block is returning successfully each time

I want @kumavis to take a pass at this, but the concern is less about interfering with `getBlock('latest')` (something we [definitely explicitly pass through](https://github.com/MetaMask/provider-engine/blob/master/subproviders/cache.js#L59)), but I'm more concerned about what caches *aren't cleared* as a result of the block tracker not running.

In particular, [other methods will probably return cached values until they get a new block](https://github.com/MetaMask/provider-engine/blob/master/subproviders/cache.js#L37).

**Comment by kumavis** [comment]
need to make sure we restart the block tracker on `latest`

**Comment by kumavis** [comment]
this will also cause all requests to cache hit on the last block seen

**Comment by kumavis** [comment]
@captDaylight thanks for the PR, we're working on a larger rewrite since so much of our code relies on always-on block tracker

**Comment by kumavis** [comment]
my approach is in progress https://github.com/MetaMask/metamask-extension/pull/4279

**Pull request closed without merging**
