### PR TITLE
test: Enable single test execution across multiple browsers

### PR DESCRIPTION
**Pull request by hjetpoluru**
## **Description**

This PR is to execute single test across multiple browsers(chrome and firefox) locally. 
E2E debug is now true by default
Updated ReadMe for the specific changes

Note:- I attempted to convert this to a TypeScript file but was unsuccessful, also  it's used internally and hence it should be fine. 

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/23357?quickstart=1)

## **Manual testing steps**

Run the test in codespace or locally --> Checkout to the branch
yarn install
yarn build:test
yarn test:e2e:single test/e2e/tests/network/update-network.spec.ts --browser=all --debug --leave-running  

Without the browser
yarn test:e2e:single test/e2e/tests/network/update-network.spec.ts 

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by hjetpoluru** [comment]
Thanks @HowardBraham, I have addressed your comments.

**Comment by HowardBraham** [comment]
Sorry, noticed two more things:
1. The description says `Set the browser used; either 'chrome' or 'firefox'.`, but should also mention 'all'
2. `run-all.js` should probably also work with `--browser=all`.  Yeah okay perhaps nobody will ever use this option, but it should be there for parity.

**Comment by chloeYue** [comment]
Not sure if it's the best approach, but could we set the default parameter to "all"? This way, if a user runs an e2e test without specifying a browser, it would automatically execute the tests on both browsers, similar to when we explicitly pass "all" as the parameter.

**Review by HowardBraham — DISMISSED** [review]

**Review by HowardBraham — DISMISSED** [review]

**Comment by chloeYue** [comment]
I think this PR requires further adjustments. I pulled this branch and tested it locally, attempting the following commands. However, they only ran tests on Chrome, not on Firefox.
`yarn test:e2e:single --browser=all test/e2e/tests/account-token-list.spec.js`
` yarn test:e2e:single test/e2e/tests/account-token-list.spec.js   `

**Comment by hjetpoluru** [comment]
@chloeYue I need to verify the current behavior: when a test fails in a single browser, does the entire test file still execute? I have not made any changes to the current behavior yet, but I will keep you updated.

**Review by HowardBraham — APPROVED** [review]

**Review by DDDDDanica — APPROVED** [review]

**Review by seaona — APPROVED** [review]

**Comment by seaona** [comment]
nice addition. LGTM

**Review by brad-decker — APPROVED** [review]

**Pull request merged**
