### PR TITLE
add version dimension to metrics event

### LINKED ISSUE #8026: add version to metrics events
to allow us to group events by version

### PR DESCRIPTION
**Pull request by jennypollack**
closes https://github.com/MetaMask/metamask-extension/issues/8026

### CODE REVIEW

**Review by danjm — DISMISSED** [review]
LGTM

**Review by Gudahtt — DISMISSED** [review]
LGTM!

**Review by Gudahtt — COMMENTED** [review]
Oops, the old integration tests are failing. That's too bad.

Perhaps `getManifest` can be mocked in these tests? 🤔 

Edit: Or maybe `getVersion` would be easier to mock out.

**Comment by rekmarks** [comment]
@Gudahtt I mocked `getVersion` in 2dbbeae

**Review by kumavis — APPROVED** [review]

**Comment by kumavis** [comment]
are we submitting analytics events in test/CI ?

**Comment by rekmarks** [comment]
@kumavis I believe so, but they're differentiated in Matomo

**Review by Gudahtt — APPROVED** [review]

**Pull request merged**
