### PR TITLE
Move phishing warning to the extension

### LINKED ISSUE #4773: Move phishing warning to the extension
Rather than redirect users to our website to show the phishing warning, we should bundle a page with the extension that shows full-page when the user hits a flagged site.

### PR DESCRIPTION
**Pull request by kelvintyb**
This fixes #4773 as discussed in that issue. 

- Bundles phishing warning HTML page with the extension
- Adds the phishing.html page to web-accessible-resources in manifest.json

### CODE REVIEW

**Comment by bdresser** [comment]
@alextsg @danfinlay

**Comment by alextsg** [comment]
Can you remove the changes to `package-lock.json`? Otherwise LGTM.

**Comment by alextsg** [comment]
@tmashuang Can you help with rerunning tests on this PR?

**Review by alextsg — APPROVED** [review]

**Review by tmashuang — APPROVED** [review]
LGTM

**Comment by tmashuang** [comment]
@bdresser Work has been accepted.

**Comment by danfinlay** [comment]
Phishing page is a little outdated, we had some wording updates on the Website repo btw.

**Pull request merged**
