### PR TITLE
Version v12.5.0

### PR DESCRIPTION
**Pull request by danjm**
:package: :rocket:

### CODE REVIEW

**Comment by hjetpoluru** [comment]
Hi Teams! We can start testing and validating v12.5.0. Let's do this!

**Instructions for Team Review**

**Review Changes**: Refer to the [Release Tracker for v12.5.0](https://docs.google.com/spreadsheets/d/1tsoodlAlyvEUpkkcNcbZ4PM9HuC9cEM80RZeoVv5OCQ/edit?gid=864997032#gid=864997032)  to see all changes relevant to your team.

- _Testing status to update the PR testing status: In Progress, Passed, Failed (with comments), Blocked, or Skipped (for documentation or testing improvements)._ 
- _Changelog status aids documentation. Select: Changed, Fixed, Added, or N/A if not required._
- _Type of Change helps determine the impact. It is broadly categorized as Functional(User facing or non), Non-Functional(regression or not),Non main change._

**Log Bugs**: If you find any issues, log them in the release tracker, and make sure you add the right labels on it: type-bug , regression-RC-x.y.z , (and release-blocker when needed).

**Approval**: After testing is completed, indicate your team's approval by marking the checkbox next to your team's name in comment. Optionally, leave a comment for additional information.

Your thorough review ensures a smooth and successful release. If you have any questions please reach out to extension platform team or in the [#metamask-qa](https://consensys.slack.com/archives/C01U65ZUS2E) slack channel. Thank you for your collaboration!

- [ ] Accounts [@mike](https://consensys.slack.com/team/C7YK4KGFWW) [@release-contact-accounts](https://consensys.slack.com/admin/user_groups) [@gustavo.antunes](https://consensys.slack.com/team/U024YL93738) - There are 4 Accounts changes. 
- [ ] Assets [@release-contact-assets](https://consensys.slack.com/admin/user_groups) [@david.walsh](https://consensys.slack.com/team/U01B02GRABF)- There are 14 Assets changes. 
- [ ] Bridge [@release-contact-bridge](https://consensys.slack.com/admin/user_groups) [@jack.clancy](https://consensys.slack.com/team/UA82P4P53) - There are 4 Bridge changes.
- [ ] Confirmations [@release-contact-confirmations](https://consensys.slack.com/admin/user_groups) [@joao.tavares](https://consensys.slack.com/team/U02U3JA9CG6) - There are 56 Confirmations changes. 
- [ ] Extension Platform [@release-contact-extension-platform](https://consensys.slack.com/admin/user_groups) [@desi.mcadam](https://consensys.slack.com/team/U05H9EE0KTL) - There are 43 Extension Platform changes.
- [ ] Hardware Wallets: [@gustavo.antunes](https://consensys.slack.com/team/U024YL93738)  - There is 8 Hardware Wallets changes.
- [ ] Lavamoat: [@robert.edstrom](https://consensys.slack.com/team/U03TF4H669F)  - There are 1 Lavamoat change.
- [ ] MMI [@release-contact-mmi](https://consensys.slack.com/admin/user_groups) [@shane](https://consensys.slack.com/team/UF3L5MEF9)- There are 4 MMI. 
- [ ] Notifications [@prithpal.sooriya](https://consensys.slack.com/team/U04S8NZLKH6), [@matteo.scurati](https://consensys.slack.com/team/U04RSUASB26)- There are 0 Notifications changes. 
- [ ] Snaps Platform [@bowen.sanders](https://consensys.slack.com/team/U030WPBCEUW) [@release-contact-snaps-platform](https://consensys.slack.com/admin/user_groups) [@ajeet.dhaliwal](https://consensys.slack.com/team/U076AQB1Q3F) - There are 17 Snaps Platform changes. 
- [ ] Swaps  [@davide.brocchetto](https://consensys.slack.com/team/UE1R5D2GG) - There is 1 Swaps change. 
- [ ] Transactions [@derek.brans](https://consensys.slack.com/team/U061CMURE6T)- There is 1 Transactions change.
- [ ] Wallet Framework [@release-contact-wallet-framework](https://consensys.slack.com/admin/user_groups) [@desi.mcadam](https://consensys.slack.com/team/U05H9EE0KTL) - There are 10 Wallet Framework changes.  
- [ ] Wallet UX [@release-contact-wallet-ux](https://consensys.slack.com/admin/user_groups) [@david.walsh](https://consensys.slack.com/team/U01B02GRABF) - There are 9 Wallet UX changes. 
- [ ] Wallet API Platform [@alex.donesky](https://consensys.slack.com/team/U01UZ3D3XHD) - There are 2 Wallet API Platform changes.

**Comment by hjetpoluru** [comment]
[Manual test scenarios:](https://github.com/MetaMask/metamask-extension/tree/develop/test/manual-scenarios)

Chrome:

- [ ] Onboarding - create a wallet
- [ ]  Transactions - speed up transaction
- [ ]  Transactions - cancel transaction
- [ ]  Transactions - cancel transaction using same nonce
- [ ]  Tokens - import ERC1155 token origin dapp - Watch NFT asset is not responsive even if you click multiple times, after that it spams you with multiple NFT imports in the same list which is not accurate
- [ ]  Tokens - autodetect tokens
- [ ]  ENS - name resolution
- [ ]  Network - switching networks
- [ ]  Network - delete networks from the dropdown list
- [ ]  Address-book - add a contact to the address book
- [ ]  Sign - sign typed data v3 with hardware wallet - (ledger and trezor only supports for sign typed data v4)
- [ ]  Sign - sign typed data v4 with hardware wallet
- [ ]  Sign - personal sign with hardware wallet
- [ ]  Swap - smart swap
- [ ]  Settings - about metamask - ui validation
- [ ]  Settings - advanced - check custom nonce toggle
- [ ]  Settings - advanced - show test networks
- [ ]  Contract - deploy contract, mint and import NFT with hardware wallet
- [ ]  Contract - hardware wallet qr based connect
- [ ]  Upgrade Testing from Master to Release Branch

Firefox:

- [ ]  Onboarding - create a wallet
- [ ]  Transactions - speed up transaction
- [ ]  Transactions - cancel transaction
- [ ]  Transactions - cancel transaction using same nonce
- [ ]  Tokens - import ERC1155 token origin dapp
- [ ]  Tokens - autodetect tokens
- [ ]  ENS - name resolution
- [ ]  Network - switching networks
- [ ]  Network - delete networks from the dropdown list
- [ ]  Address-book - add a contact to the address book
- [ ]  Sign - sign typed data v3 with hardware wallet - only support sign typed data v4 with ledger and trezor
- [ ]  Sign - sign typed data v4 with hardware wallet - test passed with trezor
- [ ]  Sign - personal sign with hardware wallet - test passed with trezor
- [ ]  Swap - smart swap
- [ ]  Settings - about metamask - ui validation
- [ ]  Settings - advanced - check custom nonce toggle
- [ ]  Settings - advanced - show test networks
- [ ]  Contract - deploy contract, mint and import NFT with hardware wallet - passed with trezor (ledger not supported)
- [ ]  Contract - hardware wallet qr based connect
- [ ]  Upgrade Testing from Master to Release Branch

**Comment by benjisclowder** [comment]
> [Manual test scenarios:](https://github.com/MetaMask/metamask-extension/tree/develop/test/manual-scenarios)
> 
> Chrome:
> 
> * [ ]  Onboarding - create a wallet
> * [ ]   Transactions - speed up transaction
> * [ ]   Transactions - cancel transaction
> * [ ]   Transactions - cancel transaction using same nonce
> * [ ]   Tokens - import ERC1155 token origin dapp
> * [ ]   Tokens - autodetect tokens
> * [ ]   ENS - name resolution
> * [ ]   Network - switching networks
> * [ ]   Network - delete networks from the dropdown list
> * [ ]   Address-book - add a contact to the address book
> * [ ]   Sign - sign typed data v3 with hardware wallet
> * [ ]   Sign - sign typed data v4 with hardware wallet
> * [ ]   Sign - personal sign with hardware wallet
> * [ ]   Swap - smart swap
> * [ ]   Settings - about metamask - ui validation
> * [ ]   Settings - advanced - check custom nonce toggle
> * [ ]   Settings - advanced - show test networks
> * [ ]   Contract - deploy contract, mint and import NFT with hardware wallet
> * [ ]   Contract - hardware wallet qr based connect
> * [ ]   Upgrade Testing from Master to Release Branch
> 
> Firefox:
> 
> * [ ]   Onboarding - create a wallet
> * [ ]   Transactions - speed up transaction
> * [ ]   Transactions - cancel transaction
> * [ ]   Transactions - cancel transaction using same nonce
> * [ ]   Tokens - import ERC1155 token origin dapp
> * [ ]   Tokens - autodetect tokens
> * [ ]   ENS - name resolution
> * [ ]   Network - switching networks
> * [ ]   Network - delete networks from the dropdown list
> * [ ]   Address-book - add a contact to the address book
> * [ ]   Sign - sign typed data v3 with hardware wallet
> * [ ]   Sign - sign typed data v4 with hardware wallet
> * [ ]   Sign - personal sign with hardware wallet
> * [ ]   Swap - smart swap
> * [ ]   Settings - about metamask - ui validation
> * [ ]   Settings - advanced - check custom nonce toggle
> * [ ]   Settings - advanced - show test networks
> * [ ]   Contract - deploy contract, mint and import NFT with hardware wallet
> * [ ]   Contract - hardware wallet qr based connect
> * [ ]   Upgrade Testing from Master to Release Branch

Testing update has been reported in TestRail, so we will discard the Github comment from here on. cc @hjetpoluru

**Comment by danjm** [comment]
@SocketSecurity ignore-all

New authors are known and network requests are needed. The native code warning is in a package that will not affect our prod builds

**Review by itsyoboieltr — APPROVED** [review]

**Pull request merged**
