### PR TITLE
[Fixed] Hide links to etherscan when no block explorer is specified for a custom network

### LINKED ISSUE #5631: Hide links to etherscan when no block explorer is specified for a custom network
**Describe the bug**
The transaction confirmation popup looks like this:
Confirmed Transaction

Clicking on it will open Etherscan to view the transaction on mainnet.  

However, if the transaction was not on mainnet, Etherscan will (most likely) not find the transaction OR show information about a transaction **other than** the one the user initiated. It **definitely** will **not** show information about the transaction that was just confirmed on a private network. 

**To Reproduce**
1. Install MetaMask and create an account or log in to an existing install.
2. Connect to a custom RPC running some dapp.
3. Visit the dapp in a browser, trigger a transaction, and approve it. 
4. Wait until the transaction is mined. 
5. See the popup similar to screenshot above. 
6. Click on the popup. 
7. Etherscan will open in your default browser and say it can't find information about that transaction.

**Expected behavior**
A. "View on Etherscan" does not appear if the transaction was executed on a private network.  In this case, the popup should not contain a link to Etherscan and Etherscan should not open if clicking on the popup.

B. If the transaction was executed on a large public testnet, it should open the Etherscan for that testnet (example links: [Rinkeby](https://rinkeby.etherscan.io/tx/0x6e40a26ac4f403099e88b4335233f0d1c479d52e9c16f576eebadfa16e624e1f), [Ropsten](https://ropsten.etherscan.io/tx/0xc46e2440914f6762ab2fa09e06451e64ff7c3a56b027f147d58f9c50303ac71f), [Kovan](https://kovan.etherscan.io/tx/0x0948ad35ed0b3edae798e288ad3c26d715878e07d55a9109a08c8d1bcddf96fa)).  I have not tested to see if this is already implemented. 

C. In cases where there is an Etherscan view of the transaction (large public net), there is a line break before the word "View."  (This might be a separate Issue.)

**Browser details (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 70.0.3538.77 (Official Build) (64-bit) (cohort: 70_77_Win)
 - MetaMask Version: 4.16.0
 - New / Beta UI

### PR DESCRIPTION
**Pull request by BboyAkers**
Fixes: #5631

Explanation: 
Once this PR is merged, [etherscan-link PR](https://github.com/MetaMask/etherscan-link/pull/29), I'll update the latest version of etherscan-link in the package.json and these changes will be valid.

In these PR, if there is a custom network implemented we set the `url` to an empty string so it doesn't render an invalid etherscan url. We then also conditionally render the `View on Etherscan` text if the url is empty.

Manual testing steps:  
  - Load a custom network
  - Send a transaction
  - There will be no url link to go to, thus removing the invalid etherscan url if a custom network is used

### CODE REVIEW

**Comment by BboyAkers** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Gudahtt** [comment]
`etherscan-link@1.4.1` has been released! This PR can be updated to use that now.

These changes look good! Just need to run `yarn lint:fix` to fix the formatting errors.

**Comment by BboyAkers** [comment]
@Gudahtt done 🙂

**Comment by BboyAkers** [comment]
@Gudahtt should I be pushing the yarn.lock?

**Comment by BboyAkers** [comment]
nvm just pushed it 🙂

**Comment by BboyAkers** [comment]
@darkwing @Gudahtt Let me know what ya'll think 🙂

**Review by Gudahtt — APPROVED** [review]
LGTM!

**Pull request merged**
