### PR TITLE
fix: OpenSea supply -> total_supply

### PR DESCRIPTION
**Pull request by bergeron**
## **Description**

OpenSea renamed the field `supply`, which used to be required, to `total_supply`.  Fixes the error:

`undefined is not an object (evaluating 'contract.supply.toString')`

A more accurate `total_supply` was also added to the collection object, which is now preferred to the one on the contract.

## **Manual testing steps**

1. Import a wallet containing NFTs on mainnet
2. Enable NFT autodetection in settings, verify the NFTs appear
3. Verify descriptions, collection/token images are correct

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by bergeron** [comment]
Is it necessary to patch the .map files?

**Comment by Gudahtt** [comment]
>Is it necessary to patch the .map files?

Typically we don't. I'm not entirely sure what advantage patching them might have. It might result in better stack traces in development, or on Sentry for production bugs, but I've never verified whether that works.

**Comment by bergeron** [comment]
> > Is it necessary to patch the .map files?
> 
> Typically we don't. I'm not entirely sure what advantage patching them might have. It might result in better stack traces in development, or on Sentry for production bugs, but I've never verified whether that works.

👍 I'll remove patching the .map files if anyone prefers, but they're currently patched in this PR.

**Comment by bergeron** [comment]
Do I have to fix those changelog/test failures?  Otherwise this is ok to merge on my side.

**Comment by danjm** [comment]
@bergeron Sorry, I might have been confusing in another message I sent. Could you based this PR against `develop` and merge to `develop`, and then we can cherry-pick that commit to the release branch? Or, is there an important reason not to do that with this change?

Also, I think it makes sense to remove the patches to the map files

**Comment by danjm** [comment]
> Do I have to fix those changelog/test failures?

No, you don't have to fix those

**Comment by bergeron** [comment]
> @bergeron Sorry, I might have been confusing in another message I sent. Could you based this PR against `develop` and merge to `develop`, and then we can cherry-pick that commit to the release branch? Or, is there an important reason not to do that with this change?
> 
> Also, I think it makes sense to remove the patches to the map files

Thanks @danjm, sent to develop here: https://github.com/MetaMask/metamask-extension/pull/22376

**Comment by bergeron** [comment]
Closed in favor of: https://github.com/MetaMask/metamask-extension/pull/22377/

**Pull request closed without merging**
