### PR TITLE
Part of #18714: Replace deprecated design system typography consts with enums

### PR DESCRIPTION
**Pull request by dhruvv173**
## Explanation
This PR is a part of #18714
Replaced deprecated design system typography consts with enums in ```confirm-data.js``` and ```confirm-hexdata.js```

File path:
- ui/components/app/confirm-hexdata/confirm-data.js
- ui/components/app/confirm-hexdata/confirm-hexdata.js

### ```confirm-data.js```
image
### ```confirm-hexdata.js```
image

### ```confirm-data.js```
image
### ```confirm-hexdata.js```
image

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [x] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Comment by dhruvv173** [comment]
Hey @georgewrmarshall 
I found a few files which used the deprecated ```<Typography>``` (refer the image below)

image
Is it supposed to be changed from  ```<Typography>``` and ```<TypographyVariant>``` to ```<Text>``` and  ```<TextVariant>```?

If yes, I'd like to work on it, thanks!

**Review by georgewrmarshall — APPROVED** [review]
LGTM! 💯 Thanks for your contribution

**Comment by dhruvv173** [comment]
> LGTM! 💯 Thanks for your contribution

Could you please check the above comment once?
Thanks!

**Comment by georgewrmarshall** [comment]
> Hey @georgewrmarshall I found a few files which used the deprecated `<Typography>` (refer the image below)
> 
> image Is it supposed to be changed from `<Typography>` and `<TypographyVariant>` to `<Text>` and `<TextVariant>`?
> 
> If yes, I'd like to work on it, thanks!

Hey @dhruvv173, that is correct! You can submit a PR against https://github.com/MetaMask/metamask-extension/issues/17670

**Comment by dhruvv173** [comment]
> > Hey @georgewrmarshall I found a few files which used the deprecated `<Typography>` (refer the image below)
> > image Is it supposed to be changed from `<Typography>` and `<TypographyVariant>` to `<Text>` and `<TextVariant>`?
> > If yes, I'd like to work on it, thanks!
> 
> Hey @dhruvv173, that is correct! You can submit a PR against #17670

Okay, will do!

**Review by brad-decker — APPROVED** [review]

**Pull request merged**
