### PR TITLE
feat: updated mmi packages

### PR DESCRIPTION
**Pull request by albertolive**
## **Description**

Updated MMI packges

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/24548?quickstart=1)

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by albertolive** [comment]
@metamaskbot update-policies

**Review by zone-live — DISMISSED** [review]

**Comment by albertolive** [comment]
@metamaskbot update-policies

**Review by zone-live — DISMISSED** [review]

**Review by DDDDDanica — DISMISSED** [review]

**Comment by albertolive** [comment]
@metamaskbot update-policies

**Comment by zone-live** [comment]
@metamaskbot update-policies

**Review by zone-live — APPROVED** [review]

**Review by DDDDDanica — APPROVED** [review]

**Pull request merged**
