### PR TITLE
Removed My Wallet Accounts

### LINKED ISSUE #10342: Remove "My Wallet Account" section in Settings > Contacts
**Description**
Remove "My Wallet Account" section in Settings > Contacts

As a user, I don't want to see a list of my accounts under my Contact settings. I believe this is a result of the Settings > [Contact page designs](https://github.com/MetaMask/metamask-extension/issues/7069) not being fully implemented.

For now that section should be removed. 

**Steps to replicate**
1. Go to 'Settings'
2. Click on 'Contact'

### PR DESCRIPTION
**Pull request by BboyAkers**
Fixes: #10342

Explanation:  
Removed My Wallet Accounts
Manual testing steps:  
  -  Settings -> Contacts -> My Wallet Accounts should be removed

### CODE REVIEW

**Comment by BboyAkers** [comment]
Wanting to add some margin or padding to put space between the address book and the line. Any specific classes tailored to margin?

**Comment by darkwing** [comment]
Thank you @BboyAkers !  I apologize for just getting to this now!  Reviewing ASAP!

**Review by darkwing — CHANGES_REQUESTED** [review]
What you've done looks good functionally!  One thing I'm noticing:  a search of `CONTACT_MY_ACCOUNTS_ROUTE` shows that's still used in a bunch of places, and there's a route and view for `#settings/contact-list/my-accounts`.  I believe you can be a hero and remove more code.  The only place the list of accounts would display after this would be during the send flow.

**Comment by BboyAkers** [comment]
@darkwing  So just for clarification before I go on a deletion spree 😂 , remove 
`CONTACT_MY_ACCOUNTS_ROUTE`
`CONTACT_MY_ACCOUNTS_VIEW_ROUTE`
`CONTACT_MY_ACCOUNTS_EDIT_ROUTE`
and just about anything associated with it? 🙂

**Comment by darkwing** [comment]
Correct, I *believe* those can go.  For safety, let's place those removals in a separate branch, so that if we can roll it back, we easily can do so :)

**Comment by darkwing** [comment]
Hello @BboyAkers!  I apologize for mis-speaking -- I meant as a separate *commit* for this PR/branch, not a separate branch!  My mistake!  Please forgive me!

**Comment by BboyAkers** [comment]
Ohhhhh 😂 I'll fix that today

**Pull request closed without merging**
