### PR TITLE
Can't click address list item when you first time import a hw wallet

### LINKED ISSUE #6343: Cannot click radio button for address when setting up Ledger.
**Describe the bug**
When going through the process of connecting a Ledger to MetaMask, I am prompted to Select HD Path (I chose Legacy), and then Select an Account.  When I click on the radio buttons for the accounts in the list, nothing happens, the radio button does not become selected and the unlock button does not become enabled.

**To Reproduce**
1. Click to setup a new ledger.
2. Change HD Path to Legacy.
3. Try to click on the first account.
4. Notice that clicking does nothing.

**Expected behavior**
I can select an account.

**Browser details (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave
 - MetaMask Version: 6.2.2

### PR DESCRIPTION
**Pull request by codeoneline**
Fixes: #6343 

Explanation:  Sometimes in page `account-list.js`. `this.props.selectedAccount = undefine`, but it need to have a value like '0','1'..., so I think the below code will work fine.
```
  UNSAFE_componentWillMount = () => {
    if (!this.props.selectedAccount && this.props.accounts.length > 0) {
      this.props.onAccountChange('0');
    }
  }
```
I have read the CLA Document and I hereby sign the CLA

### CODE REVIEW

**Comment by codeoneline** [comment]
> **CLA Signature Action:**
> 
> Thank you for your submission, we really appreciate it. We ask that you read and sign our [Contributor License Agreement](https://metamask.io/cla.html) before we can accept your contribution. You can sign the CLA by just by adding a comment to this pull request with this exact sentence:
> 
> > _**I have read the CLA Document and I hereby sign the CLA**_
> 
> By commenting with the above message you are agreeing to the terms of the CLA. Your account will be recorded as agreeing to our CLA so you don't need to sign it again for future contributions to this repository.
> 
> **0** out of **1** committers have signed the CLA.
>  @codeoneline

I have read the CLA Document and I hereby sign the CLA..
I' have updated my pull request

**Comment by codeoneline** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by brad-decker** [comment]
@codeoneline thank you for your submission. While you're waiting for review, could you go ahead and fix up those lint issues from CI?

**Comment by codeoneline** [comment]
> @codeoneline thank you for your submission. While you're waiting for review, could you go ahead and fix up those lint issues from CI?

Hi, I have update the code

**Comment by Gudahtt** [comment]
Thanks for the contribution! However I believe this is no longer required, as the bug this is meant to address was recently solved by a different means in #10198. Instead of calling that function upon mount, it's now ensured that it's always called upon clicking any account.

**Pull request closed without merging**
