### PR TITLE
chore(tools): update geckodriver to 4.0.4

### PR DESCRIPTION
**Pull request by HowardBraham**
Updating the Firefox testing tool to the newest version

### CODE REVIEW

**Review by brad-decker — APPROVED** [review]
LGTM. i'll see if i can resolve the socket-security stuff.

**Comment by brad-decker** [comment]
These all look harmless to me, but maybe @legobeat or someone from @MetaMask/supply-chain could take a look? This is a DEV only dependency so probably not high priority to investigate -- no lavamoat changes required.

**Comment by HowardBraham** [comment]
> This is a DEV only dependency so probably not high priority to investigate -- no lavamoat changes required.

That reminds me... are we sure that our `devDependencies` do not leak into the release?  I have not investigated here, but I have seen other projects that are misconfigured in this way.

I don't know the Yarn 3 way to do this, but the Yarn 1 way was `yarn install --production` on the build machine.

**Comment by Gudahtt** [comment]
@SocketSecurity ignore chainsaw@0.1.0

It does seem to be unmaintained, which is not ideal. But the author was substack, a reputable developer who deleted their account intentionally.

**Comment by Gudahtt** [comment]
@SocketSecurity ignore unzipper@0.10.14

This package is supposed to have filesystem access, that is expected and not concerning

**Comment by Gudahtt** [comment]
@SocketSecurity ignore fstream@1.0.12

It does seem to be unmaintained, but the filesystem access is expected and not concerning.

**Comment by Gudahtt** [comment]
@SocketSecurity ignore buffers@0.1.1
@SocketSecurity ignore traverse@0.3.9

More substack, same situation there.

**Comment by Gudahtt** [comment]
>@SocketSecurity ignore binary@0.3.0

More substack, also this one is ancient

**Comment by Gudahtt** [comment]
@SocketSecurity ignore agent-base@7.1.0

Geckodriver uses this to make network requests, so it should have network access

**Comment by Gudahtt** [comment]
@SocketSecurity ignore binary@0.3.0

More substack, also this one is ancient

**Comment by Gudahtt** [comment]
@SocketSecurity ignore geckodriver@4.0.4

This package is supposed to have network access, and it uses install scripts to ensure the driver is installed.

@SocketSecurity ignore web-streams-polyfill@3.2.1
@SocketSecurity ignore buffer-indexof-polyfill@1.0.2
@SocketSecurity ignore formdata-polyfill@4.0.10
@SocketSecurity ignore node-domexception@1.0.0
@SocketSecurity ignore listenercount@1.0.1
@SocketSecurity ignore loglevel-plugin-prefix@0.8.4

All unmaintained, not ideal but not a reason to object to their usage in geckodriver.

**Comment by Gudahtt** [comment]
@SocketSecurity ignore registry-url@3.1.0

Another unmaintained package

**Comment by Gudahtt** [comment]
@SocketSecurity ignore semver@5.4.1
    @SocketSecurity ignore semver@5.7.1
    @SocketSecurity ignore semver@6.3.0
    @SocketSecurity ignore semver@7.0.0
    @SocketSecurity ignore semver@7.3.7
    @SocketSecurity ignore semver@7.3.8


Regular expression denial of service attacks aren't a concern for our development tools.

**Review by Gudahtt — APPROVED** [review]
LGTM!

**Pull request merged**
