### PR TITLE
Updating zkSync Block Explorer URL

### PR DESCRIPTION
**Pull request by karnie6**
## **Related issues**

Fixes: N/A

## **Manual testing steps**

1. Go to metamask
2. Switch your network to zkSync ERA
3. Click on the ... button on the top right and click on "View on Explorer". Ensure it redirects to era.zksync.network.

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by HowardBraham** [comment]
@karnie6 thanks for your contribution.  Please tell me why you think this is a better zkSync Block Explorer URL.  Please give official documentation, if available.

**Comment by karnie6** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by karnie6** [comment]
> @karnie6 thanks for your contribution. Please tell me why you think this is a better zkSync Block Explorer URL. Please give official documentation, if available.

Hi @HowardBraham - I work at Matter Labs, the team behind zkSync. We recently launched Etherscan for zkSync at the new URL (era.zksync.network).  here's the official announcement: https://twitter.com/zksync/status/1744343401057710096?s=20 .  Etherscan is the gold standard for Ethereum devs and users, and any references to block explorers across the broader ecosystem should point to the Etherscan URL.

**Comment by karnie6** [comment]
Can we hold on approval of this PR.  Want to double-confirm with the team on our plans here.  Will update this PR in the next day.

**Comment by salimtb** [comment]
hey @karnie6
thank you for your contribution, can you pls add a recorded video before/after.
we expect to see for example all the incoming transactions on the activity tab for example

**Pull request closed without merging**
