### PR TITLE
Add types of hidden properties to Sentry data

### PR DESCRIPTION
**Pull request by Gudahtt**
## Explanation

The masked wallet state object sent to Sentry has been updated to include the type of each property omitted from the mask. This lets us at least see the full state shape, making it easier to see when errors are caused by invalid state.

Relates to #20449

## Manual Testing Steps

This is demonstrated by the "errors" e2e tests (see the state snapshots in the diff). You can manually test by performing the same steps as the tests.

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [x] How reviewers can test my changes
- [x] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Review by danjm — DISMISSED** [review]
LGTM

**Review by dan437 — DISMISSED** [review]

**Review by danjm — DISMISSED** [review]
LGTM

**Comment by Gudahtt** [comment]
I'm investigating the e2e test failures. Looks like a timing issue.

**Review by mcmire — DISMISSED** [review]

**Comment by Gudahtt** [comment]
I found that certain background state properties were causing inconsistencies between Chrome and Firefox because they were set to `undefined`, which gets serialized differently between browsers. I also found that the `currentBlockGasLimit` property was timing-dependent.

For now I have excluded these properties from the snapshots. In each case I have a better solution in mind that I will pursue in later PRs, but that need not block this PR.

**Review by danjm — APPROVED** [review]
Looks good. The recent changes makes sense

**Review by darkwing — APPROVED** [review]

**Pull request merged**
