### PR TITLE
inpage - remap ids on response

### LINKED ISSUE #592: Unable to get address of deployed contract
I am able to deploy contract in console in Mist Browser, whereas the same code doesn't work in Chrome with MetaMask.

This is code I ran in Mist console, you can see I successfully got back new contract's address

screen shot 2016-08-28 at 09 39 28

executed code:
```javascript
var source = "contract test { function multiply(uint a) returns(uint d) { return a * 7; } }"

web3.eth.compile.solidity(source, (err, res) => compiledSrc = res)

compiledSrc

web3.eth.contract(JSON.parse(compiledSrc.test.interface)).new({data: compiledSrc.test.bytecode, gas: 300000, from: web3.eth.accounts[0]}, (err, res) => {console.log(err, res); newContract = res})

newContract.address
```

This is code I ran in Chrome, you can see callback is not called second time, therefore contract's address is never assigned. Note, code is slightly different because `web3.eth.compile.solidity` returns object in different format. But that shouldn't matter for this bug.

screen shot 2016-08-28 at 09 41 50

executed code:
```javascript
var source = "contract test { function multiply(uint a) returns(uint d) { return a * 7; } }"

web3.eth.compile.solidity(source, (err, res) => compiledSrc = res)

compiledSrc

web3.eth.contract(compiledSrc.test.info.abiDefinition).new({data: compiledSrc.test.code, gas: 300000, from: web3.eth.accounts[0]}, (err, res) => {console.log(err, res); newContract = res})

newContract.address
```

Using: 
MetaMask 2.9.2
Mist 0.8.2
Geth Version: 1.4.11-stable-fed692f6
network: testnet or private net

### LINKED ISSUE #595: dapp debug - Event not firing
My frontend is using events successfully (with local geth and in Mist) to see wether a transaction has been successfully completed or not. 

EDIT: NewLicensee is an event that is shot when the method SetLicensee is successful.

```js
setLicensee () {
    StablecoinContract.at(address).setLicenseeAddress(newLicenseeAddress, 
                          {from: controledAccount}, SetLicenseeConfirm.bind(this))
  }

  SetLicenseeConfirm (err,res) {
    if (err) confReceived(err, res)
    if (!err) {var event = StablecoinContract.at(address).NewLicensee({licenseM: controledAccount, NewLicensee: newLicenseeAddress})
      event.watch(confReceived)
    }
```

The ABI: 
```js
StablecoinContract = web3.eth.contract([{"constant":true,"inputs":[],"name":"previousPrice100kETHUSD","outputs":[{"name":"","type":"uint256"}],"type":"function"},{"constant":true,"inputs":[],"name":"creator","outputs":[{"name":"","type":"address"}],"type":"function"},{"constant":true,"inputs":[],"name":"serviceRefundTime","outputs":[{"name":"","type":"uint256"}],"type":"function"},{"constant":false,"inputs":[{"name":"spender","type":"address"},{"name":"amountInUSDCents","type":"uint256"}],"name":"approve","outputs":[{"name":"","type":"bool"}],"type":"function"},{"constant":true,"inputs":[],"name":"licenseManager","outputs":[{"name":"","type":"address"}],"type":"function"},{"constant":true,"inputs":[],"name":"startDate","outputs":[{"name":"","type":"uint256"}],"type":"function"},{"constant":true,"inputs":[],"name":"duration","outputs":[{"name":"","type":"uint256"}],"type":"function"},{"constant":false,"inputs":[{"name":"toAddress","type":"address"},{"name":"value","type":"uint256"}],"name":"sendRobust","outputs":[{"name":"","type":"bool"}],"type":"function"},{"constant":true,"inputs":[],"name":"refundIndex","outputs":[{"name":"","type":"uint256"}],"type":"function"},{"constant":true,"inputs":[],"name":"totalSupply","outputs":[{"name":"supply","type":"uint256"}],"type":"function"},{"constant":false,"inputs":[],"name":"stopService","outputs":[{"name":"","type":"bool"}],"type":"function"},{"constant":true,"inputs":[],"name":"feesPercentage","outputs":[{"name":"","type":"uint256"}],"type":"function"},{"constant":true,"inputs":[],"name":"extraBalance","outputs":[{"name":"","type":"int256"}],"type":"function"},{"constant":false,"inputs":[{"name":"from","type":"address"},{"name":"to","type":"address"},{"name":"amountInUSDCents","type":"uint256"}],"name":"transferFrom","outputs":[{"name":"success","type":"bool"}],"type":"function"},{"constant":false,"inputs":[{"name":"nbRedeem","type":"uint256"}],"name":"refund","outputs":[{"name":"","type":"bool"}],"type":"function"},{"constant":false,"inputs":[],"name":"convertToUSD","outputs":[{"name":"","type":"uint256"}],"type":"function"},{"constant":true,"inputs":[],"name":"licenseeAddr","outputs":[{"name":"","type":"address"}],"type":"function"},{"constant":true,"inputs":[],"name":"trustedPriceProvider","outputs":[{"name":"","type":"address"}],"type":"function"},{"constant":true,"inputs":[],"name":"ethStakeInWei","outputs":[{"name":"","type":"uint256"}],"type":"function"},{"constant":true,"inputs":[{"name":"","type":"address"}],"name":"userSCBalances","outputs":[{"name":"","type":"uint256"}],"type":"function"},{"constant":false,"inputs":[{"name":"licensee","type":"address"}],"name":"setLicenseeAddress","outputs":[],"type":"function"},{"constant":true,"inputs":[],"name":"price100kETHUSDAtStop","outputs":[{"name":"","type":"uint256"}],"type":"function"},{"constant":true,"inputs":[],"name":"price100kETHUSD","outputs":[{"name":"","type":"uint256"}],"type":"function"},{"constant":false,"inputs":[],"name":"updateBalances","outputs":[],"type":"function"},{"constant":true,"inputs":[{"name":"_owner","type":"address"}],"name":"balanceOf","outputs":[{"name":"balance","type":"uint256"}],"type":"function"},{"constant":true,"inputs":[],"name":"now1","outputs":[{"name":"","type":"uint256"}],"type":"function"},{"constant":true,"inputs":[{"name":"","type":"uint256"}],"name":"activeUsers","outputs":[{"name":"","type":"address"}],"type":"function"},{"constant":true,"inputs":[],"name":"priceUSDWEI","outputs":[{"name":"","type":"uint256"}],"type":"function"},{"constant":true,"inputs":[],"name":"serviceProvider","outputs":[{"name":"","type":"address"}],"type":"function"},{"constant":false,"inputs":[{"name":"price100000ETHUSD","type":"uint256"}],"name":"updatePrice","outputs":[],"type":"function"},{"constant":true,"inputs":[],"name":"serviceStopped","outputs":[{"name":"","type":"bool"}],"type":"function"},{"constant":false,"inputs":[],"name":"noticeWithdrawers","outputs":[],"type":"function"},{"constant":false,"inputs":[{"name":"receiver","type":"address"},{"name":"amountInUSDCents","type":"uint256"}],"name":"transfer","outputs":[{"name":"","type":"bool"}],"type":"function"},{"constant":true,"inputs":[],"name":"durationOfWithdrawalInSecs","outputs":[{"name":"","type":"uint256"}],"type":"function"},{"constant":true,"inputs":[{"name":"amountInWEI","type":"uint256"}],"name":"getWEItoUSDCentsPrice","outputs":[{"name":"purchasePriceInUSD","type":"uint256"}],"type":"function"},{"constant":true,"inputs":[],"name":"nbSC","outputs":[{"name":"","type":"uint256"}],"type":"function"},{"constant":true,"inputs":[],"name":"lastUpdateTime","outputs":[{"name":"","type":"uint256"}],"type":"function"},{"constant":true,"inputs":[{"name":"","type":"uint256"}],"name":"overExpensiveWithdrawers","outputs":[{"name":"","type":"address"}],"type":"function"},{"constant":true,"inputs":[],"name":"servicePrevStopped","outputs":[{"name":"","type":"bool"}],"type":"function"},{"constant":false,"inputs":[{"name":"amountInUSDCents","type":"uint256"}],"name":"convertToETH","outputs":[{"name":"amountInWei","type":"uint256"}],"type":"function"},{"constant":true,"inputs":[{"name":"","type":"address"},{"name":"","type":"address"}],"name":"userAllowedAmount","outputs":[{"name":"","type":"uint256"}],"type":"function"},{"constant":true,"inputs":[{"name":"owner","type":"address"},{"name":"spender","type":"address"}],"name":"allowance","outputs":[{"name":"","type":"uint256"}],"type":"function"},{"constant":false,"inputs":[{"name":"n","type":"uint256"}],"name":"setNow","outputs":[],"type":"function"},{"constant":true,"inputs":[],"name":"publ","outputs":[{"name":"","type":"bool"}],"type":"function"},{"constant":true,"inputs":[],"name":"collateralsBalance","outputs":[{"name":"","type":"uint256"}],"type":"function"},{"constant":false,"inputs":[],"name":"killService","outputs":[{"name":"","type":"bool"}],"type":"function"},{"constant":true,"inputs":[],"name":"serviceRefunded","outputs":[{"name":"","type":"bool"}],"type":"function"},{"constant":true,"inputs":[{"name":"amountInUSDCents","type":"uint256"}],"name":"getUSDcentstoWEIPrice","outputs":[{"name":"purchasePricesInWei","type":"uint256"}],"type":"function"},{"inputs":[{"name":"ethinFinney","type":"uint256"},{"name":"pub","type":"bool"},{"name":"d","type":"uint256"},{"name":"dwith","type":"uint256"},{"name":"servProvider","type":"address"},{"name":"trustedpv","type":"address"},{"name":"licenseM","type":"address"},{"name":"feesinPercents","type":"uint256"}],"type":"constructor"},{"anonymous":false,"inputs":[{"indexed":false,"name":"TestID","type":"uint256"}],"name":"Testsc","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"duration","type":"uint256"}],"name":"Created","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"licenseM","type":"address"},{"indexed":true,"name":"NewLicensee","type":"address"}],"name":"NewLicensee","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"price","type":"uint256"}],"name":"NewPrice","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"from","type":"address"},{"indexed":true,"name":"valueInUSDCents","type":"uint256"}],"name":"ConvertedToUSDcents","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"from","type":"address"},{"indexed":true,"name":"valueInWei","type":"uint256"}],"name":"ConvertedToWEI","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"from","type":"address"},{"indexed":true,"name":"to","type":"address"},{"indexed":true,"name":"value","type":"uint256"}],"name":"Transfer","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"owner","type":"address"},{"indexed":true,"name":"spender","type":"address"},{"indexed":true,"name":"value","type":"uint256"}],"name":"Approval","type":"event"},{"anonymous":false,"inputs":[],"name":"Stopped","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"stopTime","type":"uint256"}],"name":"PreventiveStop","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"addr","type":"address"},{"indexed":false,"name":"lastingTime","type":"uint256"}],"name":"goWithdraw","type":"event"},{"anonymous":false,"inputs":[],"name":"Refunded","type":"event"},{"anonymous":false,"inputs":[],"name":"NewFakeTime","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"from","type":"address"},{"indexed":false,"name":"value","type":"uint256"}],"name":"Purchase","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"from","type":"address"},{"indexed":false,"name":"value","type":"uint256"}],"name":"Withdraw","type":"event"}])
```

### PR DESCRIPTION
**Pull request by kumavis**
Fixes #592 
Fixes #595 
possibly more

### CODE REVIEW

**Comment by phra** [comment]
https://github.com/MetaMask/metamask-extension/issues/1926

**Review by phra — COMMENTED** [review]
if i try to initialize my own web3 with the metamask provider i get errors about the wrong ids.. i think that this part should be updated because now it seems to be not working.

**Comment by kingcocomango** [comment]
I can confirm the above issue. Initializing web3 with the metamask provider throws 
`bundle.js:74606 Unhandled rejection Error: Wrong response id "1" (expected: "6505053975834747") in `

This is strictly an ID issue, the response is otherwise correct.

**Comment by phra** [comment]
@kingcocomango it's tracked on #1940

**Pull request merged**
