### PR TITLE
Part of #17670 Replace Typography with Text component for file: view-snap.js

### PR DESCRIPTION
**Pull request by PrgrmrHarshShukla**
## Explanation
In this PR I have worked on the issue #17670 Replace Typography with Text component in the file:
**ui\pages\settings\flask\view-snap\view-snap.js**

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Review by pedronfigueiredo — DISMISSED** [review]

**Review by brad-decker — DISMISSED** [review]

**Comment by brad-decker** [comment]
@PrgrmrHarshShukla starting to get some conflicts with your files merging 😅 If you can resolve these conflicts and push up i'll get reapprovals on them.

**Comment by PrgrmrHarshShukla** [comment]
Sure @brad-decker ,
😊
I will do that.

**Comment by PrgrmrHarshShukla** [comment]
Hey @brad-decker , @pedronfigueiredo ,

I have tried to resolve the conflicts.
Especially in the conflict 2, there were extra changes not in my PR.

Please check.

**Comment by georgewrmarshall** [comment]
Closing as I don't see any changes necessary

**Pull request closed without merging**
