### PR TITLE
Handle a negative gas fee

### PR DESCRIPTION
**Pull request by dan437**

### CODE REVIEW

**Comment by darkwing** [comment]
How do we get a negative gas value in the first place?

**Comment by Gtonizuka** [comment]
@darkwing I had the same question, as per @danjm "we are subtracting one value from another to compute an estimate, so some incorrect numbers from the api are causing a negative"

**Review by darkwing — APPROVED** [review]
I'm good with this as long as we investigate the API side!

**Comment by adonesky1** [comment]
> I'm good with this as long as we investigate the API side!

Sam is on it: https://consensys.slack.com/archives/G0150V3D4HX/p1643991649380189?thread_ts=1643978152.050779&cid=G0150V3D4HX

**Review by adonesky1 — APPROVED** [review]

**Pull request merged**
