### PR TITLE
Buy form

### LINKED ISSUE #494: Add method to select quantity to purchase from Coinbase
We did a bare-bones widget first, but let's add that value-selecting feature.

### PR DESCRIPTION
**Pull request by frankiebee**
fixes #494 as well as introduces ShapeShift
- also needed to comment out the logger for ui
  screen shot 2016-08-09 at 7 29 46 pm
  screen shot 2016-08-09 at 7 39 23 pm
  screen shot 2016-08-09 at 10 44 56 pm
  screen shot 2016-08-09 at 10 45 06 pm

### CODE REVIEW

**Comment by flyswatter** [comment]
Could use some address abbreviation and bigger margins.

- Dan

**Comment by frankiebee** [comment]
@flyswatter the address are input fields that have been auto filled with the current account they could be change so they were just divs. As far as bigger margins: do you mean just all around?

**Comment by flyswatter** [comment]
I just mean some of those forms seem to be breaking what otherwise looks like standard margin width, I can itemize them later, boarding a plane now, but yeah just want margin consistency.

- Dan

**Comment by frankiebee** [comment]
Okay ill got through the margins and get it a little more uniform

**Comment by flyswatter** [comment]
Here's our notes from critique:

- Maybe change ‘coinbase’ & ‘shapeshift’ to “USD” & “Crypto”
- Maybe add info button to blog post about coinbase
- Narrow up input fields a bit?
- sender address maybe not an input?
- make buy segment a new view
- Add icons for coinbase & shapeshift?
- Generate QR code for sending to

**Comment by kumavis** [comment]
@frankiebee maybe check for network and show buy options based on that network selection

for testnet, just have a button to "go to test faucet" or something

**Comment by flyswatter** [comment]
That's a good point. And we should maybe just hide the buy button on unknown networks.

**Comment by frankiebee** [comment]
screen shot 2016-08-12 at 4 16 58 pm
screen shot 2016-08-12 at 4 12 01 pm
screen shot 2016-08-12 at 4 11 43 pm
screen shot 2016-08-12 at 3 41 09 pm

**Comment by frankiebee** [comment]
The QR code is an api.

**Comment by flyswatter** [comment]
The deposit screen should both list the deposit address *and* the exact deposit value, in case they aren’t using the QR code.

**Comment by frankiebee** [comment]
Okay will do that now

**Comment by frankiebee** [comment]
@flyswatter 
screen shot 2016-08-12 at 5 39 45 pm

**Comment by flyswatter** [comment]
This seems like a good time for "last call" nit-picks, it looks good enough to merge to me, I'm just throwing out nice things to change while you're still on a roll with this feature, since it's easier now than it will be later.

If you disagree, tell me now, I can merge it as is now and we can tune it up later.  Here are my thoughts, though:

- The "send to" address should be concatenated not at the QR width, but at the section's padded width.
- The "go to test faucet" button should have more top margin.
- I like the question mark icons you added. Where does the shapeshift question mark link to?

**Comment by kumavis** [comment]
> The "send to" address should be concatenated not at the QR width, but at the section's padded width.

maybe? meh. addresses are ugly.

> The "go to test faucet" button should have more top margin.

agree

> I like the question mark icons you added. 

👍 👍 👍

**Comment by frankiebee** [comment]
@flyswatter the shapeshift ```?``` link is [https://info.shapeshift.io/about](https://info.shapeshift.io/about )although I would ideally like something in are FAQ repo like are Coinbase blog so that its a little more tailored for are use case. I will put more margin

as far as the address thing this is what that would look like:
screen shot 2016-08-14 at 9 40 09 am

**Comment by flyswatter** [comment]
Yeah, I do personally prefer that, even though I know, addresses are ugly.

That link should do for now, but agree, we’ll want something tailored soon.

After the margin patch let’s do this!

**Pull request merged**
