### PR TITLE
Disable fiat conversion in Approve Screen when `Show balance and token price checker` is OFF

### LINKED ISSUE #17428: [Bug]: Fiat Conversion is displayed while having the feature OFF for Binance Chain on the Approve screen for ERC20 and ERC721
### Describe the bug

**Problem**: when I switch off the fiat conversion option under the Privacy Settings, I expect to see no fiat conversion. Despite that, I can still see one fiat conversion on the Approve screen, while using Binance Chain, both for ERC20 and ERC721 tokens.

Relates to https://github.com/MetaMask/metamask-extension/pull/16772

image

### Steps to reproduce

Disable the Fiat conversion on Settings.

**For ERC721:**
1. Go to https://bscscan.com/token/0xADc466855ebe8d1402C5F7e6706Fccc3AEdB44a0#writeContract
2. Connect MM
3. Cliick Write Contract
4. Click Approve function
5. Add address and id (any number)
6. Click Write
7. See MM prompt and fees displayed in fiat

https://user-images.githubusercontent.com/54408225/214824513-29bd8a95-b8d1-4df5-b574-8d67f10735d1.mp4

**For ERC20:**
1. Go to https://bscscan.com/token/0x2170ed0880ac9a755fd29b2688956bd959f933f8#writeContract
2. Connect MM
3. Cliick Write Contract
4. Click Approve function
5. Add address and amount (any number)
6. Click Write
7. See MM prompt and fees displayed in fiat

### Error messages or log output

_No response_

### Version

10.24.1

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by NiranjanaBinoy**
## Explanation

Fixes #17428 
Fiat value was getting displayed on the approve screen when `Show balance and token price checker` was disabled, so we are adding the `useCurrencyRateCheck` to the Approve screen to control the Fiat display.

### After
Screenshot 2023-01-26 at 4 11 23 PM

## Manual Testing Steps
Disable the Fiat conversion on Settings.

For ERC721:

1. Go to https://bscscan.com/token/0xADc466855ebe8d1402C5F7e6706Fccc3AEdB44a0#writeContract
2. Connect MM
3. Cliick Write Contract
4. Click Approve function
5. Add address and id (any number)
6. Click Write
7. See MM prompt and fees displayed in fiat

For ERC20:

1. Go to https://bscscan.com/token/0x2170ed0880ac9a755fd29b2688956bd959f933f8#writeContract
2. Connect MM
3. Cliick Write Contract
4. Click Approve function
5. Add address and amount (any number)
6. Click Write
7. See MM prompt and fees displayed in fiat

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Review by JuanCarlosS770 — APPROVED** [review]

**Review by JuanCarlosS770 — DISMISSED** [review]

**Comment by jpuri** [comment]
Hey @NiranjanaBinoy : can you plz add test coverage also ?

**Comment by chloeYue** [comment]
Hello, for ERC721, QA test OK ✔️
For ERC20 token https://bscscan.com/token/0x2170ed0880ac9a755fd29b2688956bd959f933f8#writeContract, we still see fiat value on approve screen:

https://user-images.githubusercontent.com/105063779/215052609-4fe7106c-2d29-48d0-b42f-41ab16f3ca1b.mov

**Comment by NiranjanaBinoy** [comment]
@chloeYue Good catch ❤️ I have updated the approve confirm screen now; please verify and let me know

**Comment by chloeYue** [comment]
QA test OK, thanks !

**Comment by jpuri** [comment]
Will be nice to have test coverage.

**Review by pedronfigueiredo — DISMISSED** [review]

**Review by pedronfigueiredo — APPROVED** [review]

**Review by brad-decker — APPROVED** [review]

**Pull request merged**
