### PR TITLE
Add EIP-712 support for Trezor

### LINKED ISSUE #11498: Support EIP-712 signing for TREZOR accounts
Dear Devs, thank you for reading this. 

This is a long standing problem that breaks support of hardware wallets for many web 3 applications. 

I know that ledger already currently supports with a [not ideal solution](https://github.com/MetaMask/metamask-extension/issues/10240) but working nonetheless.

Is anyone looking into the trezor side of things?

The devs on the trezor side are currently looking into the following to fully support EIP-712.
https://github.com/trezor/trezor-firmware/pull/1568

It would be lovely if Metamask could look into the `connect` part of the specifications. I'm sorry I cannot help as this is really not in my field of expertise.

### PR DESCRIPTION
**Pull request by aloisklink**
Fixes: #11498

**Blocked by**:
- [ ] Merge and release of https://github.com/MetaMask/eth-trezor-keyring/pull/117
- [ ] Bumping `eth-trezor-keyring`'s version in `package.json`

Add EIP-712 `signTypedData_v4` support for Trezor.

Thanks to @alisinabh, @matejcik, and @BrandonNoad for their help getting Trezor Model 1 supported too in https://github.com/MetaMask/eth-trezor-keyring/pull/117, I've stuck you guys as co-authors in the git commit, let me know if you want me to remove you :wink:

### Manual testing steps:

  - Go to https://metamask.github.io/test-dapp/
  - Click on "Sign" and "Verify" for `signTypedData_v4` using:
    - A Trezor Model T hardware wallet
    - A Trezor Model 1 hardware wallet

### CODE REVIEW

**Comment by davidberiro** [comment]
Is this gonna be merged at some point?

**Comment by aloisklink** [comment]
> Is this gonna be merged at some point?

Hi @davidberiro, this is currently blocked by https://github.com/MetaMask/eth-trezor-keyring/pull/117, which needs to be reviewed/merged.

@danfinlay's said on [Twitter (link)](https://twitter.com/danfinlay/status/1483867935193980930) that it'll probably only be released Feb 7th at the earliest since it needs to go through QA as well.

And potentially even longer to go through the Google Chrome/Firefox extension stores.

You're welcome to build Metamask with this feature yourself, but since @Metamask hasn't reviewed the code, there could be security issues/bugs in the code, **so please wait for an official release, and only build a development version if you're aware of the risks**.

**Comment by davidberiro** [comment]
> > Is this gonna be merged at some point?
> 
> Hi @davidberiro, this is currently blocked by [MetaMask/eth-trezor-keyring#117](https://github.com/MetaMask/eth-trezor-keyring/pull/117), which needs to be reviewed/merged.
> 
> @danfinlay's said on [Twitter (link)](https://twitter.com/danfinlay/status/1483867935193980930) that it'll probably only be released Feb 7th at the earliest since it needs to go through QA as well.
> 
> And potentially even longer to go through the Google Chrome/Firefox extension stores.
> 
> You're welcome to build Metamask with this feature yourself, but since @MetaMask hasn't reviewed the code, there could be security issues/bugs in the code, **so please wait for an official release, and only build a development version if you're aware of the risks**.

Thanks for your prompt response. I do have a lot of software experience so would be comfortable building myself. Can you perhaps reference a guide? And would I need to build eth-trezor-keyring as well as metamask-extension?

**Comment by aloisklink** [comment]
Actually, although this PR is blocked by MetaMask/eth-trezor-keyring#117, I'll set this PR as "ready for review", since it looks like that will assign it to a specific reviewer. **Please don't merge though** until a new version of `eth-trezor-keyring` has been released and the `package.json` file has been updated!

**Comment by aloisklink** [comment]
> Thanks for your prompt response. I do have a lot of software experience so would be comfortable building myself. Can you perhaps reference a guide? And would I need to build eth-trezor-keyring as well as metamask-extension?

Hi @davidberiro, essentially, all you need to do is download my branch, then follow the instructions in the Metamask [README.md file](https://github.com/aloisklink/metamask-extension/tree/trezor-eip-712#readme)

These commands should do it, as long as you have everything installed already: https://github.com/MetaMask/eth-trezor-keyring/pull/117#issuecomment-1017393782.

No need to build `eth-trezor-keyring`, it's in the `package.json` lock file already, so it should automatically download when you run `yarn setup`.

**Comment by davidberiro** [comment]
> > Thanks for your prompt response. I do have a lot of software experience so would be comfortable building myself. Can you perhaps reference a guide? And would I need to build eth-trezor-keyring as well as metamask-extension?
> 
> Hi @davidberiro, essentially, all you need to do is download my branch, then follow the instructions in the Metamask [README.md file](https://github.com/aloisklink/metamask-extension/tree/trezor-eip-712#readme)
> 
> These commands should do it (assuming the comment isn't edited in the future), as long as you have everything installed already: [MetaMask/eth-trezor-keyring#117 (comment)](https://github.com/MetaMask/eth-trezor-keyring/pull/117#issuecomment-1017393782).
> 
> Side-note, if you're on a Windows computer, you'd probably want to run them in [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/setup/environment)
> 
> No need to build `eth-trezor-keyring`, it's in the `package.json` and lock file already, so it should automatically download when you run `yarn setup`.

Got it working and claimed my airdrop. You're the man!

**Comment by Nana12345678910** [comment]
And my my time and Avalanche there should me more in it like ten times the value

**Comment by kevincheng96** [comment]
> > Thanks for your prompt response. I do have a lot of software experience so would be comfortable building myself. Can you perhaps reference a guide? And would I need to build eth-trezor-keyring as well as metamask-extension?
> 
> Hi @davidberiro, essentially, all you need to do is download my branch, then follow the instructions in the Metamask [README.md file](https://github.com/aloisklink/metamask-extension/tree/trezor-eip-712#readme)
> 
> These commands should do it (assuming the comment isn't edited in the future), as long as you have everything installed already: [MetaMask/eth-trezor-keyring#117 (comment)](https://github.com/MetaMask/eth-trezor-keyring/pull/117#issuecomment-1017393782).
> 
> Side-note, if you're on a Windows computer, you'd probably want to run them in [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/setup/environment)
> 
> No need to build `eth-trezor-keyring`, it's in the `package.json` and lock file already, so it should automatically download when you run `yarn setup`.

Don't know if anything has changed since this post, but I can't get this working on my end with a Trezor Model One. I get this error when trying to sign a transaction: `MetaMask Message Signature: Error: Unknown message`. Tried this on Chrome for two different mac books.

**Comment by drortirosh** [comment]
When this issues is scheduled to be released?

**Comment by bastiankai** [comment]
With the new openseas contract upgrade to wyvern it is not possible to use trezor with mm anymore, I hope that a solution is found soon

**Comment by danfinlay** [comment]
@aloisklink Sorry that so much community pressure has been on your volunteer PR. Would you prefer if we were able to take over this contribution, or add a bounty for your contribution? I think you already deserve a bounty (drop your address!) but we could also agree on some additional amount for finishing it up if that could help.

**Comment by msubash26** [comment]
@aloisklink @danfinlay , Can we please expedite & fix the issue and ship the latest version soon? this is blocking many from using Trezor with MM for NFTs in Opensea and Lookrare.. Thanks a bunch for all your contributions and appreciate your hard work !!

**Comment by danjm** [comment]
Thanks for all your work on this @aloisklink 

I have pushed your branch to one directly in the repo so that we can push directly to it. https://github.com/MetaMask/metamask-extension/pull/13693

We will be working to get this merged over the next 24 hours.

**Pull request closed without merging**
