### PR TITLE
add Custom Network Added event

### PR DESCRIPTION
**Pull request by brad-decker**
Fixes: Adds custom network tracking.

### CODE REVIEW

**Review by danjm — DISMISSED** [review]
LGTM

**Review by Gudahtt — DISMISSED** [review]

**Review by darkwing — DISMISSED** [review]

**Comment by brad-decker** [comment]
waiting for one clarifying point from Lorenzo

**Comment by brad-decker** [comment]
Finalized the values/schema with Lorenzo.

**Review by Gudahtt — APPROVED** [review]
LGTM!

**Pull request merged**
