### PR TITLE
Include snap version in pill

### PR DESCRIPTION
**Pull request by FrederikBolding**
## Explanation

Moves the snap version to the pill component for snap install.

### Before

image

### After

image

## Manual Testing Steps

1. Go to https://metamask.github.io/test-snaps/0.3.0/
2. Connect and install a snap
3. See that the snap version is included in the pill

### CODE REVIEW

**Comment by eriknson** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by hmalik88 — APPROVED** [review]
LGTM.

**Review by darkwing — APPROVED** [review]
Approving but we may want to try `padding-inline-end: 8px;` instead of `padding-right`;  did you check in RTL?

**Comment by eriknson** [comment]
> 

It seems like we add a `dir="rtl"` property by the top of the DOM when the setting is set to an RTL language, flipping the suitable styling of the included elements automatically. So `padding-right` turns into `padding-left` in this case.

**Pull request merged**
