### PR TITLE
Add fiat conversion to tx confirmation view

### LINKED ISSUE #582: Add fiat conversion to TX confirmation view
Now that we have fiat conversion built into the plugin, we should get it rendered everywhere useful!

The most obvious place is on the TX approval view.

### PR DESCRIPTION
**Pull request by danfinlay**
Made the `EthBalance` component support rendering the current fiat equivalent right after it, which gives us "free" fiat comparison in most parts of the app.

Made the component accept a `showFiat` boolean to opt out of this feature, like in the tx history list.

Also fixed some new react errors I was getting with a fresh `npm install`.

Fixes #582

### CODE REVIEW

**Comment by Zanibas** [comment]
screenshot from 2016-09-06 19 52 41

**Comment by flyswatter** [comment]
Ok @Zanibas fixed the issue you caught!

**Comment by Zanibas** [comment]
@flyswatter still unfixed--we still get a double tooltip when hovering over the fiat balance.

**Comment by flyswatter** [comment]
Rebuild?

**Comment by Zanibas** [comment]
Oh, it was because my HEAD alias wasn't working as intended...whoops~

It's good!

**Pull request merged**
