### PR TITLE
Rename yarn.lock to deuces9ers/yarn.lock

### PR DESCRIPTION
**Pull request by Deuces9ers**
## **Description**

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/25602?quickstart=1)

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by Jellyman447** [comment]
Approved

**Comment by Jellyman447** [comment]
Approved

**Comment by Deuces9ers** [comment]
Im not signing any of that until i have 3.2 million dollars wired into my
local bank account. Your open collective buddies have been spending my
tokens and ive needed that fundage not just to produce, but to fucking eat.
Call Ill stay up till 9am central time. Bank is a block away. I can walk
there in 5 min. Put your team on tue phone with them. You deposit the
funds. I wont continue my legal rights to pretty much well im sure you know
considering you are consensys. 1-618-694-2367. Until that money clears i
aint signing shit. Call me between 7:55 and 9:15am and we can finish this
business

**Comment by Deuces9ers** [comment]
You should know i released a statement with linkldn about 3 hours ago so
they already know my intentions. Talk to ya at 8 am

**Comment by Jellyman447** [comment]
Approved and merge

**Pull request closed without merging**
