### PR TITLE
filters bug fix

### PR DESCRIPTION
**Pull request by kumavis**
relevant change
https://github.com/kumavis/eth-json-rpc-filters/commit/d9e5694391d38c776deb64758d45a5adaee4bd17
https://github.com/kumavis/eth-json-rpc-filters/commit/f804d9a20a8b8fa5bd30b0b796690416fc3cd454
https://github.com/kumavis/json-rpc-engine/commit/091b355309db8948efe458128e631aa8e56f3941

not certain if this fixes all the issues with events/logs/filters but it should help

Updates #2393
Updates #2255
Updates #2114

### CODE REVIEW

**Comment by kumavis** [comment]
unrelated security failure:
> Vulnerable: <=1.1.1 - Patched: >=2.0.0 - Path: sandwich-expando@1.1.1 > brfs@1.4.3 > static-module@1.5.0 > static-eval@0.2.4

**Review by frankiebee — APPROVED** [review]
LGTM as well as confirmation from user who had initial issue that this is fixed

**Comment by hbwoodrose** [comment]
Hey there. I believe this was also going to fix metamask listening to contract events. The 'transfer' event works fine for me if I dont use metamask and specify the web3 provider myself (localhost or infura). However, as soon as I try using metamask instead, the contract event is no longer listened to... Even with this new update, im still experiencing this problem. 

Im building with react and listening to the transfer event in 'componentDidMount', and making sure web3 is provided by metamask beforehand. 

Any help is much appreciated. Id like to be able to use this in production. Thanks!!

**Comment by nteymory** [comment]
Just wanted to note that this change didn't fix listening to contract events. This still doesn't work in version 3.12.0

**Comment by lazaridiscom** [comment]
@hbwoodrose @nt85 , please try this fix:

https://github.com/MetaMask/metamask-extension/pull/3224/files

**Comment by lazaridiscom** [comment]
@hbwoodrose @nt85 , please try this fix:

https://github.com/MetaMask/metamask-extension/pull/3224/files

**Comment by nt85** [comment]
I am having trouble reproducing this bug since 3.14.1, it may have been fixed, or at least improved since 3.12? So, I cannot confirm whether this change makes a difference.

**Pull request merged**
