### PR TITLE
CI - capture screenshots

### PR DESCRIPTION
**Pull request by kumavis**
this is the start of automated screenshot tool.
it runs in CI and saves screenshots throughout the app for QA/review.

- moves tests to ganache-cli (was causing lots of sporadic failures)
- exposes `global.metamask = { updateCurrentLocale, setProviderType } ` in ui for when tooling needs to interact with prod builds
- adds 2 jobs to CI:
  - screens (capture screenshots in all locales)
  - announce (upload builds + comment on PR)
- gif of english screenshot is added collapsed under builds announcement (click announcement to reveal)

### CODE REVIEW

**Comment by kumavis** [comment]
<details>
  <summary>
    Builds ready [abcdefg]:
    <a href="https://undefined-42009758-gh.circle-artifacts.com/0/builds/mascara/home.html">mascara</a>,
    <a href="https://undefined-42009758-gh.circle-artifacts.com/0/builds/metamask-chrome-4.4.0.zip">chrome</a>,
    <a href="https://undefined-42009758-gh.circle-artifacts.com/0/builds/metamask-firefox-4.4.0.zip">firefox</a>,
    <a href="https://undefined-42009758-gh.circle-artifacts.com/0/builds/metamask-edge-4.4.0.zip">edge</a>,
    <a href="https://undefined-42009758-gh.circle-artifacts.com/0/builds/metamask-opera-4.4.0.zip">opera</a>
  </summary>
  <image src="https://undefined-42009758-gh.circle-artifacts.com/0/test-artifacts/screens/walkthrough%20%28en%29.gif">
</details>

**Comment by kumavis** [comment]
seems the CI servers chrome build does not have support for non-english characters
rendering error

**Comment by tmashuang** [comment]
The only issue I ran into was `ganache-cli` was persisting after the tests,`screens` and `e2e` finish. I had to kill my server manually. Screen shot here: 
ganache-server-persisting

**Comment by kumavis** [comment]
verified the server closes on CI and OSX

**Comment by kumavis** [comment]
fixing one last berg

**Review by tmashuang — APPROVED** [review]

**Pull request merged**
