### PR TITLE
Allow zero gasPrice on testnet.

### PR DESCRIPTION
**Pull request by nujabes403**
Currently, Metamask doesn't allow zero gasPrice. 

It is natural to restrict gasPrice on mainnet, however it shouldn't be restricted to 0.1 wei on testnet.

This restriction makes development uncomfortable. (there are issues related to this: #3888, #3074)

### CODE REVIEW

**Comment by nujabes403** [comment]
@danfinlay

**Comment by danfinlay** [comment]
Fixes #3074

We'll review this soon.

**Comment by danfinlay** [comment]
Please also add an entry to `CHANGELOG.md`.

**Comment by nujabes403** [comment]
Added line "Allow zero gasPrice on testnet" on CHANGELOG.md

**Comment by danfinlay** [comment]
We talked about this, and are willing to close this in favor of #4058. Should be an even simpler PR if you want to submit it.

**Pull request closed without merging**
