### PR TITLE
v12.2.0 sync v12.1.1

### PR DESCRIPTION
**Pull request by Gudahtt**
## **Description**

Update v12.2.0 with changes from v12.1.1

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/26842?quickstart=1)

## **Related issues**

N/A

## **Manual testing steps**

N/A

## **Screenshots/Recordings**

N/A

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by Gudahtt** [comment]
@metamaskbot update-policies

**Comment by Gudahtt** [comment]
https://github.com/SocketSecurity ignore npm/@storybook/addon-toolbars@7.6.20
https://github.com/SocketSecurity ignore npm/@storybook/node-logger@7.6.20
https://github.com/SocketSecurity ignore npm/@storybook/client-logger@7.6.20
https://github.com/SocketSecurity ignore npm/@storybook/postinstall@7.6.20
https://github.com/SocketSecurity ignore npm/@storybook/react-dom-shim@7.6.20
https://github.com/SocketSecurity ignore npm/@storybook/preview@7.6.20
https://github.com/SocketSecurity ignore npm/@storybook/manager@7.6.20
https://github.com/SocketSecurity ignore npm/@storybook/addon-essentials@7.6.20
https://github.com/SocketSecurity ignore npm/@storybook/react@7.6.20
https://github.com/SocketSecurity ignore npm/storybook@7.6.20
https://github.com/SocketSecurity ignore npm/@storybook/addon-actions@7.6.20
https://github.com/SocketSecurity ignore npm/@storybook/addon-backgrounds@7.6.20
https://github.com/SocketSecurity ignore npm/@storybook/addon-controls@7.6.20
https://github.com/SocketSecurity ignore npm/@storybook/addon-docs@7.6.20
https://github.com/SocketSecurity ignore npm/@storybook/addon-highlight@7.6.20
https://github.com/SocketSecurity ignore npm/@storybook/addon-measure@7.6.20
https://github.com/SocketSecurity ignore npm/@storybook/addon-outline@7.6.20
https://github.com/SocketSecurity ignore npm/@storybook/addon-viewport@7.6.20
https://github.com/SocketSecurity ignore npm/@storybook/core-common@7.6.20
https://github.com/SocketSecurity ignore npm/@storybook/manager-api@7.6.20
https://github.com/SocketSecurity ignore npm/@storybook/preview-api@7.6.20
https://github.com/SocketSecurity ignore npm/@storybook/core-events@7.6.20
https://github.com/SocketSecurity ignore npm/@storybook/blocks@7.6.20
https://github.com/SocketSecurity ignore npm/@storybook/components@7.6.20
https://github.com/SocketSecurity ignore npm/@storybook/csf-plugin@7.6.20
https://github.com/SocketSecurity ignore npm/@storybook/csf-tools@7.6.20
https://github.com/SocketSecurity ignore npm/@storybook/theming@7.6.20
https://github.com/SocketSecurity ignore npm/@storybook/types@7.6.20
https://github.com/SocketSecurity ignore npm/@storybook/channels@7.6.20
https://github.com/SocketSecurity ignore npm/@storybook/docs-tools@7.6.20
https://github.com/SocketSecurity ignore npm/@storybook/router@7.6.20
https://github.com/SocketSecurity ignore npm/@storybook/builder-webpack5@7.6.20
https://github.com/SocketSecurity ignore npm/@storybook/preset-react-webpack@7.6.20
https://github.com/SocketSecurity ignore npm/@storybook/core-webpack@7.6.20
https://github.com/SocketSecurity ignore npm/@storybook/core-client@7.6.20
https://github.com/SocketSecurity ignore npm/@storybook/cli@7.6.20
https://github.com/SocketSecurity ignore npm/@storybook/codemod@7.6.20
https://github.com/SocketSecurity ignore npm/@storybook/core-server@7.6.20
https://github.com/SocketSecurity ignore npm/@storybook/telemetry@7.6.20
https://github.com/SocketSecurity ignore npm/@storybook/addon-a11y@7.6.20
https://github.com/SocketSecurity ignore npm/@storybook/builder-manager@7.6.20
https://github.com/SocketSecurity ignore npm/@storybook/react-webpack5@7.6.20
https://github.com/SocketSecurity ignore npm/@storybook/addons@7.6.20
https://github.com/SocketSecurity ignore npm/@storybook/api@7.6.20
https://github.com/SocketSecurity ignore npm/@storybook/addon-mdx-gfm@7.6.20
https://github.com/SocketSecurity ignore npm/@storybook/client-api@7.6.20

New author OK (seems to be a storybook maintainer), and these releases are pretty old and were not flagged as malicious

**Comment by Gudahtt** [comment]
@SocketSecurity ignore npm/@storybook/addon-toolbars@7.6.20
@SocketSecurity ignore npm/@storybook/node-logger@7.6.20
@SocketSecurity ignore npm/@storybook/client-logger@7.6.20
@SocketSecurity ignore npm/@storybook/postinstall@7.6.20
@SocketSecurity ignore npm/@storybook/react-dom-shim@7.6.20
@SocketSecurity ignore npm/@storybook/preview@7.6.20
@SocketSecurity ignore npm/@storybook/manager@7.6.20
@SocketSecurity ignore npm/@storybook/addon-essentials@7.6.20
@SocketSecurity ignore npm/@storybook/react@7.6.20
@SocketSecurity ignore npm/storybook@7.6.20
@SocketSecurity ignore npm/@storybook/addon-actions@7.6.20
@SocketSecurity ignore npm/@storybook/addon-backgrounds@7.6.20
@SocketSecurity ignore npm/@storybook/addon-controls@7.6.20
@SocketSecurity ignore npm/@storybook/addon-docs@7.6.20
@SocketSecurity ignore npm/@storybook/addon-highlight@7.6.20
@SocketSecurity ignore npm/@storybook/addon-measure@7.6.20
@SocketSecurity ignore npm/@storybook/addon-outline@7.6.20
@SocketSecurity ignore npm/@storybook/addon-viewport@7.6.20
@SocketSecurity ignore npm/@storybook/core-common@7.6.20
@SocketSecurity ignore npm/@storybook/manager-api@7.6.20
@SocketSecurity ignore npm/@storybook/preview-api@7.6.20
@SocketSecurity ignore npm/@storybook/core-events@7.6.20
@SocketSecurity ignore npm/@storybook/blocks@7.6.20
@SocketSecurity ignore npm/@storybook/components@7.6.20
@SocketSecurity ignore npm/@storybook/csf-plugin@7.6.20
@SocketSecurity ignore npm/@storybook/csf-tools@7.6.20
@SocketSecurity ignore npm/@storybook/theming@7.6.20
@SocketSecurity ignore npm/@storybook/types@7.6.20
@SocketSecurity ignore npm/@storybook/channels@7.6.20
@SocketSecurity ignore npm/@storybook/docs-tools@7.6.20
@SocketSecurity ignore npm/@storybook/router@7.6.20
@SocketSecurity ignore npm/@storybook/builder-webpack5@7.6.20
@SocketSecurity ignore npm/@storybook/preset-react-webpack@7.6.20
@SocketSecurity ignore npm/@storybook/core-webpack@7.6.20
@SocketSecurity ignore npm/@storybook/core-client@7.6.20
@SocketSecurity ignore npm/@storybook/cli@7.6.20
@SocketSecurity ignore npm/@storybook/codemod@7.6.20
@SocketSecurity ignore npm/@storybook/core-server@7.6.20
@SocketSecurity ignore npm/@storybook/telemetry@7.6.20
@SocketSecurity ignore npm/@storybook/addon-a11y@7.6.20
@SocketSecurity ignore npm/@storybook/builder-manager@7.6.20
@SocketSecurity ignore npm/@storybook/react-webpack5@7.6.20
@SocketSecurity ignore npm/@storybook/addons@7.6.20
@SocketSecurity ignore npm/@storybook/api@7.6.20
@SocketSecurity ignore npm/@storybook/addon-mdx-gfm@7.6.20
@SocketSecurity ignore npm/@storybook/client-api@7.6.20

New author OK (seems to be a storybook maintainer), and these releases are pretty old and were not flagged as malicious
New author OK

**Comment by Gudahtt** [comment]
@metamaskbot update-policies

**Comment by Gudahtt** [comment]
@metamaskbot update-policies

**Review by danjm — APPROVED** [review]
Approved! I looked into each difference in file diffs between this PR and the v12.1.1 PR to master, and they all make sense.

On slack I asked: "My only uncertainty is the diff in app/scripts/lib/accounts/BalancesController.ts (https://github.com/MetaMask/metamask-extension/pull/26842/files#diff-0d3633900770a1833627e99171dba672e3dcbdd9e05a6437215fe455813bfd9c), even though it seems that this file was not changed in the v12.1.1 PR (https://github.com/MetaMask/metamask-extension/pull/26730/files)"

And the answer: "Those changes were made as part of cherry-picking this commit: [https://github.com/MetaMask/metamask-extension/commit/27655eb8e3a125212484ee23a659e85f6c328290#diff-0d3633900770a1833627[…]9e05a6437215fe455813bfd9c](https://github.com/MetaMask/metamask-extension/commit/27655eb8e3a125212484ee23a659e85f6c328290#diff-0d3633900770a1833627e99171dba672e3dcbdd9e05a6437215fe455813bfd9c)
It required additional changes because this file was in v12.2.0, but it was not present in v12.1.1"

So LGTM

**Pull request merged**
