### PR TITLE
Enabling the MetaMask Security Code Scanner

### PR DESCRIPTION
**Pull request by witmicko**
## Required Action

Prior to merging this pull request, please ensure the following has been completed:
- [x] The lines specifying `branches` correctly specifies this repository's default branch (usually `main`).
- [ ] Any paths you would like to ignore have been added to the `paths_ignored` configuration option (see [setup](https://github.com/MetaMask/Security-Code-Scanner/blob/main/README.md#setup))
- [x] Any existing CodeQL configuration has been disabled.

## What is the Security Code Scanner?
This pull request enables the [MetaMask Security Code Scanner](https://github.com/metamask/Security-Code-Scanner/) GitHub Action. This action runs on each pull request, and will flag potential vulnerabilities as a review comment. It will also scan this repository's default branch, and log any findings in this repository's [Code Scanning Alerts Tab](https://github.com/metamask/metamask-extension/security/code-scanning). 

Screenshot 2024-02-12 at 9 19 05 PM

The action itself runs various static analysis engines behind the scenes. Currently, it is only running GitHub's CodeQL engine. For this reason, we recommend disabling any existing CodeQL configuration your repository may have.

## How do I interact with the tool?

Every finding raised by the Security Code Scanner will present context behind the potential vulnerability identified, and allow the developer to fix, or dismiss it.

The finding will automatically be dismissed by pushing a commit that fixes the identified issue, or by manually dismissing the alert using the button in GitHub's UI. If dismissing an alert manually, please add any additional context surrounding the reason for dismissal, as this informs our decision to disable, or improve any poor performing rules. 

 Screenshot 2024-02-12 at 8 41 46 PM

For more configuration options, please review the tool's [README](https://github.com/MetaMask/Security-Code-Scanner/blob/main/README.md). 
For any additional questions, please reach out to `@mm-application-security` slack.

### CODE REVIEW

**Review by NEllusion — DISMISSED** [review]
Looks good from the security side of things. Will need someone from the @MetaMask/extension-devs team to push a commit highlighting the paths they would like to avoid scanning.

**Comment by Gudahtt** [comment]
The examples of third-party/vendored code that I'm aware of are:

- `node_modules`
- `development/chromereload.js`

Definitely seems appropriate to ignore those two at least.

**Review by legobeat — APPROVED** [review]
LGTM but would it be not too tricky to have a preview available of what it would look like on current state of `develop` to get a sense of the amount of signal and noise? Like running this change on a fork? :)

**Review by legobeat — CHANGES_REQUESTED** [review]
Needs to accommodate to not make branches from external repos have failing CI.

**Review by legobeat — APPROVED** [review]
LGTM!

**Review by FrederikBolding — APPROVED** [review]

**Pull request merged**
