### PR TITLE
fix(linea): enable token detection for Linea mainnet and testnet

### PR DESCRIPTION
**Pull request by gauthierpetetin**
## Explanation

Token detection was never enabled in the extension code although the APIs we rely on for token detection do support Linea Mainnet and Linea Goerli.

Work needed:
- Add Linea Mainnet and Linea Goerli to the list of supported networks for autodetection (several enums to update in Extension code base).
- Deploy a smart contract on Linea Mainnet and Linea Goerli. This contract is then used to fetch token balances in batch. Its address needs to be hardcoded in the Extension code base. See assetsContractController.js in the "Core" code base.

### Before

Screenshot 2023-09-01 at 08 28 59

### After

`TBD`

## Manual Testing Steps

1. Install Extension and initialise it with an account that already owns some well-known ERC20 tokens (Ex: USDC) on both Linea Mainnet and Linea Goerli.
2. Go to "Extension Settings > Security & privacy > Token autodetection" and enable "Autodetect tokens" toggle.
3. Select "Linea Mainnet" => **Acceptance criteria: You shall see your USDC listed on the tokens list screen.**
4. Got to "Import tokens > Custom token" screen => **Acceptance criteria: You shall not see the following banner: "Token detection is not available on this network yet."**
5. Import token with address `0x176211869cA2b568f2A7D4EE941E073a821EE1ff` and symbol `USDC ` => Acceptance criteria: Successful import.
6. Select "Linea Goerli" => **Acceptance criteria: You shall see your USDC listed on the tokens list screen.**
7. Got to "Import tokens > Custom token" screen => **Acceptance criteria: You shall not see the following banner: "Token detection is not available on this network yet."**
8. Import token with address `0xb4257f31750961c8e536f5cfcbb3079437700416 ` and symbol `USDC ` => Acceptance criteria: Successful import.

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [x] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Review by DDDDDanica — APPROVED** [review]

**Review by montelaidev — APPROVED** [review]
lgtm

**Comment by chloeYue** [comment]
Test QA ok !

**Comment by gauthierpetetin** [comment]
Thank you all for the reviews. @chloeYue I didn't personally manage to test this PR because I don't have a test account with ERC20 tokens on Linea Mainnet and Linea Goerli. Is there a test account we can use internally for such tests?

**Comment by gauthierpetetin** [comment]
I now have USDC on Linea Mainnet and Linea Goerli on a test account.

Here's the manual import feature, which works: https://recordit.co/O7wi2n8wxL

Here's the automated detection feature, which doesn't work on my side:
https://recordit.co/YUda9N3rr2

=> @chloeYue is it the automated detection feature that you managed to test?

**Comment by nkeywal** [comment]
Hi there, what's the status? IIUC it can be merged but it has not been merged yet?

**Comment by gauthierpetetin** [comment]
Hi @nkeywal ,
We've reviewed that ticket with the team on Monday.
The status is that the work needed to support token detection is more important than what's implemented in this PR.
=> @danjm has knowledge on what needs to be done and will document it in the coming days.

**Comment by danjm** [comment]
To achieve the goal of this PR, the `detectNewTokens` method needs to work on the chosen network: https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/controllers/detect-tokens.js#L102

That means that `isTokenDetectionEnabledForNetwork(chainIdAgainstWhichToDetect)` needs to be true, `this._tokenList.state` needs to be populated, and `this.assetsContractController.getBalancesInSingleCall` needs to successfully return a result.

For  `isTokenDetectionEnabledForNetwork(chainIdAgainstWhichToDetect)` to return `true`, modify the function in `shared/modules/network.utils.ts` to handle the chosen chainId

For `this._tokenList.state` to be populated, automatic token detection needs to be toggled on, and `https://token-api.metaswap.codefi.network/tokens/${chainId}` needs to be active and return a list of tokens

For `this.assetsContractController.getBalancesInSingleCall` to successfully return a result, then `SINGLE_CALL_BALANCES_ADDRESS_BY_CHAINID` in `AssetsContractController.js` of the the core repo's `assets-controllers` package needs to have a key-value pair for the chosen chainId. The key is the chainId, and the value is the address of a contract deployed on that network, a contract which meets the spec of the `single-call-balance-checker-abi`. This is the canonical repo for those contract https://github.com/wbobeirne/eth-balance-checker. So, to make this all work on Linea, of those contracts will need to be deployed to Linea. I believe someone in ConsenSys has done such a deployment in the past... possibly someone on the curated API team.

**Comment by gauthierpetetin** [comment]
Thanks @danjm , here's a quick recap of what remains to be done:

- "modify the `isTokenDetectionEnabledForNetwork` function in shared/modules/network.utils.ts to handle the chosen chainId" => This is done in this PR
- "https://token-api.metaswap.codefi.network/tokens/${chainId} needs to be active and return a list of tokens" => This is done (see [here](https://token-api.metaswap.codefi.network/tokens/0xe708) for LINEA_MAINNET and [here](https://token-api.metaswap.codefi.network/tokens/0xe704) for LINEA_GOERLI)
- "SINGLE_CALL_BALANCES_ADDRESS_BY_CHAINID in AssetsContractController.js of the the core repo's assets-controllers package needs to have a key-value pair for the chosen chainId" => [PR](https://github.com/MetaMask/core/pull/1799) is open on core repo. It needs to be merged, then new version of `'@metamask/assets-controllers` package needs to be published and included in metamask-extension code base.

**Comment by gauthierpetetin** [comment]
Adding `release-blocker` label to this issue as it needs to be included in `release-11.4.0` (Linea team has a hard deadline for this on November 6th).

**Comment by gauthierpetetin** [comment]
The [PR](https://github.com/MetaMask/core/pull/1799) on core repo got merged.
A new version of `@metamask/assets-controllers` package needs to be published but this is blocked by some dependencies issues in the core repo (more detail in this [Slack discussion](https://consensys.slack.com/archives/C01V1L10W2E/p1697015554503239?thread_ts=1696955501.590099&cid=C01V1L10W2E)).
@mcmire is investigating these.

**Comment by gauthierpetetin** [comment]
Here's a recording of the feature on Linea Mainnet: https://recordit.co/hJqmQJWy0g

**Comment by gauthierpetetin** [comment]
Here's an example of response we receive from Token-API:
```
   {
      "address":"0x176211869ca2b568f2a7d4ee941e073a821ee1ff",
      "symbol":"USDC",
      "decimals":6,
      "name":"USD Coin",
      "iconUrl":"https://s2.coinmarketcap.com/static/img/coins/64x64/3408.png",
      "type":"erc20",
      "aggregators":[
         "lineaTeam",
         "coinGecko",
         "lifi",
         "rubic",
         "xswap"
      ],
      "occurrences":5
   }
```
You can notice `occurrences` is set to 5, because USDC si listed on 5 different `aggregators`.
The token detection feature works in a way, where tokens get detected only if token is listed on at least 3 `aggregators` (cf. this piece of [code](https://github.com/MetaMask/core/blob/main/packages/assets-controllers/src/TokenListController.ts#L290)).

Due to this condition, tokens will never be detected on Linea Goerli, despite the feature being implemented, because there is only one single `aggregator` on this network: "lineaTeam".

cc @danjm @pedronfigueiredo maybe we're fine with this behaviour, or maybe an alternative could be to remove this "3 `aggregators`" condition in case the network is a testnet. What do you think?

**Comment by gauthierpetetin** [comment]
This issue got unblocked by the upgrade of [assets controllers to version 16](https://github.com/MetaMask/metamask-extension/pull/21380#top) finalised by @pedronfigueiredo today.
@chloeYue this means this PR is ready to be re-tested.

**Comment by chloeYue** [comment]
> This PR got unblocked by the upgrade of [assets controllers to version 16](https://github.com/MetaMask/metamask-extension/pull/21380#top) finalised by @pedronfigueiredo today. @chloeYue this means this PR is ready to be re-tested.

Tested with the latest build, behaviour is as expected. Auto-detect works for Linea Mainnet. QA-passed for this PR.
 

https://github.com/MetaMask/metamask-extension/assets/105063779/7502bcc5-07cc-4ffd-9a05-504a604ac4fc

**Review by chloeYue — APPROVED** [review]

**Pull request merged**
