### PR TITLE
Fix incorrect transaction statuses

### LINKED ISSUE #21941: [Bug]: Transaction stays in `Pending` state even though it's confirmed in Etherscan
### Describe the bug

**Problem:** after sending a transaction I can see how sometimes it stays unusually long to `pending` state. This happened a couple of times and there's [another engineer reporting seeing the same](https://consensys.slack.com/archives/GTQAGKY5V/p1700650172724109).

I've encountered another case even weirder where, I send 2 transactions and both are confirmed on Ethercan but the **first one** stays pending on MetaMask  

### Expected behavior

Tx state should be updated in a reasonable amount of time
Not possible that a subsequent tx is confirmed and the first one is pending (in the wallet)

### Screenshots/Recordings

[MetaMask state logs-pending-tx-11.6.json](https://github.com/MetaMask/metamask-extension/files/13440789/MetaMask.state.logs-pending-tx-11.6.json)

https://github.com/MetaMask/metamask-extension/assets/54408225/f3a99167-7764-4be4-b36c-3060a989e598

https://github.com/MetaMask/metamask-extension/assets/54408225/f0625f9e-d2c3-4afd-a31f-ef2101ff7e9d

### Steps to reproduce

[Edited] Steps:

1. Select Sepolia
2. Send a transaction
3. Before being confirmed, change to Goerli
4. Send a transaction
5. Change back to Sepolia
6. See initial transaction stays in Pending
7. See in Etherscan is confirmed

### Error messages or log output

_No response_

### Version

11.6.0 - also reported in 11.5.1

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### LINKED ISSUE #22237: [Bug]: Incoming transactions are not visible in the Activity list on Firefox RC 11.8.0 (Linea Goerli)
### Describe the bug

Incoming transactions are not visible in the Activity list on Firefox - Linea Goerli testnet.

### Expected behavior

Incoming transactions should be shown in the Activity.

### Screenshots/Recordings

Screenshot 2023-12-12 at 12 45 49 AM

### Steps to reproduce

1. Have two different wallets, one of them on Firefox
2. Send any transaction to the Firefox extension on Linea Goerli network
3. See no incoming transactions in the Activity list

### Error messages or log output

_No response_

### Version

11.8.0

### Build type

None

### Browser

Firefox

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### LINKED ISSUE #22312: [Bug]: Swap shows as Dropped in MM UI and successful on chain (example - LINEA)
### Describe the bug

Swap shows as Dropped in MM UI and successful on network

### Expected behavior

_No response_

### Screenshots/Recordings

Screenshot 2023-12-17 at 1 04 42 PM

Screenshot 2023-12-17 at 12 38 17 PM

Screenshot 2023-12-17 at 12 38 27 PM

Screenshot 2023-12-17 at 12 39 35 PM

Screenshot 2023-12-17 at 12 45 11 PM

Screenshot 2023-12-17 at 12 58 46 PM

Screenshot 2023-12-17 at 12 43 46 PM

Screenshot 2023-12-17 at 12 43 56 PM

Screenshot 2023-12-17 at 12 44 22 PM

### Steps to reproduce

The following was tested on Linea Mainnet 

1. Go to the Swap feature in MM UI 
2. Select token ( my example ETH to USDC) and add the amount
3. Once the estimation of gas is in place confirm the swap ( I have confirmed that gas fees were within current market values that should cover the swap) 
4. When clicking on a hyperlink "View Swap on lineascan.build"  within the 'Processing.. " view it leads to the pending tx 
5. Click on the "View in activity" button within the 'Processing.. " view - and at that time the UI showed that Swap was Failed 
5. Later on in MM UI swap appears as dropped, but when you click on "View on block explore" - it leads you to the successful tx on chain [https://lineascan.build/tx/0x028025cc34cc0889084a71a2d0c20950d42d055d527e0711abbf9cda928ee19e](url)

### Error messages or log output

_No response_

### Version

11.7.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### LINKED ISSUE #22333: [Bug]: Gas fix or default value not working in recent updates.
### Describe the bug

I've fixed the gas in a network, it works well in the old version. But not in the newest release. 

### Expected behavior

_No response_

### Screenshots/Recordings

_No response_

### Steps to reproduce

1. custom and fix the gas price
2. sendtransaction again it doesn't using my gas

### Error messages or log output

_No response_

### Version

11.7.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by matthewwalsh0**
## **Description**

Update the transaction controller to:

- Fix the `dropped` status detection.
- Ensure previously pending transactions are monitored after switching network and not stuck as `pending`.
- Prevent `failed` transactions on networks that use pending transaction receipts with `null` status.
- Fix recording of `v` value to prevent errors when using `eth_getTransactionByHash`.

Also fix usage of saved gas fees.

See [related core PR](https://github.com/MetaMask/core/pull/3676).

## **Related issues**

Fixes: #21941 #22312 #22333 

### Pending Issue

1. Add a transaction.
2. Switch networks before the transaction is confirmed.
3. Add a transaction on the new network, but do not need to approve.
4. Switch back to the previous network.
5. Ensure original transaction is confirmed and does not remain pending.

### Dropped Issue

1. Add a transaction.
2. Wait until transaction is confirmed.
3. Switch networks.
4. Create a new transaction from the same account and with the same nonce.
5. Ensure the new transaction is confirmed and not dropped.

### Failed Issue

1. Switch to ZK network or any network that returns transaction receipts for pending transactions.
2. Add a transaction.
3. Ensure transaction is confirmed and not immediately set to failed.

### Saved Gas Fees

1. Add transaction.
2. Edit gas fee.
3. Enter advanced value.
4. Save for current chain.
5. Create second transaction on same chain.
6. Verify gas fee is saved value.
7. Change network.
8. Add transaction.
9. Verify no saved gas fee.

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [x] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by seaona** [comment]
I see both issues fixed in this branch

## Dropped tx fixed
https://github.com/MetaMask/metamask-extension/assets/54408225/3174f955-dd9a-4fd3-81f9-d01ae392978e

## Pending tx fixed
https://github.com/MetaMask/metamask-extension/assets/54408225/9b3dd611-2b52-497f-a04d-0299819adcec

**Comment by seaona** [comment]
## Failed tx fixed

https://github.com/MetaMask/metamask-extension/assets/54408225/80cee790-2f28-4672-bdf9-b756db154d70


**Repro**: seemed a bit trickier to repro - not happening always, but **very frequently**
- sending tx
- try speeding up / cancel
- sending another tx
- reset wallet
- sending tx

https://github.com/MetaMask/metamask-extension/assets/54408225/2010b5e3-3bfd-43cf-baa7-ac683e44afd0

**Comment by sleepytanya** [comment]
Dropped incoming transaction. Previous transaction nonce on the receiving account was 2 while dropped incoming transaction nonce (sent from another account was 5). Transaction shown as successful on block explorer https://sepolia.etherscan.io/tx/0xcb807c4f824a2435e20c96e29905a508623c3d55388b4f9a519db41ee5721fcf
State log:
[dropped.json](https://github.com/MetaMask/metamask-extension/files/13705703/dropped.json)

Screenshot 2023-12-18 at 10 43 05 AM

**Review by dbrans — DISMISSED** [review]

**Comment by sleepytanya** [comment]
Confirming that pending transaction is fixed:
Chrome

https://github.com/MetaMask/metamask-extension/assets/104780023/d30e55c7-66e4-4aea-975c-57f4a6671869

Firefox

https://github.com/MetaMask/metamask-extension/assets/104780023/e4c41c7a-ff8a-443f-90ea-e660eff44d1e

Dropped transaction looks fixed too:
Chrome

https://github.com/MetaMask/metamask-extension/assets/104780023/a1c46e9b-bb93-468f-ba8a-f9e0b3acf9eb

Firefox

https://github.com/MetaMask/metamask-extension/assets/104780023/ecf5a747-c353-43d0-91f0-843c19eee507

**Comment by sleepytanya** [comment]
For some reason gas option on this branch look like this:
Screenshot 2023-12-18 at 10 35 15 AM
11.8.0 gas options look:
Screenshot 2023-12-18 at 11 27 35 AM

**Review by vinistevam — DISMISSED** [review]

**Review by vinistevam — DISMISSED** [review]

**Comment by sleepytanya** [comment]
Confirming that Advanced Gas feature work as expected - saved values are applied to subsequent transactions on the same network:

Firefox

https://github.com/MetaMask/metamask-extension/assets/104780023/45882192-23d6-4332-9136-4a62fd0ae1f9

Chrome



https://github.com/MetaMask/metamask-extension/assets/104780023/fb6a59e6-c561-496b-a146-77db056ddcb6

**Review by vinistevam — APPROVED** [review]

**Review by dbrans — APPROVED** [review]

**Pull request merged**
