### PR TITLE
PermissionsController - capabilities rpc

### PR DESCRIPTION
**Pull request by kumavis**
this is an attempt at taking @danfinlay's work and reducing conflicts against develop, especially after #6410 lands.

### notes
  - my approach here was optimized toward minimizing conflict
  - nested things in `MetamaskController` under a `PermissionsController`
  - changed `memStore` structure (see in `MetamaskController`)
  - kept `providerApprovalController` as is
  - ui copied from providerApproval screens and modified per Dan's PR
  - skipped many things that seemed unused (see "Not Implemented")

### Revisit
  - background
    - metamask-inpage-provider#capabilities
    - PermissionsController
      - requestUnlock
      - createPermissions eth_accounts async middleware
      - stores need initState?
      - middleware placement?

 ### Not Implemented (skipped)
 - this.connections = {}
- this.logins = {}
- this.domainMetadata
- setupMessageHandler
- sendMessage
- sendPublicMessage
- clearApprovedOrigins (noop)
- this.emit('approvedPermissions:domain', opts)
- approveProviderRequest
- rejectProviderRequest
- unlocked handling
  - this.emit('unlocked') ?
- deps
  - "eth-login-controller": "^2.1.0", (unused)
    "metamask-inpage-provider": "MetaMask/metamask-inpage-provider#capabilities-change", (unused)

### CODE REVIEW

**Comment by kumavis** [comment]
some of the state doesn't seem quite hooked up yet

**Comment by kumavis** [comment]
ok got it actually passing QA : )

**Comment by kumavis** [comment]
though i didnt test it against `eth_requestAccounts` or `eth_getAccounts` if thats a thing

**Comment by kumavis** [comment]
@danfinlay made this as a suggestion for you, awhile back. its likely not relevant anymore. please close if you're done with it

**Comment by danfinlay** [comment]
I think we actually based `LoginPerSite` branch on this already, so closing.

**Pull request closed without merging**
