### PR TITLE
Version v12.2.0

### PR DESCRIPTION
**Pull request by benjisclowder**
RC V12.2.0

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/25803?quickstart=1)

### CODE REVIEW

**Comment by benjisclowder** [comment]
[Manual test scenarios:](https://github.com/MetaMask/metamask-extension/tree/develop/test/manual-scenarios)

**Chrome**

- [ ] Onboarding - create a wallet
- [ ]  Onboarding - import a wallet
- [ ]  Keyring - connect hardware wallet
- [ ]  Keyring - reset a wallet
- [ ]  Transactions - send native token origin MM
- [ ]  Transactions - send native token origin dapp
- [ ]  Transactions - send ERC20 token origin MM
- [ ]  Transactions - send ERC20 token origin dapp
- [ ]  Transactions - send ERC721 token origin MM
- [ ]  Transactions - send ERC721 token origin dapp
- [ ]  Transactions - speed up transaction
- [ ]  Transactions - cancel transaction
- [ ]  Transactions - deploy failing transaction
- [ ]  Transactions - deposit and withdraw
- [ ]  Transactions - navigate multiple transactions
- [ ]  Transactions - send transactions with custom nonce
- [ ]  Transactions - cancel transaction using same nonce
- [ ]  Tokens - import ERC20 token origin MM
- [ ]  Tokens - import ERC20 token origin dapp
- [ ]  Tokens - import ERC721 token origin MM
- [ ]  Tokens - import ERC721 token origin dapp
- [ ]  Tokens - import ERC1155 token origin MM
- [ ]  Tokens - import ERC1155 token origin dapp
- [ ]  Tokens - approve ERC1155 token
- [ ]  Tokens - approve ERC20 token
- [ ]  Tokens - approve ERC721 token
- [ ]  Tokens - autodetect tokens
- [ ]  Tokens - autodetect NFTs
- [ ]  Tokens - approve erc20 custom amount
- [ ]  ENS - name resolution
- [ ]  Phishing - warning page
- [ ]  Network - add custom network manually
- [ ]  Network - add custom network from the list of popular networks
- [ ]  Network - add custom network from dApp
- [ ]  Network - update networks
- [ ]  Network - switching networks
- [ ]  Network - delete networks from the dropdown list
- [ ]  Network - delete networks in Settings
- [ ]  Backup - backup user data
- [ ]  Backup - restore user data
- [ ]  Metrics - send event metrics
- [ ]  Address-book - add a contact to the address book
- [ ]  Address-book - remove a contact from the address book
- [ ]  Address-book - update a contact in the address book
- [ ]  Gas fee - EIP-1559 gas
- [ ]  Gas fee - legacy gas
- [ ]  Sign - eth sign
- [ ]  Sign - personal sign
- [ ]  Sign - sign in with ethereum
- [ ]  Sign - sign typed with data
- [ ]  Sign - sign typed data v3 with hardware wallet
- [ ]  Sign - sign typed data v4 with hardware wallet
- [ ]  Sign - personal sign with hardware wallet
- [ ]  Sign - eth sign with hardware wallet
- [ ]  Permissions - connecting and disconnecting from a dapp
- [ ]  Swap - smart swap
- [ ]  Swap - swap eth
- [ ]  Incoming transactions - receive native token
- [ ]  Settings - about MetaMask
- [ ]  Settings - general - change language
- [ ]  Settings - advanced - check custom nonce toggle
- [ ]  Settings - advanced - show hex data
- [ ]  Contract - deploy contract, mint and import NFT with hardware wallet
- [ ]  Contract - hardware wallet qr based connect
- [ ]  Contract - send token with hardware wallet

**Firefox**

- [ ]  Onboarding - create a wallet
- [ ]  Onboarding - import a wallet
- [ ]  Keyring - connect hardware wallet
- [ ]  Keyring - reset a wallet
- [ ]  Transactions - send native token origin MM
- [ ]  Transactions - send native token origin dapp
- [ ]  Transactions - send ERC20 token origin MM
- [ ]  Transactions - send ERC20 token origin dapp
- [ ]  Transactions - send ERC721 token origin MM
- [ ]  Transactions - send ERC721 token origin dapp
- [ ]  Transactions - speed up transaction
- [ ]  Transactions - cancel transaction
- [ ]  Transactions - deploy failing transaction
- [ ]  Transactions - deposit and withdraw
- [ ]  Transactions - navigate multiple transactions
- [ ]  Transactions - send transactions with custom nonce
- [ ]  Transactions - cancel transaction using same nonce
- [ ]  Tokens - import ERC20 token origin MM
- [ ]  Tokens - import ERC20 token origin dapp
- [ ]  Tokens - import ERC721 token origin MM
- [ ]  Tokens - import ERC721 token origin dapp
- [ ]  Tokens - import ERC1155 token origin MM
- [ ]  Tokens - import ERC1155 token origin dapp
- [ ]  Tokens - approve ERC1155 token
- [ ]  Tokens - approve ERC20 token
- [ ]  Tokens - approve ERC721 token
- [ ]  Tokens - autodetect tokens
- [ ]  Tokens - autodetect NFTs
- [ ]  Tokens - approve erc20 custom amount
- [ ]  ENS - name resolution
- [ ]  Phishing - warning page
- [ ]  Network - add custom network manually
- [ ]  Network - add custom network from the list of popular networks
- [ ]  Network - add custom network from dApp
- [ ]  Network - update networks
- [ ]  Network - switching networks
- [ ]  Network - delete networks from the dropdown list
- [ ]  Network - delete networks in Settings
- [ ]  Backup - backup user data
- [ ]  Backup - restore user data
- [ ]  Metrics - send event metrics
- [ ]  Address-book - add a contact to the address book
- [ ]  Address-book - remove a contact from the address book
- [ ]  Address-book - update a contact in the address book
- [ ]  Gas fee - EIP-1559 gas
- [ ]  Gas fee - legacy gas
- [ ]  Sign - eth sign
- [ ]  Sign - personal sign
- [ ]  Sign - sign in with ethereum
- [ ]  Sign - sign typed with data
- [ ]  Sign - sign typed data v3 with hardware wallet
- [ ]  Sign - sign typed data v4 with hardware wallet
- [ ]  Sign - personal sign with hardware wallet
- [ ]  Sign - eth sign with hardware wallet
- [ ]  Permissions - connecting and disconnecting from a dapp
- [ ]  Swap - smart swap
- [ ]  Swap - swap eth
- [ ]  Incoming transactions - receive native token
- [ ]  Settings - about MetaMask
- [ ]  Settings - general - change language
- [ ]  Settings - advanced - check custom nonce toggle
- [ ]  Settings - advanced - show hex data
- [ ]  Contract - deploy contract, mint and import NFT with hardware wallet
- [ ]  Contract - hardware wallet qr based connect
- [ ]  Contract - send token with hardware wallet

**Review by georgewrmarshall — COMMENTED** [review]
Is there a check sheet for release contacts to check off included PRs yet for `12.2.0`?

**Comment by Bullcoiner** [comment]
**Chrome Browser QA testing checks:**

- [x] Onboarding - create a wallet
- [x]  Onboarding - import a wallet
- [x]  Keyring - connect hardware wallet
- [x]  Keyring - reset a wallet
- [x]  Transactions - send native token origin MM
- [x]  Transactions - send native token origin dapp
- [x]  Transactions - send ERC20 token origin MM
- [x]  Transactions - send ERC20 token origin dapp
- [x]  Transactions - send ERC721 token origin MM
- [x]  Transactions - send ERC721 token origin dapp
- [x]  Transactions - speed up transaction
- [x]  Transactions - cancel transaction
- [x]  Transactions - deploy failing transaction
- [ ]  ❌ Transactions - deposit and withdraw  (neither deposit/withdraw transactions worked)
- [x]  Transactions - navigate multiple transactions
- [x]  Transactions - send transactions with custom nonce
- [x]  Transactions - cancel transaction using same nonce
- [x]  Tokens - import ERC20 token origin MM
- [x]  Tokens - import ERC20 token origin dapp
- [x]  Tokens - import ERC721 token origin MM
- [x]  Tokens - import ERC721 token origin dapp
- [x]  Tokens - import ERC1155 token origin MM
- [x]  Tokens - import ERC1155 token origin dapp
- [x]  Tokens - approve ERC1155 token
- [x]  Tokens - approve ERC20 token
- [x]  Tokens - approve ERC721 token
- [x]  Tokens - autodetect tokens
- [x]  Tokens - autodetect NFTs
- [x]  Tokens - approve erc20 custom amount
- [x]  ENS - name resolution
- [x]  Phishing - warning page
- [x]  Network - add custom network manually
- [x]  Network - add custom network from the list of popular networks
- [x]  Network - add custom network from dApp
- [x]  Network - update networks
- [x]  Network - switching networks
- [x]  Network - delete networks from the dropdown list
- [x]  Network - delete networks in Settings
- [x]  Backup - backup user data
- [x]  Backup - restore user data
- [x]  Metrics - send event metrics
- [ ]  ❌ Address-book - add a contact to the address book (could not add a new contact, save button did not work in expanded view nor extension window, no error message)
- [ ]  ❌ Address-book - remove a contact from the address book
- [ ]  ❌ Address-book - update a contact in the address book
- [x]  Gas fee - EIP-1559 gas
- [x]  Gas fee - legacy gas
- [x]  Sign - personal sign
- [x]  Sign - sign in with ethereum
- [x]  Sign - sign typed with data
- [ ]  ❌ Sign - sign typed data v3 with hardware wallet (Ledger: Only version 4 of typed data signing is supported)
- [x]  Sign - sign typed data v4 with hardware wallet
- [x]  Sign - personal sign with hardware wallet
- [x]  Permissions - connecting and disconnecting from a dapp
- [x]  Swap - smart swap
- [x]  Swap - swap eth
- [x]  Incoming transactions - receive native token
- [x]  Settings - about MetaMask
- [x]  Settings - general - change language
- [x]  Settings - advanced - check custom nonce toggle
- [x]  Settings - advanced - show hex data
- [x]  Contract - deploy contract, mint and import NFT with hardware wallet
- [x]  Contract - hardware wallet qr based connect
- [x]  Contract - send token with hardware wallet

**Comment by DanielTech21** [comment]
- [ ] [Manual test scenarios:](https://github.com/MetaMask/metamask-extension/tree/develop/test/manual-scenarios)

**Firefox**

- [ ]  Onboarding - create a wallet
- [ ]  Onboarding - import a wallet
- [ ]  Keyring - connect hardware wallet
- [ ]  Keyring - reset a wallet
- [ ]  Transactions - send native token origin MM
- [ ]  Transactions - send native token origin dapp
- [ ]  Transactions - send ERC20 token origin MM
- [ ]  Transactions - send ERC20 token origin dapp
- [ ]  Transactions - send ERC721 token origin MM
- [ ]  Transactions - send ERC721 token origin dapp
- [ ]  Transactions - speed up transaction
- [ ]  Transactions - cancel transaction
- [ ]  Transactions - deploy failing transaction
- [ ]  Transactions - deposit and withdraw
- [ ]  Transactions - navigate multiple transactions
- [ ]  Transactions - send transactions with custom nonce
- [ ]  Transactions - cancel transaction using same nonce
- [ ]  Tokens - import ERC20 token origin MM
- [ ]  Tokens - import ERC20 token origin dapp
- [ ]  Tokens - import ERC721 token origin MM
- [ ]  Tokens - import ERC721 token origin dapp
- [ ]  Tokens - import ERC1155 token origin MM
- [ ]  Tokens - import ERC1155 token origin dapp
- [ ]  Tokens - approve ERC1155 token
- [ ]  Tokens - approve ERC20 token
- [ ]  Tokens - approve ERC721 token
- [ ]  Tokens - autodetect tokens
- [ ]  Tokens - autodetect NFTs
- [ ]  Tokens - approve erc20 custom amount
- [ ]  ENS - name resolution - does not recognize ENS in testnets
- [ ]  Phishing - warning page
- [ ]  Network - add custom network manually
- [ ]  Network - add custom network from the list of popular networks
- [ ]  Network - add custom network from dApp
- [ ]  Network - update networks
- [ ]  Network - switching networks
- [ ]  Network - delete networks from the dropdown list
- [ ]  Network - delete networks in Settings
- [ ]  Backup - backup user data
- [ ]  Backup - restore user data
- [ ]  Metrics - send event metrics
- [ ]  Address-book - add a contact to the address book
- [ ]  Address-book - remove a contact from the address book
- [ ]  Address-book - update a contact in the address book
- [ ]  Gas fee - EIP-1559 gas
- [ ]  Gas fee - legacy gas
- [ ]  Sign - personal sign
- [ ]  Sign - sign in with ethereum
- [ ]  Sign - sign typed with data
- [ ]  Sign - sign typed data v3 with hardware wallet
- [ ]  Sign - sign typed data v4 with hardware wallet
- [ ]  Sign - personal sign with hardware wallet
- [ ]  Permissions - connecting and disconnecting from a dapp
- [ ]  Swap - smart swap
- [ ]  Swap - swap eth
- [ ]  Incoming transactions - receive native token
- [ ]  Settings - about MetaMask
- [ ]  Settings - general - change language - https://github.com/MetaMask/metamask-extension/issues/25698
- [ ]  Settings - advanced - check custom nonce toggle
- [ ]  Settings - advanced - show hex data
- [ ]  Contract - deploy contract, mint and import NFT with hardware wallet
- [ ]  Contract - hardware wallet qr based connect
- [ ]  Contract - send token with hardware wallet

**Comment by benjisclowder** [comment]
Hi! Now that we've finished v12.1.0 validation, we can start testing v12.2.0. Let's do this! :rocketship:

Instructions for Team Review

Review Changes: Refer to the [Release Tracker for v12.1.0](https://docs.google.com/spreadsheets/d/1tsoodlAlyvEUpkkcNcbZ4PM9HuC9cEM80RZeoVv5OCQ/edit?gid=2099993340#gid=2099993340) to see all changes relevant to your team.

Log Bugs: If you find any issues, log them in the release tracker and attach them to the https://github.com/MetaMask/MetaMask-planning/issues/2729.

Approval: After reviewing, indicate your team's approval by:

Marking the checkbox next to your team's name in this comment.
Optionally, leave a comment for additional information.
Your thorough review ensures a smooth and successful release. If you have any questions please reach out to extension platform team or in the [#metamask-qa](https://consensys.slack.com/archives/C01U65ZUS2E) slack channel. Thank you for your collaboration!

- [ ]  Accounts: @gantunesr - There are 21 Accounts changes in v12.2.0
- [ ]  Assets: @sahar-fehri / @alfeng6 - There are 2 Assets changes in v12.2.0
- [ ]  Bridging: @micaelae / @BZahory - There are 3 Bridging changes in v12.2.0
- [ ]  Confirmations: @sleepytanya / @cryptotavares - There are 24 Confirmations changes in v12.2.0.
- [ ]  Design/Systems: @georgewrmarshall - There are 3 Design/Systems change in v12.2.0.
- [ ]  MMI: @zone-live / @shane-t - There are 3 MMI changes in v12.2.0.
- [ ]  Notifications: @Prithpal-Sooriya / @matteoscurati - There is Notifications change in v12.2.0
- [ ]  Ramps: @georgeweiler - There are 2 Ramps changes in v12.2.0.
- [ ]  Snaps: @bowensanders / @FrederikBolding / @Montoya - There are 3 Snaps changes in v12.2.0.
- [ ]  Swaps: @davibroc - There are 2 Swaps changes in v12.2.0.
- [ ]  Transactions: @dbrans - There is 1 Transactions change in v12.2.0.
- [ ]  Wallet Framework: @Gudahtt - There are 10 Wallet Framework changes in v12.1.0.
- [ ]  Wallet UX: @darkwing / @NidhiKJha - There are 8 Wallet UX changes in v12.1.0.

**Comment by benjisclowder** [comment]
Hi! Now that we've finished v12.1.0 validation, we can start testing v12.2.0. Let's do this! :rocketship:

**Instructions for Team Review**

**Review Changes**: Refer to the [Release Tracker for v12.2.0](https://docs.google.com/spreadsheets/d/1tsoodlAlyvEUpkkcNcbZ4PM9HuC9cEM80RZeoVv5OCQ/edit?gid=1825080697#gid=1825080697) to see all changes relevant to your team.

**Log Bugs**: If you find any issues, log them in the release tracker and attach them to the https://github.com/MetaMask/MetaMask-planning/issues/2768.

**Approval**: After reviewing, indicate your team's approval by:

- Marking the checkbox next to your team's name in this comment.
- Optionally, leave a comment for additional information.
- Your thorough review ensures a smooth and successful release. If you have any questions please reach out to extension platform team or in the [#metamask-qa](https://consensys.slack.com/archives/C01U65ZUS2E) slack channel. Thank you for your collaboration!

- [ ]  Accounts: @gustavo.antunes - There are 21 Accounts changes in v12.2.0
- [ ]  Assets: @sahar.fehri / @albert.feng - There are 2 Assets changes in v12.2.0
- [ ]  Bridging: @micaela.estabillo / @bilal.zahory - There are 3 Bridging changes in v12.2.0
- [ ]  Confirmations: @tatiana.bobritsky / @joao.tavares - There are 24 Confirmations changes in v12.2.0.
- [ ]  Design/Systems: @george.marshall - There are 3 Design/Systems change in v12.2.0.
- [ ]  MMI: @antonio.regadas / @Shane T - There are 3 MMI changes in v12.2.0.
- [ ]  Notifications: @prithpal.sooriya / @matteo.scurati - There is Notifications change in v12.2.0
- [ ]  Ramps: @george.weiler - There are 2 Ramps changes in v12.2.0.
- [ ]  Snaps: @bowen.sanders / @frederik.bolding / @christian.montoya - There are 3 Snaps changes in v12.2.0.
- [ ]  Swaps: @davide.brocchetto - There are 2 Swaps changes in v12.2.0.
- [ ]  Transactions: @derek.brans - There is 1 Transactions change in v12.2.0.
- [ ]  Wallet Framework: @mark.stacey - There are 2 Wallet Framework changes in v12.2.0.
- [ ]  Wallet UX: @david.walsh / @nidhi.kumari - There are 3 Wallet UX changes in v12.2.0.
- [ ] Wallet API: @adonesky1 - There is 1 Wallet API change in v12.2.0

**Comment by georgewrmarshall** [comment]
🟢 Approved for @MetaMask/design-system 
Checked the following PRs:
- https://github.com/MetaMask/metamask-extension/pull/25262
- https://github.com/MetaMask/metamask-extension/pull/25227
- https://github.com/MetaMask/metamask-extension/pull/25284

**Review by georgewrmarshall — COMMENTED** [review]
🟢 Approved for @MetaMask/design-system 
Checked the following PRs:
- https://github.com/MetaMask/metamask-extension/pull/25262
- https://github.com/MetaMask/metamask-extension/pull/25227
- https://github.com/MetaMask/metamask-extension/pull/25284

**Comment by wachunei** [comment]
I validated Ramps changes https://github.com/MetaMask/metamask-extension/pull/25621 https://github.com/MetaMask/metamask-extension/pull/25686

**Comment by gantunesr** [comment]
Approved changes for the Accounts team including cherry-picks,

- [x] https://github.com/MetaMask/metamask-extension/pull/25739
- [x] https://github.com/MetaMask/metamask-extension/pull/25719
- [x] https://github.com/MetaMask/metamask-extension/pull/25715
- [x] https://github.com/MetaMask/metamask-extension/pull/25676
- [x] https://github.com/MetaMask/metamask-extension/pull/25672
- [x] https://github.com/MetaMask/metamask-extension/pull/25659
- [x] https://github.com/MetaMask/metamask-extension/pull/25642
- [x] https://github.com/MetaMask/metamask-extension/pull/25633
- [x] https://github.com/MetaMask/metamask-extension/pull/25628
- [x] https://github.com/MetaMask/metamask-extension/pull/25625
- [x] https://github.com/MetaMask/metamask-extension/pull/25616
- [x] https://github.com/MetaMask/metamask-extension/pull/25615
- [x] https://github.com/MetaMask/metamask-extension/pull/25558
- [x] https://github.com/MetaMask/metamask-extension/pull/25540
- [x] https://github.com/MetaMask/metamask-extension/pull/25526
- [x] https://github.com/MetaMask/metamask-extension/pull/25500

**Comment by danjm** [comment]
@SocketSecurity ignore-all

**Review by danjm — APPROVED** [review]

**Pull request merged**
