### PR TITLE
Use shared MetaMask ESLint config

### PR DESCRIPTION
**Pull request by whymarrh**
This PR replaces a portion of the ESLint config with the shared ESLint config. The rules for the import, React, Babel, and Mocha plugins are still here.

### CODE REVIEW

**Review by rekmarks — COMMENTED** [review]
>The rules for the import, React, Babel, and Mocha plugins are still here.

Why not pare down the `.eslintrc.js` here even more and have a `@metamask/eslint-config/config/extension`?

**Review by Gudahtt — APPROVED** [review]
Looks good to me!

The React rules could probably be moved into their own config module, but where it's only used here for now I don't feel strongly about it.

What was the reason for not including the `import` rules in the base config though? I would expect we'd want those basically everywhere.

**Comment by whymarrh** [comment]
> Why not pare down the `.eslintrc.js` here even more and have a `@metamask/eslint-config/config/extension`?

@rekmarks because I should be working on other things 😅 

> What was the reason for not including the import rules in the base config though? I would expect we'd want those basically everywhere.

I didn't (don't?) know if they apply to TypeScript code—if they do, great, we can add them to the base config, else we can add a separate config for an ES6 project that has them.

**Comment by Gudahtt** [comment]
>I didn't (don't?) know if they apply to TypeScript code

I had assumed most or all of them would work - TypeScript does use standard ES6 imports after all.
There is a [note in the README](https://github.com/benmosher/eslint-plugin-import#typescript) about having to set certain settings to get it to work nicely with TypeScript though. Might take a bit of tinkering.

**Comment by whymarrh** [comment]
I've linked a few issues (shown above) for the _continuation_ of this work.

**Comment by rekmarks** [comment]
>@rekmarks because I should be working on other things 😅

lol, say no more fam

**Pull request merged**
