### PR TITLE
Adding NFT autodetection to "What's New" Announcements

### LINKED ISSUE #17637: Create "What's New" for NFTs
## Background
We'll be releasing NFT support on extension. The auto detection of NFTs will be behind an experimental toggle. When the user goes to the NFT tab, they'll see a notice saying we have NFT support enabled on extension, but to use the auto-detection NFT feature, they'll need to enable that via settings. Once enabled, that toast banner will not appear.

## Acceptance Criteria
Create What's New with the following suggested copy: 
We have enabled NFT support on MetaMask Extension! To view your NFTs, you can manually add them, or turn on the NFT auto-detection feature through settings [link]. We currently only support ERC-721.

### PR DESCRIPTION
**Pull request by vthomas13**
## Explanation
Adding NFT autodetection announcement to "What's new"
* Fixes #17637 

### After
image

## Manual Testing Steps
- Install a MetaMask extension build from this branch 
- Install dependencies with `yarn`
- Run with: `NFTS_V1=1 COLLECTIBLES=1 COLLECTABLES=1 yarn start`
- Upon opening the app, a new announcement should be shown

## Pre-merge author checklist

- [X] I've clearly explained:
  - [X] What problem this PR is solving
  - [X] How this problem was solved
  - [X] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Comment by SaraCheikh** [comment]
@vthomas13 the image in full screen seems a bit displaced going over the background, Do you need me to send the images in other format that SVG?

**Comment by vthomas13** [comment]
> @vthomas13 the image in full screen seems a bit displaced going over the background, Do you need me to send the images in other format that SVG?

@SaraCheikh I think maybe .png may work here. 
Question: Is scrolling in the What's New announcement desired here? I tried scaling the picture down to 70% size and it looked nice when the Enable Autodetect button was shown without having to scroll for it.

**Review by darkwing — DISMISSED** [review]

**Comment by darkwing** [comment]
Marking as DNM until https://github.com/MetaMask/metamask-extension/pull/17401 is merged.

**Review by darkwing — DISMISSED** [review]
Well done!

**Review by darkwing — DISMISSED** [review]

**Review by danjm — DISMISSED** [review]

**Review by darkwing — DISMISSED** [review]

**Review by darkwing — APPROVED** [review]

**Review by NidhiKJha — APPROVED** [review]

**Pull request merged**
