### PR TITLE
Test - small refactor of e2e

### PR DESCRIPTION
**Pull request by kumavis**
i know e2e v2 is coming, so this may be shortlived, but here is some code refactor and improvements for e2e tests

### CODE REVIEW

**Comment by kumavis** [comment]
this should fix the fetch inf loop issue

**Review by danjm — APPROVED** [review]
LGTM

**Comment by danjm** [comment]
nice improvements

**Review by Gudahtt — APPROVED** [review]
These all look like worthwhile improvements.

I've been tempted to delay addressing these e2e test problems until we start migrating the tests to e2e v2, but simplifying these tests might help with that migration anyway. Especially that fetch mock issue, that was a great find.

**Pull request merged**
