### PR TITLE
Version v11.12.0

### PR DESCRIPTION
**Pull request by chloeYue**
RC v11.12.0

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by chloeYue** [comment]
V11.12.0 Bug Report: https://github.com/MetaMask/MetaMask-planning/issues/2138

**Comment by benjisclowder** [comment]
[Manual test scenarios:](https://github.com/MetaMask/metamask-extension/tree/develop/test/scenarios)

Chrome

- [ ]  Onboarding - create a wallet
- [ ]  Onboarding - import a wallet
- [ ]  Keyring - connect hardware wallet
- [ ]  Keyring - reset a wallet
- [ ]  Transactions - send native token origin MM
- [ ]  Transactions - send native token origin dapp
- [ ]  Transactions - send ERC20 token origin MM
- [ ]  Transactions - send ERC20 token origin dapp
- [ ]  Transactions - send ERC721 token origin MM
- [ ]  Transactions - send ERC721 token origin dapp
- [ ]  Transactions - speed up transaction
- [ ]  Transactions - cancel transaction
- [ ]  Tokens - import ERC20 token origin MM
- [ ]  Tokens - import ERC20 token origin dapp
- [ ]  Tokens - import ERC721 token origin MM
- [ ]  Tokens - import ERC721 token origin dapp
- [ ]  Tokens - import ERC1155 token origin MM
- [ ]  Tokens - import ERC1155 token origin dapp
- [ ]  Tokens - approve ERC1155 token
- [ ]  Tokens - approve ERC20 token
- [ ]  Tokens - approve ERC721 token
- [ ]  Tokens - autodetect tokens
- [ ]  Tokens - autodetect NFTs
- [ ]  ENS - name resolution
- [ ]  Phishing - warning page
- [ ]  Network - add custom network manually
- [ ]  Network - add custom network from the list of popular networks
- [ ]  Network - add custom network from dApp
- [ ]  Network - update networks
- [ ]  Network - switching networks
- [ ]  Network - delete networks from the dropdown list
- [ ]  Network - delete networks in Settings
- [ ]  Backup - backup user data
- [ ]  Backup - restore user data
- [ ]  Metrics - send event metrics
- [ ]  Address-book - add a contact to the address book
- [ ]  Address-book - remove a contact from the address book
- [ ]  Address-book - update a contact in the address book
- [ ]  Gas fee - EIP-1559 gas
- [ ]  Gas fee - legacy gas
- [ ]  Sign - eth sign
- [ ]  Sign - personal sign
- [ ]  Sign - sign in with ethereum
- [ ]  Sign - sign typed with data
- [ ]  Sign - sign typed data v3 with hardware wallet
- [ ]  Sign - sign typed data v4 with hardware wallet
- [ ]  Permissions - connecting and disconnecting from a dapp
- [ ]  Swap - smart swap
- [ ]  Swap - swap eth
- [ ]  Incoming transactions - receive native token
- [ ]  Settings - about MetaMask
- [ ]  Settings - general
- [ ]  Settings - advanced

 

Firefox

- [ ]  Onboarding - create a wallet
- [ ]  Onboarding - import a wallet
- [ ]  Keyring - connect hardware wallet
- [ ]  Keyring - reset a wallet
- [ ]  Transactions - send native token origin MM
- [ ]  Transactions - send native token origin dapp
- [ ]  Transactions - send ERC20 token origin MM
- [ ]  Transactions - send ERC20 token origin dapp
- [ ]  Transactions - send ERC721 token origin MM
- [ ]  Transactions - send ERC721 token origin dapp
- [ ]  Transactions - speed up transaction
- [ ]  Transactions - cancel transaction
- [ ]  Tokens - import ERC20 token origin MM
- [ ]  Tokens - import ERC20 token origin dapp
- [ ]  Tokens - import ERC721 token origin MM
- [ ]  Tokens - import ERC721 token origin dapp
- [ ]  Tokens - import ERC1155 token origin MM
- [ ]  Tokens - import ERC1155 token origin dapp
- [ ]  Tokens - approve ERC1155 token
- [ ]  Tokens - approve ERC20 token
- [ ]  Tokens - approve ERC721 token
- [ ]  Tokens - autodetect tokens
- [ ]  Tokens - autodetect NFTs
- [ ]  ENS - name resolution
- [ ]  Phishing - warning page
- [ ]  Network - add custom network manually
- [ ]  Network - add custom network from the list of popular networks
- [ ]  Network - add custom network from dApp
- [ ]  Network - update networks
- [ ]  Network - switching networks
- [ ]  Network - delete networks from the dropdown list
- [ ]  Network - delete networks in Settings
- [ ]  Backup - backup user data
- [ ]  Backup - restore user data
- [ ]  Metrics - send event metrics
- [ ]  Address-book - add a contact to the address book
- [ ]  Address-book - remove a contact from the address book
- [ ]  Address-book - update a contact in the address book
- [ ]  Gas fee - EIP-1559 gas
- [ ]  Gas fee - legacy gas
- [ ]  Sign - eth sign
- [ ]  Sign - personal sign
- [ ]  Sign - sign in with ethereum
- [ ]  Sign - sign typed with data
- [ ]  Sign - sign typed data v3 with hardware wallet
- [ ]  Sign - sign typed data v4 with hardware wallet
- [ ]  Permissions - connecting and disconnecting from a dapp
- [ ]  Swap - smart swap
- [ ]  Swap - swap eth
- [ ]  Incoming transactions - receive native token
- [ ]  Settings - about MetaMask
- [ ]  Settings - general
- [ ]  Settings - advanced

**Comment by benjisclowder** [comment]
Release tracker for change validation on v11.12.0:
https://docs.google.com/spreadsheets/d/1tsoodlAlyvEUpkkcNcbZ4PM9HuC9cEM80RZeoVv5OCQ/edit#gid=396431488

We need teams' approval on the 7th of March at the latest.

 Snaps: @bowensanders / @FrederikBolding / @Montoya - There are 4 functional Snaps changes in v11.12.0. Please take note of the 1 Non-main change (FLASK) commit.
 Confirmation UX: @seaona - There are 9 functional Confirmations UX changes in v11.12.0. Please also take note of the 2 Non-functional/regression possible commits.
 Confirmation Systems: @sleepytanya - There are 3 Confirmation Systems changes in v11.12.0.
 Accounts: @plasmacorral - There are 2 Accounts changes in v11.12.0.
 Wallet UX: @darkwing / @NidhiKJha - There are 14 Wallet UX changes in v11.12.0.
 Design/Systems: @georgewrmarshall - There are 4 Design/Systems changes in v11.12.0. 
 Devex: @tmashuang / @vandan - There is 1 Devex change in v11.12.0.
 DappAPI: @jiexi There are 3 DappAPI changes in v11.12.0 
 Assets: @sahar-fehri / @alfeng6 - There are 5 Assets changes in v11.12.0.
 
Note: please attach all the release bugs to this bug report epic here: https://github.com/MetaMask/MetaMask-planning/issues/2138

Thank you so much!

**Comment by PressGarden** [comment]
> [Manual test scenarios:](https://github.com/MetaMask/metamask-extension/tree/develop/test/scenarios)
>
> I can't edit the original comment (unsure why) so posting results as a comment.
> 
> Chrome
> 
> * [x]   Onboarding - create a wallet
> * [x]   Onboarding - import a wallet
> * [x]   Keyring - connect hardware wallet
> * [x]   Keyring - reset a wallet
> * [x]   Transactions - send native token origin MM
> * [x]   Transactions - send native token origin dapp
> * [x]   Transactions - send ERC20 token origin MM
> * [x]   Transactions - send ERC20 token origin dapp
> * [x]   Transactions - send ERC721 token origin MM
> * [x]   Transactions - send ERC721 token origin dapp
> * [x]   Transactions - speed up transaction
> * [x]   Transactions - cancel transaction
> * [x]   Tokens - import ERC20 token origin MM
> * [x]   Tokens - import ERC20 token origin dapp
> * [x]   Tokens - import ERC721 token origin MM
> * [x]   Tokens - import ERC721 token origin dapp
> * [x]   Tokens - import ERC1155 token origin MM
> * [x]   Tokens - import ERC1155 token origin dapp
> * [x]   Tokens - approve ERC1155 token
> * [x]   Tokens - approve ERC20 token
> * [x]   Tokens - approve ERC721 token
> * [x]   Tokens - autodetect tokens
> * [x]   Tokens - autodetect NFTs
> * [x]   ENS - name resolution
> * [x]   Phishing - warning page
> * [x]   Network - add custom network manually
> * [x]   Network - add custom network from the list of popular networks
> * [x]   Network - add custom network from dApp
> * [x]   Network - update networks
> * [x]   Network - switching networks
> * [x]   Network - delete networks from the dropdown list
> * [x]   Network - delete networks in Settings
> * [x]   Backup - backup user data
> * [x]   Backup - restore user data
> * [x]   Metrics - send event metrics
> * [x]   Address-book - add a contact to the address book
> * [x]   Address-book - remove a contact from the address book
> * [x]   Address-book - update a contact in the address book
> * [x]   Gas fee - EIP-1559 gas
> * [x]   Gas fee - legacy gas
> * [x]   Sign - eth sign
> * [x]   Sign - personal sign
> * [x]   Sign - sign in with ethereum
> * [x]   Sign - sign typed with data
> * [ ]   Sign - sign typed data v3 with hardware wallet - Cannot complete these tasks my spare ledger bricked itself
> * [ ]   Sign - sign typed data v4 with hardware wallet - Cannot complete these tasks my spare ledger bricked itself
> * [x]   Permissions - connecting and disconnecting from a dapp
> * [x]   Swap - smart swap
> * [x]   Swap - swap eth
> * [ ]   Incoming transactions - receive native token
> * [x]   Settings - about MetaMask
> * [x]   Settings - general
> * [ ]   Settings - advanced - issue found, details below:
> Hex data box appears at enter address stage, is not found after clicking next as seen below:

image

During tests my ledger needed to update and while updating bricked itself. Unfortunately someone else will need to perform those two tests as I cannot get the device to work.

**Review by georgewrmarshall — COMMENTED** [review]
Confirmed and approved changes implemented by the [Design System Engineers](https://github.com/orgs/MetaMask/teams/design-system-engineers)
Checked: 
- [fix: removing opacity from deprecated popover overlay](https://github.com/MetaMask/metamask-extension/pull/23102) ✅ 
- [chore: upgrading design tokens package that includes dynamic theming](https://github.com/MetaMask/metamask-extension/pull/23101) ✅ 
- [chore: disabling static color hex stylelint rule for specific files](https://github.com/MetaMask/metamask-extension/pull/23098) ✅ 
- [chore: upgrading design tokens to v2](https://github.com/MetaMask/metamask-extension/pull/22897) ✅

**Comment by plasmacorral** [comment]
🟢 Approval from Accounts team

**Comment by danjm** [comment]
@SocketSecurity ignore-all

**Pull request merged**
