### PR TITLE
Part of #18714: Replacing deprecated constants in `Icon` folder

### PR DESCRIPTION
**Pull request by dhruvv173**
## Explanation
- This PR is a part of #18714 
Replaced deprecated design system and storybook constants in the `Icon` folder
`ui/components/component-library/icon`

### Before

https://github.com/MetaMask/metamask-extension/assets/79097544/762612ea-591c-41c8-a425-72e9ff684ddd

### After

https://github.com/MetaMask/metamask-extension/assets/79097544/70431dc5-1cde-4fd3-9ca0-e121166cd5f5

## Manual Testing Steps
`jest` tests
image

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [x] How reviewers can test my changes
- [x] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Comment by dhruvv173** [comment]
hi @georgewrmarshall , could you please review this PR when possible?
Thanks!

**Comment by dhruvv173** [comment]
> @dhruvv173 when you get a chance fix that conflict, otherwise this is looking good

hey @garrettbear, Considering that the changes were minor and focused on just replacing constants with enums, it's expected to have minimal impact on the overall coverage. If you have any concerns , please let me know.
Thanks!

**Review by georgewrmarshall — CHANGES_REQUESTED** [review]
Hey @dhruvv173, this is looking good I did a search for the deprecated consts inside of the icon folder and got a result on `FLEX_DIRECTION` that needs updating. You will also need to resolve the conflict as @garrettbear mentioned

Screenshot 2023-05-24 at 8 51 43 PM

**Comment by dhruvv173** [comment]
> Hey @dhruvv173, this is looking good I did a search for the deprecated consts inside of the icon folder and got a result on `FLEX_DIRECTION` that needs updating. You will also need to resolve the conflict as @garrettbear mentioned
> 
> Screenshot 2023-05-24 at 8 51 43 PM
> 

@garrettbear @georgewrmarshall 
I apologize for missing those constants. I will make the changes, resolve the conflict and resubmit.

**Comment by dhruvv173** [comment]
hey @garrettbear @georgewrmarshall 
Apologies for the mistakes, you guys have been very polite while pointing them out and suggesting changes. I have made the requested changes, could you guys please review it? 
Thanks!

**Review by georgewrmarshall — APPROVED** [review]
LGTM! Thanks for your contribution @dhruvv173!

**Review by garrettbear — APPROVED** [review]

**Comment by DONOVA28** [comment]
Thank you so much

**Pull request merged**
