### PR TITLE
Dark Mode: Set to default based on user preferred scheme

### PR DESCRIPTION
**Pull request by darkwing**
This code sets the default theme to dark if the user's system signals it prefers dark.

## Manual testing
1. Set your OS system preference to dark mode
2. Install MM
3. See dark onboarding
4. Set your OS system preference to light mode
5. Install MM
6. See light onboarding

### CODE REVIEW

**Comment by darkwing** [comment]
@kevinghim Does this work for you?

**Comment by kevinghim** [comment]
> @kevinghim Does this work for you?

@darkwing on Chrome, for the system settings to take affect, I have to close the extension and reopen it. In other words, if the extension is on the open state, the system preference isn't set dynamically. Is this suppose to be the case?

With the attached, with the extension set to `system` I changed the OS preference from light to dark, back to light - didn't see the change taking affect. When I closed and reopened the extension, it correctly reflected the light setting.

https://user-images.githubusercontent.com/6951929/191145617-6bc88a83-3e97-42fe-b536-d9fe3caff2c4.mov

**Comment by darkwing** [comment]
@kevinghim This PR only sets the theme to the Operating System preference at the time the user installs MetaMask.  After install, if the user wants the other theme, they will need to change it manually

**Comment by darkwing** [comment]
Ahhh, I see what you mean @kevinghim .  I was experimenting and it seems like there's a way to do this:

https://codepen.io/darkwing/pen/zYjgWza

I'll look more at this shortly.

**Review by digiwand — DISMISSED** [review]
would be neat to update the theme dynamically in a follow-up PR

**Review by digiwand — DISMISSED** [review]
😎 🤍🖤

**Comment by kevinghim** [comment]
LGTM, thanks @darkwing!

**Review by NiranjanaBinoy — DISMISSED** [review]
LGTM

**Review by brad-decker — DISMISSED** [review]

**Review by digiwand — APPROVED** [review]

**Review by jpuri — APPROVED** [review]

**Pull request merged**
