### PR TITLE
Initial multi-chain support (aka. optional chainid fix)

### PR DESCRIPTION
**Pull request by hackmod**
from https://github.com/MetaMask/metamask-extension/pull/4516

## Description
The customRpc feature support by MetaMask somewhat buggy.
Currently, metamask get the `chainId` using `net_version` rpc call, but `net_version` does not return the real `chainId`. for these cases, we need to know real `chainId` to support EIP155 replay protection correctly.

more over, In most case of ethereum forks and variants, `chainId != networkId`.

This PR has been incubated at https://github.com/MetaMask/metamask-extension/pull/4516 (about two months) and simplified. It is almost minimal fix to support the following.
- user configurable customRPCs with their chainIds to support EIP155 signing for `networkId != chainId` cases.
- Ethereum Classic support added (a pre-defined custom RPC, indeed)

above two features share their code, ETC support is implemented as a predefined customRPC.
that's why I do not separate this fix into two PRs.

~~~
$ git diff 4f02726fd9a |diffstat
 app/_locales/en/messages.json                                  |    9
 app/images/etc_logo.svg                                        |  468 ++++++++++
...
 50 files changed, 1146 insertions(+), 172 deletions(-)
~~~
*net changes are only `+678, -172` lines*

`InfuraProvider()` for ethereum, `_configureStandardProvider()` for customRPC are not much configurable.
this customRPC implementation is a prof-of-concept quick hack.
not much nice looking but ready to be merged, work nicely  and small enough for incremental development.

## Done
- [x] fixed custom Rpc form to support optional chainid.
  - [x] both old-ui and new-ui
- [x] ETC support added
  - basically, this is a predefined `rpcUrl` + `chainId`
- [x] show ticker properly (6/21)
- [x] block explorer urls (6/21)
- [x] support shapeshift exchange for deposit(6/22)
- [x] support testnet faucet (`buyUrl`) (6/23)
- ~~[x] fixed `frequentRpcList` bug.~~
- ~~[x] increase `frequentRpcList` length by 1~~
- [x] pass circleci (https://github.com/hackmod/metamask-extension/pull/1) (8/2)

## changelog
- 8/16 use ETC cooperative's api server for ETC.
- 8/16 update ETC logo.
- 8/21 simplified, remove some logs.

## References
- https://github.com/MetaMask/metamask-extension/issues/1820
- https://github.com/ethereum/go-ethereum/pull/15002#issuecomment-394560172
- https://medium.com/metamask/metamasks-vision-for-multiple-network-support-4ffbee9ec64d

## See also
- https://github.com/MetaMask/metamask-extension/issues/3453
- https://github.com/MetaMask/metamask-extension/issues/3604

## Screenshot

image

### user configured custom RPCs (upto 3)

image

example. upto 3 customRpc supported (previously, 2 supported)
image

(old-ui)
image

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
@hackmod I think Metamask will avoid adding bunch of providers and chains, instead we need optional chain fix only without ethereum classic support

**Comment by hackmod** [comment]
rebased, resolved conflict, changed ETC logo/rpcUrl

~~~
$ git diff 955ec2dca62 |diffstat
 app/_locales/en/messages.json                                  |    9
 app/images/etc_logo.svg                                        |   20 ++
...
 51 files changed, 695 insertions(+), 172 deletions(-)
~~~
now net changes are +675, -172 lines (svg file changes are not counted)

**Comment by hackmod** [comment]
@akx20000a
> I think Metamask will avoid adding bunch of providers and chains...

what bunch of providers and chains?? this PR only include ETC only, no other providers added at all.

**Comment by bdresser** [comment]
hey @hackmod, sorry for the slow response here.

@chrisfranko is right - we’re not currently interested in adding Classic to our network menu, as discussed here: https://medium.com/metamask/metamasks-vision-for-multiple-network-support-4ffbee9ec64d

We are open to adding support for the `chainId` parameter, though, which would allow users to easily opt into Classic support if they want to. Looks like @chrisfranko opened a separate PR with that feature set - I'll comment there about a couple lingering concerns from the team (specifically around changes to the block explorer and price API).

Long term, we are interested in ways of supporting different chains without having to impose the politics of a supported network list, but right now, we believe the addition of an extra chain named “Ethereum” would only serve to confuse our already very vulnerable userbase. I hope that makes sense!

**Comment by hackmod** [comment]
* `use MultiChain option` added. (FIXME)

image

**Comment by eosclassicteam** [comment]
@hackmod Can you please split your PR one for ETC support and one for optional chainid??

Your PR changes price api and lots of stuffs that Metamask will avoid merging this, please split your PR

**Comment by hackmod** [comment]
@chrisfranko @bdresser @eosclassicteam // OK. Ive made new PR to separate all other stuff except optional chainId.

**Comment by bdresser** [comment]
closing in favor of https://github.com/MetaMask/metamask-extension/pull/5134

**Pull request closed without merging**
