### PR TITLE
Make all addresses EIP-55 compliant

### PR DESCRIPTION
**Pull request by bakaoh**
Fix: #3514

- [x] Address from QR image
- [x] Copy contract address token dropdown menu
- [x] SenderToRecipient component
- [x] ToAutoComplete compoment

### CODE REVIEW

**Comment by bdresser** [comment]
@bakaoh on the confirmation screen, when I copy one of the addresses up top by clicking the sender or recipient, it's still lowercase
screen shot 2018-09-27 at 12 53 32 pm


on the "transaction detail view" (when I click on a submitted tx) the addresses are shown and copied lowercase
screen shot 2018-09-27 at 12 52 18 pm

might be a few more..

**Comment by bakaoh** [comment]
@bdresser -- i fixed it, i guess that all

**Comment by tmashuang** [comment]
https://github.com/MetaMask/metamask-extension/blob/develop/ui/app/components/send/to-autocomplete/to-autocomplete.js#L106

Found on more.

**Comment by bakaoh** [comment]
thanks @tmashuang, fixed it

**Comment by whymarrh** [comment]
@bakaoh mind rebasing this on the latest develop to pull in the e2e test fixes? Once this has a green build we can review+merge.

**Comment by bakaoh** [comment]
@whymarrh -- i rebased it but there're still e2e test failed

**Review by whymarrh — APPROVED** [review]
Thanks @bakaoh, I've fixed up the build with ea6b102

**Pull request merged**
