### PR TITLE
Fixes to the Linea Goerli implementation

### LINKED ISSUE #18289: [Bug]: Multiple networks selected at once
### Describe the bug

Both Arbitrum one and Linea is selected in the network picker

Networks

### Steps to reproduce

1. Log in to MM
2. Add Arbitrum one network
3. Switch to Arbitrum one
4. Open the network picker

### Error messages or log output

_No response_

### Version

10.27

### Build type

None

### Browser

Chrome, Firefox

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### LINKED ISSUE #18293: [Bug]: Manually adding Linea Goerli test network does not appear in network settings
### Describe the bug

When you manually add `Linea Goerli test network`, the network appears in the network drop-down but does not appear on the network page `/home.html#settings/networks`

Manual add network

### Steps to reproduce

1. log in to MM
2. Manually add the `Linea Goerli test network`
  - Network Name: `Linea Goerli Manually Added`
  - RPC Url: `https://consensys-zkevm-goerli-prealpha.infura.io/v3/{INFURA_KEY}`
  - Chain id: `59140`
  - Currency Symbol: `crETH`
  - Block explorer: `https://explorer.goerli.zkevm.consensys.net`  
4. Open the network page, Settings -> Network

### Error messages or log output

```
runtime-lavamoat.js:7087 TypeError: Cannot destructure property 'blockExplorerUrl' of 'undefined' as it is undefined.
  at Object.setRpcTarget (ui-4.js:1:1089131)
  at onClick (ui-4.js:1:1083305)
  at onClick (ui-4.js:1:1079119)
  at e.<computed> (sentry-install.js:1:677)
  at Object.m (ui-3.js:1:1548)
  at e.<computed> (sentry-install.js:1:677)
  at T (ui-3.js:1:1691)
  at e.<computed> (sentry-install.js:1:677)
  at ui-3.js:1:1837
  at x (ui-3.js:1:1923)
  at C (ui-3.js:1:2349)
  at k (ui-3.js:1:2184)
  at j (ui-3.js:1:2532)
  at _n (ui-3.js:1:29513)
  at se (ui-3.js:1:115013)
  at jn (ui-3.js:1:30128)
  at Mn (ui-3.js:1:31085)
  at Rn (ui-3.js:1:30373)
  at n.unstable_runWithPriority (ui-3.js:1:417870)
  at $o (ui-3.js:1:46150)
  at ue (ui-3.js:1:114790)
  at Pn (ui-3.js:1:29796)
(
```

### Version

10.27

### Build type

None

### Browser

Chrome, Firefox

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by danjm**
Fixes https://github.com/MetaMask/metamask-extension/issues/18293
Fixes https://github.com/MetaMask/metamask-extension/issues/18289

This PR corrects two issues with the Linea Goerli network, as it is displayed in the network dropdown. First, it ensures that a checkmark only appears next to it in the dropdown if it is in fact the currently selected network. Next, it ensures that if the network is added manually, it appears on the network settings tab along with the default linea network.

### CODE REVIEW

**Review by georgewrmarshall — APPROVED** [review]
LGTM!
- checked code to the best of my ability
- pulled branch and checked fix locally
Screenshot 2023-03-22 at 7 59 49 PM

**Review by georgewrmarshall — DISMISSED** [review]
Apologies! Checked the second issue and it seems it's not showing up under test networks on the settings page

Screenshot 2023-03-22 at 8 07 59 PM

**Comment by danjm** [comment]
@georgewrmarshall thanks for the review. I think the reason that the test network is not appearing in the list when you are testing locally is this line in `shared/constants/network.ts`: https://github.com/MetaMask/metamask-extension/blob/develop/shared/constants/network.ts#L690-L691

So to test the feature, you would have to either edit that date so that it is earlier than todays date, or change you computers date so that it is later than March 28

**Review by pedronfigueiredo — APPROVED** [review]

**Review by VGau — APPROVED** [review]
LGTM 😄

**Review by PeterYinusa — APPROVED** [review]
LGTM

**Comment by georgewrmarshall** [comment]
@danjm ahh that makes sens. My bad! Thanks for the clarification. I even saw the date logic in my review 🤦‍♂️

**Pull request merged**
