### PR TITLE
Remove unused ShapeShift components

### PR DESCRIPTION
**Pull request by Gudahtt**
The `shift-list-item` component for displaying ShapeShift transactions has been removed, along with three other components that were used solely by that component (`copyButton`, `eth-balance`, and `fiat-value`).

This component hasn't been used in some time, as ShapeShift transactions no longer exist to display. The controller that ShapeShift transactions originated from was removed in #8118, and it became impossible to create new ShapeShift transactions from within MetaMask in #6746

### CODE REVIEW

**Comment by whymarrh** [comment]
If a user has existing ShapeShift state, what happens to that? Do we try and render it?

**Comment by Gudahtt** [comment]
What ShapeShift state could they have? The controller was deleted. That's where that state was.

**Comment by whymarrh** [comment]
Yes, and because the controller isn't there we don't combine it into the background state 👍

**Comment by whymarrh** [comment]
This makes sense now, all good

**Review by whymarrh — APPROVED** [review]
LGTM!

**Pull request merged**
