### PR TITLE
SRP copy-paste language

### PR DESCRIPTION
**Pull request by mapachurro**
As per a conversation on Aug. 3, change the language in these fields to discourage users from copy-pasting SRPs.

Fixes: #

Explanation:  
The field where the user enters their SRP when restoring a wallet says "Paste your Secret Recovery Phrase from the clipboard"; this is not in line with other messaging MM produces regarding how users should store and use their SRPs, and encourages poor SRP storage practices (cloud-based notes, for example).

Manual testing steps:  
  - 
  - 
  -

### CODE REVIEW

**Review by brad-decker — DISMISSED** [review]

**Comment by brad-decker** [comment]
@mapachurro you'll need to update the e2e tests that are keyed to look for that 'Paste' word.
>      TimeoutError: Waiting for element to be located By(css selector, input[placeholder="Paste Secret Recovery Phrase from clipboard"])

**Comment by mapachurro** [comment]
Hey, thanks for reminding me. I will try to drive into this tonight.

**Comment by mapachurro** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by darkwing — DISMISSED** [review]

**Review by mcmire — DISMISSED** [review]
Sorry for the late review. This looks good to me. EDIT: Oh, looks like there are merge conflicts now. Also for some reason the CLA bot didn't work. I'll try to fix the conflicts. Maybe it will get the bot to re-run the CLA check.

**Review by mcmire — APPROVED** [review]

**Review by adonesky1 — APPROVED** [review]

**Comment by Gudahtt** [comment]
Should we also delete the translations so that they can be updated to reflect this change? Or is this something that we can easily trigger on Crowdin manually? cc @adonesky1 @rickycodes

**Comment by rickycodes** [comment]
I think this change as is should be good? if we did this right we should just see a new translation PR with the changes to the corresponding json files open when it's ready.

@adonesky1 can correct me if i am wrong.

**Pull request merged**
