### PR TITLE
Fix incorrect account name in Account Details and Receive List

### PR DESCRIPTION
**Pull request by montelaidev**
## **Description**

Fixes the incorrect name being displayed in account details and Receive list. 

## **Related issues**

Fixes:https://github.com/MetaMask/metamask-extension/issues/22835

## **Manual testing steps**

1. Create a snap account
2. Go to MM extension
3. Click on the snap account
4. Click on account details 
5. See that the name matches

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [x] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by gantunesr — DISMISSED** [review]
lgtm! I didn't test the PR

**Review by danroc — COMMENTED** [review]
LGTM, but we should consider adding a test, WDYT?

**Review by danroc — DISMISSED** [review]
LGTM, tested on `298e45b`.

**Review by ccharly — APPROVED** [review]
LGTM, manually tested on https://github.com/MetaMask/metamask-extension/commit/779e0099e5eac21bfc556340b9220243ac2913d0.

**Review by danroc — APPROVED** [review]

**Pull request merged**
