### PR TITLE
Updating minimum GWei price to 0.2

### PR DESCRIPTION
**Pull request by tloriato**
I suggest we move the minimum GWei price to 0.2.

Edit: 

❌ Error in code

### CODE REVIEW

**Comment by tmashuang** [comment]
Ethgasstation recommends 0.1 Gwei as the SafeLow, in favor for this PR.

**Comment by kumavis** [comment]
BN doesnt support decimals! shout it from the mountain tops!

**Review by kumavis — CHANGES_REQUESTED** [review]
needs to be refactored to support <1gwei

we should specify gasPrice in wei

**Comment by tloriato** [comment]
Nice catch @kumavis 

Sorry to failed to noticed it, I'll try to work on it

**Comment by Zanibas** [comment]
This has been resolved by #2476. Working around BN.js is fuuuuun /s.

**Pull request closed without merging**
