### PR TITLE
Show checksum addresses on UI

### LINKED ISSUE #3988: [BETA UI] Copied addresses are all lowercase (not checksumed)
Address is not checksumed before showing it for being copied on the new UI.

image

### Actual behaviour:

Copied address:
```0x8a838b1722750ba185f189092833791adb98955f```

### Expected behaviour:

Copied address: 
```0x8a838B1722750ba185F189092833791Adb98955f```

### PR DESCRIPTION
**Pull request by bitpshr**
This PR updates the application to show checksum addresses throughout the UI. There wasn't an easy way to centrally modify all addresses since they can come from a number of different places. Rather than modify the background scripts (which heavily rely on lowercase addresses), the easiest solution was to explicitly checksum addresses on the component level where we show them.

Resolves #3988

### CODE REVIEW

**Review by danfinlay — APPROVED** [review]
Looks good, thanks!

**Comment by danfinlay** [comment]
Ah, tests are failing because some of the new code isn't as tolerant of `undefined` addresses!

**Comment by bitpshr** [comment]
@danfinlay Ah, I (poorly) assumed that `toChecksumAddress` from `ethereumjs-utils` would safely handle undefined addresses. I created an intermediary utility function for the UI that does handle undefined addresses so every usage across our app doesn't have to do a ternary check to prevent a blow up.

This should be ready for another review.

**Review by danfinlay — APPROVED** [review]
Looks good, nice solution, thanks!

**Pull request merged**
