### PR TITLE
Part of 17670: Replaced Typography with Text component in welcome.js and edit-gas-display.component.js

### PR DESCRIPTION
**Pull request by spiritanand**
## Explanation
Replace Typography with Text in `welcome.js` and `edit-gas-display.component.js`

Part of: #17670
### Before
`edit-gas-display.component.js`
before edit

`welcome.js`
before Welcome 1
before Welcome 2

### After
`edit-gas-display.component.js`
after edit

`welcome.js`
after welcome 1
after welcome 2

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be required.

### CODE REVIEW

**Comment by spiritanand** [comment]
@georgewrmarshall I cannot run `yarn storybook` as it throws the following error. How can I fix that?

image

and 

image


Because of this, I have not been able to verify my changes nor add the screenshots.

**Comment by georgewrmarshall** [comment]
Hey @spiritanand, ensure you are using node v16. Clear your node_modules and try running the following on `develop` branch
```
yarn && yarn storybook
```

See of that works, then see if it works on the branch with your changes

**Comment by spiritanand** [comment]
@georgewrmarshall I am using node v16.
image

I tried deleting the `node_modules` and reinstalling, but did not work. Looking for fixes online.

Current error :-
image

**Comment by spiritanand** [comment]
@georgewrmarshall everything is working as it is supposed to now. Please let me know if there are any changes required.

**Review by georgewrmarshall — APPROVED** [review]
LGTM! 🚀  Thanks for your contribution!
- pulled branch and checked storybook ✅

**Review by NidhiKJha — APPROVED** [review]

**Pull request merged**
