### PR TITLE
Update messages.json

### PR DESCRIPTION
**Pull request by alek-v**
Fixes: #

Explanation:  

Manual testing steps:  
  - 
  - 
  -

### CODE REVIEW

**Comment by alek-v** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mcmire** [comment]
Hey, sorry it's taken us so long to get back to you. We have a lot of new translations coming in via #13206, so I'll wait until that's merged first.

**Comment by brad-decker** [comment]
@alek-v if you are interested in seeing this merged could you please rebase the PR and validate that your changes are still required (we have had an automated translation system now for a bit so some of the items likely changed) Thank you!

**Comment by brad-decker** [comment]
Hey there @alek-v I am closing this PR due to it becoming stale. This doesn't mean we do not want this contribution, only that we are trying to clean our PR queue to keep our reviewers focused on the most up to date and mergeable prs. If you make the requested changes and rebase the PR you can reopen it for review. Thank you!

**Pull request closed without merging**
