### PR TITLE
fix cancelTransaction not receiving a callback

### PR DESCRIPTION
**Pull request by frankiebee**
and enforce nodeify receives a callback

### CODE REVIEW

**Comment by kumavis** [comment]
dont throw an error in a callback-based async fn

**Comment by kumavis** [comment]
hmm but i guess we have no choice

**Comment by frankiebee** [comment]
I could console.error?

**Comment by kumavis** [comment]
nah i think its alright as is actually

**Comment by Zanibas** [comment]
Apparently this code borks our transition into accounts-detail?

**Comment by frankiebee** [comment]
@Zanibas yeah fixing now

**Comment by frankiebee** [comment]
but also no.... the test is just written poorly?

**Review by kumavis — APPROVED** [review]

**Pull request merged**
