### PR TITLE
Update Keystone links

### PR DESCRIPTION
**Pull request by soralit**
## Explanation
Hello there 😄 
Just raise this PR to update `Buy Now` to `Learn More` and related link for Keystone. 

### Before
image

### After
image

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [x] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Comment by CharlesBlaqk** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Review by brad-decker — DISMISSED** [review]

**Comment by gantunesr** [comment]
@soralit can you take a look at the testing for the code cov?

**Comment by AlexJupiter** [comment]
@montelaidev if you have a moment is it possible to move this along?

**Comment by montelaidev** [comment]
Thanks for the PR @soralit, it looks like the check was failing because of insufficient code coverage, i've created a new test and merged the changes in another PR.

**Pull request closed without merging**
