### PR TITLE
Bump eth-ledger-bridge-keyring

### PR DESCRIPTION
**Pull request by brunobar79**
The new version fixes the error format of the keyring (Now it returns an Error object, as expected by the TX controller) (see https://github.com/MetaMask/eth-ledger-bridge-keyring/pull/8)

Partially addresses #5641

### CODE REVIEW

**Review by whymarrh — DISMISSED** [review]

**Comment by whymarrh** [comment]
Whoops, just noticed the conflict. I can re-approve after that's resolved.

**Comment by brunobar79** [comment]
> Whoops, just noticed the conflict. I can re-approve after that's resolved.

Good catch @whymarrh . Just fixed it

**Comment by whymarrh** [comment]
@brunobar79 I think the lockfile might have been resolved incorrectly. I'm seeing 7,582 additions and 7,604 deletions which seems like a lot, it's just the one package that's been bumped here?

**Review by whymarrh — APPROVED** [review]
👍

**Pull request merged**
