### PR TITLE
chore(deps): Bump ens-controller to ^10.0.1

### PR DESCRIPTION
**Pull request by mcmire**
## **Description**

The primary purpose for upgrading this package is to ensure that we are using a version which relies on `@metamask/base-controller` v4, which protects state from being mutated accidentally and includes more type safety for messengers, among other improvements.

However, this upgrade also includes theoretical support for Sepolia and Holesky ENS registries. I have not gotten ENS lookups to work on anything but Mainnet (perhaps we are explicitly targeting Mainnet somehow), but support is there should we need it.

See changelog:
https://github.com/MetaMask/core/blob/%40metamask/ens-controller%4010.0.1/packages/ens-controller/CHANGELOG.md

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/24207?quickstart=1)

## **Related issues**

Progresses #24140

## **Manual testing steps**

There should be no functional changes in this PR, but we may want to double-check that ENS lookups still work (e.g. add an ENS name to address book or try to send a transaction to an ENS name).

## **Screenshots/Recordings**

(None)

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by mcmire** [comment]
@metamaskbot update-policies

**Review by legobeat — DISMISSED** [review]
LGTM!

**Review by mikesposito — DISMISSED** [review]
Looks good!

**Comment by mcmire** [comment]
@metamaskbot update-policies

**Comment by mcmire** [comment]
@metamaskbot update-policies

**Review by legobeat — APPROVED** [review]

**Review by mikesposito — APPROVED** [review]

**Review by legobeat — APPROVED** [review]

**Review by legobeat — APPROVED** [review]

**Pull request merged**
