### PR TITLE
chore: Bump `@metamask/ens-controller` to v12

### PR DESCRIPTION
**Pull request by Gudahtt**
## **Description**

This resolves a peer dependency warning; v10.0.1 of the `@metamask/ens-controller` was requesting an older version of the `@metamask/network-controller` package. The versions are aligned with this update.

The only breaking changes were to this peer dependency, and to the minimum supported Node.js version.

See here for the full changelog: https://github.com/MetaMask/core/blob/%40metamask/ens-controller%4012.0.0/packages/ens-controller/CHANGELOG.md

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/26127?quickstart=1)

## **Related issues**

This helps to unblock #9372

## **Manual testing steps**

N/A

## **Screenshots/Recordings**

N/A

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by Gudahtt** [comment]
@metamaskbot update-policies

**Review by cryptodev-2s — APPROVED** [review]
LGTM!

**Review by mcmire — APPROVED** [review]
Makes sense!

**Comment by Gudahtt** [comment]
@metamaskbot update-policies

**Pull request merged**
