### PR TITLE
Part of #17670 Replace Typography with Text component for 4 files.

### PR DESCRIPTION
**Pull request by PrgrmrHarshShukla**
## Explanation
In this PR I have worked on the issue #17670 Replace Typography with Text component  and  issue #18714  Replace deprecated design system typography consts with enums for the files: 

1. ui/components/app/modals/contract-details-modal/contract-details-modal.js
2. ui/components/app/modals/customize-nonce/customize-nonce.component.js
3. ui/components/app/network-account-balance-header/network-account-balance-header.js
4. ui/components/ui/callout/callout.stories.js

### Before
Screenshot (41)

Screenshot (43)

Screenshot (44)

Screenshot (42)

### After
Screenshot (47)

Screenshot (49)

Screenshot (50)

Screenshot (48)

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Review by DDDDDanica — DISMISSED** [review]

**Comment by DDDDDanica** [comment]
> > Hey @PrgrmrHarshShukla if you can update the snapshot we can have a green pipeline to merge :)
> 
> I am finding it somewhat difficult. Please help.🙏🏼

@PrgrmrHarshShukla if you can check the jest document, https://jestjs.io/docs/snapshot-testing#updating-snapshots, it is actually pretty straightforward. Simply run all the test, or a single test using `yarn jest ui/components/app/signature-request-original/signature-request-original.test.js`, you would encounter the same report in CI: https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/44044/workflows/2099ec9b-8a9e-420f-9a35-1b3e26650568/jobs/1240000
Screenshot 2023-04-26 at 13 28 54


After which you can simply using `-u` to update and make sure the changed DOM is expected because you have changed some elements.

🙏

**Review by georgewrmarshall — COMMENTED** [review]
Looks like snapshots may still need to be updated `yarn jest --updateSnapshot` and could you add some before and after screenshots of the UI changes in the PR description please

**Review by georgewrmarshall — COMMENTED** [review]
Hey @PrgrmrHarshShukla, could you please add screenshots of all the UI changes otherwise I may have to close this PR as it does not meet the acceptance criteria thanks!

**Comment by PrgrmrHarshShukla** [comment]
Hey @georgewrmarshall 

I will add the screenshots now.
I was finding them.

**Review by georgewrmarshall — APPROVED** [review]
LGTM!

**Review by DDDDDanica — APPROVED** [review]

**Pull request merged**
