### PR TITLE
Add imToken Wallet support with EIP-4527

### PR DESCRIPTION
**Pull request by makoshan**
## **Description**
Hello, this is the imToken team. 

imToken is a mobile crypto wallet founded in 2016. It has been operating safely and steadily for 7 years. Recently, we successfully supported ERC-4527, and imToken can function as a QR code-based signer now. This integration seamlessly aligns with Metamask's bidirectional QR account feature, enhancing the ability to track accounts whose private keys are stored on external devices.

Therefore, we propose that Metamask expand its supported QR code-based wallet connection methods and include imToken. This will not only enhance Metamask's functionality and user coverage, but also provide users with a wider, more secure and efficient choice of wallets.

We have successfully completed the integration of ERC-4527 and look forward to discussing in depth the possibility of adding imToken into Metamask's QR code-based wallet connection methods. Thank you very much for your attention and feedback on this matter.

## **Related issues**
no
## **Manual testing steps**
1. Please check if the added links to the imToken official website and tutorials are correct.
2. The process is consistent with the current QR-Based Keystone and Airgap methods. Please refer to the test video provided below for reference.

### Video
[Dropbox link](https://www.dropbox.com/scl/fi/kbfcthouwgqaaueepsslc/imToken_Connect_Metamask_.mp4?rlkey=vz6js9g81oevg2y77vkizfefq&dl=0)
### User Flow
metamask

### **Before**
image

### **After**
image

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [ x] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by makoshan** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by makoshan** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by allen-hsu** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by AlexJupiter** [comment]
Thank you for this, we will prioritise this internally and try and get this merged and released soon.

**Comment by owencraston** [comment]
@makoshan can you provide manual testing steps?

**Comment by makoshan** [comment]
@owencraston  I recorded a video demonstrating the testing process for pairing and transfer using imToken and Metamask, the process is now perfectly compatible with Metamask.

Video:

https://github.com/MetaMask/metamask-extension/assets/7024451/738edfe7-67cc-438e-8b4b-e988f068d1f1

**Comment by makoshan** [comment]
@AlexJupiter @owencraston Is the test screen recording in line with what you anticipated? Please let me know if there's anything else I should add to aid in advancing the merge process 😁

**Review by Akaryatrh — APPROVED** [review]

**Review by gantunesr — APPROVED** [review]

**Review by danroc — APPROVED** [review]
LGTM, tested with `personal_sign`.

However, the process for backing up the SRP after onboarding was a bit confusing. For anyone else wanting to test it, here's the pathway: **Hamburger menu** > **Manage** > **Manage...** (next to the wallet name, above the list of blockchains) > **Backup wallet**.

**Comment by makoshan** [comment]
🎉🎉 🎉 Changes have been approved, looking forward to the merge

**Pull request merged**
