### PR TITLE
Version v12.1.0 

### PR DESCRIPTION
**Pull request by chloeYue**
RC V12.1.0

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/25586?quickstart=1)

### CODE REVIEW

**Comment by chloeYue** [comment]
Bug report for v12.1.0: https://github.com/MetaMask/MetaMask-planning/issues/2729

**Comment by benjisclowder** [comment]
Hi! We need teams' approval on July 15 for V12.1.0. Please note that if your team still has ongoing work on V12.0.0, you should prioritize that. In case any more issues arise for V12.0.0, we will push back sign-offs on V12.1.0.  Let's do this! :rocketship:

**Instructions for Team Review**

**Review Changes**: Refer to the [Release Tracker for v12.1.0](https://docs.google.com/spreadsheets/d/1tsoodlAlyvEUpkkcNcbZ4PM9HuC9cEM80RZeoVv5OCQ/edit?gid=2099993340#gid=2099993340) to see all changes relevant to your team.

**Log Bugs**: If you find any issues, log them in the release tracker and attach them to the [bug report](https://github.com/MetaMask/MetaMask-planning/issues/2729).

**Approval**: After reviewing, indicate your team's approval by:

- [ ] Marking the checkbox next to your team's name in this comment.
- [ ] Optionally, leave a comment for additional information.

Your thorough review ensures a smooth and successful release. If you have any questions please reach out to extension platform team or in the [#metamask-qa](https://consensys.slack.com/archives/C01U65ZUS2E) slack channel. Thank you for your collaboration!

- [ ] Accounts: @gantunesr - There are 19 Accounts changes in v12.1.0
- [ ]  Assets: @sahar-fehri / @alfeng6 - There are 18 Assets changes in v12.1.0
- [ ]  Bridging: @micaelae / @BZahory - There are 7 Bridging changes in v12.1.0
- [ ]  Confirmations: @sleepytanya / @cryptotavares - There are 32 Confirmations changes in v12.1.0.
- [ ]  Design/Systems: @georgewrmarshall - There are 18 Design/Systems change in v12.1.0.
- [ ]  Devex: @tmashuang / @vandan - There are 4 Devex changes in 12.1.0.
- [ ]  MMI: @zone-live / @shane-t - There are 6 MMI changes in v12.1.0.
- [ ]  Notifications: @Prithpal-Sooriya / @matteoscurati - There are 11 Notifications changes in v12.1.0
- [ ]  Ramps: @georgeweiler - There is 1 Ramps change in v12.1.0.
- [ ]  Snaps: @bowensanders / @FrederikBolding / @Montoya - There are 5 Snaps changes in v12.1.0.
- [ ]  Swaps: @davibroc / @dan437 - There are 4 Swaps change in v12.1.0.
- [ ]  Wallet API: @adonesky1 - There are 5 DappAPI changes in v12.1.0.
- [ ]  Wallet Framework: @Gudahtt - There are 10 Wallet Framework changes in v12.1.0.
- [ ]  Wallet UX: @darkwing / @NidhiKJha - There are 8 Wallet UX changes in v12.1.0.

**Comment by benjisclowder** [comment]
[Manual test scenarios:](https://github.com/MetaMask/metamask-extension/tree/develop/test/manual-scenarios)

**Chrome**

- [ ] Onboarding - create a wallet
- [ ]  Onboarding - import a wallet
- [ ]  Keyring - connect hardware wallet
- [ ]  Keyring - reset a wallet
- [ ]  Transactions - send native token origin MM
- [ ]  Transactions - send native token origin dapp
- [ ]  Transactions - send ERC20 token origin MM
- [ ]  Transactions - send ERC20 token origin dapp
- [ ]  Transactions - send ERC721 token origin MM
- [ ]  Transactions - send ERC721 token origin dapp
- [ ]  Transactions - speed up transaction
- [ ]  Transactions - cancel transaction
- [ ]  Transactions - deploy failing transaction
- [ ]  Transactions - deposit and withdraw
- [ ]  Transactions - navigate multiple transactions
- [ ]  Transactions - send transactions with custom nonce
- [ ]  Transactions - cancel transaction using same nonce
- [ ]  Tokens - import ERC20 token origin MM
- [ ]  Tokens - import ERC20 token origin dapp
- [ ]  Tokens - import ERC721 token origin MM
- [ ]  Tokens - import ERC721 token origin dapp
- [ ]  Tokens - import ERC1155 token origin MM
- [ ]  Tokens - import ERC1155 token origin dapp
- [ ]  Tokens - approve ERC1155 token
- [ ]  Tokens - approve ERC20 token
- [ ]  Tokens - approve ERC721 token
- [ ]  Tokens - autodetect tokens
- [ ]  Tokens - autodetect NFTs
- [ ]  Tokens - approve erc20 custom amount
- [ ]  ENS - name resolution
- [ ]  Phishing - warning page
- [ ]  Network - add custom network manually
- [ ]  Network - add custom network from the list of popular networks
- [ ]  Network - add custom network from dApp
- [ ]  Network - update networks
- [ ]  Network - switching networks
- [ ]  Network - delete networks from the dropdown list
- [ ]  Network - delete networks in Settings
- [ ]  Backup - backup user data
- [ ]  Backup - restore user data
- [ ]  Metrics - send event metrics
- [ ]  Address-book - add a contact to the address book
- [ ]  Address-book - remove a contact from the address book
- [ ]  Address-book - update a contact in the address book
- [ ]  Gas fee - EIP-1559 gas
- [ ]  Gas fee - legacy gas
- [ ]  Sign - eth sign
- [ ]  Sign - personal sign
- [ ]  Sign - sign in with ethereum
- [ ]  Sign - sign typed with data
- [ ]  Sign - sign typed data v3 with hardware wallet
- [ ]  Sign - sign typed data v4 with hardware wallet
- [ ]  Sign - personal sign with hardware wallet
- [ ]  Sign - eth sign with hardware wallet
- [ ]  Permissions - connecting and disconnecting from a dapp
- [ ]  Swap - smart swap
- [ ]  Swap - swap eth
- [ ]  Incoming transactions - receive native token
- [ ]  Settings - about MetaMask
- [ ]  Settings - general - change language
- [ ]  Settings - advanced - check custom nonce toggle
- [ ]  Settings - advanced - show hex data
- [ ]  Contract - deploy contract, mint and import NFT with hardware wallet
- [ ]  Contract - hardware wallet qr based connect
- [ ]  Contract - send token with hardware wallet

**Firefox**

- [ ] Onboarding - create a wallet
- [ ]  Onboarding - import a wallet
- [ ]  Keyring - connect hardware wallet
- [ ]  Keyring - reset a wallet
- [ ]  Transactions - send native token origin MM
- [ ]  Transactions - send native token origin dapp
- [ ]  Transactions - send ERC20 token origin MM
- [ ]  Transactions - send ERC20 token origin dapp
- [ ]  Transactions - send ERC721 token origin MM
- [ ]  Transactions - send ERC721 token origin dapp
- [ ]  Transactions - speed up transaction
- [ ]  Transactions - cancel transaction
- [ ]  Transactions - deploy failing transaction
- [ ]  Transactions - deposit and withdraw
- [ ]  Transactions - navigate multiple transactions
- [ ]  Transactions - send transactions with custom nonce
- [ ]  Transactions - cancel transaction using same nonce
- [ ]  Tokens - import ERC20 token origin MM
- [ ]  Tokens - import ERC20 token origin dapp
- [ ]  Tokens - import ERC721 token origin MM
- [ ]  Tokens - import ERC721 token origin dapp
- [ ]  Tokens - import ERC1155 token origin MM
- [ ]  Tokens - import ERC1155 token origin dapp
- [ ]  Tokens - approve ERC1155 token
- [ ]  Tokens - approve ERC20 token
- [ ]  Tokens - approve ERC721 token
- [ ]  Tokens - autodetect tokens
- [ ]  Tokens - autodetect NFTs
- [ ]  Tokens - approve erc20 custom amount
- [ ]  ENS - name resolution
- [ ]  Phishing - warning page
- [ ]  Network - add custom network manually
- [ ]  Network - add custom network from the list of popular networks
- [ ]  Network - add custom network from dApp
- [ ]  Network - update networks
- [ ]  Network - switching networks
- [ ]  Network - delete networks from the dropdown list
- [ ]  Network - delete networks in Settings
- [ ]  Backup - backup user data
- [ ]  Backup - restore user data
- [ ]  Metrics - send event metrics
- [ ]  Address-book - add a contact to the address book
- [ ]  Address-book - remove a contact from the address book
- [ ]  Address-book - update a contact in the address book
- [ ]  Gas fee - EIP-1559 gas
- [ ]  Gas fee - legacy gas
- [ ]  Sign - eth sign
- [ ]  Sign - personal sign
- [ ]  Sign - sign in with ethereum
- [ ]  Sign - sign typed with data
- [ ]  Sign - sign typed data v3 with hardware wallet
- [ ]  Sign - sign typed data v4 with hardware wallet
- [ ]  Sign - personal sign with hardware wallet
- [ ]  Sign - eth sign with hardware wallet
- [ ]  Permissions - connecting and disconnecting from a dapp
- [ ]  Swap - smart swap
- [ ]  Swap - swap eth
- [ ]  Incoming transactions - receive native token
- [ ]  Settings - about MetaMask
- [ ]  Settings - general - change language
- [ ]  Settings - advanced - check custom nonce toggle
- [ ]  Settings - advanced - show hex data
- [ ]  Contract - deploy contract, mint and import NFT with hardware wallet
- [ ]  Contract - hardware wallet qr based connect
- [ ]  Contract - send token with hardware wallet

**Comment by gantunesr** [comment]
Approved for @MetaMask/account-management 

Checked the following PRs were included and working in release PR

- [x] https://github.com/MetaMask/metamask-extension/pull/25200
- [x] https://github.com/MetaMask/metamask-extension/pull/25437
- [x] https://github.com/MetaMask/metamask-extension/pull/25291
- [x] https://github.com/MetaMask/metamask-extension/pull/25423
- [x] https://github.com/MetaMask/metamask-extension/pull/25491
- [x] https://github.com/MetaMask/metamask-extension/pull/25257
- [x] https://github.com/MetaMask/metamask-extension/pull/25003
- [x] https://github.com/MetaMask/metamask-extension/pull/25326
- [x] https://github.com/MetaMask/metamask-extension/pull/25314
- [x] https://github.com/MetaMask/metamask-extension/pull/25313
- [x] https://github.com/MetaMask/metamask-extension/pull/25290
- [x] https://github.com/MetaMask/metamask-extension/pull/25038
- [x] https://github.com/MetaMask/metamask-extension/pull/25287
- [x] https://github.com/MetaMask/metamask-extension/pull/25241
- [x] https://github.com/MetaMask/metamask-extension/pull/25143
- [x] https://github.com/MetaMask/metamask-extension/pull/25205
- [x] https://github.com/MetaMask/metamask-extension/pull/25201
- [x] https://github.com/MetaMask/metamask-extension/pull/25096

**Comment by anaamolnar** [comment]
Chrome

- [ ] Onboarding - create a wallet
- [ ]  Onboarding - import a wallet
- [ ]  Keyring - connect hardware wallet
- [ ]  Keyring - reset a wallet - https://github.com/MetaMask/metamask-extension/issues/25696
- [ ]  Transactions - send native token origin MM 
- [ ]  Transactions - send native token origin dapp
- [ ]  Transactions - send ERC20 token origin MM
- [ ]  Transactions - send ERC20 token origin dapp
- [ ]  Transactions - send ERC721 token origin MM
- [ ]  Transactions - send ERC721 token origin dapp
- [ ]  Transactions - speed up transaction
- [ ]  Transactions - cancel transaction
- [ ]  Transactions - deploy failing transaction
- [ ]  Transactions - deposit and withdraw
- [ ]  Transactions - navigate multiple transactions
- [ ]  Transactions - send transactions with custom nonce
- [ ]  Transactions - cancel transaction using same nonce
- [ ]  Tokens - import ERC20 token origin MM
- [ ]  Tokens - import ERC20 token origin dapp
- [ ]  Tokens - import ERC721 token origin MM
- [ ]  Tokens - import ERC721 token origin dapp
- [ ]  Tokens - import ERC1155 token origin MM
- [ ]  Tokens - import ERC1155 token origin dapp
- [ ]  Tokens - approve ERC1155 token
- [ ]  Tokens - approve ERC20 token
- [ ]  Tokens - approve ERC721 token
- [ ]  Tokens - autodetect tokens
- [ ]  Tokens - autodetect NFTs
- [ ]  Tokens - approve erc20 custom amount
- [ ]  ENS - name resolution
- [ ]  Phishing - warning page
- [ ]  Network - add custom network manually
- [ ]  Network - add custom network from the list of popular networks
- [ ]  Network - add custom network from dApp
- [ ]  Network - update networks
- [ ]  Network - switching networks
- [ ]  Network - delete networks from the dropdown list
- [ ]  Network - delete networks in Settings
- [ ]  Backup - backup user data
- [ ]  Backup - restore user data
- [ ]  Metrics - send event metrics
- [ ]  Address-book - add a contact to the address book
- [ ]  Address-book - remove a contact from the address book
- [ ]  Address-book - update a contact in the address book
- [ ]  Gas fee - EIP-1559 gas
- [ ]  Gas fee - legacy gas
- [ ]  Sign - eth sign
- [ ]  Sign - personal sign
- [ ]  Sign - sign in with ethereum
- [ ]  Sign - sign typed with data
- [ ]  Sign - sign typed data v3 with hardware wallet
- [ ]  Sign - sign typed data v4 with hardware wallet
- [ ]  Sign - personal sign with hardware wallet
- [ ]  Sign - eth sign with hardware wallet
- [ ]  Permissions - connecting and disconnecting from a dapp
- [ ]  Swap - smart swap
- [ ]  Swap - swap eth
- [ ]  Incoming transactions - receive native token
- [ ]  Settings - about MetaMask
- [ ]  Settings - general - change language
- [ ]  Settings - advanced - check custom nonce toggle
- [ ]  Settings - advanced - show hex data
- [ ]  Contract - deploy contract, mint and import NFT with hardware wallet
- [ ]  Contract - hardware wallet qr based connect
- [ ]  Contract - send token with hardware wallet

**Comment by katkopel** [comment]
Firefox v.12.1.0 (I still cannot edit the above checklist)


- [ ] Onboarding - create a wallet
- [ ]  Onboarding - import a wallet
- [ ]  Keyring - connect hardware wallet
- [ ]  Keyring - reset a wallet
- [ ]  Transactions - send native token origin MM
- [ ]  Transactions - send native token origin dapp
- [ ]  Transactions - send ERC20 token origin MM
- [ ]  Transactions - send ERC20 token origin dapp
- [ ]  Transactions - send ERC721 token origin MM
- [ ]  Transactions - send ERC721 token origin dapp
- [ ]  Transactions - speed up transaction
- [ ]  Transactions - cancel transaction
- [ ]  Transactions - deploy failing transaction
- [ ]  Transactions - deposit and withdraw - extension was unresponsive/test failed
- [ ]  Transactions - navigate multiple transactions
- [ ]  Transactions - send transactions with custom nonce
- [ ]  Transactions - cancel transaction using same nonce
- [ ]  Tokens - import ERC20 token origin MM
- [ ]  Tokens - import ERC20 token origin dapp
- [ ]  Tokens - import ERC721 token origin MM
- [ ]  Tokens - import ERC721 token origin dapp
- [ ]  Tokens - import ERC1155 token origin MM - could not import token manually after minting
- [ ]  Tokens - import ERC1155 token origin dapp- could not import token via dapp after minting
- [ ]  Tokens - approve ERC1155 token
- [ ]  Tokens - approve ERC20 token
- [ ]  Tokens - approve ERC721 token
- [ ]  Tokens - autodetect tokens
- [ ]  Tokens - autodetect NFTs
- [ ]  Tokens - approve erc20 custom amount
- [ ]  ENS - name resolution
- [ ]  Phishing - warning page
- [ ]  Network - add custom network manually
- [ ]  Network - add custom network from the list of popular networks
- [ ]  Network - add custom network from dApp
- [ ]  Network - update networks
- [ ]  Network - switching networks
- [ ]  Network - delete networks from the dropdown list
- [ ]  Network - delete networks in Settings
- [ ]  Backup - backup user data
- [ ]  Backup - restore user data
- [ ]  Metrics - send event metrics
- [ ]  Address-book - add a contact to the address book - https://github.com/MetaMask/metamask-extension/issues/25918 
- [ ]  Address-book - remove a contact from the address book
- [ ]  Address-book - update a contact in the address book
- [ ]  Gas fee - EIP-1559 gas
- [ ]  Gas fee - legacy gas
- [ ]  Sign - eth sign
- [ ]  Sign - personal sign
- [ ]  Sign - sign in with ethereum
- [ ]  Sign - sign typed with data
- [ ]  Sign - sign typed data v3 with hardware wallet
- [ ]  Si
- [ ] gn - sign typed data v4 with hardware wallet
- [ ]  Sign - personal sign with hardware wallet
- [ ]  Sign - eth sign with hardware wallet
- [ ]  Permissions - connecting and disconnecting from a dapp
- [ ]  Swap - smart swap
- [ ]  Swap - swap eth
- [ ]  Incoming transactions - receive native token
- [ ]  Settings - about MetaMask
- [ ]  Settings - general - change language - Hindi translations look good on all screens, but the other language tests partially failed. 
- [ ]  Settings - advanced - check custom nonce toggle
- [ ]  Settings - advanced - show hex data
- [ ]  Contract - deploy contract, mint and import NFT with hardware wallet
- [ ]  Contract - hardware wallet qr based connect
- [ ]  Contract - send token with hardware wallet

**Comment by georgewrmarshall** [comment]
Approved for @MetaMask/design-system-engineers 🟢 

Checked the following PRs were included and working in release PR:
- https://github.com/MetaMask/metamask-extension/pull/25122
- https://github.com/MetaMask/metamask-extension/pull/25124
- https://github.com/MetaMask/metamask-extension/pull/25011
- https://github.com/MetaMask/metamask-extension/pull/25010
- https://github.com/MetaMask/metamask-extension/pull/25083
- https://github.com/MetaMask/metamask-extension/pull/25158
- https://github.com/MetaMask/metamask-extension/pull/24971
- https://github.com/MetaMask/metamask-extension/pull/24953
- https://github.com/MetaMask/metamask-extension/pull/25019
- https://github.com/MetaMask/metamask-extension/pull/25050
- https://github.com/MetaMask/metamask-extension/pull/25228
- https://github.com/MetaMask/metamask-extension/pull/25176
- https://github.com/MetaMask/metamask-extension/pull/25237
- https://github.com/MetaMask/metamask-extension/pull/25225

**Review by georgewrmarshall — COMMENTED** [review]
Approved for design system
https://github.com/MetaMask/metamask-extension/pull/25586#issuecomment-2237555625

**Comment by Gudahtt** [comment]
@SocketSecurity ignore npm/@open-rpc/server-js@1.9.3
@SocketSecurity ignore npm/whatwg-fetch@3.6.20

These packages are intended to have network access

**Comment by Gudahtt** [comment]
@SocketSecurity ignore npm/@sentry-internal/browser-utils@8.19.0
@SocketSecurity ignore npm/@sentry/core@8.19.0
@SocketSecurity ignore npm/@sentry/utils@8.19.0

These are expected to have network access

**Comment by Gudahtt** [comment]
I tested the recent three Sentry commits by generally following the instructions here: https://github.com/MetaMask/metamask-extension/pull/26605/

The one adjustment I made was to set the sample rate to 1 so that performance events would be guaranteed to be sent. That can be adjusted here: https://github.com/MetaMask/metamask-extension/blob/42555d383bbfe9214941f84dd11733bca92e668c/app/scripts/lib/setupSentry.js#L85

I was able to confirm that:
* Errors were received from both mv3 and mv2 builds, and source maps are working correctly (Sentry showed unminified stack traces)
* We are receiving performance data, including page load time.

**Review by Gudahtt — APPROVED** [review]
We are ready to publish this now. No outstanding bug reports from QA or from the beta release.

**Review by benjisclowder — APPROVED** [review]

**Pull request merged**
