### PR TITLE
View address of an added token

### LINKED ISSUE #4440: Feature: View address of an added token
Unless I'm missing something, its impossible to view the address of an already added token unless you have made a previous transaction to that token. There should absolutely be some way of viewing/copying or opening the address in etherscan. This was a feature before the redesign.

### PR DESCRIPTION
**Pull request by scsaba**
Fixes #4440 

Added the "Copy Contract Address" and "View on Etherscan" actions.
There were two similar items in messages.json, "Copy to clipboard" and "View account on Etherscan", but in my opinion they do not describe these actions properly, hence I added these also.

image

### CODE REVIEW

**Comment by bdresser** [comment]
hey @scsaba, thanks for the fast turnaround and good work!

apologies for not including a visual mock - we'd like this to match the other dark menus throughout the extension. could you add a little more padding between each menu option? check out the "My Accounts" dropdown in the top right of the extension, and the menu__item and menu__item--clickable classes. let me know if you have questions 👍

**Comment by scsaba** [comment]
@bdresser thanks for the quick feedback, will adjust the style :)

**Comment by scsaba** [comment]
@bdresser, do you mean this dropdown on the old UI?

image

**Comment by bdresser** [comment]
on the Beta UI! From the top right, click “try beta” and then in the new UI
click the circle in the top right - there’s a menu of account options that
uses the classes I mentioned.

**Comment by scsaba** [comment]
@bdresser after changing the style:

image

**Comment by bdresser** [comment]
looks great @scsaba! @danjm or @alextsg will review early next week.

FYI @cjeria

**Review by cjeria — APPROVED** [review]

**Comment by scsaba** [comment]
Hi @bdresser, @danjm, @alextsg, I think that build failure is not related to my change. Could you please trigger a new build or should I push something that does the job?

**Review by alextsg — APPROVED** [review]

**Pull request merged**
