### PR TITLE
Allow sending transactions with hex data and no recipient

### LINKED ISSUE #5195: Send screen should allow no recipient with hex data
The hex data field can be used both for contract methods and for deploying a new contract.

Deploying a new contract is a normal transaction with:
- No recipient
- Transaction Data

Currently the new (beta) UI does not allow a tx with no recipient, making contract publication impossible from the new send screen.

For testing, a sample token hex data is:

```
0x608060405234801561001057600080fd5b506100cb6080604051908101604052806040805190810160405280600a81526020017f4574686572204d61696c0000000000000000000000000000000000000000000081525081526020016040805190810160405280600181526020017f31000000000000000000000000000000000000000000000000000000000000008152508152602001600181526020013073ffffffffffffffffffffffffffffffffffffffff168152506100da640100000000026401000000009004565b6000816000191690555061031e565b600060405180807f454950373132446f6d61696e28737472696e67206e616d652c737472696e672081526020017f76657273696f6e2c75696e7432353620636861696e49642c616464726573732081526020017f766572696679696e67436f6e74726163742900000000000000000000000000008152506052019050604051809103902082600001516040518082805190602001908083835b6020831015156101985780518252602082019150602081019050602083039250610173565b6001836020036101000a038019825116818451168082178552505050505050905001915050604051809103902083602001516040518082805190602001908083835b6020831015156101ff57805182526020820191506020810190506020830392506101da565b6001836020036101000a038019825116818451168082178552505050505050905001915050604051809103902084604001518560600151604051602001808660001916600019168152602001856000191660001916815260200184600019166000191681526020018381526020018273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001955050505050506040516020818303038152906040526040518082805190602001908083835b6020831015156102ea57805182526020820191506020810190506020830392506102c5565b6001836020036101000a03801982511681845116808217855250505050505090500191505060405180910390209050919050565b6107ef8061032d6000396000f300608060405260043610610041576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff168063f8a8fd6d14610046575b600080fd5b34801561005257600080fd5b5061005b610075565b604051808215151515815260200191505060405180910390f35b600061007f610765565b600080600060606040519081016040528060408051908101604052806040805190810160405280600381526020017f436f770000000000000000000000000000000000000000000000000000000000815250815260200173cd2a3d9f938e13cd947ec05abc7fe734df8dd82673ffffffffffffffffffffffffffffffffffffffff16815250815260200160408051908101604052806040805190810160405280600381526020017f426f620000000000000000000000000000000000000000000000000000000000815250815260200173bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb73ffffffffffffffffffffffffffffffffffffffff1681525081526020016040805190810160405280600b81526020017f48656c6c6f2c20426f62210000000000000000000000000000000000000000008152508152509350601c92507f4355c47d63924e8a72e509b65029052eb6c299d53a04e167c5775fd466751c9d60010291507f07299936d304c153f6443dfa05f40ff007d72911b6f72307f996231605b9156260010290507ff2cee375fa42b42143804025fc449deafd50cc031ca257e0b194a650a912090f6001026000546000191614151561024157fe5b7fc52c0ee5d84264471806290a3f2c4cecfc5490626bf912d01f240d7a274b371e60010261026e8561029a565b6000191614151561027b57fe5b61028784848484610436565b151561028f57fe5b600194505050505090565b600060405180807f4d61696c28506572736f6e2066726f6d2c506572736f6e20746f2c737472696e81526020017f6720636f6e74656e747329000000000000000000000000000000000000000000815250602b019050604051809103902061030583600001516105c9565b61031284602001516105c9565b84604001516040518082805190602001908083835b60208310151561034c5780518252602082019150602081019050602083039250610327565b6001836020036101000a03801982511681845116808217855250505050505090500191505060405180910390206040516020018085600019166000191681526020018460001916600019168152602001836000191660001916815260200182600019166000191681526020019450505050506040516020818303038152906040526040518082805190602001908083835b60208310151561040257805182526020820191506020810190506020830392506103dd565b6001836020036101000a03801982511681845116808217855250505050505090500191505060405180910390209050919050565b6000806000546104458761029a565b60405160200180807f190100000000000000000000000000000000000000000000000000000000000081525060020183600019166000191681526020018260001916600019168152602001925050506040516020818303038152906040526040518082805190602001908083835b6020831015156104d857805182526020820191506020810190506020830392506104b3565b6001836020036101000a0380198251168184511680821785525050505050509050019150506040518091039020905085600001516020015173ffffffffffffffffffffffffffffffffffffffff16600182878787604051600081526020016040526040518085600019166000191681526020018460ff1660ff1681526020018360001916600019168152602001826000191660001916815260200194505050505060206040516020810390808403906000865af115801561059d573d6000803e3d6000fd5b5050506020604051035173ffffffffffffffffffffffffffffffffffffffff1614915050949350505050565b600060405180807f506572736f6e28737472696e67206e616d652c616464726573732077616c6c6581526020017f74290000000000000000000000000000000000000000000000000000000000008152506022019050604051809103902082600001516040518082805190602001908083835b602083101515610661578051825260208201915060208101905060208303925061063c565b6001836020036101000a0380198251168184511680821785525050505050509050019150506040518091039020836020015160405160200180846000191660001916815260200183600019166000191681526020018273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200193505050506040516020818303038152906040526040518082805190602001908083835b602083101515610731578051825260208201915060208101905060208303925061070c565b6001836020036101000a03801982511681845116808217855250505050505090500191505060405180910390209050919050565b60a060405190810160405280610779610793565b8152602001610786610793565b8152602001606081525090565b604080519081016040528060608152602001600073ffffffffffffffffffffffffffffffffffffffff16815250905600a165627a7a7230582060c3e966deea84cbed6c8e861a2ed2a0f586ac8c81fee4a8dc9dde25dda1cabb0029
```

### PR DESCRIPTION
**Pull request by whymarrh**
Fixes #5195

### CODE REVIEW

**Comment by danjm** [comment]
Found during QA: if you set the recipient, then the hex data, then unset the recipient, you can't click "Next"

hexrecipientqa

Has to do with the `inError` in the `formShouldBeDisabled` method in `send-footer.component.js`. Shouldn't get to the error state if the hex data is set.

That this bug was possible within this PR suggests to me that something in the codebase (as it was before this PR) needs to be improved: either the way we handle errors or tests or something. It should have been easier for you as a developer to discover this...

**Review by danjm — CHANGES_REQUESTED** [review]
Fix the bug in the screenshot above and then I think this is good to go

**Comment by whymarrh** [comment]
Good catch, thanks! I'll fix that up.

**Comment by whymarrh** [comment]
@danjm fixed

**Review by alextsg — APPROVED** [review]

**Review by danjm — APPROVED** [review]

**Pull request merged**
