### PR TITLE
chore: update controllers as of core release v244

### PR DESCRIPTION
**Pull request by cryptodev-2s**
## **Description**

This PR bumps the following packages:
- `@metamask/ens-controller` to `^15.0.0`
- `@metamask/network-controller` to `^22.1.0`
- `@metamask/gas-fee-controller` to `^22.0.1`
- `@metamask/user-operation-controller` to `^20.0.1`
- `@metamask/polling-controller` to `^12.0.1`
- `@metamask/selected-network-controller` to `^19.0.0`

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/28781?quickstart=1)

## **Related issues**

Progresses https://github.com/MetaMask/MetaMask-planning/issues/3698

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by cryptodev-2s** [comment]
@metamaskbot update-policies

**Review by mikesposito — APPROVED** [review]
LGTM!

**Review by mcmire — APPROVED** [review]
It looks like we still have peer dependency warnings on `smart-transactions-controller` (which wants `transaction-controller` 38, but we have 41) and `ppom-validator` (which wants `network-controller` 21, but we are bumping to 22).

The warning for `smart-transactions-controller` was already pre-existing prior to this commit. The warning for `ppom-validator` is okay because the changes between `network-controller` 21 and 22 were minimal. We can bump `network-controller` in `ppom-validator` later.

LGTM.

**Review by Gudahtt — APPROVED** [review]
LGTM!

**Review by desi — APPROVED** [review]

**Pull request merged**
