### PR TITLE
feat: cross chain swaps - tx status - UI

### PR DESCRIPTION
**Pull request by infiniteflower**
## **Description**

This PR is a collection of all the UI related code from https://github.com/MetaMask/metamask-extension/pull/27740 (no UI changes). It has been split up in order to make it easier to review. 

The main addition is the Bridge Transaction Details and its supporting code.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/28657?quickstart=1)

## **Related issues**

Related to #27740, #28636

## **Manual testing steps**

Add `BRIDGE_USE_DEV_APIS=1` to `.metamaskrc` to enable Bridge

Refer to to #27740

## **Screenshots/Recordings**

Refer to to #27740

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by jclancy93** [comment]
I'm noticing an issue where I'm seeing the transaction pending on both the Lifi and socket explorers but it's returning pending in the UI and LiFi because of dest transaction despite the transaction being complete

https://www.loom.com/share/f66dec23c63b4353aa289a2723e3d984

**Review by jclancy93 — DISMISSED** [review]
Apart from some edge cases I'm seeing here, the polling and status fetching seems to work correctly

**Comment by infiniteflower** [comment]
> I'm noticing an issue where I'm seeing the transaction pending on both the Lifi and socket explorers but it's returning pending in the UI and LiFi because of dest transaction despite the transaction being complete
> 
> https://www.loom.com/share/f66dec23c63b4353aa289a2723e3d984
> 
> It does look like it was executed through lifi based on the calldata for the transaction. So seems like it may just be an issue on Lifi side
> 
> Update: once Lifi was correctly resolving the transaction status, I could see the bridge showing up correctly in the UI

So is the issue here that the MM UI is not updating fast enough given that the Socket Explorer said that both source + dest txs were confirmed?

**Review by micaelae — DISMISSED** [review]

**Review by micaelae — DISMISSED** [review]

**Comment by darkwing** [comment]
Most of the UI functions pretty well but I never get a quote or am able to execute the bridge:


https://github.com/user-attachments/assets/18bdc4ab-e853-4432-bdbf-71089dd4dceb

**Comment by infiniteflower** [comment]
> Most of the UI functions pretty well but I never get a quote or am able to execute the bridge:
> 
>  Screen.Recording.2024-11-27.at.4.59.25.PM.mov

Spoke to the team, the UI for "no quotes received" is still in development.

**Review by darkwing — APPROVED** [review]
Just nits but I won't block on them provided they are fixed shortly thereafter. 

Also, I'd prefer that Confirmations look at the transaction math.

**Comment by infiniteflower** [comment]
> Just nits but I won't block on them provided they are fixed shortly thereafter.
> 
> Also, I'd prefer that Confirmations look at the transaction math.

Will fix all your comments in a follow up PR, thanks so much for the approve 🙏 !

**Review by micaelae — APPROVED** [review]

**Pull request merged**
