### PR TITLE
Use EIP-1191 checksums

### LINKED ISSUE #11: Use EIP-1191 checksums in MetaMask
### Prize Bounty

0.01450 RBTC

(approximately 900 USD at time of posting)

### Challenge Description

Users can currently use the MetaMask browser extension to interact with the RSK network within DApps. However, there are a couple of minor incompatibilities which currently require the use of workarounds. This task is to eliminate this by allowing the user to configure 1 of 2 new options in MetaMask’s “Custom Network” feature, and using those values.

The 2 new options are “Derivation Path” and “Checksum uses Chain ID”. This bounty is **only** about “Checksum uses Chain ID”. If you attempt this bounty, we suggest that you also attempt [the other bounty about “Derivation Path”](https://github.com/rsksmart/rsk-gitcoin-hackathon-2021/issues/10), because if you complete one of these bounties, the other related bounty is likely to be much easier to complete, due to the similarity of the 2 tasks.

- In the “Custom Network” screen, expose a field named “Checksum uses Chain ID”. It should have an “info” icon next to it which displays a “tool tip” that says “When selected, calculate EIP1191 checksums using Chain ID.”
- Presently MetaMask does expose a field named “Chain ID”, which is used in several other areas, but does not use this during checksum calculation. This means that it uses [EIP-55](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md) for checksum calculations.
- RSK, on the other hand, uses [EIP-1191](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1191.md), which is an extension of EIP-55. When a Chain ID is provided, it is used as an input in the checksum calculation; and when a Chain ID is not provided, it defaults to EIP-55 checksums (backwards compatibility).
- The change should include changing the invocations of
  [MetaMask’s `checksumAddress`](https://github.com/MetaMask/metamask-extension/blob/76a2a9bb/ui/app/helpers/utils/util.js#L309-L312)
  to modify the function calls to
  [`ethereumjs-util`’s `toChecksumAddress`](https://github.com/ethereumjs/ethereumjs-util/blob/ebf40a0f/src/account.ts#L139-L161)
  to pass in the optional value of `eip1191ChainId` whenever “Checksum uses Chain ID” is present.

custom network in metamask dropdown menu mock up of metamask custom network with new option for checksum uses chain id

### Submission Requirements

- Integration should be written using Javascript and it should be submitted as a GIthub PR on the [MetaMask browser extension repo](https://github.com/MetaMask/metamask-extension)
- Also include a link to your own public Github repo with the git branch used in the Github PR submitted on the MetaMask browser extension repo
- Note that if you are attempting both related bounties (“Derivation Path” and “Checksum uses Chain ID”), they should be attempted separately, and submitted as separate Github PRs on separate git branches.
- Implement the features as described in the “challenge description” section
- Add tests that provide coverage for the new features added
- Refer to [MetaMask’s contributing docs](https://github.com/MetaMask/metamask-extension/tree/develop/docs) for instructions on how to develop on this repo.

### Judging Criteria

- Only one submission allowed per participant. Where a participant wishes to resubmit, update the original submission instead of submitting a separate entry.
- If the submission involves a graphical user interface of any variety, please include a video recording of it in action.
- If the submission involves a command line interface of any variety, please include a text file of it in action (including outputs).
- Test coverage for any implementation is viewed favourably: More test coverage is better.
- In cases where the bounty requires a Github PR on an existing repo, and that repo has continuous integration (CI) set up, the PR should not fail on the CI steps.
- Documentation is viewed favourably: Include specific instructions on how to set up and use your submission. Optionally, include any explanations of architectural/ design choices that went into the submission.
- The easier it is for the reviewer to run and understand the submission, the better, so be sure to consider this in your submissions!

### Winner Announcement Date

- This bounty is part of a hackathon, and there are three significant dates:
  - Start date: 15/04/2021
  - End date: 14/05/2021
  - Results date: 15/06/2021
- Submissions are welcome between the start date and the end date.
- Reviews will be conducted between the end date and the results date.
- All submissions must be submitted prior to the end date in order to be eligible for a bounty award.
- Submissions submitted or resubmitted after the end date may not be awarded any bounty.
- All submissions must be reviewed and accepted (successfully pass the review) prior to the results date in order to be eligible for a bounty award.
- The bounty will be awarded on the Gitcoin platform to the best submission among all eligible submissions for this bounty.

### More information

- For questions related to this bounty, and other bounties in this hackathon, please join the
  [RSK Slack](https://developers.rsk.co/slack),
  and check out the `#gitcoin2021` channel.
- To learn more about RSK and RIF technologies, check out our
  [Developer Portal](https://developers.rsk.co/).

### PR DESCRIPTION
**Pull request by anukul**
Fixes: https://github.com/rsksmart/rsk-gitcoin-hackathon-2021/issues/11

Explanation:  See [EIP-1191](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1191.md). MetaMask accepts chain ID in network configuration, but does not currently use it in checksum calculation. The PR adds this feature.

image

Manual testing steps:  
  - Add custom network, specify chain ID.
  - Toggle "Checksum uses Chain ID" checkbox and see updated checksum in one of many places where it is rendered (export private key modal, confirm remove account etc.)

### CODE REVIEW

**Comment by bguiz** [comment]
> A large and increasing portion of our users are brand new to the space and immediately trying to use custom networks which would be hindered, perhaps, by presenting this option. 

@brad-decker agreed to some extent - "custom networks" is already somewhat advanced for that category of user ;)
However, where networks require this, such as [RSK](https://developers.rsk.co/rsk/architecture/account-based/#checksum], not having this available causes a bigger obstacle, where we we resort to workarounds such as "convert to lowercase" or "ignore the checksum warning" in various scenarios.

> Any ideas?

Perhaps have a toggle for "show/ hide extended options" (and have that hidden by default)?
Happy to have a chat about this!

**Comment by brad-decker** [comment]
> @brad-decker agreed to some extent - "custom networks" is already somewhat advanced for that category of user ;)

@bguiz -- agreed, but they're being instructed to do it by many chains or following tutorials. They already don't know what is going on and the clicking or not clicking of this field can impact the behavior of the extension and their experience. 

A few various places (trezor, ledger, myEtherWallet, etc) out there only check for rsk chain ids before changing the checksum, whereas more generalized utilities like web3, ethereumjs-util, etc will just do it you provide a chainId assuming you know what you're doing... Is there an exhaustive list of chains that are 1191 compatible?

**Comment by bguiz** [comment]
> agreed, but they're being instructed to do it by many chains or following tutorials. They already don't know what is going on and the clicking or not clicking of this field can impact the behavior of the extension and their experience.

that's what we do as well :wink: 

We may very well soon start recommending that dapp devs start using [EIP-3085 / `wallet_addEthereumChain`](https://docs.metamask.io/guide/rpc-api.html#other-rpc-methods) instead of asking users to modify their network config.

> A few various places (trezor, ledger, myEtherWallet, etc) out there only check for rsk chain ids before changing the checksum, whereas more generalized utilities like web3, ethereumjs-util, etc will just do it you provide a chainId assuming you know what you're doing... Is there an exhaustive list of chains that are 1191 compatible?

There is a list of all networks and their chain IDs - https://chainid.network/ lists them - but it does not indicate whether they support EIP-1191 or not.

:thinking: ... are you perhaps considering an option where there's perhaps a config which lists which chainIDs use EIP-1191 - and have this baked into the MetaMask source code (instead of exposing it in custom config)? Because that sounds like a great solution too!

**Comment by brad-decker** [comment]
@bguiz -- Perhaps, or perhaps merging that work into chainid.network and using it (the npm package) to determine when to enable EIP1191 checksum support. Anything that doesn't involve making the custom network form more complex, or requiring a new field be added to `wallet_addEthereumChain`.

**Pull request closed without merging**
