### PR TITLE
Update Sentry to v5.x

### PR DESCRIPTION
**Pull request by Gudahtt**
Theses changes were made in accordance with [the provided migration guide](https://github.com/getsentry/sentry-javascript/blob/master/MIGRATION.md).

The two integrations added were included by default on v4.x, so this shouldn't result in any change in behavior.

### CODE REVIEW

**Review by whymarrh — DISMISSED** [review]
Seems legit

**Comment by Gudahtt** [comment]
I'm going to test this out locally with a test Sentry account to make sure all the release stuff works, so nobody merge this yet please. I'll update here when I'm done.

**Comment by Gudahtt** [comment]
Sorry for the delay! I have tested this, and it works the same as it did before.

**Review by whymarrh — APPROVED** [review]
LGTM

**Pull request merged**
