### PR TITLE
update prettier

### PR DESCRIPTION
**Pull request by brad-decker**
## Explanation
Updates prettier to latest version to take advantage of performance and legibility improvements. The key difference is how prettier breaks long lines up. See before / after sections for examples. Prettier now puts a higher importance on breaking after operators in assignments, so whereas previously it might add line breaks to a `const { x, y, z } = foo;` destructuring assignment such that x, y and z are all on new lines, now it'll break after the `=` and indent the next line.  

### Before & After

image
image
image

## Pre-Merge Checklist

- [x] PR template is filled out
- [ ] **IF** this PR fixes a bug, a test that _would have_ caught the bug has been added
- [ ] PR is linked to the appropriate GitHub issue
- [ ] PR has been added to the appropriate release Milestone

### CODE REVIEW

**Review by darkwing — DISMISSED** [review]
OMG I love this!

IMO, in the future, with these big PRs, we should do 2 commits -- the first with the prettier update, the second with all of the subsequent file updates.  Makes reviewing a bit easier.

**Comment by brad-decker** [comment]
Good call, i did that on the eslint pr. i'm happy to break this up into two commits soon for future reviewers.

**Comment by brad-decker** [comment]
@darkwing split the commits :)

**Review by darkwing — APPROVED** [review]

**Review by adonesky1 — APPROVED** [review]
LGTM! I didn't thoroughly vet every single line if I'm being honest... but scanned for obvious issues.

**Comment by BelfordZ** [comment]
There are some cases where the output seems less than ideal:

image


short lhs of assignment, long rhs -> make rhs shorter by line breaking on the first `.` would be IMO prefered way to handle this case

**Comment by brad-decker** [comment]
Prettier optimizes lines of code based on the maximum line length, 80. With few exceptions there is only one way to modify its output: modifying the max line length. I am sure we want the update to the latest version, especially considering we want to be able to take advantage of performance improvements as well as future updates. If we want to discuss the output of prettier as a whole we can do that outside of this pull request as it will involve every aspect of its output versus just the way it breaks lines for assignment operations.

**Comment by brad-decker** [comment]
Marking as Do Not Merge just so i can get some clarification on @BelfordZ 's comment and see if he's comfortable pushing this forward and discussing prettier output elsewhere

**Comment by BelfordZ** [comment]
@brad-decker thanks for the reply. I deleted my comment as I realized we were simply updating, not changing anything from the default settings. My B! 

default settings FTW -- Might just take some getting used to.

**Comment by brad-decker** [comment]
@BelfordZ -- Questions about our defaults and standards are welcome! I'd like to preserve the intent of your original message so I'm just gonna paraphrase without specifics:

@BelfordZ was commenting on *where* prettier chooses to break lines, and suggested that a specific way would be more legible to him. 

There were a number of back-and-forth conversations at the time we elected to use prettier, most of which centered around this concept. In the end we opted to just use the default settings because changing line length resulted in very much unwanted formatting. https://github.com/MetaMask/metamask-extension/pull/8595 is the original PR.

**Pull request merged**
