### PR TITLE
Put qr button back in account detail screen...

### LINKED ISSUE #621: Install the QR code generator

### PR DESCRIPTION
**Pull request by frankiebee**
..As well as use a qr node module instead of an api to generate the qr codes. 

fixes #621 
screen shot 2016-09-12 at 5 21 14 pm
screen shot 2016-09-12 at 5 18 34 pm

### CODE REVIEW

**Comment by flyswatter** [comment]
Have you tried this with any other qr-supporting eth clients, like sending from jaxx?

**Comment by flyswatter** [comment]
That was as fast as you said it would be!

**Comment by frankiebee** [comment]
@flyswatter no I've just tried reading it with a qr reader on my phone to make sure its the same address

**Comment by flyswatter** [comment]
I’m just curious if the other readers have implemented a particular protocol, other than just the address.

I’d like to confirm this is inter-operable before we declare it done.

**Comment by frankiebee** [comment]
coinbase's qr for wallet info is: 
```
bitcoin:
someaddressofyours
```

**Comment by flyswatter** [comment]
Frankie verified compatibility with jaxx & coinbase!

**Pull request merged**
