### PR TITLE
Enable LavaMoat for webapp background

### PR DESCRIPTION
**Pull request by kumavis**
This enables :volcano: **LavaMoat** :volcano:  protections in the webapp background process

### status
- [x] prepare `@lavamoat/lavapack` runtime (non-cjs)
- [x] add and use `@lavamoat/lavapack` runtime for background
- [x] add `lavamoat-browserify` for policy auto generation
- [x] update build policy
- [x] create handy policy generation yarn script
- [x] add browserify policy override
- [x] fix lavapack runtime-cjs bug
- [x] patch or fix transforms to be minify-proof
- [x] fix e2e delays
- [x] e2e delays upstreamed first https://github.com/MetaMask/metamask-extension/pull/11667
---

previous draft PR: https://github.com/MetaMask/metamask-extension/pull/10838

### CODE REVIEW

**Comment by kumavis** [comment]
need to fix how the policy gets loaded

**Comment by kumavis** [comment]
> error Command "lavamoat:debug" not found

**Comment by Gudahtt** [comment]
In the test that was stalling, I added a few 5-second pauses each time the popup was opened to give time for it to finish loading. This seems to have gotten the tests un-stuck. I only added them in the failing test suite though - the pauses may be needed elsewhere as well.

It seems like the page load time is _much_ longer on this branch. It takes a few seconds locally for the popup to get past the "grey rectangle" state.

**Comment by kumavis** [comment]
doing some QA:
- perf seems fine
- background packages are indeed sandboxed

**Comment by kumavis** [comment]
guess ill go eat worms

**Comment by kumavis** [comment]
moving to https://github.com/MetaMask/metamask-extension/pull/12242

**Pull request closed without merging**
