### PR TITLE
Update `zh_CN` localized messages

### PR DESCRIPTION
**Pull request by Gudahtt**
These translations were provided by Lionbridge.

### CODE REVIEW

**Comment by Gudahtt** [comment]
This is waiting on #9388, which conflicts and was submitted first.

**Comment by Gudahtt** [comment]
This PR has been rebased onto `develop` to ensure that the `yourSigRequested` message was not present (it was removed in #10300).

**Comment by Gudahtt** [comment]
This has been rebased onto `develop`, and the unused message `swapsGetQuotes` has been removed.

This is now ready for review! These translations were written from-scratch though, whereas the existing translations were the result of carefully-reviewed community contributions, so these might all be worse than what we have :thinking:

**Comment by darkwing** [comment]
@DDDDDanica We very much appreciated your localization on https://github.com/MetaMask/metamask-extension/pull/9388 ; would you have a moment to review some of this patch?

**Comment by Gudahtt** [comment]
I've just rebased this again to resolve conflicts (one message was removed)

**Comment by darkwing** [comment]
@DDDDDanica Would you have a moment for a quick review?

**Comment by Gudahtt** [comment]
I've just rebased this again to resolve conflicts (a few messages were removed)

**Comment by darkwing** [comment]
The localizers didn't have access to our current translations so we should likely provide those and have them be modified.  There's no guarantee that these are better than our current localizations.

**Pull request closed without merging**
