### PR TITLE
Support Incoming Transactions for Base

### PR DESCRIPTION
**Pull request by danyalprout**
## Explanation

Currently when using MetaMask with Base you don't see incoming transactions (Receive entries) in the Activity tab.

This PR is a small quality of life improvement for Base + MetaMask users which updates the config to enable the incoming transactions. See this [PR](https://github.com/metaMask/metamask-extension/pull/14219) for when support was added to fetch incoming transactions via Etherscan API.

You can confirm the Etherscan endpoints here:
* [Testnet](https://api-goerli.basescan.org/api?module=account&action=txlist&address=0x7d5A90C2cd5567B9966E92c710b5E9936F400d74&tag=latest&page=1)
* [Mainnet](https://api.basescan.org/api?module=account&action=txlist&address=0x7d5A90C2cd5567B9966E92c710b5E9936F400d74&tag=latest&page=1)

### Before

https://github.com/MetaMask/metamask-extension/assets/672580/16c93eb9-bb9d-4954-b7f8-8625fdedb2c1

### After

https://github.com/MetaMask/metamask-extension/assets/672580/68d01b8d-0585-4d10-ad10-66a6021c9b4e

## Manual Testing Steps

- Add the Base [testnet](https://chainlist.org/chain/84531) or [mainnet](https://chainlist.org/chain/8453) to Metamask
- Switch to that network
- Send funds from account 1 to account 2
- Switch to the account 2 activity tab and you should see a "Receive" entry for the funds you sent

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [x] How reviewers can test my changes
- [x] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [x] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [x] PR is linked to the appropriate GitHub issue
- [x] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Comment by danyalprout** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by pedronfigueiredo — DISMISSED** [review]

**Review by DDDDDanica — DISMISSED** [review]

**Comment by HowardBraham** [comment]
I want to put a hold on this PR for a minute.  Are we sure that this actually works?

I know it worked a month ago, but some of what was in the original commit was added in other PRs.  And when I tested this, I did not see any incoming transactions.

**Comment by danyalprout** [comment]
The Basescan API is currently having an outage, which is likely preventing this from working right now.

I'll double check this PR tomorrow when the API is hopefully back online

**Comment by danyalprout** [comment]
@HowardBraham I've just retested/rebased this and it seems ok (videos below). Note it requires some changes to security & privacy settings to be enabled. Let me know if you need anything else


https://github.com/MetaMask/metamask-extension/assets/672580/bb0ed95b-f0a1-4404-af35-90eb97163572


https://github.com/MetaMask/metamask-extension/assets/672580/d28b3e0b-a84e-418e-b8e9-4fb1765f3ba3

**Review by HowardBraham — APPROVED** [review]

**Pull request closed without merging**
