### PR TITLE
[MMI] Add MMI modals with their styles to the app/modals

### PR DESCRIPTION
**Pull request by albertolive**
## Explanation

This PR adds MMI modals with their styles to the `app/modals`
Ref ticket: https://consensyssoftware.atlassian.net/browse/MMI-2587

## Pre-merge author checklist

- [X] I've clearly explained:
  - [X] What problem this PR is solving
  - [X] How this problem was solved

## Pre-merge reviewer checklist

- [X] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [X] PR is linked to the appropriate GitHub issue

### CODE REVIEW

**Review by georgewrmarshall — COMMENTED** [review]
Hey @albertolive, there are discussions happening about not using this method to display modals. I'm planning on deprecating this method in the next sprint. Apologies, I know this is not clear. https://consensys.slack.com/archives/GTQAGKY5V/p1684167245776399

**Comment by zone-live** [comment]
> Hey @albertolive, there are discussions happening about not using this method to display modals. I'm planning on deprecating this method in the next sprint. Apologies, I know this is not clear. https://consensys.slack.com/archives/GTQAGKY5V/p1684167245776399

Hi @georgewrmarshall while the current model is still valid, can we still merge these, as we will need them, and then come back later and change to the new setup? We will be happy to do it asap as well.

**Comment by georgewrmarshall** [comment]
Hi @albertolive, I think that seems reasonably although the quicker we deprecate this folder the better. I'd also like to check with @brad-decker to get his thoughts on it.

**Review by brad-decker — APPROVED** [review]

**Comment by brad-decker** [comment]
@zone-live is going to create a follow up task to remove these modals. I don't want to delay the MMI build by forcing the refactor here. That said we should continue monitoring this folder/path for additional usages and prevent them from merge in the future. Thanks @georgewrmarshall

**Review by zone-live — APPROVED** [review]

**Pull request merged**
