### PR TITLE
Specify that Zora is a multilayer network

### PR DESCRIPTION
**Pull request by kolber**
## Explanation

Zora is also based on the OP stack, so follows the same gas rules as Optimism and Base.
This closely follows the form of #20097.

## Manual Testing Steps

- Open the extension
- Add the [Zora network](https://chainlist.org/chain/7777777)
- Send some transactions

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [x] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Comment by kolber** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by danjm — DISMISSED** [review]

**Review by pedronfigueiredo — DISMISSED** [review]

**Review by brad-decker — DISMISSED** [review]

**Review by alanaladd21 — APPROVED** [review]

**Comment by bschorchit** [comment]
Hi @kolber, sorry for the delay in working through your PR. We'll get to it soon (expect ~2 weeks).

**Comment by kolber** [comment]
> Hi @kolber, sorry for the delay in working through your PR. We'll get to it soon (expect ~2 weeks).

No problem at all! Thanks for the update. :)

**Comment by bschorchit** [comment]
Just an update: the team will be wrapping up a work this week that is currently blocking moving on to this. 
Sorry for the delay, but we're planning to get to this soon!

**Comment by iainnash** [comment]
@bschorchit Just bumping this. We have users actively switching to other wallets due to inflated fees that result from this diff and it would be great to offer a consistent experience between wallets.

**Comment by sbvegan** [comment]
+1 on this!

**Pull request closed without merging**
