### PR TITLE
Optional Chain_id w/o Native ETC Support

### PR DESCRIPTION
**Pull request by chrisfranko**

### CODE REVIEW

**Comment by bdresser** [comment]
rather than change all currency conversion from Infura to cryptocompare, perhaps we could default to Infura (for standard networks) and only hit cryptocompare if the user has entered a custom `chainId`.

@danfinlay what do you think? any other concerns about the changes to the block explorer?

**Comment by hackmod** [comment]
with predefined ETC network, I can make PR #4932 (formerly known PR #4516) support optional chainId + blockExplorer + symbol + currency conversion using cryptocompare.
I don't think its a big deal to get ETC network merged into trunk. its a routine thing. so that the MetaMask support multi chain properly as already described at the MetaMask blog ([multiple network support](https://medium.com/metamask/metamasks-vision-for-multiple-network-support-4ffbee9ec64d) )
image before https://github.com/ethereum/EIPs/pull/1102 is implemented correctly.

and this PR only remove some part of ETC menu only, but it can be done in the settings menu like as following:
image

**Comment by chrisfranko** [comment]
Why dont we just fork and manage our own version with the changes we want? I know it would be ideal to have them in MetaMask but they have made up their mind already. -shrug-

**Comment by danfinlay** [comment]
Thanks for the PR, I hope to have some time next week to review it.

**Review by ghost — APPROVED** [review]
ACK for the PR, can you please squash your commit into one?

**Comment by bdresser** [comment]
thanks @chrisfranko - closing in favor of https://github.com/MetaMask/metamask-extension/pull/5134

**Pull request closed without merging**
