### PR TITLE
Update BannerAlert component

### LINKED ISSUE #17552: `BannerAlert` audit and insight report updates
### Description
Complete the updates needed to align `BannerAlert` to the insight report

### Technical Details
- Rename `Banner` to `BannerAlert` 
- Add border-left previously in `BannerBase`
- Possibly more check audit and insight report in references

### Acceptance Criteria 
- `BannerAlert` meets the criteria set in the insight repoirt

### References
- [FigJam Audit](https://www.figma.com/file/ZRc86y4pTE33gLMdrobHCJ/Banner-Audit?node-id=172%3A367&t=SFnUqxHYB1d14p9k-1)

### PR DESCRIPTION
**Pull request by garrettbear**
## Explanation

*Fixes #17552 

Complete the updates needed to align `BannerAlert` to the insight report

### Technical Details
- Rename `Banner` to `BannerAlert` 
- Add border-left previously in `BannerBase`
- Possibly more check audit and insight report in references

### Acceptance Criteria 
- `BannerAlert` meets the criteria set in the insight repoirt

### References
- [FigJam Audit & Insight Report](https://www.figma.com/file/ZRc86y4pTE33gLMdrobHCJ/Banner-Audit?node-id=172%3A367&t=SFnUqxHYB1d14p9k-1)

## Screenshots/Screencaps
n/a

## Manual Testing Steps
`yarn jest ui/components/component-library`

## Pre-merge author checklist

- [X] I've clearly explained:
  - [X] What problem this PR is solving
  - [X] How this problem was solved
  - [X] How reviewers can test my changes
- [X] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [X] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [X] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Review by georgewrmarshall — CHANGES_REQUESTED** [review]
Still some instances of `Banner` 

Screenshot 2023-02-03 at 10 50 30 AM

Also getting this error in storybook may have forgot to remove the stylesheet instance in the `component-library-components.scss` file

Screenshot 2023-02-03 at 11 03 33 AM

**Review by georgewrmarshall — COMMENTED** [review]
Code is looking good. I think you need to remove the old `banner.test.js.snap` and tests should pass. Once there is a storybook build I can do a visual check

**Review by georgewrmarshall — CHANGES_REQUESTED** [review]
Looks like we are missing the border-left?

Screenshot 2023-02-06 at 2 45 22 PM

**Review by georgewrmarshall — APPROVED** [review]
LGTM

**Review by NidhiKJha — APPROVED** [review]

**Pull request merged**
