### PR TITLE
Import account message

### PR DESCRIPTION
**Pull request by tmashuang**
Change Loose Label to Imported to prevent confusion.

screen shot 2018-02-03 at 4 35 19 am

Add a message for users that are importing accounts

screen shot 2018-02-03 at 1 44 12 pm

### CODE REVIEW

**Comment by tmashuang** [comment]
A recent comment from a user on #2243 incentives this enhancement.

**Comment by cjeria** [comment]
@Zanibas Here's my copy feedback:

"Imported accounts will not be associated with your originally created MetaMask account seedphrase. Learn more about imported accounts here."

This should also be spec'd for the New UI design.

**Review by cjeria — COMMENTED** [review]
I would say:

"Imported accounts will not be associated with your originally created MetaMask account seedphrase. Learn more about imported accounts here."

**Comment by kumavis** [comment]
@tmashuang theres some conflicts that need to be addressed, but lets get this merged : )

**Comment by tmashuang** [comment]
Created a new PR for this change and updated UAT with it as well. Closing in favor of #3335.

**Pull request closed without merging**
