### PR TITLE
test: Assert accounts are removed with snap removal in existing test

### PR DESCRIPTION
**Pull request by plasmacorral**
## **Description**

Updating existing test to confirm that accounts are removed when the snap is removed

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/24442?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/accounts-planning/issues/439

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by hjetpoluru** [comment]
Could we include more assertions based on the specific account that was added? Otherwise, it looks good.

**Comment by plasmacorral** [comment]
> Could we include more assertions based on the specific account that was added? 

Thank you, @hjetpoluru! Yes, we could.  Are you suggesting to add assertions to confirm that the created account address is what we expect?

Bear in mind the snap simple keyring (SSK) does create a unique private key on any new account creation. In these tests we are not expecting a specific account address, rather just some public address derived from the private key that was created.  Verifying the address that was added in the accounts list would certainly be beneficial if we were testing the import of a known private key through SSK, but here we are a creating new random private key.

**Comment by hjetpoluru** [comment]
Yes, I totally agree with you that the address is dynamically created, and it's validated in the creation of the account in another test.

**Review by hjetpoluru — APPROVED** [review]
LGTM.

**Review by chloeYue — APPROVED** [review]
LGTM!

**Pull request merged**
