### PR TITLE
feat(NOTIFY-840): use `@metamask/notification-services-controller` and `@metamask/profile-sync-controller`

### PR DESCRIPTION
**Pull request by mathieuartu**
## **Description**

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/25894?quickstart=1)

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by mathieuartu** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Prithpal-Sooriya** [comment]
Oooh this is chonky lol, I'm happy to sync if there are good chunks/cut points if this needs breaking up into smaller PRs

**Comment by mathieuartu** [comment]
> Oooh this is chonky lol, I'm happy to sync if there are good chunks/cut points if this needs breaking up into smaller PRs

Yeaaaah @Prithpal-Sooriya it's a lot! Half of these are deleted files, but still 😅

**Comment by Prithpal-Sooriya** [comment]
@metamaskbot update-policies

**Comment by Prithpal-Sooriya** [comment]
@metamaskbot update-policies

**Comment by Prithpal-Sooriya** [comment]
@metamaskbot update-policies

**Comment by Prithpal-Sooriya** [comment]
@metamaskbot update-policies

**Comment by Prithpal-Sooriya** [comment]
@metamaskbot update-policies

**Comment by Prithpal-Sooriya** [comment]
Closing as this has been merged through smaller, incremental PRs.

**Pull request closed without merging**
