### PR TITLE
Migrate help-text components to TS

### LINKED ISSUE #19121: Migrate components to TS: HelpText
### Description
Migrate `HelpText` component to TypeScript

### Technical Details

- Convert Objects in `SNAKE_CASE` to enums in `PascalCase` (name and keys)
- Ensure enums use singular not plural e.g. `Size` not `Sizes`
- Update file name from `component-name.contants.js` to `component-name.types.ts` and add types
- Update file name from `component-name.js` to `component-name.tsx` and add types
- Update file name from `component-name.test.js` to `component-name.test.tsx`
- Update file name from `component-name.stories.js` to `component-name.stories.tsx`
- Update all instances of component objects to enums
- Update all documentation

### Acceptance Criteria

- Component has been converted to TypeScript
- Stories, documentation and tests have been updated inside of the `component-name` folder
- Before/After screen cast of component stories in storybook to show no visual regression after migration

### Difficulty: Intermediate

Good first issue for: External contributors who are familiar with TypeScript and want to contribute to improving the stability of the extension

### PR DESCRIPTION
**Pull request by taesuklee**
## Explanation

New PR based on https://github.com/MetaMask/metamask-extension/pull/19170 with better branch name. 

Added forwardRef to help-text component [as suggested](https://github.com/MetaMask/metamask-extension/pull/19170#discussion_r1197217485).

Fixes https://github.com/MetaMask/metamask-extension/issues/19121

Migrate [HelpText components](https://github.com/MetaMask/metamask-extension/tree/develop/ui/components/component-library/help-text) to TypeScript.

## Screenshots/Screencaps
No visual regression after migration.

## Manual Testing Steps
7 unit tests by `yarn jest ui/components/component-library/help-text/help-text.test.tsx` pass.

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [x] How reviewers can test my changes
- [x] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Comment by georgewrmarshall** [comment]
Hey @taesuklee, Thanks for your time and effort in creating this pull request. We have identified an issue related to the typing of the `Box` component, specifically with the polymorphic `as` prop. To address this issue, we have an open ticket at https://github.com/MetaMask/metamask-extension/issues/19239 and a draft pull request at https://github.com/MetaMask/metamask-extension/pull/19363 that needs to be merged before we can proceed with your PR. Thanks for your patience

**Comment by taesuklee** [comment]
> Hey @taesuklee, Thanks for your time and effort in creating this pull request. We have identified an issue related to the typing of the `Box` component, specifically with the polymorphic `as` prop. To address this issue, we have an open ticket at #19239 and a draft pull request at #19363 that needs to be merged before we can proceed with your PR. Thanks for your patience

Hey @georgewrmarshall, Thank you for letting me know. That would totally make sense to convert the `box` component to TS. I will make additional commit to this PR if necessary once the issue with `box` component is resolved.

**Comment by georgewrmarshall** [comment]
Blocked by https://github.com/MetaMask/metamask-extension/pull/19572

**Comment by georgewrmarshall** [comment]
Hey @taesuklee, thank you very much for your contribution! Another PR was opened that solves this task and has one approval so I am going to close this PR https://github.com/MetaMask/metamask-extension/pull/20108

**Pull request closed without merging**
