### PR TITLE
V12.0.5 cherrypick 2dc3768 fix network form update configuration in place state corruption

### PR DESCRIPTION
**Pull request by jiexi**
Cherrypick https://github.com/MetaMask/metamask-extension/pull/26453

No major merge conflicts except for having to recreate the @metamask/network-controller patch against 19.0.0 to 18.1.2

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/26457?quickstart=1)

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by jiexi** [comment]
patch branch for network-controller 18.1.2

https://github.com/MetaMask/core/compare/jl/network-controller%4018.1.2-patch?expand=1

**Comment by DDDDDanica** [comment]
@metamaskbot update-policies

**Comment by DDDDDanica** [comment]
@metamaskbot update-policies

**Comment by danjm** [comment]
@metamaskbot update-policies

**Review by DDDDDanica — APPROVED** [review]

**Comment by danjm** [comment]
@metamaskbot update-policies

**Pull request merged**
