### PR TITLE
Skip render when home page is closing or redirecting

### PR DESCRIPTION
**Pull request by Gudahtt**
The Home page component is responsible for closing the notification window and triggering redirects in various situations. When this happens, the home page is briefly rendered before the redirect/close happens. This is a waste of cycles, and is distracting for users.

We now render nothing if the page is in the process of redirecting or reloading. None of the redirects handled in this component are for sub-pages, so we don't need the Home page to render in any of these cases.

We were already doing this for redirects to transaction confirmations, but now we're taking the same approach for all redirects, and for the cases where the window is closed.

### CODE REVIEW

**Comment by Gudahtt** [comment]
This depends upon #9011

**Review by rekmarks — COMMENTED** [review]
This is great! Does it work as intended with multiple queued permissions requests as well?

**Comment by Gudahtt** [comment]
Yep! It handles multiple permission requests and confirmations perfectly.

Unfortunately it's broken in another way though; the "closing/redirecting" states are set on update, but the actual closing/redirecting only happens on mount. I'm updating it now to ensure the states are only set before mount.

**Review by rekmarks — APPROVED** [review]
LGTM!

**Pull request merged**
