### PR TITLE
issue #17475

### LINKED ISSUE #17475: UX: Replace all FontAwesome Icons with New Icons
### Description
In an effort to reduce inconsistencies it would be great to replace all Fontawesome icons with their `<Icon>` or `<ButtonIcon>` component equivalent. This is a massive undertaking by itself and creating a single PR would be too large. Instead this issue should be broken up into multiple PRs. 

### Technical Details
- Search for Fontawesome icons in the codebase by searching `fa fa-` and swap it out for the `Icon` component equivalent

### Acceptance Criteria
- All Fontawesome icons have been replaced with their `Icon` equivalent
- PR contains a **minimum of 1 file** and a **maximum of 3 files**
- Add Before / After screenshots to your PR to ensure no visual regressions
- Reference this issue in the description of your PR
- All CI tests are passing jest, lint, e2e etc

PRs that don't meet the acceptance criteria may be closed.

### References
[`Icon` component documentation](https://metamask.github.io/metamask-storybook/?path=/docs/components-componentlibrary-icon--docs)
[`ButtonIcon` component documentation](https://metamask.github.io/metamask-storybook/?path=/docs/components-componentlibrary-buttonicon--docs)

### Difficulty: Intermediate

Good first issue for: External contributors who are familiar with running the extension locally, have knowledge of React, component props, Jest tests, linting, and Storybook, and want to contribute to improving the cohesiveness of UI in the extension

### PR DESCRIPTION
**Pull request by RohanJacob23**
## Explanation
Hi,
I have fixed the issue #17475.
I have replaced the FontAwesome Icons with New Icons (Only Lock Icon)

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Comment by RohanJacob23** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by georgewrmarshall — COMMENTED** [review]
Hey @RohanJacob23, Thanks for the contribution! Could you please add some screenshots of before and after of the changes to the icons in the PR description? Also looks like there are some linting issues that you can debug using `yarn lint` Thanks!

**Comment by RohanJacob23** [comment]
Hello @georgewrmarshall,

I apologize for any inconvenience, but I'm having difficulty running the project locally. I'm new to open source.

Thank you.

**Comment by georgewrmarshall** [comment]
Hey @RohanJacob23, that's ok! Have you followed the readme? https://github.com/MetaMask/metamask-extension#building-locally. Are you getting any error messages in your terminal?

**Comment by RohanJacob23** [comment]
Hello @georgewrmarshall ,
I have checked the readme and followed the steps, and I am not receiving any errors. However, I am stuck at this point (see image below) when trying to run 'yarn start'. 

Screenshot (204)

**Pull request closed without merging**
