### PR TITLE
Clear Sass deprecations

### LINKED ISSUE #12979: DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.
**Describe the bug**
During the building process with `yarn dist` I get 5 Warnings due to the use of "/" for division in .scss files. The issue is explained here:
https://github.com/twbs/bootstrap/issues/34051

**Steps to reproduce**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Clone the repo
2. Run `yarn setup`
2. Run `yarn dist`

**Expected behavior**
Clean build without errors and warnings.

**Screenshots**
Warning Example 1:
image
Code affected (lines 6 & 7)
image

Affected files & modules:
- node_modules/@fortawesome/fontawesome-free/scss/_variables.scss 12:25
- node_modules/@fortawesome/fontawesome-free/scss/_larger.scss 6:15
- node_modules/@fortawesome/fontawesome-free/scss/_larger.scss 7:17
- node_modules/@fortawesome/fontawesome-free/scss/_list.scss 6:16
- ui/css/utilities/_colors.scss

**Browser / OS details**
 - Building on Unix

### PR DESCRIPTION
**Pull request by mcmire**
Sass has changed the syntax for dividing two numbers. Previously you
would use `/`, but because this causes some ambiguity with color
functions (`rgb()`, `rgba()`, and the like), where `/` is regularly used
to separate color channel information from an alpha value, [Sass has
deprecated the use of `/` for division.][1]

This commit converts all such usages to use `math.div()` instead. This
is a little bit difficult because there are a few places in
`@fortawesome/fontawesome-free` which use the old syntax. [There is an
issue open here about it][2] but that has not been fixed yet. So we have
to patch this package to make the deprecation warnings go away.

[1]: https://sass-lang.com/documentation/breaking-changes/slash-div
[2]: https://github.com/FortAwesome/Font-Awesome/issues/18371

---

Fixes #12979.

**Manual testing steps:** There aren't any user-facing changes, so there is nothing to test UI-wise. From a developer standpoint, however, one should be able to run `yarn start` or `yarn start:dev` without any Sass-related messages appearing in the output.

### CODE REVIEW

**Comment by darkwing** [comment]
Awesome!  I have a PR that removes the utility file  but I think we can go with this in the mean time.

**Review by darkwing — DISMISSED** [review]

**Comment by darkwing** [comment]
Hey, sorry, this needs an update since my CSS Vars PR went in. :(

**Comment by mcmire** [comment]
@darkwing Okay, should be good, mind taking another look?

**Review by darkwing — APPROVED** [review]

**Review by georgewrmarshall — APPROVED** [review]
This soothes my soul

**Pull request merged**
