### PR TITLE
Lionbridge

### PR DESCRIPTION
**Pull request by UFCSVCLionbridge**
<Received>

### CODE REVIEW

**Comment by ryanml** [comment]
@UFCSVCLionbridge - do you intend to push more to this branch? Presently there are just some conflict markers in the diff. Thanks!

**Comment by UFCSVCLionbridge** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by UFCSVCLionbridge** [comment]
Hi, as you have rightly identified there are two users on the Lionbridge side, the first is !corpitSVCUFC user account - this ID is a Windows account (actually a service account - for automation).
The second account is UFCSVCLionbridge - this is a github account which is associated my email address and is the account used to pull, push, create pull requests etc.
So I'm surprised you actually see the !corpitSVCUFC account but unfortunately this account can't be used as a Github account, so I'm not sure how I can sign the CLA document for this user? 
Thanks, Mark.

**Comment by UFCSVCLionbridge** [comment]
Finally, would it be easier to close this Pull Request and then I could create a new Pull Request with the latest translated files as this may deal with any conflicts etc. Best regards, Mark - ufcsvclionbridge

**Comment by darkwing** [comment]
@UFCSVCLionbridge Closing this PR or rebasing works -- either way :). Thank you!

**Comment by mcmire** [comment]
Closing since 1) this has a lot of conflicts and 2) #13206 will end up conflicting with this.

**Pull request closed without merging**
