### PR TITLE
Fixing EIP-1559 V2 advance gas fee inputs validations

### PR DESCRIPTION
**Pull request by jpuri**
PR fixes issues in advance gas fee save button behaviour:

1. save button is enabled by default
2. save button gets disabled in only 2 scenario:
        1. Priority fee entered is < 1
        2. Base fee in GWEI is less than priority fee

### CODE REVIEW

**Review by NiranjanaBinoy — APPROVED** [review]
LGTM

**Review by mcmire — APPROVED** [review]

**Comment by darkwing** [comment]
InpuTerrors

The first error message seems incorrect, since it's not lower than the priority fee.

**Comment by jpuri** [comment]
@darkwing : this is bit misleading, but first input is now not value in GWEI but multiplier and the error message signifies that values in GWEI for base fee is less than priority fee.

Let me discuss this with @jakehaugen

**Comment by jakehaugen** [comment]
> this is bit misleading, but first input is now not value in GWEI but multiplier and the error message signifies that values in GWEI for base fee is less than priority fee.
> 
> Let me discuss this with @jakehaugen

Yes, this logic needs to be updated. When it's a multiplier it should validate on the GWEI amount, not the multiplier itself. 

That also means we should probably update the copy for this specific case. 

I'd propose a copy change to: `Multiplier is low relative to "Priority fee"`

When editing in GWEI, the error copy/validation logic should remain as is.

**Pull request merged**
