### PR TITLE
icon audit, remove xxs icon size

### LINKED ISSUE #16786: Icon audit updates
### Description
We recently did an audit of the `Icon` component to check any discrepancies between design and engineering. We found some updates that we can make to bring both components closer.

### Technical Details
- Remove as `xxs` a size 
- Update all icons and names to adhere to the below graphic

image

### Acceptance Criteria
- All icons match Figma in both name and style

### PR DESCRIPTION
**Pull request by garrettbear**
## Explanation

Update Icon names, remove unused icons, add missing icons, and fix icons with stroke/line issues. 

* Fixes #16786 

### Before
Screenshot 2023-01-10 at 1 37 18 PM
Screenshot 2023-01-10 at 1 37 52 PM

### After
Screenshot 2023-01-10 at 1 38 03 PM
Screenshot 2023-01-10 at 1 37 25 PM

## Manual Testing Steps

`yarn test:unit:jest ui/components/component-library`

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [x] How reviewers can test my changes
- [x] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [x] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [x] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Review by georgewrmarshall — COMMENTED** [review]
Hmm I did write the generate icons script to remove the `icon-` prefix and have it as a requirement for all icon files. I'm actually surprised it still works but now I see that it takes all svgs in the icons folder not the ones prefixed with `icon-`

Screenshot 2023-01-09 at 5 25 52 PM

**Review by georgewrmarshall — COMMENTED** [review]
I think we can also remove all the ids from the svgs files.

**Review by georgewrmarshall — COMMENTED** [review]
Everything looks great! Just one suggestion about the font awesome story

**Review by georgewrmarshall — DISMISSED** [review]

**Review by georgewrmarshall — APPROVED** [review]
LGTM!

**Review by NidhiKJha — APPROVED** [review]

**Pull request merged**
