### PR TITLE
CI - Add e2e-beta tests

### PR DESCRIPTION
**Pull request by kumavis**

### CODE REVIEW

**Comment by kumavis** [comment]
1st attempt
https://21414-42009758-gh.circle-artifacts.com/0/test-artifacts/firefox/switches%20back%20to%20Token%20Factory%20to%20grab%20the%20token%20contract%20address/test-failure-screenshot.png
https://circleci.com/gh/MetaMask/metamask-extension/21414#artifacts/containers/0
```
1) Metamask popup page
       Token Factory
         switches back to Token Factory to grab the token contract address:
     NoSuchElementError: Unable to locate element: #main > div > div > div > div:nth-child(2) > span:nth-child(3)
```

2nd attempt
https://circleci.com/gh/MetaMask/metamask-extension/21475
```
  1) MetaMask
       Add existing token using search
         can pick a token from the existing options:
     TypeError: Cannot read property 'sendKeys' of undefined
      at Context.it (test/e2e/beta/metamask-beta-ui.spec.js:395:25)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  2) MetaMask
       "after each" hook for "can pick a token from the existing options":
     TypeError: Cannot read property 'title' of undefined
      at verboseReportOnFailure (test/e2e/beta/helpers.js:47:52)
      at Context.<anonymous> (test/e2e/beta/metamask-beta-ui.spec.js:63:13)
```

**Comment by whymarrh** [comment]
Thanks, I'm looking into ways to make the network calls a bit less awful now

**Comment by whymarrh** [comment]
I'm still trying to figure out what's happening with these tests on CI

**Comment by kumavis** [comment]
@whymarrh i added a fn in e2e for capturing screen shots when a test fails and adding it to test-artifacts

maybe it will reveal a clue

**Review by whymarrh — APPROVED** [review]
LGTM, thanks a bunch @danjm this is awesome work! 🙏🏽

**Pull request merged**
