### PR TITLE
Set FONTCONFIG_PATH on CircleCI containers

### LINKED ISSUE #22564: [Bug]: CircleCI E2E test workflows intermittently get stuck in Fontconfig error loop
### Describe the bug

For the past month or so, we've been seeing that CircleCI E2E test jobs will occasionally get stuck and stay running indefinitely without ever passing. The logs form the job show the error message:

```
Fontconfig error: Cannot load default config file: No such file: (null)
```

### Expected behavior

Jobs should timeout after a reasonable timeframe if they get stuck, and this specific error should not be occurring.

### Screenshots/Recordings

_No response_

### Steps to reproduce

This happens occasionally on E2E test jobs, we don't know of a way to reliably reproduce it.

### Error messages or log output

_No response_

### Version

N/A

### Build type

None

### Browser

Other (please elaborate in the "Additional Context" section)

### Operating system

Other (please elaborate in the "Additional Context" section)

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by mcmire**
## **Description**

Some test jobs in CI occasionally fail with the following error message:

    Fontconfig error: cannot load default config file

Why this happens only occasionally is a mystery, especially considering that we are running Chromium via Chromedriver in sandbox mode. But the most common solution for this kind of problem (for example, [here](https://askubuntu.com/questions/1151094/cannot-load-config-file-from-etc-fonts-fonts-conf)) is to set the `FONTCONFIG_PATH` environment variable to point to the directory that contains the `fontconfig` configuration file. Given that context, this commit sets `FONTCONFIG_PATH` to `/etc/fonts`. I've shelled into the Docker image that we use in CI to confirm that 1) this environment variable is not set and 2) `/etc/fonts` exists.

## **Related issues**

Fixes: #22564

## **Manual testing steps**

There is no way to test this, but if this works, no jobs in CI should time out and print the error message above.

## **Screenshots/Recordings**

(None)

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by HowardBraham — APPROVED** [review]
Ooh I hope this works!

**Comment by Gudahtt** [comment]
Hmm, I thought that chrome driver was being run in sandbox mode, and that this wasn't used in sandbox mode. Not 100% sure of that though

**Comment by mcmire** [comment]
Hmm, I see. I'll look further into this.

**Comment by mcmire** [comment]
Yeah, I'm not convinced this will actually work. I'll think of a different solution.

**Comment by mcmire** [comment]
We talked about this in standup today and decided that while we aren't sure whether this will solve the problem, it's still worth it to try this. So I'm bringing this out of draft again.

**Review by DDDDDanica — APPROVED** [review]

**Comment by mcmire** [comment]
@brad-decker Would you mind taking a look at this when you get a chance?

**Review by brad-decker — APPROVED** [review]

**Comment by HowardBraham** [comment]
@mcmire it didn't work.  This example isn't on develop, and I'm testing something odd here, but the FONTCONFIG_PATH is set, and we still see `Fontconfig error: Cannot load default config file: No such file: (null)`

https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/68548/workflows/88020bbc-0a1a-49ff-b85d-d1ad194674c0/jobs/2270801/parallel-runs/16

**Comment by Gudahtt** [comment]
I found a second failure example as well: https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/69070/workflows/af75fd41-4a6b-4e6e-8242-8a1f1e3f0e78/jobs/2296019

**Pull request merged**
