### PR TITLE
Add new privacy notice.

### LINKED ISSUE #1364: Add notice to warn users to log out between uses
Until we implement #714, we should add a notice to warn users for privacy to lock metamask when visiting untrusted websites, or their current account could be known.

### PR DESCRIPTION
**Pull request by 2-am-zzz**
Fixes #1364 in addressing concerns that we are not explicit about being in developer beta. Until we can address this issue, we should alert users of potential privacy concerns when they visit certain websites.

### CODE REVIEW

**Review by tmashuang — COMMENTED** [review]
Locking Metamask also doesn't hide users account info, disabling the extension only does, I believe.

**Comment by flyswatter** [comment]
Locking does hide user account info *on new pages*, documented in #1363.

**Comment by Zanibas** [comment]
Working on #1363 right now, should be valid by the time we post this.

**Comment by Zanibas** [comment]
Verified by #1371

**Comment by kumavis** [comment]
how do we feel about the copy of this notice. also: what other notices do new users currently see?

**Comment by flyswatter** [comment]
We have a highly editable & discussable version of this notice on Quip.  I agree the intro could be a little over-sensitive.
https://consensys.quip.com/JduHAYYa0SPm

We always show new users every notice + our terms of service.  Right now that means things in [this unreadable json file](https://github.com/MetaMask/metamask-plugin/blob/master/notices/notices.json), which appears to just be our terms of service.

Maybe we should just add this to our terms of service?

I also think we should add this soon, to avoid further upset users.

**Pull request closed without merging**
