### PR TITLE
Part of #17670: Replace Typography with Text component in advanced-gas-fee-default.js and cancel-speedup-popover.js

### PR DESCRIPTION
**Pull request by dhruvv173**
## Explanation
Successfully changed the contents from Typegraphy => Text in 2 files
ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-defaults/advanced-gas-fee-defaults.js
ui/components/app/cancel-speedup-popover/cancel-speedup-popover.js

I am unable to install the dependencies to run the storybook command inorder to capture the screenshots, if anyone can help me with out that I will attach the screenshots, thanks!

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

I have read the CLA Document and I hereby sign the CLA

### CODE REVIEW

**Comment by dhruvv173** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by dhruvv173** [comment]
hey @PrgrmrHarshShukla @georgewrmarshall, this is my first time contributing to a big code base, I made the required changes but some of these CI tests are failing. Could you please help me out?
Thanks!

**Comment by georgewrmarshall** [comment]
Hey @dhruvv173, thanks for your contribution. I think a prerequisite for taking on these tasks is to get the extension running on your local and storybook up and running. @PrgrmrHarshShukla just went through this exercise and could possibly help you!

**Comment by PrgrmrHarshShukla** [comment]
Yes, @dhruvv173 ,
go through the repo readme once.
You will be able to run that locally by just following the steps given there.

If you have all the prerequisites then  `npm install`  and then  `npm run storybook` will help.

**Pull request closed without merging**
