### PR TITLE
EIP-1193: standard provider API

### PR DESCRIPTION
**Pull request by bitpshr**
This pull request adds a new inpage adapter that exposes a provider API that conforms to [EIP-1193](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1193.md).

**Note:** An 1193-compatible version of web3 will be released soon. We should wait until that's ready 
(cc @nivida) so we can update the console log in this PR to link to that version of web3 for testing. We should also draft a blog that explains why this provider API is a good thing and that it should mark the end of major breaking changes.

### CODE REVIEW

**Comment by nivida** [comment]
>  An 1193-compatible version of web3 will be released soon. We should wait until that's ready
(cc @nivida) so we can update the console log in this PR to link to that version of web3 for testing. We should also draft a blog that explains why this provider API is a good thing and that it should mark the end of major breaking changes.

I'll create a wrapper for the metamask inpage provider because I expected the EIP-1193 will be released earlier. v1.0.0-beta.38 will support the EIP-1193 and also the old metamask provider.

**Review by danfinlay — APPROVED** [review]
Looks safe, and fine.

A couple thoughts, though:

This currently would require devs who want to use the new provider to make two code changes: one to the beta API now, and one back to the main provider name once we release the breaking provider change later, before we presumably remove this `window.ethereumBeta`.

It would be nice to have a roadmap that allowed no breaking changes. Like if the new provider simply got a new namespace. I think grabbing the `ethereum` global was a slight missed opportunity in that respect.

We could also give it a more permanent sounding name than `ethereumBeta`, and embrace that we might continue supporting the old one, which should be easy to derive from the new one.

Thoughts?

Not really blocking, this is at least useful as a dev tool, but it does add global pollution, and potentially builds breaking changes into our roadmap, which are both good things to avoid if possible.

**Comment by bitpshr** [comment]
Since we eventually ([rapidly?](https://gist.github.com/bitpshr/ab17784f006a65e1211d02dc4c30f993)) planned to sunset the old provider API, I personally think it's best not to indefinitely reserve the old namespace for a dated API that (soon) won't be supported in any newly-developed dapp browser.

This is the last push towards API stability, so breaking changes after this should be few and far between (especially since everything is an RPC method now, including enablement, which is huge.)

**Comment by danjm** [comment]
This is being reworked with a different implementation.

**Comment by odanado** [comment]
Would you show a detail of the different implementation? (e.g. URL, GitHub pull-request number)

**Pull request closed without merging**
