### PR TITLE
fix: typo thai ui text

### PR DESCRIPTION
**Pull request by panapol-p**
## Explanation
I found thai word is incorrect

## Screenshots/Screencaps

image

สำเหร็จ -> สำเร็จ
แอดแดรส -> แอดเดรส
เเริ่ม -> เริ่ม
แก็ส -> แก๊ส

## Manual Testing Steps
N/A

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Comment by panapol-p** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by panapol-p** [comment]
Hi @vinistevam Could you pelase help to review this change.

**Comment by vinistevam** [comment]
> Hi @vinistevam Could you pelase help to review this change.

@panapol-p  Thank you for your contribution and sorry for the hold-up. I've asked our translation team to assist with the review and I'll let you know as soon as they reply.

**Review by Unik0rnMaggie — CHANGES_REQUESTED** [review]

**Comment by panapol-p** [comment]
@Unik0rnMaggie Thank you for the review. I have successfully updated the message krub.

**Comment by vinistevam** [comment]
That is excellent @panapol-p ! Could you update your branch to fix the pipeline? :pray:

**Comment by panapol-p** [comment]
Hi @vinistevam I have successfully updated this branch krub.

**Review by vinistevam — APPROVED** [review]

**Review by Unik0rnMaggie — APPROVED** [review]

**Comment by panapol-p** [comment]
Hi, @Unik0rnMaggie 
I've updated this branch with a rebase to address the issues related to the CI/CD test errors but it still error. Could you please review this PR again?

@vinistevam 
for this one `ci/circleci: test-e2e-mmi-playwright - OPTIONAL` can we ignore this optional test right?

**Pull request closed without merging**
