### PR TITLE
Minimal fix to the TokenSearch story to ensure it compiles and works.

### LINKED ISSUE #12932: TokenSearch story broken
**Describe the bug**
`TokenSearch` story is broken

**Steps to reproduce (REQUIRED)**
1. Go to [Metamask storybook](https://metamask.github.io/metamask-storybook/?path=/story/ui-pages-import-token-token-search-token-search-stories-js--token-search-component)
2. Search "TokenSearch" if not alread there
3. See error

**Expected behavior**
TokenSearch UI should display

**Screenshots**
Screen Shot 2021-12-01 at 9 57 21 AM

### PR DESCRIPTION
**Pull request by rojotek**
Fixes: #12932

Explanation:  
Minimal fix to the TokenSearch story.

Adds the test data list of tokens to the story.

Manual testing steps:  
  - Start the storybook server
  - open the TokenSearch story
  - http://localhost:6006/?path=/story/ui-pages-import-token-token-search-token-search-stories-js--default-story

### CODE REVIEW

**Comment by rojotek** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by georgewrmarshall — DISMISSED** [review]
Looks good to me! 💯 

- [x] verified story works on local 

If you'd like to improve this story further you could add some `argTypes` for the missing props. e.g.

```
import React from 'react';
import testData from '../../../../.storybook/test-data';
import TokenSearch from './token-search.component';

export default {
  title: 'Pages/ImportToken/TokenSearch',
  id: __filename,
  argTypes: {
    error: {
      control: 'text',
    },
    onSearch: {
      action: 'onSearch',
    },
  },
};

export const DefaultStory = (args) => {
  return <TokenSearch {...args} tokenList={testData.metamask.tokenList} />;
};

DefaultStory.storyName = 'Default';
```

**Comment by rojotek** [comment]
Thanks for the suggestion @georgewrmarshall -- I've rebased from develop to pull in the latest changes and also made the suggested improvements.

**Comment by georgewrmarshall** [comment]
@rojotek everything looks good! I'm just investigating why tests are failing.

**Review by georgewrmarshall — DISMISSED** [review]
lgtm

- [x] checked story on local

**Review by georgewrmarshall — APPROVED** [review]
lgtm!

**Review by digiwand — COMMENTED** [review]
REQ: We can pass `tokenList` as an argType. This will enable the readers to see and update the list of tokens while they are testing the search feature.

**Review by jpuri — APPROVED** [review]

**Pull request merged**
