### PR TITLE
Improve confirm screen tests

### PR DESCRIPTION
**Pull request by danjm**
This makes our tests around displayed recipients on the confirm screen more robust.

### CODE REVIEW

**Review by Anastasia1510 — DISMISSED** [review]

**Comment by darkwing** [comment]
Is this test failure legit?

**Review by brad-decker — APPROVED** [review]

**Comment by seaona** [comment]
@danjm tried again and it's working fine in my end! QA pass

**Review by ryanml — APPROVED** [review]
++

**Comment by seaona** [comment]
@danjm  sorry I just realized that when we perform the send from the Dapp, it no longer appears on the activity Tab :/ do you think might be some side- effect there?

https://user-images.githubusercontent.com/54408225/178533004-c23dcd9c-eeac-44e2-8115-c95190fd38b6.mp4

**Pull request merged**
