### PR TITLE
Prevent error messages from leaking into other views

### LINKED ISSUE #1192: Error message state persists when password is incorrect
Will post a picture here. Reproduced by typing an incorrect password into the lock screen, or generating any error from either the lock screen or the first-time screen, and then visiting either settings, buy, lock again, QR code, forgotten password, import key. The only place it does NOT persist an error (correct behavior) is the send screen.

### PR DESCRIPTION
**Pull request by 2-am-zzz**
Fixes #1192 by enforcing clearing the error state during each view transition. However, there could be a cleaner way to implement this, perhaps by differentiating between actions that are responsible for shifting views vs actions that do not.

### CODE REVIEW

**Comment by flyswatter** [comment]
I have a slight concern about this behavior, and I think there might be a better solution we should consider:

During a view transition, a smooth animation depends on having the incoming and outgoing views keeping consistent state throughout the entire transition.

If a view has an error message, and is then navigated away from, that error message is holding the template in its position during the animation.

If we remove error messages before all view transitions, every single animation from a view that has an error will have a jerky moment.

I know our animations aren't all perfect as it is, but I think we should avoid introducing jerkiness when possible.

A better solution would be to keep different views' error states on different state keys, so they don't render in other views.  I might prefer that approach entirely to this one.

**Review by danfinlay — CHANGES_REQUESTED** [review]
I'm going to go ahead and block this pending some discussion of the strategy to preserve transition animations.

**Comment by Zanibas** [comment]
Should we have a warnings reducer then, that just handles all the different warnings? It'd keep the state tree fairly clean and allow us to manage different error keys.

However, this still seems like a weird solution--we shouldn't have to manage more than two warning keys at any one time. A lot of extra code for what should be a simple fix somehow...

**Comment by flyswatter** [comment]
The problem is just kinda a weird react issue:  We remove state while some of it is stlil being rendered on screen.

I think a warnings reducer isn't the worst idea, OR the appState should actually have a views reducer, so views can have their own global states, like warnings.

OR we should try to do more warning-triggering things at the component level, so it can just be managed by component state, and doesn't have to be managed by the global app state.

In the short term, I don't know which I like more:
- Avoiding warning leaks.
- Protecting transition smoothness.

I guess the first one is more functionally important, but transition smoothness is such a nice thing, I really hate compromising it.

**Pull request closed without merging**
