### PR TITLE
Upgrade chromedriver to 93

### PR DESCRIPTION
**Pull request by mcmire**
This allows developers to run the Chrome e2e tests locally without
having to have a custom version of Chrome installed.

### CODE REVIEW

**Comment by Gudahtt** [comment]
The upstream PR appears to have been merged and released

**Comment by mcmire** [comment]
@Gudahtt Ok cool I'll revisit this then!

**Comment by mcmire** [comment]
You can test this out by running one of the Chrome e2e locally - if this works then it's good to go.

**Review by PeterYinusa — APPROVED** [review]

**Review by brad-decker — APPROVED** [review]
LGTM

**Pull request merged**
