### PR TITLE
MetaMorph - Spacing and Typeface on Extension Main view

### PR DESCRIPTION
**Pull request by chikeichan**
Screen Shot 2019-05-08 at 2 46 08 PM

### CODE REVIEW

**Comment by chikeichan** [comment]
Few questions for you @cjeria :

- seondary balance, the word "History", and transaction nonce are currently using `font-weight: normal` (which is 400) according to Figma, but visually it looks more like `font-weight: 300`. Is there is difference between the Roboto font package we are using? Should I adjust to `300`?

- I cannot match most of the color hex on the color palette. On this [mock](https://www.figma.com/file/bVODFA3EVcnHuoD3mdHAyLCZ/Wallet-home-screen?node-id=1%3A2), i see that these grays are deviation from color palette: `#989A9B`, `#9B9B9B`, `#24292E`, `5B5D67`, and `#E5E5E5`. These are the closest I can find on color palette: `#9fa6ae`, `#24272a`, `#535a61`. Are the deviation intentional? 

- I cannot quite tell what the jazzicon should be aligned to, so I center aligned it vertically based on container height. Let me know if this is what you have in mind.

**Review by danjm — DISMISSED** [review]

**Comment by cjeria** [comment]
@chikeichan 
> secondary balance, the word "History", and transaction nonce are currently using font-weight: normal (which is 400) according to Figma, but visually it looks more like font-weight: 300. Is there is the difference between the Roboto font package we are using? Should I adjust to 300?

It's set to font-weight: normal (400) so let's keep it at 400. 

> I cannot match most of the color hex on the color palette. On this mock, i see that these grays are deviation from color palette: #989A9B, #9B9B9B, #24292E, 5B5D67, and #E5E5E5. These are the closest I can find on color palette: #9fa6ae, #24272a, #535a61. Are the deviation intentional?

No deviations. All colors should be consistent with the colors defined in the design system. I've made changes accordingly in the mockup. 

> I cannot quite tell what the jazzicon should be aligned to, so I center aligned it vertically based on container height. Let me know if this is what you have in mind.

The Jazzicon should have 16px padding around it. See screenshot:
image

**Comment by cjeria** [comment]
@chikeichan 
image

**Comment by chikeichan** [comment]
Screen Shot 2019-05-20 at 6 05 08 PM

Ready for review @cjeria !

**Review by cjeria — COMMENTED** [review]
Looks good to me!

**Comment by Flahe** [comment]
Thank youSent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Christian <notifications@github.com> Date: 5/21/19  5:30 PM  (GMT-05:00) To: MetaMask/metamask-extension <metamask-extension@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [MetaMask/metamask-extension] MetaMorph - Spacing and Typeface on
  Extension Main view (#6584) @cjeria commented on this pull request.

Looks good to me!

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/MetaMask/metamask-extension/pull/6584?email_source=notifications\u0026email_token=ALNXKRG4XHELQA4644CDG2TPWRSXHA5CNFSM4HLVPSD2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOBZJNTAY#pullrequestreview-240310659",
"url": "https://github.com/MetaMask/metamask-extension/pull/6584?email_source=notifications\u0026email_token=ALNXKRG4XHELQA4644CDG2TPWRSXHA5CNFSM4HLVPSD2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOBZJNTAY#pullrequestreview-240310659",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Review by danjm — APPROVED** [review]

**Pull request merged**
