### PR TITLE
fix: Update Moonbeam & Moonriver Logos

### PR DESCRIPTION
**Pull request by albertov19**
## **Description**

Updates the Moonbeam/Moonriver logos following the new [brand guidelines](https://guidelines.moonbeam.foundation)

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/25267?quickstart=1)

## **Related issues**

N/A

## **Manual testing steps**

I've built Metamask locally to confirm logo dimensions

### **Before**

image

### **After**

image

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by albertov19** [comment]
Woud be great to also update token logos for these. Thanks!

GLMR_Square
MOVR_Square

**Comment by albertov19** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by albertov19** [comment]
Any updates here ? Simple PR to update logos

**Comment by sahar-fehri** [comment]
> Woud be great to also update token logos for these. Thanks!
> 
> GLMR_Square MOVR_Square

Hi @albertov19 ! where can i find the svg for these token logos?

**Comment by sahar-fehri** [comment]
Hey @albertov19 !
I have created this PR based on your changes that also updates the logos: https://github.com/MetaMask/metamask-extension/pull/26677 ; could you have a look and approve it if it looks good? 🙏

**Comment by albertov19** [comment]
> Hey @albertov19 ! I have created this PR based on your changes that also updates the logos: #26677 ; could you have a look and approve it if it looks good? 🙏

Looks great! Thanks for working on this

**Comment by sahar-fehri** [comment]
Closing this one after merging https://github.com/MetaMask/metamask-extension/pull/26677

**Pull request closed without merging**
