### PR TITLE
feat: upgrade eth-ledger-bridge-keyring to version 4.1.0

### PR DESCRIPTION
**Pull request by dawnseeker8**
## **Description**
This PR will upgrade to use latest @metamask/eth-ledger-bridge-keyring library in metamask extensions.
This PR also update the axios library to fix vulnerability alert. and update relevant policy files 

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/26364?quickstart=1)

## **Related issues**

Fixes:

## **Manual testing steps**

Area to test:

1. connect ledger
2. send transaction
3. sign message (eth_sign, personal_sign, typedSignData v4)
4. Swap with ledger

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by dawnseeker8** [comment]
> * @SocketSecurity ignore npm/axios@1.7.3

@SocketSecurity ignore npm/axios@1.7.3

**Comment by dawnseeker8** [comment]
> **🚨 Potential security issues detected.** Learn more about [Socket for GitHub ↗︎](https://socket.dev?utm_medium=gh)
> 
> To accept the risk, merge this PR and you will not be notified again.
> 
> Alert	Package	Note	Source	CI
> [ Network access ](https://socket.dev/npm/package/axios/alerts/1.7.3?alert_name=networkAccess)	[ npm/axios@1.7.3 ](https://socket.dev/npm/package/axios/overview/1.7.3)	
> * **Module:** globalThis["fetch"]
> * **Location:** [Package overview](https://socket.dev/npm/package/axios/overview/1.7.3)
> 
> * [`package.json`](https://github.com/MetaMask/metamask-extension/pull/26364/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519)
> * [`yarn.lock`](https://github.com/MetaMask/metamask-extension/pull/26364/files#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2de)
> 
> 🚫
> [**View full report↗︎**](https://socket.dev/dashboard/org/MetaMask/diff/d34334ce-da07-4b67-b518-91fa01776630/9ac85979-746e-49ef-b3ef-ea2f304798b9)
> 
> ### Next steps
> ** What is network access? **
> ** Take a deeper look at the dependency **
> ** Remove the package **
> **Mark a package as acceptable risk**

@SocketSecurity ignore npm/axios@1.7.3

**Comment by Khalilheyrani6367** [comment]
Thanks 🙏

**Comment by legobeat** [comment]
@dawnseeker8 Any updates or blockers on this?

**Comment by dawnseeker8** [comment]
This PR is not valid anymore since @mikesposito has created another PR to upgrade library to 5.1.0 
the PR link is #27688

**Pull request closed without merging**
