### PR TITLE
Autofocus the currency input when sending tokens

### PR DESCRIPTION
**Pull request by darkwing**
This focuses the user on the send screen's value input -- saves a click!

### CODE REVIEW

**Review by Gudahtt — COMMENTED** [review]
So the only hesitation I have here is that the `CurrencyInput` component was at one point used in a few different places, some of which may have multiple fields competing for auto-focus. Is this the right level to add this prop? :thinking: 

I think it's only used in this single place right now though. And it's wrapped in `UserPreferencedCurrencyInput` and `UserPreferencedTokenInput` respectively, so it'd be a bit of a pain to pass through an `autoFocus` prop.

**Comment by darkwing** [comment]
OK, cool, thank you for the additional background; I'll close for now and rethink!

**Comment by Gudahtt** [comment]
It would be pretty safe to pass that prop down though for now, just to be safe. Or we could consider using the `useUserPreferencedCurrency` hook and getting rid of our use of those intermediary components (iirc @brad-decker was advocating that we deprecate them in favour of this hook)

**Comment by brad-decker** [comment]
Yeah, though refactoring all of the places we use them to be able to use hooks might be a challenge (either a fun one or a not-so-fun one)

**Comment by Gudahtt** [comment]
That's the thing though - `UserPreferencedCurrencyInput` and `UserPreferencedTokenInput` are only used in once place - the send flow. It should be quite easy to get rid of. It's `UserPreferencedCurrencyDisplay` that we use all over the place.

**Pull request closed without merging**
