### PR TITLE
Support CoolWalletS hardware wallet

### LINKED ISSUE #7569: Support CoolWalletS hardware wallet.
**What problem are you trying to solve?**
Support [CoolWalletS](https://www.coolwallet.io/) hardware wallet. 
I have been putting some efforts on the integration and want to see if the integration seems okay to the team. Please let us know what you think, how can we improve or any other feedbacks are welcomed.

**Describe the solution you'd like**
We plan to release a [CoolWalletS Bridge](https://coolwallets-connect.herokuapp.com/) webpage like TrezorConnect, and use it as a bridge to establish bluetooth connection and to communicate with the hardware wallet. If the wallet is empty or the user has not register the webApp to the card before, this page will help the user setup/register/reset. 

**Additional context**
What we have so far:
* A [eth-coolwallets-keyring](https://github.com/antoncoding/eth-cws-keyring)
* A [fork of MetaMask](https://github.com/antoncoding/metamask-extension) wrapping the keying.
* continuous development on **CoolWalletS Bridge**

Some screenshots from what we already have:

### Signing Tx

Our wallet also support signing message and typedData, the screenshots look similar so I'll skip it for know.

Please let us know if you think this integration is feasible, also some feedback on how can we improve. Thanks a lot

### PR DESCRIPTION
**Pull request by antoncoding**
Hi Team, we have implemented the CoolWalletS integration. Please let us know if this is feasible, or how can we improve to push this to production.

### eth-coolwallet-keyring
- [x] eth-coolwallet-keyring tests with full coverage
- [ ] move [eth-coolwalllet-keyring](https://github.com/antoncoding/eth-cws-keyring) inside metamask org

### UI
- [ ] Replace the current link to coolwallet.io with an affiliate link.

Fix #7569

### CODE REVIEW

**Comment by whymarrh** [comment]
> Hi Team, we have implemented the CoolWalletS integration. Please let us know if this is feasible, or how can we improve to push this to production.

Thanks for opening this—is there an open issue for this?

**Comment by antoncoding** [comment]
> 
> Thanks for opening this—is there an open issue for this?

We opened this issue months back. #7569

**Comment by whymarrh** [comment]
I appreciate you opening that first. I'll say here [the same thing I said to the TrustVault team](https://github.com/MetaMask/metamask-extension/pull/7712#issuecomment-599551623): there is a good bit of code here that we'll have to review & maintain going forward (in `eth-cws-keyring`) and we're already working on getting a large major version out the door ([`v7.7.8...develop`](https://github.com/MetaMask/metamask-extension/compare/v7.7.8...develop)). With that, this is unfortunately a lower priority for us right now—we'll be sure to update you here when this is on our radar.

**Comment by antoncoding** [comment]
>  With that, this is unfortunately a lower priority for us right now—we'll be sure to update you here when this is on our radar.

Of course! Totally get it. Please let us know when you guys have extra bandwidth on this.

**Comment by darkwing** [comment]
Thank you for the contribution @antoncoding !  At this time we prefer not to accept more USB-based hardware wallet solutions.  If that changes, we'll be sure to let you know.  Thank you!

**Pull request closed without merging**
