### PR TITLE
background - introduce ObservableStore (mark II)

### PR DESCRIPTION
**Pull request by kumavis**
Updates #979
Updates #847
Updates #850

### CODE REVIEW

**Comment by kumavis** [comment]
Examining the multivault migration process:
```
// Migration Map

metamaskController.submitPassword
  metamaskController.migrateOldVaultIfAny
    
    metamaskController.checkIfShouldMigrate // confusing state lookups
    
    idStoreMigrator.migratedVaultForPassword(password)
      idStore.submitPassword
      idStore.serializeVault
      idStore.checkForLostAccounts -> { serialized, lostAccounts }
    
    metamaskController.restoreOldVaultAccounts
      keyringController.restoreKeyring(serialized) // add new hd keyring
    
    metamaskController.restoreOldLostAccounts
      configManager.setLostAccounts(lostAddresses) // persist lost addresses. why?
    
      metamaskController.importLostAccounts
        keyringController.restoreKeyring({ type: 'Simple Key Pair', data: privKeys })

    keyringController.persistAllKeyrings(password) // finish up
```

**Comment by kumavis** [comment]
damnit, just realized the multiVault migration requires a password to unlock before migrating

**Comment by kumavis** [comment]
Alright, I experimented with moving the multiVault migration out to the new promise-based migrations.

It would work except that we need to unlock the vault to perform the migration.

That made me realize that:
 - our locked state has a lot of plaintext information available
 - we need to be cautious about what we are pushing into our data store
 - perhaps we should be performing migrations after we unlock the account

**Comment by kumavis** [comment]
I know this PR grew rather massive, but I feel like it is progress towards cleaner arrangement of the good stuff we already have. I'm open to pushing dev->master, publishing, and continuing this refactor

**Comment by kumavis** [comment]
some goals:
- [x] invert persistence ( controller state updates trigger persistence updates )
- [ ] break out multiVault migration as much as possible
- [ ] minimalize background.js
- [ ] clean up controllers (e.g. remove migration code from metamaskController)
- [ ] migrate off of configManager to composed obs-stores
- [ ] generalize and test obs-stores (change api to match redux store?)

**Comment by kumavis** [comment]
This is pending some conflict resolution and obs-store improvements from me

**Review by frankiebee — APPROVED** [review]

**Pull request merged**
