### PR TITLE
Part of #17670: Replace Typography with Text component for 'review-spending-cap' & 'tooltip.stories'.

### PR DESCRIPTION
**Pull request by PrgrmrHarshShukla**
## Explanation
This PR is a part of the issue #17670 Replace Typography with Text component for 2 files:

1. ui\components\ui\review-spending-cap\review-spending-cap.js
2. ui\components\ui\tooltip\tooltip.stories.js

### Before
Screenshot (55)

Screenshot (56)

### After
Screenshot (57)

Screenshot (58)

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Comment by georgewrmarshall** [comment]
Hey @PrgrmrHarshShukla, I really appreciate your enthusiasm with contributions! It would be great if all of your PRs could meet the Acceptance Criteria stipulated in the issue https://github.com/MetaMask/metamask-extension/issues/17670. This will help your PRs get reviewed and ensure that we aren't breaking anything in the UI. Unless all the acceptance criteria is met your PR may be closed.

Adding before and after screenshots will require you to get the extension running on your local. Are you being assisted with this?

Screenshot 2023-04-27 at 8 51 04 AM

**Comment by PrgrmrHarshShukla** [comment]
> Hey @PrgrmrHarshShukla, I really appreciate your enthusiasm with contributions! It would be great if all of your PRs could meet the Acceptance Criteria stipulated in the issue #17670. This will help your PRs get reviewed and ensure that we aren't breaking anything in the UI. Unless all the acceptance criteria is met your PR may be closed.
> 
> Adding before and after screenshots will require you to get the extension running on your local. Are you being assisted with this?


Hey @georgewrmarshall , @legobeat ,

The extension is running locally.
I will make sure that I add before and after screenshots in my PRs.

I will add them in the open PRs wherever possible.

I have added the screenshots in many PRs, 
but some of the files could not be found 
neither in the main link you sent [here](https://metamask.github.io/metamask-storybook/) nor in my local setup.🤷‍♂️

What should I do for them?

Thank you ❤️

**Comment by PrgrmrHarshShukla** [comment]
Hey @georgewrmarshall ,
I have added the before and after screenshots in this PR.

Apologies for not adding any in PR #18837 🙏🏼
Will keep this in mind for future PRs.

Regards.

**Review by georgewrmarshall — APPROVED** [review]
LGTM! Great PR description! Help a lot with review. Thank you for your contribution 🙏

**Review by NidhiKJha — APPROVED** [review]
LGTM

**Pull request merged**
