### PR TITLE
feat: QR-based add OneKey Hardware

### PR DESCRIPTION
**Pull request by ByteZhang1024**
## **Description**

Hello, this is the OneKey team.

Our recently released OneKey Pro hardware now supports the EIP-4527 connection method and prioritizes the display of the MetaMask connection method.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/24492?quickstart=1)

## **Related issues**

Fixes:

## **Manual testing steps**

1. On your hardware wallet, fetch the QR code for MetaMask
2. Proceed to add hardware wallet from the account drop-down selector
3. Select QR-based and Continue
4. Scan the QR code from the hardware wallet
5. user should be able to select QR code account and imported

OneKey Hradware Tutorial Documentation: https://help.onekey.so/hc/articles/9426592069903

## **Screenshots/Recordings**

https://github.com/MetaMask/metamask-extension/assets/92281880/a66a8538-2f24-403a-b9d4-163ecec46c02

### **Before**
image

### **After**

SCR-20240511-jvbr

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by ByteZhang1024** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by dawnseeker8 — DISMISSED** [review]
LGTM

**Comment by dawnseeker8** [comment]
Has tested with imported with AirGap Vault (`since OneKey is airGap compatible`) with importing accounts, connect to dapp, personal sign, Typed sign data v4, send EIP1557 transactions and confirm they all work ok.

**Review by dawnseeker8 — DISMISSED** [review]
LGTM

**Review by dawnseeker8 — APPROVED** [review]

**Review by DDDDDanica — APPROVED** [review]

**Comment by DDDDDanica** [comment]
LGTM ! Thank you !

**Comment by vivek-consensys** [comment]
OneKey added to the QR-based hardware list:
image

**Pull request merged**
