### PR TITLE
Add token list to token details page

### LINKED ISSUE #13952: Add token list to token details page
Add the token list/aggregator to the token details page.

Screen Shot 2022-03-14 at 10 15 19 PM

### PR DESCRIPTION
**Pull request by NiranjanaBinoy**
Fix #13952 

Add the token list/aggregator to the token details page.

Screen Shot 2022-03-18 at 2 54 22 PM

(Note: The token list data will be updated to match the design when the controller changes are merged.)

### CODE REVIEW

**Comment by popeda97** [comment]
tkn-dtcn-token-details

**Comment by popeda97** [comment]
#1661

**Review by popeda97 — CHANGES_REQUESTED** [review]
#14053

**Review by AymericNoel — DISMISSED** [review]

**Review by popeda97 — CHANGES_REQUESTED** [review]
tkn-dtcn-token-details

**Review by jpuri — DISMISSED** [review]

**Review by georgewrmarshall — DISMISSED** [review]
UI LGTM! Nailing the use of the new design token colors 💯

**Review by georgewrmarshall — APPROVED** [review]
UI LGTM!

**Review by adonesky1 — APPROVED** [review]
LGTM!

**Pull request merged**
