### PR TITLE
Make minified builds determinstic

### LINKED ISSUE #3999: Get builds reproducible enough for Firefox to resume accepting
Mozilla has increased the strictness of their addon acceptance, and now requires that the source code we provide reliably produce exact matches of our submitted built addon.

Our build is not perfectly deterministic, it varies slightly on different platforms.

This is very bad for our Firefox support, and so we have a lot of bugs on Firefox that have been fixed on `master`.

This issue represents the urgent need to resume our ability to publish to Firefox's addon store.

### PR DESCRIPTION
**Pull request by danfinlay**
May fix #3999, but will need to see if Mozilla can reproduce the build
with this updated repo.

Investigated a bit, looks very likely that [browserify non-determinism](https://github.com/browserify/browserify/issues/1796) is caused by [a bug in uglifyify](https://github.com/hughsk/uglifyify/issues/64) that deletes options flags when they pass through the transform.

There seems to be a good fix for it in [this PR](https://github.com/hughsk/uglifyify/pull/62), but it's been sitting around for nearly a year, so I don't expect it merged any time soon.

We should probably move to a different minification strategy, but in the meanwhile, I've merged that patch into my own branch at danfinlay/uglifyify#keep-flags, so we can install from that and have control of our source, I can also move that into the MetaMask org.

Another fix could be to remove minification, but I know that could increase our bundle size beyond what Mozilla accepts (oh, the irony, that their requirements caused us to breach them!)

### CODE REVIEW

**Comment by lazaridiscom** [comment]
> but it's been sitting around for nearly a year

The project could be rated as "unmaintained", although downloads are quite high (30k / week):

https://www.npmjs.com/package/uglifyify

Possibly the way to go here to look what other projects use to minify, and adopt this other tool.

Or to ask the maintainers to give MM maintenance access rights.

Not really sure here.

**Review by ghost — COMMENTED** [review]
This should get possibly its own full QA pass.

(intentionally not approving, to avoid getting *(@*&^( from tools/QA)

**Comment by danfinlay** [comment]
Note to QA: To QA this branch, you need to minify, which means doing a full `npm run dist` type production build, the `npm start` dev-environment does not pass through uglifyify, so that does not test this PR.

**Comment by danfinlay** [comment]
I've moved the module to the MetaMask org and protected the branch, requiring a review for any merge to that branch.

**Pull request merged**
