### PR TITLE
select current address in permissions connect

### PR DESCRIPTION
**Pull request by brad-decker**
When initiating a permissions request, automatically select the
currently selected account in the metamask UI.

### CODE REVIEW

**Comment by brad-decker** [comment]
[Have my current account selected by default](https://trello.com/c/aufCAmR6/81-have-my-current-account-selected-by-default)

**Comment by brad-decker** [comment]
I'll make this a high priority item for tomorrow morning.

**Comment by Gudahtt** [comment]
I think I know why the tests are failing - I can push up a fix.

**Comment by brad-decker** [comment]
Thanks @Gudahtt

**Review by Gudahtt — APPROVED** [review]
LGTM!

**Review by rekmarks — APPROVED** [review]

**Pull request merged**
