### PR TITLE
Interacting with MetaMask Notification window

### PR DESCRIPTION
**Pull request by PeterYinusa**
Fixes: Intermittent test failure `Error: No window with title: MetaMask Notification`

Explanation:  Switching to the MetaMask Notification is flaky on CI.
After running the tests locally using Docker, I noticed the title of the MetaMask Notification window is not returned consistently on the first attempt.

Manual testing steps:  
  - n/a

### CODE REVIEW

**Review by brad-decker — DISMISSED** [review]
🙌🏻

**Comment by PeterYinusa** [comment]
Update: I had to update a few tests to ensure we are not passing a stale list of window handles

**Review by brad-decker — APPROVED** [review]
LGTM

**Review by danjm — APPROVED** [review]
:raised_hands:

**Pull request merged**
