### PR TITLE
Version v11.7.5

### PR DESCRIPTION
**Pull request by danjm**

### CODE REVIEW

**Comment by danjm** [comment]
https://github.com/SocketSecurity ignore-all

The "new author" of the package mentioned is https://github.com/ljharb, and he is legit

**Comment by danjm** [comment]
@SocketSecurity ignore-all

The "new author" of the package mentioned is https://github.com/ljharb, and he is legit

**Comment by chloeYue** [comment]
Tested Wallet Chat snap and Wallet Guard snap on latest Chrome Canary. And also some basic send token and deploy contract functionalities. QA passed!

**Comment by danjm** [comment]
Chloe and I tested with success on Chrome Beta and Chrome Canary

**Pull request merged**
