### PR TITLE
Auto logout after specific time

### PR DESCRIPTION
**Pull request by chikeichan**
auto

Couple Notes:
- In the screen cap, timer is set to respond in *seconds* instead of *minutes* for the sake of time
- `react-idle-timer` is fairly actively maintained -> 20+ commits within last 6 months. I think the risk is trivial, but I am open to refactoring into our own idle-timer module.

- [x] unit test
- [x] fix/update integration test

### CODE REVIEW

**Review by danjm — DISMISSED** [review]
This code looks good to me. We should get at least one QA at a longer time before merging.

I will re-review once test changes are made.

**Review by danjm — APPROVED** [review]

**Review by danjm — CHANGES_REQUESTED** [review]
@chikeichan It seems the necessary changes to `advanced-tab.container.js` have been removed from this PR. For instance, `setAutoLogoutTimeLimit` is not defined anywhere

**Comment by chikeichan** [comment]
> @chikeichan It seems the necessary changes to `advanced-tab.container.js` have been removed from this PR. For instance, `setAutoLogoutTimeLimit` is not defined anywhere

wow, let me check on this later today. Thanks for pointing this out

**Review by danjm — APPROVED** [review]
looks good now

**Pull request merged**
