### PR TITLE
Network Form Design and switch to full screen enhancements

### LINKED ISSUE #12089: Custom network form updates: update custom network designs
After https://github.com/MetaMask/metamask-extension/issues/11958, update the designs in accordance with this figma https://www.figma.com/file/qZEgGoI7Z9fDLJpuzI0fwZ/Filling-out-the-custom-network-form?node-id=308%3A867

### PR DESCRIPTION
**Pull request by NiranjanaBinoy**
Fixes: #12089 #11958 

Explanation:  
Filling out the custom network form is painful because the extension popup will collapse and lose state. 
With this new design upon clicking the Add Network buttons from the Network tab in pop up and fullscreen subheader and the custom RPC from the network dropdown, a new browser window will open with the new Network form saving the user from losing the state every time they move away want to reconfirm the details they are entering.

Manual Testing:

- Navigation:

> 
> 1. In the extension popup, navigate to settings >> network tab>> click `Add Network`
> 2. In Fullscreen mode, navigate to settings >> network tab>> click `Add Network` in the subheader
> 3. In the network dropdown, click `custom RPC` in the network dropdown.

- Network form will open in a new browser open.
- After entering the details, upon clicking the save button the network details will be saved and the user will be taken back to the home page, and a green message appears in the right-hand corner of the page indicating which network is added.
- If the user clicks the `cancel` button or `X` at the top right corner, the user will be taken to the Network tab with details of the current tab displayed in the existing Network form.

### CODE REVIEW

**Review by jpuri — DISMISSED** [review]
Changes look good, a small comment added.

**Review by jpuri — DISMISSED** [review]

**Review by jpuri — DISMISSED** [review]

**Review by adonesky1 — CHANGES_REQUESTED** [review]
A few questions/requests

**Review by jpuri — DISMISSED** [review]
LGTM

**Review by adonesky1 — DISMISSED** [review]
LGTM! Great work

**Review by darkwing — DISMISSED** [review]

**Review by darkwing — APPROVED** [review]

**Review by adonesky1 — APPROVED** [review]

**Pull request merged**
