### PR TITLE
feat: Remove powered by blockaid line

### PR DESCRIPTION
**Pull request by segun**
## **Description**

Removing the "powered by Blockaid" line

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/23484?quickstart=1)

## **Related issues**

Fixes: [#2196](https://github.com/MetaMask/MetaMask-planning/issues/2196)

## **Manual testing steps**

1. Launch MM
2. Open testdapp
3. Click any malicious transaction under PPOM section
4. See the powered by blockaid line
5. Checkout this branch
6. Repeat 1-3
7. See there's no powered by blockaid line

### **Before**
image

### **After**
Screenshot 2024-03-18 at 17 49 55

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by cryptotavares — DISMISSED** [review]

**Comment by SayaGT** [comment]
Can we please fix the padding at the bottom of the banner? Here is [Figma file for reference](https://www.figma.com/file/Q69vHaA7Or7Rxz4vdzjVHC/Support-for-tx-security-providers-(MVP)?type=design&node-id=7293%3A41417&mode=design&t=L3S936pcK4RIVrFB-1)

**Comment by segun** [comment]
> Can we please fix the padding at the bottom of the banner? Here is [Figma file for reference](https://www.figma.com/file/Q69vHaA7Or7Rxz4vdzjVHC/Support-for-tx-security-providers-(MVP)?type=design&node-id=7293%3A41417&mode=design&t=L3S936pcK4RIVrFB-1)

@SayaGT I've reduced the margin as much as I can, but I also noticed that there's a margin of 12px in the disclosure component.
```
.disclosure {
  margin: 12px 0;  
```
Hence the margin that we still see now.

**Comment by SayaGT** [comment]
@segun the top padding looks too tight now in the screenshot above. Can you please check if it has changed?

**Review by digiwand — APPROVED** [review]
code LGTM!

**Review by cryptotavares — APPROVED** [review]

**Pull request merged**
