### PR TITLE
chore: bump  assets controllers to latest

### PR DESCRIPTION
**Pull request by sahar-fehri**
## **Description**

Bumps assets-controllers to latest.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/24360?quickstart=1)

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by sahar-fehri** [comment]
@metamaskbot update-policies

**Review by bergeron — DISMISSED** [review]

**Comment by legobeat** [comment]
`@metamask/assets-controllers` has a peerDependency on `@metamask/account-controllers`.

Before this change, the direct dependency version of `@metamask/account-controllers` satisfies the peerDependency requirement. This change will break it. Also upgrading `@metamask/account-controllers` from `^11.0.0` to `^14.0.0` would resolve it.

I haven't looked closer than this, but I would think that there is something behind the peerDependency bumps?

Is it actually safe, or should `@metamask/account-controllers` also be upgraded alongside?

**Review by salimtb — DISMISSED** [review]

**Comment by sahar-fehri** [comment]
> `@metamask/assets-controllers` has a peerDependency on `@metamask/account-controllers`.
> 
> Before this change, the direct dependency version of `@metamask/account-controllers` satisfies the peerDependency requirement. This change will break it. Also upgrading `@metamask/account-controllers` from `^11.0.0` to `^14.0.0` would make them align again.
> 
> I haven't looked closer than this, but I would think that there is something behind the peerDependency bumps?
> 
> Is it actually safe, or should `@metamask/account-controllers` also be upgraded alongside?

Hey @legobeat ! that's a good point! I think i expected to see build errors or errors in console extension/background if a peer dependency needed an upgrade, i have tested this PR locally and i do not see any errors. 
I see the changelog in core marked accounts-controller v14.0.0 as [breaking](https://github.com/MetaMask/core/blob/main/packages/assets-controllers/CHANGELOG.md#added) but maybe it does necessarily need an update?

**Comment by sahar-fehri** [comment]
@metamaskbot update-policies

**Comment by mcmire** [comment]
I just checked through the changes in the peer dependencies that `assets-controllers` has, and most of them are type-related, so they don't have an impact here. It seems that we can address those upgrades in a separate PR.

**Review by bergeron — APPROVED** [review]

**Review by darkwing — APPROVED** [review]

**Review by salimtb — APPROVED** [review]

**Review by mcmire — APPROVED** [review]
Looks good!

**Pull request merged**
