### PR TITLE
Handle Promise rejections when importing accounts

### LINKED ISSUE #4141: Unhandled Promise rejection: Private key does not satisfy the curve
This is a common exception reported to Sentry. The UI should properly catch promises when calling actions associated with account importing.

### PR DESCRIPTION
**Pull request by bitpshr**
This PR catches Promise rejections from the action used to import a new account (see the associated Sentry report [here](https://sentry.io/metamask/metamask/issues/505549706/?query=is:unresolved)). Thrown errors during account import are already dispatched to Redux and shown on the UI in each component that uses the action, so rejections in the components themselves just needed to be no-ops to appease the JS runtime.

Resolves #4141

### CODE REVIEW

**Comment by kumavis** [comment]
this approach makes me nervous

**Comment by kumavis** [comment]
id rather not throw rejections when we handle the error than catch things silently

**Comment by bitpshr** [comment]
@kumavis Calls to the `importNewAccount` are chained in a few places. If we rely on Redux error handling and simply short-circuit the action after dispatching an error action, these chained uses of the action could (and most likely will) break since their `then` callbacks will be called when they shouldn't be. It looks like that's the whole reason the codebase is rejecting these specific Promises when other asynchronous actions that aren't ever chained are simply short-circuited like we're talking about.

"Silently catching" was poor phrasing on my part. If anything, we're properly rejecting the Promise as we should be and catching rejections like the JS runtime requires. We just happen to not do anything when we catch this specific rejection because it's already handled via Redux upstream.

**Review by kumavis — APPROVED** [review]
- [x] comment silent catch
- [x] move catch above `then`

**Pull request merged**
