### PR TITLE
deps - bump json rpc engine for bugfix

### PR DESCRIPTION
**Pull request by kumavis**
relevant diffs
https://github.com/kumavis/json-rpc-engine/commit/3e6844f2c0754eb47b1acc78aca5f13c8f009127

### CODE REVIEW

**Comment by kumavis** [comment]
got this in CI (?)
```
	Actual: {
	  "message": "buyEthTitle is undefined",
	  "name": "TypeError"
	}
```

**Comment by danfinlay** [comment]
I guess you re-ran tests and they passed?

**Comment by kumavis** [comment]
yeah thats correct

**Review by danfinlay — APPROVED** [review]
Reviewed code & tried it out, both look good, thank you!

**Pull request merged**
