### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by thickforest**
descrption -> description

### CODE REVIEW

**Comment by thickforest** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by jpuri — DISMISSED** [review]

**Review by NiranjanaBinoy — DISMISSED** [review]

**Comment by thickforest** [comment]
@NiranjanaBinoy  Sorry for clicked the refresh button.

**Comment by brad-decker** [comment]
@thickforest can I get you to rebase this from the latest develop to fix those failing CI steps :)

**Review by brad-decker — APPROVED** [review]

**Review by darkwing — APPROVED** [review]

**Comment by darkwing** [comment]
Thank you @thickforest !

**Pull request merged**
