### PR TITLE
[MMI] Added code fencing in info tab component

### PR DESCRIPTION
**Pull request by albertolive**
## Explanation

Added code fencing in info tab component

https://consensyssoftware.atlassian.net/browse/MMI-2514

## Pre-merge author checklist

- [X] I've clearly explained:
  - [X] What problem this PR is solving
  - [X] How this problem was solved

## Pre-merge reviewer checklist

- [X] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [X] PR is linked to the appropriate GitHub issue

### CODE REVIEW

**Review by zone-live — DISMISSED** [review]

**Review by NidhiKJha — COMMENTED** [review]
Question: Are we updating the links for privacy and site url from metamask to mmi??

## Current behaviour: 

https://user-images.githubusercontent.com/39872794/226326224-dffd03f9-f9ce-4fc5-9bdb-4845d49b6ddb.mov



## Changed
https://user-images.githubusercontent.com/39872794/226326054-9ce7d575-3b83-46df-95de-4c20feaedca5.mov

**Comment by albertolive** [comment]
Hi @NidhiKJha,

Good catch! I tried the same thing, and the link has indeed changed. But it doesn't make sense because I'm adding code fencing. Will the code fencing be applied correctly when the builds are generated? Or am I missing something else?

image

**Comment by albertolive** [comment]
@NidhiKJha can you test it again? Have made some changes :)

**Review by NidhiKJha — APPROVED** [review]
Checked storybook with links. LGTM

**Review by zone-live — APPROVED** [review]

**Pull request merged**
