### PR TITLE
Various fixes you've been waiting for, how exciting!

### PR DESCRIPTION
**Pull request by kumavis**
- fix memory leak warning
- fix filters middleware to include historical results
- add some missing deps
- `metamaskController.blockTracker` now references the actual eth-block-tracker on provider-engine

### CODE REVIEW

**Comment by kumavis** [comment]
seems like a mascara test failure here

**Comment by kumavis** [comment]
just need to make sure we're on the correct deps before build and publish
relies on correct version 4 deps deep

so lets be sure to nuke node_modules and npm i on npm@4

**Comment by flyswatter** [comment]
Fixes #2122

**Review by frankiebee — DISMISSED** [review]
We need to track event listeners and reassign them on network change for this to not cause any strange bugs

**Comment by frankiebee** [comment]
please wrap in a proxy and catch the `.on` callbacks let me know if you'd like me to do that.

**Comment by kumavis** [comment]
I DIG IT

**Comment by kumavis** [comment]
@frankiebee need to actually change review to approve, not dismiss

**Review by danfinlay — APPROVED** [review]
Cursory review looks good, want to do fractional rollout. Maybe a changelog entry?

**Pull request merged**
