### PR TITLE
Version v11.16.0

### PR DESCRIPTION
**Pull request by benjisclowder**
RC 11.16.0

### CODE REVIEW

**Comment by benjisclowder** [comment]
[Manual test scenarios:](https://github.com/MetaMask/metamask-extension/tree/develop/test/scenarios)

**Chrome**

- [ ] Onboarding - create a wallet
- [ ]  Onboarding - import a wallet
- [ ]  Keyring - connect hardware wallet
- [ ]  Keyring - reset a wallet
- [ ]  Transactions - send native token origin MM
- [ ]  Transactions - send native token origin dapp
- [ ]  Transactions - send ERC20 token origin MM
- [ ]  Transactions - send ERC20 token origin dapp
- [ ]  Transactions - send ERC721 token origin MM
- [ ]  Transactions - send ERC721 token origin dapp
- [ ]  Transactions - speed up transaction
- [ ]  Transactions - cancel transaction
- [ ]  Transactions - deploy failing transaction
- [ ]  Transactions - deposit and withdraw
- [ ]  Transactions - navigate multiple transactions
- [ ]  Transactions - send transactions with custom nonce
- [ ]  Transactions - cancel transaction using same nonce
- [ ]  Tokens - import ERC20 token origin MM
- [ ]  Tokens - import ERC20 token origin dapp
- [ ]  Tokens - import ERC721 token origin MM
- [ ]  Tokens - import ERC721 token origin dapp
- [ ]  Tokens - import ERC1155 token origin MM
- [ ]  Tokens - import ERC1155 token origin dapp
- [ ]  Tokens - approve ERC1155 token
- [ ]  Tokens - approve ERC20 token
- [ ]  Tokens - approve ERC721 token
- [ ]  Tokens - autodetect tokens
- [ ]  Tokens - autodetect NFTs
- [ ]  Tokens - approve erc20 custom amount
- [ ]  ENS - name resolution
- [ ]  Phishing - warning page
- [ ]  Network - add custom network manually
- [ ]  Network - add custom network from the list of popular networks
- [ ]  Network - add custom network from dApp
- [ ]  Network - update networks
- [ ]  Network - switching networks
- [ ]  Network - delete networks from the dropdown list
- [ ]  Network - delete networks in Settings
- [ ]  Backup - backup user data
- [ ]  Backup - restore user data
- [ ]  Metrics - send event metrics
- [ ]  Address-book - add a contact to the address book
- [ ]  Address-book - remove a contact from the address book
- [ ]  Address-book - update a contact in the address book
- [ ]  Gas fee - EIP-1559 gas
- [ ]  Gas fee - legacy gas
- [ ]  Sign - eth sign
- [ ]  Sign - personal sign
- [ ]  Sign - sign in with ethereum
- [ ]  Sign - sign typed with data
- [ ]  Sign - sign typed data v3 with hardware wallet
- [ ]  Sign - sign typed data v4 with hardware wallet
- [ ]  Sign - personal sign with hardware wallet
- [ ]  Sign - eth sign with hardware wallet
- [ ]  Permissions - connecting and disconnecting from a dapp
- [ ]  Swap - smart swap
- [ ]  Swap - swap eth
- [ ]  Incoming transactions - receive native token
- [ ]  Settings - about MetaMask
- [ ]  Settings - general - change language
- [ ]  Settings - advanced - check custom nonce toggle
- [ ]  Settings - advanced - show hex data
- [ ]  Contract - deploy contract, mint and import NFT with hardware wallet
- [ ]  Contract - hardware wallet qr based connect
- [ ]  Contract - send token with hardware wallet

 
**Firefox**

- [ ] Onboarding - create a wallet
- [ ]  Onboarding - import a wallet
- [ ]  Keyring - connect hardware wallet
- [ ]  Keyring - reset a wallet
- [ ]  Transactions - send native token origin MM
- [ ]  Transactions - send native token origin dapp
- [ ]  Transactions - send ERC20 token origin MM
- [ ]  Transactions - send ERC20 token origin dapp
- [ ]  Transactions - send ERC721 token origin MM
- [ ]  Transactions - send ERC721 token origin dapp
- [ ]  Transactions - speed up transaction
- [ ]  Transactions - cancel transaction
- [ ]  Transactions - deploy failing transaction
- [ ]  Transactions - deposit and withdraw
- [ ]  Transactions - navigate multiple transactions
- [ ]  Transactions - send transactions with custom nonce
- [ ]  Transactions - cancel transaction using same nonce
- [ ]  Tokens - import ERC20 token origin MM
- [ ]  Tokens - import ERC20 token origin dapp
- [ ]  Tokens - import ERC721 token origin MM
- [ ]  Tokens - import ERC721 token origin dapp
- [ ]  Tokens - import ERC1155 token origin MM
- [ ]  Tokens - import ERC1155 token origin dapp
- [ ]  Tokens - approve ERC1155 token
- [ ]  Tokens - approve ERC20 token
- [ ]  Tokens - approve ERC721 token
- [ ]  Tokens - autodetect tokens
- [ ]  Tokens - autodetect NFTs
- [ ]  Tokens - approve erc20 custom amount
- [ ]  ENS - name resolution
- [ ]  Phishing - warning page
- [ ]  Network - add custom network manually
- [ ]  Network - add custom network from the list of popular networks
- [ ]  Network - add custom network from dApp
- [ ]  Network - update networks
- [ ]  Network - switching networks
- [ ]  Network - delete networks from the dropdown list
- [ ]  Network - delete networks in Settings
- [ ]  Backup - backup user data
- [ ]  Backup - restore user data
- [ ]  Metrics - send event metrics
- [ ]  Address-book - add a contact to the address book
- [ ]  Address-book - remove a contact from the address book
- [ ]  Address-book - update a contact in the address book
- [ ]  Gas fee - EIP-1559 gas
- [ ]  Gas fee - legacy gas
- [ ]  Sign - eth sign
- [ ]  Sign - personal sign
- [ ]  Sign - sign in with ethereum
- [ ]  Sign - sign typed with data
- [ ]  Sign - sign typed data v3 with hardware wallet
- [ ]  Sign - sign typed data v4 with hardware wallet
- [ ]  Sign - personal sign with hardware wallet
- [ ]  Sign - eth sign with hardware wallet
- [ ]  Permissions - connecting and disconnecting from a dapp
- [ ]  Swap - smart swap
- [ ]  Swap - swap eth
- [ ]  Incoming transactions - receive native token
- [ ]  Settings - about MetaMask
- [ ]  Settings - general - change language
- [ ]  Settings - advanced - check custom nonce toggle
- [ ]  Settings - advanced - show hex data
- [ ]  Contract - deploy contract, mint and import NFT with hardware wallet
- [ ]  Contract - hardware wallet qr based connect
- [ ]  Contract - send token with hardware wallet

**Comment by benjisclowder** [comment]
We need teams' approval on May 2 at the latest to stick to our 7-day release cut-submission trial plan for the following four RC's.

**Instructions for Team Review**

Review Changes: Refer to the [Release Tracker for v11.16.0](https://docs.google.com/spreadsheets/d/1tsoodlAlyvEUpkkcNcbZ4PM9HuC9cEM80RZeoVv5OCQ/edit#gid=1379689303) to see all changes relevant to your team.
Log Bugs: If you find any issues, log them in the release tracker and attach them to https://github.com/MetaMask/MetaMask-planning/issues/2426.
Approval: After reviewing, indicate your team's approval by:
Marking the checkbox next to your team's name in this comment.
Optionally, leave a comment for additional information.
Your thorough review ensures a smooth and successful release. If you have any questions please reach out to extension platform team or in the [#metamask-qa](https://consensys.slack.com/archives/C01U65ZUS2E) slack channel. Thank you for your collaboration!

- [ ]  Accounts: @plasmacorral - There are 5 Accounts changes in v11.16.0
- [ ]  Assets: @sahar-fehri / @alfeng6 - There are 10 Assets changes in v11.16.0
- [ ]  Bridging: @micaela.estabillo - There is 1 Bridging change in v11.16.0
- [ ]  Confirmation Systems: @sleepytanya - There are 13 Confirmation Systems changes in v11.16.0.
- [ ]  Confirmation UX: @seaona - There are 16 Confirmations UX changes in v11.16.0
- [ ]  DappAPI: @jiexi - There are 4 DappAPI changes in v11.16.0.
- [ ]  Design/Systems: @georgewrmarshall - There is 1 Design/Systems change in v11.16.0.
- [ ]  Devex: @tmashuang  / @vandan - There are 3 Devex changes in v11.16.0.
- [ ]  MMI: @zone-live / @shane-t - There are 11 MMI changes in v11.16.0.
- [ ]  Snaps: @bowensanders / @FrederikBolding / @Montoya - There are 9 Snaps changes in v11.16.0.
- [ ]  Swaps: @davibroc / @dan437 - There are 6 Swaps change in v11.16.0.
- [ ]  Shared Libraries: @Gudahtt - There are 3 Shared Libraries changes in v11.16.0.
- [ ]  Wallet UX: @darkwing / @NidhiKJha - There are 12 Wallet UX changes in v11.16.0.

**Comment by georgewrmarshall** [comment]
🟢 Approval from @MetaMask/design-system team
- Checked ToggleButton styles were updated https://github.com/MetaMask/metamask-extension/pull/24090

**Comment by plasmacorral** [comment]
🟢 Approval from Accounts team

**Comment by plasmacorral** [comment]
🟢 Approval from Accounts team

**Comment by adonesky1** [comment]
🟢  Approval for Wallet API Platform Team

**Comment by danjm** [comment]
@metamaskbot update-policies

**Comment by danjm** [comment]
@metamaskbot update-policies

**Comment by sleepytanya** [comment]
🟢 Approval from Confirmations team.

**Comment by brad-decker** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
