### PR TITLE
Alter broken identicon images when the image errors

### PR DESCRIPTION
**Pull request by darkwing**
This is sort of a conversation starter.  Right now, in Firefox, a broken identicon image shows the alt text, which looks kinda gross:

boooo

Instead we could do something like:
Broken

Happy for design and others to weigh in!

### CODE REVIEW

**Comment by GuillaumeRx** [comment]
Maybe we could have a default image to replace the broken identicon ? Like a little token symbol if this only appends on the token identicons

**Comment by Montoya** [comment]
Follow on request is if the broken token image could be per-blockchain, so Ethereum tokens will have a certain image and Polygon tokens will have a certain image and so on.

**Comment by brad-decker** [comment]
@georgewrmarshall @garrettbear @brianacnguyen -- i think y'all are talking about icons, avatars, etc. You may want to take to design team what to do in these cases and align on the fallback.

**Comment by georgewrmarshall** [comment]
We have a component for this! https://metamask.github.io/metamask-storybook/?path=/story/ui-components-component-library-avatar-token-avatar-token-stories-js--default-story&args=tokenImageUrl: but we need to implement the `onError` handler so it shows the first letter fallback instead of the alt tag text

**Pull request closed without merging**
