### PR TITLE
Additional incoming transactions support

### PR DESCRIPTION
**Pull request by tgmichel**
Currently only the built-in Infura networks - and not EVM compatible networks where the [official Etherscan API is available](https://etherscan.io/eaas) - support displaying incoming transactions.

This PR proposes introducing additional support for them:

- BNB Smart Chain - _mainnet, testnet_ - [view](https://bscscan.com/)
- Optimism - _mainnet, testnet_ - [view](https://optimistic.etherscan.io/)
- Polygon - _mainnet, testnet_ - [view](https://polygonscan.com/)
- Avalanche - _mainnet, testnet_ - [view](https://snowtrace.io/)
- Fantom - _mainnet, testnet_ - [view](https://ftmscan.com/)
- Moonbeam - _mainnet, testnet_ - [view](https://moonbeam.moonscan.io/)
- Moonriver - [view](https://moonriver.moonscan.io/)

### CODE REVIEW

**Comment by tgmichel** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by tgmichel** [comment]
@PeterYinusa did you have a chance to look at this?

**Comment by tgmichel** [comment]
@PeterYinusa is there any additional work to do on my side to get it reviewed? Thank you.

**Comment by brad-decker** [comment]
@tgmichel sorry we didn't review this yet, looks like a pretty amazing contribution that I'm sure our users would love. Could you do me a favor and rebase this? One area that has changed dramatically is the network.js constants file which is now typescript so you'll have to introduce some types to your changes. Let me know if you need assistance and tag me for review when you're ready :)

**Comment by tgmichel** [comment]
@brad-decker Thank you, very excited to finally get this in :) and sorry it took a while, just rebased.

**Review by brad-decker — APPROVED** [review]
Awesome work, we'll get more eyes on this next week for an additional approval.

**Review by brad-decker — DISMISSED** [review]
This LGTM, @seaona / @PeterYinusa I've tested this and it looks good locally, but i might miss some edge cases. Would either of you take a look from the QA side? @jpuri and/or @segun if you have a chance to do a code review that'd be great.

**Comment by seaona** [comment]
@brad-decker I can take a look

**Comment by seaona** [comment]
From QA looks good! @brad-decker @tgmichel ! I've only noticed one small behaviour on Polygon Testnet. Bascially, until I don't refresh the browser page I don't see any tx coming through. Not sure why I can only observe this on Polygon Testnet. Any ideas?

Just curious. I would still approve the PR from QA side, since after refreshing, the tx appear.

https://user-images.githubusercontent.com/54408225/201342105-29193b1b-1517-4abb-a0d4-858e9e1db83b.mp4

**Comment by brad-decker** [comment]
Thats peculiar. @seaona lets create a ticket to investigate that and i'll get another set of eyes on this.

**Comment by tgmichel** [comment]
@brad-decker the issue @seaona mentioned doesn't seem to originate in this PR, is there something I can do to help you unlock it?

The logic for triggering `_onLatestBlock` and updating `incomingTxLastFetchedBlockByChainId` LGTM. I didn't debug it but it might be worth looking at `getSelectedAddress` here:

```
this._onLatestBlock = async (newBlockNumberHex) => {
    const selectedAddress = this.preferencesController.getSelectedAddress();
    const newBlockNumberDec = parseInt(newBlockNumberHex, 16);
    await this._update(selectedAddress, newBlockNumberDec);
};
```

If the `selectedAddress` is not properly retrieved from `preferencesController`, the `_update` function will early return:

```
if (
    !Object.hasOwnProperty.call(ETHERSCAN_SUPPORTED_NETWORKS, chainId) ||
    !address
) {
    return;
}
```

I'm thinking _maybe_ after refreshing, the `selectedAddress` is correctly picked up and works as expected. Anyway this is just a wild guess because if that would happen shouldn't be something network-specific (and apparently is only observed in Polygon Testnet)

**Comment by chloeYue** [comment]
Hello @tgmichel Thanks for your PR ! 
Do you think it's possible to add also incoming transactions for localhost with ganache ? Then it will help when we test locally.

**Comment by tgmichel** [comment]
> add also incoming transactions for localhost with ganache

The current controller for incoming transactions leverages Etherscan Api, which is not available for Ganache afaik.

**Comment by clydesdales** [comment]
@tgmichel 
@brad-decker 
@seaona 
@PeterYinusa 

Can i add a bounty to get this expedited? When will incoming transactions be merged? The community has been waiting far too long for such an essential feature to be added

**Review by pedronfigueiredo — DISMISSED** [review]

**Comment by tgmichel** [comment]
@brad-decker sorry to come back at you again regarding this PR, please let me know when is ready to be merged so I can rebase once. Thank you!

**Review by brad-decker — APPROVED** [review]

**Review by pedronfigueiredo — APPROVED** [review]

**Pull request merged**
