### PR TITLE
Disable Bridge button on unsupported networks

### LINKED ISSUE #18193: [Bug]: Bridge button is enabled on unsupported networks
### Describe the bug

The `Bridge` button is enabled on unsupported networks, whilst the `Buy` and `Swap` button is disabled

palm bridge

### Steps to reproduce

1. Log in to the extension
2. Add the `Palm Network, switch to the newly added network
3. Click the `Bridge` button

### Error messages or log output

_No response_

### Version

v10.28

### Build type

None

### Browser

Firefox

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by micaelae**
## Explanation
* Disables the Bridge button when active network is unsupported and displays "Unavailable on this network" tooltip on hover
* Fixes [#18193](https://github.com/MetaMask/metamask-extension/issues/18193)

### Before
Screenshot 2023-03-21 at 12 09 04 PM

### After
Screenshot 2023-03-21 at 12 08 26 PM
Screenshot 2023-03-21 at 12 08 31 PM

## Manual Testing Steps
1. Open the extension
2. Select the Ethereum network
3. Verify that Bridge button is enabled and opens the portfolio page when clicked
4. Open the extension
5. Select the Fantom network
6. Verify that the Bridge button is disabled (greyed out and unclickable)
7. Hover over the Bridge button and verify that "Unavailable on this network" is visible

## Pre-merge author checklist

- [X] I've clearly explained:
  - [X] What problem this PR is solving
  - [X] How this problem was solved
  - [X] How reviewers can test my changes
- [X] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Comment by kevinghim** [comment]
Resolves https://github.com/MetaMask/metamask-extension/issues/18193

**Comment by BZahory** [comment]
LGTM!

**Review by digiwand — APPROVED** [review]
Lgtm!

**Review by danjm — APPROVED** [review]
LGTM!

**Pull request merged**
