### PR TITLE
Various UI fixes

### PR DESCRIPTION
**Pull request by ryanml**
Addressing some of the extension UI bugs found by @yanrong-chen 

Screen Shot 2021-07-13 at 1 12 46 AM
Screen Shot 2021-07-13 at 12 48 53 AM
Screen Shot 2021-07-13 at 12 37 06 AM
Screen Shot 2021-07-13 at 12 48 45 AM
Screen Shot 2021-07-13 at 12 15 35 AM

### CODE REVIEW

**Comment by darkwing** [comment]
The screenshots look good, as does the code, but is there a list of the specific issues?

**Comment by ryanml** [comment]
Hey @darkwing - check out the doc @yanrong-chen created in the design channel, thanks!

**Review by darkwing — APPROVED** [review]
I love improving the little things!  Makes the app look so much better!

**Review by NiranjanaBinoy — APPROVED** [review]
LGTM

**Pull request merged**
