### PR TITLE
Replacing deprecated Popover with Modal

### LINKED ISSUE #19555: Replace deprecated Popover component with Modal from the component-library
### Description

Currently, the extension is using an outdated `Popover` component, which needs to be replaced with the new `Modal` component.

This is a massive undertaking by itself and creating a single PR would be too large. Smaller PRs can be submitted against this issue to ensure easier review and gradual improvements.

### Technical Details

- Replace instances of Popover component (`ui/components/ui/popover/popover.component.js`) with Modal component (`ui/components/component-library/modal/modal.tsx`)
- Component architecture and APIs are different so ensure all components and props have been migrated appropriately

### Acceptance Criteria

- Instances of Popover component are completely replaced with the new Modal component
- The component APIs are updated to reflect the changes in the new Popover component and there is no functional changes or visual regression
- Each Pull Request (PR) should include **no more than 3 files**
- The code changes should pass Jest tests, linting, and Storybook without any errors.
- The PR must include before and after screenshots of the UI to ensure there are no visual regressions.

If the acceptance criteria is not met, PRs may be closed.

### Difficulty: Intermediate

Good first issue for: External contributors who are familiar with running the extension locally, have knowledge of React, component props, Jest tests, linting, and Storybook, and want to contribute to improving the cohesiveness of UI in the extension

### PR DESCRIPTION
**Pull request by Jainex17**
## Explanation

This pull request addresses the issue of replacing the outdated Popover component with the new Modal component in the cancel-speedup-popover.test.js file.

Since this is a significant undertaking, I have decided to start with a single file to facilitate easier review and gradual improvements. Once this pull request is reviewed and approved, I will proceed to add two more files related to this issue.

Thank you for your time and consideration.

* Fixes #19555 

## Chnages Made

* Replacing instances of the Popover component with the Modal component in `cancel-speedup-popover.test.js`.

### Before
Before1

### After
after

## Manual Testing Steps
* Search `CancelSpeedupPopover` in StroyBook

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [x] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

### CODE REVIEW

**Comment by georgewrmarshall** [comment]
Hey @Jainex17, Would it be possible to update this PR?

**Comment by Jainex17** [comment]
Hey @georgewrmarshall, I resolved the conflict. Could you please review it?

**Comment by Jainex17** [comment]
> Hey @Jainex17, Would it be possible to update this PR?

Apologies for the delay. I've fixed all the Jest errors. Could you please review them? Thanks!

**Review by georgewrmarshall — APPROVED** [review]
LGTM! Thanks for your contributon

**Review by garrettbear — APPROVED** [review]
👏

**Pull request merged**
