### PR TITLE
Miscellaneous Tests

### PR DESCRIPTION
**Pull request by tmashuang**
Various unit tests and updates.

### CODE REVIEW

**Comment by kumavis** [comment]
@tmashuang whoops, looks like this PR got a little stale

**Comment by bdresser** [comment]
@tmashuang @kumavis bump on this - merge? or close

**Comment by tmashuang** [comment]
I would like to bump this, I wanna say half of these tests won't change for a while, but in the case they do I'll continue to update this PR accordingly.

**Comment by whymarrh** [comment]
@tmashuang do you want to rebase this on the latest `develop`?

**Comment by kumavis** [comment]
@tmashuang lets get this merged

**Comment by tmashuang** [comment]
I can push an update for this branch, but there are talks about migrating to React 16. I'm hoping that the tests will still be fine, but not holding my breath. So when that lands, this will need to be updated as well.

**Comment by tmashuang** [comment]
With the latest commit, this broadly includes js files that have no tests including into the coverage. Some of the more complex components have just basic "does it render" tests. These will be expanded in a future commit/PR. The approach is working on the zero percentile components/files, and reiterating from the bottom.

**Comment by tmashuang** [comment]
I'm fairly hesitant on getting this merged due to momentary failures on some Ci builds that I've reran on this branch. Will investigate those.

**Comment by tmashuang** [comment]
Closing, will separate out the PR and commits accordingly.

**Pull request closed without merging**
