### PR TITLE
getCode when tokenMethodName is provided

### LINKED ISSUE #6602: Unable to call ERC20::approve on the Ropsten Test Network
Unable to call ERC20::approve on the Ropsten Test Network.

Getting error `ALERT: Trying to call a function on a non-contract address.`

**To Reproduce**
1. Go to https://ropsten.etherscan.io/address/0x603bc175a26c8f74eaf9bc6ef5dd288afb6fc4b8#writeContract
2. Set _sender to 0xfd2288b96643fe5f75917df6d846998d197bbcdb
3. Set _value to 100000000
4. Applying transaction fails

### PR DESCRIPTION
**Pull request by tmashuang**
Fixes https://github.com/MetaMask/metamask-extension/issues/6602.

### CODE REVIEW

**Review by frankiebee — CHANGES_REQUESTED** [review]
remove the `else if` for token method name all together and put ` result = tokenMethodName`  in the else if tokenMethodName is `undefined` it wont matter because `result` is already undefined

**Review by danjm — APPROVED** [review]

**Review by danjm — CHANGES_REQUESTED** [review]
wait...

**Comment by frankiebee** [comment]
lol

**Comment by danjm** [comment]
The solution here will fix the issue for cases where token `transfer`, `approve` and `transferFrom` calls are made without specifying gas. However, is will cause transactions that should be given a `transactionCategory` of `DEPLOY_CONTRACT_ACTION_KEY` to have one of `SENT_ETHER`. Also, the `getCode` call in the case of a token method can be avoided.

As an alternative, I propose https://github.com/MetaMask/metamask-extension/pull/6604

**Comment by danjm** [comment]
> However, this will cause transactions that should be given a transactionCategory of DEPLOY_CONTRACT_ACTION_KEY to have one of SENT_ETHER

Really, this is my fault for lack of unit test coverage. That has now been added in https://github.com/MetaMask/metamask-extension/pull/6604 with commit 654bd62456753b477082697c4c03f1553e1e15ee

**Comment by tmashuang** [comment]
Closed by alternative PR #6604

**Pull request closed without merging**
