### PR TITLE
Replaces SEVERITIES const with Severity enum in BannerAlert

### PR DESCRIPTION
**Pull request by pritam1813**
## Explanation
- This PR fixes Part of #19528 and #18714 
- This Replaces all instances of `SEVERITIES` const with `Severity` enum in `ui/components/component-library/banner-alert` folder

### Before

https://github.com/MetaMask/metamask-extension/assets/8112138/c8654c79-40a3-42d3-a17c-19deb05d3981

### After

https://github.com/MetaMask/metamask-extension/assets/8112138/20d21481-600a-4902-b240-9a8dc080aa3f

## Manual Testing Steps

- Pull this branch
- Run storybook `yarn storybook`
- Search `BannerAlert` in storybook
- Check docs and stories

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [x] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Review by brad-decker — DISMISSED** [review]

**Review by georgewrmarshall — COMMENTED** [review]
Hey @pritam1813, this is great could you please update the other instances of `SEVERITIES` in the `./ui/components/component-library/banner-alert` folder as well? Below is the results for this folder
Screenshot 2023-07-26 at 10 08 14 AM

**Review by georgewrmarshall — CHANGES_REQUESTED** [review]
Blocking until other instances have been updated

**Comment by pritam1813** [comment]
> Hey @pritam1813, this is great could you please update the other instances of `SEVERITIES` in the `./ui/components/component-library/banner-alert` folder as well? Below is the results for this folder Screenshot 2023-07-26 at 10 08 14 AM

Yeah, I was thinking if this would make this a large PR. Anyway I have removed rest of the instances of `SEVERITIES` from the banner-alert folder.

One odd change though, I had to use `BANNER_ALERT_SEVERITIES` object values in `ui/components/component-library/banner-alert/banner-alert.stories.js` , because it does not allow enum values from `Severity`.

**Review by georgewrmarshall — APPROVED** [review]
LGTM! Made some small updates and updated the screencasts in the PR description. Thanks for your contribution @pritam1813!

**Review by garrettbear — APPROVED** [review]

**Pull request merged**
