### PR TITLE
build - catch build pipeline errors properly

### PR DESCRIPTION
**Pull request by EtDu**
Uses `pump` because it knows how to handle errors. need to handle errors for every stream you create, errors don't propagate through streams

### CODE REVIEW

**Comment by kumavis** [comment]
QA: this might break the watch-and-build flow on error, need to check

**Review by Gudahtt — DISMISSED** [review]
LGTM! I can confirm that this makes the build crash correctly when it fails, rather than keep going without printing anything to the console.

**Comment by Gudahtt** [comment]
Oh, it does break the watch flow  though. I can see that being undesirable :thinking: But... I'd rather it crash loudly and break the flow, than fail silently I think? Maybe we can make `watch` behave more sensibly in a future PR.

**Comment by kumavis** [comment]
if you accidentally save with a syntax error it breaks the reload on change flow, so do want to fix that. just needs a try/catch around the bundle on change. ill get to it eventually

**Comment by kumavis** [comment]
sounds like i made an assumption that it would break and your experimentation showed it to be wrong

**Comment by Gudahtt** [comment]
When I tested this with `yarn start`, it would crash the process completely if a build failure occurred on the initial build, stopping the file watcher. It would also cleanly print the error, making it easy to see what went wrong.

But if I introduce a build error _after_ the initial build while `yarn start` is running, it'll print some incomprehensible "UnhandledRejection" warnings without telling me what went wrong, but the process will continue unimpeded. The watcher continues running, and will build successfully when the error is corrected.

Ideally we'd keep the process running in the first place, and print the real error in the second, but at least the syntax error scenario doesn't break the watcher.

**Comment by kumavis** [comment]
@Gudahtt addressed both issues 👍 
this should be good2go

**Review by Gudahtt — APPROVED** [review]
LGTM! I've tested this, and it now works correctly for errors on initial build and on subsequent builds.

**Pull request merged**
