### PR TITLE
Move Tx State History to diff-based format

### PR DESCRIPTION
**Pull request by kumavis**
"tx state history" is the history of a single tx changing states (e.g. status from "signed" to "confirmed")
 - moving to a diff format reduces size of tx state history to ~15% of original
 - makes it nicely human readable as a single history item shows only what changed

This PR includes:
- includes a migration to the new format
- changes tx controller to create history items in the new format
- adds tests for the new history behavior

### CODE REVIEW

**Comment by kumavis** [comment]
kumavis QA passed - its bueno

**Comment by flyswatter** [comment]
Can't wait to see what it looks like

**Comment by kumavis** [comment]
diff looks like `[{ op: 'replace', path: '/txParams/gasPrice', value: '0xabcd' }]`

**Review by danfinlay — APPROVED** [review]
I pulled this down, it seems to work fine, was able to send a tx and review its history much more easily.

**Pull request merged**
