### PR TITLE
Add new unlock screen design

### LINKED ISSUE #3614: Unlock screen design + enable password manager
While testing the new unlock screen in full page mode, I tried using my password manager and it didn't work. This might be enabled by following password form input best practices. Here's 1password's https://support.1password.com/compatible-website-design/

Attaching the design here. I also created a codepen version to reference for the password input animation: https://codepen.io/cjeria/pen/ZxBeEM?editors=1100

Also notice that I've removed the top bar (with fox and network switcher as it's not necessary when account is locked).

Let's keep the animated fox but with new dimensions of this design. 

image
unlock screen

### PR DESCRIPTION
**Pull request by alextsg**
Fixes #3614 

@cjeria 
- Regarding removing the app header from pages where the user isn't logged in, users want to be able to change the network without logging in so I've kept it on the unlock screen. However, this PR removes the bar from the first time flow.
- I don't think password managers will work with MetaMask because chrome extensions aren't able to communicate with each other for security reasons.

image

image

image

image

### CODE REVIEW

**Comment by cjeria** [comment]
@alextsg 
> users want to be able to change the network without logging in so I've kept it on the unlock screen.
Why? What's the use case?

Change 'login' to "unlock". I thought we all agreed to go with lock/unlock.

Increase button border radius. Should be 4px. It looks round in your version.

Vertical spacing of elements look are off. see screenshot. Also see font size in screenshot. 

image

**Comment by cjeria** [comment]
> I don't think password managers will work with MetaMask because chrome extensions aren't able to communicate with each other for security reasons.

Even with the extension being on full screen? Did you try adding the proper attributes to the page? https://hiddedevries.nl/en/blog/2018-01-13-making-password-managers-play-ball-with-your-login-form

**Comment by alextsg** [comment]
@cjeria Updated font size and spacing
image

**Review by cjeria — DISMISSED** [review]

**Review by danjm — DISMISSED** [review]
Looks good.

A non-blocking comment: the render method of unlock-page.component.js is large, which might make it cumbersome to unit test. Perhaps, at least, the divs with`onClick` props with conditional logic should be split out somehow (either the method into the container, or the div into a component method call or extra component...). In fact, the divs with "unlock-page__link" and "unlock-page__link--import" classes would be candidates for a subcomponent of the unlock page.

But this is a suggestion for code improvement and not a reason to not merge this PR.

**Review by frankiebee — APPROVED** [review]

**Pull request merged**
