### PR TITLE
fix: Update help center URLs

### PR DESCRIPTION
**Pull request by wtzb**
## **Description**

The MetaMask help center has migrated from using Zendesk to Docusaurus. The old Zendesk URL is no longer in use, and the support.metamask.io domain should be used instead.

Old support links still using metamask.zendesk.com will no longer function as of this week, so I've replaced these with the correct, modern URLs. Links following the old Zendesk format (support.metamask.io/hc/en-us/...) have also been replaced with the modern versions.

Also see https://github.com/MetaMask/metamask-mobile/pull/9946.

## **Related issues**

N/A

## **Manual testing steps**

N/A

## **Screenshots/Recordings**

N/A

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by wtzb** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Comment by DDDDDanica** [comment]
Also find some instance can be updated: 

1. `ui/helpers/constants/beta.js`
2. `builds.yml`

BTW is it needed to update links in `ui/helpers/constants/zendesk-url.js`?

**Comment by legobeat** [comment]
> Also find some instance can be updated:
> 
>     1. `ui/helpers/constants/beta.js`
> 
>     2. `builds.yml`
> 
> 
> BTW is it needed to update links in `ui/helpers/constants/zendesk-url.js`?

FYI, mentions of `https://metamask.zendesk.com` is also present in these files:

```
test/env.js
ui/components/app/beta-header/__snapshots__/beta-header.test.js.snap
ui/components/app/modals/confirm-remove-account/__snapshots__/confirm-remove-account.test.js.snap
ui/components/app/modals/customize-nonce/__snapshots__/customize-nonce.test.js.snap
ui/components/multichain/import-account/__snapshots__/json.test.tsx.snap
ui/helpers/constants/common.ts
ui/pages/confirmations/confirmation/templates/__snapshots__/add-ethereum-chain.test.js.snap
ui/pages/keychains/__snapshots__/reveal-seed.test.js.snap
ui/pages/onboarding-flow/create-password/__snapshots__/create-password.test.js.snap
ui/pages/settings/info-tab/info-tab.test.tsx
```

**Comment by wtzb** [comment]
Hi there @DDDDDanica and @legobeat! I've added additional links, as mentioned. Old support links still using metamask.zendesk.com will no longer function as of this week, so I've replaced these with the correct, modern URLs. Links following the old Zendesk format (support.metamask.io/hc/en-us/...) have also been replaced with the modern versions.

Let me know whether you might need anything else from my end in order to get this live as soon as possible, as currently, some links are broken.

**Review by DDDDDanica — DISMISSED** [review]

**Comment by DDDDDanica** [comment]
LGTM ! Let me know when you have the test fixed.

**Review by benjisclowder — DISMISSED** [review]

**Review by matthewwalsh0 — DISMISSED** [review]

**Comment by ccharly** [comment]
Just for the record, we are still using the old URL in some files like:

```bash
builds.yml
68:      - SUPPORT_LINK: https://metamask-flask.zendesk.com/hc
69:      - SUPPORT_REQUEST_LINK: https://metamask-flask.zendesk.com/hc/en-us/requests/new
```

**Review by vinistevam — DISMISSED** [review]

**Comment by benjisclowder** [comment]
> Just for the record, we are still using the old URL in some files like:
> 
> ```shell
> builds.yml
> 68:      - SUPPORT_LINK: https://metamask-flask.zendesk.com/hc
> 69:      - SUPPORT_REQUEST_LINK: https://metamask-flask.zendesk.com/hc/en-us/requests/new
> ```

@wtzb can you please review this and change if necessary and request re-review afterwards? Thank you!

**Review by benjisclowder — DISMISSED** [review]

**Review by jpuri — DISMISSED** [review]

**Review by ccharly — DISMISSED** [review]
LGTM, some comments though:
- I feel like some of those hardcoded URLs should use the constants from `zendesk-url.js`
- Every mention (in the code) of "zendesk" should probably be renamed to "support" (or something close to that), as well as filenames!

**Review by benjisclowder — DISMISSED** [review]

**Review by ccharly — APPROVED** [review]

**Review by danjm — APPROVED** [review]

**Review by matthewwalsh0 — APPROVED** [review]

**Review by jpuri — APPROVED** [review]

**Pull request merged**
