### PR TITLE
Use method middleware for watchAsset

### PR DESCRIPTION
**Pull request by rekmarks**
This PR moves the `wallet_watchAsset` (also `metamask_watchAsset`) implementation to the method middleware. The functionality is unchanged. This was a planned change, but I did it now because an upcoming PR will remove the `web3` usage logging method, which would leave the method middleware temporarily unused.

This method will be further refactored and moved out of the preferences controller once the approval controller is merged.

There are no e2e tests for this method, but I tested it manually with the following:
```javascript
await ethereum.request({
    method: 'wallet_watchAsset',
    params: {
        type: 'ERC20',
        options: {
            address: '0xdac17f958d2ee523a2206206994597c13d831ec7',
            symbol: 'USDT',
            decimals: 6,
        },
    },
})
```

Ref: https://eips.ethereum.org/EIPS/eip-747

### CODE REVIEW

**Comment by rekmarks** [comment]
I just realized that #8640 will add another method to the method middleware, so this is not urgent. Nevertheless, it's here when we're ready!

**Review by NiranjanaBinoy — APPROVED** [review]
LGTM

**Review by brad-decker — APPROVED** [review]
LGTM

**Review by brad-decker — APPROVED** [review]
LGTM

**Pull request merged**
