### PR TITLE
Make JSDoc formatting more consistent

### PR DESCRIPTION
**Pull request by Gudahtt**
A few inconsistencies in JSDoc formatting have been fixed throughout the project. Many issues remain; these were just the few things that were easy to fix with a regular expression.

The changes include:

* Using lower-case for primitive types, but capitalizing non-primitive  types
* Separating the parameter identifier and the description with a dash
* Omitting a dash between the return type and the return description
* Ensuring the parameter type is first and the identifier is second (in a few places it was backwards)
* Using square brackets to denote when a parameter is optional, rather than putting "(optional)" in the parameter description
* Including a type and identifier with every parameter
* Fixing inconsistent spacing, except where it's used for alignment
* Remove incorrectly formatted `@deprecated` tags that reference non-existent properties
* Remove lone comment block without accompanying function

Additionally, one parameter was renamed for clarity.

### CODE REVIEW

**Comment by Gudahtt** [comment]
https://github.com/gajus/eslint-plugin-jsdoc
:eyes: :thinking:

**Comment by brad-decker** [comment]
> gajus/eslint-plugin-jsdoc 👀 🤔
Yes please

**Review by darkwing — DISMISSED** [review]
Excellent!  Thank you!

**Comment by Gudahtt** [comment]
Whoops! There is a conflict. I will rebase this in a moment.

**Review by darkwing — APPROVED** [review]

**Pull request merged**
