### PR TITLE
Reapply view quote screen designs

### PR DESCRIPTION
**Pull request by danjm**
This is a PR that contains the work reverted in #9904 (which was originally merged with #9612 and #9629 

We may still end up using much of this code. This draft PR can be a place for further discussion if necessary, and will be updated as any new design changes are made.

### CODE REVIEW

**Comment by Gudahtt** [comment]
I'm guessing this wasn't supposed to include the revert commits

**Comment by danjm** [comment]
Below are screenshots of how it currently looks. Some of these require design or implmentation improvements for reasons stated below

:+1:  Sufficient funds, no warnings, no approval required:
<div style="display: flex;">


</div>

:+1: Insufficient funds warning:
<div style="display: flex;">


</div>
<div style="display: flex;">
:-1: No warnings, but approval required. In popup view, metamask fee info is hidden below scroll:
<div style="display: flex;">


</div>

:-1: Price difference warning. Fee info hidden below the scroll in popup view, and terms of service pushed off screen in full screen view
<div style="display: flex;">


</div>

**Comment by jakehaugen** [comment]
A couple tweaks to reduce how often scrolling is needed:

1. Move the "Terms of Service" link to the "Build Quote" screen. Remove from the "View Quote" screen.
Screen Shot 2020-12-07 at 11 01 56 AM

2. Reduce spacing in gray header. This would only apply when there is an overlay (like in Swaps and Send). Move the heading up 8px and bottom align the actions in blue to the heading. Let me know if you see any problem with this change. cc: @rachelcope 
Screen Shot 2020-12-07 at 11 05 19 AM

**Comment by rachelcope** [comment]
@jakehaugen LGTM!

**Comment by darkwing** [comment]
With @jakehaugen's changes:

ViewQuoteTimer
BuildQuote

**Review by brad-decker — APPROVED** [review]
LGTM!

**Pull request merged**
