### PR TITLE
test: add ui render for debug ui integration tests

### PR DESCRIPTION
**Pull request by cryptotavares**
## **Description**

This PR adds UI rendering capabilities for debugging UI integration tests. It introduces the jest-preview package to allow visual inspection of component states during test execution.

For jest-preview to properly render the page being tested in the UI integration test, we need to provide it with the bundled css as well as with the relevant static assets.
To do that we have also introduced a minimal build script for UI integration tests, that outputs to `test/integration/config/assets/`. For consistency with actual application build process, the build script re-uses a lot of the existing build methods.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/27621?quickstart=1)

## **Related issues**

N/A

## **Manual testing steps**

1. Run the UI integration tests with the new debug rendering enabled
2. Verify that component states can be visually inspected during test runs

## **Screenshots/Recordings**
Output of the `debug()` in a UI integration test.
Screenshot 2024-10-23 at 12 01 04

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by cryptotavares** [comment]
@SocketSecurity ignore npm/package-json@6.5.0
@SocketSecurity ignore npm/got@9.6.0
@SocketSecurity ignore npm/defer-to-connect@1.1.3
@SocketSecurity ignore npm/jest-preview@0.3.1

**Comment by cryptotavares** [comment]
> @SocketSecurity ignore npm/package-json@6.5.0 @SocketSecurity ignore npm/got@9.6.0 @SocketSecurity ignore npm/defer-to-connect@1.1.3 @SocketSecurity ignore npm/jest-preview@0.3.1

Most of the highlighted risks are highlighted as supply chain risk (which lavamoat should get us some protection against). Moreover, the packages are only running for the ui integration tests.
* The author of `package-json` and `got` is https://github.com/sindresorhus (who is a well known open source developer/contributor) and as so it should give us some level of trust.
* `jest-preview` is the actual package that we are installing (a visualisation tool for jest virtual dom html output) and we are disabling the post install script
* `defer-to-connect` is dependency of `got`, which gives us some level of confidence. Also we should take into account that this dep was already installed on a different version.

**Comment by cryptotavares** [comment]
@metamaskbot update-policies

**Comment by cryptotavares** [comment]
@metamaskbot update-policies

**Review by pedronfigueiredo — APPROVED** [review]

**Review by OGPoyraz — APPROVED** [review]

**Pull request merged**
