### PR TITLE
Remove annoying console.log on each run

### PR DESCRIPTION
**Pull request by omBratteng**
This has been annoying me for some time, and line 36 is completely not needed.

### CODE REVIEW

**Comment by Zanibas** [comment]
We don't recommend taking out the logging feature altogether--perhaps modify it as a `log.debug` and we can merge it.

**Comment by ChainsawBaby** [comment]
I'd say that is noisy logging, and not really needed. Like, you don't need a message to tell you every time you start your car, but it should tell you when something is wrong.

`console.debug` is a no-op from Chromium 58, so it's be that same as logging to /dev/null

**Comment by Zanibas** [comment]
We do not use vanilla logging in this case, we use `loglevel` as described here:
https://www.npmjs.com/package/loglevel

It's for debugging purposes, so it still is useful for us in detecting whether or not an injection has occurred. We can discuss whether or not to have these logs in production, but that is for a discussion in an issue.

**Comment by Zanibas** [comment]
Basically, `log.debug` won't ever come up in production!

**Comment by ChainsawBaby** [comment]
Right, thought it was `console.debug`, changed it to `log.debug` now. And changed web3.setProvider to use it too, just in case

**Comment by flyswatter** [comment]
Did you QA this after adding `loglevel`? I don't think it's globally available in that file, ie needs import & environment-swapping code, ie [add this to the top of the file](https://github.com/MetaMask/metamask-extension/blob/master/app/scripts/background.js#L18-L20).

**Comment by flyswatter** [comment]
Also I'm not sure we do that environment-swapping for that file, may need to be added to the `gulpfile.js`.

Thanks for doing this btw, I do think it's a good feature to add.

**Comment by ChainsawBaby** [comment]
Well, the commit #9b8a052 passed both checks.
But I can add [these lines to the file](https://github.com/MetaMask/metamask-extension/blob/master/app/scripts/background.js#L18-L20) if needed

**Comment by kumavis** [comment]
@ChainsawBaby yes please
and https://github.com/MetaMask/metamask-extension/blob/master/app/scripts/background.js#L4

**Review by 2-am-zzz — APPROVED** [review]

**Pull request merged**
