### PR TITLE
fix: incorrect method name parsed from transaction data

### LINKED ISSUE #27120: [Bug]: Transactions - Sending ETH to a Contract (without any calldata) displays the name of `Token Id Rebase`
### Describe the bug

When I'm sending ETH to a contract, I see `Contract Interaction`in the last confirmation screen. However, when I confirm that transaction,  I then see `Token Id Rebase` into the Activity list.

### Expected behavior

I should see Contract Interaction, like it's currently happening in prod

### Screenshots/Recordings

https://github.com/user-attachments/assets/9095ae44-fcf9-496f-a057-d9f8cc7abccb

### Steps to reproduce

1. Select Sepolia
2. Start a Send tx
3. Add this recipient `0x0Aa40a73021569D4614614cDE1A5ae2B4D96f77a`
4. Send
5. See how the transaction name is `Token Id Rebase`

In the case it's needed for debugging, the contract is just this;

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.6.0;

contract Destruction {

    function destruct(address myContract) public {
        selfdestruct(payable(myContract));
    }

    function getMoney() public{
        msg.sender.transfer(address(this).balance);
    }
    receive() external payable { }
}
``

### Error messages or log output

_No response_

### Detection stage

During release testing

### Version

12.3.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by matthewwalsh0**
## **Description**

The core problem identified in the related issue was due to 4Byte ultimately being queried with `0x` which returned many results and so the returned function signature was effectively random.

This was then persisted in the user state so any subsequent transaction using `0x` as the data used the same value.

This also highlighted multiple instances where `0x` was interpreted as valid transaction data and React components were incorrectly shown.

To address all this, the following changes have been made:

- Method data derived for the metrics is only persisted if a result is found.
- Queries to 4Byte are skipped if the transaction data is `0x` or less than four bytes.
- Transaction data is not rendered in the legacy or redesigned confirmations if it is `0x`.
- The `getKnownMethodData` selector only returns a value if transaction data is at least four bytes.
- The unused `useKnownMethodDataInTransaction` hook was removed.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/27363?quickstart=1)

## **Related issues**

Fixes: #27120 

## **Manual testing steps**

1. Create internal and dApp transactions to `0x0Aa40a73021569D4614614cDE1A5ae2B4D96f77a` on Sepolia.
3. Verify the legacy and redesigned transactions do not render the transaction data if it is `0x`, `0X` or missing.
4. Verify no requests to four byte are made if data is less than four bytes.
5. Verify method name is always `Contract Interaction`.
6. Verify token allowance confirmation with and without a four byte response.

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by pedronfigueiredo — APPROVED** [review]

**Review by vinistevam — APPROVED** [review]

**Comment by sleepytanya** [comment]
@matthewwalsh0 

1. Create internal transaction to `0x0Aa40a73021569D4614614cDE1A5ae2B4D96f77a` on Sepolia
2. Turn OFF `Improved Transaction requests` in `Settings` -> `Experimental`
3. Observe next transaction created with the same nonce


https://github.com/user-attachments/assets/d8dc4699-1635-4243-8fb8-8e668fc264c8

If `Improved Transaction requests` are ON subsequent transaction created with the correct nonce.

You can see for a short time after clicking 'Confirm' that correct nonce value is displayed (but transaction still has low nonce and fails):


https://github.com/user-attachments/assets/7d7e08e6-7e19-4982-93c1-ccaf8b6e3fe6

**Comment by sleepytanya** [comment]
@matthewwalsh0 
Hex is not displayed (`Show HEX Data` is ON):


https://github.com/user-attachments/assets/0aea531f-e334-4868-aa8e-34c8b18973e1

**Comment by sleepytanya** [comment]
Hex field on second confirmation screen is not displayed on [the latest 12.3.0 build](https://github.com/MetaMask/metamask-extension/pull/26973#issuecomment-2371856873) but works on [the previous](https://github.com/MetaMask/metamask-extension/pull/26973#issuecomment-2371131066):

Screenshot 2024-09-24 at 23 58 00

Screenshot 2024-09-25 at 00 00 42

**Comment by sleepytanya** [comment]
For transactions sent from test dapp HEX field is shown:



https://github.com/user-attachments/assets/02f56de0-0911-4162-86e0-3b5ba67dd7e0




https://github.com/user-attachments/assets/d5edaf80-0700-4045-9f8a-b25b4ee95008

**Comment by sleepytanya** [comment]
Same nonce behavior on current `develop`:


https://github.com/user-attachments/assets/a2b1d495-ec6d-4e0c-ae74-2743ed46e8f4

**Pull request merged**
