### PR TITLE
chore: add Solana shared utilities and constants

### PR DESCRIPTION
**Pull request by ulissesferreira**
## **Description**

As we look to simplify snaps ability to support multiple chains we find that some code needs to be included in the main extension to make sure it can be easily imported throughout. In this PR we add utility functions similar to the Bitcoin ones but for Solana.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/28269?quickstart=1)

## **Manual testing steps**

1. Run tests and make sure they still pass
2. Run build process and make sure it succeeds

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by ulissesferreira** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by zone-live** [comment]
@metamaskbot update-policies

**Review by aganglada — DISMISSED** [review]

**Comment by zone-live** [comment]
@metamaskbot update-policies

**Comment by ulissesferreira** [comment]
@metamaskbot update-policies

**Review by zone-live — APPROVED** [review]

**Review by aganglada — APPROVED** [review]

**Pull request merged**
