### PR TITLE
Adding readme for component-library folder

### LINKED ISSUE #15378: Create documentation for component-library folder
### Description
Create a readme document to explain what the `ui/components/component-library` folder is for.

The `ui/components/component-library` contains all new design-system componentization work. It's purpose is to separate all new components from current or deprecated components. These components should eventually replace all ui components in `ui/components/ui`. If you have any questions reach out to the design system team on the slack channel https://consensys.slack.com/archives/C0354T27M5M

### Technical details
- Create `README.md` in `ui/components/component-library`
- Link to design-system and IA/Nav

### Acceptance criteria 
- Readme exists and clearly outlines what this folder is for and the

### PR DESCRIPTION
**Pull request by georgewrmarshall**
## Explanation

Currently, we are working on UI components for the IA/Nav redesign work. We want to separate this work so have created a new folder following mobile suit calling it `component-library` and moving it to `ui/components/component-library`

Have also created a story in storybook to explain the components

## More Information

* Fixes #15378

### After
Screen Shot 2022-07-28 at 4 47 26 PM

In storybook

Screen Shot 2022-07-29 at 12 28 04 PM

## Manual Testing Steps

- Go to this `ui/components/component-library` in the code base
- View `README.md` 

## Pre-Merge Checklist

- [x] PR template is filled out
- [x] ~**IF** this PR fixes a bug, a test that _would have_ caught the bug has been added~ N/A
- [x] PR is linked to the appropriate GitHub issue
- [x] ~PR has been added to the appropriate release Milestone~ N/A

### + If there are functional changes:

- [x] ~Manual testing complete & passed~ N/A
- [x] ~"Extension QA Board" label has been applied~ N/A

### CODE REVIEW

**Review by brad-decker — APPROVED** [review]
LGTM. I already reviewed this when it was in draft so happy to give a fast approval ;)

**Comment by georgewrmarshall** [comment]
@brad-decker thank you! Just need to double check the docs look ok in storybook after a rebase with the storybook fix.

**Review by NidhiKJha — APPROVED** [review]

**Comment by brad-decker** [comment]
@georgewrmarshall just merged my fix and updated branch we'll see how it looks soon :)

**Comment by georgewrmarshall** [comment]
@brad-decker added screenshot of storybook to description. I think it's good to go!

**Pull request merged**
