### PR TITLE
updated CollectibleDetail Storybook Coverage

### LINKED ISSUE #17157: NFTs:  Improve CollectibleDetail Storybook Coverage
### Describe the bug

Our `CollectibleDetail` component has pretty good Storybook coverage but there are some details which don't have values, such as "Last sold" and "Last sold price".  We should create a full `CollectibleDetail` Storybook experience.

### Steps to reproduce

N/A

### Error messages or log output

_No response_

### Version

10.23

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by NidhiKJha**
Fixes #17157 

### Before
Screenshot 2023-01-23 at 9 56 46 PM

### After

https://user-images.githubusercontent.com/39872794/215050964-af1affb6-ee16-49af-9890-2d74ff0f002a.mov

## Manual Testing Steps

Storybook
- Go to the latest build of the storybook in this PR
- Search for CollectibleDetail  in App
- Check the stories, controls, and documentation

## Pre-Merge Checklist

- [x] PR template is filled out
- [ ] **IF** this PR fixes a bug, a test that _would have_ caught the bug has been added
- [x] PR is linked to the appropriate GitHub issue
- [x] PR has been added to the appropriate release Milestone

### + If there are functional changes:

- [x] Manual testing complete & passed
- [x] "Extension QA Board" label has been applied

### CODE REVIEW

**Comment by SaraCheikh** [comment]
@NidhiKJha updated [the design ](https://www.figma.com/file/8Xe22jEPgcElS5tWPw8AGM/NFTs-in-extension-(MVP)?node-id=772%3A9832&t=6N23Lxc8Arcc29HE-1)to have the copy Button Icon ( in Icon/alternative colour) only with the contract address 
Screenshot 2023-01-23 at 19 22 37

**Comment by NidhiKJha** [comment]
> @NidhiKJha updated [the design ](https://www.figma.com/file/8Xe22jEPgcElS5tWPw8AGM/NFTs-in-extension-(MVP)?node-id=772%3A9832&t=6N23Lxc8Arcc29HE-1)to have the copy Button Icon ( in Icon/alternative colour) only with the contract address Screenshot 2023-01-23 at 19 22 37

@SaraCheikh I have added the copy icon to the contract address but before I update it to use the new icon, can you please confirm if there is going to be any pressed state for the button as well? The old design had a pressed state for copy button.

For old design, [refer to this storybook](https://metamask.github.io/metamask-storybook/?path=/story/components-app-collectiblesdetail--default-story)

**Comment by SaraCheikh** [comment]
@NidhiKJha for the pressed state we would sow the same tool tip we currently have, we don't have a new tooltip in the new DS 
Screenshot 2023-01-24 at 15 39 55

**Comment by SaraCheikh** [comment]
That looks good! @NidhiKJha

**Review by SaraCheikh — APPROVED** [review]

**Review by darkwing — APPROVED** [review]

**Review by SaraCheikh — APPROVED** [review]

**Review by vthomas13 — APPROVED** [review]
Looks great! Learned a lot about Typography here

**Pull request merged**
