### PR TITLE
Delete setupFetchDebugging.js

### LINKED ISSUE #10635: Review Fetch Debugging
fetch-debugging was originally added to workaround a sentry issue
https://github.com/MetaMask/metamask-extension/pull/5522

at the same time i worked on getting it fixed upstream
https://github.com/getsentry/sentry-javascript/pull/1293

latest sentry does include capturing the fetch params in the failure case
https://github.com/getsentry/sentry-javascript/blob/ac4179e6eb894617f3dd262ace3aace950262f6d/packages/utils/src/instrument.ts#L167-L177

so we can drop this file 👍

### PR DESCRIPTION
**Pull request by kumavis**
Fixes #10635

### CODE REVIEW

**Review by ryanml — CHANGES_REQUESTED** [review]
Looks like there are still references to this in `background.js`: https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/background.js#L6-L9

**Comment by kumavis** [comment]
whoops yeah that was quite sloppy. made the pr in github ui :clown_face:

**Comment by kumavis** [comment]
ready for you @ryanml

**Review by ryanml — APPROVED** [review]
lgtm!

**Pull request merged**
