### PR TITLE
Version v12.0.0

### PR DESCRIPTION
**Pull request by benjisclowder**
## **Description**

RC V12.0.0

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/25098?quickstart=1)

### CODE REVIEW

**Comment by benjisclowder** [comment]
We need teams' approval on June 14 as V12.0.0 is a huge release, to be on schedule for June 20 submission. Let's do this! :rocketship:

**Instructions for Team Review**

Review Changes: Refer to the [Release Tracker for v12.0.0](https://docs.google.com/spreadsheets/d/1tsoodlAlyvEUpkkcNcbZ4PM9HuC9cEM80RZeoVv5OCQ/edit#gid=780745957) to see all changes relevant to your team.

Log Bugs: If you find any issues, log them in the release tracker and attach them to https://github.com/MetaMask/MetaMask-planning/issues/2619.

Approval: After reviewing, indicate your team's approval by:

- Marking the checkbox next to your team's name in this comment.
- Optionally, leave a comment for additional information.

Your thorough review ensures a smooth and successful release. If you have any questions please reach out to extension platform team or in the [#metamask-qa](https://consensys.slack.com/archives/C01U65ZUS2E) slack channel. Thank you for your collaboration!

- [ ]  Accounts: @plasmacorral / @gantunesr - There are 11 Accounts changes in v12.0.0
- [ ]  Assets: @sahar-fehri / @alfeng6 - There are 13 Assets changes in v12.0.0
- [ ]  Bridging: @micaela.estabillo - There is 1 Bridging change in v12.0.0
- [ ]  Confirmations: @sleepytanya - There are 63 (crying emoji) Confirmations changes in v12.0.0.
- [ ]  Hardware Wallets: @gantunesr (please let me know if I should tag someone else here) - There is 1 Hardwarew Wallets change in v12.0.0
- [ ]  DappAPI: @jiexi - There are 9 DappAPI changes in v12.0.0.
- [ ]  Design/Systems: @georgewrmarshall - There are 8 Design/Systems change in v12.0.0.
- [ ]  Lavamoat: @legobeat - There are 21 Lavamoat changes in v12.0.0.
- [ ]  MMI: @zone-live / @shane-t - There are 7 MMI changes in v12.0.0.
- [ ]  Notifications: @BjornGunnarsson (please let me know if I should tag someone else here) - There are 28 Notifications changes in v12.0.0
- [ ]  Porfolio: @jvbriones - There are 3 Portfolio changes in v12.0.0
- [ ]  Snaps: @bowensanders / @FrederikBolding / @Montoya - There are 20 Snaps changes in v12.0.0.
- [ ]  Swaps: @davibroc / @dan437 - There is 1 Swaps change in v12.0.0.
- [ ]  Wallet Framework: @Gudahtt - There are 16 Wallet Framework changes in v12.0.0.
- [ ]  Wallet UX: @darkwing / @NidhiKJha - There are 16 Wallet UX changes in v12.0.0.

**Comment by benjisclowder** [comment]
[Manual test scenarios:](https://github.com/MetaMask/metamask-extension/tree/develop/test/scenarios)

**Chrome**
 
- [ ] Onboarding - create a wallet
- [ ]  Onboarding - import a wallet
- [ ]  Keyring - connect hardware wallet
- [ ]  Keyring - reset a wallet
- [ ]  Transactions - send native token origin MM
- [ ]  Transactions - send native token origin dapp
- [ ]  Transactions - send ERC20 token origin MM
- [ ]  Transactions - send ERC20 token origin dapp
- [ ]  Transactions - send ERC721 token origin MM
- [ ]  Transactions - send ERC721 token origin dapp
- [ ]  Transactions - speed up transaction
- [ ]  Transactions - cancel transaction
- [ ]  Transactions - deploy failing transaction
- [ ]  Transactions - deposit and withdraw
- [ ]  Transactions - navigate multiple transactions
- [ ]  Transactions - send transactions with custom nonce
- [ ]  Transactions - cancel transaction using same nonce
- [ ]  Tokens - import ERC20 token origin MM
- [ ]  Tokens - import ERC20 token origin dapp
- [ ]  Tokens - import ERC721 token origin MM
- [ ]  Tokens - import ERC721 token origin dapp
- [ ]  Tokens - import ERC1155 token origin MM
- [ ]  Tokens - import ERC1155 token origin dapp
- [ ]  Tokens - approve ERC1155 token
- [ ]  Tokens - approve ERC20 token
- [ ]  Tokens - approve ERC721 token
- [ ]  Tokens - autodetect tokens
- [ ]  Tokens - autodetect NFTs
- [ ]  Tokens - approve erc20 custom amount
- [ ]  ENS - name resolution
- [ ]  Phishing - warning page
- [ ]  Network - add custom network manually
- [ ]  Network - add custom network from the list of popular networks
- [ ]  Network - add custom network from dApp
- [ ]  Network - update networks
- [ ]  Network - switching networks
- [ ]  Network - delete networks from the dropdown list
- [ ]  Network - delete networks in Settings
- [ ]  Backup - backup user data
- [ ]  Backup - restore user data
- [ ]  Metrics - send event metrics
- [ ]  Address-book - add a contact to the address book
- [ ]  Address-book - remove a contact from the address book
- [ ]  Address-book - update a contact in the address book
- [ ]  Gas fee - EIP-1559 gas
- [ ]  Gas fee - legacy gas
- [ ]  Sign - eth sign
- [ ]  Sign - personal sign
- [ ]  Sign - sign in with ethereum
- [ ]  Sign - sign typed with data
- [ ]  Sign - sign typed data v3 with hardware wallet
- [ ]  Sign - sign typed data v4 with hardware wallet
- [ ]  Sign - personal sign with hardware wallet
- [ ]  Sign - eth sign with hardware wallet
- [ ]  Permissions - connecting and disconnecting from a dapp
- [ ]  Swap - smart swap
- [ ]  Swap - swap eth
- [ ]  Incoming transactions - receive native token
- [ ]  Settings - about MetaMask
- [ ]  Settings - general - change language
- [ ]  Settings - advanced - check custom nonce toggle
- [ ]  Settings - advanced - show hex data
- [ ]  Contract - deploy contract, mint and import NFT with hardware wallet
- [ ]  Contract - hardware wallet qr based connect
- [ ]  Contract - send token with hardware wallet

**Firefox**

- [ ]  Onboarding - create a wallet
- [ ]  Onboarding - import a wallet
- [ ]  Keyring - connect hardware wallet
- [ ]  Keyring - reset a wallet
- [ ]  Transactions - send native token origin MM
- [ ]  Transactions - send native token origin dapp
- [ ]  Transactions - send ERC20 token origin MM
- [ ]  Transactions - send ERC20 token origin dapp
- [ ]  Transactions - send ERC721 token origin MM
- [ ]  Transactions - send ERC721 token origin dapp
- [ ]  Transactions - speed up transaction
- [ ]  Transactions - cancel transaction
- [ ]  Transactions - deploy failing transaction
- [ ]  Transactions - deposit and withdraw
- [ ]  Transactions - navigate multiple transactions
- [ ]  Transactions - send transactions with custom nonce
- [ ]  Transactions - cancel transaction using same nonce
- [ ]  Tokens - import ERC20 token origin MM
- [ ]  Tokens - import ERC20 token origin dapp
- [ ]  Tokens - import ERC721 token origin MM
- [ ]  Tokens - import ERC721 token origin dapp
- [ ]  Tokens - import ERC1155 token origin MM
- [ ]  Tokens - import ERC1155 token origin dapp
- [ ]  Tokens - approve ERC1155 token
- [ ]  Tokens - approve ERC20 token
- [ ]  Tokens - approve ERC721 token
- [ ]  Tokens - autodetect tokens
- [ ]  Tokens - autodetect NFTs
- [ ]  Tokens - approve erc20 custom amount
- [ ]  ENS - name resolution
- [ ]  Phishing - warning page
- [ ]  Network - add custom network manually
- [ ]  Network - add custom network from the list of popular networks
- [ ]  Network - add custom network from dApp
- [ ]  Network - update networks
- [ ]  Network - switching networks
- [ ]  Network - delete networks from the dropdown list
- [ ]  Network - delete networks in Settings
- [ ]  Backup - backup user data
- [ ]  Backup - restore user data
- [ ]  Metrics - send event metrics
- [ ]  Address-book - add a contact to the address book
- [ ]  Address-book - remove a contact from the address book
- [ ]  Address-book - update a contact in the address book
- [ ]  Gas fee - EIP-1559 gas
- [ ]  Gas fee - legacy gas
- [ ]  Sign - eth sign
- [ ]  Sign - personal sign
- [ ]  Sign - sign in with ethereum
- [ ]  Sign - sign typed with data
- [ ]  Sign - sign typed data v3 with hardware wallet
- [ ]  Sign - sign typed data v4 with hardware wallet
- [ ]  Sign - personal sign with hardware wallet
- [ ]  Sign - eth sign with hardware wallet
- [ ]  Permissions - connecting and disconnecting from a dapp
- [ ]  Swap - smart swap
- [ ]  Swap - swap eth
- [ ]  Incoming transactions - receive native token
- [ ]  Settings - about MetaMask
- [ ]  Settings - general - change language
- [ ]  Settings - advanced - check custom nonce toggle
- [ ]  Settings - advanced - show hex data
- [ ]  Contract - deploy contract, mint and import NFT with hardware wallet
- [ ]  Contract - hardware wallet qr based connect
- [ ]  Contract - send token with hardware wallet

**Comment by georgewrmarshall** [comment]
🟢 Approved for @MetaMask/design-system

Checked the following PRs were included and working in release PR
- https://github.com/MetaMask/metamask-extension/pull/24262
- https://github.com/MetaMask/metamask-extension/pull/24411
- https://github.com/MetaMask/metamask-extension/pull/24315
- https://github.com/MetaMask/metamask-extension/pull/24760
- https://github.com/MetaMask/metamask-extension/pull/2478
- https://github.com/MetaMask/metamask-extension/pull/24781
- https://github.com/MetaMask/metamask-extension/pull/24970

**Comment by katkopel** [comment]
Firefox v.12.0.0

 
[x] Onboarding - create a wallet
[x]  Onboarding - import a wallet
- [ ]  Keyring - connect hardware wallet
[x]   Keyring - reset a wallet
[x]   Transactions - send native token origin MM
[x]  Transactions - send native token origin dapp
[x]  Transactions - send ERC20 token origin MM
[x]  Transactions - send ERC20 token origin dapp
- [ ]   Transactions - send ERC721 token origin MM
[x]   Transactions - send ERC721 token origin dapp
[x]   Transactions - speed up transaction
[x]  Transactions - cancel transaction
[x]   Transactions - deploy failing transaction
[x]  Transactions - deposit and withdraw
[x]  Transactions - navigate multiple transactions
[x]  Transactions - send transactions with custom nonce
[x]  Transactions - cancel transaction using same nonce
[x]  Tokens - import ERC20 token origin MM
[x]  Tokens - import ERC20 token origin dapp
[x]  Tokens - import ERC721 token origin MM
[x]  Tokens - import ERC721 token origin dapp
- [ ]  Tokens - import ERC1155 token origin MM
- [ ]  Tokens - import ERC1155 token origin dapp
[x]   Tokens - approve ERC1155 token
[x]   Tokens - approve ERC20 token
[x]   Tokens - approve ERC721 token
[x]   Tokens - autodetect tokens
[x]   Tokens - autodetect NFTs
[x]   Tokens - approve erc20 custom amount
[x]   ENS - name resolution
[x]   Phishing - warning page
[x]   Network - add custom network manually
[x]   Network - add custom network from the list of popular networks
[x]   Network - add custom network from dApp
[x]   Network - update networks
[x]   Network - switching networks
[x]   Network - delete networks from the dropdown list
[x]   Network - delete networks in Settings
[x]   Backup - backup user data
[x]   Backup - restore user data
[x]   Metrics - send event metrics
[x]   Address-book - add a contact to the address book
[x]   Address-book - remove a contact from the address book
[x]   Address-book - update a contact in the address book
[x]   Gas fee - EIP-1559 gas
[x]   Gas fee - legacy gas
[x]   Sign - eth sign
[x]    Sign - personal sign
[x]  Sign - sign in with ethereum
[x]   Sign - sign typed with data
- [ ]  Sign - sign typed data v3 with hardware wallet
- [ ]  Sign - sign typed data v4 with hardware wallet
- [ ]  Sign - personal sign with hardware wallet
- [ ]  Sign - eth sign with hardware wallet
[x]   Permissions - connecting and disconnecting from a dapp
[x]   Swap - smart swap
- [ ]  Swap - swap eth
[x]   Incoming transactions - receive native token
[x]   Settings - about MetaMask
[x]   Settings - general - change language

When set to Dansk, text appears in Danish and English throughout. Invalid address error appears in Danish, but certain buttons and details in the send flow are in English. When set to Magyar, the text is in both Hungarian and English. Theme & Account identicon in General always appear in English.

[x]   Settings - advanced - check custom nonce toggle
[x]   Settings - advanced - show hex data
- [ ]   Contract - deploy contract, mint and import NFT with hardware wallet
- [ ]   Contract - hardware wallet qr based connect
- [ ]   Contract - send token with hardware wallet

**Comment by gantunesr** [comment]
Approved for @MetaMask/account-management 

The validation included manual testing and/or reviewing the following PRs,

- https://github.com/MetaMask/metamask-extension/pull/24788
- https://github.com/MetaMask/metamask-extension/pull/25022
- https://github.com/MetaMask/metamask-extension/pull/24003
- https://github.com/MetaMask/metamask-extension/pull/24678
- https://github.com/MetaMask/metamask-extension/pull/24130
- https://github.com/MetaMask/metamask-extension/pull/24199
- https://github.com/MetaMask/metamask-extension/pull/24876
- https://github.com/MetaMask/metamask-extension/pull/24693

**Comment by Gudahtt** [comment]
@metamaskbot update-attributions

**Comment by Gudahtt** [comment]
@metamaskbot update-attributions

**Comment by Gudahtt** [comment]
@metamaskbot update-attributions

**Comment by danjm** [comment]
I did a final smoke test, testing the features added in this release, and it looked fine.

**Comment by danjm** [comment]
@SocketSecurity ignore-all

The new author warnings are all fine.

The rest of the warnings have to do with network access, and all come from the inclusion of firebase dependencies. This issues are known and were examined before.

**Review by danjm — APPROVED** [review]

**Pull request merged**
