### PR TITLE
Part of #17670: Replace Typography with Text component

### PR DESCRIPTION
**Pull request by omraval18**
## Explanation

Updating `<Typography/>` to `<Text/>`  in `ui/pages/swaps/smart-transaction-status/smart-transaction-status.js`

### Before

Opera Snapshot_2023-04-13_155640_localhost

### After

Opera Snapshot_2023-04-13_160842_localhost

## Manual Testing Steps

- Go to the latest build of storybook on this PR
- Search `SmartTransactionStatusLabel` in the Side Panel
- Check It against develop storybook [https://metamask.github.io/metamask-storybook/?path=/story/pages-swaps-smarttransactionstatuslabel--smart-transaction-status-label-component](url)

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [x] How reviewers can test my changes
- [x] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Comment by omraval18** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by brad-decker** [comment]
Hey there @omraval18 your first commit (the one you authored locally, versus the one you made via github UI) is under a different username which is why the CLA is failing. If you want to resolve this you'd need to set your git user email to your github email and then rebase your PR on develop. The new commit that creates will be attributed to your github username. https://stackoverflow.com/questions/28141653/does-user-name-in-git-need-to-match-my-github-username

**Comment by omraval18** [comment]
@brad-decker thanks I'll look into it!

**Review by brad-decker — APPROVED** [review]
LGTM

**Review by NidhiKJha — APPROVED** [review]

**Pull request merged**
