### PR TITLE
Update designs for Add Token screen

### LINKED ISSUE #4232: Fix Add Token List alignment and padding
Alignment of the list is off

Also in the extension the action buttons in this screen are not visible in the frame. This confused users during a usability test didn't know how to move forward in the flow. Probably should be made stick to the bottom like we do in the send flow.

### PR DESCRIPTION
**Pull request by alextsg**
Fixes #4232, #4282 

@cjeria 
image
image
image
image
image

### CODE REVIEW

**Review by cjeria — COMMENTED** [review]
Looks good. Are the input focus border highlights going to be added to inputs and textfields?

**Comment by alextsg** [comment]
@cjeria Oh thanks. I forgot to add that in. Will update PR.

**Comment by alextsg** [comment]
@cjeria Updated:
image

**Comment by cjeria** [comment]
Was the highlight color added for the custom token fields as well?

Would be good to have an "added" lozenge label to tokens that have already been added but come up in the search results. see screenshot

image

**Comment by alextsg** [comment]
Yep also applied for the input fields in Custom Token:
image

The added label is a good idea but it might be better to leave that for a separate PR, since we're still trying to figure out the best way to display all selected tokens.

**Review by cjeria — APPROVED** [review]

**Pull request merged**
