### PR TITLE
Avoid using indexes to reference first item in array

### PR DESCRIPTION
**Pull request by darkwing**
I'm hoping we can start using some of this type of modern syntax for our arrays instead of using indexes.  Feel free to reject and close, but if this flies, it would be cool to use eslint in the future to standardize this.

### CODE REVIEW

**Review by ullashb — APPROVED** [review]

**Comment by brad-decker** [comment]
Is it that the destructuring assignment conveys more meaning than the index number? Just want to make sure there aren't any performance or behavioral implications of this change

**Review by jpuri — APPROVED** [review]
👍

**Comment by darkwing** [comment]
@brad-decker Yes sir

**Comment by brad-decker** [comment]
We'll have to discuss the eslint rule implementation, but i'm in general okay with this direction.

**Review by brad-decker — APPROVED** [review]

**Pull request merged**
