### PR TITLE
Build - fix bug in empty file copying

### PR DESCRIPTION
**Pull request by kumavis**
whoops, so sorry

the source/pattern/dest copy does not quite work the way i expected :grimacing:

### CODE REVIEW

**Comment by kumavis** [comment]
develop resulted in a file called `chromereload.jsempty.js` in the prod build
this gave me an idea for a snapshot of the build output, as a sanity check
may implement in another PR

**Review by EtDu — APPROVED** [review]
ggwp

**Review by ryanml — APPROVED** [review]
++

**Comment by kumavis** [comment]
fyi @Gudahtt

**Pull request merged**
