### PR TITLE
inpage - temporarily disable ping stream

### PR DESCRIPTION
**Pull request by kumavis**
PingStream was finding false-positives for timeouts, causing issues.
This is a hot patch to disable it until a better solution is found.
See https://github.com/MetaMask/metamask-plugin/issues/746

### CODE REVIEW

**Review by danfinlay — APPROVED** [review]
Sad but better than the infinite reload bug, while we figure it out.  Maybe bump the changelog?

**Comment by flyswatter** [comment]
Ahh and you can't include unused vars, so need to uncomment the `pingChannel` module (linter note).

**Comment by flyswatter** [comment]
Also: Expected space or tab after '//' in comment  spaced-comment (linter /2)

**Comment by kumavis** [comment]
sorry bout all that
@flyswatter please merge when ready

**Pull request merged**
