### PR TITLE
Feat: add linea sepolia network

### PR DESCRIPTION
**Pull request by VGau**
## **Description**

- A new Linea Sepolia network will be released soon. This PR adds support for the Linea Sepolia network in the MetaMask extension.
- Deprecate Linea Goerli network

## **Related issues**

Fixes:

## **Manual testing steps**

For Linea Sepolia :

- Select Linea Sepolia network
- Send a transaction
- Check the transaction result in the explorer
- Make sure the Linea Sepolia network is display in the network settings page

For Linea Goerli deprecation :

- Select Linea Goerli network
- Check that Linea Goerli deprecation message is display at the bottom of the screen

### **After**

https://github.com/MetaMask/metamask-extension/assets/85494462/96d5cf6b-f784-4d0b-aa85-e76193025923

## **Pre-merge author checklist**

- [X] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [X] I've included manual testing steps
- [X] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [X] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [X] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by mcmire — DISMISSED** [review]
This looks good to me from a Shared Libraries perspective. We've already upgraded `approval-controller`, `transaction-controller`, and `network-controller` in a previous PR, so as long as we're okay with just sending transactions working then this PR makes sense to me.

**Review by DDDDDanica — DISMISSED** [review]

**Comment by VGau** [comment]
@metamaskbot update-policies

**Comment by sahar-fehri** [comment]
update-policies

**Comment by VGau** [comment]
@metamaskbot update-policies

**Review by sahar-fehri — APPROVED** [review]

**Review by DDDDDanica — APPROVED** [review]

**Pull request merged**
