### PR TITLE
Version v11.8.0

### PR DESCRIPTION
**Pull request by chloeYue**
## **Description**

RC v11.8.0

### CODE REVIEW

**Comment by chloeYue** [comment]
Manual test scenarios:

Chrome

- [ ] Onboarding - create a wallet
- [ ] Onboarding - import a wallet
- [ ] Keyring - connect hardware wallet
- [ ] Keyring - reset a wallet
- [ ] Transactions - send native token origin MM
- [ ] Transactions - send native token origin dapp
- [ ] Transactions - send ERC20 token origin MM
- [ ] Transactions - send ERC20 token origin dapp
- [ ] Transactions - send ERC721 token origin MM
- [ ] Transactions - send ERC721 token origin dapp
- [ ] Transactions - speed up transaction
- [ ] Transactions - cancel transaction
- [ ] Tokens - import ERC20 token origin MM
- [ ] Tokens - import ERC20 token origin dapp
- [ ] Tokens - import ERC721 token origin MM
- [ ] Tokens - import ERC721 token origin dapp
- [ ] Tokens - import ERC1155 token origin MM
- [ ] Tokens - approve ERC1155 token
- [ ] Tokens - approve ERC20 token
- [ ] Tokens - approve ERC721 token
- [ ] Tokens - autodetect tokens
- [ ] Tokens - autodetect NFTs
- [ ] ENS - name resolution
- [ ] Phishing - warning page
- [ ] Network - add custom network manually
- [ ] Network - add custom network from the list of popular networks
- [ ] Network - add custom network from dApp
- [ ] Network - update networks
- [ ] Network - switching networks
- [ ] Network - delete networks from the dropdown list
- [ ] Network - delete networks in Settings
- [ ] Backup - backup user data
- [ ] Backup - restore user data
- [ ] Metrics - send event metrics
- [ ] Address-book - add a contact to the address book
- [ ] Address-book - remove a contact from the address book
- [ ] Address-book - update a contact in the address book
- [ ] Gas fee - EIP-1559 gas
- [ ] Gas fee - legacy gas
- [ ] Sign - eth sign
- [ ] Sign - personal sign
- [ ] Sign - sign in with ethereum
- [ ] Sign - sign typed with data
- [ ] Permissions - connecting and disconnecting from a dapp
- [ ] Swap - smart swap
- [ ] Swap - swap eth
- [ ] Incoming transactions - receive native token

Firefox

- [ ] Onboarding - create a wallet
- [ ] Onboarding - import a wallet
- [ ] Keyring - connect hardware wallet
- [ ] Keyring - reset a wallet
- [ ] Transactions - send native token origin MM
- [ ] Transactions - send native token origin dapp
- [ ] Transactions - send ERC20 token origin MM
- [ ] Transactions - send ERC20 token origin dapp
- [ ] Transactions - send ERC721 token origin MM
- [ ] Transactions - send ERC721 token origin dapp
- [ ] Transactions - speed up transaction
- [ ] Transactions - cancel transaction
- [ ] Tokens - import ERC20 token origin MM
- [ ] Tokens - import ERC20 token origin dapp
- [ ] Tokens - import ERC721 token origin MM
- [ ] Tokens - import ERC721 token origin dapp
- [ ] Tokens - import ERC1155 token origin MM
- [ ] Tokens - approve ERC1155 token
- [ ] Tokens - approve ERC20 token
- [ ] Tokens - approve ERC721 token
- [ ] Tokens - autodetect tokens
- [ ] Tokens - autodetect NFTs
- [ ] ENS - name resolution
- [ ] Phishing - warning page
- [ ] Network - add custom network manually
- [ ] Network - add custom network from the list of popular networks
- [ ] Network - add custom network from dApp
- [ ] Network - update networks
- [ ] Network - switching networks
- [ ] Network - delete networks from the dropdown list
- [ ] Network - delete networks in Settings
- [ ] Backup - backup user data
- [ ] Backup - restore user data
- [ ] Metrics - send event metrics
- [ ] Address-book - add a contact to the address book
- [ ] Address-book - remove a contact from the address book
- [ ] Address-book - update a contact in the address book
- [ ] Gas fee - EIP-1559 gas
- [ ] Gas fee - legacy gas
- [ ] Sign - eth sign
- [ ] Sign - personal sign
- [ ] Sign - sign in with ethereum
- [ ] Sign - sign typed with data
- [ ] Permissions - connecting and disconnecting from a dapp
- [ ] Swap - smart swap
- [ ] Swap - swap eth
- [ ] Incoming transactions - receive native token

**Comment by benjisclowder** [comment]
Release tracker for change validation on v11.8.0:
https://docs.google.com/spreadsheets/d/1tsoodlAlyvEUpkkcNcbZ4PM9HuC9cEM80RZeoVv5OCQ/edit#gid=154790624

 MMI: @zone-live / @shane-t - There are 9 MMI changes in v11.8.0. We would like to get your team's approval on this release by next Tuesday.
 Snaps: @bowensanders / @FrederikBolding / @Montoya - There are 7 Snaps changes in v11.8.0. We would like to get your team's approval on this release by next Tuesday.
 Confirmation UX: @seaona - There are 4 Confirmations UX changes in v11.8.0. We would like to get your team's approval on this release by next Tuesday.
 Confirmation Systems: @sleepytanya - There is 1 Confirmation Systems change in v11.8.0. We would like to get your team's approval on this release by next Tuesday.
 Accounts: @plasmacorral - There is 1 Accounts change in v11.8.0. We would like to get your team's approval on this release by next Tuesday.
 Assets: @sahar-fehri / @alfeng6 - There are 2 Assets changes in v11.8.0. We would like to get your team's approval on this release by next Tuesday.
 Design/Systems: @georgewrmarshall - There are 3 Design/Systems changes in v11.8.0. We would like to get your team's approval on this release by next Tuesday.
 Dapp API: @tmashuang - There are 3 Dapp API changes in v11.8.0. We would like to get your team's approval on this release by next Tuesday.
 Devex: @tmashuang / @vandan - There are 2 Devex changes in v11.8.0. We would like to get your team's approval on this release by next Tuesday.
 Swaps: @davibroc / @dan437 - There is 1 Swaps change in v11.8.0. We would like to get your team's approval on this release by next Tuesday.
 
Note: please attach all the release bugs to this bug report epic here: https://github.com/MetaMask/MetaMask-planning/issues/1792

Thank you so much!

**Comment by sleepytanya** [comment]
Confirmations System team approval:
I verified the changes in the [PR](https://github.com/MetaMask/metamask-extension/pull/21840) - only one incoming transaction is visible after `cancel`.
Screenshot 2023-12-11 at 9 52 40 AM
Screenshot 2023-12-11 at 9 52 54 AM

**Comment by PressGarden** [comment]
> Firefox
> 
> * [x]  Onboarding - create a wallet
> * [x]  Onboarding - import a wallet
> * [ ]  Keyring - connect hardware wallet - Not able to perform test, do not own Trezor and Ledger does not work with FireFox.
> * [x]  Keyring - reset a wallet
> * [x]  Transactions - send native token origin MM
> * [x]  Transactions - send native token origin dapp
> * [x]  Transactions - send ERC20 token origin MM
> * [x]  Transactions - send ERC20 token origin dapp
> * [x]  Transactions - send ERC721 token origin MM
> * [x]  Transactions - send ERC721 token origin dapp
> * [x]  Transactions - speed up transaction
> * [x]  Transactions - cancel transaction
> * [x]  Tokens - import ERC20 token origin MM
> * [x]  Tokens - import ERC20 token origin dapp
> * [x]  Tokens - import ERC721 token origin MM
> * [x]  Tokens - import ERC721 token origin dapp
> * [x]  Tokens - import ERC1155 token origin MM
> * [x]  Tokens - approve ERC1155 token

> * [ ]  Tokens - approve ERC20 token - Spending cap approval does not process, requires custom nonce to cancel transaction from pending

image

> * [x]  Tokens - approve ERC721 token
> * [x]  Tokens - autodetect tokens
> * [x]  Tokens - autodetect NFTs

> * [ ]  ENS - name resolution - ENS name does not resolve. Error "No address has been set for this name"

image

image

> * [x]  Phishing - warning page
> * [x]  Network - add custom network manually
> * [x]  Network - add custom network from the list of popular networks
> * [x]  Network - add custom network from dApp
> * [x]  Network - update networks
> * [x]  Network - switching networks
> * [x]  Network - delete networks from the dropdown list
> * [x]  Network - delete networks in Settings
> * [x]  Backup - backup user data
> * [x]  Backup - restore user data
> * [x]  Metrics - send event metrics
> * [x]  Address-book - add a contact to the address book
> * [x]  Address-book - remove a contact from the address book
> * [x]  Address-book - update a contact in the address book

> * [ ]  Gas fee - EIP-1559 gas - Transaction does not complete, even with speed up set to aggressive settings

image

> * [ ]  Gas fee - legacy gas - Same issue as above, transaction does not complete, even with speed up, have to use custom nonce to cancel transaction

image

> * [x]  Sign - eth sign
> * [x]  Sign - personal sign
> * [x]  Sign - sign in with ethereum
> * [x]  Sign - sign typed with data
> * [x]  Permissions - connecting and disconnecting from a dapp

> * [ ]  Swap - smart swap - advised to exclude this test
> * [ ]  Swap - swap eth - advised to exclude this test

> * [x]  Incoming transactions - receive native token

**Comment by benjisclowder** [comment]
> > Firefox QA testing ext v11.8.0
> > 
> > * [x]   Onboarding - create a wallet
> > * [x]   Onboarding - import a wallet
> > * [ ]   Keyring - connect hardware wallet - Not able to perform test, do not own Trezor and Ledger does not work with FireFox.
> > * [x]   Keyring - reset a wallet
> > * [x]   Transactions - send native token origin MM
> > * [x]   Transactions - send native token origin dapp
> > * [x]   Transactions - send ERC20 token origin MM
> > * [x]   Transactions - send ERC20 token origin dapp
> > * [x]   Transactions - send ERC721 token origin MM
> > * [x]   Transactions - send ERC721 token origin dapp
> > * [x]   Transactions - speed up transaction
> > * [x]   Transactions - cancel transaction
> > * [x]   Tokens - import ERC20 token origin MM
> > * [x]   Tokens - import ERC20 token origin dapp
> > * [x]   Tokens - import ERC721 token origin MM
> > * [x]   Tokens - import ERC721 token origin dapp
> > * [x]   Tokens - import ERC1155 token origin MM
> > * [x]   Tokens - approve ERC1155 token
> 
> > * [ ]   Tokens - approve ERC20 token - Spending cap approval does not process, requires custom nonce to cancel transaction from pending
> 
> image
> 
> > * [x]   Tokens - approve ERC721 token
> > * [x]   Tokens - autodetect tokens
> > * [x]   Tokens - autodetect NFTs
> 
> > * [ ]   ENS - name resolution - ENS name does not resolve. Error "No address has been set for this name"
> 
> image
> 
> image
> 
> > * [x]   Phishing - warning page
> > * [x]   Network - add custom network manually
> > * [x]   Network - add custom network from the list of popular networks
> > * [x]   Network - add custom network from dApp
> > * [x]   Network - update networks
> > * [x]   Network - switching networks
> > * [x]   Network - delete networks from the dropdown list
> > * [x]   Network - delete networks in Settings
> > * [x]   Backup - backup user data
> > * [x]   Backup - restore user data
> > * [x]   Metrics - send event metrics
> > * [x]   Address-book - add a contact to the address book
> > * [x]   Address-book - remove a contact from the address book
> > * [x]   Address-book - update a contact in the address book
> 
> > * [ ]   Gas fee - EIP-1559 gas - Transaction does not complete, even with speed up set to aggressive settings
> 
> image
> 
> > * [ ]   Gas fee - legacy gas - Same issue as above, transaction does not complete, even with speed up, have to use custom nonce to cancel transaction
> 
> image
> 
> > * [x]   Sign - eth sign
> > * [x]   Sign - personal sign
> > * [x]   Sign - sign in with ethereum
> > * [x]   Sign - sign typed with data
> > * [x]   Permissions - connecting and disconnecting from a dapp
> 
> > * [ ]   Swap - smart swap - advised to exclude this test
> > * [ ]   Swap - swap eth - advised to exclude this test
> 
> > * [x]   Incoming transactions - receive native token

@PressGarden thank you for these. I will run what couldn't be covered and check out what seemed to have issues. As a side note, for most of these, console info instead of network info would provide more relevant context or even actual errors.

**Comment by benjisclowder** [comment]
> > Firefox QA testing ext v11.8.0
> > 
> > * [x]   Onboarding - create a wallet
> > * [x]   Onboarding - import a wallet
> > * [ ]   Keyring - connect hardware wallet - Not able to perform test, do not own Trezor and Ledger does not work with FireFox.
> > * [x]   Keyring - reset a wallet
> > * [x]   Transactions - send native token origin MM
> > * [x]   Transactions - send native token origin dapp
> > * [x]   Transactions - send ERC20 token origin MM
> > * [x]   Transactions - send ERC20 token origin dapp
> > * [x]   Transactions - send ERC721 token origin MM
> > * [x]   Transactions - send ERC721 token origin dapp
> > * [x]   Transactions - speed up transaction
> > * [x]   Transactions - cancel transaction
> > * [x]   Tokens - import ERC20 token origin MM
> > * [x]   Tokens - import ERC20 token origin dapp
> > * [x]   Tokens - import ERC721 token origin MM
> > * [x]   Tokens - import ERC721 token origin dapp
> > * [x]   Tokens - import ERC1155 token origin MM
> > * [x]   Tokens - approve ERC1155 token
> 
> > * [ ]   Tokens - approve ERC20 token - Spending cap approval does not process, requires custom nonce to cancel transaction from pending
> 
> image
> 
> > * [x]   Tokens - approve ERC721 token
> > * [x]   Tokens - autodetect tokens
> > * [x]   Tokens - autodetect NFTs
> 
> > * [ ]   ENS - name resolution - ENS name does not resolve. Error "No address has been set for this name"
> 
> image
> 
> image
> 
> > * [x]   Phishing - warning page
> > * [x]   Network - add custom network manually
> > * [x]   Network - add custom network from the list of popular networks
> > * [x]   Network - add custom network from dApp
> > * [x]   Network - update networks
> > * [x]   Network - switching networks
> > * [x]   Network - delete networks from the dropdown list
> > * [x]   Network - delete networks in Settings
> > * [x]   Backup - backup user data
> > * [x]   Backup - restore user data
> > * [x]   Metrics - send event metrics
> > * [x]   Address-book - add a contact to the address book
> > * [x]   Address-book - remove a contact from the address book
> > * [x]   Address-book - update a contact in the address book
> 
> > * [ ]   Gas fee - EIP-1559 gas - Transaction does not complete, even with speed up set to aggressive settings
> 
> image
> 
> > * [ ]   Gas fee - legacy gas - Same issue as above, transaction does not complete, even with speed up, have to use custom nonce to cancel transaction
> 
> image
> 
> > * [x]   Sign - eth sign
> > * [x]   Sign - personal sign
> > * [x]   Sign - sign in with ethereum
> > * [x]   Sign - sign typed with data
> > * [x]   Permissions - connecting and disconnecting from a dapp
> 
> > * [ ]   Swap - smart swap - advised to exclude this test
> > * [ ]   Swap - swap eth - advised to exclude this test
> 
> > * [x]   Incoming transactions - receive native token

Hey! Regarding ENS, it does not yet support Sepolia. Some steps have been taken in this direction a while back but were left unresolved. We will get back with updates once we have them. In the meantime, any main network should work for ENS testing, as well as Goerli until it is deprecated.

**Comment by seaona** [comment]
**Confirmations UX**: [this PR](https://github.com/MetaMask/metamask-extension/pull/21399) needs to be reverted from the RC branch. We give the QA approval - considering the PR will be reverted
cc @danjm  @benjisclowder @chloeYue

**Comment by plasmacorral** [comment]
Accounts team approval wrt PR 21437

Tested Chrome 117.0.5938.92 and Firefox 121.0.  Migration 105 performed as expected, and no new issues observed with Lattice, Ledger, QR, or Trezor.

**Comment by seaona** [comment]
:green_circle: Confirmation UX QA Sign Off @chloeYue @benjisclowder @danjm 

cc @cryptotavares @bschorchit

**Comment by danjm** [comment]
@SocketSecurity ignore-all

The mentioned package is one we own, and the mentioned author is a bot we control

**Review by danjm — APPROVED** [review]

**Pull request merged**
