### PR TITLE
Address resubmit bug

### PR DESCRIPTION
**Pull request by danfinlay**
Added some notes, and one possible approach at a fix, for discussion.

### CODE REVIEW

**Comment by danfinlay** [comment]
A user submitted a transaction from their MetaMask, and found it resulted in 20 nearly-identical transactions (apart from the nonce).

In their state logs, those 20 transactions were one, but in that one transaction’s history we could see:

1. Its initialization
2. A series of 20 empty arrays.
3. A series of nonce increments, signatures, and submission attempts.

So it seemed clear that MetaMask had in fact submitted these transactions.

Upon reviewing the transaction controller, Frankie identified the approveTransaction function as a point of interest.

This function performs three critical and related operations:
- Increment nonce
- Sign
- Publish

She also noted that this function is called by the pending-tx-tracker in one place:
https://github.com/MetaMask/metamask-extension/blob/2a7278eb7eb4c1895c5beebda2a0ea1e80bc4037/app/scripts/controllers/transactions/pending-tx-tracker.js#L113

This resubmitTx function is called upon each new block, and because of our “network silent mode”, we call this function repeatedly in a loop when reconnecting to the internet and “catching up” to the current block.

This theory explains the mysterious chain of 23 empty arrays, because the approveTransaction function begins by setting the transaction status to approved, an operation that shows up as an empty array in the history when the tx status is already approved.

When we review the approveTransaction function in this context, it becomes clear that it is filled with asynchronous operations, like getting a nonce, and getting a signature, and publishing, which should not be done while it is being done with another copy of the same transaction.
 One question that came up, is why can the pending-tx-tracker sign transactions? It should only possess signed transactions, and should only need network access. The answer was found on this line: https://github.com/MetaMask/metamask-extension/blob/2a7278eb7eb4c1895c5beebda2a0ea1e80bc4037/app/scripts/controllers/transactions/index.js#L98

It turns out we began passing it approved transactions to mitigate an issue where a system interruption could leave “approved” transactions hanging, never getting signed.

I proposed the simplest solution I could, which was a very simple lock around the `approveTransaction` function, which ensures it cannot process on a transaction that it is already processing on. I believe this is a simple fix that will alleviate the danger at hand.

There is still room for a better cleanup of this code. The un-sticking of transactions that need to be signed could be broken into its own function, which becomes the part that requires locking, while the pendingTxTracker would no longer need access to a signing method.

That said, this is a scary bug that could result in much worse loss than it did, and so I propose we merge this quick fix for now, and can submit a cleaner fix later.

**Comment by danfinlay** [comment]
In retrospect, it makes sense that this bug was rare, because it required some kind of network interruption in the moment between user approval and transaction signing. It then required the user to regain network access, and MetaMask to rapidly attempt to catch up with blocks all before the transaction's initial nonce could be calculated.

**Review by frankiebee — APPROVED** [review]
is good as a hot fix

**Comment by frankiebee** [comment]
would still like one other person to review if possible

**Review by Gudahtt — APPROVED** [review]
Excellent writeup! Seems like a pretty reasonable solution for the time being.

**Comment by RLlane9** [comment]
Merge

**Pull request merged**
