### PR TITLE
[i18n:zh_CN] Update messages.json

### PR DESCRIPTION
**Pull request by baixiaoyu2997**
typo

Fixes: #

Explanation:  

Manual testing steps:  
  - 
  - 
  -

### CODE REVIEW

**Comment by baixiaoyu2997** [comment]
> **CLA Signature Action:**
> 
> Thank you for your submission, we really appreciate it. We ask that you read and sign our [Contributor License Agreement](https://metamask.io/cla.html) before we can accept your contribution. You can sign the CLA by just by adding a comment to this pull request with this exact sentence:
> 
> > _**I have read the CLA Document and I hereby sign the CLA**_
> 
> By commenting with the above message you are agreeing to the terms of the CLA. Your account will be recorded as agreeing to our CLA so you don't need to sign it again for future contributions to this repository.
> 
> **0** out of **1** committers have signed the CLA. ❌ @baixiaoyu2997

I have read the CLA Document and I hereby sign the CLA

**Comment by mcmire** [comment]
Hey, thanks for the PR. We have a lot of new translations coming in via #13206, so I'll wait until that's merged first before looking at this.

**Comment by brad-decker** [comment]
@baixiaoyu2997 thanks for being patient with us, and apologies for the delay in response. Our translation system is now active but we still welcome community corrections. If you'd like to see this merged please rebase and fix any conflicts, then tag me for review. Thanks for your submission!

**Comment by brad-decker** [comment]
Thank you for your contribution, @baixiaoyu2997 -- I am closing this for now due to inactivity, but if you want to rebase this and get it ready for review you may reopen at any time!

**Pull request closed without merging**
