### PR TITLE
Interface enhancements

### PR DESCRIPTION
**Pull request by luisivan**
Hey there!

I really like MetaMask so wanted to help a little bit on the UI front. Wrap up of changes:

- Beautified, bigger buttons in some views (such as disclaimer and unlock)
- Account name is now a `contenteditable`, so it's saved in real time as you type and it feels much more natural
- Hidden Ethereum address by default on account details: That's why the copy & QR code buttons are there
- Hidden small logo on the left corner: it's already shown in the extension's button!
- Tooltips are fixed in position: That's kind of a good pattern to follow

Please let me know what you think about these changes. I really want to help and would totally continue with more significant enhancements if they are welcome!

Luis

### CODE REVIEW

**Review by 2-am-zzz — APPROVED** [review]
From my perspective, looks good to me! Thanks for your contribution ^_^.

**Comment by flyswatter** [comment]
Wow, @luisivan!  This is very exciting, partly because it's the biggest PR we've ever gotten from outside the core team!

Let's take a look (will discuss in next comment so I can see the images):

A:
screen shot 2016-12-14 at 2 52 16 pm

B:
screen shot 2016-12-14 at 2 52 10 pm

C:
screen shot 2016-12-14 at 2 48 35 pm

D:
screen shot 2016-12-14 at 2 47 22 pm

E:
screen shot 2016-12-14 at 2 47 09 pm

F:
screen shot 2016-12-14 at 2 46 55 pm

**Comment by flyswatter** [comment]
1. I *think* I could use a little more side padding on the text area in the terms & conditions (A&B), curious about others' thoughts.
2. This `contenteditable` is surprisingly cool, I just got schooled on this, it's a way better interaction for renaming accounts.
3. Smaller "No tx history" message looks cleaner.
4. Smaller identicons look a little tighter, I don't mind it at all, I'm in favor.
5. Hover messages no longer follow the cursor, but are fixed to the subject, this seems more professional.
6. On `F`, since we don't have the `Create` button taking as much space, I think the other elements should probably be spaced downward to fill in the remaining space.  I would probably try to achieve this with flex-box, but if that isn't your speciality I'd be willing to clean it up from there.

Would love to hear @kumavis's thoughts too.

**Comment by flyswatter** [comment]
Oh I almost missed the lock screen.  I think we'll want to add a little more spacing to it, like I suggested for `F`:

screen shot 2016-12-14 at 3 01 01 pm

**Comment by frankiebee** [comment]
I personally think the fox need even a little more top margin then that @flyswatter.

**Comment by flyswatter** [comment]
Oh also worth mentioning the new center "Metamask" title bar spacing has shoved the sandwich-menu off the right edge of the screen.

**Comment by flyswatter** [comment]
Anyways, my feedback amounts to some small changes, but overall I really like the direction & love that's on this PR.  If you're interested in continued contributions I'd want to encourage them, I might even want to ask your opinion on some upcoming feature designs... ;D

**Comment by flyswatter** [comment]
@frankiebee I wasn't showing a proposed top margin, I was showing a different view as it exists in this PR.  I think they both need their vertical spacing re-adjusted.

**Comment by frankiebee** [comment]
oh woops i see now

**Review by kumavis — CHANGES_REQUESTED** [review]
Haven't taken it for a test drive yet, but looks great.
I especially like that there is less code than before.

We need to fix the hamburger menu.

We should revisit auto-screenshotting.

**Comment by kumavis** [comment]
I think the readability of terms and conditions could be improved but its not blocking this PR

**Review by danfinlay — APPROVED** [review]
I'm willing to make the changes I've requested, and merge first.

**Comment by flyswatter** [comment]
Just so you know, @luisivan, this `dev` branch may take a little longer to get to production than usual, probably like January 2nd, because this branch includes a considerable refactor that is still pending a couple pieces.

**Comment by luisivan** [comment]
Wow thanks a lot everyone for the warm welcome! @flyswatter the suggestions sounds great, and thanks for the willingness to implement them. Regarding the upcoming features design, I'd love to hear about them! What's the best communication channel for that?

**Comment by flyswatter** [comment]
Step one is join our slack:

http://slack.metamask.io/

- Dan

**Pull request merged**
