### PR TITLE
Deprecate extensionizer for webextension-polyfill

### LINKED ISSUE #21: TODO: Deprecate in favor of webextension-polyfill
The [`webextension-polyfill`](https://github.com/mozilla/webextension-polyfill) project has similar goals to this project, and offers a nicer API. We should consider deprecating this project in favor of `webextension-polyfill`.

I'm not entirely sure the goals of the two projects are the same though, as they explicitly don't want to support non-standard features. If that's something we want, then maybe it's still worth maintaining this project.

----------

_Edit by @rekmarks:_ We are going to do this.

### PR DESCRIPTION
**Pull request by adonesky1**
Fixes: https://github.com/MetaMask/extensionizer/issues/21

Deprecates our use of our own `extensionizer` package for [`webextension-polyfill`](https://github.com/mozilla/webextension-polyfill) as called for [here](https://github.com/MetaMask/extensionizer/issues/21). 

This work is part of [our ongoing project to support Manifest Version 3](https://www.notion.so/Chrome-Extension-Version-MV3-Migration-19063a3ee9af46c48f18bf8e8f7aa546)

### CODE REVIEW

**Comment by adonesky1** [comment]
Getting stuck with this error (no stack trace) when trying to run these changes in Firefox.
Screen Shot 2022-03-16 at 3 46 31 PM

When I attempt to open the UI:
Screen Shot 2022-03-16 at 3 47 03 PM

No such errors when running on Chrome...

Other context [`webextension-polyfill` readme says](https://github.com/mozilla/webextension-polyfill):
```
On Firefox, this library is actually acting as a NO-OP: it detects that the browser API object is already defined and it does not create any custom wrappers. Firefox is still included in the automated tests, to ensure that no wrappers are being created when running on Firefox, and for comparison with the behaviors implemented by the library on Chrome.
```

cc @kumavis @jpuri

**Review by jpuri — APPROVED** [review]
Great work 👍

**Review by mcmire — APPROVED** [review]
Wow, this is awesome! Suspiciously easy :)

**Comment by adonesky1** [comment]
> Suspiciously easy :)

not how it felt 😔haha I was being an idiot and it took like 2 days of fighting tests!

**Pull request merged**
