### PR TITLE
chore: Bump logging-controller to 3.0.1 and signature-controller to 14.0.1

### PR DESCRIPTION
**Pull request by mcmire**
## **Description**

Specifically, `@metamask/logging-controller` 3.0.0 relies on a new version of `@metamask/base-controller` which protects state from being mutated accidentally and includes more type safety for messengers, among other improvements.

EDIT @mikesposito: Since `@metamask/signature-controller@<^14` relies on `@metamask/logging-controller@^2`, the two packages are being updated atomically

See changelogs: 
- https://github.com/MetaMask/core/blob/main/packages/logging-controller/CHANGELOG.md
- https://github.com/MetaMask/core/blob/main/packages/signature-controller/CHANGELOG.md

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/24143?quickstart=1)

## **Related issues**

Progresses #24140.

## **Manual testing steps**

This upgrade contains no functional changes.

## **Screenshots/Recordings**

(N/A)

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by mcmire** [comment]
@metamaskbot update-policies

**Review by mikesposito — DISMISSED** [review]

**Comment by mikesposito** [comment]
@metamaskbot update-policies

**Comment by mikesposito** [comment]
As suggested by @legobeat, I included the `signature-controller` bump to `^14.0.1` in this PR and changed title and description accordingly

**Review by legobeat — DISMISSED** [review]
LGTM. I believe the failing CI jobs are spurious and unrelated.

**Review by legobeat — APPROVED** [review]

**Review by cryptodev-2s — APPROVED** [review]
LGTM!

**Pull request merged**
