### PR TITLE
Version v11.11.0

### PR DESCRIPTION
**Pull request by chloeYue**
## **Description**

RC v11.11.0

### CODE REVIEW

**Comment by chloeYue** [comment]
Bug report for v11.11.0: https://github.com/MetaMask/MetaMask-planning/issues/2068

**Comment by benjisclowder** [comment]
**Manual test scenarios:**

**Chrome**

- [ ]  Onboarding - create a wallet
- [ ]  Onboarding - import a wallet
- [ ]  Keyring - connect hardware wallet
- [ ]  Keyring - reset a wallet
- [ ]  Transactions - send native token origin MM
- [ ]  Transactions - send native token origin dapp
- [ ]  Transactions - send ERC20 token origin MM
- [ ]  Transactions - send ERC20 token origin dapp
- [ ]  Transactions - send ERC721 token origin MM
- [ ]  Transactions - send ERC721 token origin dapp
- [ ]  Transactions - speed up transaction
- [ ]  Transactions - cancel transaction
- [ ]  Tokens - import ERC20 token origin MM
- [ ]  Tokens - import ERC20 token origin dapp
- [ ]  Tokens - import ERC721 token origin MM 
- [ ]  Tokens - import ERC721 token origin dapp
- [ ]  Tokens - import ERC1155 token origin MM 
- [ ]  Tokens - import ERC1155 token origin dapp 
- [ ]  Tokens - approve ERC1155 token
- [ ]  Tokens - approve ERC20 token
- [ ]  Tokens - approve ERC721 token
- [ ]  Tokens - autodetect tokens
- [ ]  Tokens - autodetect NFTs 
- [ ]  ENS - name resolution
- [ ]  Phishing - warning page
- [ ]  Network - add custom network manually
- [ ]  Network - add custom network from the list of popular networks
- [ ]  Network - add custom network from dApp
- [ ]  Network - update networks
- [ ]  Network - switching networks
- [ ]  Network - delete networks from the dropdown list
- [ ]  Network - delete networks in Settings
- [ ]  Backup - backup user data
- [ ]  Backup - restore user data
- [ ]  Metrics - send event metrics
- [ ]  Address-book - add a contact to the address book
- [ ]  Address-book - remove a contact from the address book
- [ ]  Address-book - update a contact in the address book
- [ ]  Gas fee - EIP-1559 gas
- [ ]  Gas fee - legacy gas
- [ ]  Sign - eth sign
- [ ]  Sign - personal sign
- [ ]  Sign - sign in with ethereum
- [ ]  Sign - sign typed with data
- [ ]  Permissions - connecting and disconnecting from a dapp
- [ ]  Swap - smart swap
- [ ]  Swap - swap eth
- [ ]  Incoming transactions - receive native token

**Firefox**

- [ ] Onboarding - create a wallet
- [ ]  Onboarding - import a wallet
- [ ]  Keyring - connect hardware wallet
- [ ]  Keyring - reset a wallet
- [ ]  Transactions - send native token origin MM
- [ ]  Transactions - send native token origin dapp
- [ ]  Transactions - send ERC20 token origin MM
- [ ]  Transactions - send ERC20 token origin dapp
- [ ]  Transactions - send ERC721 token origin MM
- [ ]  Transactions - send ERC721 token origin dapp
- [ ]  Transactions - speed up transaction
- [ ]  Transactions - cancel transaction
- [ ]  Tokens - import ERC20 token origin MM
- [ ]  Tokens - import ERC20 token origin dapp
- [ ]  Tokens - import ERC721 token origin MM 
- [ ]  Tokens - import ERC721 token origin dapp
- [ ]  Tokens - import ERC1155 token origin MM 
- [ ]  Tokens - import ERC1155 token origin dapp
- [ ]  Tokens - approve ERC1155 token
- [ ]  Tokens - approve ERC20 token
- [ ]  Tokens - approve ERC721 token
- [ ]  Tokens - autodetect tokens
- [ ]  Tokens - autodetect NFTs
- [ ]  ENS - name resolution
- [ ]  Phishing - warning page
- [ ]  Network - add custom network manually
- [ ]  Network - add custom network from the list of popular networks
- [ ]  Network - add custom network from dApp
- [ ]  Network - update networks
- [ ]  Network - switching networks
- [ ]  Network - delete networks from the dropdown list
- [ ]  Network - delete networks in Settings
- [ ]  Backup - backup user data
- [ ]  Backup - restore user data
- [ ]  Metrics - send event metrics
- [ ]  Address-book - add a contact to the address book
- [ ]  Address-book - remove a contact from the address book
- [ ]  Address-book - update a contact in the address book
- [ ]  Gas fee - EIP-1559 gas
- [ ]  Gas fee - legacy gas
- [ ]  Sign - eth sign
- [ ]  Sign - personal sign
- [ ]  Sign - sign in with ethereum
- [ ]  Sign - sign typed with data
- [ ]  Permissions - connecting and disconnecting from a dapp
- [ ]  Swap - smart swap
- [ ]  Swap - swap eth
- [ ]  Incoming transactions - receive native token

**Comment by benjisclowder** [comment]
Release tracker for change validation on v11.11.0:
https://docs.google.com/spreadsheets/d/1tsoodlAlyvEUpkkcNcbZ4PM9HuC9cEM80RZeoVv5OCQ/edit#gid=1705023040

We need teams' approval on 19th of Feb at the latest.

- [ ] Snaps: @bowensanders / @FrederikBolding / @Montoya - There are 5 Snaps changes in v11.11.0.
- [ ]  Confirmation UX: @seaona - There are 7 Confirmations UX changes in v11.11.0.
- [ ]  Confirmation Systems: @sleepytanya - There are 10 Confirmation Systems changes in v11.11.0.
- [ ]  Accounts: @plasmacorral - There are 4 Accounts changes in v11.11.0.
- [ ]  Extension UX: @darkwing / @NidhiKJha - There are 4 Extension UX changes in v11.11.0.
- [ ]  MMI: @zone-live / @shane-t - There are 2 MMI changes in v11.11.0.
- [ ]  Design/Systems: @georgewrmarshall - There are 3 Design/Systems changes in v11.11.0. 
- [ ]  Devex: @tmashuang / @vandan - There is 1 Devex change in v11.11.0.

Note: please attach all the release bugs to this bug report epic here: https://github.com/MetaMask/MetaMask-planning/issues/2068

Thank you so much!

**Comment by A-Feder** [comment]
@benjisclowder below my findings for the  **Manual tests** on **Chrome**

**FAILED**
Keyring - connect hardware wallet

Unknown error after connecting, the flow does not proceed and the device is shown as already paired
Screenshot 2024-02-13 at 11 06 38


**FAILED**
ENS - name resolution

No address has been set for this name
Screenshot 2024-02-13 at 18 14 13


**NOT tested:**
Tokens - autodetect tokens
Tokens - autodetect NFTs
Swap - smart swap
Swap - swap eth

**Comment by ZbrancaI** [comment]
Hey @benjisclowder! Here's what I found for the manual test on **Firefox**.

**ENS - Name Resolution**

This test failed on Sepolia, as observed in the screenshot below. There's no address associated with this name. There are no issues on  Ethereum Mainnet regarding this aspect. 

Screenshot 2024-02-14 at 17 00 29

**General comment:**

- For importing a token, the formatting is terrible, dragging the elements to the extreme left, as observed in the screenshot below.

Screenshot 2024-02-14 at 11 24 50

- When initiating the transaction (the issue didn't manifest while making the transaction through the dApp), the _'Speed up'_ option disappears when the wallet closes (by clicking outside it or closing it intentionally). Only the _'cancel'_ option remains available. 

Screenshot 2024-02-14 at 11 44 30

**Import ERC1155 token origin MM**

- It might be related solely to the network, but when I triggered the transaction in the dApp by clicking on _Deploy the ERC1155 Contract_, the transaction got stuck in pending for too long (locally). I tried to _speed up_ the transaction two times, but it remained stuck. After that, only the _cancel_ option was still available, but it remained pending without any option available:

Screenshot 2024-02-14 at 13 01 10

So I cleaned the _activity and nonce data_. Everything was erased except the two initial funding transactions. After that, every time I tried to retake the steps, the transaction failed instantly (locally). The issue was also happening with other similar token operations from the dApp.

Screenshot 2024-02-14 at 13 11 34


I reinstalled the extension and restored my wallet. The issue of instantly failing transactions was persisting.

Screenshot 2024-02-14 at 13 22 03


I talked to @A-Feder, who suggested setting the gas price to 100 and the priority fee to 25. It got through after that, but the pending issue was still happening. 

I sped up the last transaction and waited approximately one hour. The transaction got through, and everything worked at a more reasonable speed after that. 

But the thing related to the Metamask extension that I want to point out is that the function from the dApp was generating prompts in the wallet, but the transactions were not present in the activity log. Only the first failed transaction was present there.

NOT TESTED:

Keyring - connect hardware wallet
Tokens - autodetect tokens
Tokens - autodetect NFTs
Swap - smart swap
Swap - swap eth

**Review by brad-decker — DISMISSED** [review]

**Comment by plasmacorral** [comment]
🟢 Approval from Accounts team
🟢 Approval on Behalf of the hardware wallets team
Several observations added to the bug report, but none are launch blocking.

[[Bug](https://github.com/MetaMask/metamask-extension/issues/22963)]: Upon swap completion if user clicks away then returns to extension, a draft swap of what was just completed is presented-confirmed in Prod 11.10.0
[[Bug](https://github.com/MetaMask/metamask-extension/issues/22953)]: Swap exceeding spending approval-confirmed in Prod 11.10.0
[[Bug](https://github.com/MetaMask/metamask-extension/issues/22952)]: alignment issues on Add suggested tokens confirmation
[[Bug](https://github.com/MetaMask/metamask-extension/issues/22933)]: Incorrect account name in receive flow
[[Bug](https://github.com/MetaMask/metamask-extension/issues/22931)]: Not observing QR progress bar as expected in RC11.11.0 
[[Bug](https://github.com/MetaMask/metamask-extension/issues/22976)]: Max Gwei value from transaction on account A, persists across send tx on account B and C- CLOSED as resolved

**Comment by sleepytanya** [comment]
🟢 Approval from Confirmations System team
[Bug]([https://github.com/MetaMask/metamask-extension/issues/22963]) - Gas estimates are not updated - closed as resolved

**Comment by danjm** [comment]
@SocketSecurity ignore-all

There are 11 warnings. 

4 are new author warnings where the author is a github staff and a known contributor to npm related projects, and 1 is an author warning for vs-codebot, which is maintained by microsoft and used for microsoft maintained packages.

1 is for a new package simple-git, which uses shell access as a dev tool

1 is for the deprecated gulp-postcss, which we should update but need not block release.

4 are for network access in make-fetch-happen, which is needed for its usage in node-gyp, which is a widely used build tool

**Review by danjm — APPROVED** [review]

**Pull request merged**
