### PR TITLE
chore: update CODEOWNERS for snap-keyring dir

### PR DESCRIPTION
**Pull request by gantunesr**
## **Description**

Update CODEOWNERS for snap-keyring directory

## **Related issues**

Fixes: NA

## **Manual testing steps**

Not applicable

## **Screenshots/Recordings**

Not applicable

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by owencraston — DISMISSED** [review]

**Review by mcmire — COMMENTED** [review]
In order to be added as a codeowner, does the `@MetaMask/accounts-engineers` team need to be explicitly added as collaborators to the repo?

**Comment by gantunesr** [comment]
I'm not sure tbh @mcmire

**Review by Gudahtt — APPROVED** [review]
LGTM!

**Comment by Gudahtt** [comment]
>In order to be added as a codeowner, does the @MetaMask/accounts-engineers team need to be explicitly added as collaborators to the repo?

Yes, this is correct. I have just granted access.

**Review by danroc — APPROVED** [review]

**Pull request merged**
