### PR TITLE
Fix: use estimate gas instead of fixed gas

### LINKED ISSUE #22359: [Bug]: Intrinsic Gas Too Low - MM can't estimate gas on 11.7.0 for Viem
### Describe the bug

When I go to deploy a contract from our dashboard, MM properly recognizes that I am going to deploy a contract. On 11.6.2, if I submit the transaction, gas is properly estimated. On 11.7.0, the transaction interface looks a bit different than I remember and when I submit the transaction, it fails with error code -32603 "Intrinsic gas too low: needed 81164, allowed 21000".

### Expected behavior

I expect that gas is estimated properly and the transaction succeeds. This seems to only affect interactions built with Viem and not those built with Ethers. I'll be submitting an issue with Viem as well, but other wallet clients and 11.6.2 of MM work with Viem so it seems to be MM 1.7.0 related.

### Screenshots/Recordings

image

image

### Steps to reproduce

1. Go to https://stackblitz.com/github/wevm/viem/tree/main/examples/contracts_deploying-contracts
2. Wait for the example to build
3. Connect MM
4. Click `deploy`
5. Submit tx
6. See that tx failed in MM
7. Open console to inspect the failure 

### Error messages or log output

_No response_

### Version

11.7.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

Pretty critical as our users can't deploy contracts on the latest MM version

### PR DESCRIPTION
**Pull request by vinistevam**
## **Description**

Update the transaction controller to:

- Fix to properly estimate the gas instead of using a fixed gas when deploying a contract without specifying the `gas`.

See [related core PR](https://github.com/MetaMask/core/pull/3694).

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/22359

## **Manual testing steps**

- Transaction regression

**Scenario of the error**
1. Go to https://stackblitz.com/github/wevm/viem/tree/main/examples/contracts_deploying-contracts
2. Wait for the example to build
3. Connect MM
4. Click deploy
5. Submit tx
6. Contract should deploy successfully

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [x] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by sleepytanya** [comment]
Contract successfully deployed:

https://github.com/MetaMask/metamask-extension/assets/104780023/14cb5560-0caa-47a9-990e-d0d8dd330ef2

**Comment by VersoriumX** [comment]
Upon review all checks pass

**Review by dbrans — DISMISSED** [review]

**Review by cryptotavares — DISMISSED** [review]

**Comment by sleepytanya** [comment]
No issues found with the transaction regression.

**Comment by vinistevam** [comment]
@metamaskbot update-policies

**Review by cryptotavares — DISMISSED** [review]

**Review by OGPoyraz — DISMISSED** [review]

**Review by matthewwalsh0 — APPROVED** [review]

**Review by OGPoyraz — APPROVED** [review]

**Pull request merged**
