### PR TITLE
fix: apply MV3 patch to snaps-controllers

### PR DESCRIPTION
**Pull request by FrederikBolding**
## **Description**

Applies a patch to include https://github.com/MetaMask/snaps/commit/54ffe3672dd02e11a0f7bb1bb0ab684b08f4b28c in the RC. Fixing stability issues when using Snaps under MV3.

### CODE REVIEW

**Comment by FrederikBolding** [comment]
@SocketSecurity ignore npm/@metamask/post-message-stream@8.0.0 
Trusted author

**Comment by legobeat** [comment]
@FrederikBolding I think it may be using the unpatched version transitively still, needing an entry in `resolutions` to "dedupe".

**Comment by FrederikBolding** [comment]
> @FrederikBolding I think it may be using the unpatched version transitively still, if so needing an entry in `resolutions` to "dedupe".

I'm not sure that matters as long as the main import in the MetaMask controller uses the right version?

Also wouldn't Yarn have added them automatically if they were necessary?

**Comment by legobeat** [comment]
> > @FrederikBolding I think it may be using the unpatched version transitively still, if so needing an entry in `resolutions` to "dedupe".
> 
> I'm not sure that matters as long as the main import in the MetaMask controller uses the right version?
> 
> Also wouldn't Yarn have added them automatically if they were necessary?

I looked through them individually and it seems that they may be fine - but due to all of them being type-only dependencies (so no code is actually included from them; red herrings).

**Pull request closed without merging**
