### PR TITLE
UX: Multichain: Convert Networks Menu to Modal

### LINKED ISSUE #19834: UX: Multichain: Convert Account, Network, and Details Popovers to Modals
### Describe the bug

The Account, Network, and Account Details UI were written with the legacy `Popover` component since the new `Modal` wasn't ready.  With the new `Modal` ready, we should convert those components to a `Modal`.

- [ ] Account Menu
- [ ] Network Menu
- [ ] Account Details

### Steps to reproduce

N/A

### Error messages or log output

_No response_

### Version

develop

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by darkwing**
## Explanation

Converts the new NetworkMenu from Popover to Modal

Fixes: #19834

## ToDo

- [ ]  Add a dozen networks and ensure the modal still looks good in popup (doesn't require the user to scroll through the entire popup).

## Screenshots/Screencaps

SCR-20230628-jpan

## Manual Testing Steps

1.  Open Networks Menu
2.  It should look and function the same as previously

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Review by georgewrmarshall — DISMISSED** [review]
LGTM. I don't think you need this css anymore in `ui/components/multichain/network-list-menu/index.scss`

```
  /* Overrides the popover's default behavior */
  &-content-wrapper {
    border-radius: 0;
  }
```

- checked in storybook
- checked in local build

**Comment by SaraCheikh** [comment]
the updated padding looks good now. Only one thing that I noticed in the build that differs from [design](xhttps://www.figma.com/file/csT5SmP88YqjA58URHL2JQ/EVM-only-multichain-V0.5?type=design&node-id=11564%3A633538&mode=design&t=S8jraOc3rPQ9HrEl-1) in this modal: 
-when the test networks toggle is on, we display the test networks on top of the test network toggle instead of below it 

Build

Screenshot 2023-06-28 at 19 41 49

Design 

Screenshot 2023-06-28 at 19 42 12

**Review by NidhiKJha — DISMISSED** [review]
LGTM

**Comment by darkwing** [comment]
@SaraCheikh Fixed in this separate PR: https://github.com/MetaMask/metamask-extension/pull/19812

**Review by NidhiKJha — DISMISSED** [review]

**Review by alokeutpal — APPROVED** [review]

**Review by NidhiKJha — APPROVED** [review]

**Review by vthomas13 — APPROVED** [review]

**Pull request merged**
