### PR TITLE
Version v11.6.0 

### PR DESCRIPTION
**Pull request by chloeYue**
## **Description**

Release Candidate v11.6.0

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by benjisclowder** [comment]
**Manual test scenarios:**

- [ ] onboarding - create a wallet
- [ ]  onboarding - import a wallet
- [ ]  keyring - connect hardware wallet
- [ ]  keyring - reset a wallet
- [ ]  transactions - send native token origin MM
- [ ]  transactions - send native token origin dapp
- [ ]  transactions - send erc20 token origin MM
- [ ]  transactions - send erc20 token origin dapp
- [ ]  transactions - send erc721 token origin MM
- [ ]  transactions - send erc721 token origin dapp
- [ ]  transactions - speed up transaction
- [ ]  transactions - cancel transaction
- [ ]  tokens - import erc20 token origin MM
- [ ]  tokens - import erc20 token origin dapp
- [ ]  tokens - import erc721 token origin MM
- [ ]  tokens - import erc 721 token origin dapp
- [ ]  tokens - autodetect tokens
- [ ]  tokens - autodetect NFTs
- [ ]  ens - name resolution
- [ ]  phishing - warning page
- [ ]  network - add custom network manually
- [ ]  network - add custom network from the list of popular networks
- [ ]  network - add custom network from dApp
- [ ]  network - update networks
- [ ]  network - switching networks
- [ ]  network - delete networks from the dropdown list
- [ ]  network - delete networks in Settings
- [ ]  backup - backup user data
- [ ]  backup - restore user data
- [ ]  metrics - send event metrics
- [ ]  address-book - add a contact to the address book
- [ ]  address-book - remove a contact from the address book
- [ ]  address-book - update a contact in the address book
- [ ]  gas fee - EIP-1559 gas
- [ ]  gas fee - legacy gas
- [ ]  sign - eth sign
- [ ]  sign - personal sign
- [ ]  sign - sign in with ethereum
- [ ]  sign - sign typed with data
- [ ]  permissions - connecting and disconnecting from a dapp
- [ ] swap - smart swap
- [ ] swap - swap eth
- [ ] incoming transactions - receive native token

**Comment by benjisclowder** [comment]
Release tracker for change validation on 11.6.0:
https://docs.google.com/spreadsheets/d/1tsoodlAlyvEUpkkcNcbZ4PM9HuC9cEM80RZeoVv5OCQ/edit#gid=1877047365

 MMI: @zone-live / @shane-t - There are 10 MMI changes in v11.6.0. We would like to get your team's approval on the v11.6.0 release by next Thursday. 
 Snaps: @bowensanders / @FrederikBolding / @Montoya - There are 11 Snaps changes in v11.6.0. We would like to get your team's approval on the 11.6.0 release by next Thursday.
 Design/Systems: @georgewrmarshall - There are 4 Design/Systems changes in v.11.6.0. We would like to get your team's approval on the 11.6.0 release by next Thursday.
 Confirmation UX: @seaona - There are 11 Confirmations UX changes in v11.6.0. We would like to get your team's approval on the 11.6.0 release by next Thursday.
 Confirmation Systems: @sleepytanya - There are 7 Confirmation Systems changes in v11.6.0. We would like to get your team's approval on the 11.6.0 release by next Thursday.
 Accounts: @plasmacorral - There are 8 Accounts changes in v11.6.0. We would like to get your team's approval on the 11.6.0 release by next Thursday.
 Assets: There are 3 Assets changes in v11.6.0.

**Comment by pedronfigueiredo** [comment]
@SocketSecurity ignore-all

Most issues are related to packages controlled by us. `blo` is a small library with no dependencies.

**Comment by bowensanders** [comment]
**Snaps team signoff on:**
✅ Bump snaps packages (#21774)
✅ Remove legacy transaction insight (#21027)
✅ Implement basic confirmation row components (#19957)
✅ Add simplified version of Snap install warning modal (#21516)
✅ Fix `AvatarAccount` type (#21671)
✅ Resolve network names using SLIP44 when applicable (#21674)
✅ Bump snaps packages (#21612)
✅ Include Snap name in permissions and add `allowedOrigins` permission caveat (#21682)
✅ Add loading state for snap delineator (#21792)

**Comment by sleepytanya** [comment]
Confirmations System Team sign-off:
✅ Add metrics event handler for MMI transaction updates (#21718)
✅ Ignore error while fetching `safeChainsList` for validation (#21676)
✅ Normalize addresses in mock state using toLowerCase (#21703)
✅ Fix: Contract data reading and parsing (#21604)
✅ Decouple swaps metric logic from `TransactionController` (#21559)

Please note, that we can't test transaction `Cancel/Speed Up` as those are not supported in MMI. 

✅ Replace MMI code fence with callbacks and arguments  (#21171)
✅ Fix MMI callbacks when checking pending transaction (#21666)

We tested MMI 1v1.4.0 and Speed Up/Cancel do not work:

[mmi.webm](https://github.com/MetaMask/metamask-extension/assets/104780023/c2451a7b-6f88-45c0-9126-bcd89ed61705)

**Comment by chloeYue** [comment]
Assets validation:
✅ feat: Add SEK currency (https://github.com/MetaMask/metamask-extension/pull/21782)
✅ fix: fix import address with non checksum Adr (https://github.com/MetaMask/metamask-extension/pull/21593)

**Comment by plasmacorral** [comment]
Verified PR 21755 within commit 3de23c0b095944ae89628322ca36430153796eaf in Mac Sonoma 14.0 with Chrome 117.0.5938.92 adding, signing, forgetting, readding, and signing again with both Ledger and QR wallet.  Also in Firefox 117.0.5938.92 w/ Trezor and QR. 

Please accept this comment as Accounts team approval for our changes in v11.6

**Comment by seaona** [comment]
**Confirmations UX Team**: we've been QAing the RC branch and [this cherry pick PR](https://github.com/MetaMask/metamask-extension/pull/21943#issuecomment-1824246377) branch, which includes the metric fixes. It looks good from our side.
This can be taken as the QA Sign Off for `11.6.0` **if** the cherry pick PR is merged to the RC branch

cc @bschorchit @cryptotavares  @danjm

**Comment by seaona** [comment]
✅  **Confirmations UX Team QA Sign Off**: after the metrics fixes were merged I confirm everything looks good on our side in this branch

**Comment by danjm** [comment]
I just did a final smoke test, testing sends and swaps on multiple networks, switching networks frequently. Also connected to opensea and optimism.

**Pull request merged**
