### PR TITLE
use 'cross-env' for env-variables within npm scripts, re #3426

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by lazaridiscom** [comment]
@kumavis , it looks like you have to add the cross-env package manually to your ci.

**Comment by kumavis** [comment]
@lazaridiscom  This is missing the `package-lock.json` diff, so the dep is not being installed

**Comment by kumavis** [comment]
@lazaridiscom hmm, maybe make sure you're on latest npm `npm i -g npm`
your npm is using the older `sha1` hash fn

**Comment by lazaridiscom** [comment]
me on 5.5.1 (don't want to change my dev-system at this moment).

Btw: I totally dislike this package-lock.json thing... (will look at this later again)

**Comment by kumavis** [comment]
@lazaridiscom yeah its annoying in PRs, but helps us create deterministic builds. It was requested by our mozilla reviewers.

**Comment by kumavis** [comment]
Opened a PR with minimal package-lock change here https://github.com/MetaMask/metamask-extension/pull/3538

**Pull request closed without merging**
