### PR TITLE
refactor: Migrate Typography to Text component in definition-list.js and contract-token-values.js

### PR DESCRIPTION
**Pull request by Devin-Apps**
## **Description**

This PR migrates the Typography component to the Text component in `definition-list.js` and `contract-token-values.js` files as part of the effort to standardize text rendering across the application. Before and after screenshots are provided to ensure no visual regressions have occurred.

Link to Devin run: https://preview.devin.ai/devin/d7074c3ba8244524a09ad51e8e6cd91e

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/25050?quickstart=1)

## **Related issues**

Partially Fixes: https://github.com/MetaMask/metamask-extension/issues/17670

## **Manual testing steps**

1. Go to the latest build of storybook in this PR
2. Manually check if the page `DefinitionList` renders correctly
3. Manually check if the page `ContractTokenValues` renders correctly
  
### **Before**
- DefinitionList: 

- ContractTokenValues: 

### **After**

- DefinitionList: 

- ContractTokenValues: 

## **Pre-merge author checklist**

  - [X] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
  - [X] I've completed the PR template to the best of my ability
  - [X] I’ve included tests if applicable
  - [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
  - [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

  - [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
  - [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by Devin-Apps** [comment]
Tagging @georgewrmarshall for review

**Review by georgewrmarshall — COMMENTED** [review]
Code looks good just have some linting issues and need to update snapshots

**Comment by Devin-Apps** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Shreyasi2002** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by georgewrmarshall — COMMENTED** [review]
Code and screenshots look good just need to update snapshot test in `ui/pages/confirmations/token-allowance/`

**Review by georgewrmarshall — APPROVED** [review]
LGTM 👍

**Review by garrettbear — APPROVED** [review]

**Review by sleepytanya — APPROVED** [review]

**Pull request merged**
