### PR TITLE
Switch to full lodash package, and update lodash

### PR DESCRIPTION
**Pull request by Gudahtt**
* Update lodash
  All versions of the full `lodash` package have been updated to 4.17
* Switch to using `lodash` instead of per-method packages
  We have the full lodash package _ten times_ as a production transitive
dependency, so including per-method packages is not saving space (it
might instead result in slightly more space being used).

### CODE REVIEW

**Review by whymarrh — COMMENTED** [review]
Keeping just the full `lodash` dependency seems alright I guess, can we import from `lodash/foo` instead? (See also https://nolanlawson.com/2018/03/20/smaller-lodash-bundles-with-webpack-and-babel/ where either that or lodash-es produce the smallest builds. Admittedly our builds are already pretty large.)

**Comment by Gudahtt** [comment]
The entire `lodash` dependency is already included in our production builds by ten different packages though. Unless they're all using file imports as well, how would using them in our project help reduce the bundle size? That's a sunk cost. Similarly for `lodash-es`, I don't know that it'd make a difference, given that we'll still have to bundle all of `lodash` anyway. Technically we already transitively depend upon `lodash-es` as well, but maybe not for long (it's used by an older version of redux, and a react package I'm hoping we can get rid of)

If we want to cut out the parts of `lodash` we don't use, the only feasible option seems to be one of the build plugins (e.g. `babel-plugin-lodash`)

**Comment by whymarrh** [comment]
Oh I mean that we can update the imports here to use `lodash/foo` and that's not any worse than what we have now?

**Review by whymarrh — APPROVED** [review]
This is good for now

**Comment by Gudahtt** [comment]
Yeah I think the prospect of tree-shaking without using a build plugin is unfeasible for now because of the number of dependencies we have that use the older package. We can revisit this in the future, maybe when v5 is released or if `lodash-es` becomes more popular.

**Pull request merged**
