### PR TITLE
fix: Set ENABLE_MV3=true for lavamoat:auto

### PR DESCRIPTION
**Pull request by danjm**
## **Description**

The lavamoat policy file generation on develop is not accounting for the offscreen document when the polcies are being generated. This is causing MV3 tests to fail because `@trezor/connect-web`, which is only imported in the offscreen, is not covered by the lavamoat policy, resulting in an error being thrown in the offscreen document.

The fix is to set ENABLE_MV3=true for `lavamoat:webapp:auto` and `lavamoat:webapp:auto:ci`, resulting in the offscreen document being included in the files used policy generation. Policy files then also need to be updated.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/24773?quickstart=1)

## **Manual testing steps**

Snaps MV3 tests should pass on https://github.com/MetaMask/metamask-extension/tree/provider-retry-fix-plus-mv3-policy-fix, which is a combination of this branch and the branch for https://github.com/MetaMask/metamask-extension/pull/24672, both of which are needed to get snaps mv3 tests passing.

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by danjm** [comment]
@metamaskbot update-policies

**Comment by danjm** [comment]
@metamaskbot update-policies

**Comment by danjm** [comment]
The MV3 tests are failing on this branch, but they are passing on https://github.com/MetaMask/metamask-extension/tree/provider-retry-fix-plus-mv3-policy-fix, which is this branch + the commits from https://github.com/MetaMask/metamask-extension/pull/24672 (both PRs are needed to get these tests passing).

This should count as validation for this PR.

**Review by davidmurdoch — APPROVED** [review]
Shipit! Branch is out of date with develo, so don't forget to check for potential issues before merging !

**Review by DDDDDanica — APPROVED** [review]

**Pull request merged**
