### PR TITLE
feat: check for ledger error codes in the message and display a more …

### LINKED ISSUE #17606: [Bug]: Vague Error Message when Connecting to Locked Ledger
### Describe the bug

Vague error message for connecting to Ledger devices that are locked.  

> 🔴 NOTE: this might seem trivial but is likely quite confusing for first-time Ledger users.

### Steps to reproduce

1. Ensure that your Ledger is locked (i.e., the Ledger screensaver is showing on the device)
2. Connect to your Ledger without first inserting your pin
image

### Error messages or log output

_No response_

### Version

10.24.2

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

Ledger

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by montelaidev**
## **Description**

This pr adds more user friendly error messages instead of just error codes when a user encounters ledger connection issues.

Resolves https://github.com/MetaMask/metamask-extension/issues/17606

## **Manual testing steps**

1. Go to Add hardware wallet
2. On the ledger device, unlock it.
3. On the `Connect a hardware wallet` page, Click on Ledger and then continue
4. Do not click connect when the webhid connection window pops up.
5. On the ledger device, lock the device
6. On the browser, click on the nano and then continue
7. See the new error

### **Before**

ledger-error-2

### **After**

ledger-error

## **Related issues**

Resolves https://github.com/MetaMask/metamask-extension/issues/17606

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained:
  - [x] What problem this PR is solving.
  - [x] How this problem was solved.
  - [x] How reviewers can test my changes.
- [x] I’ve indicated what issue this PR is linked to: Fixes #???
- [x] I’ve included tests if applicable.
- [x] I’ve documented any added code.
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)).
- [x] I’ve properly set the pull request status:
  - [x] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by coreyjanssen** [comment]
How about this for a new error message?

`Your Ledger is locked. Unlock it then try again. `

**Review by danjm — CHANGES_REQUESTED** [review]
This is a great improvement.

The only issue I have with this PR is that it is not compatible with our script to detect if translation strings are still used. See `metamask-extension/development/verify-locale-strings.js`, and in particular this code:

```
const strictSearchRegex =
    /\bt\(\s*'(\w+)'\s*\)|\btranslationKey:\s*'(\w+)'/gu;
  // match "t(`...`)" because constructing message keys from template strings
  // prevents this script from finding the messages, and then inappropriately
  // deletes them
  ```
  
  We use that to detect whether there are missing translation keys. So we need the exact string, and not a variable containing the string, to be passed to the `t` method.

To address this, you could create a function that you pass `this.context.t` and the `ledgerErrorCode`, and within that function it passes the exact string to `t()`, and then it returns the translated string.

**Comment by Akaryatrh** [comment]
> To address this, you could create a function that you pass `this.context.t` and the `ledgerErrorCode`, and within that function it passes the exact string to `t()`, and then it returns the translated string.

hey @danjm, is it what you had in mind?
```js
const getErrorMessage = (errorCode, t) => {
  switch (errorCode) {
    case '0x650f':
      return t('ledgerErrorConnectionIssue');
    case '0x5515':
      return t('ledgerErrorDevicedLocked');
    case '0x6501':
      return t('ledgerErrorEthAppNotOpen');
    case '0x6a80':
      return t('ledgerErrorTransactionDataNotPadded');
    default:
      return errorCode;
  }
};
```

**Review by gantunesr — APPROVED** [review]
lgtm!

**Review by danjm — APPROVED** [review]

**Pull request merged**
