### PR TITLE
Fixing horizontal line for gas recommendations

### LINKED ISSUE #11885: Horizontal line is about 1 pixel off to the right
Horizontal line on Edit Gas screen seems to be about 1 pixel off.
Screen Shot 2021-08-18 at 7 41 33 PM

### PR DESCRIPTION
**Pull request by ryanml**
Fixes: https://github.com/MetaMask/metamask-extension/issues/11885

Looks like this got misaligned as the result of recent changes. These values have been updated to use percentages, as the hard pixel-widths do not work for all views.

Before:
Screen Shot 2021-08-18 at 10 50 56 PM

After:
Screen Shot 2021-08-18 at 11 08 22 PM
Screen Shot 2021-08-18 at 11 08 15 PM
Screen Shot 2021-08-18 at 11 07 55 PM
Screen Shot 2021-08-18 at 11 07 47 PM

### CODE REVIEW

**Comment by darkwing** [comment]
I think I'm still seeing a 1px off in Firefox.
1px

**Review by adonesky1 — DISMISSED** [review]
LGTM!

**Comment by mcmire** [comment]
Okay, I didn't like that there were browser hacks, so I pushed another update that removes them.

Chrome:

Screen Shot 2021-09-01 at 4 26 53 PM

Firefox:

Screen Shot 2021-09-01 at 4 26 57 PM

**Review by NiranjanaBinoy — APPROVED** [review]
lgtm

**Review by adonesky1 — APPROVED** [review]
LGTM!

**Pull request merged**
