### PR TITLE
Added codeowners file

### PR DESCRIPTION
**Pull request by danfinlay**
Helps github auto-suggest the appropriate reviewers for pull requests. Just added two example owned folders to start.

### CODE REVIEW

**Review by wjmelements — APPROVED** [review]

**Comment by wjmelements** [comment]
When we change this file we should CC the owners. Does github email you for `@mention`s in commits?

**Comment by wjmelements** [comment]
CC @frankiebee @danjm @alextsg @whymarrh

**Comment by whymarrh** [comment]
> Does github email you for `@mentions` in commits?

I _think_ it does

**Comment by whymarrh** [comment]
Also, if we want to get fancy, we can use GitHub teams and have them as the owners

**Review by whymarrh — APPROVED** [review]
This is a good start

**Comment by wjmelements** [comment]
> I think it does for commit messages

did it email you for c3c0193?

**Comment by frankiebee** [comment]
i dont think i got an email till the CC mention

**Pull request merged**
