### PR TITLE
Add Swap feature to CurrencyInput

### PR DESCRIPTION
**Pull request by chikeichan**
swap

### CODE REVIEW

**Review by danjm — APPROVED** [review]

**Review by danjm — CHANGES_REQUESTED** [review]
Unit test and lint fixes needed

Code looks good otherwise

**Comment by bdresser** [comment]
that was fast @chikeichan !

@danfinlay @cjeria were you imagining the value would stay the same and the denomination would swap (as in the GIF) or that the values would swap along with the denomination? I can see arguments for either way, just want to check ~

**Comment by cjeria** [comment]
The currency converter app I use keeps the denomination the same when swapping, so I'd go with how @chikeichan implemented it.

**Review by danjm — APPROVED** [review]

**Review by whymarrh — APPROVED** [review]
LGTM

**Pull request merged**
