### PR TITLE
Refactoring incremental-security.spec.js to use fixtures

### LINKED ISSUE #10916: Refactor incremental-security.spec.js to follow pattern in metamask-extension/test/e2e/tests
This is part of #10754, and is the to-do item for the incremental-security.spec.js

### PR DESCRIPTION
**Pull request by NiranjanaBinoy**
Fixes: #10916 

Explanation:  

- Moved the file to test/e2e/tests
- Updated `helper.js` to start the sendwithprivatedapp
- Updated incremental-security.spec.js to use fixtures.
- Updated run-all.sh to use the new test file.
- Deleted the old incremental-security.spec.js file

### CODE REVIEW

**Comment by SirJosh1987** [comment]
What I do now?

**Comment by ha842** [comment]
Good cambo

**Review by brad-decker — DISMISSED** [review]
LGTM! :shipit:

**Review by brad-decker — APPROVED** [review]
LGTM!

**Pull request merged**
