### PR TITLE
feat: support transaction specific gas fee estimates

### PR DESCRIPTION
**Pull request by matthewwalsh0**
## **Description**

Traditional gas fee estimates are network specific meaning any transaction on the same network could use the same gas fee values to populate the `maxFeePerGas`, `maxPriorityFeePerGas`, and `gasPrice` parameters. These are currently sourced via the `GasFeeController` which in turn uses the gas API. Polling is dynamically initialised in the `GasFeeController` via the extension UI.

Some transactions now benefit from transaction specific gas fee estimates, such as transactions on the Linea networks via the `linea_estimateGas` RPC method. In an effort to encapsulate these transaction specific flows and decouple the complexity from the extension UI, this Linea logic and the default logic (via the `GasFeeController`) have been implemented within the `TransactionController`, each as a `GasFeeFlow`.

This PR fixes the support for gas fee flows in the dApp transactions as it was previously partially removed when the UI polling logic was updated. It also expands its adoption by using the `DefaultGasFeeFlow` to provide transaction fee estimates for all transactions, meaning the future confirmations UI can be simplified as it can locate gas fee estimates in the metadata of each transaction. This data is automatically updated via the `TransactionController` every 10 seconds.

This includes the following lower level changes:

- Update the `TransactionController` to enable the `DefaultGasFeeFlow` and `TestGasFeeFlow`.
- Add `TEST_GAS_FEE_FLOWS` environment variable to enable use of the `TestGasFeeFlow` to easily debug gas fee flow usage in the extension, as the gas fee will increase on each call on a fixed interval.
- Update the gas fee estimate and type selectors to return the data from the current confirm transaction if one exists.

This PR does **not** include the following pending work:

- Support for gas fee flows in the wallet send UI, unless the medium level is selected during confirmation.
- Support for gas fee flows in the swaps UI.
- Removal of the gas fee controller polling triggered by the UI, since it is currently required for send and swaps.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/24222?quickstart=1)

## **Related issues**

Fixes: [#2034](https://github.com/MetaMask/MetaMask-planning/issues/2034)

## **Manual testing steps**

1. Full regression of all gas fee related flows.
2. Permutations with legacy and EIP-1559 transactions on legacy and EIP-1559 networks.

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by pedronfigueiredo — DISMISSED** [review]

**Comment by sleepytanya** [comment]
Mainnet and Linea Sepolia EIP 1559 and EIP 1559 sent without gas look normal, but on Sepolia fees for EIP 1559 sent without gas are higher (including priority fee).
Mainnet [EIP 1559](https://etherscan.io/tx/0xd0fe99b3e97be1644244c0a7a9450a577822fd4ea0132bf4e3ec7349ca2e2e44) + [EIP 1559 without gas](https://etherscan.io/tx/0xfbaf6363be7070df25ad74e4d480f338c71e9bf7efcab85fa248cdd593ba1666) 

Linea [ EIP 1559](url) + [EIP 1559 without gas](https://sepolia.lineascan.build/tx/0x2387c4ed776387eea3e4e4166bae35d6a72ce059478bba1c1eefa69108cbf401) 

Sepolia [EIP1559](https://sepolia.etherscan.io/tx/0x6bd20974bead7ecae1f46d3731c445b648ac79eb3f352597d9da117c19777369) + [EIP 1559 without gas](https://sepolia.etherscan.io/tx/0x3d2a89c06ae337db12b73117b94a1bd1c5ac62891f32788dd3201da83a192724)

Not sure if that's expected but I see persisting error in the background console:
Screenshot 2024-05-02 at 14 04 01

**Comment by sleepytanya** [comment]
Again not sure if that should work like this as Scroll doesn't support EIP 1559: I am able to send Legacy tx on Scroll and also EIP 1559 without gas. Block explorer marks EIP 1559 without gas as 'Legacy': https://sepolia.scrollscan.com/tx/0x02d257f4fb91238fc4a4e5aa0b1ffe0da6b71e51bc7266c1d5f8664da4412bcb

**Comment by sleepytanya** [comment]
On Polygon only EIP 1559 without gas can be submitted. Legacy and EIP 1559 fail with Internal JSON RPC error.

Same for Avalanche - only EIP 1559 without gas can be submitted.

**Comment by sleepytanya** [comment]
All issues mentioned in the previous comments also present on production and not related to the current PR:
- 'No metadata found' error in the background console
- Sepolia and BNB fees for EIP 1559 sent without gas are higher
- only EIP 1559 without gas can be submitted on Polygon and Avalanche. Legacy and EIP 1559 fail with Internal JSON RPC error. Polygon EIP 1559 without gas also has high gas fee (30 GWEI):


https://github.com/MetaMask/metamask-extension/assets/104780023/aae4ddd8-0c84-4278-a185-a20301d5411a


https://github.com/MetaMask/metamask-extension/assets/104780023/e6c8c3d1-2d25-4276-b5ef-330145bbe0f1

**Comment by matthewwalsh0** [comment]
@metamaskbot update-policies

**Review by pedronfigueiredo — APPROVED** [review]

**Review by vinistevam — APPROVED** [review]

**Pull request merged**
