### PR TITLE
Remove bottom space when hiding testnet

### PR DESCRIPTION
**Pull request by TkzcM**
Fixes: 
dfbf0651-2cd7-4d9f-8ef0-c8466fc078ab (2)

Explanation:  
Use "display: none;" rather than "visibility: hidden;".

Manual testing steps:  
  - Add 10 networks.
  - Hide testnet in settings.
  - Open the Network dropdown.

### CODE REVIEW

**Comment by TkzcM** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by darkwing — APPROVED** [review]
Thank you for the contribution!

**Comment by darkwing** [comment]
Thank you @TkzcM!  Could you please rebase the PR so the bot sees your CLA signing?  Thank you!

**Comment by TkzcM** [comment]
It should be fine now, though I think I messed up with the merge commit...
If the PR can't be merged, please let me know things I need to do. Thanks.

**Comment by darkwing** [comment]
Hmm, I think we should take a different approach here actually.  In `ui/components/app/dropdowns/network-dropdown.js`, we shouldn't render the list items at all if the setting is off:

https://gist.github.com/darkwing/b9faaf7959fc5299b64a600e5e070c0d

TestNets

Let me know what you think!

**Review by darkwing — CHANGES_REQUESTED** [review]
Close!

**Comment by TkzcM** [comment]
Yes, the elements should also be removed. As the "network-dropdown-testnets" class is not exist anymore, I removed the css as well. Much thanks for your helping!

**Review by darkwing — DISMISSED** [review]

**Review by mcmire — CHANGES_REQUESTED** [review]
Hi @TkzcM, this looks like a good change — is it possible to add tests for this?

**Comment by TkzcM** [comment]
Sorry, I'm not familiar with adding tests. I checked the current test, as it's using color to test the visibility of networks, the changes should not affect the current test. Or we need to add a test to make sure the testnet elements aren't exist while hiding testnets?

**Comment by darkwing** [comment]
@TkzcM No problem!  This should work:

```
diff --git a/ui/components/app/dropdowns/network-dropdown.test.js b/ui/components/app/dropdowns/network-dropdown.test.js
index f8546f8b6..409b07dd9 100644
--- a/ui/components/app/dropdowns/network-dropdown.test.js
+++ b/ui/components/app/dropdowns/network-dropdown.test.js
@@ -147,6 +147,10 @@ describe('Network Dropdown', () => {
         'addNetwork',
       );
     });
+
+    it('shows test networks in the dropdown', () => {
+      expect(wrapper.find('.network-dropdown-list li').length).toStrictEqual(8);
+    });
   });
 
   describe('NetworkDropdown in appState is true and show test networks is false', () => {
@@ -193,5 +197,11 @@ describe('Network Dropdown', () => {
         'addNetwork',
       );
     });
+
+    it('does not show test networks in the dropdown', () => {
+      expect(wrapper.find('.network-dropdown-list li').length).toStrictEqual(
+        3
+      );
+    });
   });
 });

```

You'll want to run `yarn lint:fix` after implementing that to ensure lint passes.  Great work so far!

**Comment by TkzcM** [comment]
Thanks again for your helping!

**Review by darkwing — APPROVED** [review]
Well done @TkzcM !  Thank you for the contribution!

**Review by mcmire — APPROVED** [review]

**Comment by darkwing** [comment]
Hello @TkzcM !  Could you rebase this pull request so that tests will pass?  Thank you!  I'm excited to get this merged! :)

**Comment by TkzcM** [comment]
The tests is still failed, is there anything wrong?

**Comment by darkwing** [comment]
Thank you so much for your contribution @TkzcM !

**Pull request merged**
