### PR TITLE
Add metrics e2e test

### PR DESCRIPTION
**Pull request by Gudahtt**
An e2e test has been added that uses the new mock Segment server to verify that the three initial page metric events are sent correctly.

Using the mock Segment server requires a special build with this mock Segment server hostname embedded, so a distinct job for building and running this test was required. As such, it was left out of the `run-all.sh` script.

### CODE REVIEW

**Comment by Gudahtt** [comment]
Well. That's an interesting result! It works every time locally.

**Comment by Gudahtt** [comment]
Huh. I added a log to get some insight into what's happening, and it definitely appears to be failing on CI and working locally. I haven't seen the event get triggered on CI yet, yet it is always triggered when I run it locally, using exactly the same commands.

I'm using a different version of Firefox than CI is :thinking: . But I'm guessing this is just some race condition. I guess there is no guarantee that anything async performed in `beforeunload` will have time to finish.

**Comment by Gudahtt** [comment]
I'll update this PR to test something that _does_ work more reliably. We'll have to revisit this `beforeunload` behavior another time, perhaps by sending this metric event from the background instead.

**Comment by Gudahtt** [comment]
I have updated this PR (and the description) to test for the first two Page events, rather than for the close event.

Curiously, there is no third page event when the user submits their password, and navigates back to "Home" from "unlock" :thinking:

**Review by darkwing — APPROVED** [review]
Really nicely done @Gudahtt !  The test itself seems to take a while (almost 7 seconds), but that's likely triggered by MM's initial load.  Since other tests take longer, I'm not too worried about it.  Thank you!

**Pull request merged**
