### PR TITLE
Remove MetaMask Mesh testing client

### LINKED ISSUE #7248: Remove mesh testing iframe
The Mustekala project is not currently using the mesh-testing iframe that we inject in 1% of users' browsers, so we should remove it to reduce load on those users.

### PR DESCRIPTION
**Pull request by whymarrh**
Resolves #7248

This PR reverts #7031 and removes the mesh testing file originally introduced in #3222.

As @kumavis as noted,<sup>[\[1\]][1]</sup> this isn't used anymore.

  [1]:https://consensys.slack.com/archives/G1L7H42BT/p1575986981282600?thread_ts=1575928172.275100&cid=G1L7H42BT

### CODE REVIEW

**Comment by jennypollack** [comment]
resolves #7248

**Comment by whymarrh** [comment]
@jennypollack updated the OP

**Review by jennypollack — APPROVED** [review]

**Review by rekmarks — APPROVED** [review]
LGTM, although that Chrome e2e test failure is weird.

**Comment by whymarrh** [comment]
> although that Chrome e2e test failure is weird

All of our e2e failures are weird 😭 but @Gudahtt is doing great work to get them to be less weird.

**Comment by Gudahtt** [comment]
That failure in particular might be my fault 😅 Hopefully that intermittent failure is fixed by one of the PRs I'll have up today.

**Pull request merged**
