### PR TITLE
Add ability to import private keys

### LINKED ISSUE #1021: Allow importing private key hex strings

### PR DESCRIPTION
**Pull request by danfinlay**
Fixes #1021

screen shot 2017-01-17 at 3 07 22 pm

A top-right menu item now allows `Account Import`.  It has a menu (with one item for now) that allows importing a private key string.

screen shot 2017-01-17 at 3 27 49 pm

Errors are displayed, and a success navigates the user to their account list, where the imported account is labeled `LOOSE`.

screen shot 2017-01-17 at 4 17 01 pm
(Their names are simply incremented, I labeled this one for clarity)

This merged in an old Multivault UI branch.  This included a set of components already complete for showing a menu of import options, as well as templates for those import strategies.

While I'm not yet using the `geth-import` or `seed phrase` templates, I'm leaving them in because they're partially complete, and I expect to finish them soon.

Part of that old UI branch was to add a TabBar component, that makes tab-bars more modular.  It is not used in any of the new UI, but I did insert it into the `buy-ether` template, to show how to easily drop in a consistently-styled tab bar within metamask.

### CODE REVIEW

**Comment by flyswatter** [comment]
@VladTod Any thoughts on an icon for an `Import Account` menu item?

**Comment by VladTod** [comment]
I'm quite ok with the current icon, it does take your mind to "upload"
But something like the one bellow might work as well. It also connects the icon to the Switch Account icon, so it might be easier to understand what it is and were i can find it after i upload it.

let me know what you think

mm-icon

**Review by frankiebee — APPROVED** [review]

**Comment by frankiebee** [comment]
Looks good to me. Tried it out locally looks great and seems to work fine.

**Comment by frankiebee** [comment]
My non blocking request would be that once you've imported your key it would the take you to the account detail screen for that account rather the to the SELECT ACCOUNT view

**Comment by flyswatter** [comment]
@VladTod if you could provide an SVG for that icon, I'd be open to using it.  Right now all our icons are part of [FontAwesome](http://fontawesome.io/icons/).

**Comment by flyswatter** [comment]
That seems like a good idea, @frankiebee.

**Comment by VladTod** [comment]
https://www.dropbox.com/s/4fyens32wf4ymhn/Import_acc.svg?dl=0
here is the link to the SVG. Let me know if something ain't ok with it.

**Pull request merged**
