### PR TITLE
Fix: Unable to edit token allowance / custom spending cap

### LINKED ISSUE #20649: [Bug]: Unable to edit spending cap from portfolio requests
### Describe the bug

When you receive a erc-20 allowance request from https://portfolio.metamask.io/ and you try to edit it to a custom value, the value does not get updated in the confirmation screen or in the transaction data.

### Steps to reproduce

1. Go to https://portfolio.metamask.io/swap
2. Start a swap from a erc20 token that you haven't given allowance for yet
3. Click 'approve' in the portfolio UI
4. Click 'edit' in the spending cap section of the MM popup
5. Enter a custom number and click on next to see how the value remains unchanged 

### Error messages or log output

_No response_

### Version

10.34

### Build type

None

### Browser

Brave

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

https://github.com/MetaMask/metamask-extension/assets/34968356/c435f289-12a4-4be5-8232-56c99fd7ae3a

### PR DESCRIPTION
**Pull request by digiwand**
## Explanation

Fixes https://github.com/MetaMask/metamask-extension/issues/20649

This fix involves decoupling customSpendingCap from the dappProposedTokenAmount. customSpendingCap can now accept changes. customSpendingCap will be set as dappProposedTokenAmount on load if it is empty. 

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Review by segun — APPROVED** [review]

**Review by blackdevelopa — APPROVED** [review]

**Comment by seaona** [comment]
I have checked MM production and I see the issue fixed there :thinking: @bschorchit @digiwand are you still able to reproduce the issue in production?

I also see it fixed in this branch, seems the behaviour is the same from the UI perspective

https://github.com/MetaMask/metamask-extension/assets/54408225/0d6042af-8ed8-4b24-95ec-65ca9952a1d5

**Comment by digiwand** [comment]
@seaona in the Issue video, @bschorchit clicked "Next" rather than "Cancel" 🤔. that might make a difference. we need to be careful testing this... 

I accidentally lost $11 testing this - $8 on one transaction and $3 on another. In the future, it might be worth locally running the portfolio page to bypass the necessary gas amount.

Since we see page 1 of 2 in your view, I think we should be able to click "Next" to get to the next page

**Comment by seaona** [comment]
Thank you for reviewing that @digiwand !
Unfortunately I'm still not able to repro this in production :thinking: 

Before clicking next the values were unchanged on Barbara's video, but they do update in prod for me. (see number 1 in input field but `fffff...` in hex data, which showcasts the error is already present before clicking next.


Screenshot from 2023-09-13 15-12-50

After clicking next I experience the same situation (the approve value is correct for me, but not in the issue video). This is in current production `11.0.0`


https://github.com/MetaMask/metamask-extension/assets/54408225/df349cee-5e37-4ea1-8426-eb19df80cb87

**Comment by digiwand** [comment]
@seaona interesting, I see what you mean now 🤔  looks fixed to me too. I think the update in this PR will still put this in a better state... think it is good to merge?

Thank you very much for the investigation and thorough QA!

**Comment by seaona** [comment]
@digiwand it looks good to me to merge too! I confirm the behaviour is fixed in your PR too and looks good from QA side

**Pull request merged**
