### PR TITLE
Smooth balance transitions and delayed balance updates on network changes

### LINKED ISSUE #6019: Logged on testnet, then logged on main network, but showing yet the balance of testnet instead of a loading spinner
image

### PR DESCRIPTION
**Pull request by danjm**
fixes #6019 

peek 2019-02-21 00-55-2

peek 2019-02-21 00-55

### CODE REVIEW

**Comment by bdresser** [comment]
does this show all the time, or just when the balance takes a moment to fetch?

my gut is that we should make the loading indicator smaller. but i think all the right pieces are there! 

@cjeria what do you think?

**Comment by cjeria** [comment]
I personally like a more subtle approach like this text loading example:
loading-text

So if you can imagine that animation in our ui would look like this:
image

**Comment by danjm** [comment]
@bdresser the fade out and in of the balance would happen all the time, but we can decide how we want the loading indicator to behave: e.g. it only shows up after waiting one second for the new network balance to load

@cjeria thanks, I'll try something like that

**Comment by whymarrh** [comment]
@danjm I'm going to close this for now, we can reopen this when we have time to update it

**Pull request closed without merging**
