### PR TITLE
remove node-sass dependency

### PR DESCRIPTION
**Pull request by brad-decker**
Back in #10208 I changed us over to using dart-sass instead of node-sass, but gulp-sass had a dependency on node-sass that still required it in our build. This change uses `gulp-dart-sass` to remove that element.

### CODE REVIEW

**Comment by Gudahtt** [comment]
@brad-decker Instructions on how to manage lavamoat policies and allow-scripts configuration are here: https://github.com/MetaMask/metamask-extension#changing-dependencies

And yes, deleting the patch would be the correct approach. That reminds me - we don't document how to deal with patches yet :thinking: I should address that.

**Comment by brad-decker** [comment]
Erg... the policy file changes made me look at bundles

https://bundlephobia.com/result?p=gulp-dart-sass@1.0.2 vs https://bundlephobia.com/result?p=gulp-sass@4.1.0

2.2mb minified vs 141kb minified... I'm thinking we just keep node-sass around for a while.

**Comment by brad-decker** [comment]
Ew, the diff on p

**Comment by Gudahtt** [comment]
Check out the install scripts for node sass though. Are they downloading a binary? The true size can be hidden a lot of the time.

Plus... having both around doesn't do us much good if we're only using one.

**Comment by Gudahtt** [comment]
That is misleading because of node-sass, which downloads a binary as part of the install script I think? Thus hiding the true size.

Plus the bulk of the size of the dart package is due to the sass package, which we already have in our dependency tree. I do think this would be a strict reduction in our dependencies.

**Review by kumavis — DISMISSED** [review]
looks good. huge yarn-lock reduction :eyes: :+1:

**Comment by Gudahtt** [comment]
I have just rebased this to fix the `yarn.lock` conflict

**Review by Gudahtt — APPROVED** [review]
LGTM!

**Pull request merged**
