### PR TITLE
Update `vi` localized messages

### PR DESCRIPTION
**Pull request by Gudahtt**
These translations were provided by Lionbridge.

### CODE REVIEW

**Comment by Gudahtt** [comment]
If any community contributors would like to help review this PR, it would be greatly appreciated!

I'll tag anyone here that has contributed in the past: @vietlq

I wanted to give you all the opportunity to provide feedback because we owe our current translations to you. Please don't feel obliged if you don't have the time to review, and please let me know if you'd like me to stop tagging you for reviews in the future.

Thanks!

**Comment by markusait** [comment]
Hi guys, here is some feedback from the Stably team in Vietnam regarding the localization. 

- Line 866: Missing 'Full stop' between 2 sentences. (lệ. Giá)
- Line 945: I am not sure what Memo in this context means. In my experience, Binance Exchange keeps the word MEMO, not translate it, because Vietnamese does not have the word for MEMO.

FILE EN.JSON
- Line 250: Missing "tiền" - Nhận tiền
- Line 339: Missing "thông minh" (smart contract = hợp đồng thông minh)
- Line 608: Replace "Phí gas hủy" with "Phí hủy gas"
- Line 613: Replace "Phí mạng" with "Phí giao dịch". (mạng = network, transaction = giao dịch)
- Line 806: Name is different from nickname. Nickname = Biệt danh
- Line 810: Same above. Prefer to keep the word MEMO in English.
- Line 1346: I guess 50$4 is a typo, because $ and 4 are in the same place on the keyboard.

**Comment by Gudahtt** [comment]
Thanks for the feedback!

I'm having trouble understanding what line numbers these are :thinking: I can't seem to find the things you're describing here on those lines. Which files do those correspond to? I can't find a "50$4" anywhere either.

> am not sure what Memo in this context means. In my experience, Binance Exchange keeps the word MEMO, not translate it, because Vietnamese does not have the word for MEMO.

"memo" in this case is just a text field we include with each contact in the address book. It's for writing any arbitrary text associated with a contact. For example, you might include details about who that contact is. For example:

memo-example

We could certainly keep it untranslated! Though maybe there's a simpler word like "note" that would be more appropriate to use.

**Comment by Gudahtt** [comment]
This PR has been rebased onto `develop` to ensure that the `yourSigRequested` message was not present (it was removed in #10300).

**Comment by markusait** [comment]
@Gudahtt I'll ask our team member to leave a comment on the PR directly. Given that it is Tết holiday, this won't happen before the 17th of Feb, if you want to wait. I agree on keeping Memo untranslated, that is how it is called on Ethereum after all.

**Comment by Gudahtt** [comment]
This has been rebased on `develop`, and the unused message `swapGetQuotes` has been removed.

**Comment by minht-stably** [comment]
> Thanks for the feedback!
> 
> I'm having trouble understanding what line numbers these are 🤔 I can't seem to find the things you're describing here on those lines. Which files do those correspond to? I can't find a "50$4" anywhere either.
> 
> > am not sure what Memo in this context means. In my experience, Binance Exchange keeps the word MEMO, not translate it, because Vietnamese does not have the word for MEMO.
> 
> "memo" in this case is just a text field we include with each contact in the address book. It's for writing any arbitrary text associated with a contact. For example, you might include details about who that contact is. For example:
> 
> memo-example
> 
> We could certainly keep it untranslated! Though maybe there's a similar word like "note" that would be more appropriate to use.

I am Minh, @markusait 's teammate. He gave me 2 files for review:
1/ messages.json
2/ en.json

I read these files on Slack, and there are line numbers.
image

--
FILE MESSAGES.JSON
Line 866: Missing 'Full stop' between 2 sentences. (lệ. Giá)
Line 945: I am not sure what Memo in this context means. In my experience, Binance Exchange keeps the word MEMO, not translate it, because Vietnamese does not have the word for MEMO.

FILE EN.JSON
Line 250: Missing "tiền" - Nhận tiền
Line 339: Missing "thông minh" (smart contract = hợp đồng thông minh)
Line 608: Replace "Phí gas hủy" with "Phí hủy gas"
Line 613: Replace "Phí mạng" with "Phí giao dịch". (mạng = network, transaction = giao dịch)
Line 806: Name is different from nickname. Nickname = Biệt danh
Line 810: Same above. Prefer to keep the word MEMO in English.
Line 1346: I guess 50$4 is a typo, because $ and 4 are in the same place on the keyboard.

For your reference
image

**Comment by Gudahtt** [comment]
Ohhh I see, thanks! That clears things up. That second file is for the MetaMask mobile translations - so I'll pass along your feedback to the mobile team (the PR for those translations is [here](https://github.com/MetaMask/metamask-mobile/pull/2156))

**Comment by Gudahtt** [comment]
@minht-stably Thanks so much for the feedback! I've addressed both of your comments about the first file here: https://github.com/MetaMask/metamask-extension/pull/10270/commits/22fb95e0fe4a4f03a084b56e893135c68c4cebd5

**Pull request merged**
