### PR TITLE
Advanced Privacy settings page #13445

### LINKED ISSUE #13445: Advanced Privacy settings page
- The Etherscan privacy policy link seems wrong (should be "https://etherscan.io/privacyPolicy", not "https://cn.etherscan.com/privacyPolicy").

- Enhanced token detection setting doesn't describe which APIs are used, and doesn't include a privacy policy. 

Needs design feedback
cc @rachelcope

### PR DESCRIPTION
**Pull request by dragana8**
Fixes: #13445

Updated privacy policy link and token detection description.
Screenshot 2022-03-01 at 13 51 22

### CODE REVIEW

**Comment by mirjanaKukic** [comment]
Verified by QA

**Review by adonesky1 — APPROVED** [review]
LGTM

**Review by georgewrmarshall — APPROVED** [review]
lgtm!

**Comment by darkwing** [comment]
Merging with two approvals.

**Pull request merged**
