### PR TITLE
Update transaction status to not be considered anonymous

### PR DESCRIPTION
**Pull request by blackdevelopa**
## Explanation
- To include transaction status to the non-anonymous transaction finalised events. See [details](https://consensys.slack.com/archives/C03FWKDGGAG/p1684364620306539?thread_ts=1684359414.334289&cid=C03FWKDGGAG).
- Fixes [#836](https://github.com/MetaMask/MetaMask-planning/issues/836)

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Review by segun — DISMISSED** [review]

**Comment by segun** [comment]
Looks good but e2e is failing.

**Comment by blackdevelopa** [comment]
Thank you @segun

**Review by segun — APPROVED** [review]

**Review by jpuri — APPROVED** [review]

**Comment by bschorchit** [comment]
On QA for this: I've downloaded the chrome build for this PR and was able to see the status property on both anonymous and non-anonymous for all transaction events for contract deployment, simple send (legacy and eip1559) and approve transactions. 
Looks good to me.

**Comment by bschorchit** [comment]
I've merged this as I have tested it a bit more today and all looked good ✅

**Pull request merged**
