### PR TITLE
feat: create Developer Options Setting Page

### LINKED ISSUE #23592: [Feat]: Add Developer Options Settings Page
### Problem
As an internal developer, developing and testing certain features can be cumbersome due to conditional state hurdles to be met. For example, to reproduce the What's New modal or the onboarding flow, developers will need to reinstall the application and re-add their wallets to see the UI.

### Solution
With a new "Developer Options" settings page, developers can now reset various states easily to accelerate their development process. The initial settings page will allow resetting states related to What's New announcements and the onboarding flow.

### Feature Description

The "Developer Options" setting page will provide developers with additional controls and customization to assist with development and testing. This feature will enable developers to reset app states easily, toggle certain features on/off, and update configurations without needing to reinstall the app, accelerating developer velocity.

### Links
- Pull Requests:
  - https://github.com/MetaMask/metamask-extension/pull/22382)
- [Internal Slack w/ Original Demo](https://consensys.slack.com/archives/C06AFMP6TLN/p1703298628335889?thread_ts=1703183446.214679&cid=C06AFMP6TLN)
- 2nd Internal demo found in Internal Weekly Meeting that took place on 2024.03.18
- [Internal Google Slides](https://docs.google.com/presentation/d/17ajEM_yYLOZaC2FqLLR8I4Y-duS2EWsdpUIyMyahzs0)

### Other Notes
- This settings page can be expanded to support "Runtime feature flags". Related https://github.com/MetaMask/metamask-extension/issues/16748
- Currently, this settings page has been designed solely for internal dev purposes. That is, it is designed for developers working directly on the wallet. There could be a future collaboration with developer-mode settings which is intended for dapp developers working with the wallet.

### Scenario

_No response_

### Design

_No response_

### Technical Details

_No response_

### Threat Modeling Framework

_No response_

### Acceptance Criteria

_No response_

### Stakeholder review needed before the work gets merged

- [X] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

### References

_No response_

### PR DESCRIPTION
**Pull request by digiwand**
## **Description**

The "Developer Options" setting page will provide developers with additional controls and customization to assist with development and testing. This feature will enable developers to reset app states easily, toggle certain features on/off, and update configurations without needing to reinstall the app, accelerating developer velocity.

To enable, add `ENABLE_SETTINGS_PAGE_DEV_OPTIONS=true` in .metamaskrc

Developer Options Supported:
- Reset Announcements/Notifications for What's New modal
- Reset Onboarding states and redirects to second onboarding page

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/23592
Blocked By: https://github.com/MetaMask/core/pull/4088

## **Manual testing steps**

1. `yarn install` to install the latest announcement-controller changes
2. go to `.metamaskrc`
3. paste `ENABLE_SETTINGS_PAGE_DEV_OPTIONS=true`
4. `yarn start`

Test using test-dapp
1. open test-dapp
2. test with PPOM buttons

---

1. See chrome-extension://hbljfohiafgaaaabejngpgolnboohpaf/home.html#settings/developer-options

#### New UI

Screenshot 2023-12-21 at 2 33 45 PM

Screenshot 2023-12-22 at 1 58 28 PM

Screenshot 2023-12-22 at 1 59 40 PM

#### Announcements 

Screenshot 2024-03-17 at 8 13 41 PM

#### Onboarding

Screenshot 2024-03-17 at 8 13 56 PM

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by vandan** [comment]
Please take a look at some of the [thinking from DevEx](https://consensys.slack.com/archives/C02GENU377A/p1702684006205689) related to Developer settings.

**Comment by digiwand** [comment]
Hi @vandan, glad you found this PR. I believe this PR would complement the "Developer Mode" you've put deep thought into. I was thinking, upon toggling the "Developer Mode" setting, it would unlock the "Developer Options" setting page. Thoughts?

**Comment by digiwand** [comment]
@vandan 

I think there is some crossover between developers working directly on the wallet itself and developers working with the wallet. I think DevEx focuses on developers working with the wallet. This new page was designed to suit developers working directly on the wallet. I see the page extending its boundaries to all developer experiences

**Comment by vandan** [comment]
Great. Yes, I would think that a general developer mode should ideally have some functions for people building MetaMask itself as well. Everything we explored was conceptual so it's nice to see some common interest in actually solving for the developer needs.
In talking to a few folks on the team we found there is value in providing developers with a distinct onboarding path as well (to suppress features such as _SRP reminder_ by default).

**Comment by digiwand** [comment]
resurrecting PR for a demo

**Comment by digiwand** [comment]
tests are currently blocked by https://github.com/MetaMask/core/pull/4088
will need to merge AnnouncementController changes, then updated package in this PR

Screenshot 2024-03-19 at 11 57 05 PM

**Review by pedronfigueiredo — DISMISSED** [review]
LGTM

**Review by pedronfigueiredo — APPROVED** [review]

**Review by segun — APPROVED** [review]

**Review by jpuri — APPROVED** [review]

**Review by blackdevelopa — APPROVED** [review]

**Pull request merged**
