### PR TITLE
Select first account on create or restore vault

### LINKED ISSUE #2348: When restoring to new seed from another seed, select 1st new account
Currently it seems selected account is not affected, so it shows the old account until selecting account again.

### PR DESCRIPTION
**Pull request by danfinlay**
There's a bug in master where the first account is not selected on vault create or restore.

This fixes that.

Fixes #2348

### CODE REVIEW

**Comment by Zanibas** [comment]
Non-blocking, but next steps:
- `accounts` state in the `metamask` state does not clear properly on the load of a new seed phrase. Old accounts are still tracked.
- Same goes for `computedBalances`

**Review by 2-am-zzz — APPROVED** [review]
:+1:

**Comment by tmashuang** [comment]
Issue with seeing balances when switching to a new seed phrase.

**Comment by danfinlay** [comment]
I've been unable to reproduce @tmashuang's bug. Are you sure you rebuilt the branch before testing? It sounds like you're describing the bug this fixes.

**Comment by tmashuang** [comment]
Weird. I nuke node modules and rebuilt.

**Comment by danfinlay** [comment]
Implemented @Zanibas's advice, now also forgetting old accounts when restoring, so we stop tracking their balances.

**Comment by danfinlay** [comment]
@tmashuang could you check the logs? Is there a particular property being expected that you're not seeing? I also wonder if this new commit helps your issue.

**Comment by tmashuang** [comment]
Under accounts, the account that is suppose to be selected, is not showing a code, balance, nonce, and address key/pair.

**Comment by danfinlay** [comment]
This sounds a bit like a network connectivity issue. Have you checked your background network monitor?

**Comment by tmashuang** [comment]
background network is fine, curls on getBalance are fine.

**Review by kumavis — DISMISSED** [review]
getting a reproducible bug on this branch...
investigating

**Comment by kumavis** [comment]
started an issue before realizing this was not an issue on master https://github.com/MetaMask/metamask-extension/issues/2395

**Comment by tmashuang** [comment]
Recent commits have introduced a network switching bug. Bug does not allow network switching until the extension is closed and reopened. Error message `Cannot read property 'updateBalance' of undefined` in `computed-balance.js line: 24`

**Pull request merged**
