### PR TITLE
Add Incubed as network provider option

### PR DESCRIPTION
**Pull request by cerealkill**
Hi Metamask team!

We understand that Metamask uses Infura as provider, and we want to add Incubed as an option. Any user can run their own Incubed nodes, and be part of a decentralized provider infrastructure. To know how it works, try it, or even run a node, check our [documentation](https://in3.readthedocs.io/en/develop/). 
We from Slock.it are excited to release version 1.0 of Incubed and want to empower the community to use and test it on their dapps.

### Functionality
The user can select to enable the Incubed provider on the UI, under Settings -> Advanced. Metamask will automatically change the provider to the network the user is currently using. In case the network is local, custom or one not supported by incubed, the user will still be connected to it until a supported network is selected on the menu.
MM-IN3

### Changes
- New dependency for `in3-json-provider`
- New module Incubed network adapter
- Added 'enable Incubed network' toggle button under Settings -> Advanced
- Added a provider display in the network menu
- Hid unavailable networks on the network menu when incubed is enabled.
- Added tests for ui and modules.

### CODE REVIEW

**Comment by whymarrh** [comment]
Hey, @cerealkill, thanks for taking the time to work on this. The set of networks we offer (either via the network list or via a settings toggle, as added here) can't be extended to include everyone's networks and we don't have a way of honestly choosing among the various networks (see also Pocket's #6783 & xDai's #7492).

I'm going to close this for now. I appreciate you opening #7868 before starting this work—we can continue discussions there about how we might best make these networks available to our users. #3604 and #5101 are also relevant here, as ideally we should have a way to allow sites (maybe plugins even?) to add new networks. We welcome new ideas on these. We also [wrote up an article mid-2018](https://medium.com/metamask/4ffbee9ec64d) describing this our views on this in more detail.

**Comment by CJentzsch** [comment]
@whymarrh I think there is a misunderstanding. We don't want to add another network, but a different way to connect to the existing ones, mainly to the main net. 
Incubed is a decentralized alternative to Infura. It would be great to see if you could give your users the choice.

**Comment by whymarrh** [comment]
> It would be great to see if you could give your users the choice.

I agree, we're looking for a way to do exactly that but, unfortunately, I don't think that we ca simply add a toggle for your approach without excluding other approaches. We certainly can't add everyone's approach. #5101 is probably the closest thing—does that discussion offer any insight?

**Comment by CJentzsch** [comment]
#5101  is about network change. That is not what we want to achieve with this PR. This is about offering an alternative to Infura in order to connect to the same Ethereum main net. Not another new network or chain.

**Comment by whymarrh** [comment]
Yes, fair, my thinking is that a dapp would suggest this type of connection to Infura (which still stands as an option, but certainly less ideal, I'll concede). I think that's the _closest_ thing, but we're option to other options. We're open to new ideas that address the root problem you've raised, we don't have a great way of offering people choice. We simply can't add new UI for networks in this fashion, it's impractical.

**Comment by CJentzsch** [comment]
Where do you suggest such a choice should be put?
It would look something like Infura (currently as default), Incubed, <may be some other providers such as Etherscan or others>, Localhost (for people who run their own node) or point to a URL.
Here a snapshot of the MyCrypto Desktop app (Incubed being my custom node):
Screenshot 2020-02-26 at 23 09 58

**Comment by whymarrh** [comment]
Sorry, let's move this discussion to #7868

**Pull request closed without merging**
