### PR TITLE
Fix #16959 - Don't allow user to see welcome or password creation screen after a keyring has been created

### LINKED ISSUE #16959: [Bug]: Onboarding V2 - user is unable to navigate back from the create a password screen after closing and reopening MM
### Describe the bug

https://user-images.githubusercontent.com/53189696/207702943-6fc0e05f-c7cf-42cc-aad5-6a4754704477.mov

The user cannot return to the onboarding welcome page, after reopening the extension (if the extension stays open the user can navigate back and forth at leisure switching between an imported wallet or wallet creation)

### Steps to reproduce

1. Install the extension with ONBOARDING_V2 enabled
2. Go through the onboarding step to the `Secure your wallet` page
3. Close the extension
4. Open the extension

### Error messages or log output

_No response_

### Version

10.24.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by darkwing**
* Fixes #16959

## Manual Testing Steps

1. `ONBOARDING_V2 yarn start`
2. Install fresh MetaMask
3. During onboarding, set a password
4. Press the back button to try to create a new password
5. You can never set a new password as that could result in a loss of funds / problem

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

* Fixes #12345
* See: #67890
-->

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Review by digiwand — DISMISSED** [review]
LGTM! nice fix

**Comment by adonesky1** [comment]
This causes an issue when navigating back after creating a password in the `import wallet` flow:
https://user-images.githubusercontent.com/34557516/209033492-6e4d0701-33b1-4993-a7ec-ce9e71ae54c1.mov

**Review by PeterYinusa — DISMISSED** [review]
Can we make it so that clicking back twice doesn't take the user back whatsoever?

https://user-images.githubusercontent.com/53189696/210566331-95a2a5f2-f214-4778-9a9b-d0263a746437.mov

**Review by brad-decker — DISMISSED** [review]

**Review by jpuri — DISMISSED** [review]
Code changes look good, but I am not sure why it is updating lavamoat policy.

**Review by brad-decker — DISMISSED** [review]

**Comment by danjm** [comment]
was Peter's request above addressed? https://github.com/MetaMask/metamask-extension/pull/17024#pullrequestreview-1235888904

**Review by danjm — APPROVED** [review]
LGTM

**Review by brad-decker — APPROVED** [review]

**Pull request merged**
