### PR TITLE
Increase likelyhood of valid method signatures being returned by `getMethodData`

### PR DESCRIPTION
**Pull request by FrederikBolding**
## Explanation
Less than ideal method signatures have been added to the decentralized method registry that we use along with the 4byte directory. This PR changes how we choose which of these signatures to use. 

The new logic boils down to: Try both the decentralized method registry and the 4byte directory, for the 4byte directory picking the oldest method signature entry. When choosing between the signature from the decentralized registry and the 4byte registry, pick the shortest signature.

## Manual Testing Steps
For the specific bug:
- Complete an ERC721 approval and see that the method signature is correct

In general:
- Complete a few contract interactions to verify that method signatures are correct

## Pre-Merge Checklist

- [x] PR template is filled out
- [x] **IF** this PR fixes a bug, a test that _would have_ caught the bug has been added
- [ ] PR is linked to the appropriate GitHub issue
- [ ] PR has been added to the appropriate release Milestone

### + If there are functional changes:

- [ ] Manual testing complete & passed
- [ ] "Extension QA Board" label has been applied

### CODE REVIEW

**Comment by Nana12345678910** [comment]
I don't have access to my old phone number any more witch was 0405161403 my new number is 0405433015

**Comment by adonesky1** [comment]
Looks right to me. As [mentioned in that slack thread](https://consensys.slack.com/archives/GTQAGKY5V/p1655211587717079?thread_ts=1651507012.193889&cid=GTQAGKY5V), we will need to do migration to clear out the "knownMethodData" so these changes can be seen for users with incorrect data already persisted to state.

**Comment by adonesky1** [comment]
Happy to add the migration here if you'd like the assist @FrederikBolding

**Comment by FrederikBolding** [comment]
> Happy to add the migration here if you'd like the assist @FrederikBolding 

Feel free 👍

**Comment by danjm** [comment]
I see @adonesky1 offered to add a migration. That would be good. Alex: I think we can just clear the `knownMethodData` for all users. It is just a cache to reduce network calls, and will be repopulated.

**Review by adonesky1 — APPROVED** [review]
👍

**Review by kumavis — APPROVED** [review]

**Pull request merged**
