### PR TITLE
convert contextType to static prop for refactored components

### PR DESCRIPTION
**Pull request by TrejGun**

### CODE REVIEW

**Review by danjm — DISMISSED** [review]

**Comment by danjm** [comment]
@TrejGun Approved, but there are merge conflicts. Let me know if you need any help resolving them.

**Comment by TrejGun** [comment]
@danjm rebased

**Comment by danjm** [comment]
@TrejGun thanks, I'm going to try to figure out how to fix up these commits

**Comment by TrejGun** [comment]
@danjm I have fixed that issue with `push --force` now its good to go

**Review by danjm — APPROVED** [review]

**Pull request merged**
