### PR TITLE
Updated secondary copy and removed the address component from SetAppovalForAll and NFT Approve screens

### LINKED ISSUE #15704: Update secondary copy and remove the address component from SetApprovalForAll and NFT Approve screens
## Resources
[Figma Design file](https://www.figma.com/file/n0xMnZqQz4w9Sfa3ZdhWUi/Consentful-experience-for-token-allowances?node-id=2007%3A14561)

## Acceptance Criteria
1. This should be done after this https://github.com/MetaMask/metamask-extension/issues/15697 is completed;
2. The secondary copy is updated to `This allows a third party to access and transfer the following NFTs without further notice until you revoke its access.` (currently is "By granting permission, you are allowing the following account to access your funds");
3. The below address component is not shown on this confirmation screen anymore. 
Screen Shot 2022-08-24 at 18 29 49

## Steps to Reproduce
1. Open the test dapp https://metamask.github.io/test-dapp/
4. Under the collectibles section, click on "Deploy"
5.  Wait for transaction to be confirmed and click on "Mint"
6. Wait for transaction to be confirmed and click on "Set Approval For All"

### PR DESCRIPTION
**Pull request by VSaric**
## Explanation

Updated secondary copy and removed the address component from `SetAppovalForAll` and `NFT Approve` screens. Also updated the main copy for `NFT Approve` screen.

## More Information

* Fixes #15704 
* Blocked by #15756

### Before

https://user-images.githubusercontent.com/92527393/198316178-d604a0ee-8f01-4a95-9ff6-1ed752eb926d.mov

### After

https://user-images.githubusercontent.com/92527393/201886995-0ab32cac-58c4-474b-a2f9-aacb8771063c.mov

### NFT Approve screen

1. Open the test dapp https://metamask.github.io/test-dapp/
2. Under the collectibles section, click on `Deploy`
3. Wait for transaction to be confirmed and click on `Mint`
4. Wait for transaction to be confirmed and click on `Approve`

### SetApprovalForAll screen

1. Open the test dapp https://metamask.github.io/test-dapp/
2. Under the collectibles section, click on `Deploy`
3. Wait for transaction to be confirmed and click on `Mint`
4. Wait for transaction to be confirmed and click on `SetApprovalForAll`

### CODE REVIEW

**Comment by VSaric** [comment]
The main reason why this PR has `DO-NOT-MERGE` label is the first point in the ticket AC:

This should be done after this [Add a 'Verify contract details' link to SetApprovalForAll confirmation screens](https://github.com/MetaMask/metamask-extension/issues/15697)  is completed; 

So when that ticket is merged I will remove `DO-NOT-MERGE` label.

**Comment by mirjanaKukic** [comment]
Verified by QA

**Comment by bschorchit** [comment]
> The main reason why this PR has `DO-NOT-MERGE` label is the first point in the ticket AC:
> 
> This should be done after this [Add a 'Verify contract details' link to SetApprovalForAll confirmation screens](https://github.com/MetaMask/metamask-extension/issues/15697) is completed;
> 
> So when that ticket is merged I will remove `DO-NOT-MERGE` label.

The blocking ticket has now been merged :)

**Review by brad-decker — APPROVED** [review]

**Review by adonesky1 — APPROVED** [review]
LGTM

**Pull request merged**
