### PR TITLE
UX: Multichain: Move Add Account and Import Account into Account Menu Popover

### PR DESCRIPTION
**Pull request by darkwing**
## Explanation

At the moment, the `Add Account` and `Import Account` pages look bad now that we have a new account picker.  This PR moves the `Add Account` and `Import Account` functionality into the Account Menu Popover, providing a much better user experience!

## Screenshots/Screencaps

https://github.com/MetaMask/metamask-extension/assets/46655/909be9fa-f0e3-4356-8fa1-02a54a2f204f

## Manual Testing Steps

- Open the new Account Picker
- Click "Add Account"
- Click "<", see the account menu restored
- Click "Add Account"
- Create real account, see the user switch to that account
- Repeat for import

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Review by vthomas13 — DISMISSED** [review]

**Comment by NidhiKJha** [comment]
Add Account works perfectly fine but with the import account if I try to add a random string and then hit enter. The popover closes and no error is shown.
https://github.com/MetaMask/metamask-extension/assets/39872794/309dc9c7-3b88-4b65-8407-41949b7dec54

**Review by NidhiKJha — COMMENTED** [review]
Looking really good! Just some fixes for the import account:
1. The dropdown is not working for the import account 
2. If there is an error while importing the account. The error is visible on the settings page as well.
https://github.com/MetaMask/metamask-extension/assets/39872794/6662e8cd-7f71-4ccc-8060-4e4a4d959dcf

**Review by NidhiKJha — COMMENTED** [review]
Looking really good! Just some fixes for the import account:
1. The dropdown is not working for the import account 
2. If there is an error while importing the account. The error is visible on the settings page as well.

https://github.com/MetaMask/metamask-extension/assets/39872794/d2665ce5-547a-426c-8acc-b300dd59261b

**Review by NidhiKJha — COMMENTED** [review]
Question: The color of the required text should be red?
Screenshot 2023-06-09 at 4 29 15 PM

**Comment by NidhiKJha** [comment]
Looks really good! Just one change:

Importing error shows up on Settings Page
https://github.com/MetaMask/metamask-extension/assets/39872794/31e8ed44-24d3-40e7-84a9-077c53fe707b

**Comment by darkwing** [comment]
> Question: The color of the required text should be red? Screenshot 2023-06-09 at 4 29 15 PM

Good shout!  I've fixed it with one character! :)

**Review by NidhiKJha — COMMENTED** [review]
Amazing 😍 Code looks good! Add account works perfect! But the error persists on the settings page while importing an account.

https://github.com/MetaMask/metamask-extension/assets/39872794/394452f1-c0b0-4f67-851f-0c2890cf61ea

**Comment by DDDDDanica** [comment]
Hey David, the feature looks great and thanks for some bug fixes !
I was testing and found something not blocking, but not sure if this is intended and was wondering what is the preferred behavior.
In the new implementation, if there's an error of input, the previous input is kept now. Personally i think this is a better UX, but just want to make sure this is aligned with design ~

https://github.com/MetaMask/metamask-extension/assets/12678455/7712aae0-2aba-4ab2-b035-da917c66031d

**Review by vthomas13 — APPROVED** [review]

**Review by NidhiKJha — APPROVED** [review]

**Pull request merged**
