### PR TITLE
Add missing french traduction

### PR DESCRIPTION
**Pull request by Lapinou42**
Fixes: Add missing french traduction

Explanation:  
I add some missing french traduction and small fixes.

### CODE REVIEW

**Comment by mcmire** [comment]
Hey, sorry it's taken us so long to get back to you. We have a lot of new translations coming in via #13206, so I'll wait until that's merged first.

**Comment by Lapinou42** [comment]
Hey ! No worries 😉

**Comment by brad-decker** [comment]
@Lapinou42 our translation system has had a few PRs merged now, could you take a look at this and rebase so that we can consider this for inclusion?

**Comment by brad-decker** [comment]
Hey @Lapinou42 I am closing this PR due to it becoming stale. This doesn't mean we do not want this contribution, only that we are trying to clean our PR queue to keep our reviewers focused on the most up to date and mergeable prs. If you make the requested changes and rebase the PR you can reopen it for review. Thank you!

**Pull request closed without merging**
