### PR TITLE
Add  Euskara / Basque language

### PR DESCRIPTION
**Pull request by aitorla**
Fixes: #

Explanation:  

Manual testing steps:  
  - 
  - 
  -

### CODE REVIEW

**Comment by aitorla** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by aitorla — COMMENTED** [review]
I have read the CLA Document and I hereby sign the CLA

**Comment by brad-decker** [comment]
@aitorla could you run `yarn lint:fix` to fix the code lint issue. Thank you and thanks for the contribution.

**Comment by aitorla** [comment]
Hello,

I cannot make progress in solving the errors. Can someone help me?

Regards,

Aitor

**Review by darkwing — CHANGES_REQUESTED** [review]
Thank you for this @aitorla !  Could you add this change to https://github.com/MetaMask/metamask-extension/pull/12063, and then close this?

**Comment by darkwing** [comment]
Hello @aitorla !  Our main branch is `develop`, so you'll need to change this PR to merge into `develop`.

**Comment by darkwing** [comment]
Superceded by https://github.com/MetaMask/metamask-extension/pull/12653

**Pull request closed without merging**
