### PR TITLE
Privacy - Update onboarding metametrics text

### LINKED ISSUE #16711: Improve MetaMetrics onboarding copy specificity
Ensure the distinction between MetaMetrics and a provider are clearer. cc @coreyjanssen

### PR DESCRIPTION
**Pull request by darkwing**
## Explanation

Fixes: https://github.com/MetaMask/metamask-extension/issues/16711

Design: https://www.figma.com/file/iCOjL3k1BkQqpYHFUVVFUZ/Extension-Onboarding?node-id=3939%3A29433&t=9deUZGNyyzXkGMkH-0

# ToDo

- [x] Get design icons for listing
- [x] Figure out how to allow users to get to  the setting screen

## Screenshots/Screencaps

Coming soon.

### CODE REVIEW

**Review by SayaGT — CHANGES_REQUESTED** [review]
It looks beautiful! I think the copy needs to be updated but otherwise LGTM!

[Updated copy here](https://github.com/MetaMask/metamask-extension/issues/16711#issuecomment-1334605487)

**Comment by darkwing** [comment]
Copy updated!

**Review by danjm — DISMISSED** [review]
Looks good from a code perspective.

**Review by jpuri — DISMISSED** [review]

**Comment by darkwing** [comment]
After review from a variety of teams, we've decided not to go with this design set.  A new PR will replace this.

**Pull request closed without merging**
