### PR TITLE
perf: rewrite babel config to json for performance

### PR DESCRIPTION
**Pull request by naugtur**

### CODE REVIEW

**Comment by naugtur** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mcmire** [comment]
I tried this out and I'm not sure I saw the performance gains you mentioned in Slack.

I ran `node development/build/index.js scripts:core:prod:standardEntryPoints --apply-lavamoat false --lint-fence-files false` three times on develop and this branch and got:

```
develop: 69.1s, 67.4s, 67.2s
this branch: 72.3s, 67.5s, 67.4s
```

**Comment by brad-decker** [comment]
@naugtur is this still relevant or should we close this?

**Comment by naugtur** [comment]
I was surprised that it didn't produce visible results. Apparently there's other factors that need to coexist with the JS config to cause trouble. Unless we want to merge it for the simplification there's no reason to keep it at this time.

**Comment by brad-decker** [comment]
@naugtur feel free to reopen this in the future if it starts to show that it has performance impact. For now we'll close.

**Pull request closed without merging**
