### PR TITLE
Bump `@metamask/network-controller` to `15.1.0`

### PR DESCRIPTION
**Pull request by jiexi**
## **Description**

* Bump `@metamask/network-controller` to `15.1.0`
* Replace `eth-query` with `@metamask/eth-query`
* Bump `@metamask/eth-query` to `3.0.1` 

Needed for bumping `@metamask/assets-controller` to 18.0.0 from 16

## **Related issues**

See: https://github.com/MetaMask/metamask-extension/pull/21549

## **Manual testing steps**

Nothing should change for the end user

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by jiexi** [comment]
@metamaskbot update-policies

**Comment by jiexi** [comment]
@metamaskbot update-policies

**Comment by jiexi** [comment]
@metamaskbot update-policies

**Review by adonesky1 — APPROVED** [review]
LGTM!

**Review by BelfordZ — APPROVED** [review]

**Pull request merged**
