### PR TITLE
v12 cherrypick: Bump `queued-request-controller` to `^1.0.0` (#25310)

### PR DESCRIPTION
**Pull request by jiexi**
cherrypicks https://github.com/MetaMask/metamask-extension/commit/ba8d84eafd6012457e2cc7276473e5de5c03990d which bumps `queued-request-controller` to `^1.0.0` and fixes the `eth_requestAccounts` handling bug

Merge conflicts on the lavamoat policies

Fixes: https://github.com/MetaMask/metamask-extension/issues/25407

### CODE REVIEW

**Comment by Gudahtt** [comment]
@metamaskbot update-policies

**Review by Gudahtt — APPROVED** [review]
LGTM!

**Review by adonesky1 — APPROVED** [review]
LGTM!

**Comment by jiexi** [comment]
odd that the lavamoat policy is still failing

**Pull request merged**
