### PR TITLE
Bundle optimization: dedupe bn.js

### PR DESCRIPTION
**Pull request by kumavis**
dedupe `bn.js` (many many copies, ~1MB) and fix junk data we're passing to it in tests

accidentally temporarily included an unrelated deduping of `@ethersproject/hash`, undid that change with its related policy file

### CODE REVIEW

**Review by brad-decker — DISMISSED** [review]
Looks good to me, but as a heads up with the way yarn3 resolves things it may be impacted by my prs. I might tag you for a look at those once they get rebased to make sure i'm not undoing anything.

**Comment by adonesky1** [comment]
@kumavis how does this work? Are the test changes the only instances of where our use of `bn.js` v4 behaves differently than v5?

**Comment by kumavis** [comment]
@SocketSecurity ignore core-js@3.15.2

**Review by brad-decker — DISMISSED** [review]

**Comment by brad-decker** [comment]
@adonesky1 added QA externsion board label.

**Comment by kumavis** [comment]
replaced by https://github.com/MetaMask/metamask-extension/pull/20199

**Pull request closed without merging**
