### PR TITLE
Fix Delegate_Call Check

### PR DESCRIPTION
**Pull request by kumavis**
This contract hex does include the value `f4`, but it was compiled from a contract with no instance of `.delegatecall`. I believe `f4` in this case is part of some other value or contract address, and `ethBinToOps` has some error in how it skips pushed data.

### CODE REVIEW

**Comment by kumavis** [comment]
Starting this PR, will investigate

**Comment by flyswatter** [comment]
Should we just remove this feature until it works correctly?

**Comment by kumavis** [comment]
I'd like the source of the compiled code, initial op dump looks at least sane

**Comment by kumavis** [comment]
Etherscan's tool also shows a delegate call. https://etherscan.io/opcode-tool
I think we've made an incorrect assumption, and this code does legitimately contain `delgate_call`

**Comment by kumavis** [comment]
@flyswatter so I confirmed that our `delegate_call` analysis code was correct, and changed the test to expect `delegate_call` in that test code

**Pull request merged**
