### PR TITLE
fix: replace last usages of legacy gas fee polling with polling by networkClientId

### PR DESCRIPTION
**Pull request by jiexi**
## **Description**

https://github.com/MetaMask/metamask-extension/pull/23010 made initial changes to replace the GasFeeController's legacy gas fee polling in favor of polling via networkClientId. It was discovered that there are still lingering instances of the legacy gas fee polling which were causing double polling to occur since the legacy and networkClientId based polling run on separate loops. This PR fixes this by replacing those remaining legacy gas fee polling usages.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/24065?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/pull/23010

## **Manual testing steps**

1. Open background console -> Network tab
2. Open Extension Popup -> send -> enter address and amount -> next
3. Background console network tab should now start showing one single network request every 10s to the gas api endpoint

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by BelfordZ — DISMISSED** [review]
smell ya later, old polling!

**Review by adonesky1 — DISMISSED** [review]
LGTM!

**Review by jpuri — DISMISSED** [review]
I reviewed all confirmation components related code and it looks good 👍

**Review by adonesky1 — APPROVED** [review]

**Comment by adonesky1** [comment]
Wait actually I might be seeing an issue where polling continues after the send flow is closed.

**Review by jpuri — APPROVED** [review]

**Pull request merged**
