### PR TITLE
fix: Patch @metamask/key-tree

### PR DESCRIPTION
**Pull request by rekmarks**
Fixes Storybook failure by patching `@metamask/key-tree`.

This is merely an expedient to unblock #24550. The underlying issue will be addressed in the relevant packages.

### CODE REVIEW

**Comment by legobeat** [comment]
Is there a reason why this is specific only for `metamask-extension` and not other uses of the package? Or could we (also) make a corresponding change [upstream](https://github.com/MetaMask/key-tree)?

**Comment by rekmarks** [comment]
@legobeat added context to description:
> This is merely an expedient to unblock https://github.com/MetaMask/metamask-extension/pull/24550. The underlying issue will be addressed elsewhere.

**Comment by legobeat** [comment]
@rekmarks Is this still relevant after merge of #24550  and new version of `@metamask/key-tree`?

**Comment by rekmarks** [comment]
@legobeat no!

**Pull request closed without merging**
