### PR TITLE
chore: Bump address-book-controller to ^4.0.1

### PR DESCRIPTION
**Pull request by mcmire**
## **Description**

This upgrade does not introduce any functional changes, however, this version of `@metamask/address-book-controller` relies on a new version of `@metamask/base-controller` which protects state from being mutated accidentally and includes more type safety for messengers, among other improvements.

See changelog: https://github.com/MetaMask/core/blob/%40metamask/address-book-controller%404.0.1/packages/address-book-controller/CHANGELOG.md

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/24205?quickstart=1)

## **Related issues**

Progresses #24140.

## **Manual testing steps**

(No functional changes in this PR.)

## **Screenshots/Recordings**

(None)

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by mcmire** [comment]
@metamaskbot update-policies

**Review by legobeat — DISMISSED** [review]
LGTM!

**Review by mikesposito — DISMISSED** [review]
Looks good!

**Comment by mcmire** [comment]
@metamaskbot update-policies

**Comment by legobeat** [comment]
@metamaskbot update-policies

**Review by legobeat — APPROVED** [review]

**Review by mikesposito — APPROVED** [review]

**Pull request merged**
