### PR TITLE
release- Version v11.14.0

### PR DESCRIPTION
**Pull request by hjetpoluru**
## **Description**
RC v11.14.0

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/PR?quickstart=1)

### CODE REVIEW

**Comment by benjisclowder** [comment]
[Manual test scenarios:](https://github.com/MetaMask/metamask-extension/tree/develop/test/scenarios)

**Chrome**

- [ ] Onboarding - create a wallet
- [ ]  Onboarding - import a wallet
- [ ]  Keyring - connect hardware wallet
- [ ]  Keyring - reset a wallet
- [ ]  Transactions - send native token origin MM
- [ ]  Transactions - send native token origin dapp
- [ ]  Transactions - send ERC20 token origin MM
- [ ]  Transactions - send ERC20 token origin dapp
- [ ]  Transactions - send ERC721 token origin MM
- [ ]  Transactions - send ERC721 token origin dapp
- [ ]  Transactions - speed up transaction
- [ ]  Transactions - cancel transaction
- [ ]  Transactions - deploy failing transaction
- [ ]  Transactions - deposit and withdraw
- [ ]  Transactions - navigate multiple transactions
- [ ]  Tokens - import ERC20 token origin MM
- [ ]  Tokens - import ERC20 token origin dapp
- [ ]  Tokens - import ERC721 token origin MM
- [ ]  Tokens - import ERC721 token origin dapp
- [ ]  Tokens - import ERC1155 token origin MM
- [ ]  Tokens - import ERC1155 token origin dapp
- [ ]  Tokens - approve ERC1155 token
- [ ]  Tokens - approve ERC20 token
- [ ]  Tokens - approve ERC721 token
- [ ]  Tokens - autodetect tokens
- [ ]  Tokens - autodetect NFTs
- [ ]  Tokens - approve erc20 custom amount
- [ ]  ENS - name resolution
- [ ]  Phishing - warning page
- [ ]  Network - add custom network manually
- [ ]  Network - add custom network from the list of popular networks
- [ ]  Network - add custom network from dApp
- [ ]  Network - update networks
- [ ]  Network - switching networks
- [ ]  Network - delete networks from the dropdown list
- [ ]  Network - delete networks in Settings
- [ ]  Backup - backup user data
- [ ]  Backup - restore user data
- [ ]  Metrics - send event metrics
- [ ]  Address-book - add a contact to the address book
- [ ]  Address-book - remove a contact from the address book
- [ ]  Address-book - update a contact in the address book
- [ ]  Gas fee - EIP-1559 gas
- [ ]  Gas fee - legacy gas
- [ ]  Sign - eth sign
- [ ]  Sign - personal sign
- [ ]  Sign - sign in with ethereum
- [ ]  Sign - sign typed with data
- [ ]  Sign - sign typed data v3 with hardware wallet
- [ ]  Sign - sign typed data v4 with hardware wallet
- [ ]  Sign - personal sign with hardware wallet
- [ ]  Sign - eth sign with hardware wallet
- [ ]  Permissions - connecting and disconnecting from a dapp
- [ ]  Swap - smart swap
- [ ]  Swap - swap eth
- [ ]  Incoming transactions - receive native token
- [ ]  Settings - about MetaMask
- [ ]  Settings - general - change language
- [ ]  Settings - advanced - check custom nonce toggle
- [ ]  Settings - advanced - show hex data
- [ ]  Contract - deploy contract, mint and import NFT with hardware wallet
- [ ]  Contract - hardware wallet qr based connect
- [ ]  Contract - send token with hardware wallet

**Firefox**

- [ ]  Onboarding - create a wallet
- [ ]  Onboarding - import a wallet
- [ ]  Keyring - connect hardware wallet
- [ ]  Keyring - reset a wallet
- [ ]  Transactions - send native token origin MM
- [ ]  Transactions - send native token origin dapp
- [ ]  Transactions - send ERC20 token origin MM
- [ ]  Transactions - send ERC20 token origin dapp
- [ ]  Transactions - send ERC721 token origin MM
- [ ]  Transactions - send ERC721 token origin dapp
- [ ]  Transactions - speed up transaction
- [ ]  Transactions - cancel transaction
- [ ]  Transactions - deploy failing transaction
- [ ]  Transactions - deposit and withdraw
- [ ]  Transactions - navigate multiple transactions
- [ ]  Tokens - import ERC20 token origin MM
- [ ]  Tokens - import ERC20 token origin dapp
- [ ]  Tokens - import ERC721 token origin MM
- [ ]  Tokens - import ERC721 token origin dapp
- [ ]  Tokens - import ERC1155 token origin MM
- [ ]  Tokens - import ERC1155 token origin dapp
- [ ]  Tokens - approve ERC1155 token
- [ ]  Tokens - approve ERC20 token
- [ ]  Tokens - approve ERC721 token
- [ ]  Tokens - autodetect tokens
- [ ]  Tokens - autodetect NFTs
- [ ]  Tokens - approve erc20 custom amount
- [ ]  ENS - name resolution
- [ ]  Phishing - warning page
- [ ]  Network - add custom network manually
- [ ]  Network - add custom network from the list of popular networks
- [ ]  Network - add custom network from dApp
- [ ]  Network - update networks
- [ ]  Network - switching networks
- [ ]  Network - delete networks from the dropdown list
- [ ]  Network - delete networks in Settings
- [ ]  Backup - backup user data
- [ ]  Backup - restore user data
- [ ]  Metrics - send event metrics
- [ ]  Address-book - add a contact to the address book
- [ ]  Address-book - remove a contact from the address book
- [ ]  Address-book - update a contact in the address book
- [ ]  Gas fee - EIP-1559 gas
- [ ]  Gas fee - legacy gas
- [ ]  Sign - eth sign
- [ ]  Sign - personal sign
- [ ]  Sign - sign in with ethereum
- [ ]  Sign - sign typed with data
- [ ]  Sign - sign typed data v3 with hardware wallet
- [ ]  Sign - sign typed data v4 with hardware wallet
- [ ]  Sign - personal sign with hardware wallet
- [ ]  Sign - eth sign with hardware wallet
- [ ]  Permissions - connecting and disconnecting from a dapp
- [ ]  Swap - smart swap
- [ ]  Swap - swap eth
- [ ]  Incoming transactions - receive native token
- [ ]  Settings - about MetaMask
- [ ]  Settings - general - change language
- [ ]  Settings - advanced - check custom nonce toggle
- [ ]  Settings - advanced - show hex data
- [ ]  Contract - deploy contract, mint and import NFT with hardware wallet
- [ ]  Contract - hardware wallet qr based connect
- [ ]  Contract - send token with hardware wallet

**Comment by chloeYue** [comment]
Hi @jspence425, here's the extension RC v11.14.0. Thanks for helping testing!

**Comment by Bullcoiner** [comment]
**FireFox** 
- [x] Onboarding - create a wallet
- [x]  Onboarding - import a wallet
- [x]  Keyring - connect hardware wallet
- [x]  Keyring - reset a wallet
- [x]  Transactions - send native token origin MM
- [x]  Transactions - send native token origin dapp
- [x]  Transactions - send ERC20 token origin MM
- [x]  Transactions - send ERC20 token origin dapp
- [x]  Transactions - send ERC721 token origin MM
- [x]  Transactions - send ERC721 token origin dapp
- [x]  Transactions - speed up transaction
- [x]  Transactions - cancel transaction
- [ ]  Transactions - deploy failing transaction **(transaction/status did not fail)**
- [ ]  Transactions - deposit and withdraw **(Withdraw transaction didn't work, did not open or preview in extension)**
- [x]  Transactions - navigate multiple transactions
- [x]  Tokens - import ERC20 token origin MM
- [x]  Tokens - import ERC20 token origin dapp
- [x]  Tokens - import ERC721 token origin MM
- [x]  Tokens - import ERC721 token origin dapp
- [x]  Tokens - import ERC1155 token origin MM
- [x]  Tokens - import ERC1155 token origin dapp
- [x]  Tokens - approve ERC1155 token
- [x]  Tokens - approve ERC20 token
- [x]  Tokens - approve ERC721 token
- [x]  Tokens - autodetect tokens
- [x]  Tokens - autodetect NFTs
- [x]  Tokens - approve erc20 custom amount
- [x]  ENS - name resolution
- [x]  Phishing - warning page
- [x]  Network - add custom network manually
- [x]  Network - add custom network from the list of popular networks
- [x]  Network - add custom network from dApp
- [x]  Network - update networks
- [x]  Network - switching networks
- [x]  Network - delete networks from the dropdown list
- [x]  Network - delete networks in Settings
- [x]  Backup - backup user data
- [x]  Backup - restore user data
- [x]  Metrics - send event metrics
- [x]  Address-book - add a contact to the address book
- [x]  Address-book - remove a contact from the address book
- [x]  Address-book - update a contact in the address book
- [x]  Gas fee - EIP-1559 gas
- [x]  Gas fee - legacy gas
- [x]  Sign - eth sign
- [x]  Sign - personal sign
- [x]  Sign - sign in with ethereum
- [x]  Sign - sign typed with data
- [x]  Sign - sign typed data v3 with hardware wallet
- [x]  Sign - sign typed data v4 with hardware wallet
- [x]  Sign - personal sign with hardware wallet
- [x]  Sign - eth sign with hardware wallet
- [x]  Permissions - connecting and disconnecting from a dapp
- [x]  Swap - smart swap
- [x]  Swap - swap eth
- [x]  Incoming transactions - receive native token
- [x]  Settings - about MetaMask
- [x]  Settings - general - change language
- [x]  Settings - advanced - check custom nonce toggle
- [x]  Settings - advanced - show hex data
- [x]  Contract - deploy contract, mint and import NFT with hardware wallet
- [x]  Contract - hardware wallet qr based connect
- [x]  Contract - send token with hardware wallet

**Comment by sleepytanya** [comment]
🟢  Approval from the Confirmations System team.

**Comment by jiexi** [comment]
DappAPI and Devex look good

**Comment by plasmacorral** [comment]
🟢 Approval from Accounts team

**Comment by seaona** [comment]
Confirmations UX Team QA Sign Off status: 
- :green_circle: the RC looks good on my end (relevant changes are working correctly: increaseAllowance support, Base support, FF fix for new cdn..)
- :yellow_circle: I am not able to test the hardware wallet flows as I don't have the devices with me. However, our team hasn't made any recent change into the HW functionality. @sleepytanya  is checking these flows just in case

cc @benjisclowder @danjm @bschorchit

**Comment by sleepytanya** [comment]
@seaona 
[Invalid QR code message for Sign Typed Data](https://github.com/MetaMask/metamask-extension/issues/23961 ) and [inability to verify Sign Permit](https://github.com/MetaMask/metamask-extension/issues/22256) are present on the latest build.

**Comment by danjm** [comment]
@SocketSecurity ignore-all

Two new author warnings, one is a nodejs team member and one is a trezor org bot. The fetch usage in the transaction controller is part of the new simulations feature, and the shell access is part of one of our dev tools

**Review by danjm — APPROVED** [review]

**Pull request merged**
