### PR TITLE
Update design of phishing warning screen

### PR DESCRIPTION
**Pull request by whymarrh**
This PR updates the design for the phishing warning screen as per @cjeria's [comment on #2784](https://github.com/MetaMask/metamask-extension/issues/2784#issuecomment-426006076).

The implementation is contains intentional subtle differences from the design as I've tried to reuse existing icons, images, and font styles. I've also kept all of the words from the original text (e.g. #5848, #5864, and #5875).

**Old vs. new warning screens:**

screen shot 2019-02-05 at 13 10 48

screen shot 2019-02-05 at 13 15 30

### CODE REVIEW

**Comment by whymarrh** [comment]
@danfinlay this touches some of the wording changes you've recently made, let me know your thoughts on this as well

**Review by danjm — DISMISSED** [review]

**Review by tmashuang — DISMISSED** [review]

**Comment by whymarrh** [comment]
I'm going to revert the wording on this PR back to the previous one. We should revisit the wording separately.

**Comment by whymarrh** [comment]
I've updated the wording here/reverted the wording changes here—this PR now contains no wording changes. This is good for another round of review.

**Review by danjm — APPROVED** [review]
code looks good

**Pull request merged**
