### PR TITLE
Extend timeout

### PR DESCRIPTION
**Pull request by veronicaz41**
## Explanation

We are trying to generate zk proof in snap, and it keeps timeout. Extending timeout works for us.

## Manual testing steps

I have read the CLA Document and I hereby sign the CLA

### CODE REVIEW

**Comment by veronicaz41** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by rekmarks** [comment]
Thank you for submitting this, @veronicaz41. I'm marking this as "do not merge" since we need to evaluate this before making a decision about how to solve your issue.

A few questions:

1. How frequently do you need to perform the expensive operation? For example, is it only at initialization or can it occur with arbitrary frequency?
2. How you checked exactly how long the operations take?

**Comment by veronicaz41** [comment]
FYI, this is our snap: https://github.com/0xPARC/cabal/tree/main/snap
To answer your question:
1. It is not at initialization, it can occur with arbitrary frequency
2. I didn't exactly time it, but I tested a few numbers, anything  much lower (e.g. 90000) would timeout. I also want to give it a bit room in case we change our circuits.
This is what takes a long time: https://github.com/0xPARC/cabal/blob/main/snap/src/snark_utils/generate_proof.js#L9-L21

Happy to change a different number, or do something entirely different.  Just let us know.

**Comment by veronicaz41** [comment]
Actually maybe we can make this configurable in the snap somehow, rather than hard code like this? @rekmarks

**Pull request closed without merging**
