### PR TITLE
chore: Bump `@metamask/transaction-controller` to v34

### PR DESCRIPTION
**Pull request by Gudahtt**
## **Description**

The `@metamask/transaction-controller` package has been updated from v32 to v34. The `@metamask/user-operation-controller` package had to be bumped as well to avoid new peer dependency warnings.

Primarily the only breaking changes in these ranges were peer dependency updates and an update to the minimum supported Node.js version. The new peer dependencies did not introduce any new warnings, they are all met. This update has resolved some pre-existing peer dependency warnings.

The only functional change required was this update to the TransactionController in v33.0.0:

```
- **BREAKING:** The `TransactionController` messenger must now allow the `AccountsController:getSelectedAccount` action ([#4244](https://github.com/MetaMask/core/pull/4244))

...

- **BREAKING:** Remove `getSelectedAddress` option from `TransactionController` ([#4244](https://github.com/MetaMask/core/pull/4244))
  - The AccountsController is used to get the currently selected address automatically.
```

That change has been applied.

See the full changelogs here:
* [`@metamask/transaction-controller`](https://github.com/MetaMask/core/blob/%40metamask/transaction-controller%4034.0.0/packages/transaction-controller/CHANGELOG.md)
* [`@metamask/user-operation-controller`](https://github.com/MetaMask/core/blob/%40metamask/user-operation-controller%4013.0.0/packages/user-operation-controller/CHANGELOG.md)

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/26124?quickstart=1)

## **Related issues**

This helps unblock #9372

## **Manual testing steps**

N/A

## **Screenshots/Recordings**

N/A

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by Gudahtt** [comment]
@metamaskbot update-policies

**Review by cryptodev-2s — APPROVED** [review]
LGTM!

**Review by kanthesha — APPROVED** [review]
LGTM.

**Review by mcmire — APPROVED** [review]
LGTM!

**Pull request merged**
