### PR TITLE
Fix #12190 - Implement new pin extension view for onboarding

### LINKED ISSUE #12190: Pin Extension View

### PR DESCRIPTION
**Pull request by darkwing**
Fixes: #12190

Explanation:  

To Do:  
  - Implement localization texts
  - Implement billboard as SVG
  - Wire up button

### CODE REVIEW

**Review by perty69 — DISMISSED** [review]

**Review by jpuri — DISMISSED** [review]
I added a small feedback. Looks good otherwise. 🚀

**Comment by darkwing** [comment]
This *might* be blocked by https://github.com/MetaMask/metamask-extension/pull/12356

**Comment by adonesky1** [comment]
Things seem a bit wonky in RTL:
Screen Shot 2021-10-15 at 2 02 33 PM
 
 Also could you add a `max-width`?

**Comment by darkwing** [comment]
Updated to add `max-width`; I tried the following for RTL support:  https://gist.github.com/darkwing/884d185a58f45a48979dc79632dbdf91

It doesn't appear to work properly though.  I think we should open a separate ticket for RTL at the end, and evaluate as we go through each screen.

**Review by adonesky1 — DISMISSED** [review]
LGTM!

**Review by mcmire — DISMISSED** [review]
I had a question but this looks good to me regardless.

**Review by adonesky1 — APPROVED** [review]

**Review by mcmire — APPROVED** [review]

**Pull request merged**
