### PR TITLE
[FIX #12760] Highlighting on search

### LINKED ISSUE #12760: Setting search feature - New Search component
User story:  As a user I want to search the settings menu to navigate it easily.
https://www.figma.com/file/BLQYdGJFyhvSf4JtxQQrQj/Search-Settings-Menu?node-id=1%3A3

Task:
Create the search component. Depending on the status the component will looks like:
image
Pending:
image
 Term entered:
image
No matching result:
image

Task: Implement the search component in all  Settings pages (the header component of the settings component)

Popup view:
image

Full screen view:
image

Acceptance criteria:
- On entering more than 3 characters in the search textbox, application should return the matching results.
- Search is performed on all settings menu items (names and/or description) by entered term. 
- The match is when the term is found in the menu item name in any place
- Results are return in the drop down as shown on the Figma screenshots
image
- If there are no results the component will looks like:
image
- Clicking on the menu item from the search result, the menu item will be opened.
image 
- User will be able to search again without switching the page:
image
- On clicking the link: "_Request here_" a new form will be opened
- Search component should be shown on all Settings pages. Probably it is enough to implement it in the Header component.

### PR DESCRIPTION
**Pull request by amerkadicE**
Fix: [#12760](https://github.com/MetaMask/metamask-extension/issues/12760)

Explanation:  
Fix for highlighting on search.
Some search results element were not highlighting because the highlight function execute before re-render. With this fix we make sure that the highlight function execute after re-render and all elements are highlighted correctly.

Old highlight:
Screenshot 2022-02-23 at 11 57 51
Screenshot 2022-02-23 at 11 57 37

New highlight:
Screenshot 2022-02-23 at 12 00 48

Screenshot 2022-02-23 at 12 00 57

Manual testing steps:  
  - Check new highlighting in search feature

### CODE REVIEW

**Comment by mirjanaKukic** [comment]
Verified by QA

**Review by danjm — APPROVED** [review]
This looks good. Nice catch

**Review by jpuri — COMMENTED** [review]
🚢

**Review by jpuri — APPROVED** [review]

**Comment by darkwing** [comment]
Has 2 approvals, so merging.  Thank you @amerkadicE !

**Pull request merged**
