### PR TITLE
Metatx typed message

### PR DESCRIPTION
**Pull request by shahafn**
Draft of meta-tx support

### CODE REVIEW

**Comment by Gudahtt** [comment]
Hi @shahafn - could you target `develop` instead of the release branch? In general we prefer to land everything in `develop` first before including it in a release.

**Comment by shahafn** [comment]
@Gudahtt sure. The reason I targeted this branch instead of develop, was that I did it yesterday before you had v7.7.3 changes on which I rely on develop, so I ended up checking out from v7.7.3 intially.

**Comment by whymarrh** [comment]
@shahafn would you mind rebasing this PR on the latest `develop`, there seem to be a lot of extraneous changes here now.

**Comment by whymarrh** [comment]
@shahafn feel free to open this up again when it is ready for review

**Pull request closed without merging**
