### PR TITLE
RPC error middleware for json-rpc-engine

### LINKED ISSUE #794: Preserve relevant error messages from RPC node
When there is a solidity compilation error, in addition to `error.message` there is additional error information coming from Parity, in its return body, and that should be included on the Error that we pass to the Dapps.

[This StackOverflow issue](https://ethereum.stackexchange.com/questions/9873/compile-smart-contract-in-the-console-browser/9890#9890) demonstrates the easy confusion.

### LINKED ISSUE #1477: Throw descriptive error on bad RPC response
Instead of:
` callback contain no result Error: SyntaxError: Unexpected token < in JSON at position 0.`

Like in:
https://ethereum.stackexchange.com/questions/16505/remix-browser-solidity-wont-deploy-my-contract-through-metamask/16515#16515

### LINKED ISSUE #3054: Rpc error with payload
Having this problem.. trying to buy on Ethercraft.io, free items with low gas, but sometimes it goes through without any problem. sometimes all the transactions fail. Some not even able to click. Just no info, no error.

Once we hit submit with desired gas, the pop up just stays there turned white.. for those transactions no txid, Not clickable

### LINKED ISSUE #3487: Make provider errors more useful
Related to #3140 

When we switched to the new infura provider, we seem to have regressed in error comprehensibility. We are throwing generic `-32603` for a ton of cases.

Here's one simple web3 call that throws this error:
```
web3.currentProvider.sendAsync({ method: 'debug_traceTransaction', params: ['0x33ab8f2c2f73aaef9e0d1b620d8aeabd37dd8f975bb3743d11278ec13214ba38'], from: web3.eth.accounts[0] }, console.log)
```

The response doesn't give us much to go on:
```
error: code: -32603
id: undefined
jsonrpc: undefined
```

I'll lay that out as our first test-case. We should return at least a "method not found" error when a non existent method is thrown. Hopefully while that error message is added, we can pass some more meaningful data back in general, too.

### PR DESCRIPTION
**Pull request by bitpshr**
This PR implements new `json-rpc-engine`-compatible middleware intended to log consistent, human-readable RPC error messages.

Even though the JSON-RPC 2.0 specification documents `message` as a [required property on the RPC error object](http://www.jsonrpc.org/specification#error_object), it's `undefined` for most standard RPC error codes when hitting the latest Infura provider. This middleware logs predefined messages based on RPC error codes by default; it can also be configured to use provider-supplied error messages if they exist and to only fall back on predefined messages. The original RPC error object is also always logged regardless of middleware configuration so any additional error `data` can still be inspected, such as solidity compilation information.

Resolves #3487
Resolves #3054
Resolves #1477
Resolves #794

### CODE REVIEW

**Comment by danfinlay** [comment]
When I try the reproduction step from #3847 I still get an anonymous error:

```
web3.currentProvider.sendAsync({ method: 'debug_traceTransaction', params: ['0x33ab8f2c2f73aaef9e0d1b620d8aeabd37dd8f975bb3743d11278ec13214ba38'], from: web3.eth.accounts[0] }, console.log)
```

That just means it doesn't fix _that_ issue _yet_.

I couldn't figure out how to reproduce #3054, I'm fine closing it.

#1477 reproduction steps didn't throw an error for me, so I couldn't verify the fix.

#974 still gave returned an unreadable error message to the dapp:

```
Error: Invalid JSON RPC response: {"id":1,"jsonrpc":"2.0","error":{"code":-32603}}
    at Object.InvalidResponse (util.js:481)
```

Is it possible I built wrong or something? Do you get a message when calling that top method in browser console?

**Comment by bitpshr** [comment]
**Re: #3487:**

We were properly logging the RPC error object to the console, but that error object wasn't populated with a required `message` property that explains the error code. The middleware now properly logs the correct error message despite no message existing on the error object:

```
MetaMask - RPC Error: Internal JSON-RPC error. {code: -32603}
```

**Comment by bitpshr** [comment]
@danfinlay thanks for the review. You were right, I was logging the errors instead of augmenting the actual object that's passed up the chain to a dapp.

This should be ready for another review when you have a chance. I verified that the returned error object now contains a valid `message` for #3487 and #794.

**Review by anthony33lewis — APPROVED** [review]

**Comment by anthony33lewis** [comment]
Thank You

**Review by danfinlay — DISMISSED** [review]
Looks good, thank you, this is going to make a lot of devs happy. Maybe add a changelog entry to let them know?

**Comment by bitpshr** [comment]
Thanks @danfinlay, `CHANGELOG.md` entry added.

**Comment by danfinlay** [comment]
Oh wow, test-deps failing for node security. How is this not an issue on `master`? Is this a new addition, @kumavis?

**Comment by bitpshr** [comment]
@danfinlay It looks like `develop` was fixed up, so CI passes now after a rebase. Ready for another review when you have a chance, thanks again!

**Comment by kumavis** [comment]
this seems like it should go into `json-rpc-engine` as core always-on functionality

**Comment by bitpshr** [comment]
@kumavis Would you prefer I close this and submit a PR against `json-rpc-engine` instead? Technically the `message` property we're patching is required per the JSON-RPC 2.0 specification, so this middleware is paving over an Infura shortcoming and is specific to our reliance on this specific version of the Infura API that lacks proper error messages.

**Review by danfinlay — APPROVED** [review]
This looks like a good solution to me, I don't think this should be in core `json-rpc-engine`, since it's compensating for an infura quirk. Maybe we could call it an `infura-error-middleware`.

**Pull request merged**
