### PR TITLE
NFT Approval and SetApprovalForAll confirmation screens header updated

### LINKED ISSUE #15695: Update the NFT Approval and SetApprovalForAll confirmation screens to use the new header component
## Resources
[Figma Design file](https://www.figma.com/file/n0xMnZqQz4w9Sfa3ZdhWUi/Consentful-experience-for-token-allowances?node-id=2007%3A15702)

## Acceptance Criteria
1. When SetApprovalForAll confirmation screen is displayed it now shows the new header component that was created on https://github.com/MetaMask/metamask-extension/pull/15614 (It's the same one used on the new token allowance confirmation screens)
2. The balance information on the header should display the native asset balance instead of a specific token balance as it was the case with token allowances
3. The same is true for the NFT approval confirmation screen.

## Steps to Reproduce
1. Open the test dapp https://metamask.github.io/test-dapp/
2. Under the collectibles section, click on "Deploy"
4. Wait for transaction to be confirmed and click on "Mint"
5. Wait for transaction to be confirmed and click on "Approve" to get our NFT approval confirmation screen
6. Click on "Set Approval For All" to get our setApprovalForAll confirmation screen

### PR DESCRIPTION
**Pull request by filipsekulic**
## Explanation
Updated the NFT Approval and SetApprovalForAll confirmation screens header.

## More Information
* Fixes #15695
* Related #15614

### Before

https://user-images.githubusercontent.com/92310504/187452123-80cab97b-f74d-449b-8bee-431c2d6565ed.mov

### After

https://user-images.githubusercontent.com/92310504/189658658-edbdb129-c9ed-4651-9265-90b06adfc830.mov

## Manual Testing Steps
1st case: 
1. Open the test dapp https://metamask.github.io/test-dapp/
2. Under the "Collectibles" section, click on "Deploy"
3. Wait for transaction to be confirmed and click on "Mint"
4. Wait for transaction to be confirmed and click on "Approve" to get our NFT approval confirmation screen
5. Click on "Set Approval For All" to get our setApprovalForAll confirmation screen

2nd case:

1. Open the test dapp https://metamask.github.io/test-dapp/
2. Under the "Send tokens" section, click on "Create token"
3. Wait for the token to be created and click on "Approve tokens" or "Approve tokens without gas"

### CODE REVIEW

**Comment by mirjanaKukic** [comment]
Verified by QA

**Comment by adonesky1** [comment]
Do we want this header show up for ERC20 approvals too? Probably right?

https://user-images.githubusercontent.com/34557516/189396810-ddc94da8-561c-4fa5-a10e-39cf75373213.mov

**Review by adonesky1 — CHANGES_REQUESTED** [review]
Seems like we want to make this change for ERC20 approvals too?

**Comment by filipsekulic** [comment]
> Seems like we want to make this change for ERC20 approvals too?

Yes, I had checked it previously with @bschorchit before I made changes here: 45ebf6ce6f448258652850fdcfa0fdb65ac91cd5

**Comment by adonesky1** [comment]
@filipsekulic need a rebase here and then looks good to go!

**Comment by filipsekulic** [comment]
> @filipsekulic need a rebase here and then looks good to go!

Done :white_check_mark:

**Review by adonesky1 — DISMISSED** [review]
LGTM! Thanks Filip!

**Review by brad-decker — APPROVED** [review]

**Review by adonesky1 — APPROVED** [review]

**Pull request merged**
