### PR TITLE
Using translated string for state log

### LINKED ISSUE #7254: State log file name should use translated string
This should use a translatable string for multi-language support, is currently hard-code in: https://github.com/MetaMask/metamask-extension/blob/develop/ui/app/pages/settings/advanced-tab/advanced-tab.component.js#L88

### PR DESCRIPTION
**Pull request by ryanml**
Fixes: https://github.com/MetaMask/metamask-extension/issues/7254

### CODE REVIEW

**Review by Gudahtt — APPROVED** [review]
Looks good, thanks!

I am wondering if this'll cause issues on filesystems without full UTF-8 support 🤔. This isn't an especially critical button though; we can deal with that if we find a case of it.

**Comment by Gudahtt** [comment]
It's too bad... if I had an easy way to test this, I'd suggest wrapping this in `try...catch` to fallback to using the English string if the localized string fails, but I'm not sure it'd even throw an exception in that case if it did fail. No point in adding a `try...catch` unless we're sure it'll work.

**Comment by ryanml** [comment]
@Gudahtt - I think we'd have to modify the behavior of `t` for that. IIRC if the translation is not available it will just echo out the key.

**Comment by Gudahtt** [comment]
@ryanml Sorry I meant to refer to the case where the `exportAsFile` function fails, not for when `t` fails. The concern was for the case where the translation is present, but saving the file fails due to filename encoding problems.

Maybe it won't ever fail; I was just speculating. I wasn't confident that all common filesystems supported UTF-8 filenames.

**Pull request merged**
