### PR TITLE
updated to new checbox in unconnected-account-alert

### PR DESCRIPTION
**Pull request by akp111**
## Explanation

As per the comments on this PR https://github.com/MetaMask/metamask-extension/pull/20198, addressing the issue https://github.com/MetaMask/metamask-extension/issues/20164, I have broken down the changes into smaller PR. This one addresses replacing the checkbox in `ui/components/app/alerts/unconnected-account-alert/unconnected-account-alert.js`
## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [x] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Review by georgewrmarshall — CHANGES_REQUESTED** [review]
Thanks for your contribution @akp111, could you please add some before and after screencasts of the UI to show no visual regressions?

**Comment by akp111** [comment]
> Thanks for your contribution @akp111, could you please add some before and after screencasts of the UI to show no visual regressions?

Hey @georgewrmarshall , actually can you point me to which UI its pointing to. Or share any docs that can help me figure out the UI to which this component is pointing to?

**Comment by georgewrmarshall** [comment]
> > Thanks for your contribution @akp111, could you please add some before and after screencasts of the UI to show no visual regressions?
> 
> Hey @georgewrmarshall , actually can you point me to which UI its pointing to. Or share any docs that can help me figure out the UI to which this component is pointing to?

Hey @akp111, if you are making changes to a file that has a `.stories` file it should be reasonably straight forward because you can view that component in storybook using
```
yarn storybook
```
But if it doesn't have a storybook file you will have to track it down inside of the extension which can prove tricky. I usually just try to find what components are using the component I'm looking for to find clues. Hope that helps. The other option is to create a storybook file for the component and include it in the PR. You can try to use this boilerplate but it may require you to mock it with redux data

https://metamask.github.io/metamask-storybook/?path=/docs/getting-started-documentation-guidelines--docs#creating-a-story

```
import React from 'react';
import MyComponent from '.';

export default {
  title: 'Components/UI/MyComponent', // title should follow the folder structure location of the component. Don't use spaces.

};

export const DefaultStory = () => <MyComponent />;

DefaultStory.storyName = 'Default';
```

**Comment by georgewrmarshall** [comment]
Hey @akp111, I'm going to close this PR because it does not meet the acceptance criteria listed below. Please reopen a PR once you are able to get the before and after screenshots. Thanks for your contribution
> The PR must include before and after screenshots of the UI to ensure there are no visual regressions.
https://github.com/MetaMask/metamask-extension/issues/20163

**Pull request closed without merging**
