### PR TITLE
Version v11.7.0

### PR DESCRIPTION
**Pull request by danjm**

### CODE REVIEW

**Comment by chloeYue** [comment]
Manual test scenarios:

Chrome

- [ ] onboarding - create a wallet
- [ ] onboarding - import a wallet
- [ ] keyring - connect hardware wallet
- [ ] keyring - reset a wallet
- [ ] transactions - send native token origin MM
- [ ] transactions - send native token origin dapp
- [ ] transactions - send erc20 token origin MM
- [ ] transactions - send erc20 token origin dapp
- [ ] transactions - send erc721 token origin MM
- [ ] transactions - send erc721 token origin dapp
- [ ] transactions - speed up transaction
- [ ] transactions - cancel transaction
- [ ] tokens - import erc20 token origin MM
- [ ] tokens - import erc20 token origin dapp
- [ ] tokens - import erc721 token origin MM
- [ ] tokens - import erc721 token origin dapp
- [ ] tokens - import erc1155 token origin MM
- [ ] tokens - approve erc1155 token
- [ ] tokens - approve erc20 token
- [ ] tokens - approve erc721 token
- [ ] tokens - autodetect tokens
- [ ] tokens - autodetect NFTs
- [ ] ens - name resolution
- [ ] phishing - warning page
- [ ] network - add custom network manually
- [ ] network - add custom network from the list of popular networks
- [ ] network - add custom network from dApp
- [ ] network - update networks
- [ ] network - switching networks
- [ ] network - delete networks from the dropdown list
- [ ] network - delete networks in Settings
- [ ] backup - backup user data
- [ ] backup - restore user data
- [ ] metrics - send event metrics
- [ ] address-book - add a contact to the address book
- [ ] address-book - remove a contact from the address book
- [ ] address-book - update a contact in the address book
- [ ] gas fee - EIP-1559 gas
- [ ] gas fee - legacy gas
- [ ] sign - eth sign
- [ ] sign - personal sign
- [ ] sign - sign in with ethereum
- [ ] sign - sign typed with data
- [ ] permissions - connecting and disconnecting from a dapp
- [ ] swap - smart swap
- [ ] swap - swap eth
- [ ] incoming transactions - receive native token


Firefox

- [X] onboarding - create a wallet
- [X] onboarding - import a wallet
- [X] keyring - connect hardware wallet
- [X] keyring - reset a wallet
- [ ] transactions - send native token origin MM
- [ ] transactions - send native token origin dapp
- [ ] transactions - send erc20 token origin MM
- [ ] transactions - send erc20 token origin dapp
- [ ] transactions - send erc721 token origin MM
- [ ] transactions - send erc721 token origin dapp
- [ ] transactions - speed up transaction
- [ ] transactions - cancel transaction
- [X] tokens - import erc20 token origin MM
- [X] tokens - import erc20 token origin dapp
- [X] tokens - import erc721 token origin MM
- [X] tokens - import erc721 token origin dapp
- [X] tokens - import erc1155 token origin MM
- [ ] tokens - approve erc1155 token
- [ ] tokens - approve erc20 token
- [ ] tokens - approve erc721 token
- [X] tokens - autodetect tokens
- [X] tokens - autodetect NFTs
- [ ] ens - name resolution
- [ ] phishing - warning page
- [X] network - add custom network manually
- [X] network - add custom network from the list of popular networks
- [X] network - add custom network from dApp
- [X] network - update networks
- [X] network - switching networks
- [X] network - delete networks from the dropdown list
- [X] network - delete networks in Settings
- [X] backup - backup user data
- [X] backup - restore user data
- [X] metrics - send event metrics
- [X] address-book - add a contact to the address book
- [X] address-book - remove a contact from the address book
- [X] address-book - update a contact in the address book
- [ ] gas fee - EIP-1559 gas
- [ ] gas fee - legacy gas
- [ ] sign - eth sign
- [ ] sign - personal sign
- [ ] sign - sign in with ethereum
- [ ] sign - sign typed with data
- [X] permissions - connecting and disconnecting from a dapp
- [ ] swap - smart swap
- [ ] swap - swap eth
- [ ] incoming transactions - receive native token

**Comment by chloeYue** [comment]
Release tracker for change validation on v11.7.0:
https://docs.google.com/spreadsheets/d/1tsoodlAlyvEUpkkcNcbZ4PM9HuC9cEM80RZeoVv5OCQ/edit#gid=1227924347

- [ ]  MMI: @zone-live / @shane-t - There are 5 MMI changes in v11.7.0. We would like to get your team's approval on this release by next Thursday.
- [ ]  Snaps: @bowensanders / @FrederikBolding / @Montoya - There are 12 Snaps changes in v11.7.0. We would like to get your team's approval on this release by next Thursday.
- [ ]  Confirmation UX: @seaona - There is 1 Confirmations UX changes in v11.7.0. We would like to get your team's approval on this release by next Thursday.
- [X]  Confirmation Systems: @sleepytanya - There are 2 Confirmation Systems changes in v11.7.0. We would like to get your team's approval on this release by next Thursday.
- [ ]  Accounts: @plasmacorral - There are 4 Accounts changes in v11.7.0. We would like to get your team's approval on this release by next Thursday.
- [ ]  Assets: @sahar-fehri / @alfeng6 There is 1 Assets changes in v11.7.0. We would like to get your team's approval on this release by next Thursday.
- [ ]  Design/Systems: @georgewrmarshall There are 2 Design/Systems changes in v11.7.0. We would like to get your team's approval on this release by next Thursday.
- [ ]  Dapp API: @tmashuang There is one Dapp API change in v11.7.0. We would like to get your team's approval on this release by next Thursday.

Note: please attach all the release bugs to this bug report epic here: https://github.com/MetaMask/MetaMask-planning/issues/1718

Thanks all !

**Comment by danjm** [comment]
<details><summary>Builds ready [9787b7e]</summary><ul><li>builds: <a href="https://output.circle-artifacts.com/output/job/93b95f25-c16c-4116-933c-71c580febd46/artifacts/0/builds/metamask-chrome-11.7.0.zip">chrome</a>, <a href="https://output.circle-artifacts.com/output/job/93b95f25-c16c-4116-933c-71c580febd46/artifacts/0/builds/metamask-firefox-11.7.0.zip">firefox</a></li>
<li>builds (beta): <a href="https://output.circle-artifacts.com/output/job/93b95f25-c16c-4116-933c-71c580febd46/artifacts/0/builds-beta/metamask-beta-chrome-11.7.0.zip">chrome</a></li>
<li>builds (flask): <a href="https://output.circle-artifacts.com/output/job/93b95f25-c16c-4116-933c-71c580febd46/artifacts/0/builds-flask/metamask-flask-chrome-11.7.0-flask.0.zip">chrome</a>, <a href="https://output.circle-artifacts.com/output/job/93b95f25-c16c-4116-933c-71c580febd46/artifacts/0/builds-flask/metamask-flask-firefox-11.7.0-flask.0.zip">firefox</a></li>
<li>builds (MMI): <a href="https://output.circle-artifacts.com/output/job/93b95f25-c16c-4116-933c-71c580febd46/artifacts/0/builds-mmi/metamask-mmi-chrome-11.7.0-mmi.0.zip">chrome</a>, <a href="https://output.circle-artifacts.com/output/job/93b95f25-c16c-4116-933c-71c580febd46/artifacts/0/builds-mmi/metamask-mmi-firefox-11.7.0-mmi.0.zip">firefox</a></li>
<li>builds (test): <a href="https://output.circle-artifacts.com/output/job/93b95f25-c16c-4116-933c-71c580febd46/artifacts/0/builds-test/metamask-chrome-11.7.0.zip">chrome</a>, <a href="https://output.circle-artifacts.com/output/job/93b95f25-c16c-4116-933c-71c580febd46/artifacts/0/builds-test/metamask-firefox-11.7.0.zip">firefox</a></li>
<li>builds (test-flask): <a href="https://output.circle-artifacts.com/output/job/93b95f25-c16c-4116-933c-71c580febd46/artifacts/0/builds-test-flask/metamask-flask-chrome-11.7.0-flask.0.zip">chrome</a>, <a href="https://output.circle-artifacts.com/output/job/93b95f25-c16c-4116-933c-71c580febd46/artifacts/0/builds-test-flask/metamask-flask-firefox-11.7.0-flask.0.zip">firefox</a></li>
<li>build viz: <a href="https://output.circle-artifacts.com/output/job/93b95f25-c16c-4116-933c-71c580febd46/artifacts/0/build-artifacts/build-viz/index.html">Build System</a></li>
<li>mv3: <a href="https://output.circle-artifacts.com/output/job/93b95f25-c16c-4116-933c-71c580febd46/artifacts/0/test-artifacts/chrome/mv3/initialisation/background/index.html">Background Module Init Stats</a></li>
<li>mv3: <a href="https://output.circle-artifacts.com/output/job/93b95f25-c16c-4116-933c-71c580febd46/artifacts/0/test-artifacts/chrome/mv3/initialisation/ui/index.html">UI Init Stats</a></li>
<li>mv3: <a href="https://output.circle-artifacts.com/output/job/93b95f25-c16c-4116-933c-71c580febd46/artifacts/0/test-artifacts/chrome/mv3/load_time/index.html">Module Load Stats</a></li>
<li>mv3: <a href="https://output.circle-artifacts.com/output/job/93b95f25-c16c-4116-933c-71c580febd46/artifacts/0/test-artifacts/chrome/mv3/bundle_size.json">Bundle Size Stats</a></li>
<li>mv2: <a href="https://output.circle-artifacts.com/output/job/93b95f25-c16c-4116-933c-71c580febd46/artifacts/0/test-artifacts/chrome/benchmark/user_actions.json">E2e Actions Stats</a></li>
<li>code coverage: <a href="https://output.circle-artifacts.com/output/job/93b95f25-c16c-4116-933c-71c580febd46/artifacts/0/coverage/index.html">Report</a></li>
<li>storybook: <a href="https://output.circle-artifacts.com/output/job/93b95f25-c16c-4116-933c-71c580febd46/artifacts/0/storybook/index.html">Storybook</a></li>
<li>typescript migration: <a href="https://output.circle-artifacts.com/output/job/93b95f25-c16c-4116-933c-71c580febd46/artifacts/0/ts-migration-dashboard/index.html">Dashboard</a></li>
<li><a href="https://circleci.com/gh/MetaMask/metamask-extension/2050362#artifacts/containers/0">all artifacts</a></li>
<li><details>
       <summary>bundle viz:</summary>
       <ul><li>background: <a href="https://output.circle-artifacts.com/output/job/93b95f25-c16c-4116-933c-71c580febd46/artifacts/0/build-artifacts/source-map-explorer/background-0.html">0</a>, <a href="https://output.circle-artifacts.com/output/job/93b95f25-c16c-4116-933c-71c580febd46/artifacts/0/build-artifacts/source-map-explorer/background-1.html">1</a>, <a href="https://output.circle-artifacts.com/output/job/93b95f25-c16c-4116-933c-71c580febd46/artifacts/0/build-artifacts/source-map-explorer/background-2.html">2</a>, <a href="https://output.circle-artifacts.com/output/job/93b95f25-c16c-4116-933c-71c580febd46/artifacts/0/build-artifacts/source-map-explorer/background-3.html">3</a>, <a href="https://output.circle-artifacts.com/output/job/93b95f25-c16c-4116-933c-71c580febd46/artifacts/0/build-artifacts/source-map-explorer/background-4.html">4</a></li><li>common: <a href="https://output.circle-artifacts.com/output/job/93b95f25-c16c-4116-933c-71c580febd46/artifacts/0/build-artifacts/source-map-explorer/common-0.html">0</a>, <a href="https://output.circle-artifacts.com/output/job/93b95f25-c16c-4116-933c-71c580febd46/artifacts/0/build-artifacts/source-map-explorer/common-1.html">1</a>, <a href="https://output.circle-artifacts.com/output/job/93b95f25-c16c-4116-933c-71c580febd46/artifacts/0/build-artifacts/source-map-explorer/common-2.html">2</a>, <a href="https://output.circle-artifacts.com/output/job/93b95f25-c16c-4116-933c-71c580febd46/artifacts/0/build-artifacts/source-map-explorer/common-3.html">3</a>, <a href="https://output.circle-artifacts.com/output/job/93b95f25-c16c-4116-933c-71c580febd46/artifacts/0/build-artifacts/source-map-explorer/common-4.html">4</a>, <a href="https://output.circle-artifacts.com/output/job/93b95f25-c16c-4116-933c-71c580febd46/artifacts/0/build-artifacts/source-map-explorer/common-5.html">5</a>, <a href="https://output.circle-artifacts.com/output/job/93b95f25-c16c-4116-933c-71c580febd46/artifacts/0/build-artifacts/source-map-explorer/common-6.html">6</a>, <a href="https://output.circle-artifacts.com/output/job/93b95f25-c16c-4116-933c-71c580febd46/artifacts/0/build-artifacts/source-map-explorer/common-7.html">7</a></li><li>content-script: <a href="https://output.circle-artifacts.com/output/job/93b95f25-c16c-4116-933c-71c580febd46/artifacts/0/build-artifacts/source-map-explorer/content-script-0.html">0</a></li><li>contentscript: <a href="https://output.circle-artifacts.com/output/job/93b95f25-c16c-4116-933c-71c580febd46/artifacts/0/build-artifacts/source-map-explorer/contentscript.html">contentscript</a></li><li>disable-console: <a href="https://output.circle-artifacts.com/output/job/93b95f25-c16c-4116-933c-71c580febd46/artifacts/0/build-artifacts/source-map-explorer/disable-console.html">disable-console</a></li><li>inpage: <a href="https://output.circle-artifacts.com/output/job/93b95f25-c16c-4116-933c-71c580febd46/artifacts/0/build-artifacts/source-map-explorer/inpage.html">inpage</a></li><li>policy-load: <a href="https://output.circle-artifacts.com/output/job/93b95f25-c16c-4116-933c-71c580febd46/artifacts/0/build-artifacts/source-map-explorer/policy-load.html">policy-load</a></li><li>sentry-install: <a href="https://output.circle-artifacts.com/output/job/93b95f25-c16c-4116-933c-71c580febd46/artifacts/0/build-artifacts/source-map-explorer/sentry-install.html">sentry-install</a></li><li>ui: <a href="https://output.circle-artifacts.com/output/job/93b95f25-c16c-4116-933c-71c580febd46/artifacts/0/build-artifacts/source-map-explorer/ui-0.html">0</a>, <a href="https://output.circle-artifacts.com/output/job/93b95f25-c16c-4116-933c-71c580febd46/artifacts/0/build-artifacts/source-map-explorer/ui-1.html">1</a>, <a href="https://output.circle-artifacts.com/output/job/93b95f25-c16c-4116-933c-71c580febd46/artifacts/0/build-artifacts/source-map-explorer/ui-10.html">10</a>, <a href="https://output.circle-artifacts.com/output/job/93b95f25-c16c-4116-933c-71c580febd46/artifacts/0/build-artifacts/source-map-explorer/ui-11.html">11</a>, <a href="https://output.circle-artifacts.com/output/job/93b95f25-c16c-4116-933c-71c580febd46/artifacts/0/build-artifacts/source-map-explorer/ui-2.html">2</a>, <a href="https://output.circle-artifacts.com/output/job/93b95f25-c16c-4116-933c-71c580febd46/artifacts/0/build-artifacts/source-map-explorer/ui-3.html">3</a>, <a href="https://output.circle-artifacts.com/output/job/93b95f25-c16c-4116-933c-71c580febd46/artifacts/0/build-artifacts/source-map-explorer/ui-4.html">4</a>, <a href="https://output.circle-artifacts.com/output/job/93b95f25-c16c-4116-933c-71c580febd46/artifacts/0/build-artifacts/source-map-explorer/ui-5.html">5</a>, <a href="https://output.circle-artifacts.com/output/job/93b95f25-c16c-4116-933c-71c580febd46/artifacts/0/build-artifacts/source-map-explorer/ui-6.html">6</a>, <a href="https://output.circle-artifacts.com/output/job/93b95f25-c16c-4116-933c-71c580febd46/artifacts/0/build-artifacts/source-map-explorer/ui-7.html">7</a>, <a href="https://output.circle-artifacts.com/output/job/93b95f25-c16c-4116-933c-71c580febd46/artifacts/0/build-artifacts/source-map-explorer/ui-8.html">8</a>, <a href="https://output.circle-artifacts.com/output/job/93b95f25-c16c-4116-933c-71c580febd46/artifacts/0/build-artifacts/source-map-explorer/ui-9.html">9</a></li></ul>
     </details></li></ul></details>

<details><summary>Page Load Metrics (696 ± 291 ms)</summary><table><thead><tr><th>Platform</th><th>Page</th><th>Metric</th><th>Min (ms)</th><th>Max (ms)</th><th>Average (ms)</th><th>StandardDeviation (ms)</th><th>MarginOfError (ms)</th></tr></thead><tbody><tr><td rowspan="4">Chrome</td><td rowspan="4">Home</td><td>firstPaint</td><td align="right">84</td><td align="right">136</td><td align="right">111</td><td align="right">15</td><td align="right">7</td></tr><tr><td>domContentLoaded</td><td align="right">80</td><td align="right">135</td><td align="right">100</td><td align="right">16</td><td align="right">8</td></tr><tr><td>load</td><td align="right">80</td><td align="right">1603</td><td align="right">696</td><td align="right">606</td><td align="right">291</td></tr><tr><td>domInteractive</td><td align="right">80</td><td align="right">135</td><td align="right">100</td><td align="right">16</td><td align="right">8</td></tr></tbody></table></details>

<details><summary>Bundle size diffs</summary><ul><li>background: 0 Bytes (0.00%)</li>
<li>ui: 0 Bytes (0.00%)</li>
<li>common: 0 Bytes (0.00%)</li></ul></details>

**Comment by chloeYue** [comment]
Message from @mikesposito 
Accounts team approval based on testing with [commit](https://github.com/MetaMask/metamask-extension/commit/9787b7eeadfa887900f710a716c2b117c2447fdb) in mac sonoma 14.0.

2 issues reported and are shown in the release regression bug board, unrelated to the 4 changes from the accounts team. One of which I marked as a release blocker: [22119](https://github.com/MetaMask/metamask-extension/issues/22119)

We approve the changes in PRs: [18794](https://github.com/MetaMask/metamask-extension/pull/18794), [21637](https://github.com/MetaMask/metamask-extension/pull/21637), [21715](https://github.com/MetaMask/metamask-extension/pull/21715), [21479](https://github.com/MetaMask/metamask-extension/pull/21479), and [21360](https://github.com/MetaMask/metamask-extension/pull/21360)

**Comment by sleepytanya** [comment]
Confirmations System team approval based on testing with [commit](https://github.com/MetaMask/metamask-extension/commit/9787b7eeadfa887900f710a716c2b117c2447fdb) in mac sonoma 14.0.
✅ Decouple MMI controller from transaction controller internals ([PR#22038](https://github.com/MetaMask/metamask-extension/pull/21748))  
✅ Fix unit test in ConfirmTransactionBase component ([PR#21676](https://github.com/MetaMask/metamask-extension/pull/22038))  
✅ Use core transaction controller ([PR#21166](https://github.com/MetaMask/metamask-extension/pull/21166))

**Comment by seaona** [comment]
:green_circle:  Confirmations UX Team QA Sign Off

**Comment by bowensanders** [comment]
🟢 Snaps Team QA Signs Off ✅

**Pull request merged**
