### PR TITLE
chore: Update `@metamask/accounts-controller` to v5

### PR DESCRIPTION
**Pull request by Gudahtt**
## **Description**

The `@metamask/accounts-controller` package has been updated to v5. This resolves a `peerDependency` warning about the current version of this package (v4) being incompatibile with `@metamask/keyring-controller@9`.

See the changes here: https://github.com/MetaMask/core/blob/fda42694d534e1a49cf97d072178615a63ad732b/packages/accounts-controller/CHANGELOG.md#500

This should result in no functional changes.

## **Related issues**

N/A

## **Manual testing steps**

N/A

## **Screenshots/Recordings**

N/A

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [x] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by Gudahtt** [comment]
@metamaskbot update-policies

**Comment by Gudahtt** [comment]
@SocketSecurity ignore @trufflesuite/bigint-buffer@1.1.10

We trust this author

**Comment by Gudahtt** [comment]
@SocketSecurity ignore fast-xml-parser@4.2.4

Low severity vulnerability that likely doesn't impact how we're using this package.

Also this PR isn't adding this dependency, so this warning should not be appearing

**Comment by Gudahtt** [comment]
Rebased to resolve conflicts

**Review by danjm — APPROVED** [review]

**Review by brad-decker — APPROVED** [review]

**Pull request merged**
