### PR TITLE
 [Fixed] #7921 Message text overflow removed redundant title

### LINKED ISSUE #7921: signTypedData_v4 does not overflow:wrap fields.
Much of the point of `signTypedData` is that its fields are human-readable, and so as a user hoping to approve meta-transactions using this method, I should be able to read the entire field.

This is how it looks today:

Screen Shot 2020-01-28 at 3 34 14 PM

A couple issues:
- [ ] Fields overflow to be unreadable
- [ ] The title `Message` appears twice

### PR DESCRIPTION
**Pull request by BboyAkers**
Fixes: #7921

Explanation: 
Message text overflow removed redundant title

Manual testing steps:  
  -  Connect to metaMask test dapp
  -  Press sign button from SignTypedData_4
 
Result:
  -  Text should warp and redundant message title should only show one message

### CODE REVIEW

**Comment by BboyAkers** [comment]
Took me awhile to figure out the text wrapping but hopefully this suites the fix necessary and doesn't disturb the design. 🙂 

Side note:
I was curious to know if both titles should be there. I saw they both use the same i18n `context` text. So my assumption was that we should delete one after digger further into everything.

**Review by Gudahtt — COMMENTED** [review]
Thanks! This looks like a good start.

I'm still seeing a horizontal scrollbar in some cases though :thinking: Like with the signTypedData_v4 example on the [test dapp](https://metamask.github.io/test-dapp/).

Also, the indentation here is pretty severe. It won't take much nesting to make it _entirely unreadable_ unfortunately. I don't know what to do about that though.

**Comment by Gudahtt** [comment]
See this PR for an earlier attempt at fixing this problem: #9165

Also, regarding the extra "Message" header, this draft PR addresses the same thing: #10406

**Comment by BboyAkers** [comment]
Took awhile lol but there shouldn't be any overflow problems anymore!!! 🙂

**Comment by Gudahtt** [comment]
Thanks, this is definitely an improvement!

The indentation now seems slightly larger though, particularly for the first column. There's a lot of wasted space on the left.

The difference is slight, but when you consider that one level of indentation on `develop` was due to the rendundant `Message` header, the indentation is now _way_ more than it should be. It would be ideal to bring all of this left to leave more room for the message.

<details>
<summary>Screenshots:</summary>

Before (develop):

sign-indent-old

After (this PR):

signed-indent

</details>

**Comment by BboyAkers** [comment]
Gotcha, i'll get to that today and finish up!

**Comment by BboyAkers** [comment]
Sorry for the wait :P. Fixed the padding! 🙂

**Review by Gudahtt — APPROVED** [review]
LGTM!

**Pull request merged**
