### PR TITLE
keep dev Up to date

### PR DESCRIPTION
**Pull request by frankiebee**
version bump

### CODE REVIEW

**Review by kumavis — APPROVED** [review]

**Comment by flyswatter** [comment]
Does this include JSON file import? Seems like we lost a merged feature or at least a change log entry https://github.com/MetaMask/metamask-plugin/pull/1029

**Comment by frankiebee** [comment]
It looks like we just lost the change log entry.

**Comment by kumavis** [comment]
@flyswatter The JSON import is in dev. we did not rollup dev into master, we pushed a hotfix. You can see the changelog entry just above the hotfix log in the diff for this PR

**Comment by flyswatter** [comment]
Ahh.

- Dan

**Pull request merged**
