### PR TITLE
Part of #17670 & #18714: Replace Typography with Text component in token-details-page.js

### PR DESCRIPTION
**Pull request by PrgrmrHarshShukla**
## Explanation
In this PR I have worked on issue #17670 Replace Typography with Text component.
Also I have worked on issue #18714 Replace deprecated design system typography consts with enums in the file:

- **ui\pages\token-details\token-details-page.js**

### After

Screenshot 2023-05-10 at 10 36 55 AM

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Review by pedronfigueiredo — DISMISSED** [review]

**Review by DDDDDanica — DISMISSED** [review]

**Comment by PrgrmrHarshShukla** [comment]
May be I have done something wrong here.

@DDDDDanica , @brad-decker , @pedronfigueiredo ,
Kindly check this.

**Comment by PrgrmrHarshShukla** [comment]
I am using GitHub Desktop, probably I did something wrong while using it to rebase.

@brad-decker , @DDDDDanica ,
Please check.

**Comment by brad-decker** [comment]
@PrgrmrHarshShukla you most likely are rebasing on **your develop branch of your fork**. You need to make sure you're rebasing from origin/develop in github desktop.

**Comment by brad-decker** [comment]
I *thinK* I fixed this one please double check the changes to make sure they reflect your work :)

**Comment by PrgrmrHarshShukla** [comment]
> I _thinK_ I fixed this one please double check the changes to make sure they reflect your work :)

Everything looks good.👍

**Review by georgewrmarshall — COMMENTED** [review]
Hey @PrgrmrHarshShukla, the code looks good. Could you please add some before/after screenshots to ensure there are no visual regressions

**Comment by DDDDDanica** [comment]
@PrgrmrHarshShukla Looks good. If you can attach screenshot to reflect the changes would be great. Then I can approve 🙏

**Comment by brad-decker** [comment]
@PrgrmrHarshShukla the best way to track down these components is to do a global search for the filename in the code base. In this case you should search for '/token-details' because the page is exported from the index of the folder. You then would see its initialized in the routes.js file.

We are happy to help you get your pull requests to a reviewable state, but we do require you to do a little more of the legwork of hunting down these changes and provide screenshots. We are grateful for you pull requests thus far and we hope that with enough guidance you'll have no problem following the pull request template guidelines more and more with each new PR.

**Comment by PrgrmrHarshShukla** [comment]
Hey @brad-decker ,
Will give my best.
100%
Report to you soon.

Regards

**Comment by PrgrmrHarshShukla** [comment]
Hey @brad-decker ,

**I think still there is something I am unable to understand.**


Screenshot (98)


If I am searching for it at the right place to take the screenshots, I am not able to get it here. 
Correct me if I am wrong, probably I need to have some coins in order to get to this page?

Because I can also see this in 
**ui\pages\routes\routes.component.js**
Screenshot (99)

🙏🏼Really sorry for taking a lot of your time.

**Comment by georgewrmarshall** [comment]
Hey @PrgrmrHarshShukla, if there are no storybook files it's a bit tricker to track down where the UI is in the extension. First you have to run the extension locally using `yarn start` then you need to try to hunt down where the UI might be in the application. Here is a video of me doing it for the token details page. I'll admit it's not easy

https://user-images.githubusercontent.com/8112138/237024415-d2728c9e-a587-47d9-8c50-b44227d22ad6.mov

Here is the way to get there using traditional navigation. Please add the before and after screenshots for other reviewers

https://user-images.githubusercontent.com/8112138/237024893-cc505294-f371-4967-9aec-d7247723f76d.mov

**Review by georgewrmarshall — APPROVED** [review]
LGTM
- checked out the branch and viewed locally

**Comment by PrgrmrHarshShukla** [comment]
Hey @georgewrmarshall ,
Thanks a lot for explaining.🙏🏼

I did not have any assets in my wallet.
But I guess, I need to initiate a transaction in order to get the token-details component.

So, I got some assets in my Sepolia test network from 
**`https://sepolia-faucet.com/`**

Is everything OK with that?

In order to get the token-details page I need tokens.
How do I get the "TST" tokens like yours?

Screenshot (100)

**Comment by georgewrmarshall** [comment]
I believe the native asset is not counted as a token so you will need a token in your account. You can create a token contract through the test dapp https://metamask.github.io/test-dapp/ and add it to your wallet

Screenshot 2023-05-10 at 8 14 19 AM

**Review by DDDDDanica — APPROVED** [review]

**Pull request merged**
