### PR TITLE
language tweak on deposit section for wyre

### PR DESCRIPTION
**Pull request by tysonmalchow**
replaced 'credit card' with 'debit card'

### CODE REVIEW

**Comment by whymarrh** [comment]
@tysonmalchow do you mind sharing some context here? Why is this appropriate?

**Comment by tysonmalchow** [comment]
@whymarrh because Wyre does not accept credit cards, only debit cards

**Comment by whymarrh** [comment]
Oh, gotcha! Looking at [Wyre Help Center](https://support.sendwyre.com/en/), that does seem to be the case.

**Review by whymarrh — APPROVED** [review]
Thanks @tysonmalchow!

**Pull request merged**
