### PR TITLE
Only resolve ENS on mainnet

### PR DESCRIPTION
**Pull request by Gudahtt**
The ENS resolver will now bail on any network other than mainnet.

### CODE REVIEW

**Review by whymarrh — APPROVED** [review]
LGTM

**Comment by xmaysonnave** [comment]
Why that? The new registry has been deployed with the same address on mainnet, rinkeby, goerli and ropsten? How are we supposed to test and develop? Thanks for your comments.

**Comment by xmaysonnave** [comment]
https://twitter.com/nicksdjohnson/status/1222700254115463170?s=09

**Comment by Gudahtt** [comment]
This is just for the ENS resolver that acts on addresses in the browser address bar; there were usability concerns with resolving testnet addresses there, as the user might not know what the current network is.

ENS resolution for the input fields will still work on mainnet and Ropsten (as it had before), and support for the other testnets is in `develop` already and will be included in a future release.

**Comment by xmaysonnave** [comment]
As far as I know MetaMask is the only tool in the browser who gives the flexibility to resolve wherever ENS is deployed and supported. This is a great plus. 
IMHO, I see this PR as a regression as it has financial and organisational impact.

**Comment by Gudahtt** [comment]
I would appreciate it if you could explain why testnet ENS resolution in the browser address bar in particular is a useful feature for you, or why you think it could be useful for others (maybe in a new issue? That would be preferred). I had assumed people mainly used testnets for testing, and I can't see how this feature would be essential for testing (since all we did is redirect to `https://app.ens.domains/name/[address]`, and you could navigate there yourself).

Personally I'm open to considering adding this feature back, but only if we can find some way to mitigate the usability concern (e.g. ensure the user knows they're resolving testnet addresses). Maybe on an opt-in basis as well, as most users wouldn't benefit from this feature. But only if there's a case to be made for this being useful for users in the first place.

**Comment by xmaysonnave** [comment]
Thanks for your comments.
1 - Right now our users always use the same url to reach our dapps.
https://bluelightav.eth resolves either on mainnet and/or rinkeby.
The difference is the production version or the dev/test version, frontend and smart contracts.
I see this as an improvement over the tradionnal dns approach with a dot beta or dev URL prefix.
Question: What about Metamask set to Rinkeby while .eth is resolved on Mainnet ?
2 - The fact that a browser user input URL resolves on Mainnet, Ropsten, Rinkeby or Goerli (deployed ENS registries) doesn't prevent users to understand what Metamask is doing. However  .eth are resolved even a user didn't log with Metamask. In other word a user could use the .eth resolver without any relationship with the Ethereum/Smart Contract, etc...You are right to say that it could be seen as a user confusion/inconvenience.
3 - In the current situation Metamask takes the hand and the landing page is the ipfs url content.
For instance https://app.ens.domains/name/bluelightav.eth redirects to the app and not the content (7.7.3 behaviour, I didn't test the 7.7.4 yet.).
4 - In the current landscape AFAIK Metamask is the only one who provides this flexibility. Opera only resolves on Mainnet even you switch the integrated wallet to the Rinkeby network. I see that as a real plus. We could also imagine that when .eth will be an official resolved TLD. Major browsers will only resolve on Mainet. I see this point as a Metamask strength.
6 - if this PR is maintained and if I understand well we need to educate usesr to use this kind of URL https://app.ens.domains/name/bluelightav.eth, not very convenient and as seen in the past this kind of URL could change.... 
Warmly

**Comment by Gudahtt** [comment]
@xmaysonnave I can see why you value this feature. I'm considering now how we could accomplish this in a safe way.

Would it meet your requirements if we added back testnet ENS resolution, but moved to a warning page first to confirm the user understands what network they're on?

**Comment by xmaysonnave** [comment]
@gudhatt I was thinking about your proposal. 
In the current situation when a user input an eth domain there is a temporary page who's blinking with the ENS logo. If a user install Metamask and do not setup any account the eth redirection is functional and takes the default Ethereum network. If a user setup an account he starts his Metamask/Ethereum learning curve and I hope that he is aware of the different networks available. Anyway the default is Mainnet. I see two different use cases here. If a user select Ropsten for instance I really hopes that he is aware that is going to transact with Ropsten The same reasoning applies to the ENS resolution. If a user select Ropsten and he is confused to resolve against Ropsten it sounds like a user confusion. 
I see three ways: 
1 - An extra confirmation dialog as you suggest. This suggestion implies an user interaction.
2 - A specialized color per network or the traditional yellow warning color on the temporary page could be a user free interaction.
3 - Metamask on Android is less confusing as the current selected network is displayed. I have no idea if this behavior could be implemented on desktop browsers.
Thanks

**Comment by xmaysonnave** [comment]
@gudhatt 
Any progress on your side ?
You suggested to open an enhancement request.
It will be easier to contributors to comment.
Thanks

**Comment by marsrobertson** [comment]
FYI, the existing error message is misleading: https://ethereum.stackexchange.com/questions/82780/ens-on-rinkeby-network-does-not-support-ens/82804

image

**Comment by xmaysonnave** [comment]
Thanks for this input. 
I never experienced this message. 
Several issues here: 
1 - As specified in the ENS doc, https://docs.ens.domains/ens-deployments, rinkeby is supported however since the recent update the rinkeby registry is not fully upgraded:
ksnip_20200426-164547
2 - Here is the confirmation:
ksnip_20200426-164943
3 - However since then I sent a DM to solve this issue:
ksnip_20200426-165214
No answers, quite frustrating.
4 - In the meantime
ksnip_20200426-170007
my Dapp is still able to resolve against Rinkeby but I'm unable to update the content hash.
Hope that you understand the situation with ENS.
5 - I don't use rinkey and I switched to ropsten who is fully functional.
6 - Metamask Mobile on Android is still able to resolve (Mainnet, ropsten, etc...)
7 - Metamask desktop is not able to resolve
ksnip_20200426-170559
7 - No comment from the Metamask team since the 6 March.

**Comment by marsrobertson** [comment]
### Regardless Rinkeby, error message should be better

image

I'm on the mainnet already. It's the resolver that is not configured. On the other hand, no need to overcomplicate with technical details.

It just feels weird "switch to mainnet if already on the mainnet"

**Comment by xmaysonnave** [comment]
@marsrobertson Your report is not related to the current issue. I suggest to open a new request. I'm talking here the way Metamask is behaving when a user input a .eth adress in the browser address bar not in the Metamask browser extension itself.
Thanks

**Comment by rsodre** [comment]
> @Gudahtt: I would appreciate it if you could explain why testnet ENS resolution in the browser address bar in particular is a useful feature for you, or why you think it could be useful for others (maybe in a new issue? That would be preferred). 

I'm building an application that relies on ENS records and deploys static clients using ENC content hash. Opening an ens address from the url is important for us. That's THE thing we're doing, and we can't test it on a testnet.

I don't mind a confirmation before opening the content.
Or add some settings to enable it, if MetaMask still believes this is a security risk.

**Pull request merged**
