### PR TITLE
Network indicator modifications

### PR DESCRIPTION
**Pull request by 2-am-zzz**
Made the network indicator a bit more modular so it can be more easily used in other parts of the app, as well as added a network indicator in the tx confirmation. Solves #924.

Shows up in the notification.
screenshot from 2017-01-04 15-10-11

Hides itself in the popup.
screenshot from 2017-01-04 15-10-22

### CODE REVIEW

**Comment by flyswatter** [comment]
I wonder if there's a nicer place we could put the indicator on the `CONFIRMATION` screen.  I like the title being centered.

@VladTod?

**Comment by flyswatter** [comment]
It works as a menu here?

**Comment by VladTod** [comment]
Title is quite long, so having both of them there is not really an option ( unless we do as bellow )
confirm2

This can be another version, if we move the indicator.
confscreen

My problem is that i don't see any Metamask logo on this screen. We can's use the entire header in this screen right?

**Comment by flyswatter** [comment]
I like that first option.

Yeah having the full header is probably overkill, and could be confusing because the user could click the switch user screen which may make them lose track of the transaction.

It would be better if clicking the sender here was a menu of the user's accounts.

- Dan

**Comment by Zanibas** [comment]
This okay?
screenshot from 2017-01-05 08-31-34

**Comment by flyswatter** [comment]
@Zanibas I really prefer Vlad's first option, as long as there's room for the network menu below it (that widget isn't scrollable yet).

**Comment by flyswatter** [comment]
I'm sorry I meant his second option.  In my mail I think it showed up in a weird order, like I thought they were different messages and in reverse :P

**Comment by VladTod** [comment]
Thats my bad, i first used the images the other way around, and edited after :) but i think the email got there with the unedited version :)

**Review by danfinlay — APPROVED** [review]
Agreed to keep network status in the menu bar for now, because of some CSS complications, we can revisit it later, or just rewrite the UI ;)

**Comment by wighawag** [comment]
Showing the network on the transaction popup would indeed be great for users as mentioned here https://github.com/MetaMask/metamask-plugin/issues/924

We could also have a different icon than the fox in the chrome top bar to show that this is not the mainnet

**Comment by flyswatter** [comment]
I've been having a similar thought about the bar icon! There are some interesting uses for it.

- Dan

**Pull request merged**
