### PR TITLE
Add clarifying text to the "Add Token" button

### LINKED ISSUE #5497: Improve "Add Token" button
Most common support query week over week is folks not seeing certain tokens on their wallet. Especially since we auto-detect a lot of tokens, people get confused when lesser known ones don't appear automagically.

We should improve the "Add Token" button to say something more descriptive, like:

> Don't see your tokens? Click here to add them to this wallet.

Hopefully this will be mitigated by EIP 747 going forward, but for now it's a painpoint that is easily addressable.

### PR DESCRIPTION
**Pull request by whymarrh**
Fixes #5497

This PR adds clarifying text below the "Add Token" button in the sidebar. As outlined in #5497, this will hopefully be mitigated by EIP 747 going forward.

**Extension view screenshot**

<details>
<summary><strong>Wallet view screenshot</strong></summary>

</details>

### CODE REVIEW

**Comment by whymarrh** [comment]
@cjeria do you think this is fine for now? Or do you have thoughts about a better place for this? I didn't want to add the text to the button directly.

**Comment by cjeria** [comment]
@whymarrh placement makes sense. I think the font size and color can be pushed back a bit and could be a bit more subtle. Here's what I'm thinking. Let me know what ya think. cc @bdresser 

image

**Comment by bdresser** [comment]
looks great @cjeria thank you!! 

and thx for fixing @whymarrh, support team will be stoked :)

**Comment by whymarrh** [comment]
Thanks @cjeria, I'll update this

**Comment by whymarrh** [comment]
@cjeria updated! I've updated the screenshot in the OP. I don't think bolding "add tokens" is worth the effort (the way we handle translations doesn't currently support inline styling) so I've left that out.

**Comment by cjeria** [comment]
@whymarrh looks good!

**Review by bdresser — APPROVED** [review]

**Pull request merged**
