### PR TITLE
Doc fixes

### PR DESCRIPTION
**Pull request by PurpleParrot007**
Explanation:  Removed a new line character from README.md

### CODE REVIEW

**Comment by PurpleParrot007** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by darkwing — COMMENTED** [review]
Hello @PurpleParrot007 -- it looks as though some other changes made it too this pull request.  Please rebase for consideration!  Thank you!

**Review by darkwing — CHANGES_REQUESTED** [review]
Hello @PurpleParrot007 -- it looks as though some other changes made it too this pull request.  Please rebase for consideration!  Thank you!

**Comment by darkwing** [comment]
On second look, this isn't a change that pushes the README forward.  Closing.

**Pull request closed without merging**
