### PR TITLE
Storybook: Signature Request

### PR DESCRIPTION
**Pull request by kumavis**

### CODE REVIEW

**Comment by kumavis** [comment]
benchmark fails :crying_cat_face:

**Comment by kumavis** [comment]
this is it ------------> https://242891-42009758-gh.circle-artifacts.com/0/storybook/index.html?path=/story/signature-request--first-look

**Comment by kumavis** [comment]
network selector looks a little derpy, not sure why

**Comment by brad-decker** [comment]
For some reason the header is 85px tall when the header in the real app is only 58px. The side effect of the smaller height is that things just align the right way. When the height of the header is manually adjusted to 85px in the real app view, then the styling looks as it does in storybook.

adding `display: flex, align-items: center` to `--network` the same way it is added to `--account` is an appropriate fix for the alignment issue ... but still not quite sure why storybook renders the view with extra height on the header.

**Comment by kumavis** [comment]
is the repeated `Message` label a bug in the confirmation or the story

**Comment by kumavis** [comment]
reproduced on https://metamask.github.io/test-dapp/
image

**Comment by kumavis** [comment]
issue is present on  Sign Typed Data V3 +  Sign Typed Data V4

**Comment by kumavis** [comment]
@brad-decker seems like a mistake, including the same label twice https://github.com/MetaMask/metamask-extension/blob/b93046bdabc8e0107fc40d30b51b31095240798e/ui/app/components/app/signature-request/signature-request-message/signature-request-message.component.js#L47-L51

**Comment by kumavis** [comment]
with updated styles for header https://242965-42009758-gh.circle-artifacts.com/0/storybook/index.html?path=/story/signature-request--first-look

**Comment by kumavis** [comment]
this is good to go, above issue is out of scope

**Comment by Gudahtt** [comment]
The double-message-label problem is captured in #10124

**Review by brad-decker — APPROVED** [review]

**Pull request merged**
