### PR TITLE
Redesign proposal

### PR DESCRIPTION
**Pull request by denull0**
Hello guys,
I've spent few days rethinking the UI/UX aspect of Metamask. I believe most of the UI can be cleared through dropdown menus and text instead of confusing icons. Have a look and let me know what you think. On top of that spent sometimes working on a new brand that has a more serious vibe, i tried to keep some of the legacy from the fox by using a polygon for a base and play around with your two Ms. 

The UX and UI is not completely finished so please drop me feedback. My initial idea was to simply and make Metamask look more serious than its current state. Also make the UI language more neutral so more html desktop apps can embed it into their products.

### CODE REVIEW

**Comment by flyswatter** [comment]
Hi @dimoFeeld this is so cool, thanks for caring enough to contribute this time to MetaMask!

We'll go over this as a team early this week, there are lots of details here, so I'm sure there are some lessons we can draw.

We actually have been working on an internal redesign for a while, and while it isn't throwing away the logo, it is getting *a bit* more serious, so maybe we could run you through it and get your feedback there, too.

Again, thanks a lot! Will talk more soon!

**Comment by dimoFeeld** [comment]
I just added an animated version of the logo. Also tweaked he designs slightly. Hope you enjoy

**Comment by flyswatter** [comment]
For the lazy, here is the photo document:
https://github.com/dimoFeeld/metamask-plugin/blob/fd3e1a4e8347d201ce2055dd8c2479cdf3e307ca/ui/design/redesign/redesign%20source-boards.md

The animated logo is here:
animated logo

**Comment by flyswatter** [comment]
That animation is very cool. Obviously a full rebrand is a big conversation, but there are some things I like here.

I especially like the account detail drop-down for the QR/account export icons, I agree those are a source of confusion for people.

**Comment by kumavis** [comment]
@dimoFeeld are you in our slack? there is a new public design channel you're welcome to join `#design`

**Comment by Zanibas** [comment]
Closing as the discussion has now progressed into a different form!

**Pull request closed without merging**
