### PR TITLE
Prevent batch request from opening multiple windows

### LINKED ISSUE #1666: Batched eth_sendTransaction opens multiple popups
As reported on [this stackexchange post](https://ethereum.stackexchange.com/questions/18660/batch-transactions-for-metamask-using-sendasync), I've confirmed that [using the batch api](https://github.com/ethereum/wiki/wiki/JavaScript-API#batch-requests) to send multiple transaction signing requests opens many metamask windows.

Should be a simple fix.

### PR DESCRIPTION
**Pull request by trigun0x2**
There seems to an issue with the "popup" naming convention within the repo.
Currently, the chrome popup (plugin at the top right) and the notification popup (the issue I'm fixing) are both called "popup" in many different cases.

This creates confusion within the `notification-manager.js`. I've traced a route though `popup.js` to show the issue.

With regards to the main fix. It has been fixed but I have introduced a new bug (feature?) where all notification popups are closed when the chrome popup is opened. This isn't disastrous in anyway, but may not the intended flow for the extension.

There's two options:
1. Leave it as it is
2. Rework the naming convention and change how `notification-manager.js` checks for chrome popups vs notifcation popups

Please advise. I also would love it if someone else can test this version in their respective browser. I've tested on Chrome in Linux/macOS.

Fix #1666

### CODE REVIEW

**Comment by kumavis** [comment]
> all notification popups are closed when the chrome popup is opened. 

@trigun0x2  This was a feature added a while back, but must have broke at some point. I'm not sure how it behaves with the new ui full screen mode, we don't want those fullscreen windows to close.

**Comment by kumavis** [comment]
@trigun0x2 looks like there are some lint issues `npm run lint`

**Comment by trigun0x2** [comment]
@kumavis I fixed the lint issue (along with a lot of other whitespace issues).
If you're talking about the new fullscreen tab in the new ui, this "feature" won't close that.
Opening the Chrome popup will only close the notification popup.

I would still love for someone else to test this PR, but it works perfectly for me.

**Comment by kumavis** [comment]
@trigun0x2 merge master and we're ready to go (i'll close the other one)

**Comment by trigun0x2** [comment]
@kumavis I can't seem to reproduce anything after I reloaded the newest build. Hopefully it was an old build problem.

**Comment by kmewhort** [comment]
This issue has re-surfaced with the new UI.

**Pull request merged**
