### PR TITLE
Allow ENS Names in Send Form

### LINKED ISSUE #1130: Enable sending to ENS addresses
On testnet and mainnet, the `send` form should allow entering an ENS name for the recipient.

As this name is entered, a query should be debounced and issued, displaying the resolved address under the input field.

### PR DESCRIPTION
**Pull request by danfinlay**
I know we're going to deprecate the send form hopefully soon, but the plumbing will still be useful.

I've modified our normal `input` component to be an `ens-input` component, which is aware when its contents match the `*.ens` format, and indicates if the name resolves to anything on the current network.

If it does, it gives a little icon that you can click to copy.  Maybe it should be a link to a blockchain explorer, I'm open to thoughts from @VladTod and @eshon.

Here's what I've got so far:
ens-input

To create this, I made my own ENS resolving modules, published publicly on npm:
- [eth-ens-namehash](https://www.npmjs.com/package/eth-ens-namehash)
- [ethjs-ens](https://www.npmjs.com/package/ethjs-ens)

Fixes #1130

### CODE REVIEW

**Comment by Zanibas** [comment]
This UI of clicking and copying and pasting the address feels cumbersome--can't we just replace the address in the input bar after a small timeout period?

**Comment by flyswatter** [comment]
You aren't required to copy & paste the address, I was just demontrating that it works.  You can hit `send` with only a valid `ENS` name entered. Try it!

**Comment by Zanibas** [comment]
Ideally, we integrate this also into our tx-list as well--showing the eth nickname rather than the raw address.

**Comment by flyswatter** [comment]
That is part of the reverse-lookup feature in #1131.  This one is just about sending to ENS names.

**Review by 2-am-zzz — APPROVED** [review]

**Pull request merged**
