### PR TITLE
remove superfulous fonts

### PR DESCRIPTION
**Pull request by brad-decker**
1. Removes Montserrat and variations
2. Removes Lato and variations
3. Removes "DIN OT" and "DIN NEXT" and variations
4. Removes unnecessary special font loading based on unicode characters (see [Mozilla unicode-range](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/unicode-range#:~:text=The%20unicode%2Drange%20CSS%20descriptor,the%20whole%20font%20is%20downloaded.) and [Googles example of roboto usage](https://fonts.googleapis.com/css?family=Roboto:300,500). Note in the example that google loads different font files for different ranges of unicode characters)
5. Switches the few places where any of the above extra fonts were specified to use Roboto instead. ~This will likely result in slight changes to styling.~, nope both classes that were modified are no longer used... <_<

### CODE REVIEW

**Review by whymarrh — APPROVED** [review]
Seems legit! Good catch! 👏🏽

**Review by Gudahtt — APPROVED** [review]
LGTM! I can't find any remaining references to these deleted fonts.

**Comment by brad-decker** [comment]
Sorry for the early merge, but glad it worked out lol @Gudahtt

**Comment by brad-decker** [comment]
[Update fonts](https://trello.com/c/giqTMDWN/59-update-fonts)

**Pull request merged**
