### PR TITLE
Change default to mainnet

### LINKED ISSUE #1203: Switch the default network to main-net
it's time to switch the default network

### PR DESCRIPTION
**Pull request by frankiebee**
fixes #1203 
Swithch the default network to mainnet

### CODE REVIEW

**Review by kumavis — APPROVED** [review]

**Comment by kumavis** [comment]
im pretty sure we're ready to merge this but want to hear from kevin and dan again

**Comment by flyswatter** [comment]
In our last meeting, we made it sound like we didn't want to do this until we'd hit some core security measures.  I'm sorry I didn't capture what they were.

Also, Gnosis says they're fixing Ropsten by simply mining on it, which could work, so maybe just adding more testnets is more important than changing the default?

**Comment by Zanibas** [comment]
Can we close this issue for now? If we're in agreement that we're still in beta, changing default to main net is going to still be a ways off.

**Comment by flyswatter** [comment]
Yeah, we can reopen this PR when we're ready to do it.

**Pull request merged**
