### PR TITLE
fix e2e tests

### PR DESCRIPTION
**Pull request by scsaba**

### CODE REVIEW

**Comment by scsaba** [comment]
Hello @danfinlay @kumavis 

I noticed that your e2e and screen tests were failing, so I spent a few days to figure out a workaround to bring them to life.

The solution is not the nicest, but I found no other way to get the development time extension id - without changing the manifest.json. This change has much lower risk as it cannot ruin the release package.

**Comment by danfinlay** [comment]
Oh very nice, this may fix the test failure in #4199. We'll review this today.

**Comment by scsaba** [comment]
Meanwhile I could come up with a simpler solution. I will update the pull request in a few hours.

**Comment by danfinlay** [comment]
Thanks so much for this contribution.

It turns out some other team members were working on the same issue, and have fixed it similarly in PR #4226, so I'm closing this for now, since it appears to be redundant.

Thank you so much for jumping in and doing this, though!

**Pull request closed without merging**
