### PR TITLE
fix: where text wraps even though there is enough space to display it.

### PR DESCRIPTION
**Pull request by siosio34**
## Explanation

Line breaks in certain menus even though there is plenty of room for text.

If you do not apply the relevant information for any other reason, you can close the pull request.

Thank you for always making great products.

### Before
image

### After
image

## Pre-merge author checklist

- [X] I've clearly explained:
  - [X] What problem this PR is solving
  - [X] How this problem was solved
  - [X] How reviewers can test my changes
- [X] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Comment by siosio34** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by brad-decker — APPROVED** [review]
LGTM. Thanks for your contribution!

**Review by pedronfigueiredo — APPROVED** [review]

**Review by NidhiKJha — APPROVED** [review]

**Review by DDDDDanica — APPROVED** [review]

**Comment by siosio34** [comment]
Is there anything I need to do additionally to get this code merged? @brad-decker

**Comment by NidhiKJha** [comment]
> hello. I wonder if you forgot to merge this fix? Or if there is any additional work I need to do for this code to be merged, I would appreciate it if you could let me know.
> 
Hey @siosio34 we need to wait for the CI checks to pass, once all the checks are green, we will merge this PR. I will look into it today if the tests won't pass for this build

**Pull request merged**
