### PR TITLE
chore: Revert "fix: needs to be always true for MMI (#24163)"

### PR DESCRIPTION
**Pull request by legobeat**
## **Description**

#24163 seems to have been introduced a regression resulting in failing MMI-related jobs.

https://github.com/MetaMask/metamask-extension/pull/24163#discussion_r1575435070

This reverts it.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/24185?quickstart=1)

## **Related issues**

- #24163

## **Manual testing steps**

n/a

### **Before**

n/a

### **After**

n/a

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by kumavis — APPROVED** [review]

**Review by albertolive — APPROVED** [review]

**Comment by zone-live** [comment]
I don't think this needs to be reverted. Develop has not had any fail in CI because of this, and at the time this PR was merged, the pipeline was up to data with develop and green.

Last two runs in develop:
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/77524/workflows/2b0e96b2-bb3e-49ce-b1ed-cf944fb6a7d1
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/77515/workflows/d9a86e46-b934-42d5-8fd3-d9f2fcf3ddfc

**Review by zone-live — CHANGES_REQUESTED** [review]
The cause for the fails you mention in this [PR](https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/77560/workflows/55c88953-5cd1-4a58-a3e1-9d12ad543460) might be because its not up to date with develop. I'll check 👍🏼 

by the time this one was merged, all was green: https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/77481/workflows/528e4a54-b5e3-463a-9373-b12b078e6fb7
Also other [PRs open](https://github.com/MetaMask/metamask-extension/pull/24175) right now against develop don't have any issue with our build

**Comment by zone-live** [comment]
> > The cause for the fails you mention in this [PR](https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/77560/workflows/55c88953-5cd1-4a58-a3e1-9d12ad543460) might be because its not up to date with develop. I'll check 👍🏼
> > by the time this one was merged, all was green: https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/77481/workflows/528e4a54-b5e3-463a-9373-b12b078e6fb7 Also other [PRs open](https://github.com/MetaMask/metamask-extension/pull/24175) right now against develop don't have any issue with our build
> 
> Example failure; up to date with `develop`: #23216

This is happening only to forked repos, how can we make sure they have the last develop up to date? why is it not happening in PRs from the main codebase?
Also if this PR gets reverted it will add back unnecessary code. It's preferable if I just create a PR do add back the variable to builds.yml.

**Comment by zone-live** [comment]
for visibility here as well: https://github.com/MetaMask/metamask-extension/pull/24192
cc @legobeat

**Pull request closed without merging**
