### PR TITLE
Prevent user from getting stuck on opt in page

### LINKED ISSUE #9800: Stuck on MetaMetrics Opt-In page if metrics call fails
**Describe the bug**
During onboarding, opting in or out of metrics will send us an anonymized metric event. If this HTTP call fails, the user is stuck on this screen, unable to proceed.

**Steps to reproduce (REQUIRED)**

1. Install MetaMask
2. On the onboarding page, open dev tools and block requests to `api.segment.io`
3. Proceed through onboarding to the MetaMetrics page
4. Attempt to opt-in to metrics

**Expected behavior**
The user should be able to proceed despite the failure to send the metric event.

**Browser details (please complete the following information):**
 - OS: Linux
 - Browser: Firefox 82.0 (64-bit)
 - MetaMask Version: `develop`

**Additional context (Error Messages, etc.)**
When testing this locally, it looks like I remained stuck no matter how many times I tried to opt in. But if I opt out, only the first click fails. Clicking opt out multiple times did let me proceed eventually.

### PR DESCRIPTION
**Pull request by Gudahtt**
Fixes: #9800

Explanation: 

Failed metric events on the opt-in page no longer leave the user stuck on that page. If the metric events fail, they still bubble up as errors to be caught by Sentry and logged to the console, but the user is still brought to the next page.

Manual testing steps:  
  - Build MetaMask with a fake entries for SEGMENT_HOST, SEGMENT_WRITE_KEY, and SEGMENT_LEGACY_WRITE_KEY. For example, in `.metamaskrc`:
```
SEGMENT_HOST=https://fake-segment-api.metamask.io
SEGMENT_LEGACY_WRITE_KEY=FOO
SEGMENT_WRITE_KEY=bar
```
  - Install that MetaMask build
  - Proceed through onboarding to the Opt-In page (in either import or create flow)
  - The metrics events should always fail, yet selecting Opt-In or Opt-Out on either flow should still succeed.

### CODE REVIEW

**Comment by tmashuang** [comment]
After testing this out, the user no longer gets stuck on the Opt In Screen, but if the user agrees to opt in, and the segment api is failing, all metrics events will error with `Error: Network Error` and be logged to sentry. Could we not opt them in if it fails?

I am fine with this as is.

**Comment by Gudahtt** [comment]
Interesting point :thinking: 

I would rather record their consent even if we don't end up sending metrics due to network failures. It could be a temporary failure after all, like a network interruption.

I'll open a separate ticket for better handling of failed metrics. We should probably retry with an exponential backoff, then give up.

**Review by tmashuang — APPROVED** [review]
LGTM

**Review by rekmarks — APPROVED** [review]
LGTM!

**Pull request merged**
