### PR TITLE
Fix FF overflow list-item right-content/primaryCurrency wrapper

### PR DESCRIPTION
**Pull request by tmashuang**
Primarily fix for Firefox primaryCurrency going out of bounds of the grid template.

<details>
<summary>Out of bounds</summary>

</details>

<details>
<summary>Before</summary>

</details>

<details>
<summary>After</summary>

</details>

EDIT: AFTER screenshots in a later comment of fix.

### CODE REVIEW

**Comment by Gudahtt** [comment]
Huh. Strange. This definitely fixes it, but I have no idea why this is happening in the first place :thinking:

**Review by brad-decker — DISMISSED** [review]
Instead, lets add `overflow: hidden; white-space: nowrap; ` to the `.list-item__right-content` -- in firefox the overflow: hidden on the h2 doesn't take. Instead of setting an arbitrary max-width we can add these two styles and allow the h2 to control the ellipsis to get the effect we want.

**Comment by brad-decker** [comment]
<details>
<summary>Details</summary>



</details>

**Comment by tmashuang** [comment]
@brad-decker Doesn't that change remove the suffix value from the new line? That probably wasn't intended, but made it easier to see the value. Would it require splitting up the `primaryCurrency` value and the suffix along with your changes?

**Comment by brad-decker** [comment]
We don't want the suffix to overflow. That breaks alignment. I'd rather us use ellipses in the middle of a long number to keep the suffix but that can be complex for now we should hide the suffix on long values per the last PR feedback from @rachelcope

**Comment by tmashuang** [comment]
<details>
<summary>Updated Screenshot of long swap value</summary>

</details>

<details>
<summary>Updated Screenshot of long eth value</summary>

</details>

**Comment by rachelcope** [comment]
So in the future we'd ellipse the number and keep the suffix (e.g, 1.234... ETH)? But for now ellipse the entire string. (e.g, 1.234 E...)? I'd prefer to keep the suffix for comprehensibility, but this seems like a good intermediate solution until then

**Comment by Gudahtt** [comment]
Keeping the suffix is challenging because it can be pretty long - up to 12 characters currently, potentially longer if we raise the maximum token symbol length. It could be too wide to fit in this space on its own. Certainly a problem we can solve another day.

**Review by Gudahtt — APPROVED** [review]
LGTM!

**Pull request merged**
