### PR TITLE
feat: Bump eth-keyring-controller to v13.0.0

### PR DESCRIPTION
**Pull request by gantunesr**
## Explanation

This PR updates the `eth-keyring-controller` module from `10.0.1` to `13.0.0`.
## Screenshots/Screencaps

No changes to the UI

## Manual Testing Steps

User flows related to,

- [ ] Lock and unlock wallet
- [ ] Reset wallet
- [ ] Create new wallet
- [ ] Recover wallet with SRP
- [ ] Import private key
- [ ] Hardware wallet connection and disconnection
- [ ] Connect wallet connection and send a transaction
  - [ ] Ledger
  - [ ] QR based
  - [ ] Trezor
  - [ ] Lattice - Grid+
- [ ] Reveal private and SRP

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [x] How reviewers can test my changes
- [x] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [x] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Review by legobeat — DISMISSED** [review]

**Review by montelaidev — DISMISSED** [review]

**Comment by plasmacorral** [comment]
Tested Lattice hardware v2 with firmware 0.17.1 on mac ventura 13.4 with no issues.

- Bind Lattice to Firefox 114
- Send from Lattice using Firefox on mainnet
- Remove MetaMask permissions on Lattice
- Bind Lattice to Chrome 114
- Receive to Lattice using Chrome on Sepolia
- Send from Lattice using Chrome on Sepolia
- Reject proposed tx at Lattice using Chrome on Sepolia

https://sepolia.etherscan.io/address/0xc2fe0024518d8d115eac317798e3a3fc11bb2f6f
https://etherscan.io/address/0xc2fe0024518d8d115eac317798e3a3fc11bb2f6f

**Comment by gantunesr** [comment]
@metamaskbot update-policies

**Comment by gantunesr** [comment]
@metamaskbot update-policies

**Comment by gantunesr** [comment]
@metamaskbot update-policies

**Comment by gantunesr** [comment]
Hey @legobeat, I'll sync with the Shared Libraries team to bump to the latest version

**Comment by Ehsan129** [comment]
1299820

در تاریخ جمعه ۷ ژوئیه ۲۰۲۳،‏ ۱۱:۴۵ legobeat ***@***.***> نوشت:

**Comment by Ehsan129** [comment]
1299820

در تاریخ جمعه ۲۸ ژوئیه ۲۰۲۳،‏ ۰۲:۴۷ Ehsan Abdali ***@***.***>
نوشت:

**Comment by gantunesr** [comment]
@legobeat do you know how to solve this issue with lavamoat?

`Error: LavaMoat - required node builtin package not in allowlist: package "fast-glob>micromatch" requested "util" as "util"`

**Comment by gantunesr** [comment]
@legobeat is this failure related to the audit fail?

**Comment by gantunesr** [comment]
@legobeat is this failure related to the audit error?

https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/52967/workflows/301a7079-4a96-4913-be51-482eb5294d54/jobs/1551934

**Comment by gantunesr** [comment]
The script `.circleci/scripts/check-working-tree.sh` runs without errors on my end @legobeat, just some warnings

**Comment by gantunesr** [comment]
@legobeat thanks for the instructions. In both case the `git diff` output was empty

**Pull request closed without merging**
