### PR TITLE
Refactor token list

### PR DESCRIPTION
**Pull request by Gudahtt**
Refactor token-list to split it into container and component modules, according to our usual conventions. The component is now in its own directory, and it uses the new React Context AP. Additionally, a few updates have been made to simplify the component logic.

### CODE REVIEW

**Comment by Gudahtt** [comment]
This could have been three separate PRs, but I left them as three separate commits instead as they were directly dependent upon each-other. Reviewing the commits one-by-one might be easier.

**Comment by Gudahtt** [comment]
I've updated this PR to remove the commit where the component was converted to use React Hooks - I'll submit that as a separate PR at a later date.

**Review by whymarrh — DISMISSED** [review]
LGTM!

**Comment by Gudahtt** [comment]
I had to update this to resolve a conflict (the addition of the `onTokenClick` prop)

**Review by whymarrh — APPROVED** [review]
LGTM!

**Pull request merged**
