### PR TITLE
Part of #17670: Replace Typography with Text component in confirm-page-container-content and experimental-tab

### PR DESCRIPTION
**Pull request by PrgrmrHarshShukla**
## Explanation
In this PR, I have worked on issue #17670 Replace Typography with Text component and issue #18714 Replace deprecated design system typography consts with enums in the files:
**ui\pages\settings\experimental-tab\experimental-tab.component.js**

Also I have worked on issue #17670 Replace Typography with Text component for files:
**ui\components\app\confirm-page-container\confirm-page-container-content\confirm-page-container-content.component.js**

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

### CODE REVIEW

**Review by DDDDDanica — DISMISSED** [review]

**Comment by DDDDDanica** [comment]
@PrgrmrHarshShukla looks good to me. If you can update snapshot for changed DOM classname then the pipeline should be ready

**Comment by PrgrmrHarshShukla** [comment]
Sure @DDDDDanica ,
Will report to you soon.

**Review by georgewrmarshall — COMMENTED** [review]
Hey @PrgrmrHarshShukla, could you please update snapshots and add some before/after screenshots, thanks!

**Comment by georgewrmarshall** [comment]
Just need some Before/After screenshots to ensure there are no visual regressions and we can merge!

**Comment by PrgrmrHarshShukla** [comment]
Hey @georgewrmarshall ,

Same problem, not able to find this in the UI.
I am trying to add screenshots by creating a story for the component as you mentioned in #18831

**Comment by georgewrmarshall** [comment]
Hey @PrgrmrHarshShukla, just wanted to check in. It looks like this PR is almost there. Did you still want to work on it? If so, that's great! Let us know if you need any assistance or if there are any blockers. If you're unable to continue working on it or haven't had a chance to address it, no worries! I can take it from here and carry it forward. Cheers!

**Comment by georgewrmarshall** [comment]
Hey @PrgrmrHarshShukla, thanks for all your effort with this PR I am going to close it as it has become stale. Please feel free to open another PR in future. Thanks for your contributions thus far!

**Pull request closed without merging**
