### PR TITLE
Fixing yarn version command, adding yarn version plugin

### PR DESCRIPTION
**Pull request by ryanml**
## Explanation
Fix for generating the new release version, re-adding yarn version plugin which was removed in v3

### CODE REVIEW

**Review by danjm — DISMISSED** [review]

**Comment by Gudahtt** [comment]
The flags we use for this command (`--no-git-tag-version --new-version`) aren't valid for the new `version` command anymore. See: https://yarnpkg.com/cli/version

I think the new command we'd want is something like `yarn version "${version}"` but I haven't tested it. Specifically I'm unsure if that would create a git tag or not. We might need to use `--deferred` and ignore the resulting staging file?

**Review by Gudahtt — DISMISSED** [review]
LGTM!

**Review by brad-decker — DISMISSED** [review]

**Review by danjm — DISMISSED** [review]

**Comment by brad-decker** [comment]
Uhhh... i'm looking into this. These changes should not be dropping coverage at all.

**Comment by brad-decker** [comment]
Mocha is included .yarn as a coverage target... looks like this impacting codecov too.

**Comment by brad-decker** [comment]
Pushed a commit with changes. Ironically the 'lines' doesn't change just statements, branches and functions.

**Review by danjm — APPROVED** [review]

**Review by Gudahtt — APPROVED** [review]

**Pull request merged**
